from common_integrated_v2 import *

r=body_fixed()
write(RUN/'BODY-binding-audit-v2.json',dict(receipt_sha256=sha(RUN/'public-body-receipt-v2.json'),
    report_sha256=r['report_sha256'],fixed_rows=1582,all_raw_hashes_match=True,
    required_reader_corrections=r['required_reader_corrections'],
    permitted_future_integration=r['permitted_future_integration'],integration_authorized=True))
for row in load(RUN/'BODY-review-inputs-v2.json')['rows']:
    p=Path(row['path'])
    if p.resolve() in {x.resolve() for x in OWN_METADATA}:
        snapshot=RUN/'snapshots'/('BODY-reviewed--'+p.relative_to(ROOT).as_posix().replace('/','--')+'.raw')
        write(snapshot,p.read_bytes())
        assert sha(snapshot)==row['sha256']
for p,addition in [('BanditRLProof.lean',b'\nimport BanditRLProof.OnlineGuessingRandomizedIID\n'),
        ('Tests.lean',b'\nimport Tests.OnlineGuessingRandomizedIIDCanary\n')]:
    before=(RUN/'snapshots'/('CONTRACT-reviewed--'+p+'.raw')).read_bytes()
    assert Path(p).read_bytes()==before
    Path(p).write_bytes(before+addition)

delta=('Derived private-randomness and strict-past information results for the Chapter1 guessing game, '
    'printed pp.1-2/PDF13-14, equations(1.1)/(1.2). Seven producer/interface proofs and one definition '
    'are not seven printed source statements or a new regret rate. This covers arbitrary measurable private tapes '
    'independent of the WHOLE target process and predictions in subordinate pre-reveal information. '
    'It does not prove that every stochastic kernel or completed/augmented information model has this representation.')
model=('On a probability space, each target Y_t is measurable, identically distributed with Y_0, '
    'a.s. in[0,1], and the entire target family is jointly independent. The measurable private tape S is '
    'independent of the WHOLE infinite target process, not just each target separately. '
    'H_t is the comap sigma field generated by S and the strict-past tuple (Y_i)_{i<t}; H_s is contained in H_t for s<=t. '
    'A general prediction P_t is measurable in F_t contained in H_t and is a.s. feasible. '
    'The concrete policy pi_t(s,z) is jointly measurable and feasible for EVERY seed only when all past inputs are in[0,1]; '
    'no off-cube boundedness is assumed. Ambient measurability, square integrability and current-target independence are derived.')
metric=('B_T=min_{u in[0,1]} E[sum_{t<T}(u-Y_t)^2]=T Var(Y_0) is the minimum of expected FIXED loss, '
    'with comparator outside expectation. It is not the expected hindsight minimum. '
    'For the SAME stream and prefix, expected-fixed excess equals sum E[(P_t-E[Y_0])^2]>=0. '
    'All private randomness is integrated in the same probability law; no pathwise nonnegative excess claim follows.')
index=('At Lean t=0, the past is empty but the private tape may be used. '
    'Source rounds1..T correspond to Lean0..T-1; T0 is a disclosed empty-prefix extension. '
    'Only finite-horizon identities and lower bounds are proved here; source asymptotic-success equivalence remains REQUIRED. '
    'No unknown-law upper learning rate, high-probability or almost-sure convergence assertion.')
proof=('First factor the joint law of S and a past/current pair and regroup it by measurable product associativity. '
    'Extract finite past/current blocks from joint IID targets and compose whole-process seed independence. '
    'This produces (S,Y_{<t}) independent of Y_t. Restricting its generated sigma field preserves independence. '
    'The actual joint policy is measurable in that field; countable a.s. target support produces legal histories and L2. '
    'The previous actual expected-fixed minimum and moment decomposition give the same-prefix sum-of-squares identity.')
validation=('Actual seven public proofs/one information definition and29 named canary proofs compile. '
    'A fair private bit times an infinite joint IID target process has target mean1/2 and variance1/4. '
    'The actual policy uses the bit at round0 and the latest past target thereafter; two-round expected excess is1/2. '
    'Both the explicit policy and the general subordinate-information endpoint are instantiated separately. '
    'Current Y_0 is proved not measurable in private-only H_0. The policy is unbounded off the legal cube. '
    'A four-atom XOR probability model proves all three pairwise independences but joint seed+past/current independence fails. '
    '55 actual selected kernel checks use standard axioms only (42 theorem-kind,13 definition-kind), '
    'including the actual probability and measurable class proof values;29 exact canary Props/nine whole fixtures, '
    'seven universal public proof type checks/three whole benchmark-information identities,36 native fences '
    'and26 actual compiled direct VALUE pairs pass separately. Native safe scans do not compile. '
    'Preserved failed proofs and audit-only repairs do not change the frozen v2 terminals.')
boundary=('Only this independent-private-tape/subordinate-information finite IID producer is supported by the current package. '
    'Distinct staged automated CONTRACT/BODY review is recorded; root/Tests/fullharness/shadow/contributor/sharedregistry/site/pixels/FINAL/native/draftPR are separate gates. '
    'No human/external/absolute-blind/model-runtime attestation or single-runtime enforcement of every workflow convention. '
    'All old source cards retain historical boundaries; this card extends the preceding deterministic core. '
    'Universal-kernel/completed-field full-source coverage audit and asymptotic-success equivalence remain required. '
    'Original16 Chapter1 source items/required proof total unknown(null), five old main-relative module audits unwaived, '
    'Chapter1open/Chapter2incomplete/Chapters3-16unenumerated/necessaryappendicesrequired/totalGoalACTIVE. '
    'Stacked on OPENdraft/unmergedPR194 exact b08f8312259ae10032b6318060e18911532d4610, '
    'base codex/research-online-iid; canonicalmain6847 has not received this stack. No merge/deploy/live/retirement claim.')
math=r'\begin{aligned}S&\perp(Y_t)_{t\ge0},\quad\mathcal F_t\subseteq\mathcal H_t=\sigma(S,Y_{<t}),\\P_t&=\pi_t(S,Y_{<t}),\quad m=\mathbb E[Y_0],\\B_T&=\min_{u\in[0,1]}\mathbb E[\sum_{t<T}(u-Y_t)^2]=T\operatorname{Var}(Y_0),\\\mathcal E_T(P)&=\mathbb E[\sum_{t<T}(P_t-Y_t)^2]-B_T\\&=\sum_{t<T}\mathbb E[(P_t-m)^2]\ge0.\end{aligned}'
card=dict(label='Private randomness and strict-past IID information',pages='pp.1-2 (PDF13-14)',pdf_page=13,
    url='https://arxiv.org/pdf/1912.13213v10',math=math,plain=proof,fallback=proof,relationship=delta,
    contract=dict(model=model,assumptions=model,parameters=index,regret=metric,guarantee=proof+' '+validation+' '+boundary),
    local_status=dict(status='compiled',label='Private-seed IID proofs compiled',boundary=delta+' '+boundary))
p=Path('website/content/readings.json');data=load(p)
row=next(x for x in data['readings'] if x['slug']==ROUTE)
assert len(row['source_theorems'])==12
row['source_theorems'].append(card)
p.write_bytes((json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
notes=[
    ('independent_private_seed_pair','Regroup independent seed and target blocks',
     r'S\perp(X,Y),\ X\perp Y\ \Longrightarrow\ (S,X)\perp Y.',
     'Use joint-law product factorization and measurable associativity. Individual seed-target independence is insufficient.',[]),
    ('private_seed_past_independent','Derive private-seed and strict-past independence',
     r'(S,Y_{<t})\perp Y_t.',
     'Extract finite disjoint IID blocks and compose seed independence of the whole process.',['independent_private_seed_pair']),
    ('privateSeedPastInformation_monotone','Generated information grows with the strict past',
     r'\mathcal H_s\subseteq\mathcal H_t\quad(s\le t).',
     'Measurably restrict the longer past tuple. This structural result needs no probability or IID assumptions.',['privateSeedPastInformation']),
    ('predictable_private_seed_independent','Subordinate pre-reveal predictions inherit independence',
     r'P_t\text{ measurable in }\mathcal F_t\subseteq\mathcal H_t\ \Longrightarrow\ P_t\perp Y_t.',
     'Weaken the produced sigma-field independence; future-correlated side information is not allowed.',['private_seed_past_independent']),
    ('randomized_history_policy_independent','The actual joint private-seed policy cannot see the current target',
     r'\pi_t(S,Y_{<t})\perp Y_t.',
     'Compose the produced joint block with the actual jointly measurable policy. Round0 may depend on the independent seed.',['private_seed_past_independent']),
    ('predictable_private_seed_expectedFixed_excess','Predictable-information traces produce the fixed benchmark lower bound',
     r'\mathcal E_T(P)=\sum_{t<T}\mathbb E[(P_t-m)^2]\ge0.',
     'Derive ambient measurability, L2 and current independence from the subordinate information and a.s. feasibility, then reuse the actual fixed minimum.',
     ['predictable_private_seed_independent','expectedFixedMinimum_eq_variance','iid_cumulative_prediction_decomposition']),
    ('randomized_history_policy_expectedFixed_excess','Instantiate the lower bound with a real private-seed history policy',
     r'P_t=\pi_t(S,Y_{<t}),\quad\mathcal E_T(P)=\sum_{t<T}\mathbb E[(P_t-m)^2]\ge0.',
     'The real trajectory is measurable in generated information; a.s. target support produces legal histories. Instantiate the general endpoint, rather than assume its regret or independence conclusion.',
     ['predictable_private_seed_expectedFixed_excess','privateSeedPastInformation'])]
p=Path('website/content/highlights.json');data=load(p)
for order,(name,title,formula,idea,parents) in enumerate(notes,78):
    full=PRE+name
    assert not any(x['full_name']==full for x in data['highlights'])
    data['highlights'].append(dict(full_name=full,title=title,chapter=ROUTE,featured=False,teaching_order=order,
        plain=idea,math=formula,intuition='Whole-process seed independence and strict-past information preserve causality.',
        why='Include genuine private randomness in the shared expected-fixed IID benchmark.',position=delta,proof_idea=idea,
        lean_notes=model+' '+metric+' '+index+' '+validation+' '+boundary,dependencies=[PRE+n for n in parents]))
p.write_bytes((json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
p=Path('website/content/chapters.json');data=load(p);row=next(x for x in data['chapters'] if x['slug']==ROUTE)
assert PUBLIC.as_posix() not in row['module_globs']
row['module_globs'].append(PUBLIC.as_posix())
row['completion_blockers']=[boundary,'Full Chapter1, source asymptotic-success and five old main-relative audits remain required.']
row['open_gaps']=[boundary,'No universal-kernel/completed-field coverage, source asymptotic success or full chapter acceptance from this finite producer.']
p.write_bytes((json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
names=[x['name'] for x in load(CONTRACT/'targets-v2.json')['rows']]+[PRE+'privateSeedPastInformation']
reuse=[PRE+x for x in ['expectedFixedMinimum','expectedFixedRegret','expectedFixedMinimum_eq_variance',
    'iid_cumulative_prediction_decomposition','independent_prediction_square']]+[
    'ProbabilityTheory.iIndepFun.indepFun_finset','ProbabilityTheory.indepFun_iff_map_prod_eq_prod_map_map',
    'MeasureTheory.Measure.prodAssoc_prod','ProbabilityTheory.indep_of_indep_of_le_left',
    'MeasureTheory.memLp_of_bounded']
m=dict(schema_version='2.0',id=TASK,route='online-learning/chapter-1',frontier_cell=ROUTE,source_facing=True,
    source=dict(kind='book',title='Online Learning: A Modern Introduction Using Convex Optimization',
        version='arXiv:1912.13213v10,2026-06-21; SHA '+PDF_SHA,
        anchor='printed pp.1-2 / PDF pp.13-14: guessing-game IID square loss, equations(1.1)/(1.2), private randomness and strict-past information',url=card['url']),
    target=delta+' '+boundary,affected_files=[PUBLIC.as_posix(),'BanditRLProof.lean',
        'website/content/readings.json','website/content/highlights.json','website/content/chapters.json'],declarations=names,
    reuse_plan=dict(classification='missing',decision='new_shared',
        searched_existing=['Actual native shared declaration/card/API retrieval and compiled typed mathlib checks in RUN.'],
        reused_declarations=reuse,new_shared_declarations=names,
        known_consumers=[PRE+'randomized_history_policy_expectedFixed_excess',TEST+'actual_two_round_excess'],
        planned_consumers=[],no_duplicate_wrapper=True,
        decision_reason='Produce the missing joint private-seed/current independence and real policy/subordinate-information cumulative endpoint once in the shared project, reusing the actual fixed benchmark and pinned product/independence APIs.'),
    reader_contract=dict(source_anchor_visible=True,natural_language_formula_proof=True,hidden_assumptions_visible=True,
        source_vs_lean_delta_visible=True,lean_folded=True,dependencies_visible=True,remaining_boundary_visible=True),
    semantic_roundtrip=dict(required=True,status='source-reviewed',formalizer='/root',blind_decoder='/root/osd_blind',
        source_reviewer='/root/source_reviewer',verdict=r['verdict'],remaining_semantic_delta=delta+' CONTRACT/BODY accepted; R1-R7/FINAL pending.'),
    graph_contribution=dict(lean_graph='new-node',overview_graph='updated',functor_hypergraph='none-found-with-reason',
        functor_reason='One fixed scalar IID game and its probability-information producers, not composition of arbitrary learning settings.',
        focus_targets=[PRE+'private_seed_past_independent',PRE+'predictable_private_seed_expectedFixed_excess',PRE+'randomized_history_policy_expectedFixed_excess'],
        visual_review='55 actual selected compiled nodes/42 theorem-kind13 definition-kind/26 direct VALUE pairs; shared registry/current pixels pending.',
        edge_semantics='formal-solid; overlays-dashed'),
    progress_updates=dict(teaching_route='updated: one source-qualified private-seed card, seven proof notes and own module mapping; all prior cards/notes/links preserved.',
        banditrlwiki='no-change-with-reason: no new Bandit setting.',results_ledger='updated: seven frozen causal terminals compile; original source16/proof totalnull/fullC1 remain open.',
        roadmap='no-change-with-reason: persistent whole-book sequential Goal active and globalSGB unchanged.',
        website_surfaces=['website/content/readings.json','website/content/highlights.json','website/content/chapters.json']),
    truth_boundary=delta+' '+model+' '+metric+' '+index+' '+boundary,
    verification=dict(focused_checks=[validation],bandit_check='Actual combined root/Tests/full harness still required.',
        site_build='Applicable clean local build after combined Lean gate required.',site_check='Preserve every prior shared registry ID/URL/statementHash; current reader/pixels gate required.',
        independent_review='Distinct staged CONTRACT/BODY accepted-with-explicit-delta; exact R1-R7/FINAL still required.',
        owned_test_files=[CANARY.as_posix()],owned_test_root_files=['Tests.lean']),
    contributor=dict(name='Codex for Ji Cheng',role='Formalizer/shared integration; distinct required staged automated decoder and source reviewer'))
MANIFEST.write_bytes((json.dumps(m,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
fixed_integrated()
write(RUN/'reader-integrated-bindings-v2.json',dict(public_sha256=sha(PUBLIC),canary_sha256=sha(CANARY),
    BODY_receipt_sha256=sha(RUN/'public-body-receipt-v2.json'),old_source_cards=12,new_source_cards=1,new_proof_notes=7,
    new_shared_public_nodes=8,old_links_preserved=True,required_reader_corrections=r['required_reader_corrections'],
    chapter_complete=False,goal_complete=False))
print('BODY accepted raw bindings verified; exact own shared root/Test imports and source-qualified reader mapping integrated. Combined gates pending.')
