import BanditRLProof.RL.FiniteHorizonAdaptiveCumulativeUCBVIChargeSummation
import BanditRLProof.RL.FiniteHorizonStageVisitFactorization

/-!
# Same-source generated-batch alignment for recurrent UCBVI-CH

This module proves, rather than assumes, that each successor batch on the
adaptive `Kernel.trajMeasure` is the literal image of a trajectory generated
by the deterministic recurrent policy computed from its strict prefix.
-/

open MeasureTheory
open scoped BigOperators ENNReal ProbabilityTheory

universe u v

namespace BanditRLProof.FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace MDP

omit [Nonempty State] [Nonempty Action] in
theorem measurable_trajectoryStateAt
    (mdp : MDP State Action) (stage : Fin mdp.horizon) :
    Measurable (fun trajectory : State × StepTrace Action State mdp.horizon =>
      mdp.trajectoryStateAt trajectory stage) := by
  unfold trajectoryStateAt
  split_ifs
  · exact measurable_fst
  · exact measurable_snd.comp
      ((measurable_pi_apply _).comp measurable_snd)

end MDP

namespace DeterministicMarkovPolicyTable

/-- A trajectory generated by a deterministic table records exactly that
table's action at every chronological stage, almost surely. -/
theorem trajectoryMeasure_action_eq_table_ae
    {mdp : MDP State Action} (table : DeterministicMarkovPolicyTable mdp)
    (initialState : Measure State) [IsProbabilityMeasure initialState] :
    ∀ᵐ trajectory ∂table.toMarkovPolicy.trajectoryMeasure initialState,
      ∀ stage : Fin mdp.horizon,
        (mdp.episodeStepOfTrajectory trajectory stage).action =
          table stage (mdp.trajectoryStateAt trajectory stage) := by
  rw [ae_all_iff]
  intro stage
  rw [ae_iff]
  have hbad :
      {trajectory : State × StepTrace Action State mdp.horizon |
          ¬(mdp.episodeStepOfTrajectory trajectory stage).action =
            table stage (mdp.trajectoryStateAt trajectory stage)} =
        ⋃ state : State, ⋃ action : Action,
          if action ≠ table stage state then
            {trajectory |
              (mdp.episodeStepOfTrajectory trajectory stage).state = state ∧
                (mdp.episodeStepOfTrajectory trajectory stage).action = action}
          else ∅ := by
    ext trajectory
    simp only [Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_ite_empty_right,
      Set.mem_empty_iff_false, and_false]
    constructor
    · intro hne
      refine ⟨(mdp.episodeStepOfTrajectory trajectory stage).state,
        (mdp.episodeStepOfTrajectory trajectory stage).action, ?_⟩
      have hstate :
          mdp.trajectoryStateAt trajectory stage =
            (mdp.episodeStepOfTrajectory trajectory stage).state := by
        simp [MDP.episodeStepOfTrajectory]
      simpa [hstate] using hne
    · rintro ⟨state, action, hne, hstate, haction⟩
      have htrajectoryState : mdp.trajectoryStateAt trajectory stage = state := by
        simpa [MDP.episodeStepOfTrajectory] using hstate
      simpa [haction, htrajectoryState] using hne
  rw [hbad]
  apply measure_iUnion_null
  intro state
  apply measure_iUnion_null
  intro action
  by_cases hne : action ≠ table stage state
  · rw [if_pos hne]
    rw [table.toMarkovPolicy.trajectoryMeasure_visitEvent_eq_stateEvent_mul_action
      initialState stage state action]
    simp [DeterministicMarkovPolicyTable.toMarkovPolicy,
      ProbabilityTheory.Kernel.deterministic_apply, hne]
  · rw [if_neg hne]
    exact measure_empty

end DeterministicMarkovPolicyTable

namespace AdaptiveCumulativeHoeffdingUCBVI

/-- Under the one-episode mapped batch law, every reconstructed state/action
record coincides with the genuine generated trajectory and deterministic
table. -/
theorem iidEpisodeBatchMeasure_successorBatchAligned_ae
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (defaultState : State) (table : DeterministicMarkovPolicyTable mdp)
    (hhorizon : 0 < mdp.horizon) :
    ∀ᵐ batch ∂table.toMarkovPolicy.iidEpisodeBatchMeasure initialState 1,
      let reconstructed : State × StepTrace Action State mdp.horizon :=
        (batch.reconstructedInitialState defaultState,
          batch.reconstructedStepTrace)
      ∀ stage : Fin mdp.horizon,
        (batch 0 stage).state = mdp.trajectoryStateAt reconstructed stage ∧
          (batch 0 stage).action =
            table stage (mdp.trajectoryStateAt reconstructed stage) := by
  let trajectoryLaw := table.toMarkovPolicy.iidTrajectoryFamilyMeasure initialState 1
  let batchMap := mdp.episodeBatchOfTrajectories 1
  have haction :
      ∀ᵐ trajectories ∂trajectoryLaw,
        ∀ stage : Fin mdp.horizon,
          (mdp.episodeStepOfTrajectory (trajectories 0) stage).action =
            table stage
              (mdp.trajectoryStateAt (trajectories 0) stage) := by
    have hsingle := table.trajectoryMeasure_action_eq_table_ae initialState
    have heval : trajectoryLaw.map (Function.eval (0 : Fin 1)) =
        table.toMarkovPolicy.trajectoryMeasure initialState :=
      table.toMarkovPolicy.iidTrajectoryFamilyMeasure_map_eval initialState 0
    rw [← heval] at hsingle
    exact ae_of_ae_map (measurable_pi_apply (0 : Fin 1)).aemeasurable hsingle
  have hsource :
      ∀ᵐ trajectories ∂trajectoryLaw,
        let batch := batchMap trajectories
        let reconstructed : State × StepTrace Action State mdp.horizon :=
          (batch.reconstructedInitialState defaultState,
            batch.reconstructedStepTrace)
        ∀ stage : Fin mdp.horizon,
          (batch 0 stage).state = mdp.trajectoryStateAt reconstructed stage ∧
            (batch 0 stage).action =
              table stage (mdp.trajectoryStateAt reconstructed stage) := by
    filter_upwards [haction] with trajectories htrajectory
    have hinitial :
        EpisodeBatch.reconstructedInitialState defaultState
            (batchMap trajectories) = (trajectories 0).1 := by
      simp [batchMap, EpisodeBatch.reconstructedInitialState, hhorizon,
        MDP.episodeBatchOfTrajectories, MDP.episodeStepOfTrajectory,
        MDP.trajectoryStateAt]
    have htrace :
        EpisodeBatch.reconstructedStepTrace (batchMap trajectories) =
          (trajectories 0).2 := by
      funext stage
      simp [batchMap, EpisodeBatch.reconstructedStepTrace,
        MDP.episodeBatchOfTrajectories, MDP.episodeStepOfTrajectory]
    dsimp only
    intro stage
    constructor
    · simp [batchMap, hinitial, htrace, MDP.episodeBatchOfTrajectories,
        MDP.episodeStepOfTrajectory]
    · simpa [batchMap, hinitial, htrace, MDP.episodeBatchOfTrajectories,
        MDP.episodeStepOfTrajectory] using htrajectory stage
  unfold MarkovPolicy.iidEpisodeBatchMeasure
  have hreconstructed : Measurable
      (fun batch : EpisodeBatch mdp 1 =>
        (batch.reconstructedInitialState defaultState,
          batch.reconstructedStepTrace)) :=
    (EpisodeBatch.measurable_reconstructedInitialState defaultState).prodMk
      EpisodeBatch.measurable_reconstructedStepTrace
  have hstage (stage : Fin mdp.horizon) : MeasurableSet
      {batch : EpisodeBatch mdp 1 |
        (batch 0 stage).state = mdp.trajectoryStateAt
              (batch.reconstructedInitialState defaultState,
                batch.reconstructedStepTrace) stage ∧
          (batch 0 stage).action = table stage
            (mdp.trajectoryStateAt
              (batch.reconstructedInitialState defaultState,
                batch.reconstructedStepTrace) stage)} :=
    let hstep := (measurable_pi_apply stage).comp (measurable_pi_apply (0 : Fin 1))
    let hstate := EpisodeStep.measurable_state.comp hstep
    let haction := EpisodeStep.measurable_action.comp hstep
    let htrajectoryState : Measurable
        (fun batch : EpisodeBatch mdp 1 => mdp.trajectoryStateAt
          (batch.reconstructedInitialState defaultState,
            batch.reconstructedStepTrace) stage) := by
      exact (mdp.measurable_trajectoryStateAt stage).comp hreconstructed
    (measurableSet_eq_fun hstate htrajectoryState).inter
      (measurableSet_eq_fun haction
        ((measurable_of_finite (table stage)).comp htrajectoryState))
  apply (ae_map_iff
    (μ := trajectoryLaw)
    (mdp.measurable_episodeBatchOfTrajectories 1).aemeasurable ?_).2
  · exact hsource
  · simpa only [Set.iInter_setOf] using MeasurableSet.iInter hstage

/-- Every successor coordinate of the actual recurrent
`Kernel.trajMeasure` is aligned with the deterministic table computed from
that same trajectory's strict prefix. -/
theorem recurrentSource_trajectoryMeasure_successorBatchAligned_ae
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (defaultState : State) (episodes : Nat) (delta : Real)
    (hhorizon : 0 < mdp.horizon) (n : Nat) :
    ∀ᵐ trajectory ∂
        (recurrentSource mdp initialState defaultState episodes delta).trajectoryMeasure,
      SuccessorBatchAligned mdp defaultState episodes delta trajectory n := by
  let source := recurrentSource mdp initialState defaultState episodes delta
  let prefixMeasure := source.trajectoryMeasure.map (Preorder.frestrictLe n)
  let pairMap : EpisodeBatchTrajectory mdp 1 →
      EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 :=
    fun trajectory =>
      (Preorder.frestrictLe n trajectory, trajectory (n + 1))
  have hpairMap : Measurable pairMap := by fun_prop
  let tableOfPrefix : EpisodeBatchPrefix mdp 1 n →
      DeterministicMarkovPolicyTable mdp :=
    recurrentSuccessorTable defaultState
      (scale (State := State) (Action := Action) mdp episodes delta) n
  have htable : Measurable tableOfPrefix :=
    measurable_recurrentSuccessorTable defaultState
      (scale (State := State) (Action := Action) mdp episodes delta) n
  have hmeas : MeasurableSet
      {pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 |
        let reconstructed : State × StepTrace Action State mdp.horizon :=
          (pair.2.reconstructedInitialState defaultState,
            pair.2.reconstructedStepTrace)
        ∀ stage : Fin mdp.horizon,
          (pair.2 0 stage).state = mdp.trajectoryStateAt reconstructed stage ∧
            (pair.2 0 stage).action =
              tableOfPrefix pair.1 stage
                (mdp.trajectoryStateAt reconstructed stage)} := by
    have hstage (stage : Fin mdp.horizon) : MeasurableSet
        {pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 |
          (pair.2 0 stage).state = mdp.trajectoryStateAt
                (pair.2.reconstructedInitialState defaultState,
                  pair.2.reconstructedStepTrace) stage ∧
            (pair.2 0 stage).action = tableOfPrefix pair.1 stage
              (mdp.trajectoryStateAt
                (pair.2.reconstructedInitialState defaultState,
                  pair.2.reconstructedStepTrace) stage)} := by
      let hbatch0 : Measurable
          (fun pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 =>
            pair.2 (0 : Fin 1)) :=
        (measurable_pi_apply (0 : Fin 1)).comp measurable_snd
      let hstep : Measurable
          (fun pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 =>
            pair.2 (0 : Fin 1) stage) :=
        (measurable_pi_apply stage).comp hbatch0
      let hstate := EpisodeStep.measurable_state.comp hstep
      let haction := EpisodeStep.measurable_action.comp hstep
      let htrajectoryState : Measurable
        (fun pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 =>
            mdp.trajectoryStateAt
              (pair.2.reconstructedInitialState defaultState,
                pair.2.reconstructedStepTrace) stage) := by
        exact (mdp.measurable_trajectoryStateAt stage).comp
          (((EpisodeBatch.measurable_reconstructedInitialState defaultState).comp
            measurable_snd).prodMk
            (EpisodeBatch.measurable_reconstructedStepTrace.comp measurable_snd))
      have hstateEq := measurableSet_eq_fun hstate htrajectoryState
      have hactionPiece (state : State) : MeasurableSet
          {pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 |
            mdp.trajectoryStateAt
                (pair.2.reconstructedInitialState defaultState,
                  pair.2.reconstructedStepTrace) stage = state ∧
              (pair.2 0 stage).action = tableOfPrefix pair.1 stage state} := by
        have htableState : Measurable
            (fun pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 =>
              tableOfPrefix pair.1 stage state) :=
          (measurable_pi_apply state).comp
            ((measurable_pi_apply stage).comp (htable.comp measurable_fst))
        exact (measurableSet_eq_fun htrajectoryState measurable_const).inter
          (measurableSet_eq_fun haction htableState)
      have hactionEq : MeasurableSet
          {pair : EpisodeBatchPrefix mdp 1 n × EpisodeBatch mdp 1 |
            (pair.2 0 stage).action = tableOfPrefix pair.1 stage
              (mdp.trajectoryStateAt
                (pair.2.reconstructedInitialState defaultState,
                  pair.2.reconstructedStepTrace) stage)} := by
        have hunion := MeasurableSet.iUnion hactionPiece
        convert hunion using 1
        ext pair
        simp only [Set.mem_setOf_eq, Set.mem_iUnion]
        constructor
        · intro h
          exact ⟨mdp.trajectoryStateAt
            (pair.2.reconstructedInitialState defaultState,
              pair.2.reconstructedStepTrace) stage, rfl, h⟩
        · rintro ⟨state, hstateValue, hactionValue⟩
          simpa [hstateValue] using hactionValue
      exact hstateEq.inter hactionEq
    simpa only [Set.iInter_setOf] using MeasurableSet.iInter hstage
  have hpair : ∀ᵐ pair ∂prefixMeasure ⊗ₘ source.batchKernel n,
      let reconstructed : State × StepTrace Action State mdp.horizon :=
        (pair.2.reconstructedInitialState defaultState,
          pair.2.reconstructedStepTrace)
      ∀ stage : Fin mdp.horizon,
        (pair.2 0 stage).state = mdp.trajectoryStateAt reconstructed stage ∧
          (pair.2 0 stage).action = tableOfPrefix pair.1 stage
            (mdp.trajectoryStateAt reconstructed stage) := by
    apply Measure.ae_compProd_of_ae_ae hmeas
    exact Filter.Eventually.of_forall fun history => by
      rw [source.batchKernel_eq_iidEpisodeBatchMeasure]
      exact iidEpisodeBatchMeasure_successorBatchAligned_ae
        mdp initialState defaultState (tableOfPrefix history) hhorizon
  have hpair' := hpair
  rw [source.trajectoryMeasure_prefix_compProd n] at hpair'
  have hpull := ae_of_ae_map hpairMap.aemeasurable hpair'
  simpa [pairMap, tableOfPrefix, source, SuccessorBatchAligned,
    successorPolicyTable, successorPreviousQ, successorSummary,
    recurrentSource, recurrentSuccessorTable, prefixTransitionSummaries,
    adaptiveCumulativeEmpiricalModelStateAt] using hpull

/-- Countable conjunction of the same-source alignment certificates. -/
theorem recurrentSource_trajectoryMeasure_all_successorBatchAligned_ae
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (defaultState : State) (episodes : Nat) (delta : Real)
    (hhorizon : 0 < mdp.horizon) :
    ∀ᵐ trajectory ∂
        (recurrentSource mdp initialState defaultState episodes delta).trajectoryMeasure,
      ∀ n : Nat,
        SuccessorBatchAligned mdp defaultState episodes delta trajectory n := by
  rw [ae_all_iff]
  exact recurrentSource_trajectoryMeasure_successorBatchAligned_ae
    mdp initialState defaultState episodes delta hhorizon

end AdaptiveCumulativeHoeffdingUCBVI
end BanditRLProof.FiniteHorizonRL
