import BanditRLProof.RL.FiniteHorizonIIDMultiBatchCumulativeConfidenceRegret
import BanditRLProof.RewardTraceLaw

/-!
# Adaptive finite-horizon episode-batch laws

This module replaces the independent finite product of episode batches by an
Ionescu--Tulcea trajectory whose successor batch kernel may depend on the full
finite batch history.  A source records the selected Markov policy and the
exact equality between its generated iid batch law and the configured history
kernel.  The resulting trajectory exposes both the regular conditional law of
the next batch and a finite-horizon union bound for arbitrary measurable
adapted bad events.

This is a law and confidence-budget transport layer.  It does not yet prove
that an empirical optimistic-policy update is measurable, instantiate the bad
events with policy-dependent count radii, bound cumulative bonuses, or identify
the finite sum of expected regrets with realized online regret.
-/

open MeasureTheory
open scoped ENNReal ProbabilityTheory

universe u v

namespace BanditRLProof
namespace FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace EpisodeStep

/-- An episode step is inhabited whenever its state and action types are. -/
instance instNonempty : Nonempty (EpisodeStep State Action) := by
  classical
  exact ⟨{
    state := Classical.choice inferInstance
    action := Classical.choice inferInstance
    reward := 0
    nextState := Classical.choice inferInstance
  }⟩

end EpisodeStep

/-- Finite history through batch coordinate `n`. -/
abbrev EpisodeBatchPrefix (mdp : MDP State Action) (episodes n : Nat) :=
  (i : Finset.Iic n) -> EpisodeBatch mdp episodes

/-- Infinite batch trajectory used by the adaptive Ionescu--Tulcea law. -/
abbrev EpisodeBatchTrajectory (mdp : MDP State Action) (episodes : Nat) :=
  Nat -> EpisodeBatch mdp episodes

/--
An adaptive batch source.

Coordinate zero is generated by `initialPolicy`.  After observing the prefix
through coordinate `n`, `successorPolicy n history` selects the policy for
coordinate `n + 1`.  `batchKernel_eq_iidEpisodeBatchMeasure` is the exact law
transport contract: it also certifies that the history-indexed family is a
measurable Markov kernel rather than merely a pointwise family of measures.
-/
structure AdaptiveEpisodeBatchSource
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState] (episodes : Nat) where
  initialPolicy : MarkovPolicy mdp
  successorPolicy : (n : Nat) -> EpisodeBatchPrefix mdp episodes n ->
    MarkovPolicy mdp
  batchKernel : (n : Nat) ->
    ProbabilityTheory.Kernel (EpisodeBatchPrefix mdp episodes n)
      (EpisodeBatch mdp episodes)
  batchKernel_isMarkov : forall n,
    ProbabilityTheory.IsMarkovKernel (batchKernel n)
  batchKernel_eq_iidEpisodeBatchMeasure : forall n history,
    batchKernel n history =
      (successorPolicy n history).iidEpisodeBatchMeasure initialState episodes

namespace AdaptiveEpisodeBatchSource

instance instBatchKernelIsMarkov
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes) (n : Nat) :
    ProbabilityTheory.IsMarkovKernel (source.batchKernel n) :=
  source.batchKernel_isMarkov n

/-- The adaptive infinite batch-trajectory law. -/
noncomputable def trajectoryMeasure
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes) :
    Measure (EpisodeBatchTrajectory mdp episodes) :=
  ProbabilityTheory.Kernel.trajMeasure
    (X := fun _ : Nat => EpisodeBatch mdp episodes)
    (source.initialPolicy.iidEpisodeBatchMeasure initialState episodes)
    source.batchKernel

instance instTrajectoryMeasureIsProbabilityMeasure
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes) :
    IsProbabilityMeasure source.trajectoryMeasure := by
  unfold trajectoryMeasure
  infer_instance

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/-- Coordinate zero has the batch law of the configured initial policy. -/
theorem trajectoryMeasure_map_eval_zero
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes) :
    source.trajectoryMeasure.map (Function.eval 0) =
      source.initialPolicy.iidEpisodeBatchMeasure initialState episodes := by
  unfold trajectoryMeasure
  exact RewardKernel.trajMeasure_map_eval_zero
    (X := fun _ : Nat => EpisodeBatch mdp episodes)
    (source.initialPolicy.iidEpisodeBatchMeasure initialState episodes)
    source.batchKernel

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/--
Every successor prefix/next-batch marginal is the compProd of the prefix law
and the configured adaptive batch kernel.
-/
theorem trajectoryMeasure_prefix_compProd
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (n : Nat) :
    source.trajectoryMeasure.map (Preorder.frestrictLe n) ⊗ₘ
        source.batchKernel n =
      source.trajectoryMeasure.map
        (fun trajectory =>
          (Preorder.frestrictLe n trajectory, trajectory (n + 1))) := by
  unfold trajectoryMeasure
  exact
    ProbabilityTheory.Kernel.map_frestrictLe_trajMeasure_compProd_eq_map_trajMeasure
      (X := fun _ : Nat => EpisodeBatch mdp episodes)
      (μ₀ := source.initialPolicy.iidEpisodeBatchMeasure initialState episodes)
      (κ := source.batchKernel) (a := n)

omit [DecidableEq State] [DecidableEq Action] in
/--
The next batch conditioned on the full finite prefix has the configured
history-dependent Markov kernel.
-/
theorem trajectoryMeasure_condDistrib
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    [StandardBorelSpace (EpisodeBatch mdp episodes)]
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (n : Nat) :
    ProbabilityTheory.condDistrib
        (fun trajectory : EpisodeBatchTrajectory mdp episodes =>
          trajectory (n + 1))
        (Preorder.frestrictLe n) source.trajectoryMeasure =ᶠ[
          ae (source.trajectoryMeasure.map (Preorder.frestrictLe n))]
      source.batchKernel n := by
  unfold trajectoryMeasure
  exact ProbabilityTheory.Kernel.condDistrib_trajMeasure
    (X := fun _ : Nat => EpisodeBatch mdp episodes)
    (μ₀ := source.initialPolicy.iidEpisodeBatchMeasure initialState episodes)
    (κ := source.batchKernel) (a := n)

omit [DecidableEq State] [DecidableEq Action] in
/--
The next batch conditioned on the finite prefix is exactly the generated iid
batch law of the policy selected from that prefix.
-/
theorem trajectoryMeasure_condDistrib_eq_iidEpisodeBatchMeasure
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    [StandardBorelSpace (EpisodeBatch mdp episodes)]
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (n : Nat) :
    ProbabilityTheory.condDistrib
        (fun trajectory : EpisodeBatchTrajectory mdp episodes =>
          trajectory (n + 1))
        (Preorder.frestrictLe n) source.trajectoryMeasure =ᶠ[
          ae (source.trajectoryMeasure.map (Preorder.frestrictLe n))]
      fun history =>
        (source.successorPolicy n history).iidEpisodeBatchMeasure
          initialState episodes := by
  filter_upwards [source.trajectoryMeasure_condDistrib n] with history hhistory
  calc
    ProbabilityTheory.condDistrib
          (fun trajectory : EpisodeBatchTrajectory mdp episodes =>
            trajectory (n + 1))
          (Preorder.frestrictLe n) source.trajectoryMeasure history =
        source.batchKernel n history := hhistory
    _ = (source.successorPolicy n history).iidEpisodeBatchMeasure
          initialState episodes :=
      source.batchKernel_eq_iidEpisodeBatchMeasure n history

/-- Pull an initial-coordinate event back to the adaptive trajectory. -/
def initialBadEvent
    {mdp : MDP State Action} {episodes : Nat}
    (bad : Set (EpisodeBatch mdp episodes)) :
    Set (EpisodeBatchTrajectory mdp episodes) :=
  (Function.eval 0) ⁻¹' bad

/-- Pull a prefix-dependent successor event back to the adaptive trajectory. -/
def successorBadEvent
    {mdp : MDP State Action} {episodes : Nat} (n : Nat)
    (bad : Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)) :
    Set (EpisodeBatchTrajectory mdp episodes) :=
  (fun trajectory =>
    (Preorder.frestrictLe n trajectory, trajectory (n + 1))) ⁻¹' bad

/-- Round-indexed adapted bad event, with a separate coordinate-zero event. -/
def roundBadEvent
    {mdp : MDP State Action} {episodes : Nat}
    (initialBad : Set (EpisodeBatch mdp episodes))
    (successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)) :
    Nat -> Set (EpisodeBatchTrajectory mdp episodes)
  | 0 => initialBadEvent initialBad
  | n + 1 => successorBadEvent n (successorBad n)

/-- Union of the first `rounds` adapted bad events. -/
def finiteHorizonBadEvent
    {mdp : MDP State Action} {episodes : Nat}
    (rounds : Nat)
    (initialBad : Set (EpisodeBatch mdp episodes))
    (successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)) :
    Set (EpisodeBatchTrajectory mdp episodes) :=
  ⋃ round : Fin rounds, roundBadEvent initialBad successorBad round

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Measurability of every pulled-back adapted round event. -/
theorem measurableSet_roundBadEvent
    {mdp : MDP State Action} {episodes : Nat}
    {initialBad : Set (EpisodeBatch mdp episodes)}
    {successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, MeasurableSet (successorBad n))
    (round : Nat) :
    MeasurableSet (roundBadEvent initialBad successorBad round) := by
  cases round with
  | zero =>
      exact hinitial.preimage (measurable_pi_apply 0)
  | succ n =>
      exact (hsuccessor n).preimage (by fun_prop)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Measurability of the finite adapted bad-event union. -/
theorem measurableSet_finiteHorizonBadEvent
    {mdp : MDP State Action} {episodes rounds : Nat}
    {initialBad : Set (EpisodeBatch mdp episodes)}
    {successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (successorBad n)) :
    MeasurableSet
      (finiteHorizonBadEvent rounds initialBad successorBad) := by
  refine MeasurableSet.iUnion fun round => ?_
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          exact hinitial.preimage (measurable_pi_apply 0)
      | succ n =>
          exact (hsuccessor n hvalue).preimage (by fun_prop)

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/-- Exact mass of a pulled-back coordinate-zero event. -/
theorem trajectoryMeasure_initialBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    {bad : Set (EpisodeBatch mdp episodes)} (hbad : MeasurableSet bad) :
    source.trajectoryMeasure (initialBadEvent bad) =
      source.initialPolicy.iidEpisodeBatchMeasure initialState episodes bad := by
  change source.trajectoryMeasure ((Function.eval 0) ⁻¹' bad) = _
  rw [← Measure.map_apply (measurable_pi_apply 0) hbad]
  rw [source.trajectoryMeasure_map_eval_zero]

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/--
An adapted successor event inherits a uniform bound on every history fiber.
-/
theorem trajectoryMeasure_successorBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (n : Nat)
    {bad : Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (hbad : MeasurableSet bad) (budget : ENNReal)
    (hfiber : forall history,
      source.batchKernel n history (Prod.mk history ⁻¹' bad) <= budget) :
    source.trajectoryMeasure (successorBadEvent n bad) <= budget := by
  let prefixMeasure :=
    source.trajectoryMeasure.map (Preorder.frestrictLe n)
  let pairMap : EpisodeBatchTrajectory mdp episodes ->
      EpisodeBatchPrefix mdp episodes n × EpisodeBatch mdp episodes :=
    fun trajectory =>
      (Preorder.frestrictLe n trajectory, trajectory (n + 1))
  have hpairMap : Measurable pairMap := by fun_prop
  haveI : IsProbabilityMeasure prefixMeasure := by
    dsimp only [prefixMeasure]
    exact Measure.isProbabilityMeasure_map (by fun_prop)
  calc
    source.trajectoryMeasure (successorBadEvent n bad) =
        source.trajectoryMeasure.map pairMap bad := by
      rw [Measure.map_apply hpairMap hbad]
      rfl
    _ = (prefixMeasure ⊗ₘ source.batchKernel n) bad := by
      rw [source.trajectoryMeasure_prefix_compProd n]
    _ = ∫⁻ history, source.batchKernel n history
          (Prod.mk history ⁻¹' bad) ∂prefixMeasure :=
      Measure.compProd_apply hbad
    _ <= ∫⁻ _history, budget ∂prefixMeasure :=
      lintegral_mono hfiber
    _ = budget := by simp [prefixMeasure]

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/-- Every adapted round event inherits the supplied local budget. -/
theorem trajectoryMeasure_roundBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    {initialBad : Set (EpisodeBatch mdp episodes)}
    {successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (rounds : Nat)
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (successorBad n))
    (budget : ENNReal)
    (hinitial_le :
      source.initialPolicy.iidEpisodeBatchMeasure initialState episodes
        initialBad <= budget)
    (hsuccessor_le : forall n, n + 1 < rounds -> forall history,
      source.batchKernel n history
        (Prod.mk history ⁻¹' successorBad n) <= budget)
    (round : Fin rounds) :
    source.trajectoryMeasure
        (roundBadEvent initialBad successorBad round) <= budget := by
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          change source.trajectoryMeasure (initialBadEvent initialBad) <= budget
          rw [source.trajectoryMeasure_initialBadEvent hinitial]
          exact hinitial_le
      | succ n =>
          exact source.trajectoryMeasure_successorBadEvent_le n
            (hsuccessor n hvalue) budget (hsuccessor_le n hvalue)

omit [DecidableEq State] [DecidableEq Action]
    [Nonempty State] [Nonempty Action] in
/--
Finite-horizon adaptive union bound with equal confidence shares
`delta / rounds`.  Independence between batches is not assumed.
-/
theorem trajectoryMeasure_finiteHorizonBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (hrounds : 0 < rounds) (delta : Real)
    {initialBad : Set (EpisodeBatch mdp episodes)}
    {successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (successorBad n))
    (hinitial_le :
      source.initialPolicy.iidEpisodeBatchMeasure initialState episodes
          initialBad <=
        ENNReal.ofReal (multiBatchLocalDelta rounds delta))
    (hsuccessor_le : forall n, n + 1 < rounds -> forall history,
      source.batchKernel n history
          (Prod.mk history ⁻¹' successorBad n) <=
        ENNReal.ofReal (multiBatchLocalDelta rounds delta)) :
    source.trajectoryMeasure
        (finiteHorizonBadEvent rounds initialBad successorBad) <=
      ENNReal.ofReal delta := by
  letI : Nonempty (Fin rounds) := ⟨⟨0, hrounds⟩⟩
  simpa [finiteHorizonBadEvent, multiBatchLocalDelta] using
    (ProbabilityUnionBound.measure_biUnion_finset_le_of_uniform
      source.trajectoryMeasure (Finset.univ : Finset (Fin rounds))
      Finset.univ_nonempty delta
      (fun round : Fin rounds =>
        roundBadEvent initialBad successorBad round)
      (fun round _ => by
        simpa [multiBatchLocalDelta] using
          source.trajectoryMeasure_roundBadEvent_le rounds hinitial hsuccessor
            (ENNReal.ofReal (multiBatchLocalDelta rounds delta))
            hinitial_le hsuccessor_le round))

omit [DecidableEq State] [DecidableEq Action] in
/--
Terminal adaptive law-and-budget package: every successor conditional law is
the generated iid batch law of the history-selected policy, and arbitrary
measurable adapted local events obey one global finite-horizon delta budget.
-/
theorem trajectoryMeasure_conditionalLaw_and_finiteHorizonBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    [StandardBorelSpace (EpisodeBatch mdp episodes)]
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (hrounds : 0 < rounds) (delta : Real)
    {initialBad : Set (EpisodeBatch mdp episodes)}
    {successorBad : (n : Nat) -> Set (EpisodeBatchPrefix mdp episodes n ×
      EpisodeBatch mdp episodes)}
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (successorBad n))
    (hinitial_le :
      source.initialPolicy.iidEpisodeBatchMeasure initialState episodes
          initialBad <=
        ENNReal.ofReal (multiBatchLocalDelta rounds delta))
    (hsuccessor_le : forall n, n + 1 < rounds -> forall history,
      source.batchKernel n history
          (Prod.mk history ⁻¹' successorBad n) <=
        ENNReal.ofReal (multiBatchLocalDelta rounds delta)) :
    (forall n,
      ProbabilityTheory.condDistrib
          (fun trajectory : EpisodeBatchTrajectory mdp episodes =>
            trajectory (n + 1))
          (Preorder.frestrictLe n) source.trajectoryMeasure =ᶠ[
            ae (source.trajectoryMeasure.map (Preorder.frestrictLe n))]
        fun history =>
          (source.successorPolicy n history).iidEpisodeBatchMeasure
            initialState episodes) ∧
    MeasurableSet
      (finiteHorizonBadEvent rounds initialBad successorBad) ∧
    source.trajectoryMeasure
        (finiteHorizonBadEvent rounds initialBad successorBad) <=
      ENNReal.ofReal delta := by
  exact ⟨source.trajectoryMeasure_condDistrib_eq_iidEpisodeBatchMeasure,
    measurableSet_finiteHorizonBadEvent hinitial hsuccessor,
    source.trajectoryMeasure_finiteHorizonBadEvent_le rounds hrounds delta
      hinitial hsuccessor hinitial_le hsuccessor_le⟩

/-- Count-confidence event for the initial policy's coordinate-zero batch. -/
def initialSimultaneousCountBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (delta : Real) : Set (EpisodeBatch mdp episodes) :=
  source.initialPolicy.simultaneousCountBadEvent initialState episodes
    (multiBatchLocalDelta rounds delta)

/--
Prefix/next-batch count event for the policy selected from that prefix.
-/
def successorSimultaneousCountBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (delta : Real) (n : Nat) :
    Set (EpisodeBatchPrefix mdp episodes n × EpisodeBatch mdp episodes) :=
  {pair | pair.2 ∈
    (source.successorPolicy n pair.1).simultaneousCountBadEvent
      initialState episodes (multiBatchLocalDelta rounds delta)}

/--
The finite-horizon union of initial and history-selected simultaneous count
events on the adaptive batch trajectory.
-/
def adaptiveSimultaneousCountBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (delta : Real) :
    Set (EpisodeBatchTrajectory mdp episodes) :=
  finiteHorizonBadEvent rounds
    (source.initialSimultaneousCountBadEvent rounds delta)
    (source.successorSimultaneousCountBadEvent rounds delta)

/-- Policy used at a batch coordinate of one adaptive trajectory. -/
def policyAt
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (trajectory : EpisodeBatchTrajectory mdp episodes) : Nat -> MarkovPolicy mdp
  | 0 => source.initialPolicy
  | n + 1 => source.successorPolicy n (Preorder.frestrictLe n trajectory)

omit [Nonempty State] [Nonempty Action] in
/--
The initial count event receives the common local confidence share.
-/
theorem initialSimultaneousCountBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (hrounds : 0 < rounds)
    (hepisodes : 0 < episodes) (delta : Real) (hdelta : 0 < delta)
    (hdelta_le_one : delta <= 1) :
    source.initialPolicy.iidEpisodeBatchMeasure initialState episodes
        (source.initialSimultaneousCountBadEvent rounds delta) <=
      ENNReal.ofReal (multiBatchLocalDelta rounds delta) := by
  have hroundsReal : 0 < (rounds : Real) := Nat.cast_pos.mpr hrounds
  have hroundsOne : (1 : Real) <= (rounds : Real) := by
    exact_mod_cast hrounds
  have hlocal_pos : 0 < multiBatchLocalDelta rounds delta :=
    div_pos hdelta hroundsReal
  have hlocal_le_one : multiBatchLocalDelta rounds delta <= 1 := by
    unfold multiBatchLocalDelta
    exact (div_le_one hroundsReal).2 (hdelta_le_one.trans hroundsOne)
  exact source.initialPolicy.iidEpisodeBatch_simultaneousCountBadEvent_le
    initialState episodes hepisodes (multiBatchLocalDelta rounds delta)
      hlocal_pos hlocal_le_one

omit [Nonempty State] [Nonempty Action] in
/--
Every history fiber of the selected-policy successor count event receives the
same local confidence share.
-/
theorem successorSimultaneousCountBadEvent_fiber_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (hrounds : 0 < rounds)
    (hepisodes : 0 < episodes) (delta : Real) (hdelta : 0 < delta)
    (hdelta_le_one : delta <= 1) (n : Nat)
    (history : EpisodeBatchPrefix mdp episodes n) :
    source.batchKernel n history
        (Prod.mk history ⁻¹'
          source.successorSimultaneousCountBadEvent rounds delta n) <=
      ENNReal.ofReal (multiBatchLocalDelta rounds delta) := by
  have hroundsReal : 0 < (rounds : Real) := Nat.cast_pos.mpr hrounds
  have hroundsOne : (1 : Real) <= (rounds : Real) := by
    exact_mod_cast hrounds
  have hlocal_pos : 0 < multiBatchLocalDelta rounds delta :=
    div_pos hdelta hroundsReal
  have hlocal_le_one : multiBatchLocalDelta rounds delta <= 1 := by
    unfold multiBatchLocalDelta
    exact (div_le_one hroundsReal).2 (hdelta_le_one.trans hroundsOne)
  rw [source.batchKernel_eq_iidEpisodeBatchMeasure]
  change
    (source.successorPolicy n history).iidEpisodeBatchMeasure
        initialState episodes
        ((source.successorPolicy n history).simultaneousCountBadEvent
          initialState episodes (multiBatchLocalDelta rounds delta)) <= _
  exact
    (source.successorPolicy n history).iidEpisodeBatch_simultaneousCountBadEvent_le
      initialState episodes hepisodes (multiBatchLocalDelta rounds delta)
        hlocal_pos hlocal_le_one

omit [Nonempty State] [Nonempty Action] in
/-- Measurability of the adaptive simultaneous-count union. -/
theorem measurableSet_adaptiveSimultaneousCountBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (delta : Real)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet
        (source.successorSimultaneousCountBadEvent rounds delta n)) :
    MeasurableSet
      (source.adaptiveSimultaneousCountBadEvent rounds delta) := by
  exact measurableSet_finiteHorizonBadEvent
    (source.initialPolicy.measurableSet_simultaneousCountBadEvent
      initialState episodes (multiBatchLocalDelta rounds delta))
    hsuccessor

omit [Nonempty State] [Nonempty Action] in
/--
Adaptive global-delta simultaneous count confidence.  Outside one measurable
finite-horizon event, every realized batch satisfies the strict count
deviation bound relative to the policy selected from its preceding history.
-/
theorem trajectoryMeasure_adaptiveSimultaneousCountConfidence
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (source : AdaptiveEpisodeBatchSource mdp initialState episodes)
    (rounds : Nat) (hrounds : 0 < rounds)
    (hepisodes : 0 < episodes) (delta : Real) (hdelta : 0 < delta)
    (hdelta_le_one : delta <= 1)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet
        (source.successorSimultaneousCountBadEvent rounds delta n)) :
    MeasurableSet
        (source.adaptiveSimultaneousCountBadEvent rounds delta) ∧
    source.trajectoryMeasure
        (source.adaptiveSimultaneousCountBadEvent rounds delta) <=
      ENNReal.ofReal delta ∧
    forall trajectory,
      trajectory ∉ source.adaptiveSimultaneousCountBadEvent rounds delta ->
      forall round : Fin rounds, forall coordinate : CountCoordinate mdp,
        |coordinate.deviation (source.policyAt trajectory round)
            initialState (trajectory round)| <
          simultaneousCountConfidenceRadius mdp episodes
            (multiBatchLocalDelta rounds delta) := by
  refine ⟨source.measurableSet_adaptiveSimultaneousCountBadEvent
      rounds delta hsuccessor, ?_, ?_⟩
  · exact source.trajectoryMeasure_finiteHorizonBadEvent_le
      rounds hrounds delta
      (source.initialPolicy.measurableSet_simultaneousCountBadEvent
        initialState episodes (multiBatchLocalDelta rounds delta))
      hsuccessor
      (source.initialSimultaneousCountBadEvent_le rounds hrounds hepisodes
        delta hdelta hdelta_le_one)
      (fun n _hn =>
        source.successorSimultaneousCountBadEvent_fiber_le
          rounds hrounds hepisodes delta hdelta hdelta_le_one n)
  · intro trajectory htrajectory round coordinate
    have hround : trajectory ∉
        roundBadEvent
          (source.initialSimultaneousCountBadEvent rounds delta)
          (source.successorSimultaneousCountBadEvent rounds delta) round := by
      intro hmem
      exact htrajectory (Set.mem_iUnion_of_mem round hmem)
    cases round with
    | mk value hvalue =>
      cases value with
      | zero =>
          change trajectory 0 ∉
            source.initialPolicy.simultaneousCountBadEvent initialState episodes
              (multiBatchLocalDelta rounds delta) at hround
          exact
            source.initialPolicy.countCoordinate_abs_deviation_lt_of_not_mem_simultaneousCountBadEvent
              initialState (trajectory 0) hround coordinate
      | succ n =>
          change trajectory (n + 1) ∉
            (source.successorPolicy n (Preorder.frestrictLe n trajectory)).simultaneousCountBadEvent
              initialState episodes (multiBatchLocalDelta rounds delta) at hround
          exact
            (source.successorPolicy n (Preorder.frestrictLe n trajectory)).countCoordinate_abs_deviation_lt_of_not_mem_simultaneousCountBadEvent
              initialState (trajectory (n + 1)) hround coordinate

end AdaptiveEpisodeBatchSource
end FiniteHorizonRL
end BanditRLProof
