import BanditRLProof.RL.FiniteHorizonAdaptiveCumulativeInverseSqrtCalibration

/-!
# Adaptive cumulative Hoeffding UCB-VI foundation

This module records the first generated-process leaves for the Hoeffding
UCB-VI route.  It adds the reward-sum component that was absent from the
existing cumulative transition-count state, proves exact prefix updates and
measurability, and defines a one-episode-at-a-time adaptive source whose next
policy is the cumulative empirical optimistic policy with a clipped
inverse-square-root Hoeffding radius.

The source is genuinely generated by `AdaptiveEpisodeBatchSource.trajectoryMeasure`.
It has no forced uniform-exploration mixture and its policy depends on the
complete generated prefix.  The definitions are total at zero counts and at
invalid confidence inputs; under the eventual task contract (`0 < delta <= 1`,
positive horizon and episode budget) the logarithmic factor agrees with the
usual UCBVI-CH factor.

This is not yet the high-probability UCB-VI regret theorem.  In particular,
the existing `EstimatedModelPlan` recursion does not yet implement the
paper's cross-episode `min (Q_previous, H, backup)` clipping, and the adaptive
self-normalized transition-value confidence and cumulative martingale/bonus
assembly remain downstream obligations.
-/

open MeasureTheory
open scoped ENNReal NNReal ProbabilityTheory

universe u v

namespace BanditRLProof.FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

/-- Reward sums indexed by stage, state, and action. -/
abbrev RewardSumSummary (mdp : MDP State Action) :=
  Fin mdp.horizon -> State -> Action -> Real

/--
The cumulative empirical-model state needed by UCB-VI: transition counts and
sampled reward sums.  State-action visit counts are derived from the transition
summary, so they cannot drift away from the transition counts.
-/
abbrev AdaptiveCumulativeEmpiricalModelState (mdp : MDP State Action) :=
  TransitionCountSummary mdp × RewardSumSummary mdp

/-- UCBVI-CH state-action visits aggregated across every stage. -/
abbrev AggregateVisitCountSummary := State -> Action -> Nat

namespace TransitionCountSummary

/-- Sum a stage-indexed transition summary into the paper count `N_k(x,a)`. -/
def aggregateVisitCount
    {mdp : MDP State Action} (summary : TransitionCountSummary mdp) :
    AggregateVisitCountSummary (State := State) (Action := Action) :=
  fun state action =>
    ∑ stage : Fin mdp.horizon, summary.visitCount stage state action

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The complete cross-stage aggregate count view is measurable. -/
theorem measurable_aggregateVisitCount {mdp : MDP State Action} :
    Measurable
      (aggregateVisitCount : TransitionCountSummary mdp ->
        AggregateVisitCountSummary (State := State) (Action := Action)) := by
  refine measurable_pi_lambda _ fun state => ?_
  refine measurable_pi_lambda _ fun action => ?_
  refine Finset.measurable_sum Finset.univ fun stage _ => ?_
  unfold visitCount
  refine Finset.measurable_sum Finset.univ fun nextState _ => ?_
  exact (measurable_pi_apply nextState).comp
    ((measurable_pi_apply action).comp
      ((measurable_pi_apply state).comp (measurable_pi_apply stage)))

end TransitionCountSummary

namespace EpisodeBatchPrefix

/-- Sum every reward coordinate in a nonempty finite generated-batch prefix. -/
def cumulativeRewardSumSummary
    {mdp : MDP State Action} {episodes n : Nat}
    (history : EpisodeBatchPrefix mdp episodes n) : RewardSumSummary mdp :=
  fun stage state action =>
    ∑ i : Fin (n + 1),
      (history ⟨i, Finset.mem_Iic.mpr (Nat.le_of_lt_succ i.isLt)⟩).rewardSum
        stage state action

omit [Nonempty State] [Nonempty Action] in
/-- A fixed batch reward sum is measurable. -/
theorem measurable_rewardSum_coordinate
    {mdp : MDP State Action} {episodes : Nat}
    (stage : Fin mdp.horizon) (state : State) (action : Action) :
    Measurable fun batch : EpisodeBatch mdp episodes =>
      batch.rewardSum stage state action := by
  classical
  refine Finset.measurable_sum Finset.univ fun episode _ => ?_
  let step : EpisodeBatch mdp episodes -> EpisodeStep State Action :=
    fun batch => batch episode stage
  have hstep : Measurable step :=
    (measurable_pi_apply stage).comp (measurable_pi_apply episode)
  have hstate : Measurable fun batch : EpisodeBatch mdp episodes =>
      (step batch).state := EpisodeStep.measurable_state.comp hstep
  have haction : Measurable fun batch : EpisodeBatch mdp episodes =>
      (step batch).action := EpisodeStep.measurable_action.comp hstep
  have hreward : Measurable fun batch : EpisodeBatch mdp episodes =>
      (step batch).reward := EpisodeStep.measurable_reward.comp hstep
  exact Measurable.ite
    ((measurableSet_eq_fun hstate measurable_const).inter
      (measurableSet_eq_fun haction measurable_const))
    hreward measurable_const

omit [Nonempty State] [Nonempty Action] in
/-- The complete cumulative reward-sum table is history measurable. -/
theorem measurable_cumulativeRewardSumSummary
    {mdp : MDP State Action} {episodes n : Nat} :
    Measurable
      (cumulativeRewardSumSummary :
        EpisodeBatchPrefix mdp episodes n -> RewardSumSummary mdp) := by
  refine measurable_pi_lambda _ fun stage => ?_
  refine measurable_pi_lambda _ fun state => ?_
  refine measurable_pi_lambda _ fun action => ?_
  change Measurable fun history : EpisodeBatchPrefix mdp episodes n =>
    ∑ i : Fin (n + 1),
      (history ⟨i, Finset.mem_Iic.mpr (Nat.le_of_lt_succ i.isLt)⟩).rewardSum
        stage state action
  refine Finset.measurable_sum Finset.univ fun i _ => ?_
  let index : Finset.Iic n :=
    ⟨i, Finset.mem_Iic.mpr (Nat.le_of_lt_succ i.isLt)⟩
  exact (measurable_rewardSum_coordinate stage state action).comp
    (measurable_pi_apply index)

/-- Cumulative transition counts and reward sums from exactly the same prefix. -/
def cumulativeEmpiricalModelState
    {mdp : MDP State Action} {episodes n : Nat}
    (history : EpisodeBatchPrefix mdp episodes n) :
    AdaptiveCumulativeEmpiricalModelState mdp :=
  (history.cumulativeTransitionCountSummary,
    history.cumulativeRewardSumSummary)

omit [Nonempty State] [Nonempty Action] in
/-- The paired cumulative empirical-model state is history measurable. -/
theorem measurable_cumulativeEmpiricalModelState
    {mdp : MDP State Action} {episodes n : Nat} :
    Measurable
      (cumulativeEmpiricalModelState : EpisodeBatchPrefix mdp episodes n ->
        AdaptiveCumulativeEmpiricalModelState mdp) :=
  (measurable_cumulativeTransitionCountSummary).prodMk
    measurable_cumulativeRewardSumSummary

end EpisodeBatchPrefix

/-- Cumulative empirical-model state through trajectory coordinate `round`. -/
def adaptiveCumulativeEmpiricalModelStateAt
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat) :
    AdaptiveCumulativeEmpiricalModelState mdp :=
  EpisodeBatchPrefix.cumulativeEmpiricalModelState
    (Preorder.frestrictLe round trajectory)

omit [Nonempty State] [Nonempty Action] in
/-- The cumulative empirical-model state at a fixed generated round is measurable. -/
theorem measurable_adaptiveCumulativeEmpiricalModelStateAt
    {mdp : MDP State Action} {episodes : Nat} (round : Nat) :
    Measurable fun trajectory : EpisodeBatchTrajectory mdp episodes =>
      adaptiveCumulativeEmpiricalModelStateAt trajectory round :=
  EpisodeBatchPrefix.measurable_cumulativeEmpiricalModelState.comp
    (Preorder.measurable_frestrictLe round)

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Extending the prefix adds exactly the new transition-count coordinate. -/
theorem adaptiveCumulativeEmpiricalModelStateAt_transitionCount_succ
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat)
    (stage : Fin mdp.horizon) (state : State) (action : Action)
    (nextState : State) :
    (adaptiveCumulativeEmpiricalModelStateAt trajectory (round + 1)).1
        stage state action nextState =
      (adaptiveCumulativeEmpiricalModelStateAt trajectory round).1
          stage state action nextState +
        (trajectory (round + 1)).transitionCount
          stage state action nextState := by
  exact cumulativeTransitionCountSummaryAt_succ
    trajectory round stage state action nextState

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Extending the prefix adds exactly the new reward-sum coordinate. -/
theorem adaptiveCumulativeEmpiricalModelStateAt_rewardSum_succ
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat)
    (stage : Fin mdp.horizon) (state : State) (action : Action) :
    (adaptiveCumulativeEmpiricalModelStateAt trajectory (round + 1)).2
        stage state action =
      (adaptiveCumulativeEmpiricalModelStateAt trajectory round).2
          stage state action +
        (trajectory (round + 1)).rewardSum stage state action := by
  classical
  unfold adaptiveCumulativeEmpiricalModelStateAt
    EpisodeBatchPrefix.cumulativeEmpiricalModelState
    EpisodeBatchPrefix.cumulativeRewardSumSummary
  change
    (∑ i : Fin (round + 2),
      (trajectory i).rewardSum stage state action) =
      (∑ i : Fin (round + 1),
        (trajectory i).rewardSum stage state action) +
      (trajectory (round + 1)).rewardSum stage state action
  rw [Fin.sum_univ_castSucc]
  rfl

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Visit counts are definitionally derived from the same cumulative state. -/
theorem adaptiveCumulativeEmpiricalModelStateAt_visitCount
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat)
    (stage : Fin mdp.horizon) (state : State) (action : Action) :
    (adaptiveCumulativeEmpiricalModelStateAt trajectory round).1.visitCount
        stage state action =
      ∑ i : Fin (round + 1),
        (trajectory i).visitCount stage state action := by
  simpa [adaptiveCumulativeEmpiricalModelStateAt,
    EpisodeBatchPrefix.cumulativeEmpiricalModelState] using
      (EpisodeBatchPrefix.cumulativeTransitionCountSummary_visitCount
        (Preorder.frestrictLe round trajectory) stage state action)

/-- The paper count `N_k(x,a)` read from exactly one generated prefix. -/
def adaptiveCumulativeAggregateVisitCountAt
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat) :
    AggregateVisitCountSummary (State := State) (Action := Action) :=
  (adaptiveCumulativeEmpiricalModelStateAt trajectory round).1.aggregateVisitCount

omit [Nonempty State] [Nonempty Action] in
/-- Every fixed-round aggregate state-action count table is measurable. -/
theorem measurable_adaptiveCumulativeAggregateVisitCountAt
    {mdp : MDP State Action} {episodes : Nat} (round : Nat) :
    Measurable fun trajectory : EpisodeBatchTrajectory mdp episodes =>
      adaptiveCumulativeAggregateVisitCountAt trajectory round :=
  TransitionCountSummary.measurable_aggregateVisitCount.comp
    (measurable_adaptiveCumulativeEmpiricalModelStateAt round).fst

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The aggregate count is the literal sum over prior episodes and stages. -/
theorem adaptiveCumulativeAggregateVisitCountAt_eq_sum
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat)
    (state : State) (action : Action) :
    adaptiveCumulativeAggregateVisitCountAt trajectory round state action =
      ∑ i : Fin (round + 1), ∑ stage : Fin mdp.horizon,
        (trajectory i).visitCount stage state action := by
  classical
  unfold adaptiveCumulativeAggregateVisitCountAt
    TransitionCountSummary.aggregateVisitCount
  simp_rw [adaptiveCumulativeEmpiricalModelStateAt_visitCount]
  rw [Finset.sum_comm]

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Extending the generated prefix adds exactly one episode's stage visits. -/
theorem adaptiveCumulativeAggregateVisitCountAt_succ
    {mdp : MDP State Action} {episodes : Nat}
    (trajectory : EpisodeBatchTrajectory mdp episodes) (round : Nat)
    (state : State) (action : Action) :
    adaptiveCumulativeAggregateVisitCountAt trajectory (round + 1) state action =
      adaptiveCumulativeAggregateVisitCountAt trajectory round state action +
        ∑ stage : Fin mdp.horizon,
          (trajectory (round + 1)).visitCount stage state action := by
  rw [adaptiveCumulativeAggregateVisitCountAt_eq_sum,
    adaptiveCumulativeAggregateVisitCountAt_eq_sum]
  rw [Fin.sum_univ_castSucc]
  simp

/-- Empirical reward with the explicit zero-count convention. -/
noncomputable def AdaptiveCumulativeEmpiricalModelState.empiricalReward
    {mdp : MDP State Action}
    (model : AdaptiveCumulativeEmpiricalModelState mdp)
    (stage : Fin mdp.horizon) (state : State) (action : Action) : Real :=
  model.2 stage state action /
    (model.1.visitCount stage state action : Real)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
@[simp]
theorem AdaptiveCumulativeEmpiricalModelState.empiricalReward_of_visitCount_eq_zero
    {mdp : MDP State Action}
    (model : AdaptiveCumulativeEmpiricalModelState mdp)
    (stage : Fin mdp.horizon) (state : State) (action : Action)
    (hzero : model.1.visitCount stage state action = 0) :
    model.empiricalReward stage state action = 0 := by
  simp [AdaptiveCumulativeEmpiricalModelState.empiricalReward, hzero]

namespace AdaptiveCumulativeHoeffdingUCBVI

/-- Total number of environment time steps after `episodes` episodes. -/
def totalSteps (mdp : MDP State Action) (episodes : Nat) : Nat :=
  episodes * mdp.horizon

/-- Integer numerator used in the UCBVI-CH logarithmic factor. -/
def confidenceNumerator
    (mdp : MDP State Action) (episodes : Nat) : Nat :=
  5 * mdp.horizon * Fintype.card State * Fintype.card Action *
    totalSteps mdp episodes

/--
Safe total version of the UCBVI-CH logarithmic factor.  The `max 1` only
specifies invalid/degenerate inputs and disappears under the positive task
contract.
-/
noncomputable def logFactor
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) : Real :=
  Real.log (max 1
    (((confidenceNumerator (State := State) (Action := Action)
      mdp episodes : Nat) : Real) / delta))

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
theorem one_le_confidenceNumerator_div
    (mdp : MDP State Action) (episodes : Nat) (delta : Real)
    (hhorizon : 0 < mdp.horizon) (hepisodes : 0 < episodes)
    (hdelta : 0 < delta) (hdelta_le_one : delta <= 1) :
    1 <= ((confidenceNumerator (State := State) (Action := Action)
      mdp episodes : Nat) : Real) / delta := by
  have hnumeratorPos :
      0 < confidenceNumerator (State := State) (Action := Action)
        mdp episodes := by
    unfold confidenceNumerator totalSteps
    positivity
  have honeNumerator :
      (1 : Real) <=
        (confidenceNumerator (State := State) (Action := Action)
          mdp episodes : Nat) := by
    exact_mod_cast hnumeratorPos
  apply (le_div_iff₀ hdelta).2
  simpa using hdelta_le_one.trans honeNumerator

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
/-- On the task domain, the safe total logarithm is exactly the paper factor. -/
theorem logFactor_eq_paper
    (mdp : MDP State Action) (episodes : Nat) (delta : Real)
    (hhorizon : 0 < mdp.horizon) (hepisodes : 0 < episodes)
    (hdelta : 0 < delta) (hdelta_le_one : delta <= 1) :
    logFactor (State := State) (Action := Action) mdp episodes delta =
      Real.log
        (((confidenceNumerator (State := State) (Action := Action)
          mdp episodes : Nat) : Real) / delta) := by
  unfold logFactor
  rw [max_eq_right
    (one_le_confidenceNumerator_div mdp episodes delta hhorizon hepisodes
      hdelta hdelta_le_one)]

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem logFactor_nonneg
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) :
    0 <= logFactor (State := State) (Action := Action) mdp episodes delta := by
  unfold logFactor
  exact Real.log_nonneg (le_max_left _ _)

/-- Paper-shaped Hoeffding scale `7 H L`. -/
noncomputable def scale
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) : Real :=
  7 * (mdp.horizon : Real) *
    logFactor (State := State) (Action := Action) mdp episodes delta

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem scale_nonneg
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) :
    0 <= scale (State := State) (Action := Action) mdp episodes delta := by
  unfold scale
  exact mul_nonneg
    (mul_nonneg (by norm_num) (Nat.cast_nonneg mdp.horizon))
    (logFactor_nonneg mdp episodes delta)

/--
Clipped Hoeffding radius: `H` at zero visits and
`min H (7 H L / sqrt N)` afterwards.
-/
noncomputable def countRadius
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) :
    TransitionCountRadius :=
  TransitionCountRadius.cappedInverseSqrt
    (mdp.horizon : Real)
    (scale (State := State) (Action := Action) mdp episodes delta)
    (by positivity) (scale_nonneg mdp episodes delta)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
@[simp]
theorem countRadius_zero
    (mdp : MDP State Action) (episodes : Nat) (delta : Real) :
    (countRadius (State := State) (Action := Action) mdp episodes delta).radius 0 =
      (mdp.horizon : Real) := by
  simp [countRadius]

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem countRadius_of_pos
    (mdp : MDP State Action) (episodes : Nat) (delta : Real)
    {count : Nat} (hcount : 0 < count) :
    (countRadius (State := State) (Action := Action) mdp episodes delta).radius count =
      min (mdp.horizon : Real)
        (scale (State := State) (Action := Action) mdp episodes delta /
          Real.sqrt count) := by
  exact TransitionCountRadius.cappedInverseSqrt_radius_of_pos
    (mdp.horizon : Real)
    (scale (State := State) (Action := Action) mdp episodes delta)
    (by positivity) (scale_nonneg mdp episodes delta) hcount

/--
One-episode-at-a-time cumulative optimistic source.  Coordinate zero follows
`initialTable`; coordinate `n+1` is generated by the pure optimistic policy
computed from all coordinates through `n`.
-/
noncomputable def source
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (episodes : Nat) (delta : Real) :
    AdaptiveEpisodeBatchSource mdp initialState 1 where
  initialPolicy := initialTable.toMarkovPolicy
  successorPolicy n history :=
    (AdaptiveCumulativeEmpiricalOptimisticSource.successorTable
      defaultState
      (countRadius (State := State) (Action := Action) mdp episodes delta)
      n history).toMarkovPolicy
  batchKernel n :=
    (DeterministicMarkovPolicyTable.iidEpisodeBatchKernel initialState 1).comap
      (AdaptiveCumulativeEmpiricalOptimisticSource.successorTable
        defaultState
        (countRadius (State := State) (Action := Action) mdp episodes delta) n)
      (AdaptiveCumulativeEmpiricalOptimisticSource.measurable_successorTable
        defaultState
        (countRadius (State := State) (Action := Action) mdp episodes delta) n)
  batchKernel_isMarkov n := by
    exact ProbabilityTheory.Kernel.IsMarkovKernel.comap _
      (AdaptiveCumulativeEmpiricalOptimisticSource.measurable_successorTable
        defaultState
        (countRadius (State := State) (Action := Action) mdp episodes delta) n)
  batchKernel_eq_iidEpisodeBatchMeasure n history := by
    rw [ProbabilityTheory.Kernel.comap_apply]
    rfl

omit [Nonempty State] in
/-- The next policy is exactly the cumulative empirical optimistic plan. -/
theorem source_successorPolicy_eq_optimisticPolicy
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (episodes : Nat) (delta : Real)
    (n : Nat) (history : EpisodeBatchPrefix mdp 1 n) :
    (source mdp initialState initialTable defaultState episodes delta).successorPolicy
        n history =
      (history.cumulativeTransitionCountSummary.countRadiusOptimisticPlan
        mdp defaultState
        (countRadius (State := State) (Action := Action) mdp episodes delta)
      ).optimisticPolicy := by
  rfl

omit [Nonempty State] in
/--
On a complete generated trajectory, the policy at successor episode `n+1`
uses exactly the cumulative counts through `n`.
-/
theorem source_policyAt_succ_eq_optimisticPolicy
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (episodes : Nat) (delta : Real)
    (trajectory : EpisodeBatchTrajectory mdp 1) (n : Nat) :
    (source mdp initialState initialTable defaultState episodes delta).policyAt
        trajectory (n + 1) =
      (adaptiveCumulativeEmpiricalOptimisticPlanAt trajectory defaultState
        (countRadius (State := State) (Action := Action) mdp episodes delta) n
      ).optimisticPolicy := by
  rfl

omit [Nonempty State] in
/-- The policy/model alignment names the paired cumulative state explicitly. -/
theorem source_policyAt_succ_eq_modelState_optimisticPolicy
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (episodes : Nat) (delta : Real)
    (trajectory : EpisodeBatchTrajectory mdp 1) (n : Nat) :
    (source mdp initialState initialTable defaultState episodes delta).policyAt
        trajectory (n + 1) =
      ((adaptiveCumulativeEmpiricalModelStateAt trajectory n).1
        |>.countRadiusOptimisticPlan mdp defaultState
          (countRadius (State := State) (Action := Action) mdp episodes delta)
        |>.optimisticPolicy) := by
  rfl

end AdaptiveCumulativeHoeffdingUCBVI

end BanditRLProof.FiniteHorizonRL
