import BanditRLProof.RL.FiniteHorizonStochasticRewardIIDSelfConsistentCalibration
import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticExplicitBudgetRealizedBehaviorRegret

/-!
# Self-consistent-budget realized successor regret for actual sampled optimism

This module replaces the coarse transition budget `rewardBound + 2 * rewardBudget`
by the exact fixed point generated by a contraction coefficient `q < 1`.  It
retains actual sampled rewards, adaptive policy selection, three independent
confidence shares, and the globally centered successor-return transport.

The endpoint is fixed-window and excludes the initial batch.  It does not claim
an anytime, minimax, or complete UCB-VI rate; schedule-level control of the
contraction, reward radius, exploration charge, and return radius remains
downstream.
-/

open MeasureTheory
open scoped ENNReal ProbabilityTheory BigOperators

universe u v

namespace BanditRLProof
namespace FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace AdaptiveStochasticSampledEmpiricalOptimisticSource

/--
Finite-round actual-sampled confidence under the exact self-consistent
transition budget.  Every selected model is built from its observed batch.
-/
theorem exploratorySource_trajectoryMeasure_finiteRound_allCoordinateConfidence_optimism_and_recommendedExpectedRegret_of_pathSupport_selfConsistentCalibration
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (explorationRate : NNReal) (hexplorationRate : explorationRate <= 1)
    (rounds : Nat) (hrounds : 0 < rounds) (hepisodes : 0 < episodes)
    (varianceProxy : NNReal)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (htotal : 0 < ((((episodes : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta : Real) (hcountDelta : 0 < countDelta)
    (hcountDelta_le_one : countDelta <= 1)
    (rewardDelta : Real) (hrewardDelta : 0 < rewardDelta)
    (hrewardDelta_le_one : rewardDelta <= 1)
    (defaultState : State) (rewardBound : Real)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= rewardBound)
    (support : ExploratoryPathSupport mdp initialState) (visitFloor : Real)
    (hfloor : ExploratoryPathUniformVisitFloor support explorationRate visitFloor)
    (hmargin :
      simultaneousCountConfidenceRadius mdp episodes
          (multiBatchLocalDelta rounds countDelta) <
        (episodes : Real) * visitFloor)
    (hq : uniformFloorStochasticTransitionContraction mdp episodes
      (multiBatchLocalDelta rounds countDelta) visitFloor < 1) :
    let localCountDelta := multiBatchLocalDelta rounds countDelta
    let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
    let rewardBudget :=
      uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
        localCountDelta localRewardDelta visitFloor
    let transitionBudget :=
      uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
        localCountDelta visitFloor rewardBound rewardBudget
    let source := exploratorySource mdp initialState episodes rewardSource
      initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    let event := source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
    MeasurableSet event ∧
      source.trajectoryMeasure event <=
        ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta ∧
      forall trajectory, trajectory ∉ event -> forall round : Fin rounds,
        let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
          episodes (mdp.sampledEpisodeBatchOfStochasticTrajectories
            episodes (trajectory round))
          defaultState rewardBudget transitionBudget
        (forall state,
            mdp.optimalValueRemaining mdp.horizon le_rfl state <=
              model.plan.upperValueRemaining mdp.horizon le_rfl state) ∧
          model.plan.optimisticPolicy.expectedRegret initialState <=
            model.plan.optimisticPolicy.occupancySumRemaining
              (fun remaining hremaining state =>
                2 * model.plan.selectedRadiusRemaining
                  remaining hremaining state)
              mdp.horizon le_rfl initialState := by
  dsimp only
  let localCountDelta := multiBatchLocalDelta rounds countDelta
  let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
  let rewardBudget :=
    uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
      localCountDelta localRewardDelta visitFloor
  let transitionBudget :=
    uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
      localCountDelta visitFloor rewardBound rewardBudget
  let source : AdaptiveStochasticEpisodeBatchSource mdp initialState episodes :=
    exploratorySource mdp initialState episodes rewardSource
      initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
  let event : Set (StochasticEpisodeBatchTrajectory mdp episodes) :=
    source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
  have hlocalCountPos : 0 < localCountDelta :=
    AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_pos_of_pos
      hrounds hcountDelta
  have hlocalCountLeOne : localCountDelta <= 1 :=
    AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_le_one_of_le_one
      hrounds hcountDelta_le_one
  have hlocalRewardPos : 0 < localRewardDelta :=
    AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_pos_of_pos
      hrounds hrewardDelta
  have hlocalRewardLeOne : localRewardDelta <= 1 :=
    AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_le_one_of_le_one
      hrounds hrewardDelta_le_one
  have hevent : MeasurableSet event ∧
      source.trajectoryMeasure event <=
        ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta := by
    simpa [event, source] using
      (exploratorySource_trajectoryMeasure_adaptiveAllCoordinateEmpiricalModelBadEvent_le
        rewardSource initialTable defaultState rewardBudget transitionBudget
          explorationRate hexplorationRate rounds hrounds hepisodes
          varianceProxy law htotal countDelta hcountDelta hcountDelta_le_one
          rewardDelta hrewardDelta hrewardDelta_le_one)
  refine ⟨hevent.1, hevent.2, ?_⟩
  intro (trajectory : StochasticEpisodeBatchTrajectory mdp episodes)
    (htrajectory : trajectory ∉ event)
    (round : Fin rounds)
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          have hfixed :=
            initialTable.exploratoryPolicy_iidStochasticTrajectoryFamilyMeasure_allCoordinate_optimism_and_expectedRegret_of_pathSupport_selfConsistentCalibration
              rewardSource initialState explorationRate hexplorationRate
                episodes hepisodes varianceProxy law htotal
                localCountDelta hlocalCountPos hlocalCountLeOne
                localRewardDelta hlocalRewardPos hlocalRewardLeOne
                defaultState rewardBound hrewardBound support visitFloor hfloor
                hmargin hq
          have hnot' : trajectory 0 ∉
              rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
                (initialTable.exploratoryPolicy explorationRate hexplorationRate)
                initialState episodes varianceProxy
                  localCountDelta localRewardDelta := by
            simpa [source, localCountDelta, localRewardDelta,
              AdaptiveStochasticEpisodeBatchSource.policyAt, exploratorySource]
              using
                (AdaptiveStochasticEpisodeBatchSource.policyAt_batch_not_mem_allCoordinateEmpiricalModelBadEvent
                  (mdp := mdp) (initialState := initialState) (episodes := episodes)
                  (rounds := rounds) source trajectory varianceProxy countDelta
                    rewardDelta htrajectory (⟨0, hvalue⟩ : Fin rounds))
          exact hfixed.2.2 (trajectory 0) hnot'
      | succ n =>
          let table := successorTable defaultState rewardBudget transitionBudget n
            (Preorder.frestrictLe n trajectory)
          have hfixed :=
            table.exploratoryPolicy_iidStochasticTrajectoryFamilyMeasure_allCoordinate_optimism_and_expectedRegret_of_pathSupport_selfConsistentCalibration
              rewardSource initialState explorationRate hexplorationRate
                episodes hepisodes varianceProxy law htotal
                localCountDelta hlocalCountPos hlocalCountLeOne
                localRewardDelta hlocalRewardPos hlocalRewardLeOne
                defaultState rewardBound hrewardBound support visitFloor hfloor
                hmargin hq
          have hnot' : trajectory (n + 1) ∉
              rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
                (table.exploratoryPolicy explorationRate hexplorationRate)
                initialState episodes varianceProxy
                  localCountDelta localRewardDelta := by
            simpa [source, table, localCountDelta, localRewardDelta,
              AdaptiveStochasticEpisodeBatchSource.policyAt, exploratorySource]
              using
                (AdaptiveStochasticEpisodeBatchSource.policyAt_batch_not_mem_allCoordinateEmpiricalModelBadEvent
                  (mdp := mdp) (initialState := initialState) (episodes := episodes)
                  (rounds := rounds) source trajectory varianceProxy countDelta
                    rewardDelta htrajectory (⟨n + 1, hvalue⟩ : Fin rounds))
          exact hfixed.2.2 (trajectory (n + 1)) hnot'

/--
The self-consistent per-round certificate sums to the successor exploratory
behavior expected-regret bound, including the explicit exploration charge.
-/
theorem exploratorySource_trajectoryMeasure_finiteRound_allCoordinateConfidence_optimism_and_cumulativeSuccessorExploratoryBehaviorExpectedRegret_of_pathSupport_selfConsistentCalibration
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (explorationRate : NNReal) (hexplorationRate : explorationRate <= 1)
    (rounds : Nat) (hrounds : 0 < rounds) (hepisodes : 0 < episodes)
    (varianceProxy : NNReal)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (htotal : 0 < ((((episodes : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta : Real) (hcountDelta : 0 < countDelta)
    (hcountDelta_le_one : countDelta <= 1)
    (rewardDelta : Real) (hrewardDelta : 0 < rewardDelta)
    (hrewardDelta_le_one : rewardDelta <= 1)
    (defaultState : State) (rewardBound : Real)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= rewardBound)
    (support : ExploratoryPathSupport mdp initialState) (visitFloor : Real)
    (hfloor : ExploratoryPathUniformVisitFloor support explorationRate visitFloor)
    (hmargin :
      simultaneousCountConfidenceRadius mdp episodes
          (multiBatchLocalDelta rounds countDelta) <
        (episodes : Real) * visitFloor)
    (hq : uniformFloorStochasticTransitionContraction mdp episodes
      (multiBatchLocalDelta rounds countDelta) visitFloor < 1) :
    let localCountDelta := multiBatchLocalDelta rounds countDelta
    let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
    let rewardBudget :=
      uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
        localCountDelta localRewardDelta visitFloor
    let transitionBudget :=
      uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
        localCountDelta visitFloor rewardBound rewardBudget
    let source := exploratorySource mdp initialState episodes rewardSource
      initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    let event := source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
    MeasurableSet event ∧
      source.trajectoryMeasure event <=
        ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta ∧
      forall trajectory, trajectory ∉ event ->
        (forall round : Fin rounds, forall state,
          mdp.optimalValueRemaining mdp.horizon le_rfl state <=
            (adaptiveStochasticSampledEmpiricalOptimisticPlanAt trajectory
              defaultState rewardBudget transitionBudget round).upperValueRemaining
                mdp.horizon le_rfl state) ∧
          adaptiveStochasticSampledEmpiricalOptimisticSuccessorExploratoryBehaviorExpectedRegret
              (mdp := mdp) (initialState := initialState) (episodes := episodes)
              trajectory defaultState rewardBudget transitionBudget
                explorationRate hexplorationRate rounds <=
            adaptiveStochasticSampledEmpiricalOptimisticOccupancyRadiusSum
                (mdp := mdp) (initialState := initialState) (episodes := episodes)
                trajectory defaultState rewardBudget transitionBudget rounds +
              (rounds : Real) *
                exploratoryBehaviorRegretCharge mdp explorationRate rewardBound := by
  dsimp only
  let localCountDelta := multiBatchLocalDelta rounds countDelta
  let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
  let rewardBudget :=
    uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
      localCountDelta localRewardDelta visitFloor
  let transitionBudget :=
    uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
      localCountDelta visitFloor rewardBound rewardBudget
  let source : AdaptiveStochasticEpisodeBatchSource mdp initialState episodes :=
    exploratorySource mdp initialState episodes rewardSource
      initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
  let event : Set (StochasticEpisodeBatchTrajectory mdp episodes) :=
    source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
  have hparent :=
    exploratorySource_trajectoryMeasure_finiteRound_allCoordinateConfidence_optimism_and_recommendedExpectedRegret_of_pathSupport_selfConsistentCalibration
      rewardSource initialTable explorationRate hexplorationRate
        rounds hrounds hepisodes varianceProxy law htotal
        countDelta hcountDelta hcountDelta_le_one
        rewardDelta hrewardDelta hrewardDelta_le_one
        defaultState rewardBound hrewardBound support visitFloor hfloor
        hmargin hq
  have hparent' :
      MeasurableSet event ∧
        source.trajectoryMeasure event <=
          ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta ∧
        forall trajectory, trajectory ∉ event -> forall round : Fin rounds,
          let plan := adaptiveStochasticSampledEmpiricalOptimisticPlanAt
            trajectory defaultState rewardBudget transitionBudget round
          (forall state,
              mdp.optimalValueRemaining mdp.horizon le_rfl state <=
                plan.upperValueRemaining mdp.horizon le_rfl state) ∧
            plan.optimisticPolicy.expectedRegret initialState <=
              plan.optimisticPolicy.occupancySumRemaining
                (fun remaining hremaining state =>
                  2 * plan.selectedRadiusRemaining remaining hremaining state)
                mdp.horizon le_rfl initialState := by
    simpa [source, event, localCountDelta, localRewardDelta, rewardBudget,
      transitionBudget, adaptiveStochasticSampledEmpiricalOptimisticPlanAt]
      using hparent
  refine ⟨hparent'.1, hparent'.2.1, ?_⟩
  intro trajectory htrajectory
  have hrecommended :=
    adaptiveStochasticSampledEmpiricalOptimistic_optimism_and_cumulativeRecommendedExpectedRegret
      (mdp := mdp) (initialState := initialState) (episodes := episodes)
      trajectory defaultState rewardBudget transitionBudget
        (hparent'.2.2 trajectory htrajectory)
  exact
    adaptiveStochasticSampledEmpiricalOptimistic_optimism_and_cumulativeSuccessorExploratoryBehaviorExpectedRegret
      trajectory defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate rewardBound hrewardBound hrecommended

end AdaptiveStochasticSampledEmpiricalOptimisticSource

/-- Planning part of the self-consistent realized average-regret certificate. -/
noncomputable def
    adaptiveStochasticSampledEmpiricalOptimisticSelfConsistentBudgetAverageBound
    (mdp : MDP State Action) (episodes : Nat) (countDelta visitFloor : Real)
    (explorationRate : NNReal) (rewardBound rewardBudget : Real) : Real :=
  (mdp.horizon : Real) *
      (2 * (rewardBudget +
        uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
          countDelta visitFloor rewardBound rewardBudget)) +
    exploratoryBehaviorRegretCharge mdp explorationRate rewardBound

omit [Nonempty State] in
/-- The exact occupancy sum closes to the self-consistent average bound. -/
theorem adaptiveStochasticSampledEmpiricalOptimistic_occupancyAndChargeAverage_eq_selfConsistentBudgetAverageBound
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (trajectory : StochasticEpisodeBatchTrajectory mdp episodes)
    (defaultState : State) (countDelta visitFloor rewardBound rewardBudget : Real)
    (explorationRate : NNReal) (rounds : Nat) (hrounds : 0 < rounds) :
    (adaptiveStochasticSampledEmpiricalOptimisticOccupancyRadiusSum
          (mdp := mdp) (initialState := initialState) (episodes := episodes)
          trajectory defaultState rewardBudget
            (uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
              countDelta visitFloor rewardBound rewardBudget)
            rounds +
        (rounds : Real) *
          exploratoryBehaviorRegretCharge mdp explorationRate rewardBound) /
        (rounds : Real) =
      adaptiveStochasticSampledEmpiricalOptimisticSelfConsistentBudgetAverageBound
        mdp episodes countDelta visitFloor explorationRate rewardBound
          rewardBudget := by
  rw [adaptiveStochasticSampledEmpiricalOptimisticOccupancyRadiusSum_eq]
  have hroundsReal : (rounds : Real) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt hrounds
  unfold adaptiveStochasticSampledEmpiricalOptimisticSelfConsistentBudgetAverageBound
  field_simp [hroundsReal]

namespace AdaptiveStochasticSampledEmpiricalOptimisticSource

/--
Actual sampled-model confidence and globally centered realized successor regret
under the shrinking self-consistent transition budget.
-/
theorem exploratorySource_trajectoryMeasure_finiteRound_allCoordinateConfidence_optimism_and_selfConsistentBudgetRealizedSuccessorAverageRegret_of_pathSupport_selfConsistentCalibration
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [StandardBorelSpace (StochasticEpisodeBatch mdp episodes)]
    [Nonempty (StochasticEpisodeBatch mdp episodes)]
    [StandardBorelSpace (StochasticEpisodeBatchTrajectory mdp episodes)]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (explorationRate : NNReal) (hexplorationRate : explorationRate <= 1)
    (rounds : Nat) (hrounds : 0 < rounds) (hepisodes : 0 < episodes)
    (varianceProxy : NNReal)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (hmodelTotal : 0 < ((((episodes : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta : Real) (hcountDelta : 0 < countDelta)
    (hcountDelta_le_one : countDelta <= 1)
    (rewardDelta : Real) (hrewardDelta : 0 < rewardDelta)
    (hrewardDelta_le_one : rewardDelta <= 1)
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1)
    (defaultState : State) (rewardBound : NNReal)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= (rewardBound : Real))
    (support : ExploratoryPathSupport mdp initialState) (visitFloor : Real)
    (hfloor : ExploratoryPathUniformVisitFloor support explorationRate visitFloor)
    (hmargin :
      simultaneousCountConfidenceRadius mdp episodes
          (multiBatchLocalDelta rounds countDelta) <
        (episodes : Real) * visitFloor)
    (hq : uniformFloorStochasticTransitionContraction mdp episodes
      (multiBatchLocalDelta rounds countDelta) visitFloor < 1)
    (hreturnTotal : 0 <
      ((AdaptiveStochasticEpisodeBatchSource.cumulativeSuccessorGlobalReturnVarianceProxy
        mdp rounds episodes rewardBound varianceProxy : NNReal) : Real)) :
    let localCountDelta := multiBatchLocalDelta rounds countDelta
    let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
    let rewardBudget :=
      uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
        localCountDelta localRewardDelta visitFloor
    let transitionBudget :=
      uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
        localCountDelta visitFloor (rewardBound : Real) rewardBudget
    let source := exploratorySource mdp initialState episodes rewardSource
      initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    let modelBadEvent := source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
    let returnBadEvent := source.successorGlobalReturnDeviationBadEvent
      rounds rewardBound varianceProxy returnDelta
    let combinedBadEvent := modelBadEvent ∪ returnBadEvent
    MeasurableSet combinedBadEvent ∧
      source.trajectoryMeasure combinedBadEvent <=
        (ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta) +
          ENNReal.ofReal returnDelta ∧
      forall trajectory, trajectory ∉ combinedBadEvent ->
        (forall round : Fin rounds, forall state,
          mdp.optimalValueRemaining mdp.horizon le_rfl state <=
            (adaptiveStochasticSampledEmpiricalOptimisticPlanAt trajectory
              defaultState rewardBudget transitionBudget round).upperValueRemaining
                mdp.horizon le_rfl state) ∧
          source.realizedSuccessorAverageRegret trajectory rounds <=
            adaptiveStochasticSampledEmpiricalOptimisticSelfConsistentBudgetAverageBound
                mdp episodes localCountDelta visitFloor explorationRate
                  (rewardBound : Real) rewardBudget +
              Concentration.subGaussianSumConfidenceRadius
                  (AdaptiveStochasticEpisodeBatchSource.cumulativeSuccessorGlobalReturnVarianceProxy
                    mdp rounds episodes rewardBound varianceProxy)
                  returnDelta /
                ((episodes : Real) * (rounds : Real)) := by
  dsimp only
  let localCountDelta := multiBatchLocalDelta rounds countDelta
  let localRewardDelta := multiBatchLocalDelta rounds rewardDelta
  let rewardBudget :=
    uniformFloorStochasticRewardCoordinateRadius mdp episodes varianceProxy
      localCountDelta localRewardDelta visitFloor
  let transitionBudget :=
    uniformFloorStochasticSelfConsistentTransitionBudget mdp episodes
      localCountDelta visitFloor (rewardBound : Real) rewardBudget
  let source : AdaptiveStochasticEpisodeBatchSource mdp initialState episodes :=
    exploratorySource mdp initialState episodes rewardSource initialTable
      defaultState rewardBudget transitionBudget explorationRate hexplorationRate
  let modelBadEvent : Set (StochasticEpisodeBatchTrajectory mdp episodes) :=
    source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
  let returnBadEvent : Set (StochasticEpisodeBatchTrajectory mdp episodes) :=
    source.successorGlobalReturnDeviationBadEvent
      rounds rewardBound varianceProxy returnDelta
  let combinedBadEvent : Set (StochasticEpisodeBatchTrajectory mdp episodes) :=
    modelBadEvent ∪ returnBadEvent
  let expectedBound :=
    adaptiveStochasticSampledEmpiricalOptimisticSelfConsistentBudgetAverageBound
      mdp episodes localCountDelta visitFloor explorationRate
        (rewardBound : Real) rewardBudget
  let Good := fun trajectory : StochasticEpisodeBatchTrajectory mdp episodes =>
    forall round : Fin rounds, forall state,
      mdp.optimalValueRemaining mdp.horizon le_rfl state <=
        (adaptiveStochasticSampledEmpiricalOptimisticPlanAt trajectory
          defaultState rewardBudget transitionBudget round).upperValueRemaining
            mdp.horizon le_rfl state
  have hmodel :=
    exploratorySource_trajectoryMeasure_finiteRound_allCoordinateConfidence_optimism_and_cumulativeSuccessorExploratoryBehaviorExpectedRegret_of_pathSupport_selfConsistentCalibration
      rewardSource initialTable explorationRate hexplorationRate
        rounds hrounds hepisodes varianceProxy law hmodelTotal
        countDelta hcountDelta hcountDelta_le_one
        rewardDelta hrewardDelta hrewardDelta_le_one
        defaultState (rewardBound : Real) hrewardBound support visitFloor hfloor
        hmargin hq
  have hmodel' :
      MeasurableSet modelBadEvent ∧
        source.trajectoryMeasure modelBadEvent <=
          ENNReal.ofReal countDelta + ENNReal.ofReal rewardDelta ∧
        forall trajectory, trajectory ∉ modelBadEvent ->
          Good trajectory ∧
            adaptiveStochasticSampledEmpiricalOptimisticSuccessorExploratoryBehaviorExpectedRegret
                (mdp := mdp) (initialState := initialState) (episodes := episodes)
                trajectory defaultState rewardBudget transitionBudget
                  explorationRate hexplorationRate rounds <=
              adaptiveStochasticSampledEmpiricalOptimisticOccupancyRadiusSum
                  (mdp := mdp) (initialState := initialState) (episodes := episodes)
                  trajectory defaultState rewardBudget transitionBudget rounds +
                (rounds : Real) * exploratoryBehaviorRegretCharge mdp
                  explorationRate (rewardBound : Real) := by
    simpa [source, modelBadEvent, Good, localCountDelta, localRewardDelta,
      rewardBudget, transitionBudget] using hmodel
  have hmodelTail : source.trajectoryMeasure modelBadEvent <=
      ENNReal.ofReal (countDelta + rewardDelta) := by
    rw [ENNReal.ofReal_add hcountDelta.le hrewardDelta.le]
    exact hmodel'.2.1
  have hcountGood : forall trajectory, trajectory ∉ modelBadEvent ->
      Good trajectory ∧
        source.successorExpectedAverageRegret trajectory rounds <= expectedBound := by
    intro trajectory htrajectory
    have hgood := hmodel'.2.2 trajectory htrajectory
    refine ⟨hgood.1, ?_⟩
    have hroundsReal : 0 < (rounds : Real) := by exact_mod_cast hrounds
    have hexpected : source.successorExpectedAverageRegret trajectory rounds <=
        (adaptiveStochasticSampledEmpiricalOptimisticOccupancyRadiusSum
              (mdp := mdp) (initialState := initialState) (episodes := episodes)
              trajectory defaultState rewardBudget transitionBudget rounds +
            (rounds : Real) * exploratoryBehaviorRegretCharge mdp
              explorationRate (rewardBound : Real)) /
          (rounds : Real) := by
      rw [show source.successorExpectedAverageRegret trajectory rounds =
          adaptiveStochasticSampledEmpiricalOptimisticSuccessorExploratoryBehaviorExpectedRegret
              (mdp := mdp) (initialState := initialState) (episodes := episodes)
              trajectory defaultState rewardBudget transitionBudget
                explorationRate hexplorationRate rounds /
            (rounds : Real) by
        simpa [source] using
          exploratorySource_successorExpectedAverageRegret_eq_sampledPlanExploratoryBehaviorExpectedRegret
            rewardSource initialTable defaultState rewardBudget transitionBudget
              explorationRate hexplorationRate trajectory rounds]
      exact div_le_div_of_nonneg_right hgood.2 hroundsReal.le
    exact hexpected.trans_eq
      (adaptiveStochasticSampledEmpiricalOptimistic_occupancyAndChargeAverage_eq_selfConsistentBudgetAverageBound
        (mdp := mdp) (initialState := initialState) (episodes := episodes)
        trajectory defaultState localCountDelta visitFloor (rewardBound : Real)
          rewardBudget explorationRate rounds hrounds)
  have htransport :=
    source.trajectoryMeasure_expected_to_realized_successor_average_regret_transport_two_delta
      rounds hrounds hepisodes rewardBound varianceProxy hrewardBound law
        hreturnTotal (countDelta + rewardDelta) returnDelta hreturnDelta
        hreturnDelta_le_one modelBadEvent expectedBound Good hmodel'.1
        hmodelTail hcountGood
  simpa [source, modelBadEvent, returnBadEvent, combinedBadEvent, expectedBound,
    Good, localCountDelta, localRewardDelta, rewardBudget, transitionBudget,
    ENNReal.ofReal_add hcountDelta.le hrewardDelta.le] using htransport

end AdaptiveStochasticSampledEmpiricalOptimisticSource

end FiniteHorizonRL
end BanditRLProof
