import BanditRLProof.RL.FiniteHorizonStochasticRewardConditionalLaw
import BanditRLProof.ConcentrationSubGaussian
import Mathlib.Probability.Process.Adapted

/-!
# Finite-horizon stochastic reward head concentration

This module transports a selected reward-kernel sub-Gaussian law through the
compiled generated-head conditional distribution.  It exposes the centered
head reward as a conditional and unconditional sub-Gaussian random variable,
then specializes the existing finite-sum concentration route to a one-step
two-sided tail.
-/

open MeasureTheory
open scoped ProbabilityTheory

universe u v

namespace BanditRLProof
namespace FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]

namespace MDP

/-- The selected mean reward at the first coordinate of a positive trace. -/
def headRewardMean (mdp : MDP State Action) (state : State)
    (remaining : Nat) :
    RewardStepTrace Action State (remaining + 1) -> Real :=
  fun trace => mdp.reward state
    (RewardStepTrace.headAction
      (Action := Action) (State := State) remaining trace)

theorem measurable_headRewardMean (mdp : MDP State Action) (state : State)
    (remaining : Nat) :
    Measurable (mdp.headRewardMean state remaining) := by
  exact mdp.measurable_reward.comp
    (measurable_const.prodMk
      (RewardStepTrace.measurable_headAction remaining))

/-- The selected head mean is measurable in the sigma-algebra generated by the head action. -/
theorem measurable_headRewardMean_comap_headAction
    (mdp : MDP State Action) (state : State) (remaining : Nat) :
    @Measurable (RewardStepTrace Action State (remaining + 1)) Real
      (MeasurableSpace.comap
        (RewardStepTrace.headAction
          (Action := Action) (State := State) remaining)
        inferInstance)
      inferInstance
      (mdp.headRewardMean state remaining) := by
  have hrewardAt : Measurable (fun action : Action => mdp.reward state action) :=
    mdp.measurable_reward.comp (measurable_const.prodMk measurable_id)
  exact hrewardAt.comp (Measurable.of_comap_le le_rfl)

/-- Actual first sampled reward centered by the mean of its selected action law. -/
def headRewardDeviation (mdp : MDP State Action) (state : State)
    (remaining : Nat) :
    RewardStepTrace Action State (remaining + 1) -> Real :=
  fun trace =>
    RewardStepTrace.headReward
        (Action := Action) (State := State) remaining trace -
      mdp.headRewardMean state remaining trace

theorem measurable_headRewardDeviation
    (mdp : MDP State Action) (state : State) (remaining : Nat) :
    Measurable (mdp.headRewardDeviation state remaining) := by
  exact (RewardStepTrace.measurable_headReward remaining).sub
    (mdp.measurable_headRewardMean state remaining)

namespace MeanCompatibleRewardKernel

variable {mdp : MDP State Action}

/-- Every selected reward law is sub-Gaussian around its stored MDP mean with one common proxy. -/
structure UniformSubgaussianRewardLaw
    (source : MeanCompatibleRewardKernel mdp) (varianceProxy : NNReal) : Prop where
  hasSubgaussianMGF : forall state action,
    ProbabilityTheory.HasSubgaussianMGF
      (fun reward : Real => reward - mdp.reward state action)
      varianceProxy
      (source.rewardKernel.kernel (state, action))

/-- A common selected-reward interval constructs a uniform Hoeffding proxy. -/
theorem uniformSubgaussianRewardLaw_of_mem_Icc
    (source : MeanCompatibleRewardKernel mdp) (lo hi : Real)
    (hbound : forall state action,
      ∀ᵐ reward ∂ source.rewardKernel.kernel (state, action),
        reward ∈ Set.Icc lo hi) :
    source.UniformSubgaussianRewardLaw
      (Concentration.intervalVarianceProxy lo hi) := by
  constructor
  intro state action
  letI : IsProbabilityMeasure
      (source.rewardKernel.kernel (state, action)) :=
    RewardKernel.isProbabilityMeasure_apply source.rewardKernel (state, action)
  exact
    Concentration.boundedCentered_hasSubgaussianMGF_of_mem_Icc_integral_eq
      (source.rewardKernel.kernel (state, action))
      measurable_id.aemeasurable (hbound state action)
      (source.integral_reward_eq state action)

/-- The first generated reward deviation is conditionally sub-Gaussian given its sampled action. -/
theorem stochasticTrajectoryKernelRemaining_headRewardDeviation_hasCondSubgaussianMGF
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [Nonempty Action]
    (source : MeanCompatibleRewardKernel mdp)
    (policy : MarkovPolicy mdp)
    (remaining : Nat) (hremaining : remaining + 1 <= mdp.horizon)
    (state : State) (varianceProxy : NNReal)
    (law : source.UniformSubgaussianRewardLaw varianceProxy) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (MeasurableSpace.comap
        (RewardStepTrace.headAction
          (Action := Action) (State := State) remaining)
        inferInstance)
      (RewardStepTrace.measurable_headAction remaining).comap_le
      (mdp.headRewardDeviation state remaining)
      varianceProxy
      (source.stochasticTrajectoryKernelRemaining policy
        (remaining + 1) hremaining state) := by
  letI : Nonempty State := ⟨state⟩
  let target : RewardStepTrace Action State (remaining + 1) -> Measure Real :=
    fun trace => source.selectedRewardKernelAt state
      (RewardStepTrace.headAction
        (Action := Action) (State := State) remaining trace)
  have htarget : ∀ᵐ trace ∂
      (source.stochasticTrajectoryKernelRemaining policy
        (remaining + 1) hremaining state).trim
        (RewardStepTrace.measurable_headAction remaining).comap_le,
      ProbabilityTheory.HasSubgaussianMGF
        (fun reward : Real => reward - mdp.headRewardMean state remaining trace)
        varianceProxy (target trace) := by
    exact Filter.Eventually.of_forall fun trace => by
      simpa [target, selectedRewardKernelAt, MDP.headRewardMean] using
        law.hasSubgaussianMGF state
          (RewardStepTrace.headAction
            (Action := Action) (State := State) remaining trace)
  simpa [MDP.headRewardDeviation] using
    (ConditionalExpectationReward.hasCondSubgaussianMGF_centered_of_condExpKernel_map_eq
      (source.stochasticTrajectoryKernelRemaining policy
        (remaining + 1) hremaining state)
      (MeasurableSpace.comap
        (RewardStepTrace.headAction
          (Action := Action) (State := State) remaining)
        inferInstance)
      (RewardStepTrace.measurable_headAction remaining).comap_le
      (RewardStepTrace.headReward
        (Action := Action) (State := State) remaining)
      (mdp.headRewardMean state remaining)
      varianceProxy
      (RewardStepTrace.measurable_headReward remaining)
      (mdp.measurable_headRewardMean_comap_headAction state remaining)
      target
      (source.stochasticTrajectoryKernelRemaining_condExpKernel_map_headReward_given_headAction
        policy remaining hremaining state)
      htarget)

/-- The conditional head deviation law also gives its unconditional sub-Gaussian MGF. -/
theorem stochasticTrajectoryKernelRemaining_headRewardDeviation_hasSubgaussianMGF
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [Nonempty Action]
    (source : MeanCompatibleRewardKernel mdp)
    (policy : MarkovPolicy mdp)
    (remaining : Nat) (hremaining : remaining + 1 <= mdp.horizon)
    (state : State) (varianceProxy : NNReal)
    (law : source.UniformSubgaussianRewardLaw varianceProxy) :
    ProbabilityTheory.HasSubgaussianMGF
      (mdp.headRewardDeviation state remaining)
      varianceProxy
      (source.stochasticTrajectoryKernelRemaining policy
        (remaining + 1) hremaining state) := by
  letI : Nonempty State := ⟨state⟩
  have hzeroGlobal : ProbabilityTheory.HasSubgaussianMGF
      (fun _trace : RewardStepTrace Action State (remaining + 1) => 0) 0
      (source.stochasticTrajectoryKernelRemaining policy
        (remaining + 1) hremaining state) := by
    exact ProbabilityTheory.HasSubgaussianMGF.fun_zero
  have hzero := ProbabilityTheory.HasSubgaussianMGF.trim
    (RewardStepTrace.measurable_headAction remaining).comap_le
    measurable_const hzeroGlobal
  have hcond :=
    source.stochasticTrajectoryKernelRemaining_headRewardDeviation_hasCondSubgaussianMGF
      policy remaining hremaining state varianceProxy law
  have hsum :=
    ProbabilityTheory.HasSubgaussianMGF.add_of_hasCondSubgaussianMGF
      (RewardStepTrace.measurable_headAction remaining).comap_le hzero hcond
  have hzero_add :
      (fun _trace : RewardStepTrace Action State (remaining + 1) => 0) +
          mdp.headRewardDeviation state remaining =
        mdp.headRewardDeviation state remaining := by
    funext trace
    simp
  rw [hzero_add, zero_add] at hsum
  exact hsum

/-- One-step two-sided delta tail for the generated head reward deviation. -/
theorem stochasticTrajectoryKernelRemaining_headRewardDeviation_abs_tail_le
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [Nonempty Action]
    (source : MeanCompatibleRewardKernel mdp)
    (policy : MarkovPolicy mdp)
    (remaining : Nat) (hremaining : remaining + 1 <= mdp.horizon)
    (state : State) (varianceProxy : NNReal)
    (law : source.UniformSubgaussianRewardLaw varianceProxy)
    (hvariance : 0 < (varianceProxy : Real))
    (delta : Real) (hdelta : 0 < delta) (hdelta_le_one : delta <= 1) :
    (source.stochasticTrajectoryKernelRemaining policy
      (remaining + 1) hremaining state)
      {trace |
        Concentration.subGaussianSumConfidenceRadius varianceProxy delta <=
          |mdp.headRewardDeviation state remaining trace|} <=
      ENNReal.ofReal delta := by
  letI : Nonempty State := ⟨state⟩
  let mu := source.stochasticTrajectoryKernelRemaining policy
    (remaining + 1) hremaining state
  let F : Filtration Nat
      (inferInstance : MeasurableSpace
        (RewardStepTrace Action State (remaining + 1))) :=
    Filtration.const Nat inferInstance le_rfl
  let Y : Nat -> RewardStepTrace Action State (remaining + 1) -> Real :=
    fun _ => mdp.headRewardDeviation state remaining
  let cY : Nat -> NNReal := fun _ => varianceProxy
  have hadapted : StronglyAdapted F Y := by
    intro i
    simpa [F, Y] using
      (mdp.measurable_headRewardDeviation state remaining).stronglyMeasurable
  have hzero : ProbabilityTheory.HasSubgaussianMGF (Y 0) (cY 0) mu := by
    simpa [Y, cY, mu] using
      source.stochasticTrajectoryKernelRemaining_headRewardDeviation_hasSubgaussianMGF
        policy remaining hremaining state varianceProxy law
  have hsucc : forall i, i < 1 - 1 ->
      ProbabilityTheory.HasCondSubgaussianMGF
        (F i) (F.le i) (Y (i + 1)) (cY (i + 1)) mu := by
    intro i hi
    omega
  have hvarianceSum :
      0 < ((((Finset.range 1).sum cY : NNReal) : Real)) := by
    simpa [cY] using hvariance
  simpa [mu, Y, cY] using
    (Concentration.condSubGaussian_sum_abs_tail_ennreal_delta_of_stronglyAdapted
      hadapted hzero 1 hsucc hvarianceSum delta hdelta hdelta_le_one)

end MeanCompatibleRewardKernel
end MDP
end FiniteHorizonRL
end BanditRLProof
