import BanditRLProof.RL.FiniteHorizonNaturalCausalBehaviorExpectedRegretHighProbabilityLogRate
import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticSelfConsistentCausalRealizedSuccessorRegret

/-!
# Fixed-prefix high-probability natural causal realized behavior regret

This module converts the compiled fixed-prefix logarithmic behavior-expected
regret route into a realized route on the same heterogeneous dependent causal
source.  Natural round `t` uses the sample average of the actual successor
batch at coordinate `t + 1`, generated by the exploratory policy selected from
the prefix through `t`.

The return process keeps coordinate zero equal to zero and divides each
globally centered successor-batch return by its own positive batch size.
Mathlib's scalar sub-Gaussian MGF transport therefore multiplies the existing
conditional proxy by the square of that reciprocal.  The existing
strongly-adapted finite-sum theorem gives a fixed-prefix two-sided return tail.

Regularity: finite nonempty measurable State/Action with measurable
singletons, a probability initial law, Standard Borel source spaces, positive
round count and scheduled batch sizes, bounded stored means, a uniform
selected-reward sub-Gaussian law, positive horizon/proxy/base floor, and
exploratory path support.

Failure policy: preserve the actual causal source, successor indexing, global
initial-law centering, schedule-specific batch sizes, and separate model and
return failure shares.  This is fixed-prefix control of batch-average realized
behavior regret.  It is not arbitrary-delta model control, a one-raw-episode
online process, uniform-time/anytime control, minimax/optimal-rate regret, or a
complete UCB-VI theorem.
-/

open Filter MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal ProbabilityTheory Topology BigOperators

namespace BanditRLProof.FiniteHorizonRL

universe u v

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace HeterogeneousAdaptiveStochasticEpisodeBatchSource

/--
Successor return deviation divided by the actual successor batch size.
Coordinate zero is a dummy zero so coordinate `n + 1` remains conditioned on
the prefix filtration at `n`.
-/
noncomputable def naturalSuccessorAverageReturnDeviationIncrement
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (round : Nat)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :
    Real :=
  match round with
  | 0 => 0
  | n + 1 =>
      ((episodes (n + 1) : Real)⁻¹) *
        source.successorGlobalReturnIncrement (n + 1) trajectory

/-- Exact square-scaled conditional proxy for the normalized increment. -/
noncomputable def naturalSuccessorAverageReturnVarianceProxyAt
    (mdp : MDP State Action) (episodes : Nat -> Nat) (round : Nat)
    (rewardBound rewardVarianceProxy : NNReal) : NNReal :=
  match round with
  | 0 => 0
  | n + 1 =>
      ((episodes (n + 1) : NNReal)⁻¹) ^ 2 *
        mdp.iidGlobalSampledCumulativeReturnDeviationVarianceProxy
          (episodes (n + 1)) rewardBound rewardVarianceProxy

/-- Total proxy for normalized successor sample-average deviations. -/
noncomputable def naturalCumulativeSuccessorAverageReturnVarianceProxy
    (mdp : MDP State Action) (episodes : Nat -> Nat) (rounds : Nat)
    (rewardBound rewardVarianceProxy : NNReal) : NNReal :=
  ∑ t ∈ Finset.range (rounds + 1),
    naturalSuccessorAverageReturnVarianceProxyAt mdp episodes t
      rewardBound rewardVarianceProxy

/-- Cumulative normalized deviation over natural successor rounds. -/
noncomputable def naturalCumulativeSuccessorAverageReturnDeviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :
    Real :=
  ∑ t ∈ Finset.range (rounds + 1),
    source.naturalSuccessorAverageReturnDeviationIncrement t trajectory

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The normalized successor return process is strongly adapted to `piLE`. -/
theorem naturalSuccessorAverageReturnDeviationIncrement_stronglyAdapted_piLE
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability] :
    StronglyAdapted
      (Filtration.piLE
        (X := fun n : Nat => StochasticEpisodeBatch mdp (episodes n)))
      source.naturalSuccessorAverageReturnDeviationIncrement := by
  intro round
  cases round with
  | zero =>
      simpa [naturalSuccessorAverageReturnDeviationIncrement] using
        (stronglyMeasurable_const :
          StronglyMeasurable[
            Filtration.piLE
              (X := fun n : Nat => StochasticEpisodeBatch mdp (episodes n)) 0]
            (fun _ : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes =>
              (0 : Real)))
  | succ n =>
      simpa [naturalSuccessorAverageReturnDeviationIncrement] using
        ((source.successorGlobalReturnIncrement_stronglyAdapted_piLE (n + 1)).const_mul
          ((episodes (n + 1) : Real)⁻¹))

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The normalized cumulative return deviation is measurable. -/
theorem measurable_naturalCumulativeSuccessorAverageReturnDeviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) :
    Measurable (source.naturalCumulativeSuccessorAverageReturnDeviation rounds) := by
  unfold naturalCumulativeSuccessorAverageReturnDeviation
  refine Finset.measurable_sum (Finset.range (rounds + 1)) fun t _ => ?_
  exact
    (((source.naturalSuccessorAverageReturnDeviationIncrement_stronglyAdapted_piLE t).mono
      ((Filtration.piLE
        (X := fun n : Nat => StochasticEpisodeBatch mdp (episodes n))).le t)).measurable)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
/-- Scalar transport of the selected conditional successor-return MGF. -/
theorem naturalSuccessorAverageReturnDeviationIncrement_succ_hasCondSubgaussianMGF
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability] (n : Nat)
    [StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [Nonempty (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [StandardBorelSpace
      (StochasticEpisodeBatch mdp (episodes (n + 1)))]
    [Nonempty (StochasticEpisodeBatch mdp (episodes (n + 1)))]
    [StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)]
    (rewardBound rewardVarianceProxy : NNReal)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= (rewardBound : Real))
    (law : source.rewardSource.UniformSubgaussianRewardLaw
      rewardVarianceProxy) :
    HasCondSubgaussianMGF
      (Filtration.piLE
        (X := fun k : Nat => StochasticEpisodeBatch mdp (episodes k)) n)
      ((Filtration.piLE
        (X := fun k : Nat => StochasticEpisodeBatch mdp (episodes k))).le n)
      (source.naturalSuccessorAverageReturnDeviationIncrement (n + 1))
      (naturalSuccessorAverageReturnVarianceProxyAt mdp episodes (n + 1)
        rewardBound rewardVarianceProxy)
      source.trajectoryMeasure := by
  have hbase :=
    source.successorGlobalReturnIncrement_succ_hasCondSubgaussianMGF
      n rewardBound rewardVarianceProxy hrewardBound law
  simpa [naturalSuccessorAverageReturnDeviationIncrement,
    naturalSuccessorAverageReturnVarianceProxyAt] using
      hbase.const_mul ((episodes (n + 1) : Real)⁻¹)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- A positive prefix has positive normalized total return proxy. -/
theorem naturalCumulativeSuccessorAverageReturnVarianceProxy_pos
    (mdp : MDP State Action) (episodes : Nat -> Nat) (rounds : Nat)
    (rewardBound rewardVarianceProxy : NNReal)
    (hrounds : 0 < rounds) (hepisodes : forall n, 0 < episodes n)
    (hrewardBound_pos : 0 < rewardBound) (hhorizon : 0 < mdp.horizon) :
    0 < ((naturalCumulativeSuccessorAverageReturnVarianceProxy mdp episodes
      rounds rewardBound rewardVarianceProxy : NNReal) : Real) := by
  let cY : Nat -> NNReal := fun t =>
    naturalSuccessorAverageReturnVarianceProxyAt mdp episodes t
      rewardBound rewardVarianceProxy
  have hepisodesOneReal : 0 < (episodes 1 : Real) := by
    exact_mod_cast hepisodes 1
  have hepisodesOneNN : 0 < (episodes 1 : NNReal) := by
    exact_mod_cast hepisodes 1
  have hscale : 0 <
      ((episodes 1 : NNReal)⁻¹) ^ 2 := by
    exact pow_pos (inv_pos.mpr hepisodesOneNN) 2
  have hbase : 0 <
      mdp.iidGlobalSampledCumulativeReturnDeviationVarianceProxy
        (episodes 1) rewardBound rewardVarianceProxy := by
    rw [MDP.iidGlobalSampledCumulativeReturnDeviationVarianceProxy_eq]
    exact mul_pos (by exact_mod_cast hepisodes 1)
      (mdp.globalReturnDeviationPerEpisodeVarianceProxy_pos
        rewardBound rewardVarianceProxy hrewardBound_pos hhorizon)
  have hcoordinate : 0 < cY 1 := by
    simpa [cY, naturalSuccessorAverageReturnVarianceProxyAt] using
      mul_pos hscale hbase
  have hcoordinate_le : cY 1 <=
      ∑ t ∈ Finset.range (rounds + 1), cY t :=
    Finset.single_le_sum (fun t _ => zero_le (cY t))
      (Finset.mem_range.mpr (Nat.succ_lt_succ hrounds))
  have hpositive : 0 < ∑ t ∈ Finset.range (rounds + 1), cY t :=
    hcoordinate.trans_le hcoordinate_le
  exact_mod_cast (show 0 <
    naturalCumulativeSuccessorAverageReturnVarianceProxy mdp episodes
      rounds rewardBound rewardVarianceProxy by
        simpa [cY, naturalCumulativeSuccessorAverageReturnVarianceProxy] using
          hpositive)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
/-- Fixed-prefix two-sided tail for normalized successor sample-average returns. -/
theorem trajectoryMeasure_naturalCumulativeSuccessorAverageReturnDeviation_abs_tail_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [forall n, StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, Nonempty
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, StandardBorelSpace
      (StochasticEpisodeBatch mdp (episodes n))]
    [forall n, Nonempty (StochasticEpisodeBatch mdp (episodes n))]
    [StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)]
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) (rewardBound rewardVarianceProxy : NNReal)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= (rewardBound : Real))
    (law : source.rewardSource.UniformSubgaussianRewardLaw
      rewardVarianceProxy)
    (htotal : 0 <
      ((naturalCumulativeSuccessorAverageReturnVarianceProxy mdp episodes rounds
        rewardBound rewardVarianceProxy : NNReal) : Real))
    (delta : Real) (hdelta : 0 < delta) (hdelta_le_one : delta <= 1) :
    source.trajectoryMeasure
        {trajectory |
          Concentration.subGaussianSumConfidenceRadius
              (naturalCumulativeSuccessorAverageReturnVarianceProxy mdp episodes
                rounds rewardBound rewardVarianceProxy) delta <=
            |source.naturalCumulativeSuccessorAverageReturnDeviation
              rounds trajectory|} <=
      ENNReal.ofReal delta := by
  let F := Filtration.piLE
    (X := fun n : Nat => StochasticEpisodeBatch mdp (episodes n))
  let cY : Nat -> NNReal := fun t =>
    naturalSuccessorAverageReturnVarianceProxyAt mdp episodes t
      rewardBound rewardVarianceProxy
  have hadapted : StronglyAdapted F
      source.naturalSuccessorAverageReturnDeviationIncrement := by
    simpa [F] using
      source.naturalSuccessorAverageReturnDeviationIncrement_stronglyAdapted_piLE
  have hzero : HasSubgaussianMGF
      (source.naturalSuccessorAverageReturnDeviationIncrement 0) (cY 0)
      source.trajectoryMeasure := by
    change HasSubgaussianMGF (fun _ => 0) 0 source.trajectoryMeasure
    exact HasSubgaussianMGF.fun_zero
  have hsucc : forall i, i < (rounds + 1) - 1 ->
      HasCondSubgaussianMGF
        (F i) (F.le i)
        (source.naturalSuccessorAverageReturnDeviationIncrement (i + 1))
        (cY (i + 1)) source.trajectoryMeasure := by
    intro i _hi
    simpa [F, cY] using
      source.naturalSuccessorAverageReturnDeviationIncrement_succ_hasCondSubgaussianMGF
        i rewardBound rewardVarianceProxy hrewardBound law
  have hvariance :
      0 < ((((Finset.range (rounds + 1)).sum cY : NNReal) : Real)) := by
    simpa [cY, naturalCumulativeSuccessorAverageReturnVarianceProxy] using htotal
  simpa [naturalCumulativeSuccessorAverageReturnVarianceProxy,
    naturalCumulativeSuccessorAverageReturnDeviation, cY] using
    (Concentration.condSubGaussian_sum_abs_tail_ennreal_delta_of_stronglyAdapted
      hadapted hzero (rounds + 1) hsucc hvariance
      delta hdelta hdelta_le_one)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The dummy-zero process is exactly the natural successor-round sum. -/
theorem naturalCumulativeSuccessorAverageReturnDeviation_eq_sum_range
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) :
    source.naturalCumulativeSuccessorAverageReturnDeviation rounds trajectory =
      ∑ t ∈ Finset.range rounds,
        ((episodes (t + 1) : Real)⁻¹) *
          source.successorGlobalReturnIncrement (t + 1) trajectory := by
  unfold naturalCumulativeSuccessorAverageReturnDeviation
  rw [Finset.sum_range_succ']
  simp [naturalSuccessorAverageReturnDeviationIncrement]

/-- Realized regret of the sample average in successor batch `t + 1`. -/
noncomputable def naturalSuccessorBatchAverageRealizedRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (_source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (t : Nat) : Real :=
  AdaptiveStochasticEpisodeBatchSource.optimalInitialExpectedReturn
      mdp initialState -
    mdp.sampledCumulativeRewardSum (episodes (t + 1)) (trajectory (t + 1)) /
      (episodes (t + 1) : Real)

/-- Natural-prefix cumulative successor-batch-average realized regret. -/
noncomputable def naturalCumulativeRealizedBehaviorRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  ∑ t ∈ Finset.range rounds,
    source.naturalSuccessorBatchAverageRealizedRegret trajectory t

/-- Natural-prefix round-average realized behavior regret. -/
noncomputable def naturalAverageRealizedBehaviorRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  source.naturalCumulativeRealizedBehaviorRegret trajectory rounds /
    (rounds : Real)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- A successor-batch-average realized-regret coordinate is measurable. -/
theorem measurable_naturalSuccessorBatchAverageRealizedRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (t : Nat) :
    Measurable (fun trajectory =>
      source.naturalSuccessorBatchAverageRealizedRegret trajectory t) := by
  unfold naturalSuccessorBatchAverageRealizedRegret
  exact measurable_const.sub
    (((mdp.measurable_sampledCumulativeRewardSum (episodes (t + 1))).comp
      (measurable_pi_apply (t + 1))).div_const (episodes (t + 1) : Real))

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- The natural cumulative realized behavior-regret process is measurable. -/
theorem measurable_naturalCumulativeRealizedBehaviorRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat) :
    Measurable (fun trajectory =>
      source.naturalCumulativeRealizedBehaviorRegret trajectory rounds) := by
  unfold naturalCumulativeRealizedBehaviorRegret
  exact Finset.measurable_sum (Finset.range rounds) fun t _ =>
    source.measurable_naturalSuccessorBatchAverageRealizedRegret t

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- The natural round-average realized behavior-regret process is measurable. -/
theorem measurable_naturalAverageRealizedBehaviorRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat) :
    Measurable (fun trajectory =>
      source.naturalAverageRealizedBehaviorRegret trajectory rounds) := by
  unfold naturalAverageRealizedBehaviorRegret
  exact (source.measurable_naturalCumulativeRealizedBehaviorRegret rounds).div_const
    (rounds : Real)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- Exact one-round batch-average realized/expected/deviation identity. -/
theorem naturalSuccessorBatchAverageRealizedRegret_eq_expected_sub_deviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (t : Nat) (hepisodes : 0 < episodes (t + 1)) :
    source.naturalSuccessorBatchAverageRealizedRegret trajectory t =
      (source.successorPolicyAt trajectory t).expectedRegret initialState -
        source.naturalSuccessorAverageReturnDeviationIncrement (t + 1)
          trajectory := by
  simp only [naturalSuccessorAverageReturnDeviationIncrement]
  rw [source.successorGlobalReturnIncrement_succ_eq trajectory t]
  unfold naturalSuccessorBatchAverageRealizedRegret
    MarkovPolicy.expectedRegret
    AdaptiveStochasticEpisodeBatchSource.optimalInitialExpectedReturn
  rw [(source.successorPolicyAt trajectory t).integral_cumulativeReward_trajectoryMeasure_eq_integral_valueAt_zero]
  have hepisodesReal : (episodes (t + 1) : Real) ≠ 0 := by
    exact_mod_cast (ne_of_gt hepisodes)
  field_simp [hepisodesReal]
  all_goals ring

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- Exact natural-prefix cumulative expected-minus-normalized-deviation identity. -/
theorem naturalCumulativeRealizedBehaviorRegret_eq_expected_sub_deviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) (hepisodes : forall n, 0 < episodes n) :
    source.naturalCumulativeRealizedBehaviorRegret trajectory rounds =
      (∑ t ∈ Finset.range rounds,
          (source.successorPolicyAt trajectory t).expectedRegret initialState) -
        source.naturalCumulativeSuccessorAverageReturnDeviation rounds
          trajectory := by
  rw [source.naturalCumulativeSuccessorAverageReturnDeviation_eq_sum_range]
  unfold naturalCumulativeRealizedBehaviorRegret
  calc
    (∑ t ∈ Finset.range rounds,
        source.naturalSuccessorBatchAverageRealizedRegret trajectory t) =
        ∑ t ∈ Finset.range rounds,
          ((source.successorPolicyAt trajectory t).expectedRegret initialState -
            ((episodes (t + 1) : Real)⁻¹) *
              source.successorGlobalReturnIncrement (t + 1) trajectory) := by
      apply Finset.sum_congr rfl
      intro t _ht
      simpa [naturalSuccessorAverageReturnDeviationIncrement] using
        source.naturalSuccessorBatchAverageRealizedRegret_eq_expected_sub_deviation
          trajectory t (hepisodes (t + 1))
    _ = (∑ t ∈ Finset.range rounds,
          (source.successorPolicyAt trajectory t).expectedRegret initialState) -
        ∑ t ∈ Finset.range rounds,
          ((episodes (t + 1) : Real)⁻¹) *
            source.successorGlobalReturnIncrement (t + 1) trajectory := by
      rw [Finset.sum_sub_distrib]

end HeterogeneousAdaptiveStochasticEpisodeBatchSource

namespace AdaptiveStochasticSampledEmpiricalOptimisticSource

/-- Self-consistent normalized successor-return proxy for a natural prefix. -/
noncomputable def selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
    (mdp : MDP State Action) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) : NNReal :=
  HeterogeneousAdaptiveStochasticEpisodeBatchSource.naturalCumulativeSuccessorAverageReturnVarianceProxy
    mdp
    (fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
        mdp varianceProxy baseVisitFloor t)
    rounds 1 varianceProxy

/-- Normalized successor-return deviation on the self-consistent causal source. -/
noncomputable def selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    HeterogeneousStochasticEpisodeBatchTrajectory mdp
        (fun t =>
          AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
            mdp varianceProxy baseVisitFloor t) -> Real :=
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  source.naturalCumulativeSuccessorAverageReturnDeviation rounds

/-- Natural cumulative successor-batch-average realized behavior regret. -/
noncomputable def selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    HeterogeneousStochasticEpisodeBatchTrajectory mdp
        (fun t =>
          AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
            mdp varianceProxy baseVisitFloor t) -> Real :=
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  fun trajectory =>
    source.naturalCumulativeRealizedBehaviorRegret trajectory rounds

/-- Natural round-average successor-batch-average realized behavior regret. -/
noncomputable def selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    HeterogeneousStochasticEpisodeBatchTrajectory mdp
        (fun t =>
          AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
            mdp varianceProxy baseVisitFloor t) -> Real :=
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  fun trajectory => source.naturalAverageRealizedBehaviorRegret trajectory rounds

/-- Fixed-prefix two-sided normalized return-deviation event. -/
noncomputable def selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  {trajectory |
    Concentration.subGaussianSumConfidenceRadius
        (selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
          mdp varianceProxy baseVisitFloor rounds) returnDelta <=
      |selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory|}

/-- The self-consistent normalized return-deviation process is measurable. -/
theorem measurable_selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    Measurable
      (selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds) := by
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  letI : source.GlobalReturnMeasurability := by
    dsimp [source, selfConsistentScheduledCausalSource]
    infer_instance
  simpa [selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess,
    source] using
      source.measurable_naturalCumulativeSuccessorAverageReturnDeviation rounds

/-- The natural cumulative batch-average realized-regret process is measurable. -/
theorem measurable_selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    Measurable
      (selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds) := by
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  simpa [selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess,
    source] using source.measurable_naturalCumulativeRealizedBehaviorRegret rounds

/-- The natural round-average batch-average realized-regret process is measurable. -/
theorem measurable_selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    Measurable
      (selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds) := by
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  simpa [selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess,
    source] using source.measurable_naturalAverageRealizedBehaviorRegret rounds

/-- The fixed-prefix normalized return event is measurable. -/
theorem measurableSet_selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    MeasurableSet
      (selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent mdp
        initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta) := by
  unfold selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent
  exact measurableSet_le measurable_const
    (measurable_selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds).abs

/-- Exact natural-prefix cumulative realized/expected/deviation identity. -/
theorem selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_eq_expected_sub_deviation
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory =
      selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory -
        selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory := by
  let episodes := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
      mdp varianceProxy baseVisitFloor t
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  have hidentity :=
    source.naturalCumulativeRealizedBehaviorRegret_eq_expected_sub_deviation
      trajectory rounds
        (fun n =>
          AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes_pos
            mdp varianceProxy baseVisitFloor n)
  simpa [selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess,
    selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess,
    selfConsistentScheduledNaturalCausalSuccessorPolicyExpectedRegretProcess,
    selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess,
    source, episodes] using hidentity

/-- Exact natural-prefix round-average realized/expected/deviation identity. -/
theorem selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess_eq_expected_sub_deviation
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :
    selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory =
      (selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory -
        selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory) / (rounds : Real) := by
  simpa [selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess,
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.naturalAverageRealizedBehaviorRegret,
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess] using
    congrArg (fun value : Real => value / (rounds : Real))
      (selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_eq_expected_sub_deviation
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory)

/-- The self-consistent normalized return event has its exact return share. -/
theorem selfConsistentScheduledCausalSource_trajectoryMeasure_naturalCumulativeReturnBadEvent_le
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (baseVisitFloor : Real)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (rounds : Nat) (hrounds : 0 < rounds)
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1) :
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    source.trajectoryMeasure
        (selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent mdp
          initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds returnDelta) <=
      ENNReal.ofReal returnDelta := by
  dsimp only
  let episodes := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
      mdp varianceProxy baseVisitFloor t
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  letI : source.GlobalReturnMeasurability := by
    dsimp [source, selfConsistentScheduledCausalSource]
    infer_instance
  have hepisodes : forall t, 0 < episodes t := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes_pos
      mdp varianceProxy baseVisitFloor t
  have htotal : 0 <
      ((HeterogeneousAdaptiveStochasticEpisodeBatchSource.naturalCumulativeSuccessorAverageReturnVarianceProxy
        mdp episodes rounds 1 varianceProxy : NNReal) : Real) :=
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.naturalCumulativeSuccessorAverageReturnVarianceProxy_pos
      mdp episodes rounds 1 varianceProxy hrounds hepisodes one_pos hhorizon
  have hrewardBoundNN : forall state action,
      |mdp.reward state action| <= ((1 : NNReal) : Real) := by
    simpa using hrewardBound
  simpa [source, episodes,
    selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent,
    selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy,
    selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess] using
    source.trajectoryMeasure_naturalCumulativeSuccessorAverageReturnDeviation_abs_tail_le
      rounds 1 varianceProxy hrewardBoundNN law htotal returnDelta
        hreturnDelta hreturnDelta_le_one

/-- Logarithmic model rate plus the normalized successor-return radius. -/
noncomputable def selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
    (mdp : MDP State Action) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) : Real :=
  selfConsistentScheduledNaturalCausalLogarithmicCumulativeIntegratedBehaviorExpectedRegretRate
      mdp rounds +
    Concentration.subGaussianSumConfidenceRadius
      (selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
        mdp varianceProxy baseVisitFloor rounds) returnDelta

/-- Round-average form of the fixed-prefix realized logarithmic rate. -/
noncomputable def selfConsistentScheduledNaturalCausalRealizedAverageLogarithmicRate
    (mdp : MDP State Action) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) : Real :=
  selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
    mdp varianceProxy baseVisitFloor rounds returnDelta / (rounds : Real)

/-- Union of the actual finite-prefix model event and normalized return event. -/
noncomputable def selfConsistentScheduledNaturalCausalModelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  selfConsistentScheduledCausalModelBadEvent mdp initialState rewardSource
      initialTable defaultState varianceProxy baseVisitFloor rounds ∪
    selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent mdp
      initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta

/-- One-sided cumulative realized-regret violation set. -/
noncomputable def selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  {trajectory |
    selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
        mdp varianceProxy baseVisitFloor rounds returnDelta <
      selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory}

/-- One-sided round-average realized-regret violation set. -/
noncomputable def selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  {trajectory |
    selfConsistentScheduledNaturalCausalRealizedAverageLogarithmicRate
        mdp varianceProxy baseVisitFloor rounds returnDelta <
      selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory}

/-- The cumulative realized-regret violation set is Borel measurable. -/
theorem measurableSet_selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    MeasurableSet
      (selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta) := by
  unfold selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
  exact measurableSet_lt measurable_const
    (measurable_selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds)

/-- The average realized-regret violation set is Borel measurable. -/
theorem measurableSet_selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    MeasurableSet
      (selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta) := by
  unfold selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
  exact measurableSet_lt measurable_const
    (measurable_selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds)

/-- The model/return union is measurable and obeys the sum of its two shares. -/
theorem selfConsistentScheduledCausalSource_trajectoryMeasure_naturalModelReturnBadEvent_le
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds)
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1) :
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    let event := selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp
      initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta
    MeasurableSet event ∧
      source.trajectoryMeasure event <=
        selfConsistentScheduledCausalModelFailureBudget mdp rounds +
          ENNReal.ofReal returnDelta := by
  dsimp only
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  let modelEvent := selfConsistentScheduledCausalModelBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
  let returnEvent := selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent mdp
    initialState rewardSource initialTable defaultState varianceProxy
      baseVisitFloor rounds returnDelta
  have hmodel :=
    selfConsistentScheduledCausalSource_trajectoryMeasure_allCoordinateConfidence_optimism_and_recommendedExpectedRegret
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds
  have hreturnMeasurable : MeasurableSet returnEvent := by
    simpa [returnEvent] using
      (measurableSet_selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta)
  have hreturnTail : source.trajectoryMeasure returnEvent <=
      ENNReal.ofReal returnDelta := by
    simpa [source, returnEvent] using
      (selfConsistentScheduledCausalSource_trajectoryMeasure_naturalCumulativeReturnBadEvent_le
        mdp initialState rewardSource varianceProxy law initialTable defaultState
          baseVisitFloor hrewardBound hhorizon rounds hrounds returnDelta
            hreturnDelta hreturnDelta_le_one)
  refine ⟨?_, ?_⟩
  · simpa [selfConsistentScheduledNaturalCausalModelReturnBadEvent,
      modelEvent, returnEvent] using hmodel.1.union hreturnMeasurable
  · have hunion : source.trajectoryMeasure (modelEvent ∪ returnEvent) <=
        source.trajectoryMeasure modelEvent +
          source.trajectoryMeasure returnEvent :=
      measure_union_le modelEvent returnEvent
    have hsum := add_le_add hmodel.2.1 hreturnTail
    simpa [selfConsistentScheduledNaturalCausalModelReturnBadEvent,
      modelEvent, returnEvent, source] using hunion.trans hsum

/-- Outside the joint event, cumulative realized regret obeys the explicit rate. -/
theorem selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (returnDelta : Real)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t))
    (htrajectory : trajectory ∉
      selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp initialState
        rewardSource initialTable defaultState varianceProxy baseVisitFloor
          rounds returnDelta) :
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory <=
      selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
        mdp varianceProxy baseVisitFloor rounds returnDelta := by
  let modelEvent := selfConsistentScheduledCausalModelBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
  let returnEvent := selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent mdp
    initialState rewardSource initialTable defaultState varianceProxy
      baseVisitFloor rounds returnDelta
  have hnotModel : trajectory ∉ modelEvent := by
    intro hmodel
    exact htrajectory (by
      simpa [selfConsistentScheduledNaturalCausalModelReturnBadEvent,
        modelEvent, returnEvent] using Set.mem_union_left returnEvent hmodel)
  have hnotReturn : trajectory ∉ returnEvent := by
    intro hreturn
    exact htrajectory (by
      simpa [selfConsistentScheduledNaturalCausalModelReturnBadEvent,
        modelEvent, returnEvent] using Set.mem_union_right modelEvent hreturn)
  have hexpected :=
    selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess_le_logarithmic_of_not_mem_modelBadEvent
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds trajectory (by simpa [modelEvent] using hnotModel)
  have hnotRadius : ¬
      Concentration.subGaussianSumConfidenceRadius
          (selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
            mdp varianceProxy baseVisitFloor rounds) returnDelta <=
        |selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory| := by
    simpa [returnEvent,
      selfConsistentScheduledNaturalCausalCumulativeReturnBadEvent] using hnotReturn
  have hnoise :
      -selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory <=
        Concentration.subGaussianSumConfidenceRadius
          (selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
            mdp varianceProxy baseVisitFloor rounds) returnDelta :=
    (neg_le_abs _).trans (lt_of_not_ge hnotRadius).le
  rw [selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_eq_expected_sub_deviation
    mdp initialState rewardSource initialTable defaultState varianceProxy
      baseVisitFloor rounds trajectory]
  calc
    selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory -
        selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory =
      selfConsistentScheduledNaturalCausalCumulativeBehaviorExpectedRegretProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory +
        (-selfConsistentScheduledNaturalCausalCumulativeReturnDeviationProcess
          mdp initialState rewardSource initialTable defaultState varianceProxy
            baseVisitFloor rounds trajectory) := by ring
    _ <= selfConsistentScheduledNaturalCausalLogarithmicCumulativeIntegratedBehaviorExpectedRegretRate
          mdp rounds +
        Concentration.subGaussianSumConfidenceRadius
          (selfConsistentScheduledNaturalCausalCumulativeReturnVarianceProxy
            mdp varianceProxy baseVisitFloor rounds) returnDelta :=
      add_le_add hexpected hnoise
    _ = selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
          mdp varianceProxy baseVisitFloor rounds returnDelta := rfl

/-- Outside the joint event, average realized regret obeys the divided rate. -/
theorem selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds) (returnDelta : Real)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t))
    (htrajectory : trajectory ∉
      selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp initialState
        rewardSource initialTable defaultState varianceProxy baseVisitFloor
          rounds returnDelta) :
    selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds trajectory <=
      selfConsistentScheduledNaturalCausalRealizedAverageLogarithmicRate
        mdp varianceProxy baseVisitFloor rounds returnDelta := by
  have hcumulative :=
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds returnDelta trajectory htrajectory
  have hroundsNonneg : (0 : Real) <= (rounds : Real) := by positivity
  simpa [selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess,
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.naturalAverageRealizedBehaviorRegret,
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess,
    selfConsistentScheduledNaturalCausalRealizedAverageLogarithmicRate] using
      div_le_div_of_nonneg_right hcumulative hroundsNonneg

/-- Every cumulative realized-regret violation lies in the joint event. -/
theorem selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet_subset_modelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (returnDelta : Real) :
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta ⊆
      selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp initialState
        rewardSource initialTable defaultState varianceProxy baseVisitFloor
          rounds returnDelta := by
  intro trajectory hviolation
  by_contra hgood
  have hbound :=
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds returnDelta trajectory hgood
  exact (not_lt_of_ge hbound) hviolation

/-- Every average realized-regret violation lies in the joint event. -/
theorem selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet_subset_modelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds) (returnDelta : Real) :
    selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta ⊆
      selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp initialState
        rewardSource initialTable defaultState varianceProxy baseVisitFloor
          rounds returnDelta := by
  intro trajectory hviolation
  by_contra hgood
  have hbound :=
    selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds hrounds returnDelta trajectory hgood
  exact (not_lt_of_ge hbound) hviolation

/-
Terminal fixed-prefix realized route.  The model/return event and both
one-sided realized-regret violation sets are measurable, both violations are
covered by the joint event, all three probabilities use the sum of the actual
model budget and the caller's return share, and every joint-good trajectory
has the cumulative and round-average logarithmic certificates.
-/
theorem selfConsistentScheduledCausalSource_fixedPrefixHighProbabilityLogarithmicCumulativeAverageRealizedBehaviorRegret
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds)
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1) :
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    let event := selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp
      initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta
    let cumulativeViolation :=
      selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta
    let averageViolation :=
      selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
        mdp initialState rewardSource initialTable defaultState varianceProxy
          baseVisitFloor rounds returnDelta
    let failureBudget :=
      selfConsistentScheduledCausalModelFailureBudget mdp rounds +
        ENNReal.ofReal returnDelta
    MeasurableSet event ∧
      MeasurableSet cumulativeViolation ∧
      MeasurableSet averageViolation ∧
      source.trajectoryMeasure event <= failureBudget ∧
      cumulativeViolation ⊆ event ∧
      averageViolation ⊆ event ∧
      source.trajectoryMeasure cumulativeViolation <= failureBudget ∧
      source.trajectoryMeasure averageViolation <= failureBudget ∧
      (failureBudget < 1 ->
        source.trajectoryMeasure event < 1 ∧
        source.trajectoryMeasure cumulativeViolation < 1 ∧
        source.trajectoryMeasure averageViolation < 1) ∧
      ∀ trajectory, trajectory ∉ event ->
        selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess
            mdp initialState rewardSource initialTable defaultState varianceProxy
              baseVisitFloor rounds trajectory <=
          selfConsistentScheduledNaturalCausalRealizedCumulativeLogarithmicRate
            mdp varianceProxy baseVisitFloor rounds returnDelta ∧
        selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess
            mdp initialState rewardSource initialTable defaultState varianceProxy
              baseVisitFloor rounds trajectory <=
          selfConsistentScheduledNaturalCausalRealizedAverageLogarithmicRate
            mdp varianceProxy baseVisitFloor rounds returnDelta := by
  dsimp only
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  let event := selfConsistentScheduledNaturalCausalModelReturnBadEvent mdp
    initialState rewardSource initialTable defaultState varianceProxy
      baseVisitFloor rounds returnDelta
  let cumulativeViolation :=
    selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta
  let averageViolation :=
    selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta
  let failureBudget :=
    selfConsistentScheduledCausalModelFailureBudget mdp rounds +
      ENNReal.ofReal returnDelta
  have hjoint :=
    selfConsistentScheduledCausalSource_trajectoryMeasure_naturalModelReturnBadEvent_le
      mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
        defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
          hbaseVisitFloor rounds hrounds returnDelta hreturnDelta
            hreturnDelta_le_one
  have hcumulativeSubset : cumulativeViolation ⊆ event := by
    simpa [cumulativeViolation, event] using
      (selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet_subset_modelReturnBadEvent
        mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
          defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
            hbaseVisitFloor rounds returnDelta)
  have haverageSubset : averageViolation ⊆ event := by
    simpa [averageViolation, event] using
      (selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet_subset_modelReturnBadEvent
        mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
          defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
            hbaseVisitFloor rounds hrounds returnDelta)
  have heventTail : source.trajectoryMeasure event <= failureBudget := by
    simpa [source, event, failureBudget] using hjoint.2
  have hcumulativeTail : source.trajectoryMeasure cumulativeViolation <=
      failureBudget := (measure_mono hcumulativeSubset).trans heventTail
  have haverageTail : source.trajectoryMeasure averageViolation <=
      failureBudget := (measure_mono haverageSubset).trans heventTail
  refine ⟨by simpa [event] using hjoint.1,
    measurableSet_selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretLogarithmicViolationSet
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta,
    measurableSet_selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretLogarithmicViolationSet
      mdp initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta,
    heventTail, hcumulativeSubset, haverageSubset,
    hcumulativeTail, haverageTail, ?_, ?_⟩
  · intro hbudget
    exact ⟨heventTail.trans_lt hbudget, hcumulativeTail.trans_lt hbudget,
      haverageTail.trans_lt hbudget⟩
  intro trajectory htrajectory
  refine ⟨?_, ?_⟩
  · exact
      selfConsistentScheduledNaturalCausalCumulativeRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
        mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
          defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
            hbaseVisitFloor rounds returnDelta trajectory (by simpa [event] using htrajectory)
  · exact
      selfConsistentScheduledNaturalCausalAverageRealizedBehaviorRegretProcess_le_logarithmic_of_not_mem_modelReturnBadEvent
        mdp initialState rewardSource varianceProxy hvarianceProxy law initialTable
          defaultState support baseVisitFloor hbaseFloor hrewardBound hhorizon
            hbaseVisitFloor rounds hrounds returnDelta trajectory
              (by simpa [event] using htrajectory)

end AdaptiveStochasticSampledEmpiricalOptimisticSource

end BanditRLProof.FiniteHorizonRL
