import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticSelfConsistentCausalSource
import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticConfidence
import BanditRLProof.RL.FiniteHorizonStochasticRewardIIDSelfConsistentCalibration

/-!
# Empirical-model confidence on the heterogeneous causal source

This module transports actual sampled count-and-reward empirical-model events
to the dependent source whose coordinate `t` contains `episodes t` complete
stochastic episodes.  Unlike the constant-window route, local count and reward
shares are functions of the coordinate.  The fixed-prefix failure budget is
therefore their genuine finite `ENNReal` sum.

Coordinate zero is generated by the initial exploratory policy.  Coordinate
`n + 1` is generated by the policy selected from the prefix through `n`.
Exact iid fibers and the prefix/next `compProd` law give each coordinate its
own model-event bound without assuming independence between adaptive rounds.

Regularity is finite measurable nonempty State/Action with measurable
singletons, a probability initial law, Standard Borel State/Action for the iid
model-confidence parent, positive batch sizes and reward proxy, and positive
local shares at most one.  Concrete event measurability additionally uses the
compiled measurable heterogeneous optimistic-table selector.

Failure policy: preserve actual sampled rewards, coordinate-specific batch
sizes and shares, generating-policy indexing, and the finite failure-budget
sum.  No constant-window rate, independence across rounds, uniform-time,
pathwise, almost-sure, anytime, minimax, reachability, or complete-UCB-VI claim
is inferred.
-/

open MeasureTheory
open scoped ENNReal NNReal ProbabilityTheory BigOperators

universe u v

namespace BanditRLProof.FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace HeterogeneousAdaptiveStochasticEpisodeBatchSource

/-- Policy whose exact iid law generated coordinate `t`. -/
def policyAt
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :
    Nat -> MarkovPolicy mdp
  | 0 => source.initialPolicy
  | n + 1 => source.successorPolicy n (Preorder.frestrictLe n trajectory)

/-- Pull an initial heterogeneous-batch event back to the causal trajectory. -/
def initialBadEvent
    {mdp : MDP State Action} {episodes : Nat -> Nat}
    (bad : Set (StochasticEpisodeBatch mdp (episodes 0))) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :=
  (Function.eval 0) ⁻¹' bad

/-- Pull a prefix-dependent successor event back to the causal trajectory. -/
def successorBadEvent
    {mdp : MDP State Action} {episodes : Nat -> Nat} (n : Nat)
    (bad : Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
      StochasticEpisodeBatch mdp (episodes (n + 1)))) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :=
  (fun trajectory =>
    (Preorder.frestrictLe n trajectory, trajectory (n + 1))) ⁻¹' bad

/-- Coordinate-indexed adapted heterogeneous-batch event. -/
def roundBadEvent
    {mdp : MDP State Action} {episodes : Nat -> Nat}
    (initialBad : Set (StochasticEpisodeBatch mdp (episodes 0)))
    (successorBad : (n : Nat) ->
      Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
        StochasticEpisodeBatch mdp (episodes (n + 1)))) :
    Nat -> Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
  | 0 => initialBadEvent initialBad
  | n + 1 => successorBadEvent n (successorBad n)

/-- Union of the first `rounds` heterogeneous adapted events. -/
def finiteHorizonBadEvent
    {mdp : MDP State Action} {episodes : Nat -> Nat}
    (rounds : Nat)
    (initialBad : Set (StochasticEpisodeBatch mdp (episodes 0)))
    (successorBad : (n : Nat) ->
      Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
        StochasticEpisodeBatch mdp (episodes (n + 1)))) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :=
  ⋃ round : Fin rounds, roundBadEvent initialBad successorBad round

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Measurability of the finite heterogeneous adapted union. -/
theorem measurableSet_finiteHorizonBadEvent
    {mdp : MDP State Action} {episodes : Nat -> Nat} {rounds : Nat}
    {initialBad : Set (StochasticEpisodeBatch mdp (episodes 0))}
    {successorBad : (n : Nat) ->
      Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
        StochasticEpisodeBatch mdp (episodes (n + 1)))}
    (hinitial : MeasurableSet initialBad)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (successorBad n)) :
    MeasurableSet
      (finiteHorizonBadEvent rounds initialBad successorBad) := by
  refine MeasurableSet.iUnion fun round => ?_
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          exact hinitial.preimage (measurable_pi_apply 0)
      | succ n =>
          exact (hsuccessor n hvalue).preimage (by fun_prop)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Exact mass of a pulled-back initial heterogeneous-batch event. -/
theorem trajectoryMeasure_initialBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    {bad : Set (StochasticEpisodeBatch mdp (episodes 0))}
    (hbad : MeasurableSet bad) :
    source.trajectoryMeasure (initialBadEvent bad) =
      source.rewardSource.iidStochasticTrajectoryFamilyMeasure
        source.initialPolicy initialState (episodes 0) bad := by
  change source.trajectoryMeasure ((Function.eval 0) ⁻¹' bad) = _
  rw [← Measure.map_apply (measurable_pi_apply 0) hbad]
  rw [source.trajectoryMeasure_map_eval_zero]

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- A successor event inherits a uniform bound on every selected history fiber. -/
theorem trajectoryMeasure_successorBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (n : Nat)
    {bad : Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
      StochasticEpisodeBatch mdp (episodes (n + 1)))}
    (hbad : MeasurableSet bad) (budget : ENNReal)
    (hfiber : forall history,
      source.batchKernel n history (Prod.mk history ⁻¹' bad) <= budget) :
    source.trajectoryMeasure (successorBadEvent n bad) <= budget := by
  let prefixMeasure :=
    source.trajectoryMeasure.map (Preorder.frestrictLe n)
  let pairMap : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes ->
      HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
        StochasticEpisodeBatch mdp (episodes (n + 1)) :=
    fun trajectory =>
      (Preorder.frestrictLe n trajectory, trajectory (n + 1))
  have hpairMap : Measurable pairMap := by fun_prop
  haveI : IsProbabilityMeasure prefixMeasure := by
    dsimp only [prefixMeasure]
    exact Measure.isProbabilityMeasure_map (by fun_prop)
  calc
    source.trajectoryMeasure (successorBadEvent n bad) =
        source.trajectoryMeasure.map pairMap bad := by
      rw [Measure.map_apply hpairMap hbad]
      rfl
    _ = (prefixMeasure ⊗ₘ source.batchKernel n) bad := by
      rw [source.trajectoryMeasure_prefix_compProd n]
    _ = ∫⁻ history, source.batchKernel n history
          (Prod.mk history ⁻¹' bad) ∂prefixMeasure :=
      Measure.compProd_apply hbad
    _ <= ∫⁻ _history, budget ∂prefixMeasure :=
      lintegral_mono hfiber
    _ = budget := by simp [prefixMeasure]

/-- Initial selected empirical-model event with coordinate-specific shares. -/
noncomputable def initialAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real) :
    Set (StochasticEpisodeBatch mdp (episodes 0)) :=
  source.rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
    source.initialPolicy initialState (episodes 0) varianceProxy
      (countDelta 0) (rewardDelta 0)

/-- Prefix-selected successor empirical-model event with local shares. -/
noncomputable def successorAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real) (n : Nat) :
    Set (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
      StochasticEpisodeBatch mdp (episodes (n + 1))) :=
  {pair | pair.2 ∈
    source.rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
      (source.successorPolicy n pair.1) initialState (episodes (n + 1))
        varianceProxy (countDelta (n + 1)) (rewardDelta (n + 1))}

/-- First-`rounds` selected count-and-reward empirical-model event. -/
noncomputable def adaptiveAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :=
  finiteHorizonBadEvent rounds
    (source.initialAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta)
    (source.successorAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta)

/-- Exact finite sum of coordinate-specific count and reward failure shares. -/
noncomputable def cumulativeModelFailureBudget
    (rounds : Nat) (countDelta rewardDelta : Nat -> Real) : ENNReal :=
  ∑ round : Fin rounds,
    (ENNReal.ofReal (countDelta round) + ENNReal.ofReal (rewardDelta round))

/-- The initial coordinate event is measurable. -/
theorem measurableSet_initialAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real) :
    MeasurableSet (source.initialAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta) := by
  exact
    source.rewardSource.measurableSet_stochasticAllCoordinateEmpiricalModelBadEvent
      source.initialPolicy initialState (episodes 0) varianceProxy
        (countDelta 0) (rewardDelta 0)

/-- Selected successor measurability closes the finite heterogeneous event. -/
theorem measurableSet_adaptiveAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (source.successorAllCoordinateEmpiricalModelBadEvent
        varianceProxy countDelta rewardDelta n)) :
    MeasurableSet (source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta) := by
  exact measurableSet_finiteHorizonBadEvent
    (source.measurableSet_initialAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta)
    hsuccessor

/-- The initial selected iid fiber receives its coordinate shares. -/
theorem initialAllCoordinateEmpiricalModelBadEvent_le
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (hepisodes : 0 < episodes 0)
    (varianceProxy : NNReal)
    (law : source.rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (htotal : 0 < ((((episodes 0 : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta rewardDelta : Nat -> Real)
    (hcountDelta : 0 < countDelta 0) (hcountDelta_le_one : countDelta 0 <= 1)
    (hrewardDelta : 0 < rewardDelta 0)
    (hrewardDelta_le_one : rewardDelta 0 <= 1) :
    (source.rewardSource.iidStochasticTrajectoryFamilyMeasure
      source.initialPolicy initialState (episodes 0))
        (source.initialAllCoordinateEmpiricalModelBadEvent
          varianceProxy countDelta rewardDelta) <=
      ENNReal.ofReal (countDelta 0) + ENNReal.ofReal (rewardDelta 0) := by
  exact
    source.rewardSource.iidStochasticTrajectoryFamilyMeasure_stochasticAllCoordinateEmpiricalModelBadEvent_le
      source.initialPolicy initialState (episodes 0) hepisodes varianceProxy law
        htotal (countDelta 0) hcountDelta hcountDelta_le_one
        (rewardDelta 0) hrewardDelta hrewardDelta_le_one

/-- Every selected successor iid fiber receives its coordinate shares. -/
theorem successorAllCoordinateEmpiricalModelBadEvent_fiber_le
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (varianceProxy : NNReal)
    (law : source.rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (countDelta rewardDelta : Nat -> Real) (n : Nat)
    (hepisodes : 0 < episodes (n + 1))
    (htotal : 0 <
      ((((episodes (n + 1) : NNReal) * varianceProxy : NNReal) : Real)))
    (hcountDelta : 0 < countDelta (n + 1))
    (hcountDelta_le_one : countDelta (n + 1) <= 1)
    (hrewardDelta : 0 < rewardDelta (n + 1))
    (hrewardDelta_le_one : rewardDelta (n + 1) <= 1)
    (history : HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n) :
    source.batchKernel n history
        (Prod.mk history ⁻¹'
          source.successorAllCoordinateEmpiricalModelBadEvent
            varianceProxy countDelta rewardDelta n) <=
      ENNReal.ofReal (countDelta (n + 1)) +
        ENNReal.ofReal (rewardDelta (n + 1)) := by
  rw [source.batchKernel_eq_iidStochasticTrajectoryFamilyMeasure]
  change
    (source.rewardSource.iidStochasticTrajectoryFamilyMeasure
      (source.successorPolicy n history) initialState (episodes (n + 1)))
        (source.rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
          (source.successorPolicy n history) initialState (episodes (n + 1))
            varianceProxy (countDelta (n + 1)) (rewardDelta (n + 1))) <= _
  exact
    source.rewardSource.iidStochasticTrajectoryFamilyMeasure_stochasticAllCoordinateEmpiricalModelBadEvent_le
      (source.successorPolicy n history) initialState (episodes (n + 1))
        hepisodes varianceProxy law htotal
        (countDelta (n + 1)) hcountDelta hcountDelta_le_one
        (rewardDelta (n + 1)) hrewardDelta hrewardDelta_le_one

/-
Finite-prefix heterogeneous count-and-reward confidence.  No independence
between coordinates is used; every successor is integrated through its exact
selected iid history fiber.
-/
theorem trajectoryMeasure_adaptiveAllCoordinateEmpiricalModelBadEvent_le
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) (rounds : Nat)
    (hepisodes : forall t, 0 < episodes t) (varianceProxy : NNReal)
    (law : source.rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (htotal : forall t,
      0 < ((((episodes t : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta rewardDelta : Nat -> Real)
    (hcountDelta : forall t, t < rounds -> 0 < countDelta t)
    (hcountDelta_le_one : forall t, t < rounds -> countDelta t <= 1)
    (hrewardDelta : forall t, t < rounds -> 0 < rewardDelta t)
    (hrewardDelta_le_one : forall t, t < rounds -> rewardDelta t <= 1)
    (hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (source.successorAllCoordinateEmpiricalModelBadEvent
        varianceProxy countDelta rewardDelta n)) :
    source.trajectoryMeasure
        (source.adaptiveAllCoordinateEmpiricalModelBadEvent
          rounds varianceProxy countDelta rewardDelta) <=
      cumulativeModelFailureBudget rounds countDelta rewardDelta := by
  let initialBad := source.initialAllCoordinateEmpiricalModelBadEvent
    varianceProxy countDelta rewardDelta
  let successorBad := source.successorAllCoordinateEmpiricalModelBadEvent
    varianceProxy countDelta rewardDelta
  have hinitialMeasurable : MeasurableSet initialBad := by
    exact source.measurableSet_initialAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta
  have hroundTail : forall round : Fin rounds,
      source.trajectoryMeasure (roundBadEvent initialBad successorBad round) <=
        ENNReal.ofReal (countDelta round) +
          ENNReal.ofReal (rewardDelta round) := by
    intro round
    cases round with
    | mk value hvalue =>
        cases value with
        | zero =>
            rw [roundBadEvent,
              source.trajectoryMeasure_initialBadEvent hinitialMeasurable]
            exact source.initialAllCoordinateEmpiricalModelBadEvent_le
              (hepisodes 0) varianceProxy law (htotal 0)
                countDelta rewardDelta
                (hcountDelta 0 hvalue) (hcountDelta_le_one 0 hvalue)
                (hrewardDelta 0 hvalue) (hrewardDelta_le_one 0 hvalue)
        | succ n =>
            exact source.trajectoryMeasure_successorBadEvent_le n
              (hsuccessor n hvalue)
              (ENNReal.ofReal (countDelta (n + 1)) +
                ENNReal.ofReal (rewardDelta (n + 1)))
              (fun history =>
                source.successorAllCoordinateEmpiricalModelBadEvent_fiber_le
                  varianceProxy law countDelta rewardDelta n
                    (hepisodes (n + 1)) (htotal (n + 1))
                    (hcountDelta (n + 1) hvalue)
                    (hcountDelta_le_one (n + 1) hvalue)
                    (hrewardDelta (n + 1) hvalue)
                    (hrewardDelta_le_one (n + 1) hvalue) history)
  calc
    source.trajectoryMeasure
        (source.adaptiveAllCoordinateEmpiricalModelBadEvent
          rounds varianceProxy countDelta rewardDelta) <=
        ∑ round : Fin rounds,
          source.trajectoryMeasure
            (roundBadEvent initialBad successorBad round) := by
      simpa [adaptiveAllCoordinateEmpiricalModelBadEvent,
        finiteHorizonBadEvent, initialBad, successorBad] using
          (ProbabilityUnionBound.measure_iUnion_fintype_le_sum
            source.trajectoryMeasure
            (fun round : Fin rounds =>
              roundBadEvent initialBad successorBad round))
    _ <= ∑ round : Fin rounds,
        (ENNReal.ofReal (countDelta round) +
          ENNReal.ofReal (rewardDelta round)) :=
      Finset.sum_le_sum fun round _ => hroundTail round
    _ = cumulativeModelFailureBudget rounds countDelta rewardDelta := rfl

omit [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- Outside the finite event, every batch avoids its generating-policy event. -/
theorem policyAt_batch_not_mem_allCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) (varianceProxy : NNReal)
    (countDelta rewardDelta : Nat -> Real)
    (htrajectory : trajectory ∉
      source.adaptiveAllCoordinateEmpiricalModelBadEvent
        rounds varianceProxy countDelta rewardDelta)
    (round : Fin rounds) :
    trajectory round ∉
      source.rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
        (source.policyAt trajectory round) initialState (episodes round)
          varianceProxy (countDelta round) (rewardDelta round) := by
  have hround : trajectory ∉ roundBadEvent
      (source.initialAllCoordinateEmpiricalModelBadEvent
        varianceProxy countDelta rewardDelta)
      (source.successorAllCoordinateEmpiricalModelBadEvent
        varianceProxy countDelta rewardDelta) round := by
    intro hmem
    apply htrajectory
    exact Set.mem_iUnion_of_mem round hmem
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          simpa [roundBadEvent, initialBadEvent,
            initialAllCoordinateEmpiricalModelBadEvent, policyAt] using hround
      | succ n =>
          simpa [roundBadEvent, successorBadEvent,
            successorAllCoordinateEmpiricalModelBadEvent, policyAt] using hround

end HeterogeneousAdaptiveStochasticEpisodeBatchSource

namespace AdaptiveStochasticSampledEmpiricalOptimisticSource

/-- Concrete heterogeneous successor events are measurable. -/
theorem heterogeneousExploratorySource_measurableSet_successorAllCoordinateEmpiricalModelBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (rewardBudget transitionBudget : Nat -> Real)
    (explorationRate : Nat -> NNReal)
    (hexplorationRate : forall t, explorationRate t <= 1)
    (varianceProxy : NNReal) (countDelta rewardDelta : Nat -> Real)
    (n : Nat) :
    let source := heterogeneousExploratorySource mdp initialState episodes
      rewardSource initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    MeasurableSet (source.successorAllCoordinateEmpiricalModelBadEvent
      varianceProxy countDelta rewardDelta n) := by
  dsimp only
  change MeasurableSet
    {pair : HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n ×
        StochasticEpisodeBatch mdp (episodes (n + 1)) |
      pair.2 ∈ rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
        ((heterogeneousSuccessorTable defaultState rewardBudget transitionBudget
          n pair.1).exploratoryPolicy
            (explorationRate (n + 1)) (hexplorationRate (n + 1)))
        initialState (episodes (n + 1)) varianceProxy
          (countDelta (n + 1)) (rewardDelta (n + 1))}
  exact
    measurableSet_selectedExploratoryStochasticAllCoordinateEmpiricalModelBadEvent
      rewardSource
      (heterogeneousSuccessorTable defaultState rewardBudget transitionBudget n)
      (measurable_heterogeneousSuccessorTable
        defaultState rewardBudget transitionBudget n)
      (explorationRate (n + 1)) (hexplorationRate (n + 1)) varianceProxy
      (countDelta (n + 1)) (rewardDelta (n + 1))

/-- Concrete heterogeneous source event and its finite failure-budget bound. -/
theorem heterogeneousExploratorySource_trajectoryMeasure_adaptiveAllCoordinateEmpiricalModelBadEvent_le
    [StandardBorelSpace State] [StandardBorelSpace Action]
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (rewardBudget transitionBudget : Nat -> Real)
    (explorationRate : Nat -> NNReal)
    (hexplorationRate : forall t, explorationRate t <= 1)
    (rounds : Nat) (hepisodes : forall t, 0 < episodes t)
    (varianceProxy : NNReal)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (htotal : forall t,
      0 < ((((episodes t : NNReal) * varianceProxy : NNReal) : Real)))
    (countDelta rewardDelta : Nat -> Real)
    (hcountDelta : forall t, t < rounds -> 0 < countDelta t)
    (hcountDelta_le_one : forall t, t < rounds -> countDelta t <= 1)
    (hrewardDelta : forall t, t < rounds -> 0 < rewardDelta t)
    (hrewardDelta_le_one : forall t, t < rounds -> rewardDelta t <= 1) :
    let source := heterogeneousExploratorySource mdp initialState episodes
      rewardSource initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    let event := source.adaptiveAllCoordinateEmpiricalModelBadEvent
      rounds varianceProxy countDelta rewardDelta
    MeasurableSet event ∧
      source.trajectoryMeasure event <=
        HeterogeneousAdaptiveStochasticEpisodeBatchSource.cumulativeModelFailureBudget
          rounds countDelta rewardDelta := by
  dsimp only
  let source := heterogeneousExploratorySource mdp initialState episodes
    rewardSource initialTable defaultState rewardBudget transitionBudget
      explorationRate hexplorationRate
  have hsuccessor : forall n, n + 1 < rounds ->
      MeasurableSet (source.successorAllCoordinateEmpiricalModelBadEvent
        varianceProxy countDelta rewardDelta n) := by
    intro n _hn
    exact
      heterogeneousExploratorySource_measurableSet_successorAllCoordinateEmpiricalModelBadEvent
        rewardSource initialTable defaultState rewardBudget transitionBudget
          explorationRate hexplorationRate varianceProxy countDelta rewardDelta n
  exact
    ⟨source.measurableSet_adaptiveAllCoordinateEmpiricalModelBadEvent
        rounds varianceProxy countDelta rewardDelta hsuccessor,
      source.trajectoryMeasure_adaptiveAllCoordinateEmpiricalModelBadEvent_le
        rounds hepisodes varianceProxy law htotal countDelta rewardDelta
          hcountDelta hcountDelta_le_one hrewardDelta hrewardDelta_le_one
          hsuccessor⟩

/-- Model-confidence failure budget of the first causal schedule coordinates. -/
noncomputable def selfConsistentScheduledCausalModelFailureBudget
    (mdp : MDP State Action) (rounds : Nat) : ENNReal :=
  HeterogeneousAdaptiveStochasticEpisodeBatchSource.cumulativeModelFailureBudget
    rounds
    (AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta mdp)
    (AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta mdp)

/-- Named actual-sampled model event on the self-consistent causal source. -/
noncomputable def selfConsistentScheduledCausalModelBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  source.adaptiveAllCoordinateEmpiricalModelBadEvent rounds varianceProxy
    (AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta mdp)
    (AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta mdp)

/-
The genuine causal schedule receives coordinatewise sampled-model confidence.
Every model is computed from the actual batch at that coordinate, with the
same reward and transition budgets used by the next causal selector.
-/
theorem selfConsistentScheduledCausalSource_trajectoryMeasure_allCoordinateConfidence_optimism_and_recommendedExpectedRegret
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) :
    let episodes := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
        mdp varianceProxy baseVisitFloor t
    let rewardBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
        mdp varianceProxy baseVisitFloor t
    let transitionBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
        mdp varianceProxy baseVisitFloor t
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    let event := selfConsistentScheduledCausalModelBadEvent mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
    MeasurableSet event ∧
      source.trajectoryMeasure event <=
        selfConsistentScheduledCausalModelFailureBudget mdp rounds ∧
      forall trajectory, trajectory ∉ event -> forall round : Fin rounds,
        let t := (round : Nat)
        let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
          (episodes t)
          (mdp.sampledEpisodeBatchOfStochasticTrajectories
            (episodes t) (trajectory t))
          defaultState (rewardBudget t) (transitionBudget t)
        (forall state,
            mdp.optimalValueRemaining mdp.horizon le_rfl state <=
              model.plan.upperValueRemaining mdp.horizon le_rfl state) ∧
          model.plan.optimisticPolicy.expectedRegret initialState <=
            model.plan.optimisticPolicy.occupancySumRemaining
              (fun remaining hremaining state =>
                2 * model.plan.selectedRadiusRemaining
                  remaining hremaining state)
              mdp.horizon le_rfl initialState := by
  dsimp only
  let episodes := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
      mdp varianceProxy baseVisitFloor t
  let localDelta :=
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta mdp
  let rewardBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
      mdp varianceProxy baseVisitFloor t
  let transitionBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
      mdp varianceProxy baseVisitFloor t
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  let event := selfConsistentScheduledCausalModelBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
  have hepisodes : forall t, 0 < episodes t := by
    intro t
    exact
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes_pos
        mdp varianceProxy baseVisitFloor t
  have hlocalDeltaPos : forall t, 0 < localDelta t := by
    intro t
    exact
      AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_pos_of_pos
        (AdaptiveEpisodeBatchSource.decayingExplorationRounds_pos mdp t)
        (AdaptiveEpisodeBatchSource.vanishingAverageConfidenceDelta_pos t)
  have hlocalDeltaLeOne : forall t, localDelta t <= 1 := by
    intro t
    exact
      AdaptiveStochasticEpisodeBatchSource.multiBatchLocalDelta_le_one_of_le_one
        (AdaptiveEpisodeBatchSource.decayingExplorationRounds_pos mdp t)
        (AdaptiveEpisodeBatchSource.vanishingAverageConfidenceDelta_le_one t)
  have htotal : forall t,
      0 < ((((episodes t : NNReal) * varianceProxy : NNReal) : Real)) := by
    intro t
    have hepisodesNN : 0 < (episodes t : NNReal) := by
      exact_mod_cast hepisodes t
    exact_mod_cast mul_pos hepisodesNN hvarianceProxy
  have hevent : MeasurableSet event ∧
      source.trajectoryMeasure event <=
        selfConsistentScheduledCausalModelFailureBudget mdp rounds := by
    simpa [event, source, episodes, localDelta,
      selfConsistentScheduledCausalModelBadEvent,
      selfConsistentScheduledCausalModelFailureBudget] using
      (heterogeneousExploratorySource_trajectoryMeasure_adaptiveAllCoordinateEmpiricalModelBadEvent_le
        (episodes := episodes) rewardSource initialTable defaultState
          rewardBudget transitionBudget
          AdaptiveEpisodeBatchSource.decayingExplorationRate
          AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one
          rounds hepisodes varianceProxy law htotal localDelta localDelta
          (fun t _ht => hlocalDeltaPos t)
          (fun t _ht => hlocalDeltaLeOne t)
          (fun t _ht => hlocalDeltaPos t)
          (fun t _ht => hlocalDeltaLeOne t))
  refine ⟨hevent.1, hevent.2, ?_⟩
  intro trajectory htrajectory round
  have hnot :=
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.policyAt_batch_not_mem_allCoordinateEmpiricalModelBadEvent
      source trajectory rounds varianceProxy localDelta localDelta
        (by simpa [event, source, localDelta,
          selfConsistentScheduledCausalModelBadEvent] using htrajectory)
        round
  cases round with
  | mk value hvalue =>
      cases value with
      | zero =>
          have hschedule :=
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduled_countMargin_and_halfContraction
              mdp defaultState varianceProxy hhorizon hbaseVisitFloor 0
          have hfixed :=
            initialTable.exploratoryPolicy_iidStochasticTrajectoryFamilyMeasure_allCoordinate_optimism_and_expectedRegret_of_pathSupport_selfConsistentCalibration
              rewardSource initialState
              (AdaptiveEpisodeBatchSource.decayingExplorationRate 0)
              (AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one 0)
              (episodes 0) (hepisodes 0) varianceProxy law (htotal 0)
              (localDelta 0) (hlocalDeltaPos 0) (hlocalDeltaLeOne 0)
              (localDelta 0) (hlocalDeltaPos 0) (hlocalDeltaLeOne 0)
              defaultState 1 hrewardBound support
              (AdaptiveEpisodeBatchSource.decayingExplorationVisitFloor
                mdp baseVisitFloor 0)
              (AdaptiveEpisodeBatchSource.decayingExplorationUniformVisitFloor
                support hbaseFloor 0)
              (by simpa [episodes, localDelta,
                AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta]
                using hschedule.1)
              (lt_of_le_of_lt
                (by simpa [episodes, localDelta,
                  AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta]
                  using hschedule.2)
                (by norm_num))
          have hnot' : trajectory 0 ∉
              rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
                (initialTable.exploratoryPolicy
                  (AdaptiveEpisodeBatchSource.decayingExplorationRate 0)
                  (AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one 0))
                initialState (episodes 0) varianceProxy
                  (localDelta 0) (localDelta 0) := by
            simpa [source, episodes,
              HeterogeneousAdaptiveStochasticEpisodeBatchSource.policyAt,
              selfConsistentScheduledCausalSource,
              heterogeneousExploratorySource] using hnot
          simpa [episodes, rewardBudget, transitionBudget,
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget,
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget,
            localDelta] using hfixed.2.2 (trajectory 0) hnot'
      | succ n =>
          let table := heterogeneousSuccessorTable defaultState rewardBudget
            transitionBudget n (Preorder.frestrictLe n trajectory)
          have hschedule :=
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduled_countMargin_and_halfContraction
              mdp defaultState varianceProxy hhorizon hbaseVisitFloor (n + 1)
          have hfixed :=
            table.exploratoryPolicy_iidStochasticTrajectoryFamilyMeasure_allCoordinate_optimism_and_expectedRegret_of_pathSupport_selfConsistentCalibration
              rewardSource initialState
              (AdaptiveEpisodeBatchSource.decayingExplorationRate (n + 1))
              (AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one (n + 1))
              (episodes (n + 1)) (hepisodes (n + 1)) varianceProxy law
              (htotal (n + 1))
              (localDelta (n + 1)) (hlocalDeltaPos (n + 1))
              (hlocalDeltaLeOne (n + 1))
              (localDelta (n + 1)) (hlocalDeltaPos (n + 1))
              (hlocalDeltaLeOne (n + 1)) defaultState 1 hrewardBound support
              (AdaptiveEpisodeBatchSource.decayingExplorationVisitFloor
                mdp baseVisitFloor (n + 1))
              (AdaptiveEpisodeBatchSource.decayingExplorationUniformVisitFloor
                support hbaseFloor (n + 1))
              (by simpa [episodes, localDelta,
                AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta]
                using hschedule.1)
              (lt_of_le_of_lt
                (by simpa [episodes, localDelta,
                  AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledLocalDelta]
                  using hschedule.2)
                (by norm_num))
          have hnot' : trajectory (n + 1) ∉
              rewardSource.stochasticAllCoordinateEmpiricalModelBadEvent
                (table.exploratoryPolicy
                  (AdaptiveEpisodeBatchSource.decayingExplorationRate (n + 1))
                  (AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one
                    (n + 1)))
                initialState (episodes (n + 1)) varianceProxy
                  (localDelta (n + 1)) (localDelta (n + 1)) := by
            simpa [source, table, episodes, rewardBudget, transitionBudget,
              HeterogeneousAdaptiveStochasticEpisodeBatchSource.policyAt,
              selfConsistentScheduledCausalSource,
              heterogeneousExploratorySource] using hnot
          simpa [episodes, rewardBudget, transitionBudget,
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget,
            AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget,
            localDelta] using hfixed.2.2 (trajectory (n + 1)) hnot'

end AdaptiveStochasticSampledEmpiricalOptimisticSource

end BanditRLProof.FiniteHorizonRL
