import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticSelfConsistentCausalModelConfidence
import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticSelfConsistentCausalReturnConcentration
import BanditRLProof.RL.FiniteHorizonAdaptiveStochasticRewardSampledEmpiricalOptimisticCumulativeExploratoryBehaviorRegret

/-!
# Realized successor regret on the heterogeneous causal source

This module combines the actual-sampled empirical-model event with the
successor-only globally centered return event on the genuinely dependent
round-varying source.  Coordinate `n + 1` is generated by the exploratory
policy selected from the prefix through `n` and contains `episodes (n + 1)`
complete episodes.  Expected and realized successor regret are therefore
weighted by the actual coordinate batch sizes and normalized by their finite
sum, never by a constant-window `episodes * rounds` denominator.

The proof route first establishes the exact weighted identity

`realized = expected - globally centered deviation`.

Outside the model event, each sampled model at coordinate `n` supplies
optimism and recommended-policy expected-regret control.  The exploratory
policy that generates coordinate `n + 1` pays the existing explicit
exploration charge.  A finite event union with the compiled heterogeneous
return tail then yields realized successor-average behavior regret.

Regularity is finite measurable nonempty State/Action with measurable
singletons, a probability initial law, Standard Borel State/Action, positive
scheduled batch sizes, a positive selected-reward sub-Gaussian proxy, bounded
stored means, path support, and a positive horizon/base visit floor.

Failure policy: preserve the actual sampled batches, `n`-prefix to `n + 1`
policy indexing, coordinate-specific episode weights, global initial-law
centering, and the exact finite model plus return failure budget.  This is a
fixed-prefix causal theorem; it proves no old constant-window rate,
uniform-time, pathwise, almost-sure, anytime, minimax, reachability, or
complete-UCB-VI claim.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal ProbabilityTheory BigOperators

universe u v

namespace BanditRLProof.FiniteHorizonRL

variable {State : Type u} {Action : Type v}
    [MeasurableSpace State] [MeasurableSpace Action]
    [Fintype State] [Fintype Action]
    [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action]

namespace HeterogeneousAdaptiveStochasticEpisodeBatchSource

/-- The selected policy that generates successor coordinate `n + 1`. -/
noncomputable def successorPolicyAt
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (n : Nat) : MarkovPolicy mdp :=
  source.successorPolicy n (Preorder.frestrictLe n trajectory)

/-- Total number of complete episodes in successor coordinates `1..rounds`. -/
noncomputable def successorEpisodeMass
    (episodes : Nat -> Nat) (rounds : Nat) : Real :=
  ∑ round : Fin rounds, (episodes ((round : Nat) + 1) : Real)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem successorEpisodeMass_pos
    (episodes : Nat -> Nat) (rounds : Nat) (hrounds : 0 < rounds)
    (hepisodes : forall t, 0 < episodes t) :
    0 < successorEpisodeMass episodes rounds := by
  unfold successorEpisodeMass
  refine Finset.sum_pos' (fun round _ => ?_) ?_
  · exact_mod_cast (Nat.zero_le (episodes ((round : Nat) + 1)))
  · let round : Fin rounds := ⟨0, hrounds⟩
    refine ⟨round, Finset.mem_univ _, ?_⟩
    exact_mod_cast (hepisodes 1)

/-- Batch-size-weighted expected regret of the selected successor policies. -/
noncomputable def successorWeightedExpectedCumulativeRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  ∑ round : Fin rounds,
    (episodes ((round : Nat) + 1) : Real) *
      (source.successorPolicyAt trajectory round).expectedRegret initialState

/-- Weighted successor expected regret per sampled successor episode. -/
noncomputable def successorWeightedExpectedAverageRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  source.successorWeightedExpectedCumulativeRegret trajectory rounds /
    successorEpisodeMass episodes rounds

/-- Realized regret of every sampled successor batch, with its actual size. -/
noncomputable def realizedSuccessorCumulativeRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState]
    {episodes : Nat -> Nat}
    (_source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  ∑ round : Fin rounds,
    ((episodes ((round : Nat) + 1) : Real) *
        AdaptiveStochasticEpisodeBatchSource.optimalInitialExpectedReturn
          mdp initialState -
      mdp.sampledCumulativeRewardSum (episodes ((round : Nat) + 1))
        (trajectory ((round : Nat) + 1)))

/-- Realized successor regret per actual sampled successor episode. -/
noncomputable def realizedSuccessorAverageRegret
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) : Real :=
  source.realizedSuccessorCumulativeRegret trajectory rounds /
    successorEpisodeMass episodes rounds

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- A successor increment is actual return minus its selected policy mean. -/
theorem successorGlobalReturnIncrement_succ_eq
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (n : Nat) :
    source.successorGlobalReturnIncrement (n + 1) trajectory =
      mdp.sampledCumulativeRewardSum (episodes (n + 1))
          (trajectory (n + 1)) -
        (episodes (n + 1) : Real) *
          integral initialState
            ((source.successorPolicyAt trajectory n).valueAt
              0 (Nat.zero_le mdp.horizon)) := by
  simp only [successorGlobalReturnIncrement,
    successorGlobalReturnPrefixIncrement, successorGlobalReturnDeviation,
    successorPolicyAt, Preorder.frestrictLe_apply]
  exact mdp.globalSampledCumulativeReturnDeviationSum_eq
    (source.successorPolicy n (Preorder.frestrictLe n trajectory))
    initialState (episodes (n + 1)) (trajectory (n + 1))

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
/-- The global deviation is exactly the finite sum of successor increments. -/
theorem cumulativeSuccessorGlobalReturnDeviation_eq_fin_sum
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) :
    source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory =
      ∑ round : Fin rounds,
        source.successorGlobalReturnIncrement ((round : Nat) + 1)
          trajectory := by
  unfold cumulativeSuccessorGlobalReturnDeviation
  rw [Finset.sum_range_succ']
  simp only [successorGlobalReturnIncrement,
    successorGlobalReturnPrefixIncrement, add_zero]
  rw [Finset.sum_fin_eq_sum_range]
  apply Finset.sum_congr rfl
  intro round hround
  have hround_lt : round < rounds := Finset.mem_range.mp hround
  rw [dif_pos hround_lt]

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- Exact weighted realized-equals-expected-minus-deviation identity. -/
theorem realizedSuccessorCumulativeRegret_eq_expected_sub_deviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) :
    source.realizedSuccessorCumulativeRegret trajectory rounds =
      source.successorWeightedExpectedCumulativeRegret trajectory rounds -
        source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory := by
  rw [source.cumulativeSuccessorGlobalReturnDeviation_eq_fin_sum]
  unfold realizedSuccessorCumulativeRegret
    successorWeightedExpectedCumulativeRegret
  calc
    (∑ round : Fin rounds,
        ((episodes ((round : Nat) + 1) : Real) *
            AdaptiveStochasticEpisodeBatchSource.optimalInitialExpectedReturn
              mdp initialState -
          mdp.sampledCumulativeRewardSum
            (episodes ((round : Nat) + 1))
            (trajectory ((round : Nat) + 1)))) =
        ∑ round : Fin rounds,
          ((episodes ((round : Nat) + 1) : Real) *
              (source.successorPolicyAt trajectory round).expectedRegret
                initialState -
            source.successorGlobalReturnIncrement
              ((round : Nat) + 1) trajectory) := by
      apply Finset.sum_congr rfl
      intro round _hround
      rw [source.successorGlobalReturnIncrement_succ_eq]
      unfold MarkovPolicy.expectedRegret
        AdaptiveStochasticEpisodeBatchSource.optimalInitialExpectedReturn
      rw [(source.successorPolicyAt trajectory round).integral_cumulativeReward_trajectoryMeasure_eq_integral_valueAt_zero]
      ring
    _ = (∑ round : Fin rounds,
            (episodes ((round : Nat) + 1) : Real) *
              (source.successorPolicyAt trajectory round).expectedRegret
                initialState) -
          ∑ round : Fin rounds,
            source.successorGlobalReturnIncrement
              ((round : Nat) + 1) trajectory := by
      rw [Finset.sum_sub_distrib]

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] in
/-- Exact weighted average form of the realized-regret decomposition. -/
theorem realizedSuccessorAverageRegret_eq_expected_sub_deviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (rounds : Nat) (hmass : 0 < successorEpisodeMass episodes rounds) :
    source.realizedSuccessorAverageRegret trajectory rounds =
      source.successorWeightedExpectedAverageRegret trajectory rounds -
        source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory /
          successorEpisodeMass episodes rounds := by
  have hmass_ne : successorEpisodeMass episodes rounds ≠ 0 :=
    ne_of_gt hmass
  rw [realizedSuccessorAverageRegret,
    successorWeightedExpectedAverageRegret,
    source.realizedSuccessorCumulativeRegret_eq_expected_sub_deviation]
  field_simp

/-- Named successor-only global-return event for heterogeneous batches. -/
noncomputable def successorGlobalReturnDeviationBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes)
    (rounds : Nat) (rewardBound rewardVarianceProxy : NNReal)
    (delta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes) :=
  {trajectory |
    Concentration.subGaussianSumConfidenceRadius
        (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes rounds
          rewardBound rewardVarianceProxy) delta <=
      |source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory|}

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem measurable_cumulativeSuccessorGlobalReturnDeviation
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) :
    Measurable (source.cumulativeSuccessorGlobalReturnDeviation rounds) := by
  refine Finset.measurable_sum (Finset.range (rounds + 1)) fun t _ => ?_
  exact (((source.successorGlobalReturnIncrement_stronglyAdapted_piLE t).mono
    ((Filtration.piLE
      (X := fun n : Nat => StochasticEpisodeBatch mdp (episodes n))).le t)).measurable)

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action]
    [Nonempty State] [Nonempty Action] in
theorem measurableSet_successorGlobalReturnDeviationBadEvent
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) (rewardBound rewardVarianceProxy : NNReal)
    (delta : Real) :
    MeasurableSet (source.successorGlobalReturnDeviationBadEvent
      rounds rewardBound rewardVarianceProxy delta) := by
  exact measurableSet_le measurable_const
    (source.measurable_cumulativeSuccessorGlobalReturnDeviation rounds).abs

omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
theorem trajectoryMeasure_successorGlobalReturnDeviationBadEvent_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [forall n, StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, Nonempty
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, StandardBorelSpace
      (StochasticEpisodeBatch mdp (episodes n))]
    [forall n, Nonempty (StochasticEpisodeBatch mdp (episodes n))]
    [StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)]
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) (rewardBound rewardVarianceProxy : NNReal)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= (rewardBound : Real))
    (law : source.rewardSource.UniformSubgaussianRewardLaw
      rewardVarianceProxy)
    (htotal : 0 <
      ((cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes rounds
        rewardBound rewardVarianceProxy : NNReal) : Real))
    (delta : Real) (hdelta : 0 < delta) (hdelta_le_one : delta <= 1) :
    source.trajectoryMeasure
        (source.successorGlobalReturnDeviationBadEvent
          rounds rewardBound rewardVarianceProxy delta) <=
      ENNReal.ofReal delta := by
  simpa only [successorGlobalReturnDeviationBadEvent] using
    source.trajectoryMeasure_cumulativeSuccessorGlobalReturnDeviation_abs_tail_le
      rounds rewardBound rewardVarianceProxy hrewardBound law htotal
      delta hdelta hdelta_le_one

/-
Combine an arbitrary model/optimism event with the heterogeneous successor
return event.  The caller supplies a weighted expected-regret certificate;
this theorem performs only the exact expected-to-realized transport.
-/
omit [DecidableEq State] [DecidableEq Action]
    [MeasurableSingletonClass State] [MeasurableSingletonClass Action] in
theorem trajectoryMeasure_weightedExpected_to_realized_successor_average_regret_transport
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    [StandardBorelSpace State] [StandardBorelSpace Action]
    [forall n, StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, Nonempty
      (HeterogeneousStochasticEpisodeBatchPrefix mdp episodes n)]
    [forall n, StandardBorelSpace
      (StochasticEpisodeBatch mdp (episodes n))]
    [forall n, Nonempty (StochasticEpisodeBatch mdp (episodes n))]
    [StandardBorelSpace
      (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)]
    (source : HeterogeneousAdaptiveStochasticEpisodeBatchSource
      mdp initialState episodes) [source.GlobalReturnMeasurability]
    (rounds : Nat) (hrounds : 0 < rounds)
    (hepisodes : forall t, 0 < episodes t)
    (rewardBound rewardVarianceProxy : NNReal)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= (rewardBound : Real))
    (law : source.rewardSource.UniformSubgaussianRewardLaw
      rewardVarianceProxy)
    (htotal : 0 <
      ((cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes rounds
        rewardBound rewardVarianceProxy : NNReal) : Real))
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1)
    (modelBadEvent :
      Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes))
    (modelFailureBudget : ENNReal) (expectedBound : Real)
    (Good : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes -> Prop)
    (hmodelMeasurable : MeasurableSet modelBadEvent)
    (hmodelTail : source.trajectoryMeasure modelBadEvent <= modelFailureBudget)
    (hmodelGood : forall trajectory, trajectory ∉ modelBadEvent ->
      Good trajectory /\
        source.successorWeightedExpectedAverageRegret trajectory rounds <=
          expectedBound) :
    let returnBadEvent := source.successorGlobalReturnDeviationBadEvent
      rounds rewardBound rewardVarianceProxy returnDelta
    let combinedBadEvent := modelBadEvent ∪ returnBadEvent
    MeasurableSet combinedBadEvent /\
      source.trajectoryMeasure combinedBadEvent <=
        modelFailureBudget + ENNReal.ofReal returnDelta /\
      forall trajectory, trajectory ∉ combinedBadEvent ->
        Good trajectory /\
          source.realizedSuccessorAverageRegret trajectory rounds <=
            expectedBound +
              Concentration.subGaussianSumConfidenceRadius
                  (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes
                    rounds rewardBound rewardVarianceProxy) returnDelta /
                successorEpisodeMass episodes rounds := by
  let returnBadEvent := source.successorGlobalReturnDeviationBadEvent
    rounds rewardBound rewardVarianceProxy returnDelta
  let combinedBadEvent := modelBadEvent ∪ returnBadEvent
  have hreturnMeasurable : MeasurableSet returnBadEvent := by
    simpa [returnBadEvent] using
      source.measurableSet_successorGlobalReturnDeviationBadEvent
        rounds rewardBound rewardVarianceProxy returnDelta
  have hreturnTail : source.trajectoryMeasure returnBadEvent <=
      ENNReal.ofReal returnDelta := by
    simpa [returnBadEvent] using
      source.trajectoryMeasure_successorGlobalReturnDeviationBadEvent_le
        rounds rewardBound rewardVarianceProxy hrewardBound law htotal
        returnDelta hreturnDelta hreturnDelta_le_one
  refine ⟨hmodelMeasurable.union hreturnMeasurable, ?_, ?_⟩
  · exact (measure_union_le modelBadEvent returnBadEvent).trans
      (add_le_add hmodelTail hreturnTail)
  · intro trajectory htrajectory
    have hnotModel : trajectory ∉ modelBadEvent := by
      exact fun hmem => htrajectory (Set.mem_union_left returnBadEvent hmem)
    have hnotReturn : trajectory ∉ returnBadEvent := by
      exact fun hmem => htrajectory (Set.mem_union_right modelBadEvent hmem)
    have hgood := hmodelGood trajectory hnotModel
    refine ⟨hgood.1, ?_⟩
    have hdeviation :
        |source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory| <
          Concentration.subGaussianSumConfidenceRadius
            (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes rounds
              rewardBound rewardVarianceProxy) returnDelta := by
      exact lt_of_not_ge (by simpa [returnBadEvent,
        successorGlobalReturnDeviationBadEvent] using hnotReturn)
    have hmass : 0 < successorEpisodeMass episodes rounds :=
      successorEpisodeMass_pos episodes rounds hrounds hepisodes
    rw [source.realizedSuccessorAverageRegret_eq_expected_sub_deviation
      trajectory rounds hmass]
    have hnoise :
        -source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory /
            successorEpisodeMass episodes rounds <=
          Concentration.subGaussianSumConfidenceRadius
              (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes
                rounds rewardBound rewardVarianceProxy) returnDelta /
            successorEpisodeMass episodes rounds := by
      apply div_le_div_of_nonneg_right _ hmass.le
      exact (neg_le_abs _).trans hdeviation.le
    calc
      source.successorWeightedExpectedAverageRegret trajectory rounds -
          source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory /
            successorEpisodeMass episodes rounds =
        source.successorWeightedExpectedAverageRegret trajectory rounds +
          (-source.cumulativeSuccessorGlobalReturnDeviation rounds trajectory /
            successorEpisodeMass episodes rounds) := by ring
      _ <= source.successorWeightedExpectedAverageRegret trajectory rounds +
          Concentration.subGaussianSumConfidenceRadius
              (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes
                rounds rewardBound rewardVarianceProxy) returnDelta /
            successorEpisodeMass episodes rounds :=
        add_le_add (le_refl _) hnoise
      _ <= expectedBound +
          Concentration.subGaussianSumConfidenceRadius
              (cumulativeSuccessorGlobalReturnVarianceProxy mdp episodes
                rounds rewardBound rewardVarianceProxy) returnDelta /
            successorEpisodeMass episodes rounds :=
        add_le_add hgood.2 (le_refl _)

end HeterogeneousAdaptiveStochasticEpisodeBatchSource

omit [Nonempty State] in
/-- A sampled stochastic empirical model has the two supplied fixed radii. -/
theorem MDP.stochasticAllCoordinateEmpiricalFiniteBatchModel_occupancySelectedRadiusRemaining_eq
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat}
    (batch : EpisodeBatch mdp episodes) (defaultState : State)
    (rewardBudget transitionBudget : Real) :
    let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel episodes
      batch defaultState rewardBudget transitionBudget
    model.plan.optimisticPolicy.occupancySumRemaining
        (fun remaining hremaining state =>
          2 * model.plan.selectedRadiusRemaining remaining hremaining state)
        mdp.horizon le_rfl initialState =
      (mdp.horizon : Real) * (2 * (rewardBudget + transitionBudget)) := by
  dsimp only
  rw [show
    (fun remaining hremaining state =>
      2 * (mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel episodes batch
        defaultState rewardBudget transitionBudget).plan.selectedRadiusRemaining
          remaining hremaining state) =
      (fun _remaining _hremaining _state =>
        2 * (rewardBudget + transitionBudget)) by
      funext remaining hremaining state
      simp [MDP.EstimatedModelPlan.selectedRadiusRemaining,
        MDP.stochasticAllCoordinateEmpiricalFiniteBatchModel,
        MDP.FiniteBatchModel.plan]]
  exact MarkovPolicy.occupancySumRemaining_const
    (policy :=
      (mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel episodes batch
        defaultState rewardBudget transitionBudget).plan.optimisticPolicy)
    (2 * (rewardBudget + transitionBudget)) mdp.horizon le_rfl initialState

namespace AdaptiveStochasticSampledEmpiricalOptimisticSource

/-- The sampled table at coordinate `n` is exactly the next source policy. -/
theorem heterogeneousExploratorySource_successorPolicyAt_eq_sampledPlanExploratoryPolicy
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (rewardBudget transitionBudget : Nat -> Real)
    (explorationRate : Nat -> NNReal)
    (hexplorationRate : forall t, explorationRate t <= 1)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (n : Nat) :
    let source := heterogeneousExploratorySource mdp initialState episodes
      rewardSource initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    source.successorPolicyAt trajectory n =
      ((trajectory n).sampledEmpiricalOptimisticPolicyTable defaultState
        (rewardBudget n) (transitionBudget n)).exploratoryPolicy
          (explorationRate (n + 1)) (hexplorationRate (n + 1)) := by
  rfl

/-- One selected causal exploratory policy pays only its local charge. -/
theorem heterogeneousExploratorySource_successorPolicyAt_expectedRegret_le
    {mdp : MDP State Action} {initialState : Measure State}
    [IsProbabilityMeasure initialState] {episodes : Nat -> Nat}
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (rewardBudget transitionBudget : Nat -> Real)
    (explorationRate : Nat -> NNReal)
    (hexplorationRate : forall t, explorationRate t <= 1)
    (trajectory : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes)
    (n : Nat) (rewardBound : Real)
    (hrewardBound : forall state action,
      |mdp.reward state action| <= rewardBound) :
    let source := heterogeneousExploratorySource mdp initialState episodes
      rewardSource initialTable defaultState rewardBudget transitionBudget
        explorationRate hexplorationRate
    let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
      (episodes n)
      (mdp.sampledEpisodeBatchOfStochasticTrajectories
        (episodes n) (trajectory n))
      defaultState (rewardBudget n) (transitionBudget n)
    (source.successorPolicyAt trajectory n).expectedRegret initialState <=
      model.plan.optimisticPolicy.expectedRegret initialState +
        exploratoryBehaviorRegretCharge mdp (explorationRate (n + 1))
          rewardBound := by
  dsimp only
  let table := (trajectory n).sampledEmpiricalOptimisticPolicyTable
    defaultState (rewardBudget n) (transitionBudget n)
  have htransport :=
    table.exploratoryPolicy_expectedRegret_le_toMarkovPolicy_expectedRegret_add_charge
      initialState (explorationRate (n + 1))
      (hexplorationRate (n + 1)) rewardBound hrewardBound
  simpa [table, HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorPolicyAt,
    heterogeneousExploratorySource, heterogeneousSuccessorTable,
    heterogeneousLatestBatch, Preorder.frestrictLe_apply,
    exploratoryBehaviorRegretCharge,
    StochasticEpisodeBatch.sampledEmpiricalOptimisticPolicyTable_toMarkovPolicy]
    using htransport

/-- Weighted planning envelope for all causal successor batches. -/
noncomputable def selfConsistentScheduledCausalSuccessorPlanningCumulativeBound
    (mdp : MDP State Action) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) : Real :=
  ∑ round : Fin rounds,
    let t := (round : Nat)
    let episodes :=
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
        mdp varianceProxy baseVisitFloor
    let rewardBudget :=
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
        mdp varianceProxy baseVisitFloor
    let transitionBudget :=
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
        mdp varianceProxy baseVisitFloor
    (episodes (t + 1) : Real) *
      ((mdp.horizon : Real) *
          (2 * (rewardBudget t + transitionBudget t)) +
        exploratoryBehaviorRegretCharge mdp
          (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1)

/-- The same planning envelope per actual sampled successor episode. -/
noncomputable def selfConsistentScheduledCausalSuccessorPlanningAverageBound
    (mdp : MDP State Action) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) : Real :=
  selfConsistentScheduledCausalSuccessorPlanningCumulativeBound mdp
      varianceProxy baseVisitFloor rounds /
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorEpisodeMass
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)
      rounds

/-
The sampled-model event controls the actual exploratory successor policies.
Every coordinate keeps its own model budgets, next-coordinate exploration
rate, and successor batch-size weight.
-/
theorem selfConsistentScheduledCausalSource_trajectoryMeasure_optimism_and_weightedExpectedSuccessorAverageRegret
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds) :
    let episodes := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
        mdp varianceProxy baseVisitFloor t
    let rewardBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
        mdp varianceProxy baseVisitFloor t
    let transitionBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
        mdp varianceProxy baseVisitFloor t
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    let event := selfConsistentScheduledCausalModelBadEvent mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
    MeasurableSet event /\
      source.trajectoryMeasure event <=
        selfConsistentScheduledCausalModelFailureBudget mdp rounds /\
      forall trajectory, trajectory ∉ event ->
        (forall round : Fin rounds,
          let t := (round : Nat)
          let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
            (episodes t)
            (mdp.sampledEpisodeBatchOfStochasticTrajectories
              (episodes t) (trajectory t))
            defaultState (rewardBudget t) (transitionBudget t)
          forall state,
            mdp.optimalValueRemaining mdp.horizon le_rfl state <=
              model.plan.upperValueRemaining mdp.horizon le_rfl state) /\
        source.successorWeightedExpectedAverageRegret trajectory rounds <=
          selfConsistentScheduledCausalSuccessorPlanningAverageBound mdp
            varianceProxy baseVisitFloor rounds := by
  dsimp only
  let episodes := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
      mdp varianceProxy baseVisitFloor t
  let rewardBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
      mdp varianceProxy baseVisitFloor t
  let transitionBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
      mdp varianceProxy baseVisitFloor t
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  let event := selfConsistentScheduledCausalModelBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
  have hparent :
      MeasurableSet event /\
        source.trajectoryMeasure event <=
          selfConsistentScheduledCausalModelFailureBudget mdp rounds /\
        forall trajectory, trajectory ∉ event -> forall round : Fin rounds,
          let t := (round : Nat)
          let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
            (episodes t)
            (mdp.sampledEpisodeBatchOfStochasticTrajectories
              (episodes t) (trajectory t))
            defaultState (rewardBudget t) (transitionBudget t)
          (forall state,
              mdp.optimalValueRemaining mdp.horizon le_rfl state <=
                model.plan.upperValueRemaining mdp.horizon le_rfl state) /\
            model.plan.optimisticPolicy.expectedRegret initialState <=
              model.plan.optimisticPolicy.occupancySumRemaining
                (fun remaining hremaining state =>
                  2 * model.plan.selectedRadiusRemaining
                    remaining hremaining state)
                mdp.horizon le_rfl initialState := by
    simpa [episodes, rewardBudget, transitionBudget, source, event] using
      selfConsistentScheduledCausalSource_trajectoryMeasure_allCoordinateConfidence_optimism_and_recommendedExpectedRegret
        mdp initialState rewardSource varianceProxy hvarianceProxy law
          initialTable defaultState support baseVisitFloor hbaseFloor
          hrewardBound hhorizon hbaseVisitFloor rounds
  refine ⟨hparent.1, hparent.2.1, ?_⟩
  intro trajectory htrajectory
  have hcert := hparent.2.2 trajectory htrajectory
  refine ⟨fun round => (hcert round).1, ?_⟩
  have hcum :
      source.successorWeightedExpectedCumulativeRegret trajectory rounds <=
        selfConsistentScheduledCausalSuccessorPlanningCumulativeBound mdp
          varianceProxy baseVisitFloor rounds := by
    unfold
      HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorWeightedExpectedCumulativeRegret
      selfConsistentScheduledCausalSuccessorPlanningCumulativeBound
    apply Finset.sum_le_sum
    intro round _hround
    let t := (round : Nat)
    let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
      (episodes t)
      (mdp.sampledEpisodeBatchOfStochasticTrajectories
        (episodes t) (trajectory t))
      defaultState (rewardBudget t) (transitionBudget t)
    have hbehavior :
        (source.successorPolicyAt trajectory t).expectedRegret initialState <=
          model.plan.optimisticPolicy.expectedRegret initialState +
            exploratoryBehaviorRegretCharge mdp
              (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1 := by
      simpa [source, episodes, rewardBudget, transitionBudget, model,
        selfConsistentScheduledCausalSource] using
        (heterogeneousExploratorySource_successorPolicyAt_expectedRegret_le
          (episodes := episodes) rewardSource initialTable defaultState
          rewardBudget transitionBudget
          AdaptiveEpisodeBatchSource.decayingExplorationRate
          AdaptiveEpisodeBatchSource.decayingExplorationRate_le_one
          trajectory t 1 hrewardBound)
    have hmodel := (hcert round).2
    have hoccupancy :=
      mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel_occupancySelectedRadiusRemaining_eq
        (initialState := initialState)
        (mdp.sampledEpisodeBatchOfStochasticTrajectories
          (episodes t) (trajectory t))
        defaultState (rewardBudget t) (transitionBudget t)
    have hlocal :
        (source.successorPolicyAt trajectory t).expectedRegret initialState <=
          (mdp.horizon : Real) *
              (2 * (rewardBudget t + transitionBudget t)) +
            exploratoryBehaviorRegretCharge mdp
              (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1 := by
      calc
        (source.successorPolicyAt trajectory t).expectedRegret initialState <=
            model.plan.optimisticPolicy.expectedRegret initialState +
              exploratoryBehaviorRegretCharge mdp
                (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1 :=
          hbehavior
        _ <= model.plan.optimisticPolicy.occupancySumRemaining
                (fun remaining hremaining state =>
                  2 * model.plan.selectedRadiusRemaining
                    remaining hremaining state)
                mdp.horizon le_rfl initialState +
              exploratoryBehaviorRegretCharge mdp
                (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1 :=
          add_le_add hmodel (le_refl _)
        _ = (mdp.horizon : Real) *
                (2 * (rewardBudget t + transitionBudget t)) +
              exploratoryBehaviorRegretCharge mdp
                (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1 := by
          simpa [model] using congrArg
            (fun value => value +
              exploratoryBehaviorRegretCharge mdp
                (AdaptiveEpisodeBatchSource.decayingExplorationRate (t + 1)) 1)
            hoccupancy
    have hweight : 0 <= (episodes (t + 1) : Real) := by positivity
    exact mul_le_mul_of_nonneg_left hlocal hweight
  have hmass : 0 <
      HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorEpisodeMass
        episodes rounds :=
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorEpisodeMass_pos
      episodes rounds hrounds (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes_pos
          mdp varianceProxy baseVisitFloor t)
  unfold
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorWeightedExpectedAverageRegret
    selfConsistentScheduledCausalSuccessorPlanningAverageBound
  exact div_le_div_of_nonneg_right hcum hmass.le

/-- Named successor-only return event for the self-consistent causal source. -/
noncomputable def selfConsistentScheduledCausalSuccessorReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  source.successorGlobalReturnDeviationBadEvent rounds 1 varianceProxy
    returnDelta

/-- Union of the causal sampled-model and globally centered return events. -/
noncomputable def selfConsistentScheduledCausalModelReturnBadEvent
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State) (varianceProxy : NNReal)
    (baseVisitFloor : Real) (rounds : Nat) (returnDelta : Real) :
    Set (HeterogeneousStochasticEpisodeBatchTrajectory mdp
      (fun t =>
        AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
          mdp varianceProxy baseVisitFloor t)) :=
  selfConsistentScheduledCausalModelBadEvent mdp initialState rewardSource
      initialTable defaultState varianceProxy baseVisitFloor rounds ∪
    selfConsistentScheduledCausalSuccessorReturnBadEvent mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
        rounds returnDelta

/-- Exact finite-prefix model-plus-return failure budget. -/
noncomputable def selfConsistentScheduledCausalModelReturnFailureBudget
    (mdp : MDP State Action) (rounds : Nat) (returnDelta : Real) : ENNReal :=
  selfConsistentScheduledCausalModelFailureBudget mdp rounds +
    ENNReal.ofReal returnDelta

/-
End-to-end causal finite-prefix theorem.  Off one named event, every actual
sampled model is optimistic and the weighted realized successor-average
behavior regret is controlled by the coordinatewise schedule plus the
heterogeneous globally centered return radius.
-/
theorem selfConsistentScheduledCausalSource_trajectoryMeasure_optimism_and_realizedSuccessorAverageRegret
    (mdp : MDP State Action) (initialState : Measure State)
    [IsProbabilityMeasure initialState]
    [StandardBorelSpace State] [StandardBorelSpace Action]
    (rewardSource : mdp.MeanCompatibleRewardKernel)
    (varianceProxy : NNReal) (hvarianceProxy : 0 < varianceProxy)
    (law : rewardSource.UniformSubgaussianRewardLaw varianceProxy)
    (initialTable : DeterministicMarkovPolicyTable mdp)
    (defaultState : State)
    (support : ExploratoryPathSupport mdp initialState)
    (baseVisitFloor : Real)
    (hbaseFloor : ExploratoryPathUniformVisitFloor support 1 baseVisitFloor)
    (hrewardBound : forall state action, |mdp.reward state action| <= 1)
    (hhorizon : 0 < mdp.horizon) (hbaseVisitFloor : 0 < baseVisitFloor)
    (rounds : Nat) (hrounds : 0 < rounds)
    (returnDelta : Real) (hreturnDelta : 0 < returnDelta)
    (hreturnDelta_le_one : returnDelta <= 1) :
    let episodes := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
        mdp varianceProxy baseVisitFloor t
    let rewardBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
        mdp varianceProxy baseVisitFloor t
    let transitionBudget := fun t =>
      AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
        mdp varianceProxy baseVisitFloor t
    let source := selfConsistentScheduledCausalSource mdp initialState
      rewardSource initialTable defaultState varianceProxy baseVisitFloor
    let event := selfConsistentScheduledCausalModelReturnBadEvent mdp
      initialState rewardSource initialTable defaultState varianceProxy
        baseVisitFloor rounds returnDelta
    MeasurableSet event /\
      source.trajectoryMeasure event <=
        selfConsistentScheduledCausalModelReturnFailureBudget mdp rounds
          returnDelta /\
      forall trajectory, trajectory ∉ event ->
        (forall round : Fin rounds,
          let t := (round : Nat)
          let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
            (episodes t)
            (mdp.sampledEpisodeBatchOfStochasticTrajectories
              (episodes t) (trajectory t))
            defaultState (rewardBudget t) (transitionBudget t)
          forall state,
            mdp.optimalValueRemaining mdp.horizon le_rfl state <=
              model.plan.upperValueRemaining mdp.horizon le_rfl state) /\
        source.realizedSuccessorAverageRegret trajectory rounds <=
          selfConsistentScheduledCausalSuccessorPlanningAverageBound mdp
              varianceProxy baseVisitFloor rounds +
            Concentration.subGaussianSumConfidenceRadius
                (HeterogeneousAdaptiveStochasticEpisodeBatchSource.cumulativeSuccessorGlobalReturnVarianceProxy
                  mdp episodes rounds 1 varianceProxy) returnDelta /
              HeterogeneousAdaptiveStochasticEpisodeBatchSource.successorEpisodeMass
                episodes rounds := by
  dsimp only
  let episodes := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes
      mdp varianceProxy baseVisitFloor t
  let rewardBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledRewardBudget
      mdp varianceProxy baseVisitFloor t
  let transitionBudget := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledTransitionBudget
      mdp varianceProxy baseVisitFloor t
  let source := selfConsistentScheduledCausalSource mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor
  let modelEvent := selfConsistentScheduledCausalModelBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
  let returnEvent := selfConsistentScheduledCausalSuccessorReturnBadEvent mdp
    initialState rewardSource initialTable defaultState varianceProxy
      baseVisitFloor rounds returnDelta
  let event := selfConsistentScheduledCausalModelReturnBadEvent mdp initialState
    rewardSource initialTable defaultState varianceProxy baseVisitFloor rounds
      returnDelta
  let Good : HeterogeneousStochasticEpisodeBatchTrajectory mdp episodes ->
      Prop := fun trajectory =>
    forall round : Fin rounds,
      let t := (round : Nat)
      let model := mdp.stochasticAllCoordinateEmpiricalFiniteBatchModel
        (episodes t)
        (mdp.sampledEpisodeBatchOfStochasticTrajectories
          (episodes t) (trajectory t))
        defaultState (rewardBudget t) (transitionBudget t)
      forall state,
        mdp.optimalValueRemaining mdp.horizon le_rfl state <=
          model.plan.upperValueRemaining mdp.horizon le_rfl state
  letI : source.GlobalReturnMeasurability := by
    dsimp [source, selfConsistentScheduledCausalSource]
    infer_instance
  have hepisodes : forall t, 0 < episodes t := fun t =>
    AdaptiveStochasticEpisodeBatchSource.selfConsistentScheduledEpisodes_pos
      mdp varianceProxy baseVisitFloor t
  have hmodel :
      MeasurableSet modelEvent /\
        source.trajectoryMeasure modelEvent <=
          selfConsistentScheduledCausalModelFailureBudget mdp rounds /\
        forall trajectory, trajectory ∉ modelEvent ->
          Good trajectory /\
            source.successorWeightedExpectedAverageRegret trajectory rounds <=
              selfConsistentScheduledCausalSuccessorPlanningAverageBound mdp
                varianceProxy baseVisitFloor rounds := by
    simpa [episodes, rewardBudget, transitionBudget, source, modelEvent, Good]
      using
        selfConsistentScheduledCausalSource_trajectoryMeasure_optimism_and_weightedExpectedSuccessorAverageRegret
          mdp initialState rewardSource varianceProxy hvarianceProxy law
            initialTable defaultState support baseVisitFloor hbaseFloor
            hrewardBound hhorizon hbaseVisitFloor rounds hrounds
  have htotal : 0 <
      ((HeterogeneousAdaptiveStochasticEpisodeBatchSource.cumulativeSuccessorGlobalReturnVarianceProxy
        mdp episodes rounds 1 varianceProxy : NNReal) : Real) :=
    HeterogeneousAdaptiveStochasticEpisodeBatchSource.cumulativeSuccessorGlobalReturnVarianceProxy_pos
      mdp episodes rounds 1 varianceProxy hrounds hepisodes hhorizon
        hvarianceProxy
  have hrewardBoundNN : forall state action,
      |mdp.reward state action| <= ((1 : NNReal) : Real) := by
    simpa using hrewardBound
  have htransport :=
    source.trajectoryMeasure_weightedExpected_to_realized_successor_average_regret_transport
      rounds hrounds hepisodes 1 varianceProxy hrewardBoundNN law htotal
        returnDelta hreturnDelta hreturnDelta_le_one modelEvent
        (selfConsistentScheduledCausalModelFailureBudget mdp rounds)
        (selfConsistentScheduledCausalSuccessorPlanningAverageBound mdp
          varianceProxy baseVisitFloor rounds)
        Good hmodel.1 hmodel.2.1 hmodel.2.2
  simpa [episodes, source, modelEvent, returnEvent, event, Good,
    selfConsistentScheduledCausalSuccessorReturnBadEvent,
    selfConsistentScheduledCausalModelReturnBadEvent,
    selfConsistentScheduledCausalModelReturnFailureBudget] using htransport

end AdaptiveStochasticSampledEmpiricalOptimisticSource

end BanditRLProof.FiniteHorizonRL
