import BanditRLProof.Algorithms.CUCBImpossibleCase
import BanditRLProof.Algorithms.CUCBGapInverse
import BanditRLProof.Algorithms.CUCBOracleSuccess
import BanditRLProof.Algorithms.CUCBActualReward
import BanditRLProof.Algorithms.CUCBSufficientSampling

/-! Source model and deterministic-trigger dependency checks.
The required concrete noisy final-performance witness is still pending. -/
namespace Tests.CUCBSourceModelCanary
open BanditRLProof.CUCB

#print axioms cucbTrajectory_ae_round_property
#print axioms ChargeData.counters_le_observations_ae_of_one
#print axioms FeedbackModel.minTrigger_pos
#print axioms FeedbackModel.minTrigger_le_one
#print axioms FeedbackModel.deterministic_counter_bound
#print axioms FeedbackModel.charged_observation_tail
#print axioms FeedbackModel.nice_event_probability
#print axioms SourceModel.inverseGap_spec
#print axioms SourceModel.chargeData_sufficient
#print axioms SourceModel.not_bad_of_nice_and_sufficient_observations
#print axioms SourceModel.maxPositiveGap_eq_zero_of_no_bad
#print axioms SourceModel.counters_zero_of_no_bad

#print axioms SourceModel.inverseAt_unique
#print axioms SourceModel.inverseAt_gap
#print axioms SourceModel.inverseAt_strictMono
#print axioms SourceModel.gapThreshold_antitone
#print axioms SourceModel.gapThreshold_intervalIntegrable
#print axioms SourceModel.continuous_score
#print axioms SourceModel.continuous_optimum
#print axioms SourceModel.measurableSet_path_oracleSuccess
#print axioms SourceModel.condExp_oracle_success
#print axioms SourceModel.initial_oracle_success
#print axioms SourceModel.oracle_failure_probability
#print axioms SourceModel.integrable_round_reward
#print axioms SourceModel.integral_joint_reward_eq_score
#print axioms SourceModel.integrable_actual_reward
#print axioms SourceModel.cumulative_actual_reward_expectation
#print axioms SourceModel.approximationRegret_zero
#print axioms SourceModel.approximationRegret_eq_mean
#print axioms SourceModel.approximationRegret_eq_gap_sum
#print axioms probabilistic_threshold_crossing
#print axioms FeedbackModel.globalMinTrigger_pos
#print axioms FeedbackModel.globalMinTrigger_eq_one_iff
#print axioms SourceModel.trigger_shortfall_slice
#print axioms SourceModel.trigger_shortfall_probability
#print axioms SourceModel.trigger_shortfall_probability_of_one
#print axioms SourceModel.trigger_shortfall_union_probability
#print axioms SourceModel.sufficient_successful_charge_subset
#print axioms SourceModel.sufficient_successful_charge_probability_of_all_one
#print axioms SourceModel.sufficient_successful_charge_probability_source
end Tests.CUCBSourceModelCanary
