import BanditRLProof.DelayedFeedback.EliminatedArmInitialization

open BanditRLProof

namespace BanditRLProof.DelayedFeedback

/-- A concrete two-arm arrival batch.  Both processed sources selected arm one,
so Algorithm 5 line 10 reads `n_1(S) = 2` at horizon four. -/
def eliminatedInitializationTwoArmState : DelayedSAPOStructuralRoundState 2 where
  currentActionRound := 4
  currentActionRound_pos := by norm_num
  delayAt := fun s => if s = 1 then 2 else 0
  processedOrder := [3]
  processedOrder_nodup := by simp
  processedOrder_available := by
    intro s hs
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hs
    subst s
    norm_num
  activeAtSourceRound := fun _ => Finset.univ
  sourceActive_antitone := by
    intro _s _t _hst
    exact Finset.Subset.rfl
  currentActive := Finset.univ
  currentActive_subset_roundStart := Finset.Subset.rfl
  chosenArmAt := fun _ => (1 : Fin 2)
  inactiveProbabilityAt := fun _ _ => 0

/-- Arm one has a deliberately separated empirical surface, while arm zero
remains below the strict line-7 elimination threshold.  This canary isolates
the deterministic line-7/line-10 data flow; the value `20` is deliberately a
structural test fixture, not a claim that this state was generated by a
`[0, 1]` loss trajectory. -/
noncomputable def eliminatedInitializationStep :
    DelayedSAPONoSwitchProcessOne eliminatedInitializationTwoArmState where
  sourceRound := 1
  source_new := by native_decide
  empiricalMean := fun i => if i = 0 then 0 else 20
  importanceUpper := fun _ => 20
  previousEmpiricalUpper := fun _ => 20
  ucbStar := 0

def eliminatedInitializationPrior : DelayedSAPOEliminatedArmBank 2 :=
  fun _ => none

example : ActiveArmsUninitialized eliminatedInitializationTwoArmState
    eliminatedInitializationPrior := by
  intro i _hi
  rfl

theorem eliminatedInitialization_armOne_processedPullCount :
    eliminatedInitializationStep.toPreEliminationSummary.toProcessedPrefix.processedPullCount
      (1 : Fin 2) = 2 := by
  simp [DelayedSAPOProcessedPrefix.processedPullCount,
    DelayedSAPOProcessedTraceSummary.toProcessedPrefix,
    DelayedSAPONoSwitchProcessOne.toPreEliminationSummary,
    DelayedSAPONoSwitchProcessOne.extendedOrder,
    eliminatedInitializationStep, eliminatedInitializationTwoArmState]

/-- In the concrete `K = 2`, `T = 4`, `n_1(S) = 2` fixture, the exact printed
line-10 formula gives `p_1^1 = 1/2`. -/
example :
    (DelayedSAPOEliminatedArmInitialization.ofProcessOne
      eliminatedInitializationStep 4 (1 : Fin 2)).initialProbability =
        (1 : Real) / 2 := by
  norm_num [DelayedSAPOEliminatedArmInitialization.ofProcessOne,
    delayedSAPOInitialEliminatedProbability,
    eliminatedInitialization_armOne_processedPullCount]

/-- The high empirical-mean arm is selected by the literal strict test. -/
theorem eliminatedInitialization_armOne_mem_eliminated :
    (1 : Fin 2) ∈
      (eliminatedInitializationStep.toPreEliminationSummary.toConfidenceSnapshot 4).eliminated := by
  rw [DelayedSAPOEliminationSnapshot.mem_eliminated_iff]
  constructor
  · simp [eliminatedInitializationStep, eliminatedInitializationTwoArmState,
      DelayedSAPONoSwitchProcessOne.toPreEliminationSummary,
      DelayedSAPOProcessedTraceSummary.toConfidenceSnapshot]
  · have hwidth :
        eliminatedInitializationStep.toPreEliminationSummary.empiricalWidthAt
            4 (1 : Fin 2) <= 1 :=
      DelayedSAPOProcessedPrefixCountCertificate.sourceEmpiricalWidthScale_le_one _ _
    change 0 < 20 - 9 *
      eliminatedInitializationStep.toPreEliminationSummary.empiricalWidthAt
        4 (1 : Fin 2)
    linarith

/-- Arm zero survives because every generated source width is nonnegative. -/
theorem eliminatedInitialization_armZero_mem_remainingActive :
    (0 : Fin 2) ∈
      (eliminatedInitializationStep.toPreEliminationSummary.toConfidenceSnapshot 4).remainingActive := by
  rw [DelayedSAPOEliminationSnapshot.mem_remainingActive_iff]
  constructor
  · simp [eliminatedInitializationStep, eliminatedInitializationTwoArmState,
      DelayedSAPONoSwitchProcessOne.toPreEliminationSummary,
      DelayedSAPOProcessedTraceSummary.toConfidenceSnapshot]
  · have hwidth :
        0 <= eliminatedInitializationStep.toPreEliminationSummary.empiricalWidthAt
            4 (0 : Fin 2) :=
      DelayedSAPOProcessedPrefixCountCertificate.sourceEmpiricalWidthScale_nonneg _ _
    change 0 - 9 *
      eliminatedInitializationStep.toPreEliminationSummary.empiricalWidthAt
        4 (0 : Fin 2) <= 0
    linarith

example :
    DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated
        eliminatedInitializationStep 4 eliminatedInitializationPrior (1 : Fin 2) =
      some (DelayedSAPOEliminatedArmInitialization.ofProcessOne
        eliminatedInitializationStep 4 (1 : Fin 2)) := by
  apply DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated_of_mem
  exact eliminatedInitialization_armOne_mem_eliminated

example :
    DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated
        eliminatedInitializationStep 4 eliminatedInitializationPrior (0 : Fin 2) =
      none := by
  apply DelayedSAPOEliminatedArmInitialization.remainingActive_uninitialized_after_initialize
    (horizon := 4)
  · intro i _hi
    rfl
  · exact eliminatedInitialization_armZero_mem_remainingActive

example :
    0 < (DelayedSAPOEliminatedArmInitialization.ofProcessOne
      eliminatedInitializationStep 4 (1 : Fin 2)).initialProbability :=
  DelayedSAPOEliminatedArmInitialization.initialProbability_pos
    eliminatedInitializationStep 4 (1 : Fin 2)

example :
    0 < (DelayedSAPOEliminatedArmInitialization.ofProcessOne
      eliminatedInitializationStep 4 (1 : Fin 2)).surrogateGap :=
  DelayedSAPOEliminatedArmInitialization.surrogateGap_pos
    eliminatedInitializationStep 4 (1 : Fin 2) (by norm_num)

example :
    0 < (DelayedSAPOEliminatedArmInitialization.ofProcessOne
      eliminatedInitializationStep 4 (1 : Fin 2)).initialPhaseTarget :=
  DelayedSAPOEliminatedArmInitialization.initialPhaseTarget_pos
    eliminatedInitializationStep 4 (1 : Fin 2) (by norm_num)

#check delayedSAPOInitialEliminatedProbability
#check delayedSAPOInitialPhaseTarget
#check DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated
#check DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated_spec_of_mem
#check DelayedSAPOEliminatedArmInitialization.mem_eliminated_of_initializeNewlyEliminated_ne_prior

#print axioms DelayedSAPOEliminatedArmInitialization.initialProbability_pos
#print axioms DelayedSAPOEliminatedArmInitialization.surrogateGap_pos
#print axioms DelayedSAPOEliminatedArmInitialization.initialPhaseTarget_pos
#print axioms DelayedSAPOEliminatedArmInitialization.initializeNewlyEliminated_spec_of_mem
#print axioms DelayedSAPOEliminatedArmInitialization.mem_eliminated_of_initializeNewlyEliminated_ne_prior

end BanditRLProof.DelayedFeedback
