import BanditRLProof.DelayedFeedback.ProcessedPrefixCounts

open BanditRLProof

#check DelayedFeedback.DelayedSAPOProcessedPrefix
#check DelayedFeedback.DelayedSAPOProcessedPrefix.processedPullCount
#check DelayedFeedback.DelayedSAPOProcessedPrefix.expectedPullMass
#check DelayedFeedback.DelayedSAPOProcessedPrefix.expectedPullMass_eq_of_active_throughout
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.expectedPullMass_eq_of_mem_active
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.quarter_count_sub_six_log_le_count_of_mem_active
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.eighth_count_le_count_of_large_count
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.empiricalWidth_le_three_of_large_count
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.empiricalWidth_le_ten_of_mem_active
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.ucbStar_le_empiricalMean_add_width
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.activeArmGapBranch
#check DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.gap_le_twenty_mul_gap_at_earlier_elimination_snapshot_of_countCertificate

#print axioms DelayedFeedback.DelayedSAPOProcessedPrefix.expectedPullMass_eq_of_active_throughout
#print axioms DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.empiricalWidth_le_ten_of_mem_active
#print axioms DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.ucbStar_le_empiricalMean_add_width
#print axioms DelayedFeedback.DelayedSAPOProcessedPrefixCountCertificate.gap_le_twenty_mul_gap_at_earlier_elimination_snapshot_of_countCertificate
