import BanditRLProof.Algorithms.StochasticGradientBanditTwoArmInitialRecurrence

#check BanditRLProof.StochasticGradientBandit.softmaxProbability_zeroInitialization_finTwo
#check BanditRLProof.StochasticGradientBandit.integral_twoArmInitialPairKernel_exp_forwardIncrement_le
#check BanditRLProof.StochasticGradientBandit.integral_twoArmInitialPairKernel_exp_inverseIncrement_le

#print axioms BanditRLProof.StochasticGradientBandit.softmaxProbability_zeroInitialization_finTwo
#print axioms BanditRLProof.StochasticGradientBandit.integral_twoArmInitialPairKernel_exp_forwardIncrement_le
#print axioms BanditRLProof.StochasticGradientBandit.integral_twoArmInitialPairKernel_exp_inverseIncrement_le
