import BanditRLProof.Algorithms.StochasticGradientBanditTwoArmRecurrence

#check BanditRLProof.StochasticGradientBandit.twoArmForwardQ
#check BanditRLProof.StochasticGradientBandit.twoArmInverseQ
#check BanditRLProof.StochasticGradientBandit.twoArmForwardEqEightRemainder_le
#check BanditRLProof.StochasticGradientBandit.twoArmInverseEqEightRemainder_le
#check BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le
#check BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le_add_success_sq
#check BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le
#check BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le_sub_failure_sq

#print axioms BanditRLProof.StochasticGradientBandit.twoArmForwardEqEightRemainder_le
#print axioms BanditRLProof.StochasticGradientBandit.twoArmInverseEqEightRemainder_le
#print axioms BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le_add_success_sq
#print axioms BanditRLProof.StochasticGradientBandit.integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le_sub_failure_sq
