import BanditRLProof.Algorithms.StochasticGradientBanditAudit

open scoped BigOperators

#check BanditRLProof.StochasticGradientBandit.softmaxDenominator
#check BanditRLProof.StochasticGradientBandit.softmaxProbability
#check BanditRLProof.StochasticGradientBandit.softmaxProbability_sum
#check BanditRLProof.StochasticGradientBandit.softmaxProbability_le_one
#check BanditRLProof.StochasticGradientBandit.sourceIncrement
#check BanditRLProof.StochasticGradientBandit.sum_sourceIncrement
#check BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gradientCoordinate
#check BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gapCoordinate
#check BanditRLProof.StochasticGradientBandit.instantaneousGap_ge_minGap_mul_failureMass
#check BanditRLProof.StochasticGradientBandit.bestParameterIncrementSum_ge
#check BanditRLProof.StochasticGradientBandit.sourceRegretDecomposition_le

#print axioms BanditRLProof.StochasticGradientBandit.softmaxProbability_sum
#print axioms BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gapCoordinate
#print axioms BanditRLProof.StochasticGradientBandit.bestParameterIncrementSum_ge
#print axioms BanditRLProof.StochasticGradientBandit.sourceRegretDecomposition_le
