import BanditRLProof.Algorithms.StochasticGradientBanditTrajectoryAudit

open scoped BigOperators

#check BanditRLProof.StochasticGradientBandit.softmaxDenominator
#check BanditRLProof.StochasticGradientBandit.softmaxProbability
#check BanditRLProof.StochasticGradientBandit.softmaxProbability_sum
#check BanditRLProof.StochasticGradientBandit.softmaxProbability_le_one
#check BanditRLProof.StochasticGradientBandit.sourceIncrement
#check BanditRLProof.StochasticGradientBandit.sum_sourceIncrement
#check BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gradientCoordinate
#check BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gapCoordinate
#check BanditRLProof.StochasticGradientBandit.instantaneousGap_ge_minGap_mul_failureMass
#check BanditRLProof.StochasticGradientBandit.bestParameterIncrementSum_ge
#check BanditRLProof.StochasticGradientBandit.sourceRegretDecomposition_le
#check BanditRLProof.StochasticGradientBandit.historyParameter
#check BanditRLProof.StochasticGradientBandit.historyParameter_succ
#check BanditRLProof.StochasticGradientBandit.measurable_historyParameter
#check BanditRLProof.StochasticGradientBandit.historySoftmaxDistributionSource
#check BanditRLProof.StochasticGradientBandit.historyAlgorithm
#check BanditRLProof.StochasticGradientBandit.trajectoryKernel
#check BanditRLProof.StochasticGradientBandit.trajectoryMeasure_condDistrib_action_zero_given_environment
#check BanditRLProof.StochasticGradientBandit.trajectoryMeasure_condDistrib_action
#check BanditRLProof.StochasticGradientBandit.trajectoryMeasure_condDistrib_nextPair_given_environment_prefix
#check BanditRLProof.StochasticGradientBandit.integral_measurableEnvironmentInitialPairKernel_sourceIncrement_eq_expectedSourceIncrement
#check BanditRLProof.StochasticGradientBandit.integral_historyStepKernel_sourceIncrement_eq_expectedSourceIncrement
#check BanditRLProof.StochasticGradientBandit.integral_measurableEnvironmentHistoryStepKernel_sourceIncrement_eq_gapCoordinate

#print axioms BanditRLProof.StochasticGradientBandit.softmaxProbability_sum
#print axioms BanditRLProof.StochasticGradientBandit.expectedSourceIncrement_eq_gapCoordinate
#print axioms BanditRLProof.StochasticGradientBandit.bestParameterIncrementSum_ge
#print axioms BanditRLProof.StochasticGradientBandit.sourceRegretDecomposition_le
#print axioms BanditRLProof.StochasticGradientBandit.measurable_historyParameter
#print axioms BanditRLProof.StochasticGradientBandit.integral_measurableEnvironmentInitialPairKernel_sourceIncrement_eq_expectedSourceIncrement
#print axioms BanditRLProof.StochasticGradientBandit.trajectoryMeasure_condDistrib_action
#print axioms BanditRLProof.StochasticGradientBandit.trajectoryMeasure_condDistrib_nextPair_given_environment_prefix
#print axioms BanditRLProof.StochasticGradientBandit.integral_measurableEnvironmentHistoryStepKernel_sourceIncrement_eq_gapCoordinate
