import BanditRLProof.Algorithms.StochasticGradientBanditTwoArmMeasurableRecurrence

#check BanditRLProof.StochasticGradientBandit.TwoArmBoundedFixedMeanEnvironmentContract
#check BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_forwardSuccessor_le
#check BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_inverseSuccessor_le
#check BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_forwardSuccessor_le_of_contract
#check BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_inverseSuccessor_le_of_contract
#check BanditRLProof.StochasticGradientBandit.measurable_twoArmForwardSuccessorPotential
#check BanditRLProof.StochasticGradientBandit.measurable_twoArmInverseSuccessorPotential
#check BanditRLProof.StochasticGradientBandit.twoArmPrefixFiltration
#check BanditRLProof.StochasticGradientBandit.trajectoryPrefix_condDistrib_integral_forwardSuccessor_le
#check BanditRLProof.StochasticGradientBandit.trajectoryPrefix_condDistrib_integral_inverseSuccessor_le

#print axioms BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_forwardSuccessor_le_of_contract
#print axioms BanditRLProof.StochasticGradientBandit.integral_measurableTwoArmHistoryStepKernel_inverseSuccessor_le_of_contract
#print axioms BanditRLProof.StochasticGradientBandit.twoArmPrefixSigma_mono
#print axioms BanditRLProof.StochasticGradientBandit.trajectoryPrefix_condDistrib_integral_forwardSuccessor_le
#print axioms BanditRLProof.StochasticGradientBandit.trajectoryPrefix_condDistrib_integral_inverseSuccessor_le
