# Conversion Window: AE strict-past representation and same-prediction IID excess

Task id: `ONLINE-AE-CAUSAL-20261008`

Source card:
Scenario card:

## Natural-Language Statement

Write the theorem, proof fragment, or paper equation in precise prose.

## Lean Mapping

| Source symbol | Meaning | Lean declaration | Type / role | Status |
| --- | --- | --- | --- | --- |
| `A_t` | action at time `t` | | action process | unmapped |

## Assumption Ledger

| Assumption | Lean status | Source | Blocking? |
| --- | --- | --- | --- |
| finite action set | typed | task packet | no |
| sub-Gaussian rewards | obligation | cited result | yes |

## Local API And Proof Route

| Leaf | Existing APIs/imports | Mathlib/LML cards | Intended route | Pivot rule |
| --- | --- | --- | --- | --- |
| root | TBD | TBD | theorem-card route plus local wrappers | pivot only after reviewer records a mathematical reason |

## Proof-DAG

| Node | Interface | Dependencies | Owner | Lean declaration | Human proof map | Retrieval cards | Regularity contracts | Mathlib status | Gate | Status |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| root | target theorem | TBD | upper | | this file | TBD | TBD | project-local | `lake build && lake build Tests` | planned |

## Gaps

- [ ] Missing definition:
- [ ] Missing lemma:
- [ ] Missing regularity contract:
- [ ] Mathlib candidate to upstream:
- [ ] Missing cited-result entry:


## Frozen draft contract

# Source intention and precise AE subobligation

Orabona, Online Learning: A Modern Introduction Using Convex Optimization, arXiv1912.13213v10,2026-06-21. Cached original SHA cef4edfa97a6e063e53e9c532717c50aa156e5bc782ea49f969b3385011a1b17. Printed1/PDF13 gives the unit-interval guessing game, fixed IID law, mean benchmark, inability to beat cumulative variance, Eqs1.1/1.2 and their nonnegativity. Printed3/PDF15 emphasizes that only strict past is available; the initial prediction precedes all target observations. These targets are three derived formalization results, not three printed numbered source theorems.

Fix one probability space, one infinite jointly independent same-law real target process Y, one measurable private seed S independent of the entire infinite target process, and one prediction process P. At time t, information F_t is subordinate to the sigma algebra generated by (S,Y_0,...,Y_(t-1)). Round0 corresponds to printed round1 and has empty history. A single seed represents a private tape, not fresh seed information correlated with unrevealed targets. No current-target independence premise is supplied.

This package allows P_t to have an F_t-measurable version equal to P_t almost everywhere for the ambient measure (AEStronglyMeasurable[F_t]). It does not equate this hypothesis with every usual completed-filtration model without a separate representation proof. P_t and Y_t are unit-valued almost everywhere. One countable intersection supplies one full-measure event for every natural time, so the representation is fixed before all horizons. It is not a horizon-dependent algorithm existence theorem.

L1 representation: for any ambient measure, AEStronglyMeasurable[F_t] and AE unit support produce a jointly-in-seed/history measurable policy at every time, unit-valued on ALL seed/history inputs, with P_t equal to this policy along the observed history on one AE event for all t. Choose measurable representatives, apply pinned Doob-Dynkin, and project each policy value to[0,1] using existing Set.projIcc. Clipping preserves P on its AE unit support. This is a classical, law-relative representation of a given prediction process, not an executable learner design or access to future observations. Ambient Y/S measurability, IID or probability normalization are unnecessary for this representation target.

L2 independence: ambient target/seed measurability, joint independence of targets, and independence of the seed from the whole stream derive current-target independence for the AE-adapted P_t by an F_t-measurable representative and AE congruence. No unit bound or same-law condition is necessary for L2. Pairwise-only seed independence would be insufficient and is not substituted.

L3 source lower producer: under the displayed probability/IID/support conditions, for EVERY natural T, the SAME original prediction process satisfies

    expectedFixedRegret(mu,Y,P,T) = sum(t<T) E[(P_t-E[Y_0])^2] >= 0.

expectedFixedRegret is E of actual cumulative squared loss minus the MINIMUM OVER FIXED unit comparators of their expected cumulative loss. The minimum stays outside expectation. Existing source-faithful comparator existence/variance and L2 sum decomposition are reused. Original P, not merely the representative, appears on both sides. The population mean is analysis-only; it is not a learner input. T=0 has empty sums and zero minimum/regret; no division by zero or convergence claim occurs. T>0 averaging and asymptotic-success equivalence remain existing distinct endpoints, not newly inferred here.

Assumption delta: probability/IID/unit support/private causal randomness are source-implicit in this specialization. AE rather than literal pathwise feasibility is a probability-model generalization; L1 supplies a pointwise unit-valued causal version, but no off-null equality is claimed. F-subordination and AE predictability are an explicitly delimited information model. L1's nonprobability case and L2's nonidentical/unbounded case are visible generalizations. Existing independent-prediction consumers are reused after independence is genuinely derived. No kernel realization or completion identity is smuggled into these hypotheses.

Required red boundary: universal stochastic-kernel realization, general completed-information augmentation/factorization coverage, all other Chapter1 obligations, Chapter2 remaining obligations, Chapters3–16 enumeration/required proofs and necessary appendices remain REQUIRED. Original16 source objects and null unknown proof total must be preserved. Three local targets cannot stand for Chapter1 or whole-program completion. No source correction, main merge, deployment, live claim or worktree retirement is proposed.

Exact targets: docs/contracts/online-ae-causal-v1/targets-v1.json. DAG: dependency-DAG-v1.json. L1/L2 dependency-ready, L3 awaits L2. Draft type syntax checked; zero theorem bodies/terminals compiled. Contract semantic round trip and review pending.
