import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import BanditRLProof.Exp3Potential

/-!
# Deterministic exponential-weights regret

This module closes the full-information exponential-weights/Hedge potential
argument that sits immediately below EXP3.  It defines weights from cumulative
losses, normalizes them on an explicit nonempty finite action set, proves the
one-step logarithmic potential inequality, and telescopes it into second-order
and `[0,1]` finite-horizon regret bounds.

No probability space or importance-weighted estimator is used here.  The EXP3
route must separately construct an estimator, prove its conditional
unbiasedness and second-moment bound, and then take expectations of this
pathwise theorem.
-/

namespace BanditRLProof
namespace Exp3

universe u

/-- Cumulative loss of one action before round `t`. -/
noncomputable def cumulativeLoss {Action : Type u}
    (loss : Nat -> Action -> Real) (t : Nat) (a : Action) : Real :=
  (Finset.range t).sum (fun s => loss s a)

/-- Exponential weight generated by the cumulative loss before round `t`. -/
noncomputable def weight {Action : Type u}
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) (a : Action) : Real :=
  Real.exp (-eta * cumulativeLoss loss t a)

/-- Total exponential weight on an explicit finite action set. -/
noncomputable def totalWeight {Action : Type u}
    (arms : Finset Action) (eta : Real)
    (loss : Nat -> Action -> Real) (t : Nat) : Real :=
  arms.sum (weight eta loss t)

/-- Normalized exponential weight at round `t`. -/
noncomputable def distribution {Action : Type u}
    (arms : Finset Action) (eta : Real)
    (loss : Nat -> Action -> Real) (t : Nat) (a : Action) : Real :=
  weight eta loss t a / totalWeight arms eta loss t

/-- Mixed loss incurred by the normalized exponential weights at round `t`. -/
noncomputable def mixedLoss {Action : Type u}
    (arms : Finset Action) (eta : Real)
    (loss : Nat -> Action -> Real) (t : Nat) : Real :=
  arms.sum (fun a => distribution arms eta loss t a * loss t a)

/-- Mixed second moment of the losses at round `t`. -/
noncomputable def mixedSquaredLoss {Action : Type u}
    (arms : Finset Action) (eta : Real)
    (loss : Nat -> Action -> Real) (t : Nat) : Real :=
  arms.sum (fun a => distribution arms eta loss t a * (loss t a) ^ 2)

theorem cumulativeLoss_succ {Action : Type u}
    (loss : Nat -> Action -> Real) (t : Nat) (a : Action) :
    cumulativeLoss loss (t + 1) a = cumulativeLoss loss t a + loss t a := by
  simp [cumulativeLoss, Finset.sum_range_succ]

theorem weight_pos {Action : Type u}
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) (a : Action) :
    0 < weight eta loss t a := by
  exact Real.exp_pos _

theorem weight_succ {Action : Type u}
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) (a : Action) :
    weight eta loss (t + 1) a =
      weight eta loss t a * Real.exp (-eta * loss t a) := by
  rw [weight, cumulativeLoss_succ]
  rw [show -eta * (cumulativeLoss loss t a + loss t a) =
      -eta * cumulativeLoss loss t a + -eta * loss t a by ring]
  rw [Real.exp_add]
  rfl

theorem totalWeight_pos {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) :
    0 < totalWeight arms eta loss t := by
  unfold totalWeight
  refine Finset.sum_pos' (fun a _ha => (weight_pos eta loss t a).le) ?_
  rcases harms with ⟨a, ha⟩
  exact ⟨a, ha, weight_pos eta loss t a⟩

theorem distribution_nonneg {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) (a : Action) :
    0 <= distribution arms eta loss t a := by
  exact div_nonneg (weight_pos eta loss t a).le
    (totalWeight_pos arms harms eta loss t).le

theorem distribution_pos {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) (a : Action) :
    0 < distribution arms eta loss t a := by
  exact div_pos (weight_pos eta loss t a)
    (totalWeight_pos arms harms eta loss t)

theorem sum_distribution {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) :
    arms.sum (distribution arms eta loss t) = 1 := by
  rw [show arms.sum (distribution arms eta loss t) =
      arms.sum (weight eta loss t) / totalWeight arms eta loss t by
    simp only [distribution]
    rw [Finset.sum_div]]
  rw [show arms.sum (weight eta loss t) = totalWeight arms eta loss t by rfl]
  exact div_self (ne_of_gt (totalWeight_pos arms harms eta loss t))

theorem totalWeight_zero {Action : Type u}
    (arms : Finset Action) (eta : Real) (loss : Nat -> Action -> Real) :
    totalWeight arms eta loss 0 = arms.card := by
  simp [totalWeight, weight, cumulativeLoss]

/-- Global quadratic upper bound for a nonnegative exponential argument. -/
theorem exp_neg_le_one_sub_add_sq {x : Real} (hx : 0 <= x) :
    Real.exp (-x) <= 1 - x + x ^ 2 := by
  by_cases hx_le : x <= 1
  · have hneg : -x <= 0 := neg_nonpos.mpr hx
    have habs : |-x| <= 1 := by simpa [abs_of_nonpos hneg]
    have hrem := Real.abs_exp_sub_one_sub_id_le habs
    have hrem_le : Real.exp (-x) - 1 - (-x) <= (-x) ^ 2 :=
      (le_abs_self _).trans hrem
    nlinarith [hrem_le]
  · have hexp : Real.exp (-x) <= 1 := by
      simpa only [Real.exp_zero] using
        Real.exp_le_exp.mpr (neg_nonpos.mpr hx)
    have hone : 1 <= 1 - x + x ^ 2 := by
      nlinarith [lt_of_not_ge hx_le]
    exact hexp.trans hone

/-- Quadratic exponential bound for arbitrary nonnegative learning rates and losses. -/
theorem exp_neg_mul_le_one_sub_add_sq_of_nonneg
    {eta ell : Real} (heta : 0 <= eta) (hell : 0 <= ell) :
    Real.exp (-eta * ell) <= 1 - eta * ell + eta ^ 2 * ell ^ 2 := by
  have h := exp_neg_le_one_sub_add_sq (mul_nonneg heta hell)
  simpa [mul_pow] using h

/-- Backwards-compatible bounded-loss specialization of the global bound. -/
theorem exp_neg_mul_le_one_sub_add_sq
    {eta ell : Real} (heta : 0 <= eta) (_heta_le : eta <= 1)
    (hell : 0 <= ell) (_hell_le : ell <= 1) :
    Real.exp (-eta * ell) <= 1 - eta * ell + eta ^ 2 * ell ^ 2 :=
  exp_neg_mul_le_one_sub_add_sq_of_nonneg heta hell

theorem totalWeight_succ_div_eq_sum_distribution_mul_exp
    {Action : Type u}
    (arms : Finset Action)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat) :
    totalWeight arms eta loss (t + 1) /
        totalWeight arms eta loss t =
      arms.sum (fun a =>
        distribution arms eta loss t a * Real.exp (-eta * loss t a)) := by
  rw [totalWeight]
  simp_rw [weight_succ]
  rw [Finset.sum_div]
  apply Finset.sum_congr rfl
  intro a _ha
  simp only [distribution, totalWeight]
  ring

theorem totalWeight_succ_div_le_of_nonneg
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 <= eta)
    (loss : Nat -> Action -> Real) (t : Nat)
    (hloss : forall a, a ∈ arms -> 0 <= loss t a) :
    totalWeight arms eta loss (t + 1) /
        totalWeight arms eta loss t <=
      1 - eta * mixedLoss arms eta loss t +
        eta ^ 2 * mixedSquaredLoss arms eta loss t := by
  rw [totalWeight_succ_div_eq_sum_distribution_mul_exp arms]
  calc
    arms.sum (fun a =>
        distribution arms eta loss t a * Real.exp (-eta * loss t a)) <=
      arms.sum (fun a =>
        distribution arms eta loss t a *
          (1 - eta * loss t a + eta ^ 2 * (loss t a) ^ 2)) := by
        apply Finset.sum_le_sum
        intro a ha
        exact mul_le_mul_of_nonneg_left
          (exp_neg_mul_le_one_sub_add_sq_of_nonneg heta (hloss a ha))
          (distribution_nonneg arms harms eta loss t a)
    _ = arms.sum (distribution arms eta loss t) -
          eta * mixedLoss arms eta loss t +
          eta ^ 2 * mixedSquaredLoss arms eta loss t := by
        simp only [mixedLoss, mixedSquaredLoss]
        calc
          arms.sum (fun a =>
              distribution arms eta loss t a *
                (1 - eta * loss t a + eta ^ 2 * (loss t a) ^ 2)) =
            arms.sum (fun a =>
              (distribution arms eta loss t a -
                eta * (distribution arms eta loss t a * loss t a)) +
                eta ^ 2 *
                  (distribution arms eta loss t a * (loss t a) ^ 2)) := by
              apply Finset.sum_congr rfl
              intro a _ha
              ring
          _ = arms.sum (distribution arms eta loss t) -
                eta * arms.sum (fun a =>
                  distribution arms eta loss t a * loss t a) +
                eta ^ 2 * arms.sum (fun a =>
                  distribution arms eta loss t a * (loss t a) ^ 2) := by
              rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
                ← Finset.mul_sum, ← Finset.mul_sum]
    _ = 1 - eta * mixedLoss arms eta loss t +
          eta ^ 2 * mixedSquaredLoss arms eta loss t := by
        rw [sum_distribution arms harms]

theorem totalWeight_succ_div_le
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 <= eta) (_heta_le : eta <= 1)
    (loss : Nat -> Action -> Real) (t : Nat)
    (hloss : forall a, a ∈ arms -> 0 <= loss t a ∧ loss t a <= 1) :
    totalWeight arms eta loss (t + 1) /
        totalWeight arms eta loss t <=
      1 - eta * mixedLoss arms eta loss t +
        eta ^ 2 * mixedSquaredLoss arms eta loss t :=
  totalWeight_succ_div_le_of_nonneg arms harms eta heta loss t
    (fun a ha => (hloss a ha).1)

theorem log_totalWeight_succ_sub_le_of_nonneg
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 <= eta)
    (loss : Nat -> Action -> Real) (t : Nat)
    (hloss : forall a, a ∈ arms -> 0 <= loss t a) :
    Real.log (totalWeight arms eta loss (t + 1)) -
        Real.log (totalWeight arms eta loss t) <=
      -eta * mixedLoss arms eta loss t +
        eta ^ 2 * mixedSquaredLoss arms eta loss t := by
  have hnext := totalWeight_pos arms harms eta loss (t + 1)
  have hcurrent := totalWeight_pos arms harms eta loss t
  rw [← Real.log_div (ne_of_gt hnext) (ne_of_gt hcurrent)]
  have hlog := Real.log_le_sub_one_of_pos (div_pos hnext hcurrent)
  have hratio := totalWeight_succ_div_le_of_nonneg
    arms harms eta heta loss t hloss
  linarith

theorem log_totalWeight_succ_sub_le
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 <= eta) (_heta_le : eta <= 1)
    (loss : Nat -> Action -> Real) (t : Nat)
    (hloss : forall a, a ∈ arms -> 0 <= loss t a ∧ loss t a <= 1) :
    Real.log (totalWeight arms eta loss (t + 1)) -
        Real.log (totalWeight arms eta loss t) <=
      -eta * mixedLoss arms eta loss t +
        eta ^ 2 * mixedSquaredLoss arms eta loss t :=
  log_totalWeight_succ_sub_le_of_nonneg arms harms eta heta loss t
    (fun a ha => (hloss a ha).1)

theorem mixedSquaredLoss_le_one
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (loss : Nat -> Action -> Real) (t : Nat)
    (hloss : forall a, a ∈ arms -> 0 <= loss t a ∧ loss t a <= 1) :
    mixedSquaredLoss arms eta loss t <= 1 := by
  calc
    mixedSquaredLoss arms eta loss t <=
        arms.sum (distribution arms eta loss t) := by
      unfold mixedSquaredLoss
      apply Finset.sum_le_sum
      intro a ha
      have hsquare : (loss t a) ^ 2 <= 1 := by
        nlinarith [(hloss a ha).1, (hloss a ha).2]
      simpa using mul_le_mul_of_nonneg_left hsquare
        (distribution_nonneg arms harms eta loss t a)
    _ = 1 := sum_distribution arms harms eta loss t

/--
Second-order finite-horizon Hedge regret bound against one comparator action.
-/
theorem hedge_regret_le_log_card_div_add_eta_mul_mixedSquaredLoss_of_nonneg
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta)
    (loss : Nat -> Action -> Real) (T : Nat)
    (hloss : forall t, t < T -> forall a, a ∈ arms ->
      0 <= loss t a)
    (comparator : Action) (hcomparator : comparator ∈ arms) :
    (Finset.range T).sum (fun t => mixedLoss arms eta loss t) -
        cumulativeLoss loss T comparator <=
      Real.log arms.card / eta +
        eta * (Finset.range T).sum
          (fun t => mixedSquaredLoss arms eta loss t) := by
  have hlog_upper :
      Real.log (totalWeight arms eta loss T) -
          Real.log (totalWeight arms eta loss 0) <=
        -eta * (Finset.range T).sum
            (fun t => mixedLoss arms eta loss t) +
          eta ^ 2 * (Finset.range T).sum
            (fun t => mixedSquaredLoss arms eta loss t) := by
    calc
      Real.log (totalWeight arms eta loss T) -
          Real.log (totalWeight arms eta loss 0) =
        (Finset.range T).sum (fun t =>
          Real.log (totalWeight arms eta loss (t + 1)) -
            Real.log (totalWeight arms eta loss t)) := by
              symm
              exact Exp3Potential.sum_range_forward_difference
                (fun t => Real.log (totalWeight arms eta loss t)) T
      _ <= (Finset.range T).sum (fun t =>
          -eta * mixedLoss arms eta loss t +
            eta ^ 2 * mixedSquaredLoss arms eta loss t) := by
              apply Finset.sum_le_sum
              intro t ht
              exact log_totalWeight_succ_sub_le_of_nonneg arms harms eta heta.le
                loss t (hloss t (Finset.mem_range.mp ht))
      _ = -eta * (Finset.range T).sum
            (fun t => mixedLoss arms eta loss t) +
          eta ^ 2 * (Finset.range T).sum
            (fun t => mixedSquaredLoss arms eta loss t) := by
              rw [Finset.sum_add_distrib, ← Finset.mul_sum,
                ← Finset.mul_sum]
  have hweight_le :
      weight eta loss T comparator <= totalWeight arms eta loss T := by
    exact Finset.single_le_sum
      (fun a _ha => (weight_pos eta loss T a).le) hcomparator
  have hcomparator_log :
      -eta * cumulativeLoss loss T comparator <=
        Real.log (totalWeight arms eta loss T) := by
    have hlog := Real.log_le_log (weight_pos eta loss T comparator) hweight_le
    simpa [weight] using hlog
  have hinitial :
      Real.log (totalWeight arms eta loss 0) = Real.log arms.card := by
    rw [totalWeight_zero]
  rw [hinitial] at hlog_upper
  have hscaled :
      eta * ((Finset.range T).sum (fun t => mixedLoss arms eta loss t) -
          cumulativeLoss loss T comparator) <=
        Real.log arms.card +
          eta ^ 2 * (Finset.range T).sum
            (fun t => mixedSquaredLoss arms eta loss t) := by
    linarith
  calc
    (Finset.range T).sum (fun t => mixedLoss arms eta loss t) -
        cumulativeLoss loss T comparator <=
      (Real.log arms.card +
          eta ^ 2 * (Finset.range T).sum
            (fun t => mixedSquaredLoss arms eta loss t)) / eta := by
        apply (le_div_iff₀ heta).2
        nlinarith
    _ = Real.log arms.card / eta +
        eta * (Finset.range T).sum
          (fun t => mixedSquaredLoss arms eta loss t) := by
      field_simp

/-- Bounded-loss compatibility wrapper for the generalized second-order theorem. -/
theorem hedge_regret_le_log_card_div_add_eta_mul_mixedSquaredLoss
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta) (_heta_le : eta <= 1)
    (loss : Nat -> Action -> Real) (T : Nat)
    (hloss : forall t, t < T -> forall a, a ∈ arms ->
      0 <= loss t a ∧ loss t a <= 1)
    (comparator : Action) (hcomparator : comparator ∈ arms) :
    (Finset.range T).sum (fun t => mixedLoss arms eta loss t) -
        cumulativeLoss loss T comparator <=
      Real.log arms.card / eta +
        eta * (Finset.range T).sum
          (fun t => mixedSquaredLoss arms eta loss t) :=
  hedge_regret_le_log_card_div_add_eta_mul_mixedSquaredLoss_of_nonneg
    arms harms eta heta loss T
      (fun t ht a ha => (hloss t ht a ha).1) comparator hcomparator

/--
Finite-horizon Hedge regret for losses in `[0,1]`.

This is the deterministic full-information theorem consumed by the future
importance-weighted EXP3 route.
-/
theorem hedge_regret_le_log_card_div_add_eta_mul_horizon
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta) (heta_le : eta <= 1)
    (loss : Nat -> Action -> Real) (T : Nat)
    (hloss : forall t, t < T -> forall a, a ∈ arms ->
      0 <= loss t a ∧ loss t a <= 1)
    (comparator : Action) (hcomparator : comparator ∈ arms) :
    (Finset.range T).sum (fun t => mixedLoss arms eta loss t) -
        cumulativeLoss loss T comparator <=
      Real.log arms.card / eta + eta * T := by
  have hsecond :=
    hedge_regret_le_log_card_div_add_eta_mul_mixedSquaredLoss
      arms harms eta heta heta_le loss T hloss comparator hcomparator
  have hsquare_sum :
      (Finset.range T).sum
          (fun t => mixedSquaredLoss arms eta loss t) <= (T : Real) := by
    calc
      (Finset.range T).sum
          (fun t => mixedSquaredLoss arms eta loss t) <=
        (Finset.range T).sum (fun _t => (1 : Real)) := by
          apply Finset.sum_le_sum
          intro t ht
          exact mixedSquaredLoss_le_one arms harms eta loss t
            (hloss t (Finset.mem_range.mp ht))
      _ = (T : Real) := by simp
  exact hsecond.trans
    (add_le_add (le_refl _) (mul_le_mul_of_nonneg_left hsquare_sum heta.le))

end Exp3
end BanditRLProof
