import BanditRLProof.Exp3SampledHistoryScore

/-!
# Predictable adversarial feedback for EXP3

This module packages history-dependent loss vectors that are fixed before the
current action is sampled.  It realizes their chosen coordinate as a
deterministic feedback environment and keeps the EXP3 action law valid after
conditioning on both the latent environment and the visible finite history.
-/

open MeasureTheory ProbabilityTheory

universe u v w x

namespace BanditRLProof
namespace Exp3

/--
A measurable adversarial loss-vector family selected before the current action.
The successor loss vector may depend on the environment and the preceding pair
history, but not on the action sampled at that successor step.
-/
structure PredictableLossVector
    (Env : Type u) (Action : Type v)
    [MeasurableSpace Env] [MeasurableSpace Action] where
  initial : Env -> Action -> Real
  successor : (n : Nat) ->
    Env -> History.FinitePairHistory Action Real n -> Action -> Real
  measurable_initial : Measurable (fun input : Env × Action =>
    initial input.1 input.2)
  measurable_successor : forall n, Measurable
    (fun input : Env × (History.FinitePairHistory Action Real n × Action) =>
      successor n input.1 input.2.1 input.2.2)
  initial_nonneg : forall env action, 0 <= initial env action
  initial_le_one : forall env action, initial env action <= 1
  successor_nonneg : forall n env history action,
    0 <= successor n env history action
  successor_le_one : forall n env history action,
    successor n env history action <= 1

/-- Deterministic chosen-coordinate feedback generated by a predictable loss family. -/
noncomputable def PredictableLossVector.environment
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : PredictableLossVector Env Action) :
    Thompson.MeasurableHistoryEnvironment Env Action Real where
  initialFeedback := Kernel.deterministic
    (fun input : Env × Action => loss.initial input.1 input.2)
    loss.measurable_initial
  feedback n := Kernel.deterministic
    (fun input : Env × (History.FinitePairHistory Action Real n × Action) =>
      loss.successor n input.1 input.2.1 input.2.2)
    (loss.measurable_successor n)

@[simp]
theorem PredictableLossVector.environment_initialFeedback_apply
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : PredictableLossVector Env Action) (env : Env) (action : Action) :
    loss.environment.initialFeedback (env, action) =
      Measure.dirac (loss.initial env action) := by
  rfl

@[simp]
theorem PredictableLossVector.environment_feedback_apply
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : PredictableLossVector Env Action) (n : Nat)
    (env : Env) (history : History.FinitePairHistory Action Real n)
    (action : Action) :
    loss.environment.feedback n (env, (history, action)) =
      Measure.dirac (loss.successor n env history action) := by
  rfl

theorem PredictableLossVector.initial_mem_unitInterval
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : PredictableLossVector Env Action) (env : Env) (action : Action) :
    loss.initial env action ∈ Set.Icc (0 : Real) 1 :=
  ⟨loss.initial_nonneg env action, loss.initial_le_one env action⟩

theorem PredictableLossVector.successor_mem_unitInterval
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : PredictableLossVector Env Action) (n : Nat) (env : Env)
    (history : History.FinitePairHistory Action Real n) (action : Action) :
    loss.successor n env history action ∈ Set.Icc (0 : Real) 1 :=
  ⟨loss.successor_nonneg n env history action,
    loss.successor_le_one n env history action⟩

/--
Mixing fixed-environment trajectory laws preserves a common action kernel when
the conditioning variable retains the environment coordinate.
-/
theorem trajectoryMixture_condDistrib_action_given_environment_history
    {Env : Type u} {Omega : Type v} {History : Type w} {Action : Type x}
    [MeasurableSpace Env] [MeasurableSpace Omega]
    [MeasurableSpace History]
    [MeasurableSpace Action] [StandardBorelSpace Action] [Nonempty Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (trajectory : Kernel Env Omega) [IsMarkovKernel trajectory]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hlaw : forall env,
      (trajectory env).map (fun omega => (history omega, action omega)) =
        (trajectory env).map history ⊗ₘ policy) :
    condDistrib (action ∘ Prod.snd)
        (fun sample : Env × Omega => (sample.1, history sample.2))
        (prior ⊗ₘ trajectory) =ᵐ[
      (prior ⊗ₘ trajectory).map
        (fun sample : Env × Omega => (sample.1, history sample.2))]
      policy.comap (fun input : Env × History => input.2)
        (measurable_snd : Measurable (fun input : Env × History => input.2)) := by
  apply condDistrib_ae_eq_of_measure_eq_compProd_of_measurable
    ((measurable_fst.prodMk (hhistory.comp measurable_snd)))
    (haction.comp measurable_snd)
  apply Measure.ext_prod
  intro environmentHistoryEvent actionEvent hEnvironmentHistoryEvent hActionEvent
  let pairMap : Omega -> History × Action :=
    fun omega => (history omega, action omega)
  let globalPairMap : Env × Omega -> (Env × History) × Action :=
    fun sample => ((sample.1, history sample.2), action sample.2)
  let globalHistory : Env × Omega -> Env × History :=
    fun sample => (sample.1, history sample.2)
  have hpairMap : Measurable pairMap := hhistory.prodMk haction
  have hglobalPairMap : Measurable globalPairMap :=
    (measurable_fst.prodMk (hhistory.comp measurable_snd)).prodMk
      (haction.comp measurable_snd)
  have hglobalHistory : Measurable globalHistory :=
    measurable_fst.prodMk (hhistory.comp measurable_snd)
  change (Measure.map globalPairMap (prior ⊗ₘ trajectory))
      (environmentHistoryEvent ×ˢ actionEvent) =
    (Measure.map globalHistory (prior ⊗ₘ trajectory) ⊗ₘ
      policy.comap (fun input : Env × History => input.2)
        (measurable_snd : Measurable
          (fun input : Env × History => input.2)))
        (environmentHistoryEvent ×ˢ actionEvent)
  rw [Measure.map_apply hglobalPairMap
      (hEnvironmentHistoryEvent.prod hActionEvent),
    Measure.compProd_apply_prod hEnvironmentHistoryEvent hActionEvent]
  simp only [Kernel.coe_comap, Function.comp_apply]
  conv_rhs =>
    change ∫⁻ a in environmentHistoryEvent,
      ((fun h => policy h actionEvent) ∘ Prod.snd) a
        ∂Measure.map globalHistory (prior ⊗ₘ trajectory)
    rw [MeasureTheory.setLIntegral_map hEnvironmentHistoryEvent
      ((policy.measurable_coe hActionEvent).comp measurable_snd)
      hglobalHistory]
  have hhistorySection (env : Env) : MeasurableSet
      {h : History | (env, h) ∈ environmentHistoryEvent} :=
    hEnvironmentHistoryEvent.preimage
      (measurable_const.prodMk measurable_id)
  have hsection (env : Env) : MeasurableSet
      {omega : Omega | (env, history omega) ∈ environmentHistoryEvent} :=
    (hhistorySection env).preimage hhistory
  let integrand : Env × Omega -> ENNReal :=
    fun sample => policy (history sample.2) actionEvent
  have hintegrand : Measurable integrand :=
    ((policy.measurable_coe hActionEvent).comp hhistory).comp measurable_snd
  have hglobalHistoryEvent :
      MeasurableSet (globalHistory ⁻¹' environmentHistoryEvent) :=
    hglobalHistory hEnvironmentHistoryEvent
  conv_rhs =>
    change ∫⁻ sample in globalHistory ⁻¹' environmentHistoryEvent,
      integrand sample ∂(prior ⊗ₘ trajectory)
    rw [← MeasureTheory.lintegral_indicator hglobalHistoryEvent,
      Measure.lintegral_compProd
        (hintegrand.indicator hglobalHistoryEvent)]
  rw [Measure.compProd_apply]
  · apply lintegral_congr
    intro env
    have hpointwise :
        trajectory env
            (pairMap ⁻¹' ({h : History | (env, h) ∈ environmentHistoryEvent} ×ˢ
              actionEvent)) =
          ∫⁻ h in {h : History | (env, h) ∈ environmentHistoryEvent},
            policy h actionEvent ∂(trajectory env).map history := by
      rw [← Measure.map_apply hpairMap
          ((hhistorySection env).prod hActionEvent),
        hlaw env,
        Measure.compProd_apply_prod (hhistorySection env) hActionEvent]
    have hpreimage :
        (Prod.mk env) ⁻¹'
            (globalPairMap ⁻¹'
              (environmentHistoryEvent ×ˢ actionEvent)) =
          pairMap ⁻¹' ({h : History | (env, h) ∈ environmentHistoryEvent} ×ˢ
            actionEvent) := by
      ext omega
      simp [pairMap, globalPairMap]
    rw [hpreimage, hpointwise,
      MeasureTheory.setLIntegral_map (hhistorySection env)
        (policy.measurable_coe hActionEvent) hhistory]
    conv_rhs =>
      change ∫⁻ omega,
        (globalHistory ⁻¹' environmentHistoryEvent).indicator integrand
          (env, omega) ∂trajectory env
      rw [show
          (fun omega =>
            (globalHistory ⁻¹' environmentHistoryEvent).indicator integrand
              (env, omega)) =
            {omega : Omega |
              (env, history omega) ∈ environmentHistoryEvent}.indicator
                (fun omega => policy (history omega) actionEvent) by
          funext omega
          by_cases hmem :
              (env, history omega) ∈ environmentHistoryEvent <;>
            simp [globalHistory, integrand, Set.indicator, hmem]]
      rw [MeasureTheory.lintegral_indicator (hsection env)]
    rfl
  · exact hglobalPairMap
      (hEnvironmentHistoryEvent.prod hActionEvent)

/--
The concrete sampled-score EXP3 action remains independent of the current
predictable loss vector after conditioning on the environment and prefix.
-/
theorem sampledImportanceWeightedTrajectoryMeasure_condDistrib_action_given_environment
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (loss : PredictableLossVector Env Action) (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.2 (n + 1)).1)
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.1, Preorder.frestrictLe n sample.2))
        (prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
          eta gamma hgamma_nonneg hgamma_le_one loss.environment) =ᵐ[
      (prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
        eta gamma hgamma_nonneg hgamma_le_one loss.environment).map
          (fun sample : Env × ((k : Nat) -> Action × Real) =>
            (sample.1, Preorder.frestrictLe n sample.2))]
      (finiteActionKernel arms
        (sampledHistoryDistribution arms eta gamma n)
        (exploredHistoryDistributionSource arms harms eta gamma
          (sampledHistoryScore arms eta gamma)
          (measurableFiniteHistoryScore_sampledHistoryScore arms eta gamma)
          hgamma_nonneg hgamma_le_one n)).comap
        (fun input : Env × History.FinitePairHistory Action Real n => input.2)
        (measurable_snd : Measurable
          (fun input : Env × History.FinitePairHistory Action Real n =>
            input.2)) := by
  simpa [sampledImportanceWeightedTrajectoryKernel,
    sampledImportanceWeightedHistoryAlgorithm_policy,
    sampledHistoryDistribution] using
    (trajectoryMixture_condDistrib_action_given_environment_history prior
      (sampledImportanceWeightedTrajectoryKernel arms harms eta gamma
        hgamma_nonneg hgamma_le_one loss.environment)
      (Preorder.frestrictLe n) (Preorder.measurable_frestrictLe n)
      (fun trajectory => (trajectory (n + 1)).1)
      (measurable_fst.comp (measurable_pi_apply (n + 1)))
      ((sampledImportanceWeightedHistoryAlgorithm arms harms eta gamma
        hgamma_nonneg hgamma_le_one).policy n)
      (fun env =>
        Thompson.canonicalMeasurableEnvironmentTrajectoryKernel_map_history_action_eq_compProd
          (sampledImportanceWeightedHistoryAlgorithm arms harms eta gamma
            hgamma_nonneg hgamma_le_one)
          loss.environment env n))

end Exp3
end BanditRLProof
