import Mathlib.Probability.Kernel.CondDistrib
import Mathlib.Probability.Kernel.Composition.IntegralCompProd
import BanditRLProof.Exp3ImportanceWeighted

/-!
# Conditional-law transport for EXP3 importance-weighted moments

This module turns the finite weighted-sum identities for the EXP3 estimator
into Bochner-integral identities under an actual history-conditional action
law.  The conditional distribution is represented by a Markov kernel whose
values are explicit finite sums of Dirac measures.
-/

namespace BanditRLProof
namespace Exp3

open MeasureTheory ProbabilityTheory

universe u v w

/-- Probability-vector contracts on an explicit finite action support. -/
structure FiniteActionDistribution {Action : Type u}
    (arms : Finset Action) (prob : Action -> Real) : Prop where
  nonneg : forall action, action ∈ arms -> 0 <= prob action
  sum_eq_one : arms.sum prob = 1

/-- The finite action law generated by a probability vector on `arms`. -/
noncomputable def finiteActionMeasure {Action : Type u} [MeasurableSpace Action]
    (arms : Finset Action) (prob : Action -> Real) : Measure Action :=
  arms.sum (fun action =>
    ENNReal.ofReal (prob action) • Measure.dirac action)

theorem finiteActionMeasure_isProbabilityMeasure {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    (arms : Finset Action) (prob : Action -> Real)
    (hdist : FiniteActionDistribution arms prob) :
    IsProbabilityMeasure (finiteActionMeasure arms prob) := by
  rw [isProbabilityMeasure_iff]
  simp [finiteActionMeasure, ← ENNReal.ofReal_sum_of_nonneg hdist.nonneg,
    hdist.sum_eq_one]

theorem integral_finiteActionMeasure_eq_sum {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    (arms : Finset Action) (prob : Action -> Real)
    (hdist : FiniteActionDistribution arms prob) (f : Action -> Real) :
    integral (finiteActionMeasure arms prob) f =
      arms.sum (fun action => prob action * f action) := by
  rw [finiteActionMeasure, integral_finset_sum_measure]
  · apply Finset.sum_congr rfl
    intro action haction
    rw [integral_smul_measure, integral_dirac]
    simp [ENNReal.toReal_ofReal (hdist.nonneg action haction)]
  · intro action _haction
    exact (integrable_dirac (by simp)).smul_measure ENNReal.ofReal_ne_top

/--
An identified finite conditional action law converts any integrable
history/action score into the corresponding probability-weighted finite sum.
-/
theorem integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob : History -> Action -> Real)
    (hdist : forall h, FiniteActionDistribution arms (prob h))
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (score : History × Action -> Real) (hscore : Measurable score)
    (hIntegrable : Integrable score (mu.map history ⊗ₘ policy)) :
    integral mu (fun omega => score (history omega, action omega)) =
      integral (mu.map history) (fun h =>
        arms.sum (fun candidate => prob h candidate * score (h, candidate))) := by
  have hpair :
      mu.map (fun omega => (history omega, action omega)) =
        mu.map history ⊗ₘ policy :=
    (condDistrib_ae_eq_iff_measure_eq_compProd history
      haction.aemeasurable policy).mp hcond
  calc
    integral mu (fun omega => score (history omega, action omega)) =
        integral (mu.map (fun omega => (history omega, action omega))) score := by
      symm
      rw [integral_map (hhistory.prodMk haction).aemeasurable
        hscore.aestronglyMeasurable]
    _ = integral (mu.map history ⊗ₘ policy) score := by rw [hpair]
    _ = integral (mu.map history) (fun h => integral (policy h) (fun a => score (h, a))) :=
      Measure.integral_compProd hIntegrable
    _ = integral (mu.map history) (fun h =>
        arms.sum (fun candidate => prob h candidate * score (h, candidate))) := by
      apply integral_congr_ae
      filter_upwards [hpolicy] with h hh
      rw [hh, integral_finiteActionMeasure_eq_sum arms (prob h) (hdist h)]

/-- One-round armwise unbiasedness under the identified conditional action law. -/
theorem integral_importanceWeightedLoss_eq_integral_loss_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (hdist : forall h, FiniteActionDistribution arms (prob h))
    (hprob : forall h candidate, candidate ∈ arms -> 0 < prob h candidate)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (comparator : Action) (hcomparator : comparator ∈ arms)
    (hscore : Measurable (fun z : History × Action =>
      importanceWeightedLoss (prob z.1) (loss z.1) z.2 comparator))
    (hIntegrable : Integrable (fun z : History × Action =>
      importanceWeightedLoss (prob z.1) (loss z.1) z.2 comparator)
      (mu.map history ⊗ₘ policy)) :
    integral mu (fun omega =>
        importanceWeightedLoss (prob (history omega)) (loss (history omega))
          (action omega) comparator) =
      integral (mu.map history) (fun h => loss h comparator) := by
  have htransport :=
    integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
      mu history hhistory action haction arms prob hdist policy hpolicy hcond
      (fun z => importanceWeightedLoss (prob z.1) (loss z.1) z.2 comparator)
      hscore hIntegrable
  refine htransport.trans ?_
  apply integral_congr_ae
  filter_upwards [] with h
  exact sum_prob_mul_importanceWeightedLoss_eq_loss
    arms (prob h) (loss h) comparator hcomparator
      (ne_of_gt (hprob h comparator hcomparator))

/-- The mixed estimated-loss integral equals the true mixed-loss integral. -/
theorem integral_mixedImportanceWeightedLoss_eq_integral_mixedLoss_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (hdist : forall h, FiniteActionDistribution arms (prob h))
    (hprob : forall h candidate, candidate ∈ arms -> 0 < prob h candidate)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (hscore : Measurable (fun z : History × Action =>
      mixedImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2))
    (hIntegrable : Integrable (fun z : History × Action =>
      mixedImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2)
      (mu.map history ⊗ₘ policy)) :
    integral mu (fun omega =>
        mixedImportanceWeightedLoss arms (prob (history omega))
          (loss (history omega)) (action omega)) =
      integral (mu.map history) (fun h =>
        arms.sum (fun candidate => prob h candidate * loss h candidate)) := by
  have htransport :=
    integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
      mu history hhistory action haction arms prob hdist policy hpolicy hcond
      (fun z => mixedImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2)
      hscore hIntegrable
  refine htransport.trans ?_
  apply integral_congr_ae
  filter_upwards [] with h
  exact sum_prob_mul_mixedImportanceWeightedLoss_eq_mixedLoss
    arms (prob h) (loss h) (fun candidate hcandidate =>
      ne_of_gt (hprob h candidate hcandidate))

/-- A second predictable finite distribution may weight the estimator without
changing the sampling law used by the conditional transport. -/
theorem integral_weightedImportanceWeightedLoss_eq_integral_weightedLoss_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob weight loss : History -> Action -> Real)
    (hdist : forall h, FiniteActionDistribution arms (prob h))
    (hprob : forall h candidate, candidate ∈ arms -> 0 < prob h candidate)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (hscore : Measurable (fun z : History × Action =>
      weightedImportanceWeightedLoss arms (prob z.1) (weight z.1)
        (loss z.1) z.2))
    (hIntegrable : Integrable (fun z : History × Action =>
      weightedImportanceWeightedLoss arms (prob z.1) (weight z.1)
        (loss z.1) z.2) (mu.map history ⊗ₘ policy)) :
    integral mu (fun omega =>
        weightedImportanceWeightedLoss arms (prob (history omega))
          (weight (history omega)) (loss (history omega)) (action omega)) =
      integral (mu.map history) (fun h =>
        arms.sum (fun candidate => weight h candidate * loss h candidate)) := by
  have htransport :=
    integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
      mu history hhistory action haction arms prob hdist policy hpolicy hcond
      (fun z => weightedImportanceWeightedLoss arms (prob z.1) (weight z.1)
        (loss z.1) z.2) hscore hIntegrable
  refine htransport.trans ?_
  apply integral_congr_ae
  filter_upwards [] with h
  exact sum_prob_mul_weightedImportanceWeightedLoss_eq_weightedLoss
    arms (prob h) (weight h) (loss h) (fun candidate hcandidate =>
      ne_of_gt (hprob h candidate hcandidate))

/-- The mixed estimator-square integral equals the integral of summed loss squares. -/
theorem integral_mixedSquaredImportanceWeightedLoss_eq_integral_sum_loss_sq_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (hdist : forall h, FiniteActionDistribution arms (prob h))
    (hprob : forall h candidate, candidate ∈ arms -> 0 < prob h candidate)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (hscore : Measurable (fun z : History × Action =>
      mixedSquaredImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2))
    (hIntegrable : Integrable (fun z : History × Action =>
      mixedSquaredImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2)
      (mu.map history ⊗ₘ policy)) :
    integral mu (fun omega =>
        mixedSquaredImportanceWeightedLoss arms (prob (history omega))
          (loss (history omega)) (action omega)) =
      integral (mu.map history) (fun h =>
        arms.sum (fun candidate => (loss h candidate) ^ 2)) := by
  have htransport :=
    integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
      mu history hhistory action haction arms prob hdist policy hpolicy hcond
      (fun z => mixedSquaredImportanceWeightedLoss arms
        (prob z.1) (loss z.1) z.2) hscore hIntegrable
  refine htransport.trans ?_
  apply integral_congr_ae
  filter_upwards [] with h
  exact sum_prob_mul_mixedSquaredImportanceWeightedLoss_eq_sum_loss_sq
    arms (prob h) (loss h) (fun candidate hcandidate =>
      ne_of_gt (hprob h candidate hcandidate))

end Exp3
end BanditRLProof
