import BanditRLProof.Exp3RealizedRegret

/-!
# Uniform-horizon predictable EXP3 regret

This module closes the small-horizon branch left by the tuned square-root
theorem.  It clips the exploration rate at `1/2`, uses the tuned theorem when
`4 K log K <= T`, and otherwise uses the pathwise `[0,1]` loss budget.
-/

namespace BanditRLProof
namespace Exp3

open MeasureTheory ProbabilityTheory

universe u v

/-- Any generated predictable EXP3 process has expected exploration-mixed
regret at most the horizon, independently of the learning rate. -/
theorem sampledPredictable_exploredExpectedRegret_le_horizon
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsProbabilityMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (hgamma_nonneg : 0 <= gamma)
    (hgamma_le_one : gamma <= 1)
    (loss : PredictableLossVector Env Action) (horizon : Nat)
    (comparator : Action) :
    let mu := prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
      eta gamma hgamma_nonneg hgamma_le_one loss.environment
    integral mu (fun sample =>
      (Finset.range horizon).sum (fun t =>
          sampledTrajectoryExploredPredictableLossAt
            arms eta gamma loss t sample) -
        (Finset.range horizon).sum (fun t =>
          predictableLossAt loss t sample comparator)) <=
      (horizon : Real) := by
  dsimp only
  let mu := prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
    eta gamma hgamma_nonneg hgamma_le_one loss.environment
  have hexploredSum : Integrable (fun sample =>
      (Finset.range horizon).sum (fun t =>
        sampledTrajectoryExploredPredictableLossAt
          arms eta gamma loss t sample)) mu :=
    IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun t sample => sampledTrajectoryExploredPredictableLossAt
        arms eta gamma loss t sample)
      (fun t _ht => integrable_sampledTrajectoryExploredPredictableLossAt
        mu arms harms eta gamma hgamma_nonneg hgamma_le_one loss t)
  have hcomparatorSum : Integrable (fun sample =>
      (Finset.range horizon).sum (fun t =>
        predictableLossAt loss t sample comparator)) mu :=
    IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun t sample => predictableLossAt loss t sample comparator)
      (fun t _ht => integrable_predictableLossAt mu loss t comparator)
  have hae : ∀ᵐ sample ∂mu,
      (Finset.range horizon).sum (fun t =>
          sampledTrajectoryExploredPredictableLossAt
            arms eta gamma loss t sample) -
        (Finset.range horizon).sum (fun t =>
          predictableLossAt loss t sample comparator) <=
        (horizon : Real) := by
    filter_upwards [] with sample
    have hexplored :
        (Finset.range horizon).sum (fun t =>
            sampledTrajectoryExploredPredictableLossAt
              arms eta gamma loss t sample) <= (horizon : Real) := by
      calc
        _ <= (Finset.range horizon).sum (fun _t => (1 : Real)) := by
          apply Finset.sum_le_sum
          intro t _ht
          exact (sampledTrajectoryExploredPredictableLossAt_mem_unitInterval
            arms harms eta gamma hgamma_nonneg hgamma_le_one loss t sample).2
        _ = (horizon : Real) := by simp
    have hcomparator : 0 <= (Finset.range horizon).sum (fun t =>
        predictableLossAt loss t sample comparator) := by
      apply Finset.sum_nonneg
      intro t _ht
      cases t with
      | zero => exact loss.initial_nonneg sample.1 comparator
      | succ n =>
          exact loss.successor_nonneg n sample.1
            (Preorder.frestrictLe n sample.2) comparator
    linarith
  have hmono := integral_mono_ae
    (hexploredSum.sub hcomparatorSum) (integrable_const _) hae
  simpa [mu] using hmono

/-- The same horizon bound for the scalar losses actually generated by the
predictable environment. -/
theorem sampledPredictable_realizedExpectedRegret_le_horizon
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsProbabilityMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (hgamma_nonneg : 0 <= gamma)
    (hgamma_le_one : gamma <= 1)
    (loss : PredictableLossVector Env Action) (horizon : Nat)
    (comparator : Action) :
    let mu := prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
      eta gamma hgamma_nonneg hgamma_le_one loss.environment
    integral mu (fun sample =>
      (Finset.range horizon).sum (fun t =>
          sampledTrajectoryRealizedLossAt t sample) -
        (Finset.range horizon).sum (fun t =>
          predictableLossAt loss t sample comparator)) <=
      (horizon : Real) := by
  dsimp only
  let mu := prior ⊗ₘ sampledImportanceWeightedTrajectoryKernel arms harms
    eta gamma hgamma_nonneg hgamma_le_one loss.environment
  have htransport :=
    sampledPredictableRealized_finiteHorizon_integral_eq_explored
      prior arms harms eta gamma hgamma_nonneg hgamma_le_one loss horizon
  have hbase := sampledPredictable_exploredExpectedRegret_le_horizon
    prior arms harms eta gamma hgamma_nonneg hgamma_le_one loss horizon comparator
  dsimp only at htransport hbase
  have hrealizedSum : Integrable (fun sample =>
      (Finset.range horizon).sum (fun t =>
        sampledTrajectoryRealizedLossAt t sample)) mu :=
    IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun t sample => sampledTrajectoryRealizedLossAt t sample)
      (fun t _ht => integrable_sampledTrajectoryRealizedLossAt
        prior arms harms eta gamma hgamma_nonneg hgamma_le_one loss t)
  have hexploredSum : Integrable (fun sample =>
      (Finset.range horizon).sum (fun t =>
        sampledTrajectoryExploredPredictableLossAt
          arms eta gamma loss t sample)) mu :=
    IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun t sample => sampledTrajectoryExploredPredictableLossAt
        arms eta gamma loss t sample)
      (fun t _ht => integrable_sampledTrajectoryExploredPredictableLossAt
        mu arms harms eta gamma hgamma_nonneg hgamma_le_one loss t)
  have hcomparatorSum : Integrable (fun sample =>
      (Finset.range horizon).sum (fun t =>
        predictableLossAt loss t sample comparator)) mu :=
    IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun t sample => predictableLossAt loss t sample comparator)
      (fun t _ht => integrable_predictableLossAt mu loss t comparator)
  rw [integral_sub hexploredSum hcomparatorSum] at hbase
  rw [integral_sub hrealizedSum hcomparatorSum]
  rw [htransport]
  exact hbase

/-- Exploration rate clipped to the range supported uniformly by the compiled
expected-regret route. -/
noncomputable def clippedExplorationRate (K T : Real) : Real :=
  min (1 / 2) (tunedExplorationRate K T)

/-- Learning rate paired with `clippedExplorationRate`. -/
noncomputable def clippedLearningRate (K T : Real) : Real :=
  clippedExplorationRate K T / K

theorem clippedExplorationRate_nonneg (K T : Real) :
    0 <= clippedExplorationRate K T := by
  rw [clippedExplorationRate]
  exact le_min (by norm_num) (Real.sqrt_nonneg _)

theorem clippedExplorationRate_le_half (K T : Real) :
    clippedExplorationRate K T <= 1 / 2 := by
  exact min_le_left _ _

theorem clippedExplorationRate_eq_tuned
    (K T : Real) (h : tunedExplorationRate K T <= 1 / 2) :
    clippedExplorationRate K T = tunedExplorationRate K T := by
  exact min_eq_right h

/-- Generated predictable EXP3 kernel using the clipped all-horizon rates. -/
noncomputable def clippedPredictableTrajectoryKernel
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [Nonempty Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (loss : PredictableLossVector Env Action) (horizon : Nat) :
    Kernel Env (Nat -> Action × Real) :=
  sampledImportanceWeightedTrajectoryKernel arms harms
    (clippedLearningRate (arms.card : Real) (horizon : Real))
    (clippedExplorationRate (arms.card : Real) (horizon : Real))
    (clippedExplorationRate_nonneg _ _)
    ((clippedExplorationRate_le_half _ _).trans (by norm_num))
    loss.environment

/-- Uniform-horizon expected regret for the scalar loss actually generated by
predictable EXP3.  The minimum records the trivial short-horizon budget and the
large-horizon square-root theorem without imposing a regime assumption. -/
theorem sampledPredictable_clippedRealizedExpectedRegret_le_min
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsProbabilityMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (hcard_two : 2 <= arms.card)
    (loss : PredictableLossVector Env Action) (horizon : Nat)
    (comparator : Action) (hcomparator : comparator ∈ arms) :
    let K := (arms.card : Real)
    let T := (horizon : Real)
    let mu := prior ⊗ₘ clippedPredictableTrajectoryKernel
      arms harms loss horizon
    integral mu (fun sample =>
      (Finset.range horizon).sum (fun t =>
          sampledTrajectoryRealizedLossAt t sample) -
        (Finset.range horizon).sum (fun t =>
          predictableLossAt loss t sample comparator)) <=
      min T (4 * Real.sqrt (K * T * Real.log K)) := by
  dsimp only
  let K := (arms.card : Real)
  let T := (horizon : Real)
  let gamma := clippedExplorationRate K T
  let eta := clippedLearningRate K T
  let mu := prior ⊗ₘ clippedPredictableTrajectoryKernel arms harms loss horizon
  have hgamma_nonneg : 0 <= gamma := clippedExplorationRate_nonneg K T
  have hgamma_le_one : gamma <= 1 :=
    (clippedExplorationRate_le_half K T).trans (by norm_num)
  have htrivial := sampledPredictable_realizedExpectedRegret_le_horizon
    prior arms harms eta gamma hgamma_nonneg hgamma_le_one loss horizon comparator
  dsimp only at htrivial
  have htrivial' : integral mu (fun sample =>
      (Finset.range horizon).sum (fun t =>
          sampledTrajectoryRealizedLossAt t sample) -
        (Finset.range horizon).sum (fun t =>
          predictableLossAt loss t sample comparator)) <= T := by
    simpa [mu, eta, gamma, clippedPredictableTrajectoryKernel] using htrivial
  have hK_one : 1 < K := by
    dsimp [K]
    exact_mod_cast hcard_two
  have hKlog_pos : 0 < K * Real.log K :=
    mul_pos (by linarith) (Real.log_pos hK_one)
  have hT_nonneg : 0 <= T := by
    dsimp [T]
    exact_mod_cast (Nat.zero_le horizon)
  by_cases hscale : 4 * K * Real.log K <= T
  · have hT_pos : 0 < T := by nlinarith
    have hhorizon_pos : 0 < horizon := by
      have hT_pos' : 0 < (horizon : Real) := by simpa [T] using hT_pos
      exact_mod_cast hT_pos'
    have hgamma_tuned : tunedExplorationRate K T <= 1 / 2 :=
      tunedExplorationRate_le_half K T hT_pos hscale
    have htuned :=
      sampledPredictable_realizedExpectedRegret_le_four_mul_sqrt
        prior arms harms hcard_two loss horizon hhorizon_pos
          (by simpa [K, T] using hscale) comparator hcomparator
    dsimp only at htuned
    have htuned' : integral mu (fun sample =>
        (Finset.range horizon).sum (fun t =>
            sampledTrajectoryRealizedLossAt t sample) -
          (Finset.range horizon).sum (fun t =>
            predictableLossAt loss t sample comparator)) <=
        4 * Real.sqrt (K * T * Real.log K) := by
      simpa [mu, K, T, clippedPredictableTrajectoryKernel,
        clippedLearningRate, clippedExplorationRate_eq_tuned K T hgamma_tuned,
        tunedPredictableTrajectoryKernel, tunedLearningRate] using htuned
    exact le_min htrivial' htuned'
  · have hsmall : T < 4 * K * Real.log K := lt_of_not_ge hscale
    have hradicand : 0 <= K * T * Real.log K := by
      nlinarith [mul_nonneg hT_nonneg hKlog_pos.le]
    have hsquare := Real.sq_sqrt hradicand
    have hsqrt_nonneg := Real.sqrt_nonneg (K * T * Real.log K)
    have hmul := mul_le_mul_of_nonneg_left hsmall.le hT_nonneg
    have hT_le_sqrt : T <= 4 * Real.sqrt (K * T * Real.log K) := by
      nlinarith
    rw [min_eq_left hT_le_sqrt]
    exact htrivial'

end Exp3
end BanditRLProof
