import BanditRLProof.Exp3ScoreRegularity
import BanditRLProof.Algorithms.ThompsonRecursiveSampler

/-!
# Recursive measurable EXP3 trajectories

This module turns a measurable finite-history score into the exploration-mixed
exponential policy used by EXP3.  It proves normalization, coordinate
measurability, and a uniform exploration floor, packages the policy as the
project's stochastic finite-history algorithm, and invokes the Mathlib-backed
Ionescu--Tulcea trajectory kernel.  The resulting theorem identifies every
successor action's conditional law with the explicit finite-action policy.

The score is an input contract here.  Constructing it recursively from sampled
importance-weighted losses is the next layer of the EXP3 route.
-/

namespace BanditRLProof
namespace Exp3

open MeasureTheory ProbabilityTheory

universe u v w

/-- Exponential weight generated by a finite-history cumulative score. -/
noncomputable def historyWeight {Action History : Type*}
    (eta : Real) (score : History -> Action -> Real)
    (history : History) (action : Action) : Real :=
  Real.exp (-eta * score history action)

/-- Total exponential weight on the explicit finite support. -/
noncomputable def historyTotalWeight {Action History : Type*}
    (arms : Finset Action) (eta : Real)
    (score : History -> Action -> Real) (history : History) : Real :=
  arms.sum (historyWeight eta score history)

/-- Normalized exponential history policy before explicit exploration mixing. -/
noncomputable def normalizedHistoryDistribution {Action History : Type*}
    (arms : Finset Action) (eta : Real)
    (score : History -> Action -> Real) (history : History)
    (action : Action) : Real :=
  historyWeight eta score history action /
    historyTotalWeight arms eta score history

/-- EXP3 policy: normalized exponential weights mixed with uniform exploration. -/
noncomputable def exploredHistoryDistribution {Action History : Type*}
    (arms : Finset Action) (eta gamma : Real)
    (score : History -> Action -> Real) (history : History)
    (action : Action) : Real :=
  (1 - gamma) * normalizedHistoryDistribution arms eta score history action +
    gamma / (arms.card : Real)

theorem historyTotalWeight_pos
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score : History -> Action -> Real) (history : History) :
    0 < historyTotalWeight arms eta score history := by
  unfold historyTotalWeight
  refine Finset.sum_pos' (fun action _ => (Real.exp_pos _).le) ?_
  rcases harms with ⟨action, haction⟩
  exact ⟨action, haction, Real.exp_pos _⟩

theorem normalizedHistoryDistribution_nonneg
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score : History -> Action -> Real)
    (history : History) (action : Action) :
    0 <= normalizedHistoryDistribution arms eta score history action := by
  exact div_nonneg (Real.exp_pos _).le
    (historyTotalWeight_pos arms harms eta score history).le

theorem sum_normalizedHistoryDistribution
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score : History -> Action -> Real) (history : History) :
    arms.sum (normalizedHistoryDistribution arms eta score history) = 1 := by
  rw [show arms.sum (normalizedHistoryDistribution arms eta score history) =
      arms.sum (historyWeight eta score history) /
        historyTotalWeight arms eta score history by
    simp only [normalizedHistoryDistribution]
    rw [Finset.sum_div]]
  rw [show arms.sum (historyWeight eta score history) =
      historyTotalWeight arms eta score history by rfl]
  exact div_self (ne_of_gt
    (historyTotalWeight_pos arms harms eta score history))

theorem exploredHistoryDistribution_nonneg
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (score : History -> Action -> Real)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (history : History) (action : Action) :
    0 <= exploredHistoryDistribution arms eta gamma score history action := by
  unfold exploredHistoryDistribution
  exact add_nonneg
    (mul_nonneg (sub_nonneg.mpr hgamma_le_one)
      (normalizedHistoryDistribution_nonneg arms harms eta score history action))
    (div_nonneg hgamma_nonneg (Nat.cast_nonneg _))

theorem sum_exploredHistoryDistribution
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (score : History -> Action -> Real)
    (history : History) :
    arms.sum (exploredHistoryDistribution arms eta gamma score history) = 1 := by
  have hcard_pos : 0 < (arms.card : Real) := by
    exact_mod_cast harms.card_pos
  unfold exploredHistoryDistribution
  rw [Finset.sum_add_distrib, ← Finset.mul_sum,
    sum_normalizedHistoryDistribution arms harms]
  simp only [Finset.sum_const, nsmul_eq_mul]
  field_simp
  ring

theorem exploredHistoryDistribution_floor
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (score : History -> Action -> Real)
    (hgamma_le_one : gamma <= 1)
    (history : History) (action : Action) :
    gamma / (arms.card : Real) <=
      exploredHistoryDistribution arms eta gamma score history action := by
  unfold exploredHistoryDistribution
  exact le_add_of_nonneg_left
    (mul_nonneg (sub_nonneg.mpr hgamma_le_one)
      (normalizedHistoryDistribution_nonneg arms harms eta score history action))

theorem explorationFloor_pos
    {Action : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (gamma : Real) (hgamma_pos : 0 < gamma) :
    0 < gamma / (arms.card : Real) := by
  exact div_pos hgamma_pos (by exact_mod_cast harms.card_pos)

theorem finiteActionDistribution_exploredHistoryDistribution
    {Action History : Type*}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real) (score : History -> Action -> Real)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (history : History) :
    FiniteActionDistribution arms
      (exploredHistoryDistribution arms eta gamma score history) where
  nonneg := fun action _ => exploredHistoryDistribution_nonneg
    arms harms eta gamma score hgamma_nonneg hgamma_le_one history action
  sum_eq_one := sum_exploredHistoryDistribution
    arms harms eta gamma score history

theorem measurable_historyWeight
    {Action History : Type*} [MeasurableSpace History]
    (eta : Real) (score : History -> Action -> Real)
    (action : Action) (hscore : Measurable (fun history => score history action)) :
    Measurable (fun history => historyWeight eta score history action) := by
  exact Real.measurable_exp.comp (measurable_const.mul hscore)

theorem measurable_historyTotalWeight
    {Action History : Type*} [MeasurableSpace History]
    (arms : Finset Action) (eta : Real)
    (score : History -> Action -> Real)
    (hscore : forall action, action ∈ arms ->
      Measurable (fun history => score history action)) :
    Measurable (historyTotalWeight arms eta score) := by
  unfold historyTotalWeight
  exact Finset.measurable_sum arms fun action haction =>
    measurable_historyWeight eta score action (hscore action haction)

theorem measurable_normalizedHistoryDistribution
    {Action History : Type*} [MeasurableSpace History]
    (arms : Finset Action) (eta : Real)
    (score : History -> Action -> Real)
    (hscore : forall action, action ∈ arms ->
      Measurable (fun history => score history action))
    (action : Action) (haction : action ∈ arms) :
    Measurable (fun history =>
      normalizedHistoryDistribution arms eta score history action) := by
  exact (measurable_historyWeight eta score action (hscore action haction)).div
    (measurable_historyTotalWeight arms eta score hscore)

theorem measurable_exploredHistoryDistribution
    {Action History : Type*} [MeasurableSpace History]
    (arms : Finset Action) (eta gamma : Real)
    (score : History -> Action -> Real)
    (hscore : forall action, action ∈ arms ->
      Measurable (fun history => score history action))
    (action : Action) (haction : action ∈ arms) :
    Measurable (fun history =>
      exploredHistoryDistribution arms eta gamma score history action) := by
  exact (measurable_const.mul
    (measurable_normalizedHistoryDistribution arms eta score hscore
      action haction)).add measurable_const

/-- Coordinate measurability for a score indexed by inclusive pair histories. -/
structure MeasurableFiniteHistoryScore
    {Action : Type u} {Loss : Type v}
    [MeasurableSpace Action] [MeasurableSpace Loss]
    (arms : Finset Action)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real) : Prop where
  measurable_score : forall n action, action ∈ arms ->
    Measurable (fun history => score n history action)

/-- The un-explored normalized exponential-weights policy supplies measurable
probability vectors on every finite-history level. -/
def normalizedHistoryDistributionSource
    {Action : Type u} {Loss : Type v}
    [MeasurableSpace Action] [MeasurableSpace Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (n : Nat) :
    MeasurableFiniteActionDistribution arms
      (normalizedHistoryDistribution arms eta (score n)) where
  distribution := fun history =>
    { nonneg := fun action _haction =>
        normalizedHistoryDistribution_nonneg arms harms eta (score n)
          history action
      sum_eq_one :=
        sum_normalizedHistoryDistribution arms harms eta (score n) history }
  measurable_prob := fun action haction =>
    measurable_normalizedHistoryDistribution arms eta (score n)
      (fun selected hselected =>
        hscore.measurable_score n selected hselected) action haction

/-- The exploration-mixed history policy supplies measurable probability vectors. -/
def exploredHistoryDistributionSource
    {Action : Type u} {Loss : Type v}
    [MeasurableSpace Action] [MeasurableSpace Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (n : Nat) :
    MeasurableFiniteActionDistribution arms
      (exploredHistoryDistribution arms eta gamma (score n)) where
  distribution := fun history =>
    finiteActionDistribution_exploredHistoryDistribution arms harms eta gamma
      (score n) hgamma_nonneg hgamma_le_one history
  measurable_prob := fun action haction =>
    measurable_exploredHistoryDistribution arms eta gamma (score n)
      (fun selected hselected =>
        hscore.measurable_score n selected hselected) action haction

/-- Initial EXP3 probabilities, obtained from zero cumulative scores. -/
noncomputable def initialExploredDistribution {Action : Type u}
    (arms : Finset Action) (eta gamma : Real) : Action -> Real :=
  exploredHistoryDistribution arms eta gamma
    (fun _ : Unit => fun _ => 0) ()

theorem finiteActionDistribution_initialExploredDistribution
    {Action : Type u}
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1) :
    FiniteActionDistribution arms
      (initialExploredDistribution arms eta gamma) := by
  exact finiteActionDistribution_exploredHistoryDistribution arms harms
    eta gamma (fun _ : Unit => fun _ => 0) hgamma_nonneg hgamma_le_one ()

/-- Stochastic finite-history algorithm generated by the EXP3 score policy. -/
noncomputable def exploredHistoryAlgorithm
    {Action : Type u} {Loss : Type v}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [MeasurableSpace Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1) :
    Thompson.HistoryAlgorithm Action Loss where
  policy n := finiteActionKernel arms
    (exploredHistoryDistribution arms eta gamma (score n))
    (exploredHistoryDistributionSource arms harms eta gamma score hscore
      hgamma_nonneg hgamma_le_one n)
  policy_isMarkov n := instFiniteActionKernelIsMarkovKernel
    arms (exploredHistoryDistribution arms eta gamma (score n))
      (exploredHistoryDistributionSource arms harms eta gamma score hscore
        hgamma_nonneg hgamma_le_one n)
  initialAction := finiteActionMeasure arms
    (initialExploredDistribution arms eta gamma)
  initialAction_isProbability := finiteActionMeasure_isProbabilityMeasure arms
    (initialExploredDistribution arms eta gamma)
    (finiteActionDistribution_initialExploredDistribution arms harms eta gamma
      hgamma_nonneg hgamma_le_one)

@[simp]
theorem exploredHistoryAlgorithm_policy
    {Action : Type u} {Loss : Type v}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [MeasurableSpace Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (n : Nat) :
    (exploredHistoryAlgorithm arms harms eta gamma score hscore
      hgamma_nonneg hgamma_le_one).policy n =
      finiteActionKernel arms
        (exploredHistoryDistribution arms eta gamma (score n))
        (exploredHistoryDistributionSource arms harms eta gamma score hscore
          hgamma_nonneg hgamma_le_one n) :=
  rfl

/-- Complete environment-indexed recursive EXP3 action/loss trajectory kernel. -/
noncomputable def exploredTrajectoryKernel
    {Env : Type w} {Action : Type u} {Loss : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [MeasurableSpace Loss] [Nonempty Action] [Nonempty Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Loss) :
    Kernel Env ((n : Nat) -> Action × Loss) :=
  Thompson.canonicalMeasurableEnvironmentTrajectoryKernel
    (exploredHistoryAlgorithm arms harms eta gamma score hscore
      hgamma_nonneg hgamma_le_one) environment

instance instExploredTrajectoryKernelIsMarkov
    {Env : Type w} {Action : Type u} {Loss : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [MeasurableSpace Loss] [Nonempty Action] [Nonempty Loss]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Loss) :
    IsMarkovKernel
      (exploredTrajectoryKernel arms harms eta gamma score hscore
        hgamma_nonneg hgamma_le_one environment) := by
  unfold exploredTrajectoryKernel
  infer_instance

/--
Every successor action of the recursive trajectory has the explicit
exploration-mixed EXP3 policy as its conditional law given the finite history.
-/
theorem exploredTrajectoryMeasure_condDistrib_action
    {Env : Type w} {Action : Type u} {Loss : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action]
    [MeasurableSpace Loss] [StandardBorelSpace Loss] [Nonempty Loss]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta gamma : Real)
    (score : (n : Nat) -> History.FinitePairHistory Action Loss n ->
      Action -> Real)
    (hscore : MeasurableFiniteHistoryScore arms score)
    (hgamma_nonneg : 0 <= gamma) (hgamma_le_one : gamma <= 1)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Loss)
    (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Loss) =>
          (sample.2 (n + 1)).1)
        (fun sample => Preorder.frestrictLe n sample.2)
        (prior ⊗ₘ exploredTrajectoryKernel arms harms eta gamma score hscore
          hgamma_nonneg hgamma_le_one environment) =ᵐ[
      (prior ⊗ₘ exploredTrajectoryKernel arms harms eta gamma score hscore
        hgamma_nonneg hgamma_le_one environment).map
          (fun sample => Preorder.frestrictLe n sample.2)]
      finiteActionKernel arms
        (exploredHistoryDistribution arms eta gamma (score n))
        (exploredHistoryDistributionSource arms harms eta gamma score hscore
          hgamma_nonneg hgamma_le_one n) := by
  simpa [exploredTrajectoryKernel, exploredHistoryAlgorithm_policy] using
    (Thompson.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action
      prior
      (exploredHistoryAlgorithm arms harms eta gamma score hscore
        hgamma_nonneg hgamma_le_one)
      environment n)

end Exp3
end BanditRLProof
