import BanditRLProof.Exp3ConditionalMoments

/-!
# A generated one-round EXP3 action process

This module constructs a history-adaptive finite-action Markov kernel from
measurable probability coordinates.  Its canonical sample measure is the
history law composed with that kernel, so the sampled action has the requested
conditional distribution by Mathlib's `condDistrib`/`compProd` uniqueness
theorem.  The final wrappers discharge the law premises of the one-round EXP3
importance-weighted moment transport.
-/

namespace BanditRLProof
namespace Exp3

open MeasureTheory ProbabilityTheory

universe u v

/-- Pointwise probability-vector and coordinate-measurability contracts. -/
structure MeasurableFiniteActionDistribution
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] (arms : Finset Action)
    (prob : History -> Action -> Real) : Prop where
  distribution : forall history, FiniteActionDistribution arms (prob history)
  measurable_prob : forall action, action ∈ arms ->
    Measurable (fun history => prob history action)

/-- The history-adaptive finite action kernel generated by `prob`. -/
noncomputable def finiteActionKernel
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    Kernel History Action where
  toFun history := finiteActionMeasure arms (prob history)
  measurable' := by
    refine Measure.measurable_of_measurable_coe _ fun event hevent => ?_
    simp only [finiteActionMeasure, Measure.finset_sum_apply,
      Measure.smul_apply, smul_eq_mul, Measure.dirac_apply' _ hevent]
    refine Finset.measurable_sum arms fun action haction => ?_
    exact (ENNReal.measurable_ofReal.comp
      (source.measurable_prob action haction)).mul measurable_const

@[simp]
theorem finiteActionKernel_apply
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob)
    (history : History) :
    finiteActionKernel arms prob source history =
      finiteActionMeasure arms (prob history) :=
  rfl

instance instFiniteActionKernelIsMarkovKernel
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    IsMarkovKernel (finiteActionKernel arms prob source) where
  isProbabilityMeasure history := by
    rw [finiteActionKernel_apply]
    exact finiteActionMeasure_isProbabilityMeasure
      arms (prob history) (source.distribution history)

/-- Canonical joint history/action law generated by the adaptive policy. -/
noncomputable def actionProcessMeasure
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    Measure (History × Action) :=
  historyMu ⊗ₘ finiteActionKernel arms prob source

instance instActionProcessMeasureIsFiniteMeasure
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    IsFiniteMeasure (actionProcessMeasure historyMu arms prob source) := by
  unfold actionProcessMeasure
  infer_instance

instance instActionProcessMeasureIsProbabilityMeasure
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (historyMu : Measure History) [IsProbabilityMeasure historyMu]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    IsProbabilityMeasure (actionProcessMeasure historyMu arms prob source) := by
  unfold actionProcessMeasure
  infer_instance

/-- History coordinate of the generated one-round process. -/
def actionProcessHistory {History Action : Type*} : History × Action -> History :=
  Prod.fst

/-- Sampled action coordinate of the generated one-round process. -/
def actionProcessAction {History Action : Type*} : History × Action -> Action :=
  Prod.snd

theorem actionProcessHistory_measurable
    {History Action : Type*}
    [MeasurableSpace History] [MeasurableSpace Action] :
    Measurable (@actionProcessHistory History Action) :=
  measurable_fst

theorem actionProcessAction_measurable
    {History Action : Type*}
    [MeasurableSpace History] [MeasurableSpace Action] :
    Measurable (@actionProcessAction History Action) :=
  measurable_snd

/-- The generated process preserves the supplied history marginal. -/
theorem actionProcess_history_map_eq
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    (actionProcessMeasure historyMu arms prob source).map
        actionProcessHistory = historyMu := by
  change (historyMu ⊗ₘ finiteActionKernel arms prob source).fst = historyMu
  rw [Measure.fst_compProd]

/-- The sampled action has the generated policy as its a.e. conditional law. -/
theorem actionProcess_condDistrib_action_ae_eq_finiteActionKernel
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    condDistrib actionProcessAction actionProcessHistory
        (actionProcessMeasure historyMu arms prob source) =ᵐ[
      (actionProcessMeasure historyMu arms prob source).map
        actionProcessHistory]
      finiteActionKernel arms prob source := by
  apply (condDistrib_ae_eq_iff_measure_eq_compProd
    (μ := actionProcessMeasure historyMu arms prob source)
    actionProcessHistory actionProcessAction_measurable.aemeasurable
    (finiteActionKernel arms prob source)).2
  rw [actionProcess_history_map_eq]
  change (historyMu ⊗ₘ finiteActionKernel arms prob source).map id = _
  rw [Measure.map_id]

/-- The generated policy is pointwise the explicit finite Dirac action law. -/
theorem finiteActionKernel_ae_eq_finiteActionMeasure
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    (historyMu : Measure History)
    (arms : Finset Action) (prob : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob) :
    finiteActionKernel arms prob source =ᵐ[historyMu]
      fun history => finiteActionMeasure arms (prob history) := by
  filter_upwards [] with history
  exact finiteActionKernel_apply arms prob source history

/-- Canonical generated-process armwise importance-weighted identity. -/
theorem actionProcess_integral_importanceWeightedLoss_eq_integral_loss
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob)
    (hprob : forall history action, action ∈ arms -> 0 < prob history action)
    (comparator : Action) (hcomparator : comparator ∈ arms)
    (hscore : Measurable (fun z : History × Action =>
      importanceWeightedLoss (prob z.1) (loss z.1) z.2 comparator))
    (hIntegrable : Integrable (fun z : History × Action =>
      importanceWeightedLoss (prob z.1) (loss z.1) z.2 comparator)
      (historyMu ⊗ₘ finiteActionKernel arms prob source)) :
    integral (actionProcessMeasure historyMu arms prob source) (fun sample =>
        importanceWeightedLoss (prob (actionProcessHistory sample))
          (loss (actionProcessHistory sample)) (actionProcessAction sample)
          comparator) =
      integral historyMu (fun history => loss history comparator) := by
  have hhistory := actionProcess_history_map_eq historyMu arms prob source
  simpa [hhistory] using
    integral_importanceWeightedLoss_eq_integral_loss_of_condDistrib
      (actionProcessMeasure historyMu arms prob source)
      actionProcessHistory actionProcessHistory_measurable
      actionProcessAction actionProcessAction_measurable arms prob loss
      source.distribution hprob (finiteActionKernel arms prob source)
      (finiteActionKernel_ae_eq_finiteActionMeasure
        ((actionProcessMeasure historyMu arms prob source).map
          actionProcessHistory) arms prob source)
      (actionProcess_condDistrib_action_ae_eq_finiteActionKernel
        historyMu arms prob source)
      comparator hcomparator hscore (by simpa [hhistory] using hIntegrable)

/-- Canonical generated-process mixed first-moment identity. -/
theorem actionProcess_integral_mixedImportanceWeightedLoss_eq_integral_mixedLoss
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob)
    (hprob : forall history action, action ∈ arms -> 0 < prob history action)
    (hscore : Measurable (fun z : History × Action =>
      mixedImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2))
    (hIntegrable : Integrable (fun z : History × Action =>
      mixedImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2)
      (historyMu ⊗ₘ finiteActionKernel arms prob source)) :
    integral (actionProcessMeasure historyMu arms prob source) (fun sample =>
        mixedImportanceWeightedLoss arms (prob (actionProcessHistory sample))
          (loss (actionProcessHistory sample)) (actionProcessAction sample)) =
      integral historyMu (fun history =>
        arms.sum (fun action => prob history action * loss history action)) := by
  have hhistory := actionProcess_history_map_eq historyMu arms prob source
  simpa [hhistory] using
    integral_mixedImportanceWeightedLoss_eq_integral_mixedLoss_of_condDistrib
      (actionProcessMeasure historyMu arms prob source)
      actionProcessHistory actionProcessHistory_measurable
      actionProcessAction actionProcessAction_measurable arms prob loss
      source.distribution hprob (finiteActionKernel arms prob source)
      (finiteActionKernel_ae_eq_finiteActionMeasure
        ((actionProcessMeasure historyMu arms prob source).map
          actionProcessHistory) arms prob source)
      (actionProcess_condDistrib_action_ae_eq_finiteActionKernel
        historyMu arms prob source)
      hscore (by simpa [hhistory] using hIntegrable)

/-- Canonical generated-process mixed second-moment identity. -/
theorem actionProcess_integral_mixedSquaredImportanceWeightedLoss_eq_integral_sum_loss_sq
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (source : MeasurableFiniteActionDistribution arms prob)
    (hprob : forall history action, action ∈ arms -> 0 < prob history action)
    (hscore : Measurable (fun z : History × Action =>
      mixedSquaredImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2))
    (hIntegrable : Integrable (fun z : History × Action =>
      mixedSquaredImportanceWeightedLoss arms (prob z.1) (loss z.1) z.2)
      (historyMu ⊗ₘ finiteActionKernel arms prob source)) :
    integral (actionProcessMeasure historyMu arms prob source) (fun sample =>
        mixedSquaredImportanceWeightedLoss arms
          (prob (actionProcessHistory sample))
          (loss (actionProcessHistory sample)) (actionProcessAction sample)) =
      integral historyMu (fun history =>
        arms.sum (fun action => (loss history action) ^ 2)) := by
  have hhistory := actionProcess_history_map_eq historyMu arms prob source
  simpa [hhistory] using
    integral_mixedSquaredImportanceWeightedLoss_eq_integral_sum_loss_sq_of_condDistrib
      (actionProcessMeasure historyMu arms prob source)
      actionProcessHistory actionProcessHistory_measurable
      actionProcessAction actionProcessAction_measurable arms prob loss
      source.distribution hprob (finiteActionKernel arms prob source)
      (finiteActionKernel_ae_eq_finiteActionMeasure
        ((actionProcessMeasure historyMu arms prob source).map
          actionProcessHistory) arms prob source)
      (actionProcess_condDistrib_action_ae_eq_finiteActionKernel
        historyMu arms prob source)
      hscore (by simpa [hhistory] using hIntegrable)

end Exp3
end BanditRLProof
