import Mathlib.Probability.Process.Filtration
import BanditRLProof.MeasureFoundation

/-!
# History filtrations

This module gives a narrow project-local filtration canary: the sigma-algebras
generated by past action/reward singleton events form a Mathlib filtration.
It does not construct kernels, policies, conditional expectations, conditional
MGF witnesses, or adaptive regret theorems.
-/

universe u v w

namespace BanditRLProof
namespace History

open MeasureTheory

/-- Finite action histories through index `t`, represented on Mathlib's
`Finset.Iic t` finite-prefix index type. -/
abbrev FiniteActionHistory (Action : Type v) (t : Nat) :=
  (i : Finset.Iic t) -> Action

/-- Finite reward histories through index `t`, represented on Mathlib's
`Finset.Iic t` finite-prefix index type. -/
abbrev FiniteRewardHistory (Reward : Type w) (t : Nat) :=
  (i : Finset.Iic t) -> Reward

/-- Pair-coordinate finite action/reward histories through index `t`. -/
abbrev FinitePairHistory (Action : Type v) (Reward : Type w) (t : Nat) :=
  (i : Finset.Iic t) -> Prod Action Reward

/-- The paired finite action/reward history object at a finite prefix. -/
abbrev FiniteHistory (Action : Type v) (Reward : Type w) (t : Nat) :=
  FiniteActionHistory Action t × FiniteRewardHistory Reward t

/-- Restrict an infinite action trace to the finite prefix indexed by
`Finset.Iic t`. -/
def finiteActionHistoryOfTrace
    {Action : Type v}
    (action : ActionTrace Action) (t : Nat) :
    FiniteActionHistory Action t :=
  fun i => action i.1

/-- Restrict an infinite reward trace to the finite prefix indexed by
`Finset.Iic t`. -/
def finiteRewardHistoryOfTrace
    {Reward : Type w}
    (reward : RewardTrace Reward) (t : Nat) :
    FiniteRewardHistory Reward t :=
  fun i => reward i.1

/--
Complete a finite reward history to an infinite trace, using `default` outside
the observed prefix.

The completion agrees with `history` at every coordinate through `t`.  It is a
deterministic history-reconstruction helper; it does not assert that the
defaulted future coordinates agree with an ambient reward process.
-/
def completeRewardTrace
    {Reward : Type w}
    (t : Nat) (history : FiniteRewardHistory Reward t) (default : Reward) :
    RewardTrace Reward :=
  fun s => if h : s <= t then history ⟨s, Finset.mem_Iic.mpr h⟩ else default

/-- Restrict infinite action and reward traces to a paired finite history. -/
def finiteHistoryOfTrace
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    FiniteHistory Action Reward t :=
  (finiteActionHistoryOfTrace action t, finiteRewardHistoryOfTrace reward t)

/-- Restrict infinite action and reward traces to pair-coordinate history. -/
def finitePairHistoryOfTrace
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    FinitePairHistory Action Reward t :=
  fun i => (action i.1, reward i.1)

/-- Extend a finite pair history from `t` to `t + 1` by appending the next pair. -/
def extendPairHistorySucc
    {Action : Type v} {Reward : Type w} {t : Nat}
    (history : FinitePairHistory Action Reward t)
    (next : Prod Action Reward) :
    FinitePairHistory Action Reward (t + 1) :=
  fun i =>
    if h : i.1 <= t then
      history ⟨i.1, Finset.mem_Iic.mpr h⟩
    else
      next

@[simp]
theorem finiteActionHistoryOfTrace_apply
    {Action : Type v}
    (action : ActionTrace Action) (t : Nat) (i : Finset.Iic t) :
    finiteActionHistoryOfTrace action t i = action i.1 := rfl

@[simp]
theorem finiteRewardHistoryOfTrace_apply
    {Reward : Type w}
    (reward : RewardTrace Reward) (t : Nat) (i : Finset.Iic t) :
    finiteRewardHistoryOfTrace reward t i = reward i.1 := rfl

/--
Completing the actual finite reward prefix recovers every original coordinate
through that prefix.
-/
@[simp]
theorem completeRewardTrace_finiteRewardHistoryOfTrace_apply_of_le
    {Reward : Type w}
    (reward : RewardTrace Reward) (t s : Nat) (default : Reward)
    (hs : s <= t) :
    completeRewardTrace t (finiteRewardHistoryOfTrace reward t) default s =
      reward s := by
  simp [completeRewardTrace, hs, finiteRewardHistoryOfTrace]

@[simp]
theorem finiteHistoryOfTrace_fst
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    (finiteHistoryOfTrace action reward t).1 =
      finiteActionHistoryOfTrace action t := rfl

@[simp]
theorem finiteHistoryOfTrace_snd
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    (finiteHistoryOfTrace action reward t).2 =
      finiteRewardHistoryOfTrace reward t := rfl

@[simp]
theorem finitePairHistoryOfTrace_apply
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) (i : Finset.Iic t) :
    finitePairHistoryOfTrace action reward t i =
      (action i.1, reward i.1) := rfl

@[simp]
theorem extendPairHistorySucc_apply_of_le
    {Action : Type v} {Reward : Type w} {t : Nat}
    (history : FinitePairHistory Action Reward t)
    (next : Prod Action Reward)
    (i : Finset.Iic (t + 1)) (hi : i.1 <= t) :
    extendPairHistorySucc history next i =
      history ⟨i.1, Finset.mem_Iic.mpr hi⟩ := by
  simp [extendPairHistorySucc, hi]

@[simp]
theorem extendPairHistorySucc_apply_succ
    {Action : Type v} {Reward : Type w} {t : Nat}
    (history : FinitePairHistory Action Reward t)
    (next : Prod Action Reward) :
    extendPairHistorySucc history next
        ⟨t + 1, Finset.mem_Iic.mpr le_rfl⟩ =
      next := by
  simp [extendPairHistorySucc]

/--
The trace prefix at `t + 1` is the old pair prefix extended by the next
action/reward pair.
-/
@[simp]
theorem finitePairHistoryOfTrace_succ
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    finitePairHistoryOfTrace action reward (t + 1) =
      extendPairHistorySucc
        (finitePairHistoryOfTrace action reward t)
        (action (t + 1), reward (t + 1)) := by
  funext i
  by_cases hi : i.1 <= t
  · simp [extendPairHistorySucc, hi]
  · have hi_le : i.1 <= t + 1 := Finset.mem_Iic.mp i.2
    have h_succ_le : t + 1 <= i.1 := Nat.succ_le_of_lt (lt_of_not_ge hi)
    have hi_eq : i.1 = t + 1 := le_antisymm hi_le h_succ_le
    simp [extendPairHistorySucc, hi_eq]

/-- Project the reward coordinates from a prefix of `(Action, Reward)` pairs. -/
def pairHistoryRewardProjection
    {Action : Type v} {Reward : Type w} {t : Nat}
    (history : (i : Finset.Iic t) -> Prod Action Reward) :
    FiniteRewardHistory Reward t :=
  fun i => (history i).2

@[simp]
theorem pairHistoryRewardProjection_apply
    {Action : Type v} {Reward : Type w} {t : Nat}
    (history : (i : Finset.Iic t) -> Prod Action Reward)
    (i : Finset.Iic t) :
    pairHistoryRewardProjection history i = (history i).2 := rfl

@[simp]
theorem pairHistoryRewardProjection_finitePairHistoryOfTrace
    {Action : Type v} {Reward : Type w}
    (action : ActionTrace Action)
    (reward : RewardTrace Reward)
    (t : Nat) :
    pairHistoryRewardProjection
        (finitePairHistoryOfTrace action reward t) =
      finiteRewardHistoryOfTrace reward t := rfl

/-- Coordinate evaluation on finite action histories is measurable. -/
theorem measurable_finiteActionHistory_eval
    {Action : Type v} [MeasurableSpace Action]
    (t : Nat) (i : Finset.Iic t) :
    Measurable (fun history : FiniteActionHistory Action t => history i) :=
  measurable_pi_apply i

/-- Coordinate evaluation on finite reward histories is measurable. -/
theorem measurable_finiteRewardHistory_eval
    {Reward : Type w} [MeasurableSpace Reward]
    (t : Nat) (i : Finset.Iic t) :
    Measurable (fun history : FiniteRewardHistory Reward t => history i) :=
  measurable_pi_apply i

/-- Action-coordinate evaluation on paired finite histories is measurable. -/
theorem measurable_finiteHistory_action_eval
    {Action : Type v} {Reward : Type w}
    [MeasurableSpace Action] [MeasurableSpace Reward]
    (t : Nat) (i : Finset.Iic t) :
    Measurable
      (fun history : FiniteHistory Action Reward t => history.1 i) :=
  (measurable_finiteActionHistory_eval (Action := Action) t i).comp
    measurable_fst

/-- Reward-coordinate evaluation on paired finite histories is measurable. -/
theorem measurable_finiteHistory_reward_eval
    {Action : Type v} {Reward : Type w}
    [MeasurableSpace Action] [MeasurableSpace Reward]
    (t : Nat) (i : Finset.Iic t) :
    Measurable
      (fun history : FiniteHistory Action Reward t => history.2 i) :=
  (measurable_finiteRewardHistory_eval (Reward := Reward) t i).comp
    measurable_snd

/-- The reward projection from pair-coordinate histories is measurable. -/
theorem measurable_pairHistoryRewardProjection
    {Action : Type v} {Reward : Type w}
    [MeasurableSpace Action] [MeasurableSpace Reward]
    (t : Nat) :
    Measurable
      (fun history : (i : Finset.Iic t) -> Prod Action Reward =>
        pairHistoryRewardProjection history) := by
  exact
    measurable_pi_lambda _
      (fun i : Finset.Iic t => measurable_snd.comp (measurable_pi_apply i))

/--
Timewise measurable action and reward traces restrict to a measurable
pair-coordinate finite history object.
-/
theorem measurable_finitePairHistoryOfTrace
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [MeasurableSpace Omega]
    [MeasurableSpace Action] [MeasurableSpace Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    Measurable
      (fun omega : Omega =>
        finitePairHistoryOfTrace (action omega) (reward omega) t) := by
  exact
    measurable_pi_lambda _
      (fun i : Finset.Iic t => (haction i.1).prod (hreward i.1))

/-- The successor-extension map for pair histories is measurable. -/
theorem measurable_extendPairHistorySucc
    {Action : Type v} {Reward : Type w} {t : Nat}
    [MeasurableSpace Action] [MeasurableSpace Reward] :
    Measurable
      (fun input :
          Prod (FinitePairHistory Action Reward t) (Prod Action Reward) =>
        extendPairHistorySucc input.1 input.2) := by
  refine measurable_pi_lambda _ ?_
  intro i
  by_cases hi : i.1 <= t
  · let oldIndex : Finset.Iic t := ⟨i.1, Finset.mem_Iic.mpr hi⟩
    have h_old :
        Measurable
          (fun input :
              Prod (FinitePairHistory Action Reward t) (Prod Action Reward) =>
            input.1 oldIndex) := by
      exact (measurable_pi_apply oldIndex).comp measurable_fst
    simpa [extendPairHistorySucc, hi, oldIndex] using h_old
  · simpa [extendPairHistorySucc, hi] using
      measurable_snd

/--
Timewise measurable action traces restrict to measurable finite action-history
objects.
-/
theorem measurable_finiteActionHistoryOfTrace
    {Omega : Type u} {Action : Type v}
    [MeasurableSpace Omega] [MeasurableSpace Action]
    (action : Omega -> ActionTrace Action)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (t : Nat) :
    Measurable
      (fun omega : Omega =>
        finiteActionHistoryOfTrace (action omega) t) := by
  exact measurable_pi_lambda _ (fun i : Finset.Iic t => haction i.1)

/--
Timewise measurable reward traces restrict to measurable finite reward-history
objects.
-/
theorem measurable_finiteRewardHistoryOfTrace
    {Omega : Type u} {Reward : Type w}
    [MeasurableSpace Omega] [MeasurableSpace Reward]
    (reward : Omega -> RewardTrace Reward)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    Measurable
      (fun omega : Omega =>
        finiteRewardHistoryOfTrace (reward omega) t) := by
  exact measurable_pi_lambda _ (fun i : Finset.Iic t => hreward i.1)

/--
Timewise measurable action and reward traces restrict to a measurable paired
finite history object.
-/
theorem measurable_finiteHistoryOfTrace
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [MeasurableSpace Omega]
    [MeasurableSpace Action] [MeasurableSpace Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    Measurable
      (fun omega : Omega =>
        finiteHistoryOfTrace (action omega) (reward omega) t) := by
  exact
    (measurable_finiteActionHistoryOfTrace action haction t).prod
      (measurable_finiteRewardHistoryOfTrace reward hreward t)

/--
The singleton-valued action/reward events visible before time `t`.

This is deliberately discrete: it is shaped for finite arms and discrete local
reward traces such as `Rat`, where singleton events are the current compiled
measurability surface.
-/
def historyGenerators
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (t : Nat) : Set (Set Omega) :=
  Set.union
    {s | Exists (fun i => And (i < t)
      (Exists (fun a =>
        s = Set.preimage (fun omega => action omega i) (Set.singleton a))))}
    {s | Exists (fun i => And (i < t)
      (Exists (fun r =>
        s = Set.preimage (fun omega => reward omega i) (Set.singleton r))))}

/-- Past history generators are monotone in the horizon. -/
theorem historyGenerators_mono
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    {t u : Nat} (htu : t <= u) :
    Set.Subset (historyGenerators action reward t)
      (historyGenerators action reward u) := by
  intro s hs
  rcases hs with hs | hs
  · cases hs with
    | intro i hi =>
      cases hi with
      | intro hit hrest =>
        cases hrest with
        | intro a hs_eq =>
          exact Or.inl
            (Exists.intro i
              (And.intro (lt_of_lt_of_le hit htu)
                (Exists.intro a hs_eq)))
  · cases hs with
    | intro i hi =>
      cases hi with
      | intro hit hrest =>
        cases hrest with
        | intro r hs_eq =>
          exact Or.inr
            (Exists.intro i
              (And.intro (lt_of_lt_of_le hit htu)
                (Exists.intro r hs_eq)))

/-- The sigma-algebra generated by past action/reward singleton events. -/
@[reducible]
def historyMeasurableSpace
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (t : Nat) : MeasurableSpace Omega :=
  MeasurableSpace.generateFrom (historyGenerators action reward t)

/-- The history sigma-algebras are monotone. -/
theorem historyMeasurableSpace_mono
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    {t u : Nat} (htu : t <= u) :
    historyMeasurableSpace action reward t <=
      historyMeasurableSpace action reward u := by
  exact MeasurableSpace.generateFrom_mono
    (historyGenerators_mono action reward htu)

/--
The generated history sigma-algebra is a sub-sigma-algebra of the ambient
measurable space when action and reward coordinates are timewise measurable.
-/
theorem historyMeasurableSpace_le
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    historyMeasurableSpace action reward t <=
      (inferInstance : MeasurableSpace Omega) := by
  refine MeasurableSpace.generateFrom_le ?_
  intro s hs
  rcases hs with hs | hs
  · cases hs with
    | intro i hi =>
      cases hi with
      | intro _hit hrest =>
        cases hrest with
        | intro a hs_eq =>
          rw [hs_eq]
          exact (haction i) (MeasurableSet.singleton a)
  · cases hs with
    | intro i hi =>
      cases hi with
      | intro _hit hrest =>
        cases hrest with
        | intro r hs_eq =>
          rw [hs_eq]
          exact (hreward i) (MeasurableSet.singleton r)

/--
The local history filtration generated by past action/reward singleton events.

This is the compiled `FILTRATION-HISTORY` canary.  It is intentionally only a
filtration construction, not a policy/predictability or conditional-expectation
theorem.
-/
def historyFiltration
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t)) :
    Filtration Nat mOmega where
  seq t := historyMeasurableSpace action reward t
  mono' := fun _ _ htu => historyMeasurableSpace_mono action reward htu
  le' := historyMeasurableSpace_le action reward haction hreward

@[simp]
theorem historyFiltration_apply
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    (historyFiltration action reward haction hreward t :
      MeasurableSpace Omega) =
      historyMeasurableSpace action reward t := rfl

/--
The one-step shifted history filtration.

`historyFiltration` at index `t` contains observations with index `< t`.
For adapted reward increments it is often more convenient to index the
filtration by observations available after time `t`, i.e. `< t + 1`.
-/
def historyFiltrationSucc
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t)) :
    Filtration Nat mOmega where
  seq t := historyFiltration action reward haction hreward (t + 1)
  mono' := fun _ _ htu =>
    (historyFiltration action reward haction hreward).mono
      (Nat.succ_le_succ htu)
  le' := fun t =>
    (historyFiltration action reward haction hreward).le (t + 1)

@[simp]
theorem historyFiltrationSucc_apply
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (t : Nat) :
    (historyFiltrationSucc action reward haction hreward t :
      MeasurableSpace Omega) =
      historyFiltration action reward haction hreward (t + 1) := rfl

/-- Past action singleton events are measurable in the generated history. -/
theorem measurableSet_action_mem_historyFiltration
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    {i t : Nat} (hit : i < t) (a : Action) :
    MeasurableSet[historyFiltration action reward haction hreward t]
      (Set.preimage (fun omega => action omega i) (Set.singleton a)) := by
  rw [historyFiltration_apply]
  exact MeasurableSpace.measurableSet_generateFrom
    (Or.inl
      (Exists.intro i
        (And.intro hit (Exists.intro a rfl))))

/--
Past action coordinates are measurable with respect to the generated history.

This is a deliberately discrete `ADAPTED-ACTION` canary: it uses countability
and singleton-event measurability, not a full policy-predictability contract.
-/
theorem measurable_action_mem_historyFiltration_of_lt
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action] [Countable Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    {i t : Nat} (hit : i < t) :
    @Measurable Omega Action
      (historyFiltration action reward haction hreward t)
      inferInstance
      (fun omega => action omega i) := by
  exact @measurable_to_countable' Action Omega inferInstance inferInstance
    (historyFiltration action reward haction hreward t)
    (f := fun omega => action omega i)
    (fun a : Action =>
      measurableSet_action_mem_historyFiltration
        action reward haction hreward hit a)

/-- Past reward singleton events are measurable in the generated history. -/
theorem measurableSet_reward_mem_historyFiltration
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    {i t : Nat} (hit : i < t) (r : Reward) :
    MeasurableSet[historyFiltration action reward haction hreward t]
      (Set.preimage (fun omega => reward omega i) (Set.singleton r)) := by
  rw [historyFiltration_apply]
  exact MeasurableSpace.measurableSet_generateFrom
    (Or.inr
      (Exists.intro i
        (And.intro hit (Exists.intro r rfl))))

/--
Past reward coordinates are measurable with respect to the generated history.

This is the reward-side companion canary for the local history filtration; it
still does not instantiate conditional reward laws or martingale differences.
-/
theorem measurable_reward_mem_historyFiltration_of_lt
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    [Countable Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    {i t : Nat} (hit : i < t) :
    @Measurable Omega Reward
      (historyFiltration action reward haction hreward t)
      inferInstance
      (fun omega => reward omega i) := by
  exact @measurable_to_countable' Reward Omega inferInstance inferInstance
    (historyFiltration action reward haction hreward t)
    (f := fun omega => reward omega i)
    (fun r : Reward =>
      measurableSet_reward_mem_historyFiltration
        action reward haction hreward hit r)

/--
Finite pair histories up to `n` are measurable with respect to any generated
history filtration level strictly after `n`.

This is the product-valued counterpart of the coordinate measurability canaries
above.  It is intentionally countable/discrete, matching the singleton-event
definition of `historyMeasurableSpace`.
-/
theorem measurable_finitePairHistoryOfTrace_mem_historyFiltration_of_lt
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action] [Countable Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    [Countable Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    {n t : Nat} (hnt : n < t) :
    @Measurable Omega ((i : Finset.Iic n) -> Prod Action Reward)
      (historyFiltration (mOmega := mOmega) action reward haction hreward t)
      inferInstance
      (fun omega : Omega =>
        finitePairHistoryOfTrace (action omega) (reward omega) n) := by
  letI : MeasurableSpace Omega :=
    historyFiltration (mOmega := mOmega) action reward haction hreward t
  change Measurable
    (fun omega : Omega =>
      finitePairHistoryOfTrace (action omega) (reward omega) n)
  refine measurable_pi_lambda _ ?_
  intro i
  have hit : i.1 < t := lt_of_le_of_lt (Finset.mem_Iic.mp i.2) hnt
  have h_action :
      Measurable (fun omega : Omega => action omega i.1) := by
    change @Measurable Omega Action
      (historyFiltration (mOmega := mOmega) action reward haction hreward t)
      inferInstance
      (fun omega : Omega => action omega i.1)
    exact
      measurable_action_mem_historyFiltration_of_lt
        (mOmega := mOmega) action reward haction hreward hit
  have h_reward :
      Measurable (fun omega : Omega => reward omega i.1) := by
    change @Measurable Omega Reward
      (historyFiltration (mOmega := mOmega) action reward haction hreward t)
      inferInstance
      (fun omega : Omega => reward omega i.1)
    exact
      measurable_reward_mem_historyFiltration_of_lt
        (mOmega := mOmega) action reward haction hreward hit
  simpa [finitePairHistoryOfTrace] using h_action.prod h_reward

/--
The generated history filtration after observing indices `<= n` is exactly the
comap of the finite pair-history restriction map.

The forward inclusion follows from the singleton generators.  The reverse
inclusion follows from the previous product-valued measurability wrapper.
This equality is a local bridge between the hand-rolled history filtration and
Mathlib conditional-distribution statements conditioned on finite prefixes.
-/
theorem historyFiltration_succ_eq_comap_finitePairHistoryOfTrace
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action] [Countable Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    [Countable Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (n : Nat) :
    (historyFiltration action reward haction hreward (n + 1) :
        MeasurableSpace Omega) =
      (inferInstance :
        MeasurableSpace ((i : Finset.Iic n) -> Prod Action Reward)).comap
        (fun omega : Omega =>
          finitePairHistoryOfTrace (action omega) (reward omega) n) := by
  apply le_antisymm
  · rw [historyFiltration_apply]
    refine MeasurableSpace.generateFrom_le ?_
    intro s hs
    rcases hs with hs | hs
    · rcases hs with ⟨i, hi, a, hs_eq⟩
      rw [hs_eq]
      have hin : i <= n := Nat.lt_succ_iff.mp hi
      let j : Finset.Iic n := ⟨i, Finset.mem_Iic.mpr hin⟩
      have hcoord :
          @Measurable Omega Action
            ((inferInstance :
              MeasurableSpace
                ((k : Finset.Iic n) -> Prod Action Reward)).comap
              (fun omega : Omega =>
                finitePairHistoryOfTrace (action omega) (reward omega) n))
            inferInstance
            (fun omega : Omega => action omega i) := by
        have hbase :
            Measurable
              (fun history :
                  (k : Finset.Iic n) -> Prod Action Reward =>
                (history j).1) :=
          measurable_fst.comp (measurable_pi_apply j)
        have hprefix :
            @Measurable Omega
              ((k : Finset.Iic n) -> Prod Action Reward)
              ((inferInstance :
                MeasurableSpace
                  ((k : Finset.Iic n) -> Prod Action Reward)).comap
                (fun omega : Omega =>
                  finitePairHistoryOfTrace (action omega) (reward omega) n))
              inferInstance
              (fun omega : Omega =>
                finitePairHistoryOfTrace (action omega) (reward omega) n) :=
          Measurable.of_comap_le le_rfl
        simpa [finitePairHistoryOfTrace, j] using hbase.comp hprefix
      exact hcoord (MeasurableSet.singleton a)
    · rcases hs with ⟨i, hi, r, hs_eq⟩
      rw [hs_eq]
      have hin : i <= n := Nat.lt_succ_iff.mp hi
      let j : Finset.Iic n := ⟨i, Finset.mem_Iic.mpr hin⟩
      have hcoord :
          @Measurable Omega Reward
            ((inferInstance :
              MeasurableSpace
                ((k : Finset.Iic n) -> Prod Action Reward)).comap
              (fun omega : Omega =>
                finitePairHistoryOfTrace (action omega) (reward omega) n))
            inferInstance
            (fun omega : Omega => reward omega i) := by
        have hbase :
            Measurable
              (fun history :
                  (k : Finset.Iic n) -> Prod Action Reward =>
                (history j).2) :=
          measurable_snd.comp (measurable_pi_apply j)
        have hprefix :
            @Measurable Omega
              ((k : Finset.Iic n) -> Prod Action Reward)
              ((inferInstance :
                MeasurableSpace
                  ((k : Finset.Iic n) -> Prod Action Reward)).comap
                (fun omega : Omega =>
                  finitePairHistoryOfTrace (action omega) (reward omega) n))
              inferInstance
              (fun omega : Omega =>
                finitePairHistoryOfTrace (action omega) (reward omega) n) :=
          Measurable.of_comap_le le_rfl
        simpa [finitePairHistoryOfTrace, j] using hbase.comp hprefix
      exact hcoord (MeasurableSet.singleton r)
  · exact
      Measurable.comap_le
        (measurable_finitePairHistoryOfTrace_mem_historyFiltration_of_lt
          (mOmega := mOmega) action reward haction hreward
          (Nat.lt_succ_self n))

/--
The shifted generated-history filtration at time `n` is exactly the comap of
the finite pair-history restriction through index `n`.

This is the `historyFiltrationSucc`-indexed form used by the conditional-kernel
source contracts.
-/
theorem historyFiltrationSucc_eq_comap_finitePairHistoryOfTrace
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Action]
    [MeasurableSingletonClass Action] [Countable Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward]
    [Countable Reward]
    (action : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction : forall t : Nat,
      Measurable (fun omega : Omega => action omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (n : Nat) :
    (historyFiltrationSucc action reward haction hreward n :
        MeasurableSpace Omega) =
      (inferInstance :
        MeasurableSpace ((i : Finset.Iic n) -> Prod Action Reward)).comap
        (fun omega : Omega =>
          finitePairHistoryOfTrace (action omega) (reward omega) n) := by
  simpa [historyFiltrationSucc_apply] using
    historyFiltration_succ_eq_comap_finitePairHistoryOfTrace
      (mOmega := mOmega) action reward haction hreward n

/--
Two shifted history filtrations agree at time `n` when their action traces
agree pointwise through `n` and they use the same reward trace.

The proof passes through the finite-pair-history comap characterization. It is
useful when an adaptive policy has a deterministic exploration prefix.
-/
theorem historyFiltrationSucc_eq_of_action_eq_on_prefix
    {Omega : Type u} {Action : Type v} {Reward : Type w}
    [mOmega : MeasurableSpace Omega]
    [MeasurableSpace Action] [MeasurableSingletonClass Action] [Countable Action]
    [MeasurableSpace Reward] [MeasurableSingletonClass Reward] [Countable Reward]
    (action0 action1 : Omega -> ActionTrace Action)
    (reward : Omega -> RewardTrace Reward)
    (haction0 : forall t : Nat,
      Measurable (fun omega : Omega => action0 omega t))
    (haction1 : forall t : Nat,
      Measurable (fun omega : Omega => action1 omega t))
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (n : Nat)
    (haction_eq : forall omega i, i <= n -> action0 omega i = action1 omega i) :
    (historyFiltrationSucc action0 reward haction0 hreward n :
        MeasurableSpace Omega) =
      (historyFiltrationSucc action1 reward haction1 hreward n :
        MeasurableSpace Omega) := by
  rw [historyFiltrationSucc_eq_comap_finitePairHistoryOfTrace,
    historyFiltrationSucc_eq_comap_finitePairHistoryOfTrace]
  congr 1
  funext omega i
  simp only [finitePairHistoryOfTrace_apply]
  rw [haction_eq omega i.1 (Finset.mem_Iic.mp i.2)]

end History
end BanditRLProof
