import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Ring

/-!
# OFUL elliptical-potential linear algebra wrappers

This module records the first deterministic finite-dimensional linear-algebra
surface needed by OFUL/LinUCB routes.  It packages rank-one feature Gram
matrices and finite-history Gram matrices, then proves their quadratic forms
are squares or sums of squares.

It does not prove a matrix determinant lemma, log-determinant telescoping,
self-normalized concentration, confidence ellipsoids, or an OFUL regret
theorem.
-/

namespace BanditRLProof
namespace OFUL

universe u v

/-- Rank-one Gram matrix generated by one feature vector. -/
def rankOneGram {Feature : Type u}
    (x : Feature -> Real) : Matrix Feature Feature Real :=
  fun i j => x i * x j

/-- Quadratic form associated with a finite real matrix. -/
noncomputable def quadraticForm {Feature : Type u} [Fintype Feature]
    (A : Matrix Feature Feature Real) (y : Feature -> Real) : Real :=
  (Finset.univ : Finset Feature).sum
    (fun i => (Finset.univ : Finset Feature).sum
      (fun j => y i * A i j * y j))

/-- Finite-history feature Gram matrix `sum_t x_t x_t^T`. -/
noncomputable def featureGram {Time : Type v} {Feature : Type u}
    [Fintype Time] (x : Time -> Feature -> Real) :
    Matrix Feature Feature Real :=
  fun i j => (Finset.univ : Finset Time).sum
    (fun t => x t i * x t j)

/--
The quadratic form of a rank-one Gram matrix is the square of the projection
of the query vector onto the feature vector.
-/
theorem rankOneGram_quadraticForm_eq_sq
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    quadraticForm (rankOneGram x) y =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
  unfold quadraticForm rankOneGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * (x i * x j) * y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (y i * x i) * (x j * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (y i * x i) *
          (Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.mul_sum]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      rw [Finset.sum_mul]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      have hleft :
          ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) =
            ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) := by
        apply Finset.sum_congr rfl
        intro i _hi
        ring
      rw [hleft]
    _ = ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
      ring

/-- Rank-one Gram matrices have nonnegative quadratic forms. -/
theorem rankOneGram_quadraticForm_nonneg
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    0 <= quadraticForm (rankOneGram x) y := by
  rw [rankOneGram_quadraticForm_eq_sq]
  exact sq_nonneg _

/--
The quadratic form of a finite-history Gram matrix is a finite sum of squared
feature projections.
-/
theorem featureGram_quadraticForm_eq_sum_sq
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    quadraticForm (featureGram x) y =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
  unfold quadraticForm featureGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j =>
            y i *
              ((Finset.univ : Finset Time).sum
                (fun t => x t i * x t j)) *
              y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (Finset.univ : Finset Time).sum
            (fun t => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      rw [Finset.mul_sum, Finset.sum_mul]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Time).sum
          (fun t => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t => (Finset.univ : Finset Feature).sum
          (fun i => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
      apply Finset.sum_congr rfl
      intro t _ht
      simpa [quadraticForm, rankOneGram] using
        rankOneGram_quadraticForm_eq_sq (x := x t) (y := y)

/-- Finite-history Gram matrices have nonnegative quadratic forms. -/
theorem featureGram_quadraticForm_nonneg
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    0 <= quadraticForm (featureGram x) y := by
  rw [featureGram_quadraticForm_eq_sum_sq]
  exact Finset.sum_nonneg (fun t _ht => sq_nonneg _)

end OFUL
end BanditRLProof
