import BanditRLProof.OFULScheduledBlockStartForcedPseudoRegretDecomposition
import BanditRLProof.OFULScheduledAllHorizonHighProbabilityRegretRate

/-!
# All-time confidence for block-start forced telescoping OFUL

This module parameterizes the predictable-feature concentration layer over an
arbitrary measurable deterministic finite-history selector. It then
specializes that layer to the block-start forced telescoping OFUL policy, so
the final confidence tail is proved under the modified policy's own canonical
trajectory measure.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

universe u

namespace BanditRLProof
namespace OFUL

/-- Strict-past feature process generated by a measurable deterministic selector. -/
noncomputable def deterministicHistoryCanonicalPredictableFeature
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K) :
    Nat -> (Nat -> Fin K × Real) -> Feature -> Real
  | 0, _trajectory =>
      actionFeature ⟨0, hK⟩
  | n + 1, trajectory =>
      actionFeature (selector n (Preorder.frestrictLe n trajectory))

/-- Every coordinate of the deterministic-selector feature is strict-past measurable. -/
theorem deterministicHistoryCanonicalPredictableFeature_stronglyMeasurable
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (t : Nat) (j : Feature) :
    StronglyMeasurable[
      canonicalHistoryTrajectoryBeforeFiltration (K := K) t]
      (fun trajectory =>
        deterministicHistoryCanonicalPredictableFeature
          hK actionFeature selector t trajectory j) := by
  cases t with
  | zero =>
      exact stronglyMeasurable_const
  | succ n =>
      let F := canonicalHistoryTrajectoryBeforeFiltration (K := K)
      have hprefix :
          @Measurable (Nat -> Fin K × Real)
            ((i : Finset.Iic n) -> Fin K × Real)
            (F (n + 1)) inferInstance
            (Preorder.frestrictLe n) := by
        rw [canonicalHistoryTrajectoryBeforeFiltration_succ,
          Filtration.piLE_eq_comap_frestrictLe]
        exact Measurable.of_comap_le le_rfl
      have hfeature :
          Measurable
            (fun history : History.FinitePairHistory (Fin K) Real n =>
              actionFeature (selector n history) j) :=
        (measurable_of_countable
          (fun action : Fin K => actionFeature action j)).comp (hselector n)
      exact (hfeature.comp hprefix).stronglyMeasurable

/-- A deterministic history algorithm starts from its prescribed fixed arm. -/
theorem deterministicHistoryCanonical_action_zero_ae_eq_initialArm
    {K : Nat}
    (hK : 0 < K)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real) :
    ∀ᵐ trajectory ∂
        Thompson.canonicalHistoryTrajectoryMeasure
          (Thompson.deterministicHistoryAlgorithm
            (Fin.mk 0 hK) selector hselector)
          environment,
      Thompson.canonicalHistoryTrajectoryAction trajectory 0 = Fin.mk 0 hK := by
  letI : Nonempty (Fin K) := ⟨Fin.mk 0 hK⟩
  let algorithm :=
    Thompson.deterministicHistoryAlgorithm (Fin.mk 0 hK) selector hselector
  let mu := Thompson.canonicalHistoryTrajectoryMeasure algorithm environment
  have hmap :
      Measure.map
          (fun trajectory =>
            Thompson.canonicalHistoryTrajectoryAction trajectory 0)
          mu =
        Measure.dirac (Fin.mk 0 hK) := by
    have h :=
      Thompson.initialAction_map_eq_of_historyAlgorithmEnvironmentSequence
        mu
        Thompson.canonicalHistoryTrajectoryAction
        Thompson.canonicalHistoryTrajectoryReward
        algorithm environment
        (Thompson.canonicalHistoryAlgorithmEnvironmentSequence
          algorithm environment)
    simpa [algorithm, Thompson.deterministicHistoryAlgorithm] using h
  have hmap_ae :
      ∀ᵐ action ∂
          Measure.map
            (fun trajectory =>
              Thompson.canonicalHistoryTrajectoryAction trajectory 0)
            mu,
        action = (Fin.mk 0 hK : Fin K) := by
    rw [hmap]
    simp
  exact
    (ae_map_iff
      (Thompson.measurable_canonicalHistoryTrajectoryAction_apply
        0).aemeasurable
      (by measurability)).mp hmap_ae

/-- Actual and predictable features agree at every fixed time. -/
theorem canonicalHistoryTrajectoryFeature_ae_eq_deterministicHistoryPredictableFeature
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (t : Nat) :
    canonicalHistoryTrajectoryFeature actionFeature t =ᵐ[
      Thompson.canonicalHistoryTrajectoryMeasure
        (Thompson.deterministicHistoryAlgorithm
          (Fin.mk 0 hK) selector hselector)
        environment]
      deterministicHistoryCanonicalPredictableFeature
        hK actionFeature selector t := by
  letI : Nonempty (Fin K) := ⟨Fin.mk 0 hK⟩
  cases t with
  | zero =>
      filter_upwards [
        deterministicHistoryCanonical_action_zero_ae_eq_initialArm
          hK selector hselector environment] with trajectory htrajectory
      simp [canonicalHistoryTrajectoryFeature,
        deterministicHistoryCanonicalPredictableFeature, htrajectory]
  | succ n =>
      filter_upwards [
        Thompson.canonicalHistoryTrajectory_action_succ_ae_eq_deterministicHistorySelector
          (Fin.mk 0 hK) selector hselector environment n] with
        trajectory htrajectory
      simpa [canonicalHistoryTrajectoryFeature,
        deterministicHistoryCanonicalPredictableFeature,
        History.finitePairHistoryOfTrace,
        Thompson.canonicalHistoryTrajectoryAction,
        Thompson.canonicalHistoryTrajectoryReward,
        Preorder.frestrictLe] using congrArg actionFeature htrajectory

/-- Actual and predictable features agree simultaneously at all times. -/
theorem
    canonicalHistoryTrajectoryFeature_ae_eq_deterministicHistoryPredictableFeature_all
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real) :
    ∀ᵐ trajectory ∂
        Thompson.canonicalHistoryTrajectoryMeasure
          (Thompson.deterministicHistoryAlgorithm
            (Fin.mk 0 hK) selector hselector)
          environment,
      forall t,
        canonicalHistoryTrajectoryFeature actionFeature t trajectory =
          deterministicHistoryCanonicalPredictableFeature
            hK actionFeature selector t trajectory := by
  rw [ae_all_iff]
  exact
    canonicalHistoryTrajectoryFeature_ae_eq_deterministicHistoryPredictableFeature
      hK actionFeature selector hselector environment

/-- Reward residual centered at the deterministic selector's strict-past feature. -/
noncomputable def deterministicHistoryCanonicalPredictableResidual
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (i : Nat) (trajectory : Nat -> Fin K × Real) : Real :=
  canonicalHistoryTrajectoryResponse i trajectory -
    dotProduct thetaStar
      (deterministicHistoryCanonicalPredictableFeature
        hK actionFeature selector i trajectory)

/-- The zero-initialized deterministic-selector residual is strongly adapted. -/
theorem deterministicHistoryCanonicalPredictableResidual_stronglyAdapted
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n)) :
    StronglyAdapted
      (canonicalHistoryTrajectoryBeforeFiltration (K := K))
      (fun t trajectory =>
        match t with
        | 0 => 0
        | i + 1 =>
            deterministicHistoryCanonicalPredictableResidual
              hK thetaStar actionFeature selector i trajectory) := by
  let F := canonicalHistoryTrajectoryBeforeFiltration (K := K)
  intro t
  cases t with
  | zero =>
      exact stronglyMeasurable_const
  | succ i =>
      have hresponse :
          StronglyMeasurable[F (i + 1)]
            (canonicalHistoryTrajectoryResponse i) :=
        (measurable_canonicalHistoryTrajectoryResponse_before_succ
          (K := K) i).stronglyMeasurable
      have hfeature : forall j,
          StronglyMeasurable[F (i + 1)]
            (fun trajectory =>
              deterministicHistoryCanonicalPredictableFeature
                hK actionFeature selector i trajectory j) := by
        intro j
        exact
          (deterministicHistoryCanonicalPredictableFeature_stronglyMeasurable
            hK actionFeature selector hselector i j).mono
            (F.mono (Nat.le_succ i))
      have hdot :
          StronglyMeasurable[F (i + 1)]
            (fun trajectory =>
              dotProduct thetaStar
                (deterministicHistoryCanonicalPredictableFeature
                  hK actionFeature selector i trajectory)) := by
        have hsum :=
          Finset.stronglyMeasurable_sum
            (Finset.univ : Finset Feature) fun j _ =>
              (stronglyMeasurable_const :
                StronglyMeasurable[F (i + 1)]
                  (fun _trajectory : Nat -> Fin K × Real =>
                    thetaStar j)).mul
                (hfeature j)
        convert hsum using 1
        funext trajectory
        simp [dotProduct, Finset.sum_apply]
      simpa [F, deterministicHistoryCanonicalPredictableResidual] using
        hresponse.sub hdot

/-- Deterministic-selector features obey the finite-action projection cap. -/
theorem
    deterministicHistoryPredictableFeature_projection_le_finiteActionProjectionBound
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (actionFeature : Fin K -> Feature -> Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (theta : EuclideanSpace Real Feature)
    (i : Nat) (trajectory : Nat -> Fin K × Real) :
    |dotProduct (WithLp.ofLp theta)
        (deterministicHistoryCanonicalPredictableFeature
          hK actionFeature selector i trajectory)| <=
      finiteActionProjectionBound hK actionFeature theta := by
  letI : Nonempty (Fin K) := ⟨Fin.mk 0 hK⟩
  cases i with
  | zero =>
      simpa [deterministicHistoryCanonicalPredictableFeature,
        finiteActionProjectionBound] using
        (Finset.le_sup'
          (s := (Finset.univ : Finset (Fin K)))
          (f := fun action =>
            |dotProduct (WithLp.ofLp theta) (actionFeature action)|)
          (Finset.mem_univ (Fin.mk 0 hK)))
  | succ n =>
      simpa [deterministicHistoryCanonicalPredictableFeature,
        finiteActionProjectionBound] using
        (Finset.le_sup'
          (s := (Finset.univ : Finset (Fin K)))
          (f := fun action =>
            |dotProduct (WithLp.ofLp theta) (actionFeature action)|)
          (Finset.mem_univ
            (selector n (Preorder.frestrictLe n trajectory))))

/-- The reward marginal of a deterministic history step is its selected feedback law. -/
theorem deterministicHistory_historyStepKernel_map_snd
    {K : Nat}
    (initialAction : Fin K)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (n : Nat) (history : History.FinitePairHistory (Fin K) Real n) :
    (Thompson.historyStepKernel
        (Thompson.deterministicHistoryAlgorithm
          initialAction selector hselector)
        environment n).map Prod.snd history =
      environment.feedback n (history, selector n history) := by
  ext s hs
  rw [ProbabilityTheory.Kernel.map_apply _ measurable_snd,
    Measure.map_apply measurable_snd hs]
  unfold Thompson.historyStepKernel
  rw [ProbabilityTheory.Kernel.compProd_apply (measurable_snd hs)]
  rw [Thompson.deterministicHistoryAlgorithm_policy_apply]
  rw [lintegral_dirac]
  have hpreimage :
      Prod.mk (selector n history) ⁻¹' (Prod.snd ⁻¹' s) = s := by
    ext reward
    rfl
  rw [hpreimage]

/-- Stochastic law required by the deterministic-selector all-time confidence layer. -/
structure CanonicalDeterministicHistoryPredictableScalarRidgeResidualLaw
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R S : Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real) : Prop where
  theta_norm_le : euclideanLength thetaStar <= S
  residual_hasCondSubgaussianMGF : forall i,
    HasCondSubgaussianMGF
      (canonicalHistoryTrajectoryBeforeFiltration (K := K) i)
      ((canonicalHistoryTrajectoryBeforeFiltration (K := K)).le i)
      (deterministicHistoryCanonicalPredictableResidual
        hK thetaStar actionFeature selector i)
      (constantSquaredVarianceProxy R i)
      (Thompson.canonicalHistoryTrajectoryMeasure
        (Thompson.deterministicHistoryAlgorithm
          (Fin.mk 0 hK) selector hselector)
        environment)

/--
The kernel-level linear sub-Gaussian environment law constructs the
predictable residual law for any measurable deterministic history selector.
-/
noncomputable def
    canonicalDeterministicHistoryPredictableScalarRidgeResidualLaw_of_linearSubgaussianEnvironment
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R S : Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (source : CanonicalLinearSubgaussianEnvironmentLaw
      hK thetaStar actionFeature R S environment) :
    CanonicalDeterministicHistoryPredictableScalarRidgeResidualLaw
      hK thetaStar actionFeature R S selector hselector environment where
  theta_norm_le := source.theta_norm_le
  residual_hasCondSubgaussianMGF i := by
    let algorithm :=
      Thompson.deterministicHistoryAlgorithm
        (Fin.mk 0 hK) selector hselector
    let mu := Thompson.canonicalHistoryTrajectoryMeasure algorithm environment
    cases i with
    | zero =>
        let condition : (Nat -> Fin K × Real) -> Unit := fun _trajectory => ()
        let mcond :=
          (inferInstance : MeasurableSpace Unit).comap condition
        let reward0 : (Nat -> Fin K × Real) -> Real :=
          fun trajectory => (trajectory 0).2
        let center0 : (Nat -> Fin K × Real) -> Real :=
          fun _trajectory =>
            dotProduct thetaStar (actionFeature (Fin.mk 0 hK))
        have hmcond :
            mcond <=
              (MeasurableSpace.pi :
                MeasurableSpace (Nat -> Fin K × Real)) := by
          exact measurable_const.comap_le
        have hrewardLaw :
            Filter.Eventually
              (fun trajectory : Nat -> Fin K × Real =>
                @Measure.map (Nat -> Fin K × Real) Real
                    MeasurableSpace.pi inferInstance reward0
                    (@ProbabilityTheory.condExpKernel
                      (Nat -> Fin K × Real) MeasurableSpace.pi _ mu _
                      mcond trajectory) =
                  environment.initialFeedback (Fin.mk 0 hK))
              (ae (@Measure.trim (Nat -> Fin K × Real)
                mcond MeasurableSpace.pi mu hmcond)) := by
          simpa [mu, algorithm, mcond, condition, reward0] using
            canonicalHistoryTrajectory_initialReward_condExpKernel_map_eq_historyAlgorithmInitialFeedback_unitComap
              algorithm (Fin.mk 0 hK) rfl environment
        have htargetLaw :
            Filter.Eventually
              (fun _trajectory : Nat -> Fin K × Real =>
                ProbabilityTheory.HasSubgaussianMGF
                  (fun reward => reward - center0 _trajectory)
                  (constantSquaredVarianceProxy R 0)
                  (environment.initialFeedback (Fin.mk 0 hK)))
              (ae (@Measure.trim (Nat -> Fin K × Real)
                mcond MeasurableSpace.pi mu hmcond)) :=
          Filter.Eventually.of_forall (fun _trajectory =>
            source.initial_reward_hasSubgaussianMGF)
        have hconditional :=
          ConditionalExpectationReward.hasCondSubgaussianMGF_centered_of_condExpKernel_map_eq
            (mOmega := MeasurableSpace.pi)
            mu mcond hmcond reward0 center0
            (constantSquaredVarianceProxy R 0)
            (measurable_snd.comp (measurable_pi_apply 0))
            measurable_const
            (fun _trajectory => environment.initialFeedback (Fin.mk 0 hK))
            hrewardLaw htargetLaw
        simpa [mu, algorithm, mcond, condition, reward0, center0,
          deterministicHistoryCanonicalPredictableResidual,
          canonicalHistoryTrajectoryResponse,
          deterministicHistoryCanonicalPredictableFeature,
          MeasurableSpace.comap_const] using hconditional
    | succ n =>
        let history : (Nat -> Fin K × Real) ->
            History.FinitePairHistory (Fin K) Real n :=
          Preorder.frestrictLe n
        let mcond :=
          (inferInstance :
            MeasurableSpace
              (History.FinitePairHistory (Fin K) Real n)).comap history
        let response : (Nat -> Fin K × Real) -> Real :=
          fun trajectory => (trajectory (n + 1)).2
        let center : (Nat -> Fin K × Real) -> Real :=
          fun trajectory =>
            dotProduct thetaStar
              (deterministicHistoryCanonicalPredictableFeature
                hK actionFeature selector (n + 1) trajectory)
        let stepRewardKernel :=
          (Thompson.historyStepKernel algorithm environment n).map Prod.snd
        let target : (Nat -> Fin K × Real) -> Measure Real :=
          fun trajectory => stepRewardKernel (history trajectory)
        have hmcond :
            mcond <=
              (MeasurableSpace.pi :
                MeasurableSpace (Nat -> Fin K × Real)) := by
          simpa [mcond, history] using
            (Preorder.measurable_frestrictLe
              (X := fun _ : Nat => Fin K × Real) n).comap_le
        have hcenterF :
            @Measurable (Nat -> Fin K × Real) Real
              (canonicalHistoryTrajectoryBeforeFiltration (K := K) (n + 1))
              inferInstance center := by
          have hcoordinates : forall j,
              StronglyMeasurable[
                canonicalHistoryTrajectoryBeforeFiltration (K := K) (n + 1)]
                (fun trajectory =>
                  deterministicHistoryCanonicalPredictableFeature
                    hK actionFeature selector (n + 1) trajectory j) := by
            intro j
            exact
              deterministicHistoryCanonicalPredictableFeature_stronglyMeasurable
                hK actionFeature selector hselector (n + 1) j
          have hsum :=
            Finset.stronglyMeasurable_sum
              (Finset.univ : Finset Feature) fun j _ =>
                (stronglyMeasurable_const :
                  StronglyMeasurable[
                    canonicalHistoryTrajectoryBeforeFiltration
                      (K := K) (n + 1)]
                    (fun _trajectory : Nat -> Fin K × Real =>
                      thetaStar j)).mul
                  (hcoordinates j)
          convert hsum.measurable using 1
          funext trajectory
          simp [center, dotProduct, Finset.sum_apply]
        have hfiltration :
            (canonicalHistoryTrajectoryBeforeFiltration (K := K) (n + 1) :
                MeasurableSpace (Nat -> Fin K × Real)) = mcond := by
          simp [mcond, history,
            canonicalHistoryTrajectoryBeforeFiltration_succ,
            Filtration.piLE_eq_comap_frestrictLe]
        have hcenter : @Measurable (Nat -> Fin K × Real) Real
            mcond inferInstance center := by
          rw [← hfiltration]
          exact hcenterF
        have hrewardLaw :
            Filter.Eventually
              (fun trajectory : Nat -> Fin K × Real =>
                @Measure.map (Nat -> Fin K × Real) Real
                    MeasurableSpace.pi inferInstance response
                    (@ProbabilityTheory.condExpKernel
                      (Nat -> Fin K × Real) MeasurableSpace.pi _ mu _
                      mcond trajectory) =
                  target trajectory)
              (ae (@Measure.trim (Nat -> Fin K × Real)
                mcond MeasurableSpace.pi mu hmcond)) := by
          simpa [mu, algorithm, mcond, history, response, target,
            stepRewardKernel] using
            canonicalHistoryTrajectory_reward_succ_condExpKernel_map_eq_historyStepReward_comap
              hK algorithm environment n
        have htargetLaw :
            Filter.Eventually
              (fun trajectory : Nat -> Fin K × Real =>
                ProbabilityTheory.HasSubgaussianMGF
                  (fun reward => reward - center trajectory)
                  (constantSquaredVarianceProxy R (n + 1))
                  (target trajectory))
              (ae (@Measure.trim (Nat -> Fin K × Real)
                mcond MeasurableSpace.pi mu hmcond)) := by
          refine Filter.Eventually.of_forall (fun trajectory => ?_)
          rw [show target trajectory =
              environment.feedback n
                (history trajectory, selector n (history trajectory)) by
            exact deterministicHistory_historyStepKernel_map_snd
              (Fin.mk 0 hK) selector hselector environment n
                (history trajectory)]
          simpa [center, history,
            deterministicHistoryCanonicalPredictableFeature] using
            source.feedback_reward_hasSubgaussianMGF n (history trajectory)
              (selector n (history trajectory))
        have hconditional :=
          ConditionalExpectationReward.hasCondSubgaussianMGF_centered_of_condExpKernel_map_eq
            (mOmega := MeasurableSpace.pi)
            mu mcond hmcond response center
            (constantSquaredVarianceProxy R (n + 1))
            (measurable_snd.comp (measurable_pi_apply (n + 1)))
            hcenter target hrewardLaw htargetLaw
        have hconditionalF :=
          ConditionalExpectationReward.hasCondSubgaussianMGF_congr_measurableSpace
            (mOmega := MeasurableSpace.pi) mu mcond
            (canonicalHistoryTrajectoryBeforeFiltration (K := K) (n + 1))
            hmcond
            ((canonicalHistoryTrajectoryBeforeFiltration (K := K)).le (n + 1))
            hfiltration.symm
            (fun trajectory => response trajectory - center trajectory)
            (constantSquaredVarianceProxy R (n + 1)) hconditional
        simpa [mu, algorithm, response, center,
          deterministicHistoryCanonicalPredictableResidual] using hconditionalF

/--
All-time scalar-ridge confidence for any measurable deterministic history
selector, under that selector's own canonical trajectory measure.
-/
theorem
    measure_deterministicHistoryCanonical_allTimeTelescopingScalarRidgeConfidenceFailureSet_le
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real)
    (selector :
      (n : Nat) -> History.FinitePairHistory (Fin K) Real n -> Fin K)
    (hselector : forall n, Measurable (selector n))
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (source : CanonicalDeterministicHistoryPredictableScalarRidgeResidualLaw
      hK thetaStar actionFeature R S selector hselector environment) :
    Thompson.canonicalHistoryTrajectoryMeasure
        (Thompson.deterministicHistoryAlgorithm
          (Fin.mk 0 hK) selector hselector)
        environment
        (allTimeTelescopingScalarRidgeConfidenceFailureSet
          lambda thetaStar S
          (canonicalHistoryTrajectoryFeature actionFeature)
          canonicalHistoryTrajectoryResponse R delta) <=
      ENNReal.ofReal delta := by
  let algorithm :=
    Thompson.deterministicHistoryAlgorithm
      (Fin.mk 0 hK) selector hselector
  let mu := Thompson.canonicalHistoryTrajectoryMeasure algorithm environment
  let F := canonicalHistoryTrajectoryBeforeFiltration (K := K)
  let predictableFeature :=
    deterministicHistoryCanonicalPredictableFeature
      hK actionFeature selector
  let residual :=
    deterministicHistoryCanonicalPredictableResidual
      hK thetaStar actionFeature selector
  have hpredictable :
      mu
          (allTimeTelescopingScalarRidgeConfidenceFailureSet
            lambda thetaStar S predictableFeature
            canonicalHistoryTrajectoryResponse R delta) <=
        ENNReal.ofReal delta := by
    apply
      measure_allTimeTelescopingScalarRidgeConfidenceFailureSet_le
        mu lambda hlambda thetaStar S source.theta_norm_le F
        predictableFeature canonicalHistoryTrajectoryResponse residual
        R hR
        (fun theta _i =>
          finiteActionProjectionBound hK actionFeature theta)
    · intro i j
      exact
        deterministicHistoryCanonicalPredictableFeature_stronglyMeasurable
          hK actionFeature selector hselector i j
    · exact
        deterministicHistoryCanonicalPredictableResidual_stronglyAdapted
          hK thetaStar actionFeature selector hselector
    · intro theta i
      exact finiteActionProjectionBound_nonneg hK actionFeature theta
    · intro theta i trajectory
      exact
        deterministicHistoryPredictableFeature_projection_le_finiteActionProjectionBound
          hK actionFeature selector theta i trajectory
    · intro i
      simpa [mu, algorithm, residual] using
        source.residual_hasCondSubgaussianMGF i
    · intro trajectory i
      simp [residual, predictableFeature,
        deterministicHistoryCanonicalPredictableResidual]
    · exact hdelta
    · exact hdelta_one
  have hevents :
      ∀ᵐ trajectory ∂mu,
        trajectory ∈
            allTimeTelescopingScalarRidgeConfidenceFailureSet
              lambda thetaStar S
              (canonicalHistoryTrajectoryFeature actionFeature)
              canonicalHistoryTrajectoryResponse R delta ↔
          trajectory ∈
            allTimeTelescopingScalarRidgeConfidenceFailureSet
              lambda thetaStar S predictableFeature
              canonicalHistoryTrajectoryResponse R delta := by
    filter_upwards [
      canonicalHistoryTrajectoryFeature_ae_eq_deterministicHistoryPredictableFeature_all
        hK actionFeature selector hselector environment] with
      trajectory htrajectory
    exact
      mem_allTimeTelescopingScalarRidgeConfidenceFailureSet_iff_of_feature_eq
        lambda thetaStar S
        (canonicalHistoryTrajectoryFeature actionFeature)
        predictableFeature canonicalHistoryTrajectoryResponse
        R delta trajectory htrajectory
  change
    mu
        (allTimeTelescopingScalarRidgeConfidenceFailureSet
          lambda thetaStar S
          (canonicalHistoryTrajectoryFeature actionFeature)
          canonicalHistoryTrajectoryResponse R delta) <=
      ENNReal.ofReal delta
  calc
    mu
        (allTimeTelescopingScalarRidgeConfidenceFailureSet
          lambda thetaStar S
          (canonicalHistoryTrajectoryFeature actionFeature)
          canonicalHistoryTrajectoryResponse R delta) =
        mu
          (allTimeTelescopingScalarRidgeConfidenceFailureSet
            lambda thetaStar S predictableFeature
            canonicalHistoryTrajectoryResponse R delta) :=
      measure_congr (hevents.mono fun _ h => propext h)
    _ <= ENNReal.ofReal delta := hpredictable

/-- The linear environment law supplies the residual law for the forced selector. -/
noncomputable def
    canonicalBlockStartForcedPredictableScalarRidgeResidualLaw_of_linearSubgaussianEnvironment
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (lambda : Real)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R delta S : Real)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (source : CanonicalLinearSubgaussianEnvironmentLaw
      hK thetaStar actionFeature R S environment) :
    CanonicalDeterministicHistoryPredictableScalarRidgeResidualLaw
      hK thetaStar actionFeature R S
      (finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      (measurable_finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      environment :=
  canonicalDeterministicHistoryPredictableScalarRidgeResidualLaw_of_linearSubgaussianEnvironment
    hK thetaStar actionFeature R S
    (finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
      hK lambda actionFeature R delta S forcedAction window)
    (measurable_finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
      hK lambda actionFeature R delta S forcedAction window)
    environment source

/-- Source-level all-time confidence tail for the block-start forced policy. -/
theorem
    measure_blockStartForcedCanonicalHistoryTrajectory_allTimeConfidenceFailureSet_le
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (source : CanonicalDeterministicHistoryPredictableScalarRidgeResidualLaw
      hK thetaStar actionFeature R S
      (finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      (measurable_finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      environment) :
    Thompson.canonicalHistoryTrajectoryMeasure
        (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
          hK lambda actionFeature R delta S forcedAction window)
        environment
        (allTimeTelescopingScalarRidgeConfidenceFailureSet
          lambda thetaStar S
          (canonicalHistoryTrajectoryFeature actionFeature)
          canonicalHistoryTrajectoryResponse R delta) <=
      ENNReal.ofReal delta := by
  simpa [finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm] using
    (measure_deterministicHistoryCanonical_allTimeTelescopingScalarRidgeConfidenceFailureSet_le
      hK lambda hlambda thetaStar actionFeature R hR
      delta hdelta hdelta_one S
      (finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      (measurable_finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      environment source)

/--
The concrete block-start forced policy has the same all-time confidence tail
under its own canonical measure as any other measurable deterministic selector
driven by the same linear sub-Gaussian environment.
-/
theorem
    measure_blockStartForcedCanonicalHistoryTrajectory_allTimeConfidenceFailureSet_le_of_linearSubgaussianEnvironment
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (source : CanonicalLinearSubgaussianEnvironmentLaw
      hK thetaStar actionFeature R S environment) :
    Thompson.canonicalHistoryTrajectoryMeasure
        (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
          hK lambda actionFeature R delta S forcedAction window)
        environment
        (allTimeTelescopingScalarRidgeConfidenceFailureSet
          lambda thetaStar S
          (canonicalHistoryTrajectoryFeature actionFeature)
          canonicalHistoryTrajectoryResponse R delta) <=
      ENNReal.ofReal delta := by
  exact
    measure_blockStartForcedCanonicalHistoryTrajectory_allTimeConfidenceFailureSet_le
      hK lambda hlambda thetaStar actionFeature R hR
      delta hdelta hdelta_one S forcedAction window environment
      (canonicalBlockStartForcedPredictableScalarRidgeResidualLaw_of_linearSubgaussianEnvironment
        hK lambda thetaStar actionFeature R delta S
        forcedAction window environment source)

/-- The nonforced scheduled charge is bounded by the full pathwise width budget. -/
theorem
    blockStartOptimisticSuccessorRadiusWidthCharge_le_telescopingStandardScalarRadiusWidthBound
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (actionFeature : Fin K -> Feature -> Real)
    (R delta S : Real) (hdelta : 0 < delta) (hS : 0 <= S)
    (window horizon : Nat)
    (L2 : Real) (hL2 : 0 <= L2)
    (hactionFeatureBound : forall action,
      dotProduct (actionFeature action) (actionFeature action) <= L2)
    (hL2lambda : L2 <= lambda)
    (trajectory : Nat -> Fin K × Real) :
    blockStartOptimisticSuccessorRadiusWidthCharge
        lambda actionFeature R delta S window horizon trajectory <=
      telescopingStandardScalarRadiusWidthBound
        (Feature := Feature) R delta lambda S horizon L2 := by
  unfold blockStartOptimisticSuccessorRadiusWidthCharge
  calc
    ((Finset.range horizon).filter (fun n => n % window ≠ 0)).sum
        (fun n =>
          2 *
            finiteHorizonScalarConfidenceRadius
              (canonicalHistoryTrajectoryFeature actionFeature)
              R (allTimeTelescopingDelta delta (n + 1))
              lambda S (n + 1) trajectory *
            confidenceWidth
              (finiteHorizonScalarGram lambda
                (canonicalHistoryTrajectoryFeature actionFeature)
                (n + 1) trajectory)
              (actionFeature
                (Thompson.canonicalHistoryTrajectoryAction
                  trajectory (n + 1)))) <=
      (Finset.range horizon).sum
        (fun n =>
          2 *
            finiteHorizonScalarConfidenceRadius
              (canonicalHistoryTrajectoryFeature actionFeature)
              R (allTimeTelescopingDelta delta (n + 1))
              lambda S (n + 1) trajectory *
            confidenceWidth
              (finiteHorizonScalarGram lambda
                (canonicalHistoryTrajectoryFeature actionFeature)
                (n + 1) trajectory)
              (actionFeature
                (Thompson.canonicalHistoryTrajectoryAction
                  trajectory (n + 1)))) := by
        apply Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
        intro n _hn _hnot
        have hradius :
            0 <=
              finiteHorizonScalarConfidenceRadius
                (canonicalHistoryTrajectoryFeature actionFeature)
                R (allTimeTelescopingDelta delta (n + 1))
                lambda S (n + 1) trajectory := by
          unfold finiteHorizonScalarConfidenceRadius
            finiteHorizonConfidenceRadius
          positivity
        have hwidth :
            0 <=
              confidenceWidth
                (finiteHorizonScalarGram lambda
                  (canonicalHistoryTrajectoryFeature actionFeature)
                  (n + 1) trajectory)
                (actionFeature
                  (Thompson.canonicalHistoryTrajectoryAction
                    trajectory (n + 1))) :=
          Real.sqrt_nonneg _
        exact mul_nonneg (mul_nonneg (by norm_num) hradius) hwidth
    _ <=
      telescopingStandardScalarRadiusWidthBound
        (Feature := Feature) R delta lambda S horizon L2 :=
      canonicalHistoryTrajectory_sum_range_succ_telescoping_radius_mul_width_le_standard_of_featureBound_le_regularization
        lambda hlambda actionFeature R delta S hdelta hS
        horizon L2 hL2 hactionFeatureBound hL2lambda trajectory

/-- The fixed initial arm has the standard deterministic linear-gap envelope. -/
theorem blockStartForcedCanonicalHistoryTrajectory_initialGap_le_ae
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature]
    (hK : 0 < K)
    (lambda : Real)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R delta S : Real) (hS : 0 <= S)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (L2 : Real)
    (hactionFeatureBound : forall action,
      dotProduct (actionFeature action) (actionFeature action) <= L2)
    (best : Fin K)
    (htheta : euclideanLength thetaStar <= S) :
    ∀ᵐ trajectory ∂
        Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment,
      linearValue thetaStar (actionFeature best) -
          linearValue thetaStar
            (actionFeature
              (Thompson.canonicalHistoryTrajectoryAction trajectory 0)) <=
        standardScalarInitialGapBound S L2 := by
  filter_upwards [
    deterministicHistoryCanonical_action_zero_ae_eq_initialArm
      hK
      (finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      (measurable_finiteHistoryBlockStartForcedTelescopingScalarRidgeAction
        hK lambda actionFeature R delta S forcedAction window)
      environment] with trajectory haction
  rw [haction]
  exact
    linearValue_sub_linearValue_le_two_mul_parameterFeatureBound
      thetaStar (actionFeature best) (actionFeature (Fin.mk 0 hK))
      S L2 hS htheta
      (hactionFeatureBound best)
      (hactionFeatureBound (Fin.mk 0 hK))

/--
On the one all-time confidence event, every finite-horizon pseudo-regret is
bounded by the deterministic forced-arm charge plus the explicit telescoping
OFUL rate.
-/
theorem
    blockStartForcedCanonicalStandardHighProbabilityPseudoRegret_le_forcedActionCharge_add_explicitBound_ae
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real) (hS : 0 <= S)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (L2 : Real) (hL2 : 0 <= L2)
    (hactionFeatureBound : forall action,
      dotProduct (actionFeature action) (actionFeature action) <= L2)
    (hL2lambda : L2 <= lambda)
    (best : Fin K)
    (htheta : euclideanLength thetaStar <= S) :
    ∀ᵐ trajectory ∂
        Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment,
      forall horizon,
        trajectory ∉
            allTimeTelescopingScalarRidgeConfidenceFailureSet
              lambda thetaStar S
              (canonicalHistoryTrajectoryFeature actionFeature)
              canonicalHistoryTrajectoryResponse R delta ->
          canonicalStandardHighProbabilityPseudoRegret
              thetaStar actionFeature best horizon trajectory <=
            blockStartForcedActionSuccessorPseudoRegret
                thetaStar actionFeature best forcedAction window horizon +
              telescopingHighProbabilityPseudoRegretBound
                (Feature := Feature) R delta lambda S horizon L2 := by
  rw [ae_all_iff]
  intro horizon
  filter_upwards [
    canonicalStandardHighProbabilityPseudoRegret_le_initial_add_forcedActionCharge_add_radiusWidthCharge_ae_of_not_mem_allTimeConfidenceFailure
      hK lambda hlambda thetaStar actionFeature R delta S
      forcedAction window environment horizon best,
    blockStartForcedCanonicalHistoryTrajectory_initialGap_le_ae
      hK lambda thetaStar actionFeature R delta S hS
      forcedAction window environment L2 hactionFeatureBound best htheta] with
    trajectory hdecomposition hinitial
  intro hgood
  have hregret := hdecomposition hgood
  have hradius :=
    blockStartOptimisticSuccessorRadiusWidthCharge_le_telescopingStandardScalarRadiusWidthBound
      lambda hlambda actionFeature R delta S hdelta hS
      window horizon L2 hL2 hactionFeatureBound hL2lambda trajectory
  have hbudget :=
    telescopingStandardScalarAllRoundGapBound_eq_telescopingHighProbabilityPseudoRegretBound
      (Feature := Feature)
      R hR delta hdelta hdelta_one lambda hlambda S horizon L2 hL2
  unfold telescopingStandardScalarAllRoundGapBound at hbudget
  linarith

/-- All-horizon violation event for the block-start forced pseudo-regret rate. -/
noncomputable def
    blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet
    {K : Nat} {Feature : Type u}
    [Fintype Feature]
    (lambda : Real)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R delta S L2 : Real)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (best : Fin K) :
    Set (Nat -> Fin K × Real) :=
  {trajectory | exists horizon,
    blockStartForcedActionSuccessorPseudoRegret
        thetaStar actionFeature best forcedAction window horizon +
        telescopingHighProbabilityPseudoRegretBound
          (Feature := Feature) R delta lambda S horizon L2 <
      canonicalStandardHighProbabilityPseudoRegret
        thetaStar actionFeature best horizon trajectory}

/-- Every all-horizon forced-policy regret violation is a confidence failure a.e. -/
theorem
    blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet_subset_confidenceFailure_ae
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real) (hS : 0 <= S)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (L2 : Real) (hL2 : 0 <= L2)
    (hactionFeatureBound : forall action,
      dotProduct (actionFeature action) (actionFeature action) <= L2)
    (hL2lambda : L2 <= lambda)
    (best : Fin K)
    (htheta : euclideanLength thetaStar <= S) :
    ∀ᵐ trajectory ∂
        Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment,
      trajectory ∈
          blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet
            lambda thetaStar actionFeature R delta S L2
            forcedAction window best ->
        trajectory ∈
          allTimeTelescopingScalarRidgeConfidenceFailureSet
            lambda thetaStar S
            (canonicalHistoryTrajectoryFeature actionFeature)
            canonicalHistoryTrajectoryResponse R delta := by
  filter_upwards [
    blockStartForcedCanonicalStandardHighProbabilityPseudoRegret_le_forcedActionCharge_add_explicitBound_ae
      hK lambda hlambda thetaStar actionFeature R hR
      delta hdelta hdelta_one S hS forcedAction window environment
      L2 hL2 hactionFeatureBound hL2lambda best htheta] with
    trajectory htrajectory
  rintro ⟨horizon, hviolation⟩
  by_contra hgood
  exact (not_lt_of_ge (htrajectory horizon hgood)) hviolation

/--
Complete all-horizon high-probability pseudo-regret theorem for the block-start
forced policy. The ordinary OFUL rate is augmented only by the deterministic
forced-arm gap charge.
-/
theorem
    blockStartForcedCanonicalStandardHighProbabilityPseudoRegret_nonneg_and_allHorizon_tail_le_explicitBound_of_linearSubgaussianEnvironment_of_featureBound_le_regularization
    {K : Nat} {Feature : Type u}
    [Fintype Feature] [DecidableEq Feature] [Nonempty Feature]
    (hK : 0 < K)
    (lambda : Real) (hlambda : 0 < lambda)
    (thetaStar : Feature -> Real)
    (actionFeature : Fin K -> Feature -> Real)
    (R : Real) (hR : 0 < R)
    (delta : Real) (hdelta : 0 < delta) (hdelta_one : delta <= 1)
    (S : Real) (hS : 0 <= S)
    (forcedAction : Nat -> Fin K)
    (window : Nat)
    (environment : Thompson.HistoryEnvironment (Fin K) Real)
    (L2 : Real) (hL2 : 0 <= L2)
    (hactionFeatureBound : forall action,
      dotProduct (actionFeature action) (actionFeature action) <= L2)
    (hL2lambda : L2 <= lambda)
    (best : Fin K)
    (hbest : IsOptimalLinearArm thetaStar actionFeature best)
    (source : CanonicalLinearSubgaussianEnvironmentLaw
      hK thetaStar actionFeature R S environment) :
    (forall horizon trajectory,
      0 <= canonicalStandardHighProbabilityPseudoRegret
        thetaStar actionFeature best horizon trajectory) ∧
      Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment
          (blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet
            lambda thetaStar actionFeature R delta S L2
            forcedAction window best) <=
        ENNReal.ofReal delta := by
  constructor
  · intro horizon trajectory
    exact
      canonicalHistoryTrajectorySumRangeAllFixedComparatorGap_nonneg
        thetaStar actionFeature horizon best hbest trajectory
  · calc
      Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment
          (blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet
            lambda thetaStar actionFeature R delta S L2
            forcedAction window best) <=
        Thompson.canonicalHistoryTrajectoryMeasure
          (finiteHistoryBlockStartForcedTelescopingScalarRidgeAlgorithm
            hK lambda actionFeature R delta S forcedAction window)
          environment
          (allTimeTelescopingScalarRidgeConfidenceFailureSet
            lambda thetaStar S
            (canonicalHistoryTrajectoryFeature actionFeature)
            canonicalHistoryTrajectoryResponse R delta) := by
        exact measure_mono_ae
          (blockStartForcedCanonicalStandardHighProbabilityPseudoRegretAllHorizonViolationSet_subset_confidenceFailure_ae
            hK lambda hlambda thetaStar actionFeature R hR
            delta hdelta hdelta_one S hS forcedAction window environment
            L2 hL2 hactionFeatureBound hL2lambda best source.theta_norm_le)
      _ <= ENNReal.ofReal delta :=
        measure_blockStartForcedCanonicalHistoryTrajectory_allTimeConfidenceFailureSet_le_of_linearSubgaussianEnvironment
          hK lambda hlambda thetaStar actionFeature R hR
          delta hdelta hdelta_one S forcedAction window environment source

end OFUL
end BanditRLProof
