import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Analysis.Matrix.PosDef
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Real.Basic
import Mathlib.LinearAlgebra.Matrix.SchurComplement
import Mathlib.Tactic.Ring

/-!
# OFUL elliptical-potential linear algebra wrappers

This module records the first deterministic finite-dimensional linear-algebra
surface needed by OFUL/LinUCB routes.  It packages rank-one feature Gram
matrices and finite-history Gram matrices, then proves their quadratic forms
are squares or sums of squares.  It also exposes the determinant and
invertibility side condition for the scalar regularization base used in OFUL
Gram recursions.

It does not prove log-determinant telescoping, determinant growth inequalities,
self-normalized concentration, confidence ellipsoids, or an OFUL regret theorem.
-/

namespace BanditRLProof
namespace OFUL

universe u v

/-- Rank-one Gram matrix generated by one feature vector. -/
def rankOneGram {Feature : Type u}
    (x : Feature -> Real) : Matrix Feature Feature Real :=
  fun i j => x i * x j

/-- The local rank-one Gram matrix is Mathlib's column-row product shape. -/
theorem rankOneGram_eq_replicateCol_mul_replicateRow
    {Feature : Type u} [Fintype Feature]
    (x : Feature -> Real) :
    rankOneGram x =
      Matrix.replicateCol Unit x * Matrix.replicateRow Unit x := by
  ext i j
  simp [rankOneGram, Matrix.mul_apply]

/-- Rank-one Gram matrices are Hermitian. -/
theorem rankOneGram_isHermitian
    {Feature : Type u} [Fintype Feature]
    (x : Feature -> Real) :
    (rankOneGram x).IsHermitian := by
  refine Matrix.IsHermitian.ext ?_
  intro i j
  simp [rankOneGram, mul_comm]

/--
Rank-one determinant lemma at the identity, specialized to feature Gram
updates.
-/
theorem det_one_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (x : Feature -> Real) :
    (1 + rankOneGram x).det = 1 + dotProduct x x := by
  rw [rankOneGram_eq_replicateCol_mul_replicateRow]
  simpa using
    Matrix.det_one_add_replicateCol_mul_replicateRow (ι := Unit)
      (u := x) (v := x)

/--
The one-dimensional determinant factor in the rank-one matrix determinant
lemma is the scalar `1 + x^T A^{-1} x`.
-/
theorem det_rankOne_update_factor_eq_one_add_dotProduct_inv_mulVec
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (A : Matrix Feature Feature Real) (x : Feature -> Real) :
    (1 + Matrix.replicateRow Unit x * A⁻¹ *
        Matrix.replicateCol Unit x).det =
      1 + dotProduct x (Matrix.mulVec (A⁻¹) x) := by
  rw [Matrix.det_unique]
  simp [Matrix.mul_apply, dotProduct, Matrix.mulVec, Finset.sum_mul]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro i _hi
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j _hj
  ring

/--
Rank-one matrix determinant lemma in OFUL feature notation.

The invertibility side condition is kept as Mathlib's `IsUnit A.det`, matching
the upstream Schur-complement API.
-/
theorem det_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (A : Matrix Feature Feature Real) (hA : IsUnit A.det)
    (x : Feature -> Real) :
    (A + rankOneGram x).det =
      A.det * (1 + dotProduct x (Matrix.mulVec (A⁻¹) x)) := by
  rw [rankOneGram_eq_replicateCol_mul_replicateRow]
  rw [Matrix.det_add_replicateCol_mul_replicateRow (ι := Unit)
    (A := A) hA x x]
  rw [det_rankOne_update_factor_eq_one_add_dotProduct_inv_mulVec]

/-- Determinant of the scalar regularization matrix `lambda I`. -/
theorem det_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) :
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det =
      lambda ^ Fintype.card Feature := by
  rw [Matrix.scalar_apply]
  rw [Matrix.det_diagonal]
  simp

/-- Nonzero scalar regularization has nonzero determinant. -/
theorem det_scalar_identity_ne_zero
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) :
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det ≠ 0 := by
  rw [det_scalar_identity]
  exact pow_ne_zero _ hlambda

/--
Nonzero scalar regularization satisfies Mathlib's determinant-unit side
condition for the rank-one determinant update lemma.
-/
theorem isUnit_det_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) :
    IsUnit (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det := by
  exact IsUnit.mk0 _ (det_scalar_identity_ne_zero hlambda)

/--
First determinant update from the regularized scalar base `lambda I`.

This is the one-step OFUL/LinUCB determinant recursion specialized to the
empty-history base matrix.  General log-det telescoping and determinant-growth
bounds remain separate leaves.
-/
theorem det_scalar_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) (x : Feature -> Real) :
    ((Matrix.scalar Feature lambda : Matrix Feature Feature Real) +
        rankOneGram x).det =
      (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det *
        (1 + dotProduct x
          (Matrix.mulVec
            ((Matrix.scalar Feature lambda :
              Matrix Feature Feature Real)⁻¹) x)) := by
  exact det_add_rankOneGram
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real)
    (isUnit_det_scalar_identity hlambda) x

/-- Quadratic form associated with a finite real matrix. -/
noncomputable def quadraticForm {Feature : Type u} [Fintype Feature]
    (A : Matrix Feature Feature Real) (y : Feature -> Real) : Real :=
  (Finset.univ : Finset Feature).sum
    (fun i => (Finset.univ : Finset Feature).sum
      (fun j => y i * A i j * y j))

/-- Quadratic forms distribute over matrix addition. -/
theorem quadraticForm_add
    {Feature : Type u} [Fintype Feature]
    (A B : Matrix Feature Feature Real) (y : Feature -> Real) :
    quadraticForm (A + B) y = quadraticForm A y + quadraticForm B y := by
  unfold quadraticForm
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * (A i j + B i j) * y j)) =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * A i j * y j + y i * B i j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i =>
          (Finset.univ : Finset Feature).sum
            (fun j => y i * A i j * y j) +
          (Finset.univ : Finset Feature).sum
            (fun j => y i * B i j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_add_distrib]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * A i j * y j)) +
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * B i j * y j)) := by
      rw [Finset.sum_add_distrib]

/-- The Mathlib dot-product/mulVec form agrees with the local quadratic form. -/
theorem dotProduct_mulVec_eq_quadraticForm
    {Feature : Type u} [Fintype Feature]
    (A : Matrix Feature Feature Real) (y : Feature -> Real) :
    dotProduct y (Matrix.mulVec A y) = quadraticForm A y := by
  simp [dotProduct, Matrix.mulVec, quadraticForm, Finset.mul_sum, mul_assoc]

/-- Quadratic form of the scalar regularization matrix `lambda I`. -/
theorem quadraticForm_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (y : Feature -> Real) :
    quadraticForm
        (Matrix.scalar Feature lambda : Matrix Feature Feature Real) y =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
  unfold quadraticForm
  rw [Matrix.scalar_apply]
  simp [Matrix.diagonal_apply]
  calc
    (Finset.univ : Finset Feature).sum
        (fun x => y x * lambda * y x) =
      (Finset.univ : Finset Feature).sum
        (fun x => lambda * y x ^ 2) := by
      apply Finset.sum_congr rfl
      intro x _hx
      ring
    _ =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
      rw [Finset.mul_sum]

/-- A finite sum of coordinate squares is positive for a nonzero vector. -/
theorem sum_sq_pos_of_exists_ne_zero
    {Feature : Type u} [Fintype Feature]
    (y : Feature -> Real) (hy : ∃ i : Feature, y i ≠ 0) :
    0 < (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
  classical
  let i := Classical.choose hy
  have hi : y i ≠ 0 := Classical.choose_spec hy
  refine Finset.sum_pos' (fun j _hj => sq_nonneg (y j)) ?_
  exact Exists.intro i
    (And.intro (Finset.mem_univ i) (sq_pos_of_ne_zero hi))

/-- A nonzero vector has a nonzero coordinate. -/
theorem exists_coord_ne_zero_of_ne_zero
    {Feature : Type u} (y : Feature -> Real) (hy : y ≠ 0) :
    ∃ i : Feature, y i ≠ 0 := by
  by_contra h
  apply hy
  funext i
  by_contra hi
  exact h (Exists.intro i hi)

/-- Finite-history feature Gram matrix `sum_t x_t x_t^T`. -/
noncomputable def featureGram {Time : Type v} {Feature : Type u}
    [Fintype Time] (x : Time -> Feature -> Real) :
    Matrix Feature Feature Real :=
  fun i j => (Finset.univ : Finset Time).sum
    (fun t => x t i * x t j)

/-- Finite-history feature Gram matrices are Hermitian. -/
theorem featureGram_isHermitian
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) :
    (featureGram x).IsHermitian := by
  refine Matrix.IsHermitian.ext ?_
  intro i j
  simp [featureGram, mul_comm]

/-- Regularized finite-history Gram matrix `lambda I + sum_t x_t x_t^T`. -/
noncomputable def regularizedFeatureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    Matrix Feature Feature Real :=
  Matrix.scalar Feature lambda + featureGram x

/-- The named regularized Gram unfolds to scalar regularization plus Gram. -/
theorem regularizedFeatureGram_eq_scalar_add_featureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    regularizedFeatureGram lambda x =
      Matrix.scalar Feature lambda + featureGram x := by
  rfl

/-- Regularized finite-history feature Gram matrices are Hermitian. -/
theorem regularizedFeatureGram_isHermitian
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).IsHermitian := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  exact Matrix.IsHermitian.add (by
    rw [Matrix.scalar_apply]
    exact Matrix.isHermitian_diagonal _) (featureGram_isHermitian x)

/-- Prefix Gram matrix `sum_{t < T} x_t x_t^T` for a Nat-indexed history. -/
noncomputable def prefixFeatureGram {Feature : Type u}
    (x : Nat -> Feature -> Real) (T : Nat) :
    Matrix Feature Feature Real :=
  fun i j => (Finset.range T).sum (fun t => x t i * x t j)

/-- Regularized prefix Gram matrix `lambda I + sum_{t < T} x_t x_t^T`. -/
noncomputable def regularizedPrefixFeatureGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Nat -> Feature -> Real) (T : Nat) :
    Matrix Feature Feature Real :=
  Matrix.scalar Feature lambda + prefixFeatureGram x T

/-- Prefix Grams grow by one rank-one feature update. -/
theorem prefixFeatureGram_succ
    {Feature : Type u}
    (x : Nat -> Feature -> Real) (T : Nat) :
    prefixFeatureGram x (T + 1) =
      prefixFeatureGram x T + rankOneGram (x T) := by
  ext i j
  simp [prefixFeatureGram, rankOneGram, Finset.sum_range_succ]

/-- Regularized prefix Grams grow by one rank-one feature update. -/
theorem regularizedPrefixFeatureGram_succ
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Nat -> Feature -> Real) (T : Nat) :
    regularizedPrefixFeatureGram lambda x (T + 1) =
      regularizedPrefixFeatureGram lambda x T + rankOneGram (x T) := by
  ext i j
  simp [regularizedPrefixFeatureGram, prefixFeatureGram, rankOneGram,
    Finset.sum_range_succ]
  ring

/-- Prefix Gram matrices are Hermitian. -/
theorem prefixFeatureGram_isHermitian
    {Feature : Type u} [Fintype Feature]
    (x : Nat -> Feature -> Real) (T : Nat) :
    (prefixFeatureGram x T).IsHermitian := by
  refine Matrix.IsHermitian.ext ?_
  intro i j
  simp [prefixFeatureGram, mul_comm]

/-- Regularized prefix Gram matrices are Hermitian. -/
theorem regularizedPrefixFeatureGram_isHermitian
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Nat -> Feature -> Real) (T : Nat) :
    (regularizedPrefixFeatureGram lambda x T).IsHermitian := by
  rw [regularizedPrefixFeatureGram]
  exact Matrix.IsHermitian.add (by
    rw [Matrix.scalar_apply]
    exact Matrix.isHermitian_diagonal _) (prefixFeatureGram_isHermitian x T)

/--
The quadratic form of a rank-one Gram matrix is the square of the projection
of the query vector onto the feature vector.
-/
theorem rankOneGram_quadraticForm_eq_sq
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    quadraticForm (rankOneGram x) y =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
  unfold quadraticForm rankOneGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * (x i * x j) * y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (y i * x i) * (x j * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (y i * x i) *
          (Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.mul_sum]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      rw [Finset.sum_mul]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      have hleft :
          ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) =
            ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) := by
        apply Finset.sum_congr rfl
        intro i _hi
        ring
      rw [hleft]
    _ = ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
      ring

/-- Rank-one Gram matrices are Mathlib-positive semidefinite. -/
theorem rankOneGram_posSemidef
    {Feature : Type u} [Fintype Feature]
    (x : Feature -> Real) :
    (rankOneGram x).PosSemidef := by
  refine Matrix.PosSemidef.of_dotProduct_mulVec_nonneg
    (rankOneGram_isHermitian x) ?_
  intro y
  have hstar : star y = y := by
    funext i
    simp
  rw [hstar]
  rw [dotProduct_mulVec_eq_quadraticForm]
  rw [rankOneGram_quadraticForm_eq_sq]
  exact sq_nonneg _

/-- Rank-one Gram matrices have nonnegative quadratic forms. -/
theorem rankOneGram_quadraticForm_nonneg
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    0 <= quadraticForm (rankOneGram x) y := by
  rw [rankOneGram_quadraticForm_eq_sq]
  exact sq_nonneg _

/--
The quadratic form of a finite-history Gram matrix is a finite sum of squared
feature projections.
-/
theorem featureGram_quadraticForm_eq_sum_sq
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    quadraticForm (featureGram x) y =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
  unfold quadraticForm featureGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j =>
            y i *
              ((Finset.univ : Finset Time).sum
                (fun t => x t i * x t j)) *
              y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (Finset.univ : Finset Time).sum
            (fun t => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      rw [Finset.mul_sum, Finset.sum_mul]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Time).sum
          (fun t => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t => (Finset.univ : Finset Feature).sum
          (fun i => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
      apply Finset.sum_congr rfl
      intro t _ht
      simpa [quadraticForm, rankOneGram] using
        rankOneGram_quadraticForm_eq_sq (x := x t) (y := y)

/--
The quadratic form of a Nat-prefix Gram matrix is a finite range sum of
squared feature projections.
-/
theorem prefixFeatureGram_quadraticForm_eq_sum_sq
    {Feature : Type u} [Fintype Feature]
    (x : Nat -> Feature -> Real) (T : Nat) (y : Feature -> Real) :
    quadraticForm (prefixFeatureGram x T) y =
      (Finset.range T).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
  unfold quadraticForm prefixFeatureGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j =>
            y i *
              ((Finset.range T).sum
                (fun t => x t i * x t j)) *
              y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (Finset.range T).sum
            (fun t => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      rw [Finset.mul_sum, Finset.sum_mul]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.range T).sum
          (fun t => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_comm]
    _ =
      (Finset.range T).sum
        (fun t => (Finset.univ : Finset Feature).sum
          (fun i => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      rw [Finset.sum_comm]
    _ =
      (Finset.range T).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
      apply Finset.sum_congr rfl
      intro t _ht
      simpa [quadraticForm, rankOneGram] using
        rankOneGram_quadraticForm_eq_sq (x := x t) (y := y)

/--
The regularized Gram quadratic form is the scalar regularization term plus the
finite-history Gram sum of squared feature projections.
-/
theorem regularizedFeatureGram_quadraticForm_eq_sum_sq
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) (y : Feature -> Real) :
    quadraticForm (regularizedFeatureGram lambda x) y =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) +
        (Finset.univ : Finset Time).sum
          (fun t =>
            ((Finset.univ : Finset Feature).sum
              (fun i => x t i * y i)) ^ 2) := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  rw [featureGram_quadraticForm_eq_sum_sq]

/--
The regularized prefix Gram quadratic form is the scalar regularization term
plus the prefix sum of squared feature projections.
-/
theorem regularizedPrefixFeatureGram_quadraticForm_eq_sum_sq
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Nat -> Feature -> Real) (T : Nat)
    (y : Feature -> Real) :
    quadraticForm (regularizedPrefixFeatureGram lambda x T) y =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) +
        (Finset.range T).sum
          (fun t =>
            ((Finset.univ : Finset Feature).sum
              (fun i => x t i * y i)) ^ 2) := by
  rw [regularizedPrefixFeatureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  rw [prefixFeatureGram_quadraticForm_eq_sum_sq]

/-- Finite-history Gram matrices have nonnegative quadratic forms. -/
theorem featureGram_quadraticForm_nonneg
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    0 <= quadraticForm (featureGram x) y := by
  rw [featureGram_quadraticForm_eq_sum_sq]
  exact Finset.sum_nonneg (fun t _ht => sq_nonneg _)

/-- Nat-prefix Gram matrices have nonnegative quadratic forms. -/
theorem prefixFeatureGram_quadraticForm_nonneg
    {Feature : Type u} [Fintype Feature]
    (x : Nat -> Feature -> Real) (T : Nat) (y : Feature -> Real) :
    0 <= quadraticForm (prefixFeatureGram x T) y := by
  rw [prefixFeatureGram_quadraticForm_eq_sum_sq]
  exact Finset.sum_nonneg (fun t _ht => sq_nonneg _)

/-- Regularized finite-history Gram matrices are PSD when `0 <= lambda`. -/
theorem regularizedFeatureGram_quadraticForm_nonneg
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 <= lambda)
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    0 <= quadraticForm (regularizedFeatureGram lambda x) y := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  exact add_nonneg
    (mul_nonneg hlambda (Finset.sum_nonneg (fun i _hi => sq_nonneg _)))
    (featureGram_quadraticForm_nonneg x y)

/-- Regularized Nat-prefix Gram matrices are PSD when `0 <= lambda`. -/
theorem regularizedPrefixFeatureGram_quadraticForm_nonneg
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 <= lambda)
    (x : Nat -> Feature -> Real) (T : Nat) (y : Feature -> Real) :
    0 <= quadraticForm (regularizedPrefixFeatureGram lambda x T) y := by
  rw [regularizedPrefixFeatureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  exact add_nonneg
    (mul_nonneg hlambda (Finset.sum_nonneg (fun i _hi => sq_nonneg _)))
    (prefixFeatureGram_quadraticForm_nonneg x T y)

/--
Regularized finite-history Gram matrices have strictly positive quadratic
forms on nonzero vectors when `0 < lambda`.
-/
theorem regularizedFeatureGram_quadraticForm_pos_of_pos_lambda
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) (y : Feature -> Real)
    (hy : ∃ i : Feature, y i ≠ 0) :
    0 < quadraticForm (regularizedFeatureGram lambda x) y := by
  rw [regularizedFeatureGram_quadraticForm_eq_sum_sq]
  exact add_pos_of_pos_of_nonneg
    (mul_pos hlambda (sum_sq_pos_of_exists_ne_zero y hy))
    (Finset.sum_nonneg (fun t _ht => sq_nonneg _))

/--
Regularized Nat-prefix Gram matrices have strictly positive quadratic forms on
nonzero vectors when `0 < lambda`.
-/
theorem regularizedPrefixFeatureGram_quadraticForm_pos_of_pos_lambda
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Nat -> Feature -> Real) (T : Nat) (y : Feature -> Real)
    (hy : ∃ i : Feature, y i ≠ 0) :
    0 < quadraticForm (regularizedPrefixFeatureGram lambda x T) y := by
  rw [regularizedPrefixFeatureGram_quadraticForm_eq_sum_sq]
  exact add_pos_of_pos_of_nonneg
    (mul_pos hlambda (sum_sq_pos_of_exists_ne_zero y hy))
    (Finset.sum_nonneg (fun t _ht => sq_nonneg _))

/-- Regularized finite-history Gram matrices are Mathlib-positive definite. -/
theorem regularizedFeatureGram_posDef
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).PosDef := by
  refine Matrix.PosDef.of_dotProduct_mulVec_pos
    (regularizedFeatureGram_isHermitian lambda x) ?_
  intro y hy
  have hstar : star y = y := by
    funext i
    simp
  rw [hstar]
  rw [dotProduct_mulVec_eq_quadraticForm]
  exact regularizedFeatureGram_quadraticForm_pos_of_pos_lambda
    lambda hlambda x y (exists_coord_ne_zero_of_ne_zero y hy)

/-- Regularized Nat-prefix Gram matrices are Mathlib-positive definite. -/
theorem regularizedPrefixFeatureGram_posDef
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Nat -> Feature -> Real) (T : Nat) :
    (regularizedPrefixFeatureGram lambda x T).PosDef := by
  refine Matrix.PosDef.of_dotProduct_mulVec_pos
    (regularizedPrefixFeatureGram_isHermitian lambda x T) ?_
  intro y hy
  have hstar : star y = y := by
    funext i
    simp
  rw [hstar]
  rw [dotProduct_mulVec_eq_quadraticForm]
  exact regularizedPrefixFeatureGram_quadraticForm_pos_of_pos_lambda
    lambda hlambda x T y (exists_coord_ne_zero_of_ne_zero y hy)

/-- Regularized finite-history Gram matrices have positive determinant. -/
theorem regularizedFeatureGram_det_pos
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    0 < (regularizedFeatureGram lambda x).det := by
  exact Matrix.PosDef.det_pos (regularizedFeatureGram_posDef lambda hlambda x)

/-- Regularized Nat-prefix Gram matrices have positive determinant. -/
theorem regularizedPrefixFeatureGram_det_pos
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Nat -> Feature -> Real) (T : Nat) :
    0 < (regularizedPrefixFeatureGram lambda x T).det := by
  exact Matrix.PosDef.det_pos
    (regularizedPrefixFeatureGram_posDef lambda hlambda x T)

/-- Regularized finite-history Gram matrices have nonzero determinant. -/
theorem regularizedFeatureGram_det_ne_zero
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).det ≠ 0 := by
  exact ne_of_gt (regularizedFeatureGram_det_pos lambda hlambda x)

/-- Regularized Nat-prefix Gram matrices have nonzero determinant. -/
theorem regularizedPrefixFeatureGram_det_ne_zero
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Nat -> Feature -> Real) (T : Nat) :
    (regularizedPrefixFeatureGram lambda x T).det ≠ 0 := by
  exact ne_of_gt (regularizedPrefixFeatureGram_det_pos lambda hlambda x T)

/--
Positive regularization supplies Mathlib's determinant-unit side condition for
arbitrary finite-history regularized Gram matrices.
-/
theorem isUnit_det_regularizedFeatureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    IsUnit (regularizedFeatureGram lambda x).det := by
  exact IsUnit.mk0 _ (regularizedFeatureGram_det_ne_zero lambda hlambda x)

/--
Positive regularization supplies Mathlib's determinant-unit side condition for
Nat-prefix regularized Gram matrices.
-/
theorem isUnit_det_regularizedPrefixFeatureGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Nat -> Feature -> Real) (T : Nat) :
    IsUnit (regularizedPrefixFeatureGram lambda x T).det := by
  exact IsUnit.mk0 _
    (regularizedPrefixFeatureGram_det_ne_zero lambda hlambda x T)

/--
One-step determinant recursion for an arbitrary finite-history regularized Gram
matrix.

This is the determinant identity consumed by OFUL/LinUCB log-det telescoping:
the `IsUnit det` side condition is discharged from positive regularization.
-/
theorem det_regularizedFeatureGram_add_rankOneGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    (regularizedFeatureGram lambda history + rankOneGram x).det =
      (regularizedFeatureGram lambda history).det *
        (1 + dotProduct x
          (Matrix.mulVec
            ((regularizedFeatureGram lambda history)⁻¹) x)) := by
  exact det_add_rankOneGram (regularizedFeatureGram lambda history)
    (isUnit_det_regularizedFeatureGram lambda hlambda history) x

/--
One-step determinant recursion for Nat-prefix regularized Gram matrices.

This keeps the growing-history surface in a single Nat-indexed feature stream.
-/
theorem det_regularizedPrefixFeatureGram_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det =
      (regularizedPrefixFeatureGram lambda history T).det *
        (1 + dotProduct x
          (Matrix.mulVec
            ((regularizedPrefixFeatureGram lambda history T)⁻¹) x)) := by
  exact det_add_rankOneGram (regularizedPrefixFeatureGram lambda history T)
    (isUnit_det_regularizedPrefixFeatureGram lambda hlambda history T) x

/-- Positive regularized Grams stay positive definite after a rank-one update. -/
theorem regularizedFeatureGram_add_rankOneGram_posDef
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    (regularizedFeatureGram lambda history + rankOneGram x).PosDef := by
  exact Matrix.PosDef.add_posSemidef
    (regularizedFeatureGram_posDef lambda hlambda history)
    (rankOneGram_posSemidef x)

/-- Positive regularized prefix Grams stay positive definite after a rank-one update. -/
theorem regularizedPrefixFeatureGram_add_rankOneGram_posDef
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    (regularizedPrefixFeatureGram lambda history T + rankOneGram x).PosDef := by
  exact Matrix.PosDef.add_posSemidef
    (regularizedPrefixFeatureGram_posDef lambda hlambda history T)
    (rankOneGram_posSemidef x)

/-- The determinant after a positive regularized rank-one update is positive. -/
theorem det_regularizedFeatureGram_add_rankOneGram_pos
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    0 < (regularizedFeatureGram lambda history + rankOneGram x).det := by
  exact Matrix.PosDef.det_pos
    (regularizedFeatureGram_add_rankOneGram_posDef
      lambda hlambda history x)

/-- The determinant after a positive regularized prefix rank-one update is positive. -/
theorem det_regularizedPrefixFeatureGram_add_rankOneGram_pos
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    0 < (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det := by
  exact Matrix.PosDef.det_pos
    (regularizedPrefixFeatureGram_add_rankOneGram_posDef
      lambda hlambda history T x)

/-- The scalar rank-one determinant-update factor is positive. -/
theorem regularizedFeatureGram_rankOne_update_factor_pos
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    0 < 1 + dotProduct x
      (Matrix.mulVec ((regularizedFeatureGram lambda history)⁻¹) x) := by
  set factor := 1 + dotProduct x
    (Matrix.mulVec ((regularizedFeatureGram lambda history)⁻¹) x)
  have hdet :
      (regularizedFeatureGram lambda history + rankOneGram x).det =
        (regularizedFeatureGram lambda history).det * factor := by
    simpa [factor] using
      det_regularizedFeatureGram_add_rankOneGram
        lambda hlambda history x
  have hnew : 0 <
      (regularizedFeatureGram lambda history + rankOneGram x).det :=
    det_regularizedFeatureGram_add_rankOneGram_pos
      lambda hlambda history x
  have hmul : 0 <
      (regularizedFeatureGram lambda history).det * factor := by
    simpa [hdet] using hnew
  exact pos_of_mul_pos_right hmul
    (le_of_lt (regularizedFeatureGram_det_pos lambda hlambda history))

/-- The scalar Nat-prefix rank-one determinant-update factor is positive. -/
theorem regularizedPrefixFeatureGram_rankOne_update_factor_pos
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    0 < 1 + dotProduct x
      (Matrix.mulVec ((regularizedPrefixFeatureGram lambda history T)⁻¹) x) := by
  set factor := 1 + dotProduct x
    (Matrix.mulVec ((regularizedPrefixFeatureGram lambda history T)⁻¹) x)
  have hdet :
      (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det =
        (regularizedPrefixFeatureGram lambda history T).det * factor := by
    simpa [factor] using
      det_regularizedPrefixFeatureGram_add_rankOneGram
        lambda hlambda history T x
  have hnew : 0 <
      (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det :=
    det_regularizedPrefixFeatureGram_add_rankOneGram_pos
      lambda hlambda history T x
  have hmul : 0 <
      (regularizedPrefixFeatureGram lambda history T).det * factor := by
    simpa [hdet] using hnew
  exact pos_of_mul_pos_right hmul
    (le_of_lt (regularizedPrefixFeatureGram_det_pos lambda hlambda history T))

/-- Logarithmic one-step determinant recursion for regularized Grams. -/
theorem log_det_regularizedFeatureGram_add_rankOneGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    Real.log (regularizedFeatureGram lambda history + rankOneGram x).det =
      Real.log (regularizedFeatureGram lambda history).det +
        Real.log (1 + dotProduct x
          (Matrix.mulVec ((regularizedFeatureGram lambda history)⁻¹) x)) := by
  rw [det_regularizedFeatureGram_add_rankOneGram
    lambda hlambda history x]
  exact Real.log_mul
    (regularizedFeatureGram_det_ne_zero lambda hlambda history)
    (ne_of_gt (regularizedFeatureGram_rankOne_update_factor_pos
      lambda hlambda history x))

/-- Logarithmic one-step determinant recursion for regularized prefix Grams. -/
theorem log_det_regularizedPrefixFeatureGram_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    Real.log (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det =
      Real.log (regularizedPrefixFeatureGram lambda history T).det +
        Real.log (1 + dotProduct x
          (Matrix.mulVec
            ((regularizedPrefixFeatureGram lambda history T)⁻¹) x)) := by
  rw [det_regularizedPrefixFeatureGram_add_rankOneGram
    lambda hlambda history T x]
  exact Real.log_mul
    (regularizedPrefixFeatureGram_det_ne_zero lambda hlambda history T)
    (ne_of_gt (regularizedPrefixFeatureGram_rankOne_update_factor_pos
      lambda hlambda history T x))

/-- Increment form of the logarithmic determinant recursion. -/
theorem log_det_regularizedFeatureGram_add_rankOneGram_sub
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Time -> Feature -> Real) (x : Feature -> Real) :
    Real.log (regularizedFeatureGram lambda history + rankOneGram x).det -
        Real.log (regularizedFeatureGram lambda history).det =
      Real.log (1 + dotProduct x
        (Matrix.mulVec ((regularizedFeatureGram lambda history)⁻¹) x)) := by
  rw [log_det_regularizedFeatureGram_add_rankOneGram
    lambda hlambda history x]
  ring

/-- Increment form of the logarithmic determinant recursion for prefix Grams. -/
theorem log_det_regularizedPrefixFeatureGram_add_rankOneGram_sub
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) (x : Feature -> Real) :
    Real.log (regularizedPrefixFeatureGram lambda history T + rankOneGram x).det -
        Real.log (regularizedPrefixFeatureGram lambda history T).det =
      Real.log (1 + dotProduct x
        (Matrix.mulVec
          ((regularizedPrefixFeatureGram lambda history T)⁻¹) x)) := by
  rw [log_det_regularizedPrefixFeatureGram_add_rankOneGram
    lambda hlambda history T x]
  ring

/-- Determinant recursion for the concrete prefix update `T -> T + 1`. -/
theorem det_regularizedPrefixFeatureGram_succ
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) :
    (regularizedPrefixFeatureGram lambda history (T + 1)).det =
      (regularizedPrefixFeatureGram lambda history T).det *
        (1 + dotProduct (history T)
          (Matrix.mulVec
            ((regularizedPrefixFeatureGram lambda history T)⁻¹)
            (history T))) := by
  rw [regularizedPrefixFeatureGram_succ]
  exact det_regularizedPrefixFeatureGram_add_rankOneGram
    lambda hlambda history T (history T)

/-- Log-det increment recursion for the concrete prefix update `T -> T + 1`. -/
theorem log_det_regularizedPrefixFeatureGram_succ_sub
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) :
    Real.log (regularizedPrefixFeatureGram lambda history (T + 1)).det -
        Real.log (regularizedPrefixFeatureGram lambda history T).det =
      Real.log (1 + dotProduct (history T)
        (Matrix.mulVec
          ((regularizedPrefixFeatureGram lambda history T)⁻¹)
          (history T))) := by
  rw [regularizedPrefixFeatureGram_succ]
  exact log_det_regularizedPrefixFeatureGram_add_rankOneGram_sub
    lambda hlambda history T (history T)

/-- Finite forward-difference telescope used by log-det recursions. -/
theorem sum_range_forward_difference
    (Phi : Nat -> Real) (T : Nat) :
    (Finset.range T).sum (fun t => Phi (t + 1) - Phi t) =
      Phi T - Phi 0 := by
  induction T with
  | zero => simp
  | succ T ih =>
      rw [Finset.sum_range_succ, ih]
      ring

/--
Abstract finite-horizon log-det telescope from one-step log-update factors.

This packages the shape needed after instantiating `detSeq` with an OFUL
regularized Gram determinant process and `factor` with the corresponding
rank-one update factor.
-/
theorem sum_range_log_update_factor_eq_log_det_ratio
    (detSeq factor : Nat -> Real) (T : Nat)
    (hstep : forall t : Nat, t < T ->
      Real.log (detSeq (t + 1)) - Real.log (detSeq t) =
        Real.log (factor t)) :
    (Finset.range T).sum (fun t => Real.log (factor t)) =
      Real.log (detSeq T) - Real.log (detSeq 0) := by
  calc
    (Finset.range T).sum (fun t => Real.log (factor t)) =
      (Finset.range T).sum
        (fun t => Real.log (detSeq (t + 1)) - Real.log (detSeq t)) := by
      apply Finset.sum_congr rfl
      intro t ht
      exact (hstep t (Finset.mem_range.mp ht)).symm
    _ = Real.log (detSeq T) - Real.log (detSeq 0) := by
      exact sum_range_forward_difference
        (fun t => Real.log (detSeq t)) T

/--
Concrete finite-horizon log-det telescope for Nat-prefix regularized Grams.

This is the growing-history instantiation of the abstract telescope.  It does
not prove any determinant-growth upper bound for the resulting ratio.
-/
theorem sum_range_log_regularizedPrefixFeatureGram_update_factor_eq_log_det_ratio
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (history : Nat -> Feature -> Real) (T : Nat) :
    (Finset.range T).sum
        (fun t => Real.log (1 + dotProduct (history t)
          (Matrix.mulVec
            ((regularizedPrefixFeatureGram lambda history t)⁻¹)
            (history t)))) =
      Real.log (regularizedPrefixFeatureGram lambda history T).det -
        Real.log (regularizedPrefixFeatureGram lambda history 0).det := by
  exact sum_range_log_update_factor_eq_log_det_ratio
    (fun t => (regularizedPrefixFeatureGram lambda history t).det)
    (fun t => 1 + dotProduct (history t)
      (Matrix.mulVec
        ((regularizedPrefixFeatureGram lambda history t)⁻¹)
        (history t)))
    T
    (fun t _ht =>
      log_det_regularizedPrefixFeatureGram_succ_sub
        lambda hlambda history t)

end OFUL
end BanditRLProof
