import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Analysis.Matrix.PosDef
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Real.Basic
import Mathlib.LinearAlgebra.Matrix.SchurComplement
import Mathlib.Tactic.Ring

/-!
# OFUL elliptical-potential linear algebra wrappers

This module records the first deterministic finite-dimensional linear-algebra
surface needed by OFUL/LinUCB routes.  It packages rank-one feature Gram
matrices and finite-history Gram matrices, then proves their quadratic forms
are squares or sums of squares.  It also exposes the determinant and
invertibility side condition for the scalar regularization base used in OFUL
Gram recursions.

It does not prove log-determinant telescoping, determinant growth inequalities,
self-normalized concentration, confidence ellipsoids, or an OFUL regret theorem.
-/

namespace BanditRLProof
namespace OFUL

universe u v

/-- Rank-one Gram matrix generated by one feature vector. -/
def rankOneGram {Feature : Type u}
    (x : Feature -> Real) : Matrix Feature Feature Real :=
  fun i j => x i * x j

/-- The local rank-one Gram matrix is Mathlib's column-row product shape. -/
theorem rankOneGram_eq_replicateCol_mul_replicateRow
    {Feature : Type u} [Fintype Feature]
    (x : Feature -> Real) :
    rankOneGram x =
      Matrix.replicateCol Unit x * Matrix.replicateRow Unit x := by
  ext i j
  simp [rankOneGram, Matrix.mul_apply]

/--
Rank-one determinant lemma at the identity, specialized to feature Gram
updates.
-/
theorem det_one_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (x : Feature -> Real) :
    (1 + rankOneGram x).det = 1 + dotProduct x x := by
  rw [rankOneGram_eq_replicateCol_mul_replicateRow]
  simpa using
    Matrix.det_one_add_replicateCol_mul_replicateRow (ι := Unit)
      (u := x) (v := x)

/--
The one-dimensional determinant factor in the rank-one matrix determinant
lemma is the scalar `1 + x^T A^{-1} x`.
-/
theorem det_rankOne_update_factor_eq_one_add_dotProduct_inv_mulVec
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (A : Matrix Feature Feature Real) (x : Feature -> Real) :
    (1 + Matrix.replicateRow Unit x * A⁻¹ *
        Matrix.replicateCol Unit x).det =
      1 + dotProduct x (Matrix.mulVec (A⁻¹) x) := by
  rw [Matrix.det_unique]
  simp [Matrix.mul_apply, dotProduct, Matrix.mulVec, Finset.sum_mul]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro i _hi
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j _hj
  ring

/--
Rank-one matrix determinant lemma in OFUL feature notation.

The invertibility side condition is kept as Mathlib's `IsUnit A.det`, matching
the upstream Schur-complement API.
-/
theorem det_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (A : Matrix Feature Feature Real) (hA : IsUnit A.det)
    (x : Feature -> Real) :
    (A + rankOneGram x).det =
      A.det * (1 + dotProduct x (Matrix.mulVec (A⁻¹) x)) := by
  rw [rankOneGram_eq_replicateCol_mul_replicateRow]
  rw [Matrix.det_add_replicateCol_mul_replicateRow (ι := Unit)
    (A := A) hA x x]
  rw [det_rankOne_update_factor_eq_one_add_dotProduct_inv_mulVec]

/-- Determinant of the scalar regularization matrix `lambda I`. -/
theorem det_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) :
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det =
      lambda ^ Fintype.card Feature := by
  rw [Matrix.scalar_apply]
  rw [Matrix.det_diagonal]
  simp

/-- Nonzero scalar regularization has nonzero determinant. -/
theorem det_scalar_identity_ne_zero
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) :
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det ≠ 0 := by
  rw [det_scalar_identity]
  exact pow_ne_zero _ hlambda

/--
Nonzero scalar regularization satisfies Mathlib's determinant-unit side
condition for the rank-one determinant update lemma.
-/
theorem isUnit_det_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) :
    IsUnit (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det := by
  exact IsUnit.mk0 _ (det_scalar_identity_ne_zero hlambda)

/--
First determinant update from the regularized scalar base `lambda I`.

This is the one-step OFUL/LinUCB determinant recursion specialized to the
empty-history base matrix.  General log-det telescoping and determinant-growth
bounds remain separate leaves.
-/
theorem det_scalar_add_rankOneGram
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    {lambda : Real} (hlambda : lambda ≠ 0) (x : Feature -> Real) :
    ((Matrix.scalar Feature lambda : Matrix Feature Feature Real) +
        rankOneGram x).det =
      (Matrix.scalar Feature lambda : Matrix Feature Feature Real).det *
        (1 + dotProduct x
          (Matrix.mulVec
            ((Matrix.scalar Feature lambda :
              Matrix Feature Feature Real)⁻¹) x)) := by
  exact det_add_rankOneGram
    (Matrix.scalar Feature lambda : Matrix Feature Feature Real)
    (isUnit_det_scalar_identity hlambda) x

/-- Quadratic form associated with a finite real matrix. -/
noncomputable def quadraticForm {Feature : Type u} [Fintype Feature]
    (A : Matrix Feature Feature Real) (y : Feature -> Real) : Real :=
  (Finset.univ : Finset Feature).sum
    (fun i => (Finset.univ : Finset Feature).sum
      (fun j => y i * A i j * y j))

/-- Quadratic forms distribute over matrix addition. -/
theorem quadraticForm_add
    {Feature : Type u} [Fintype Feature]
    (A B : Matrix Feature Feature Real) (y : Feature -> Real) :
    quadraticForm (A + B) y = quadraticForm A y + quadraticForm B y := by
  unfold quadraticForm
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * (A i j + B i j) * y j)) =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * A i j * y j + y i * B i j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i =>
          (Finset.univ : Finset Feature).sum
            (fun j => y i * A i j * y j) +
          (Finset.univ : Finset Feature).sum
            (fun j => y i * B i j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_add_distrib]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * A i j * y j)) +
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * B i j * y j)) := by
      rw [Finset.sum_add_distrib]

/-- The Mathlib dot-product/mulVec form agrees with the local quadratic form. -/
theorem dotProduct_mulVec_eq_quadraticForm
    {Feature : Type u} [Fintype Feature]
    (A : Matrix Feature Feature Real) (y : Feature -> Real) :
    dotProduct y (Matrix.mulVec A y) = quadraticForm A y := by
  simp [dotProduct, Matrix.mulVec, quadraticForm, Finset.mul_sum, mul_assoc]

/-- Quadratic form of the scalar regularization matrix `lambda I`. -/
theorem quadraticForm_scalar_identity
    {Feature : Type u} [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (y : Feature -> Real) :
    quadraticForm
        (Matrix.scalar Feature lambda : Matrix Feature Feature Real) y =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
  unfold quadraticForm
  rw [Matrix.scalar_apply]
  simp [Matrix.diagonal_apply]
  calc
    (Finset.univ : Finset Feature).sum
        (fun x => y x * lambda * y x) =
      (Finset.univ : Finset Feature).sum
        (fun x => lambda * y x ^ 2) := by
      apply Finset.sum_congr rfl
      intro x _hx
      ring
    _ =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
      rw [Finset.mul_sum]

/-- A finite sum of coordinate squares is positive for a nonzero vector. -/
theorem sum_sq_pos_of_exists_ne_zero
    {Feature : Type u} [Fintype Feature]
    (y : Feature -> Real) (hy : ∃ i : Feature, y i ≠ 0) :
    0 < (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) := by
  classical
  let i := Classical.choose hy
  have hi : y i ≠ 0 := Classical.choose_spec hy
  refine Finset.sum_pos' (fun j _hj => sq_nonneg (y j)) ?_
  exact Exists.intro i
    (And.intro (Finset.mem_univ i) (sq_pos_of_ne_zero hi))

/-- A nonzero vector has a nonzero coordinate. -/
theorem exists_coord_ne_zero_of_ne_zero
    {Feature : Type u} (y : Feature -> Real) (hy : y ≠ 0) :
    ∃ i : Feature, y i ≠ 0 := by
  by_contra h
  apply hy
  funext i
  by_contra hi
  exact h (Exists.intro i hi)

/-- Finite-history feature Gram matrix `sum_t x_t x_t^T`. -/
noncomputable def featureGram {Time : Type v} {Feature : Type u}
    [Fintype Time] (x : Time -> Feature -> Real) :
    Matrix Feature Feature Real :=
  fun i j => (Finset.univ : Finset Time).sum
    (fun t => x t i * x t j)

/-- Finite-history feature Gram matrices are Hermitian. -/
theorem featureGram_isHermitian
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) :
    (featureGram x).IsHermitian := by
  refine Matrix.IsHermitian.ext ?_
  intro i j
  simp [featureGram, mul_comm]

/-- Regularized finite-history Gram matrix `lambda I + sum_t x_t x_t^T`. -/
noncomputable def regularizedFeatureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    Matrix Feature Feature Real :=
  Matrix.scalar Feature lambda + featureGram x

/-- The named regularized Gram unfolds to scalar regularization plus Gram. -/
theorem regularizedFeatureGram_eq_scalar_add_featureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    regularizedFeatureGram lambda x =
      Matrix.scalar Feature lambda + featureGram x := by
  rfl

/-- Regularized finite-history feature Gram matrices are Hermitian. -/
theorem regularizedFeatureGram_isHermitian
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).IsHermitian := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  exact Matrix.IsHermitian.add (by
    rw [Matrix.scalar_apply]
    exact Matrix.isHermitian_diagonal _) (featureGram_isHermitian x)

/--
The quadratic form of a rank-one Gram matrix is the square of the projection
of the query vector onto the feature vector.
-/
theorem rankOneGram_quadraticForm_eq_sq
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    quadraticForm (rankOneGram x) y =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
  unfold quadraticForm rankOneGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => y i * (x i * x j) * y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (y i * x i) * (x j * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (y i * x i) *
          (Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.mul_sum]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      rw [Finset.sum_mul]
    _ =
      ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) *
        ((Finset.univ : Finset Feature).sum (fun j => x j * y j)) := by
      have hleft :
          ((Finset.univ : Finset Feature).sum (fun i => y i * x i)) =
            ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) := by
        apply Finset.sum_congr rfl
        intro i _hi
        ring
      rw [hleft]
    _ = ((Finset.univ : Finset Feature).sum (fun i => x i * y i)) ^ 2 := by
      ring

/-- Rank-one Gram matrices have nonnegative quadratic forms. -/
theorem rankOneGram_quadraticForm_nonneg
    {Feature : Type u} [Fintype Feature]
    (x y : Feature -> Real) :
    0 <= quadraticForm (rankOneGram x) y := by
  rw [rankOneGram_quadraticForm_eq_sq]
  exact sq_nonneg _

/--
The quadratic form of a finite-history Gram matrix is a finite sum of squared
feature projections.
-/
theorem featureGram_quadraticForm_eq_sum_sq
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    quadraticForm (featureGram x) y =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
  unfold quadraticForm featureGram
  calc
    (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j =>
            y i *
              ((Finset.univ : Finset Time).sum
                (fun t => x t i * x t j)) *
              y j))
        =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Feature).sum
          (fun j => (Finset.univ : Finset Time).sum
            (fun t => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      apply Finset.sum_congr rfl
      intro j _hj
      rw [Finset.mul_sum, Finset.sum_mul]
    _ =
      (Finset.univ : Finset Feature).sum
        (fun i => (Finset.univ : Finset Time).sum
          (fun t => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      apply Finset.sum_congr rfl
      intro i _hi
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t => (Finset.univ : Finset Feature).sum
          (fun i => (Finset.univ : Finset Feature).sum
            (fun j => y i * (x t i * x t j) * y j))) := by
      rw [Finset.sum_comm]
    _ =
      (Finset.univ : Finset Time).sum
        (fun t =>
          ((Finset.univ : Finset Feature).sum
            (fun i => x t i * y i)) ^ 2) := by
      apply Finset.sum_congr rfl
      intro t _ht
      simpa [quadraticForm, rankOneGram] using
        rankOneGram_quadraticForm_eq_sq (x := x t) (y := y)

/--
The regularized Gram quadratic form is the scalar regularization term plus the
finite-history Gram sum of squared feature projections.
-/
theorem regularizedFeatureGram_quadraticForm_eq_sum_sq
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (x : Time -> Feature -> Real) (y : Feature -> Real) :
    quadraticForm (regularizedFeatureGram lambda x) y =
      lambda * (Finset.univ : Finset Feature).sum (fun i => y i ^ 2) +
        (Finset.univ : Finset Time).sum
          (fun t =>
            ((Finset.univ : Finset Feature).sum
              (fun i => x t i * y i)) ^ 2) := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  rw [featureGram_quadraticForm_eq_sum_sq]

/-- Finite-history Gram matrices have nonnegative quadratic forms. -/
theorem featureGram_quadraticForm_nonneg
    {Time : Type v} {Feature : Type u} [Fintype Time] [Fintype Feature]
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    0 <= quadraticForm (featureGram x) y := by
  rw [featureGram_quadraticForm_eq_sum_sq]
  exact Finset.sum_nonneg (fun t _ht => sq_nonneg _)

/-- Regularized finite-history Gram matrices are PSD when `0 <= lambda`. -/
theorem regularizedFeatureGram_quadraticForm_nonneg
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 <= lambda)
    (x : Time -> Feature -> Real) (y : Feature -> Real) :
    0 <= quadraticForm (regularizedFeatureGram lambda x) y := by
  rw [regularizedFeatureGram_eq_scalar_add_featureGram]
  rw [quadraticForm_add]
  rw [quadraticForm_scalar_identity]
  exact add_nonneg
    (mul_nonneg hlambda (Finset.sum_nonneg (fun i _hi => sq_nonneg _)))
    (featureGram_quadraticForm_nonneg x y)

/--
Regularized finite-history Gram matrices have strictly positive quadratic
forms on nonzero vectors when `0 < lambda`.
-/
theorem regularizedFeatureGram_quadraticForm_pos_of_pos_lambda
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) (y : Feature -> Real)
    (hy : ∃ i : Feature, y i ≠ 0) :
    0 < quadraticForm (regularizedFeatureGram lambda x) y := by
  rw [regularizedFeatureGram_quadraticForm_eq_sum_sq]
  exact add_pos_of_pos_of_nonneg
    (mul_pos hlambda (sum_sq_pos_of_exists_ne_zero y hy))
    (Finset.sum_nonneg (fun t _ht => sq_nonneg _))

/-- Regularized finite-history Gram matrices are Mathlib-positive definite. -/
theorem regularizedFeatureGram_posDef
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).PosDef := by
  refine Matrix.PosDef.of_dotProduct_mulVec_pos
    (regularizedFeatureGram_isHermitian lambda x) ?_
  intro y hy
  have hstar : star y = y := by
    funext i
    simp
  rw [hstar]
  rw [dotProduct_mulVec_eq_quadraticForm]
  exact regularizedFeatureGram_quadraticForm_pos_of_pos_lambda
    lambda hlambda x y (exists_coord_ne_zero_of_ne_zero y hy)

/-- Regularized finite-history Gram matrices have positive determinant. -/
theorem regularizedFeatureGram_det_pos
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    0 < (regularizedFeatureGram lambda x).det := by
  exact Matrix.PosDef.det_pos (regularizedFeatureGram_posDef lambda hlambda x)

/-- Regularized finite-history Gram matrices have nonzero determinant. -/
theorem regularizedFeatureGram_det_ne_zero
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    (regularizedFeatureGram lambda x).det ≠ 0 := by
  exact ne_of_gt (regularizedFeatureGram_det_pos lambda hlambda x)

/--
Positive regularization supplies Mathlib's determinant-unit side condition for
arbitrary finite-history regularized Gram matrices.
-/
theorem isUnit_det_regularizedFeatureGram
    {Time : Type v} {Feature : Type u}
    [Fintype Time] [Fintype Feature] [DecidableEq Feature]
    (lambda : Real) (hlambda : 0 < lambda)
    (x : Time -> Feature -> Real) :
    IsUnit (regularizedFeatureGram lambda x).det := by
  exact IsUnit.mk0 _ (regularizedFeatureGram_det_ne_zero lambda hlambda x)

end OFUL
end BanditRLProof
