import BanditRLProof.TsallisFTRLExpectedStability
import BanditRLProof.Exp3SampledHistoryScore
import BanditRLProof.Exp3PredictableAdversary
import BanditRLProof.Exp3SampledHedge

/-!
# Recursive half-Tsallis trajectories

This module builds the pure half-Tsallis finite-history policy and its
Ionescu--Tulcea trajectory.  The only selector-specific input is coordinate
measurability of the canonical noncomputable minimizer for every measurable
finite-history score.  Simplex feasibility, score recursion, policy kernels,
and conditional action laws are constructed locally.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v

/-- Reusable regularity boundary for the noncomputable half-Tsallis selector.
It asks only that measurable finite-history score coordinates produce
measurable selected probability coordinates. -/
structure HalfTsallisFiniteHistorySelectorMeasurability
    {Action : Type u} [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) : Prop where
  measurable_selector :
    forall n
      (score : History.FinitePairHistory Action Real n -> Action -> Real),
      (forall action, action ∈ arms ->
        Measurable (fun history => score history action)) ->
      forall action, action ∈ arms ->
        Measurable (fun history =>
          halfTsallisMinimizer arms harms eta (score history) action)

/-- Initial pure half-Tsallis law, before any observed pair. -/
noncomputable def initialHalfTsallisDistribution
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) : Action -> Real :=
  halfTsallisMinimizer arms harms eta (fun _ => 0)

theorem finiteActionDistribution_initialHalfTsallisDistribution
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) :
    Exp3.FiniteActionDistribution arms
      (initialHalfTsallisDistribution arms harms eta) := by
  have hmin := halfTsallisMinimizer_isRegularizedMinimizer
    arms harms eta (fun _ => 0)
  exact {
    nonneg := hmin.1.1
    sum_eq_one := hmin.1.2
  }

/-- Cumulative importance-weighted score through an inclusive observed pair
history, using the pure half-Tsallis law generated by the previous score. -/
noncomputable def sampledHalfTsallisHistoryScore
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) :
    (n : Nat) -> History.FinitePairHistory Action Real n -> Action -> Real
  | 0, history, action =>
      Exp3.importanceWeightedLoss
        (initialHalfTsallisDistribution arms harms eta)
        (fun _ => (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).2)
        (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).1 action
  | n + 1, history, action =>
      let previous := Exp3.previousPairHistory history
      sampledHalfTsallisHistoryScore arms harms eta n previous action +
        Exp3.importanceWeightedLoss
          (halfTsallisMinimizer arms harms eta
            (sampledHalfTsallisHistoryScore arms harms eta n previous))
          (fun _ => (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).2)
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).1 action

@[simp]
theorem sampledHalfTsallisHistoryScore_zero
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (history : History.FinitePairHistory Action Real 0) (action : Action) :
    sampledHalfTsallisHistoryScore arms harms eta 0 history action =
      Exp3.importanceWeightedLoss
        (initialHalfTsallisDistribution arms harms eta)
        (fun _ => (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).2)
        (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).1 action :=
  rfl

@[simp]
theorem sampledHalfTsallisHistoryScore_succ
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (n : Nat) (history : History.FinitePairHistory Action Real (n + 1))
    (action : Action) :
    sampledHalfTsallisHistoryScore arms harms eta (n + 1) history action =
      sampledHalfTsallisHistoryScore arms harms eta n
          (Exp3.previousPairHistory history) action +
        Exp3.importanceWeightedLoss
          (halfTsallisMinimizer arms harms eta
            (sampledHalfTsallisHistoryScore arms harms eta n
              (Exp3.previousPairHistory history)))
          (fun _ => (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).2)
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).1 action :=
  rfl

/-- The generic selector contract makes the recursively accumulated score
measurable at every supported action coordinate. -/
theorem measurable_sampledHalfTsallisHistoryScore
    {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) :
    forall n action, action ∈ arms ->
      Measurable (fun history : History.FinitePairHistory Action Real n =>
        sampledHalfTsallisHistoryScore arms harms eta n history action) := by
  intro n
  induction n with
  | zero =>
      intro action _haction
      let zeroIndex : Finset.Iic 0 := ⟨0, Finset.mem_Iic.mpr le_rfl⟩
      have hchosen : Measurable
          (fun history : History.FinitePairHistory Action Real 0 =>
            (history zeroIndex).1) :=
        measurable_fst.comp (measurable_pi_apply zeroIndex)
      have hloss : Measurable
          (fun history : History.FinitePairHistory Action Real 0 =>
            (history zeroIndex).2) :=
        measurable_snd.comp (measurable_pi_apply zeroIndex)
      simpa [sampledHalfTsallisHistoryScore, zeroIndex] using
        (Exp3.measurable_observedImportanceWeightedLoss
          (fun _history : History.FinitePairHistory Action Real 0 =>
            initialHalfTsallisDistribution arms harms eta)
          (fun history => (history zeroIndex).1)
          (fun history => (history zeroIndex).2)
          action measurable_const hchosen hloss)
  | succ n ih =>
      intro action haction
      let lastIndex : Finset.Iic (n + 1) :=
        ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩
      have hprevious : Measurable
          (Exp3.previousPairHistory (Action := Action) (n := n)) :=
        Exp3.measurable_previousPairHistory
      have hscore : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            sampledHalfTsallisHistoryScore arms harms eta n
              (Exp3.previousPairHistory history) action) :=
        (ih action haction).comp hprevious
      have hprob : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            halfTsallisMinimizer arms harms eta
              (sampledHalfTsallisHistoryScore arms harms eta n
                (Exp3.previousPairHistory history)) action) :=
        (selector.measurable_selector n
          (sampledHalfTsallisHistoryScore arms harms eta n)
          (fun selected hselected => ih selected hselected)
          action haction).comp hprevious
      have hchosen : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            (history lastIndex).1) :=
        measurable_fst.comp (measurable_pi_apply lastIndex)
      have hloss : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            (history lastIndex).2) :=
        measurable_snd.comp (measurable_pi_apply lastIndex)
      have hincrement : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            Exp3.importanceWeightedLoss
              (halfTsallisMinimizer arms harms eta
                (sampledHalfTsallisHistoryScore arms harms eta n
                  (Exp3.previousPairHistory history)))
              (fun _ => (history lastIndex).2)
              (history lastIndex).1 action) :=
        Exp3.measurable_observedImportanceWeightedLoss
          (fun history =>
            halfTsallisMinimizer arms harms eta
              (sampledHalfTsallisHistoryScore arms harms eta n
                (Exp3.previousPairHistory history)))
          (fun history => (history lastIndex).1)
          (fun history => (history lastIndex).2)
          action hprob hchosen hloss
      simpa [sampledHalfTsallisHistoryScore, lastIndex] using
        hscore.add hincrement

/-- Pure half-Tsallis probabilities generated by the sampled score. -/
noncomputable def sampledHalfTsallisHistoryDistribution
    {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) (n : Nat) :
    History.FinitePairHistory Action Real n -> Action -> Real :=
  halfTsallisHistoryMinimizer arms harms eta
    (sampledHalfTsallisHistoryScore arms harms eta n)

/-- Measurable finite-action source for the recursively generated policy. -/
noncomputable def sampledHalfTsallisHistoryDistributionSource
    {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) (n : Nat) :
    Exp3.MeasurableFiniteActionDistribution arms
      (sampledHalfTsallisHistoryDistribution arms harms eta n) :=
  measurableFiniteActionDistribution_halfTsallisHistoryMinimizer
    arms harms eta (sampledHalfTsallisHistoryScore arms harms eta n)
    (fun action haction =>
      selector.measurable_selector n
        (sampledHalfTsallisHistoryScore arms harms eta n)
        (fun selected hselected =>
          measurable_sampledHalfTsallisHistoryScore arms harms eta selector n
            selected hselected)
        action haction)

/-- Stochastic finite-history algorithm generated by the recursive pure
half-Tsallis score. -/
noncomputable def sampledHalfTsallisHistoryAlgorithm
    {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) :
    Thompson.HistoryAlgorithm Action Real where
  policy n := Exp3.finiteActionKernel arms
    (sampledHalfTsallisHistoryDistribution arms harms eta n)
    (sampledHalfTsallisHistoryDistributionSource
      arms harms eta selector n)
  policy_isMarkov n := Exp3.instFiniteActionKernelIsMarkovKernel
    arms (sampledHalfTsallisHistoryDistribution arms harms eta n)
      (sampledHalfTsallisHistoryDistributionSource
        arms harms eta selector n)
  initialAction := Exp3.finiteActionMeasure arms
    (initialHalfTsallisDistribution arms harms eta)
  initialAction_isProbability := Exp3.finiteActionMeasure_isProbabilityMeasure
    arms (initialHalfTsallisDistribution arms harms eta)
      (finiteActionDistribution_initialHalfTsallisDistribution
        arms harms eta)

@[simp]
theorem sampledHalfTsallisHistoryAlgorithm_policy
    {Action : Type u}
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) (n : Nat) :
    (sampledHalfTsallisHistoryAlgorithm arms harms eta selector).policy n =
      Exp3.finiteActionKernel arms
        (sampledHalfTsallisHistoryDistribution arms harms eta n)
        (sampledHalfTsallisHistoryDistributionSource
          arms harms eta selector n) :=
  rfl

/-- Complete environment-indexed recursive pure half-Tsallis trajectory. -/
noncomputable def sampledHalfTsallisTrajectoryKernel
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action] [Nonempty Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real) :
    Kernel Env ((n : Nat) -> Action × Real) :=
  Thompson.canonicalMeasurableEnvironmentTrajectoryKernel
    (sampledHalfTsallisHistoryAlgorithm arms harms eta selector) environment

instance instSampledHalfTsallisTrajectoryKernelIsMarkov
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action] [Nonempty Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real) :
    IsMarkovKernel
      (sampledHalfTsallisTrajectoryKernel arms harms eta selector
        environment) := by
  unfold sampledHalfTsallisTrajectoryKernel
  infer_instance

/-- Every successor action has the recursive pure half-Tsallis finite-action
law conditional on its visible pair-history prefix. -/
theorem sampledHalfTsallisTrajectoryMeasure_condDistrib_action
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.2 (n + 1)).1)
        (fun sample => Preorder.frestrictLe n sample.2)
        (prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
          arms harms eta selector environment) =ᵐ[
      (prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
        arms harms eta selector environment).map
          (fun sample => Preorder.frestrictLe n sample.2)]
      Exp3.finiteActionKernel arms
        (sampledHalfTsallisHistoryDistribution arms harms eta n)
        (sampledHalfTsallisHistoryDistributionSource
          arms harms eta selector n) := by
  simpa [sampledHalfTsallisTrajectoryKernel,
    sampledHalfTsallisHistoryAlgorithm_policy] using
    (Thompson.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action
      prior (sampledHalfTsallisHistoryAlgorithm arms harms eta selector)
      environment n)

/-- The same conditional law after retaining the environment in the visible
history.  The policy kernel is comapped along the pair-history projection. -/
theorem sampledHalfTsallisTrajectoryMeasure_condDistrib_action_given_environment
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.2 (n + 1)).1)
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.1, Preorder.frestrictLe n sample.2))
        (prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
          arms harms eta selector environment) =ᵐ[
      (prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
        arms harms eta selector environment).map
          (fun sample : Env × ((k : Nat) -> Action × Real) =>
            (sample.1, Preorder.frestrictLe n sample.2))]
      (Exp3.finiteActionKernel arms
        (sampledHalfTsallisHistoryDistribution arms harms eta n)
        (sampledHalfTsallisHistoryDistributionSource
          arms harms eta selector n)).comap
        (fun input : Env × History.FinitePairHistory Action Real n => input.2)
        (measurable_snd : Measurable
          (fun input : Env × History.FinitePairHistory Action Real n =>
            input.2)) := by
  simpa [sampledHalfTsallisTrajectoryKernel,
    sampledHalfTsallisHistoryAlgorithm_policy] using
    (Exp3.trajectoryMixture_condDistrib_action_given_environment_history prior
      (sampledHalfTsallisTrajectoryKernel arms harms eta selector environment)
      (Preorder.frestrictLe n) (Preorder.measurable_frestrictLe n)
      (fun trajectory => (trajectory (n + 1)).1)
      (measurable_fst.comp (measurable_pi_apply (n + 1)))
      ((sampledHalfTsallisHistoryAlgorithm arms harms eta selector).policy n)
      (fun env =>
        Thompson.canonicalMeasurableEnvironmentTrajectoryKernel_map_history_action_eq_compProd
          (sampledHalfTsallisHistoryAlgorithm arms harms eta selector)
          environment env n))

/-- Visible environment/pair-history state before successor action `n + 1`. -/
def sampledHalfTsallisHistoryAt
    {Env : Type v} {Action : Type u}
    (n : Nat) (sample : Env × ((k : Nat) -> Action × Real)) :
    Env × History.FinitePairHistory Action Real n :=
  (sample.1, Preorder.frestrictLe n sample.2)

/-- Successor action sampled after the visible prefix through `n`. -/
def sampledHalfTsallisActionAt
    {Env : Type v} {Action : Type u}
    (n : Nat) (sample : Env × ((k : Nat) -> Action × Real)) : Action :=
  (sample.2 (n + 1)).1

/-- Recursive half-Tsallis score on an environment/prefix state. -/
noncomputable def sampledHalfTsallisScoreAt
    {Env : Type v} {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) (n : Nat) :
    Env × History.FinitePairHistory Action Real n -> Action -> Real :=
  fun input => sampledHalfTsallisHistoryScore arms harms eta n input.2

/-- Predictable successor loss vector on an environment/prefix state. -/
def sampledHalfTsallisPredictableLossAt
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [MeasurableSpace Action]
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    Env × History.FinitePairHistory Action Real n -> Action -> Real :=
  fun input => loss.successor n input.1 input.2

/-- Pure half-Tsallis probability on an environment/prefix state. -/
noncomputable def sampledHalfTsallisProbabilityAt
    {Env : Type v} {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) (n : Nat) :
    Env × History.FinitePairHistory Action Real n -> Action -> Real :=
  halfTsallisHistoryMinimizer arms harms eta
    (sampledHalfTsallisScoreAt arms harms eta n)

/-- Canonical sampled-action update on an environment/prefix state. -/
noncomputable def sampledHalfTsallisUpdatedAt
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    Env × History.FinitePairHistory Action Real n -> Action -> Action -> Real :=
  halfTsallisHistoryUpdatedMinimizer arms harms eta
    (sampledHalfTsallisScoreAt arms harms eta n)
    (sampledHalfTsallisPredictableLossAt loss n)

/-- The one-round stability score on visible history/action pairs. -/
noncomputable def sampledHalfTsallisHistoryActionStabilityAt
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    (Env × History.FinitePairHistory Action Real n) × Action -> Real :=
  importanceWeightedStabilityScore arms
    (sampledHalfTsallisProbabilityAt arms harms eta n)
    (sampledHalfTsallisPredictableLossAt loss n)
    (sampledHalfTsallisUpdatedAt arms harms eta loss n)

/-- The roundwise half-power budget on a visible history. -/
noncomputable def sampledHalfTsallisHalfPowerBoundAt
    {Env : Type v} {Action : Type u} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) (n : Nat) :
    Env × History.FinitePairHistory Action Real n -> Real :=
  halfPowerStabilityBound arms eta
    (sampledHalfTsallisProbabilityAt arms harms eta n)

/-- The actual displayed stability term with the next generated prefix's
current selector, rather than the sampled-action update notation. -/
noncomputable def sampledHalfTsallisSuccessorStabilityAt
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat)
    (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  let history := sampledHalfTsallisHistoryAt n sample
  let prob := sampledHalfTsallisProbabilityAt arms harms eta n history
  let estimatedLoss := Exp3.importanceWeightedLoss prob
    (sampledHalfTsallisPredictableLossAt loss n history)
    (sampledHalfTsallisActionAt n sample)
  FTRL.linearLoss arms prob estimatedLoss -
    FTRL.linearLoss arms
      (sampledHalfTsallisHistoryDistribution arms harms eta (n + 1)
        (Preorder.frestrictLe (n + 1) sample.2))
      estimatedLoss

/-- Environment-lifted measurable probability source at one prefix level. -/
noncomputable def sampledHalfTsallisEnvironmentHistoryDistributionSource
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) (n : Nat) :
    Exp3.MeasurableFiniteActionDistribution arms
      (sampledHalfTsallisProbabilityAt (Env := Env) arms harms eta n) := by
  let localSource := sampledHalfTsallisHistoryDistributionSource
    arms harms eta selector n
  exact {
    distribution := fun input => localSource.distribution input.2
    measurable_prob := fun action haction =>
      (localSource.measurable_prob action haction).comp measurable_snd
  }

/-- Algorithm policy comapped to the environment/prefix state. -/
noncomputable def sampledHalfTsallisPolicyAt
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) (n : Nat) :
    Kernel (Env × History.FinitePairHistory Action Real n) Action :=
  ((sampledHalfTsallisHistoryAlgorithm arms harms eta selector).policy n).comap
    (fun input : Env × History.FinitePairHistory Action Real n => input.2)
    measurable_snd

instance instSampledHalfTsallisPolicyAtIsMarkov
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta) (n : Nat) :
    IsMarkovKernel
      (sampledHalfTsallisPolicyAt (Env := Env)
        arms harms eta selector n) := by
  unfold sampledHalfTsallisPolicyAt
  infer_instance

/-- The recursive score on generated prefixes follows the predictable
importance-weighted update almost surely. -/
theorem sampledHalfTsallisScoreAt_succ_ae
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    (fun sample => sampledHalfTsallisHistoryScore arms harms eta (n + 1)
      (Preorder.frestrictLe (n + 1) sample.2)) =ᵐ[mu]
      (fun sample candidate =>
        sampledHalfTsallisHistoryScore arms harms eta n
            (Preorder.frestrictLe n sample.2) candidate +
          Exp3.importanceWeightedLoss
            (sampledHalfTsallisHistoryDistribution arms harms eta n
              (Preorder.frestrictLe n sample.2))
            (loss.successor n sample.1
              (Preorder.frestrictLe n sample.2))
            (sample.2 (n + 1)).1 candidate) := by
  dsimp only
  let algorithm := sampledHalfTsallisHistoryAlgorithm arms harms eta selector
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hreward :
      (fun sample : Env × ((k : Nat) -> Action × Real) =>
        (sample.2 (n + 1)).2) =ᵐ[mu]
      (fun sample => loss.successor n sample.1
        (Preorder.frestrictLe n sample.2) (sample.2 (n + 1)).1) := by
    simpa [mu, algorithm, sampledHalfTsallisTrajectoryKernel] using
      (Exp3.canonicalPredictableTrajectoryMeasure_reward_eq_successorLoss_ae
        prior algorithm loss n)
  filter_upwards [hreward] with sample hrewardSample
  funext candidate
  rw [sampledHalfTsallisHistoryScore_succ,
    Exp3.previousPairHistory_frestrictLe]
  unfold sampledHalfTsallisHistoryDistribution
  unfold halfTsallisHistoryMinimizer
  by_cases hchosen : (sample.2 (n + 1)).1 = candidate
  · simp [Exp3.importanceWeightedLoss, hchosen, hrewardSample]
  · simp [Exp3.importanceWeightedLoss, hchosen]

/--
Generated predictable-trajectory finite-horizon half-Tsallis stability.

The trajectory construction discharges the policy-kernel, conditional-law,
and successor-score-recursion obligations.  The remaining explicit inputs are
the canonical selector measurability contract and regularity of the updated
stability score under each generated history/action product law.
-/
theorem integral_sum_sampledHalfTsallisSuccessorStability_le_integral_sum_halfPowerStabilityBound
    {Env : Type v} {Action : Type u}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (horizon : Nat) (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta)
    (selector : HalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta)
    (loss : Exp3.PredictableLossVector Env Action)
    (hscore : forall n, Measurable
      (sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n))
    (hIntegrable : forall n, Integrable
      (sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n)
      ((prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
          arms harms eta selector loss.environment).map
          (sampledHalfTsallisHistoryAt n) ⊗ₘ
        sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n))
    (hboundIntegrable : forall n, Integrable
      (sampledHalfTsallisHalfPowerBoundAt (Env := Env)
        arms harms eta n)
      ((prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
          arms harms eta selector loss.environment).map
          (sampledHalfTsallisHistoryAt n))) :
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    integral mu (fun sample => (Finset.range horizon).sum (fun n =>
        sampledHalfTsallisSuccessorStabilityAt
          arms harms eta loss n sample)) <=
      integral mu (fun sample => (Finset.range horizon).sum (fun n =>
        sampledHalfTsallisHalfPowerBoundAt (Env := Env)
          arms harms eta n (sampledHalfTsallisHistoryAt n sample))) := by
  dsimp only
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hhistory (n : Nat) : Measurable
      (sampledHalfTsallisHistoryAt (Env := Env) (Action := Action) n) :=
    measurable_fst.prodMk
      ((Preorder.measurable_frestrictLe n).comp measurable_snd)
  have haction (n : Nat) : Measurable
      (sampledHalfTsallisActionAt (Env := Env) (Action := Action) n) := by
    exact measurable_fst.comp
      ((measurable_pi_apply (n + 1)).comp measurable_snd)
  have hpolicyEq (n : Nat) :
      sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n =
        Exp3.finiteActionKernel arms
          (sampledHalfTsallisProbabilityAt (Env := Env)
            arms harms eta n)
          (sampledHalfTsallisEnvironmentHistoryDistributionSource
            (Env := Env) arms harms eta selector n) := by
    ext input event hevent
    rw [sampledHalfTsallisPolicyAt, Kernel.comap_apply,
      sampledHalfTsallisHistoryAlgorithm_policy,
      Exp3.finiteActionKernel_apply, Exp3.finiteActionKernel_apply]
    rfl
  have hpolicy (n : Nat) :
      sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n =ᵐ[
        mu.map (sampledHalfTsallisHistoryAt n)]
        fun input => Exp3.finiteActionMeasure arms
          (sampledHalfTsallisProbabilityAt (Env := Env)
            arms harms eta n input) := by
    filter_upwards [] with input
    rw [hpolicyEq n, Exp3.finiteActionKernel_apply]
  have hcond (n : Nat) :
      condDistrib
          (sampledHalfTsallisActionAt (Env := Env) (Action := Action) n)
          (sampledHalfTsallisHistoryAt n) mu =ᵐ[
        mu.map (sampledHalfTsallisHistoryAt n)]
        sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n := by
    simpa [mu, sampledHalfTsallisHistoryAt, sampledHalfTsallisActionAt,
      sampledHalfTsallisPolicyAt] using
      (sampledHalfTsallisTrajectoryMeasure_condDistrib_action_given_environment
        prior arms harms eta selector loss.environment n)
  have hscoreComp : forall n, Integrable (fun sample =>
      sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n
        (sampledHalfTsallisHistoryAt n sample,
          sampledHalfTsallisActionAt n sample)) mu := by
    intro n
    exact
      integrable_importanceWeightedStabilityScore_comp_history_action_of_condDistrib
        mu (sampledHalfTsallisHistoryAt n) (hhistory n)
        (sampledHalfTsallisActionAt n) (haction n) arms
        (sampledHalfTsallisProbabilityAt (Env := Env)
          arms harms eta n)
        (sampledHalfTsallisPredictableLossAt loss n)
        (sampledHalfTsallisUpdatedAt arms harms eta loss n)
        (sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n)
        (hcond n) (hIntegrable n)
  have hboundComp : forall n, Integrable (fun sample =>
      sampledHalfTsallisHalfPowerBoundAt (Env := Env)
        arms harms eta n (sampledHalfTsallisHistoryAt n sample)) mu := by
    intro n
    exact integrable_halfPowerStabilityBound_comp_history
      mu (sampledHalfTsallisHistoryAt n) (hhistory n) arms eta
      (sampledHalfTsallisProbabilityAt (Env := Env)
        arms harms eta n) (hboundIntegrable n)
  have hround (n : Nat) :
      integral mu (fun sample =>
          sampledHalfTsallisHistoryActionStabilityAt
            arms harms eta loss n
            (sampledHalfTsallisHistoryAt n sample,
              sampledHalfTsallisActionAt n sample)) <=
        integral mu (fun sample =>
          sampledHalfTsallisHalfPowerBoundAt (Env := Env)
            arms harms eta n (sampledHalfTsallisHistoryAt n sample)) := by
    have h :=
      integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_condDistrib_of_minimizers
        mu (sampledHalfTsallisHistoryAt n) (hhistory n)
        (sampledHalfTsallisActionAt n) (haction n) arms eta
        (sampledHalfTsallisScoreAt arms harms eta n)
        (sampledHalfTsallisProbabilityAt (Env := Env)
          arms harms eta n)
        (sampledHalfTsallisPredictableLossAt loss n)
        (sampledHalfTsallisUpdatedAt arms harms eta loss n)
        (sampledHalfTsallisPolicyAt (Env := Env)
          arms harms eta selector n)
        (hpolicy n) (hcond n) heta
        (fun input => halfTsallisMinimizer_isRegularizedMinimizer
          arms harms eta (sampledHalfTsallisScoreAt arms harms eta n input))
        (fun input chosen _ =>
          halfTsallisUpdatedMinimizer_isRegularizedMinimizer
            arms harms eta
            (sampledHalfTsallisScoreAt arms harms eta n input)
            (sampledHalfTsallisPredictableLossAt loss n input) chosen)
        (fun input candidate _ =>
          loss.successor_mem_unitInterval n input.1 input.2 candidate)
        (hscore n) (hIntegrable n) (hboundIntegrable n)
    calc
      integral mu (fun sample =>
          sampledHalfTsallisHistoryActionStabilityAt
            arms harms eta loss n
            (sampledHalfTsallisHistoryAt n sample,
              sampledHalfTsallisActionAt n sample)) <=
        integral (mu.map (sampledHalfTsallisHistoryAt n))
          (sampledHalfTsallisHalfPowerBoundAt (Env := Env)
            arms harms eta n) := h
      _ = integral mu (fun sample =>
          sampledHalfTsallisHalfPowerBoundAt (Env := Env)
            arms harms eta n (sampledHalfTsallisHistoryAt n sample)) := by
        rw [integral_map (hhistory n).aemeasurable
          (hboundIntegrable n).aestronglyMeasurable]
  have hterm (n : Nat) :
      (fun sample => sampledHalfTsallisSuccessorStabilityAt
        arms harms eta loss n sample) =ᵐ[mu]
      (fun sample => sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n
        (sampledHalfTsallisHistoryAt n sample,
          sampledHalfTsallisActionAt n sample)) := by
    have hscoreSucc := sampledHalfTsallisScoreAt_succ_ae
      prior arms harms eta selector loss n
    dsimp only at hscoreSucc
    filter_upwards [hscoreSucc] with sample hscoreSuccSample
    have hnext :
        sampledHalfTsallisHistoryDistribution arms harms eta (n + 1)
            (Preorder.frestrictLe (n + 1) sample.2) =
          sampledHalfTsallisUpdatedAt arms harms eta loss n
            (sampledHalfTsallisHistoryAt n sample)
            (sampledHalfTsallisActionAt n sample) := by
      simp only [sampledHalfTsallisHistoryDistribution,
        sampledHalfTsallisUpdatedAt, halfTsallisHistoryMinimizer,
        halfTsallisHistoryUpdatedMinimizer, halfTsallisUpdatedMinimizer,
        sampledHalfTsallisScoreAt, sampledHalfTsallisPredictableLossAt,
        sampledHalfTsallisHistoryAt, sampledHalfTsallisActionAt]
      rw [hscoreSuccSample]
      rfl
    simp only [sampledHalfTsallisSuccessorStabilityAt,
      sampledHalfTsallisHistoryActionStabilityAt,
      importanceWeightedStabilityScore]
    rw [hnext]
  have htermAll : ∀ᵐ sample ∂mu, ∀ n,
      sampledHalfTsallisSuccessorStabilityAt
          arms harms eta loss n sample =
        sampledHalfTsallisHistoryActionStabilityAt
          arms harms eta loss n
          (sampledHalfTsallisHistoryAt n sample,
            sampledHalfTsallisActionAt n sample) := by
    rw [ae_all_iff]
    exact hterm
  calc
    integral mu (fun sample => (Finset.range horizon).sum (fun n =>
        sampledHalfTsallisSuccessorStabilityAt
          arms harms eta loss n sample)) =
      integral mu (fun sample => (Finset.range horizon).sum (fun n =>
        sampledHalfTsallisHistoryActionStabilityAt
          arms harms eta loss n
          (sampledHalfTsallisHistoryAt n sample,
            sampledHalfTsallisActionAt n sample))) := by
      apply integral_congr_ae
      filter_upwards [htermAll] with sample hsample
      exact Finset.sum_congr rfl fun n _ => hsample n
    _ = (Finset.range horizon).sum (fun n => integral mu (fun sample =>
        sampledHalfTsallisHistoryActionStabilityAt
          arms harms eta loss n
          (sampledHalfTsallisHistoryAt n sample,
            sampledHalfTsallisActionAt n sample))) := by
      exact ExpectationBochnerSums.integral_finset_sum mu
        (Finset.range horizon) (fun n sample =>
          sampledHalfTsallisHistoryActionStabilityAt
            arms harms eta loss n
            (sampledHalfTsallisHistoryAt n sample,
              sampledHalfTsallisActionAt n sample))
        (fun n _ => hscoreComp n)
    _ <= (Finset.range horizon).sum (fun n => integral mu (fun sample =>
        sampledHalfTsallisHalfPowerBoundAt (Env := Env)
          arms harms eta n (sampledHalfTsallisHistoryAt n sample))) := by
      exact Finset.sum_le_sum fun n _ => hround n
    _ = integral mu (fun sample => (Finset.range horizon).sum (fun n =>
        sampledHalfTsallisHalfPowerBoundAt (Env := Env)
          arms harms eta n (sampledHalfTsallisHistoryAt n sample))) := by
      symm
      exact ExpectationBochnerSums.integral_finset_sum mu
        (Finset.range horizon) (fun n sample =>
          sampledHalfTsallisHalfPowerBoundAt (Env := Env)
            arms harms eta n (sampledHalfTsallisHistoryAt n sample))
        (fun n _ => hboundComp n)

end Tsallis
end BanditRLProof
