import BanditRLProof.TsallisFTRLFiniteHorizonSelection
import BanditRLProof.Exp3ActionProcess

/-!
# One-round conditional transport for half-Tsallis stability

This module transports the compiled finite sampling-law half-Tsallis stability
bound through an identified conditional action law.  It also exposes a
canonical generated-action consumer for the fixed half-Tsallis minimizer.

The canonical minimizer is selected with `Classical.choose`.  Its coordinate
measurability, and measurability/integrability of the score involving the
chosen updated minimizer, remain explicit inputs rather than hidden claims.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v w

/-- The one-round FTRL stability score generated by an importance-weighted
loss estimate. -/
noncomputable def importanceWeightedStabilityScore
    {History : Type u} {Action : Type v}
    (arms : Finset Action)
    (prob loss : History -> Action -> Real)
    (next : History -> Action -> Action -> Real)
    (sample : History × Action) : Real :=
  FTRL.linearLoss arms (prob sample.1)
      (Exp3.importanceWeightedLoss
        (prob sample.1) (loss sample.1) sample.2) -
    FTRL.linearLoss arms (next sample.1 sample.2)
      (Exp3.importanceWeightedLoss
        (prob sample.1) (loss sample.1) sample.2)

/-- The pointwise half-Tsallis upper bound for the sampling-law averaged
one-round stability score. -/
noncomputable def halfPowerStabilityBound
    {History : Type u} {Action : Type v}
    (arms : Finset Action) (eta : Real)
    (prob : History -> Action -> Real) (history : History) : Real :=
  2 * eta * powerSum arms (1 / 2 : Real) (prob history)

/--
An identified finite conditional action law transports the pointwise
half-Tsallis minimizer stability theorem to a one-round integral inequality.

The score and bound integrability hypotheses are the exact analytic boundary
needed by Bochner integral monotonicity.  No measurability of a particular
minimizer selector is inferred here.
-/
theorem integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_condDistrib_of_minimizers
    {Omega : Type u} {History : Type v} {Action : Type w}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (eta : Real)
    (score prob loss : History -> Action -> Real)
    (next : History -> Action -> Action -> Real)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hpolicy : policy =ᵐ[mu.map history]
      fun h => Exp3.finiteActionMeasure arms (prob h))
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (heta : 0 < eta)
    (hprobMin : forall h,
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (score h) (prob h))
    (hnextMin : forall h chosen, chosen ∈ arms ->
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (fun candidate => score h candidate +
          Exp3.importanceWeightedLoss
            (prob h) (loss h) chosen candidate)
        (next h chosen))
    (hloss : forall h candidate, candidate ∈ arms ->
      0 <= loss h candidate ∧ loss h candidate <= 1)
    (hscore : Measurable
      (importanceWeightedStabilityScore arms prob loss next))
    (hIntegrable : Integrable
      (importanceWeightedStabilityScore arms prob loss next)
      (mu.map history ⊗ₘ policy))
    (hboundIntegrable : Integrable
      (halfPowerStabilityBound arms eta prob) (mu.map history)) :
    integral mu (fun omega =>
        importanceWeightedStabilityScore arms prob loss next
          (history omega, action omega)) <=
      integral (mu.map history) (halfPowerStabilityBound arms eta prob) := by
  have hdist : forall h, Exp3.FiniteActionDistribution arms (prob h) := by
    intro h
    exact {
      nonneg := (hprobMin h).1.1
      sum_eq_one := (hprobMin h).1.2
    }
  have htransport :=
    Exp3.integral_historyAction_eq_integral_sum_of_condDistrib_ae_eq_finiteActionMeasure
      mu history hhistory action haction arms prob hdist policy hpolicy hcond
      (importanceWeightedStabilityScore arms prob loss next)
      hscore hIntegrable
  have hsumEq :
      (fun h => integral (policy h) (fun chosen =>
        importanceWeightedStabilityScore arms prob loss next (h, chosen))) =ᵐ[
        mu.map history]
      fun h => arms.sum (fun chosen =>
        prob h chosen *
          importanceWeightedStabilityScore arms prob loss next (h, chosen)) := by
    filter_upwards [hpolicy] with h hh
    rw [hh, Exp3.integral_finiteActionMeasure_eq_sum
      arms (prob h) (hdist h)]
  have hsumIntegrable : Integrable (fun h => arms.sum (fun chosen =>
      prob h chosen *
        importanceWeightedStabilityScore arms prob loss next (h, chosen)))
      (mu.map history) :=
    hIntegrable.integral_compProd.congr hsumEq
  have hpoint : forall h,
      arms.sum (fun chosen => prob h chosen *
          importanceWeightedStabilityScore arms prob loss next (h, chosen)) <=
        halfPowerStabilityBound arms eta prob h := by
    intro h
    simpa [importanceWeightedStabilityScore, halfPowerStabilityBound] using
      sum_prob_mul_linearLoss_sub_next_importanceWeightedLoss_le_powerSum_half_of_minimizers
        arms eta (score h) (prob h) (loss h) (next h) heta
        (hprobMin h) (hnextMin h) (hloss h)
  calc
    integral mu (fun omega =>
        importanceWeightedStabilityScore arms prob loss next
          (history omega, action omega)) =
        integral (mu.map history) (fun h => arms.sum (fun chosen =>
          prob h chosen *
            importanceWeightedStabilityScore arms prob loss next
              (h, chosen))) := htransport
    _ <= integral (mu.map history)
        (halfPowerStabilityBound arms eta prob) :=
      integral_mono hsumIntegrable hboundIntegrable hpoint

/-- Generated finite-action process specialization of the conditional
half-Tsallis stability transport. -/
theorem actionProcess_integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_minimizers
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (eta : Real)
    (score prob loss : History -> Action -> Real)
    (next : History -> Action -> Action -> Real)
    (source : Exp3.MeasurableFiniteActionDistribution arms prob)
    (heta : 0 < eta)
    (hprobMin : forall h,
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (score h) (prob h))
    (hnextMin : forall h chosen, chosen ∈ arms ->
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (fun candidate => score h candidate +
          Exp3.importanceWeightedLoss
            (prob h) (loss h) chosen candidate)
        (next h chosen))
    (hloss : forall h candidate, candidate ∈ arms ->
      0 <= loss h candidate ∧ loss h candidate <= 1)
    (hscore : Measurable
      (importanceWeightedStabilityScore arms prob loss next))
    (hIntegrable : Integrable
      (importanceWeightedStabilityScore arms prob loss next)
      (historyMu ⊗ₘ Exp3.finiteActionKernel arms prob source))
    (hboundIntegrable : Integrable
      (halfPowerStabilityBound arms eta prob) historyMu) :
    integral (Exp3.actionProcessMeasure historyMu arms prob source)
        (importanceWeightedStabilityScore arms prob loss next) <=
      integral historyMu (halfPowerStabilityBound arms eta prob) := by
  have hhistory := Exp3.actionProcess_history_map_eq
    historyMu arms prob source
  have hresult :=
    integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_condDistrib_of_minimizers
      (Exp3.actionProcessMeasure historyMu arms prob source)
      Exp3.actionProcessHistory Exp3.actionProcessHistory_measurable
      Exp3.actionProcessAction Exp3.actionProcessAction_measurable
      arms eta score prob loss next
      (Exp3.finiteActionKernel arms prob source)
      (Exp3.finiteActionKernel_ae_eq_finiteActionMeasure
        ((Exp3.actionProcessMeasure historyMu arms prob source).map
          Exp3.actionProcessHistory) arms prob source)
      (Exp3.actionProcess_condDistrib_action_ae_eq_finiteActionKernel
        historyMu arms prob source)
      heta hprobMin hnextMin hloss hscore
      (by simpa [hhistory] using hIntegrable)
      (by simpa [hhistory] using hboundIntegrable)
  simpa [hhistory] using hresult

/-- The fixed half-Tsallis minimizer viewed as a history-indexed action
distribution. -/
noncomputable def halfTsallisHistoryMinimizer
    {History : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score : History -> Action -> Real) :
    History -> Action -> Real :=
  fun history => halfTsallisMinimizer arms harms eta (score history)

/-- The fixed importance-weighted half-Tsallis update viewed as a
history/action-indexed family. -/
noncomputable def halfTsallisHistoryUpdatedMinimizer
    {History : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score loss : History -> Action -> Real) :
    History -> Action -> Action -> Real :=
  fun history chosen =>
    halfTsallisUpdatedMinimizer arms harms eta
      (score history) (loss history) chosen

/-- Coordinate measurability is the only missing contract for turning the
fixed history-indexed minimizer into the project's finite-action kernel
source.  Distribution feasibility follows from the minimizer certificate. -/
noncomputable def measurableFiniteActionDistribution_halfTsallisHistoryMinimizer
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score : History -> Action -> Real)
    (hmeasurable : forall action, action ∈ arms -> Measurable (fun history =>
      halfTsallisHistoryMinimizer arms harms eta score history action)) :
    Exp3.MeasurableFiniteActionDistribution arms
      (halfTsallisHistoryMinimizer arms harms eta score) where
  distribution history := by
    have hmin := halfTsallisMinimizer_isRegularizedMinimizer
      arms harms eta (score history)
    exact {
      nonneg := hmin.1.1
      sum_eq_one := hmin.1.2
    }
  measurable_prob := hmeasurable

/--
Canonical generated-action one-round stability endpoint.

The minimizer certificates and finite-distribution laws are internal.  The
remaining caller contracts expose exactly what is not yet proved for the
`Classical.choose` selector: coordinate measurability and regularity of the
updated stability score.
-/
theorem actionProcess_integral_halfTsallisHistoryStability_le_integral_halfPowerStabilityBound
    {History : Type u} {Action : Type v}
    [MeasurableSpace History] [MeasurableSpace Action]
    [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (score loss : History -> Action -> Real)
    (hmeasurable : forall action, action ∈ arms -> Measurable (fun history =>
      halfTsallisHistoryMinimizer arms harms eta score history action))
    (heta : 0 < eta)
    (hloss : forall history candidate, candidate ∈ arms ->
      0 <= loss history candidate ∧ loss history candidate <= 1)
    (hscore : Measurable (importanceWeightedStabilityScore arms
      (halfTsallisHistoryMinimizer arms harms eta score) loss
      (halfTsallisHistoryUpdatedMinimizer arms harms eta score loss)))
    (hIntegrable : Integrable (importanceWeightedStabilityScore arms
      (halfTsallisHistoryMinimizer arms harms eta score) loss
      (halfTsallisHistoryUpdatedMinimizer arms harms eta score loss))
      (historyMu ⊗ₘ Exp3.finiteActionKernel arms
        (halfTsallisHistoryMinimizer arms harms eta score)
        (measurableFiniteActionDistribution_halfTsallisHistoryMinimizer
          arms harms eta score hmeasurable)))
    (hboundIntegrable : Integrable (halfPowerStabilityBound arms eta
      (halfTsallisHistoryMinimizer arms harms eta score)) historyMu) :
    integral (Exp3.actionProcessMeasure historyMu arms
        (halfTsallisHistoryMinimizer arms harms eta score)
        (measurableFiniteActionDistribution_halfTsallisHistoryMinimizer
          arms harms eta score hmeasurable))
      (importanceWeightedStabilityScore arms
        (halfTsallisHistoryMinimizer arms harms eta score) loss
        (halfTsallisHistoryUpdatedMinimizer arms harms eta score loss)) <=
      integral historyMu (halfPowerStabilityBound arms eta
        (halfTsallisHistoryMinimizer arms harms eta score)) := by
  exact
    actionProcess_integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_minimizers
      historyMu arms eta score
      (halfTsallisHistoryMinimizer arms harms eta score) loss
      (halfTsallisHistoryUpdatedMinimizer arms harms eta score loss)
      (measurableFiniteActionDistribution_halfTsallisHistoryMinimizer
        arms harms eta score hmeasurable)
      heta
      (fun history =>
        halfTsallisMinimizer_isRegularizedMinimizer
          arms harms eta (score history))
      (fun history chosen _ =>
        halfTsallisUpdatedMinimizer_isRegularizedMinimizer
          arms harms eta (score history) (loss history) chosen)
      hloss hscore hIntegrable hboundIntegrable

end Tsallis
end BanditRLProof
