import BanditRLProof.TsallisFiniteArmIIDTimeVaryingCorruptedRewardLaw
import BanditRLProof.TsallisScheduledIIDHistoryAdaptive
import BanditRLProof.TsallisScheduledReferenceGapSelfBounding

/-!
# History-adaptive corrupted finite-arm IID reward laws

The base reward vector is fresh IID at every round.  Before the current action
is sampled, a measurable arm-dependent reward shift may be selected from the
preceding finite pair history.  Shifted rewards are clipped to `[0, 1]`.  A
deterministic time-and-arm envelope controls the resulting baseline-gap
perturbation and therefore supplies the additive regret budget.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

/-- A predictable reward-shift process and its deterministic envelope. -/
structure FiniteArmIIDHistoryAdaptiveRewardShiftSource (K : Nat) where
  initial : Fin K -> Real
  successor : forall n,
    History.FinitePairHistory (Fin K) Real n -> Fin K -> Real
  measurable_successor : forall n, Measurable
    (fun input : History.FinitePairHistory (Fin K) Real n × Fin K =>
      successor n input.1 input.2)
  envelope : Nat -> Fin K -> Real
  envelope_nonneg : forall t arm, 0 <= envelope t arm
  initial_abs_le : forall arm, |initial arm| <= envelope 0 arm
  successor_abs_le : forall n history arm,
    |successor n history arm| <= envelope (n + 1) arm

/-- Projection to the real unit interval is measurable. -/
theorem measurable_clippedUnitReal : Measurable clippedUnitReal := by
  simpa only [clippedUnitReal] using
    (continuous_subtype_val.comp
      (continuous_projIcc (a := (0 : Real)) (b := 1)
        (h := zero_le_one))).measurable

theorem measurable_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_initial
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K) :
    Measurable (fun input : (Nat -> (Fin K -> Rat)) × Fin K =>
      finiteArmIIDStationaryCorruptedRewardVectorLoss source.initial
        (input.1 0) input.2) := by
  let Domain := (Nat -> (Fin K -> Rat)) × Fin K
  have hstate : Measurable (fun input : Domain => input.1 0) :=
    (measurable_pi_apply 0).comp measurable_fst
  have hstateAction : Measurable
      (fun input : Domain => (input.1 0, input.2)) :=
    hstate.prodMk measurable_snd
  have hbaseRewardPair : Measurable
      (fun input : (Fin K -> Rat) × Fin K =>
        clippedUnitReward (input.1 input.2)) := by
    exact measurable_of_countable _
  have hbaseReward : Measurable (fun input : Domain =>
      clippedUnitReward (input.1 0 input.2)) :=
    hbaseRewardPair.comp hstateAction
  have hshift : Measurable (fun input : Domain => source.initial input.2) :=
    (measurable_of_countable source.initial).comp measurable_snd
  simpa only [finiteArmIIDStationaryCorruptedRewardVectorLoss,
    finiteArmIIDStationaryCorruptedReward] using
    measurable_const.sub (measurable_clippedUnitReal.comp
      (hbaseReward.add hshift))

theorem measurable_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_successor
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (n : Nat) :
    Measurable (fun input : (Nat -> (Fin K -> Rat)) ×
        (History.FinitePairHistory (Fin K) Real n × Fin K) =>
      finiteArmIIDStationaryCorruptedRewardVectorLoss
        (source.successor n input.2.1) (input.1 (n + 1)) input.2.2) := by
  let Domain := (Nat -> (Fin K -> Rat)) ×
    (History.FinitePairHistory (Fin K) Real n × Fin K)
  have hstate : Measurable (fun input : Domain => input.1 (n + 1)) :=
    (measurable_pi_apply (n + 1)).comp measurable_fst
  have haction : Measurable (fun input : Domain => input.2.2) :=
    measurable_snd.comp measurable_snd
  have hstateAction : Measurable
      (fun input : Domain => (input.1 (n + 1), input.2.2)) :=
    hstate.prodMk haction
  have hbaseRewardPair : Measurable
      (fun input : (Fin K -> Rat) × Fin K =>
        clippedUnitReward (input.1 input.2)) := by
    exact measurable_of_countable _
  have hbaseReward : Measurable
      (fun input : Domain =>
        clippedUnitReward (input.1 (n + 1) input.2.2)) :=
    hbaseRewardPair.comp hstateAction
  have hshift : Measurable (fun input : Domain =>
      source.successor n input.2.1 input.2.2) :=
    (source.measurable_successor n).comp measurable_snd
  simpa only [finiteArmIIDStationaryCorruptedRewardVectorLoss,
    finiteArmIIDStationaryCorruptedReward] using
    measurable_const.sub (measurable_clippedUnitReal.comp
      (hbaseReward.add hshift))

/-- Predictable clipped loss generated by a history-adaptive reward shift. -/
noncomputable def finiteArmIIDHistoryAdaptiveCorruptedRewardLoss {K : Nat}
    (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K) :
    Exp3.PredictableLossVector (Nat -> (Fin K -> Rat)) (Fin K) where
  initial environment arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss source.initial
      (environment 0) arm
  successor n environment history arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss
      (source.successor n history) (environment (n + 1)) arm
  measurable_initial :=
    measurable_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_initial source
  measurable_successor n :=
    measurable_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_successor source n
  initial_nonneg environment arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss_nonneg source.initial
      (environment 0) arm
  initial_le_one environment arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss_le_one source.initial
      (environment 0) arm
  successor_nonneg n environment history arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss_nonneg
      (source.successor n history) (environment (n + 1)) arm
  successor_le_one n environment history arm :=
    finiteArmIIDStationaryCorruptedRewardVectorLoss_le_one
      (source.successor n history) (environment (n + 1)) arm

/-- The concrete history-adaptive loss reads no future IID state coordinate. -/
theorem finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_hasIIDStateCoordinateLocality
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K) :
    HasIIDStateCoordinateLocality
      (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source) := by
  constructor
  · intro environment1 environment2 arm hstate
    simp only [finiteArmIIDHistoryAdaptiveCorruptedRewardLoss]
    rw [hstate]
  · intro n environment1 environment2 history arm hstate
    simp only [finiteArmIIDHistoryAdaptiveCorruptedRewardLoss]
    rw [hstate]

@[simp]
theorem predictableLossAt_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_zero
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (sample : (Nat -> (Fin K -> Rat)) ×
      ((k : Nat) -> Fin K × Real)) (arm : Fin K) :
    Exp3.predictableLossAt
        (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source) 0 sample arm =
      finiteArmIIDStationaryCorruptedRewardVectorLoss source.initial
        (sample.1 0) arm := by
  rfl

@[simp]
theorem predictableLossAt_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_succ
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (n : Nat) (sample : (Nat -> (Fin K -> Rat)) ×
      ((k : Nat) -> Fin K × Real)) (arm : Fin K) :
    Exp3.predictableLossAt
        (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source) (n + 1)
          sample arm =
      finiteArmIIDStationaryCorruptedRewardVectorLoss
        (source.successor n (Preorder.frestrictLe n sample.2))
        (sample.1 (n + 1)) arm := by
  rfl

/-- Pointwise actual/reference gap deviation under the source envelope. -/
theorem abs_historyAdaptiveCorruptedPredictableLossDiff_sub_baseLossDiff_le
    {K : Nat} (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (t : Nat) (sample : (Nat -> (Fin K -> Rat)) ×
      ((k : Nat) -> Fin K × Real)) (best arm : Fin K) :
    |(Exp3.predictableLossAt
          (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source)
            t sample arm -
        Exp3.predictableLossAt
          (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source)
            t sample best) -
      (Exp3.predictableLossAt
          (iidLossStatePredictableLossVector finiteArmIIDRewardVectorLoss
            measurable_finiteArmIIDRewardVectorLoss
            finiteArmIIDRewardVectorLoss_nonneg
            finiteArmIIDRewardVectorLoss_le_one)
            t sample arm -
        Exp3.predictableLossAt
          (iidLossStatePredictableLossVector finiteArmIIDRewardVectorLoss
            measurable_finiteArmIIDRewardVectorLoss
            finiteArmIIDRewardVectorLoss_nonneg
            finiteArmIIDRewardVectorLoss_le_one)
            t sample best)| <=
      source.envelope t arm + source.envelope t best := by
  cases t with
  | zero =>
      calc
        _ <= |source.initial arm| + |source.initial best| := by
          simpa only [
            predictableLossAt_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_zero,
            predictableLossAt_iidLossStatePredictableLossVector] using
            abs_stationaryCorruptedLossDiff_sub_baseLossDiff_le
              source.initial (sample.1 0) best arm
        _ <= source.envelope 0 arm + source.envelope 0 best :=
          add_le_add (source.initial_abs_le arm)
            (source.initial_abs_le best)
  | succ n =>
      calc
        _ <= |source.successor n (Preorder.frestrictLe n sample.2) arm| +
            |source.successor n (Preorder.frestrictLe n sample.2) best| := by
          simpa only [
            predictableLossAt_finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_succ,
            predictableLossAt_iidLossStatePredictableLossVector] using
            abs_stationaryCorruptedLossDiff_sub_baseLossDiff_le
              (source.successor n (Preorder.frestrictLe n sample.2))
              (sample.1 (n + 1)) best arm
        _ <= source.envelope (n + 1) arm +
            source.envelope (n + 1) best :=
          add_le_add
            (source.successor_abs_le n
              (Preorder.frestrictLe n sample.2) arm)
            (source.successor_abs_le n
              (Preorder.frestrictLe n sample.2) best)

/-- Explicit deterministic envelope budget for predictable corruption. -/
noncomputable def finiteArmIIDHistoryAdaptiveRewardCorruptionBudget {K : Nat}
    (model : FiniteBanditModel K) (horizon : Nat)
    (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K) : Real :=
  scheduledTimeVaryingGapDeviationBudget
    (Finset.univ : Finset (Fin K)) model.bestArm horizon
    (fun t arm => source.envelope t arm + source.envelope t model.bestArm)

theorem finiteArmIIDHistoryAdaptiveRewardCorruptionBudget_eq {K : Nat}
    (model : FiniteBanditModel K) (horizon : Nat)
    (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K) :
    finiteArmIIDHistoryAdaptiveRewardCorruptionBudget model horizon source =
      (Finset.range (horizon + 1)).sum (fun t =>
        ((Finset.univ : Finset (Fin K)).erase model.bestArm).sum
          (fun arm =>
            source.envelope t arm + source.envelope t model.bestArm)) := by
  rfl

/-- The uncorrupted predictable shift source. -/
def zeroFiniteArmIIDHistoryAdaptiveRewardShiftSource (K : Nat) :
    FiniteArmIIDHistoryAdaptiveRewardShiftSource K where
  initial _ := 0
  successor _ _ _ := 0
  measurable_successor _ := measurable_const
  envelope _ _ := 0
  envelope_nonneg _ _ := le_rfl
  initial_abs_le _ := by simp
  successor_abs_le _ _ _ := by simp

@[simp]
theorem finiteArmIIDHistoryAdaptiveRewardCorruptionBudget_zero {K : Nat}
    (model : FiniteBanditModel K) (horizon : Nat) :
    finiteArmIIDHistoryAdaptiveRewardCorruptionBudget model horizon
      (zeroFiniteArmIIDHistoryAdaptiveRewardShiftSource K) = 0 := by
  simp [finiteArmIIDHistoryAdaptiveRewardCorruptionBudget,
    zeroFiniteArmIIDHistoryAdaptiveRewardShiftSource,
    scheduledTimeVaryingGapDeviationBudget]

/-- The actual history-adaptive canonical trajectory has the IID-prefix
factorization needed to reuse the uncorrupted reference gap law. -/
theorem hasScheduledIIDPrefixKernelFactorization_sampledScheduledHalfTsallisFiniteArmIIDHistoryAdaptiveTrajectoryKernel
    {K : Nat} [Nonempty (Fin K)]
    (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (arms : Finset (Fin K)) (harms : arms.Nonempty) (eta : Nat -> Real)
    (selector : HalfTsallisScheduleFiniteHistorySelectorMeasurability
      arms harms eta) (horizon : Nat) :
    HasScheduledIIDPrefixKernelFactorization
      (sampledScheduledHalfTsallisTrajectoryKernel
        arms harms eta selector
          (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source).environment)
      horizon := by
  exact
    hasScheduledIIDPrefixKernelFactorization_sampledScheduledHalfTsallisHistoryAdaptiveTrajectoryKernel
      (fun _ : Fin K => (0 : Rat))
      (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source)
      (finiteArmIIDHistoryAdaptiveCorruptedRewardLoss_hasIIDStateCoordinateLocality
        source)
      arms harms eta selector horizon

/-- Scheduled half-Tsallis logarithmic regret under a measurable predictable
history-adaptive reward shift.  The additive allowance is the deterministic
envelope budget packaged by `source`, not a free theorem parameter. -/
theorem integral_sampledScheduledHalfTsallisFiniteArmIIDHistoryAdaptiveCorruptedRewardLawRegret_le_log
    {K : Nat} (model : FiniteBanditModel K)
    (armLaw : Fin K -> Measure Rat)
    (hprob : forall arm, IsProbabilityMeasure (armLaw arm))
    (hbound : forall arm, ∀ᵐ reward ∂armLaw arm,
      ((reward : Rat) : Real) ∈ Set.Icc (0 : Real) 1)
    (hmean : forall arm,
      integral (armLaw arm) (fun reward : Rat => ((reward : Rat) : Real)) =
        ((model.mean arm : Rat) : Real))
    (source : FiniteArmIIDHistoryAdaptiveRewardShiftSource K)
    (hgapPos : forall arm, arm ≠ model.bestArm ->
      0 < ((model.gap arm : Rat) : Real))
    (horizon : Nat) :
    letI : Nonempty (Fin K) := ⟨model.bestArm⟩
    let law := finiteArmIIDRewardVectorLaw armLaw
    let loss := finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source
    let selector :=
      canonicalHalfTsallisScheduleGeneratedSelectorMeasurability
        (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
        sampledScheduledHalfTsallisSqrtSchedule loss
    let prior := Measure.infinitePi (fun _ : Nat => law)
    let mu := prior ⊗ₘ sampledScheduledHalfTsallisTrajectoryKernel
      (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
      sampledScheduledHalfTsallisSqrtSchedule
      selector.finiteHistory loss.environment
    integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
        (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
        sampledScheduledHalfTsallisSqrtSchedule loss
        (pointMass model.bestArm) horizon) <=
      (1 + Real.log (((horizon + 1 : Nat) : Real))) *
        (1 + 25 * ((Finset.univ : Finset (Fin K)).erase model.bestArm).sum
          (fun arm => 1 / ((model.gap arm : Rat) : Real))) +
        finiteArmIIDHistoryAdaptiveRewardCorruptionBudget
          model horizon source := by
  letI : Nonempty (Fin K) := ⟨model.bestArm⟩
  letI (arm : Fin K) : IsProbabilityMeasure (armLaw arm) := hprob arm
  let law := finiteArmIIDRewardVectorLaw armLaw
  letI : IsProbabilityMeasure law := by
    dsimp only [law, finiteArmIIDRewardVectorLaw]
    infer_instance
  let loss := finiteArmIIDHistoryAdaptiveCorruptedRewardLoss source
  let referenceLoss := iidLossStatePredictableLossVector
    (finiteArmIIDRewardVectorLoss (K := K))
    (measurable_finiteArmIIDRewardVectorLoss (K := K))
    (finiteArmIIDRewardVectorLoss_nonneg (K := K))
    (finiteArmIIDRewardVectorLoss_le_one (K := K))
  let arms : Finset (Fin K) := Finset.univ
  let harms : arms.Nonempty := Finset.univ_nonempty
  let eta := sampledScheduledHalfTsallisSqrtSchedule
  let selector := canonicalHalfTsallisScheduleGeneratedSelectorMeasurability
    arms harms eta loss
  let prior := Measure.infinitePi (fun _ : Nat => law)
  let trajectoryKernel := sampledScheduledHalfTsallisTrajectoryKernel
    arms harms eta selector.finiteHistory loss.environment
  let mu := prior ⊗ₘ trajectoryKernel
  let baseGap := fun arm : Fin K => ((model.gap arm : Rat) : Real)
  let deviation := fun (t : Nat) (arm : Fin K) =>
    source.envelope t arm + source.envelope t model.bestArm
  have hfactor : HasScheduledIIDPrefixKernelFactorization trajectoryKernel
      horizon := by
    simpa only [trajectoryKernel, selector, eta, loss] using
      hasScheduledIIDPrefixKernelFactorization_sampledScheduledHalfTsallisFiniteArmIIDHistoryAdaptiveTrajectoryKernel
        source arms harms eta selector.finiteHistory horizon
  have hindependent : HasScheduledIndependentMeanGapLaw
      mu arms referenceLoss model.bestArm
        (iidLossStateMeanGap law finiteArmIIDRewardVectorLoss model.bestArm)
      horizon := by
    simpa only [mu, prior, trajectoryKernel, referenceLoss, law] using
      hasScheduledIndependentMeanGapLaw_of_iidLossState
        law finiteArmIIDRewardVectorLoss
          measurable_finiteArmIIDRewardVectorLoss
          finiteArmIIDRewardVectorLoss_nonneg
          finiteArmIIDRewardVectorLoss_le_one
          arms model.bestArm horizon trajectoryKernel hfactor
  have hreferenceRaw : HasScheduledExpectedGapLaw
      mu arms harms eta referenceLoss model.bestArm
        (iidLossStateMeanGap law finiteArmIIDRewardVectorLoss model.bestArm)
      horizon :=
    hasScheduledExpectedGapLaw_of_independentMeanGapLaw
      mu arms harms eta referenceLoss model.bestArm
        (iidLossStateMeanGap law finiteArmIIDRewardVectorLoss model.bestArm)
        horizon hindependent
  have hgapEq : forall arm,
      iidLossStateMeanGap law finiteArmIIDRewardVectorLoss
          model.bestArm arm = baseGap arm := by
    intro arm
    simpa only [law, baseGap] using
      iidLossStateMeanGap_finiteArmIIDRewardVectorLoss_eq_gap
        model armLaw hprob hbound hmean arm
  have hreferenceGapLaw : HasScheduledExpectedGapLaw
      mu arms harms eta referenceLoss model.bestArm baseGap horizon := by
    intro t ht arm harm
    simpa only [hgapEq arm] using hreferenceRaw t ht arm harm
  have hdeviation : forall t, t <= horizon -> forall sample arm,
      arm ∈ arms.erase model.bestArm ->
      |(Exp3.predictableLossAt loss t sample arm -
            Exp3.predictableLossAt loss t sample model.bestArm) -
          (Exp3.predictableLossAt referenceLoss t sample arm -
            Exp3.predictableLossAt referenceLoss t sample model.bestArm)| <=
        deviation t arm := by
    intro t _ht sample arm _harm
    simpa only [loss, referenceLoss, deviation] using
      abs_historyAdaptiveCorruptedPredictableLossDiff_sub_baseLossDiff_le
        source t sample model.bestArm arm
  have hselfBounding :
      (Finset.range (horizon + 1)).sum (fun t =>
          (arms.erase model.bestArm).sum (fun arm =>
            baseGap arm * sampledScheduledHalfTsallisExpectedProbabilityAt
              mu arms harms eta t arm)) -
        scheduledTimeVaryingGapDeviationBudget
          arms model.bestArm horizon deviation <=
      integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss (pointMass model.bestArm) horizon) :=
    integral_sampledScheduledHalfTsallisPredictableEnvironmentRegret_hasSelfBounding_of_referenceExpectedGapLaw
      mu arms harms eta loss referenceLoss (Finset.mem_univ model.bestArm)
      baseGap deviation horizon hreferenceGapLaw hdeviation
  have hharmonic :=
    integral_sampledScheduledHalfTsallisPredictableEnvironmentRegret_pointMass_le_sqrtSchedule_of_selfBounding
      prior arms harms loss (Finset.mem_univ model.bestArm) horizon baseGap
      (fun arm harm => hgapPos arm (Finset.ne_of_mem_erase harm))
      (scheduledTimeVaryingGapDeviationBudget
        arms model.bestArm horizon deviation)
      (by simpa only [mu, trajectoryKernel, selector, eta] using hselfBounding)
  let gapFactor := 1 + 25 * (arms.erase model.bestArm).sum
    (fun arm => 1 / baseGap arm)
  have hgapSum : 0 <= (arms.erase model.bestArm).sum
      (fun arm => 1 / baseGap arm) := by
    apply Finset.sum_nonneg
    intro arm harm
    exact le_of_lt (one_div_pos.mpr
      (hgapPos arm (Finset.ne_of_mem_erase harm)))
  have hgapFactor : 0 <= gapFactor := by
    dsimp only [gapFactor]
    nlinarith
  have hbudget := sampledScheduledHalfTsallisHarmonicBudget_le_one_add_log
    horizon
  have hmul : sampledScheduledHalfTsallisHarmonicBudget horizon * gapFactor <=
      (1 + Real.log (((horizon + 1 : Nat) : Real))) * gapFactor :=
    mul_le_mul_of_nonneg_right hbudget hgapFactor
  dsimp only at hharmonic
  calc
    integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss (pointMass model.bestArm) horizon) <=
      sampledScheduledHalfTsallisHarmonicBudget horizon * gapFactor +
        scheduledTimeVaryingGapDeviationBudget
          arms model.bestArm horizon deviation := by
      simpa only [gapFactor, eta, baseGap] using hharmonic
    _ <= (1 + Real.log (((horizon + 1 : Nat) : Real))) * gapFactor +
        scheduledTimeVaryingGapDeviationBudget
          arms model.bestArm horizon deviation := by
      linarith
    _ = (1 + Real.log (((horizon + 1 : Nat) : Real))) *
        (1 + 25 * ((Finset.univ : Finset (Fin K)).erase model.bestArm).sum
          (fun arm => 1 / ((model.gap arm : Rat) : Real))) +
        finiteArmIIDHistoryAdaptiveRewardCorruptionBudget
          model horizon source := by
      rfl

end Tsallis
end BanditRLProof
