import BanditRLProof.TsallisScheduledTimeVaryingExpectedGap

/-!
# Reference-gap self-bounding for predictable perturbations

The action probabilities and regret are generated by `actualLoss`, while a
second predictable loss vector on the same trajectory supplies the stochastic
baseline gap law.  A pointwise bound between the two loss differences then
converts the reference expected-gap law into a self-bound for the actual
regret.  This is the generic bridge needed by history-adaptive corruption.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v

/-- A reference expected-gap law plus a pointwise predictable perturbation
bound yields the fixed-baseline self-bound for the actual generated regret. -/
theorem integral_sampledScheduledHalfTsallisPredictableEnvironmentRegret_hasSelfBounding_of_referenceExpectedGapLaw
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (mu : Measure (Env × ((k : Nat) -> Action × Real)))
    [IsProbabilityMeasure mu]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Nat -> Real)
    (actualLoss referenceLoss : Exp3.PredictableLossVector Env Action)
    {best : Action} (hbest : best ∈ arms)
    (baseGap : Action -> Real) (deviation : Nat -> Action -> Real)
    (horizon : Nat)
    (hreferenceGapLaw : HasScheduledExpectedGapLaw
      mu arms harms eta referenceLoss best baseGap horizon)
    (hdeviation : ∀ t, t <= horizon -> ∀ sample action,
      action ∈ arms.erase best ->
      |(Exp3.predictableLossAt actualLoss t sample action -
            Exp3.predictableLossAt actualLoss t sample best) -
          (Exp3.predictableLossAt referenceLoss t sample action -
            Exp3.predictableLossAt referenceLoss t sample best)| <=
        deviation t action) :
    (Finset.range (horizon + 1)).sum (fun t =>
        (arms.erase best).sum (fun action =>
          baseGap action * sampledScheduledHalfTsallisExpectedProbabilityAt
            mu arms harms eta t action)) -
      scheduledTimeVaryingGapDeviationBudget
        arms best horizon deviation <=
      integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
        arms harms eta actualLoss (pointMass best) horizon) := by
  have hactualIntegral :
      integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
          arms harms eta actualLoss (pointMass best) horizon) =
        (Finset.range (horizon + 1)).sum (fun t =>
          (arms.erase best).sum (fun action =>
            integral mu (fun sample =>
              sampledScheduledHalfTsallisProbabilityAtTime
                  arms harms eta t sample action *
                (Exp3.predictableLossAt actualLoss t sample action -
                  Exp3.predictableLossAt actualLoss t sample best)))) := by
    rw [integral_congr_ae (Filter.Eventually.of_forall fun sample =>
      sampledScheduledHalfTsallisPredictableEnvironmentRegret_pointMass_eq_weightedLossGapMass
        arms harms eta actualLoss hbest horizon sample)]
    rw [ExpectationBochnerSums.integral_finset_sum mu
      (Finset.range (horizon + 1))]
    · apply Finset.sum_congr rfl
      intro t _ht
      rw [ExpectationBochnerSums.integral_finset_sum mu (arms.erase best)]
      intro action haction
      exact
        integrable_sampledScheduledHalfTsallisProbability_mul_predictableLossDiffAt
          mu arms harms eta actualLoss best action
            (Finset.mem_of_mem_erase haction) t
    · intro t _ht
      exact IntegrabilitySums.integrable_finset_sum mu (arms.erase best)
        (fun action sample =>
          sampledScheduledHalfTsallisProbabilityAtTime
              arms harms eta t sample action *
            (Exp3.predictableLossAt actualLoss t sample action -
              Exp3.predictableLossAt actualLoss t sample best))
        (fun action haction =>
          integrable_sampledScheduledHalfTsallisProbability_mul_predictableLossDiffAt
            mu arms harms eta actualLoss best action
              (Finset.mem_of_mem_erase haction) t)
  have hcoordinate : ∀ t, t <= horizon -> ∀ action,
      action ∈ arms.erase best ->
      baseGap action * sampledScheduledHalfTsallisExpectedProbabilityAt
          mu arms harms eta t action - deviation t action <=
        integral mu (fun sample =>
          sampledScheduledHalfTsallisProbabilityAtTime
              arms harms eta t sample action *
            (Exp3.predictableLossAt actualLoss t sample action -
              Exp3.predictableLossAt actualLoss t sample best)) := by
    intro t ht action haction
    let probability := fun sample : Env × ((k : Nat) -> Action × Real) =>
      sampledScheduledHalfTsallisProbabilityAtTime
        arms harms eta t sample action
    let actualDiff := fun sample : Env × ((k : Nat) -> Action × Real) =>
      Exp3.predictableLossAt actualLoss t sample action -
        Exp3.predictableLossAt actualLoss t sample best
    let referenceDiff := fun sample : Env × ((k : Nat) -> Action × Real) =>
      Exp3.predictableLossAt referenceLoss t sample action -
        Exp3.predictableLossAt referenceLoss t sample best
    have hrefIntegrable : Integrable (probability * referenceDiff) mu := by
      simpa only [probability, referenceDiff] using
        integrable_sampledScheduledHalfTsallisProbability_mul_predictableLossDiffAt
          mu arms harms eta referenceLoss best action
            (Finset.mem_of_mem_erase haction) t
    have hactualIntegrable : Integrable (probability * actualDiff) mu := by
      simpa only [probability, actualDiff] using
        integrable_sampledScheduledHalfTsallisProbability_mul_predictableLossDiffAt
          mu arms harms eta actualLoss best action
            (Finset.mem_of_mem_erase haction) t
    have hpointwise : ∀ᵐ sample ∂mu,
        probability sample * referenceDiff sample - deviation t action <=
          probability sample * actualDiff sample := by
      filter_upwards [] with sample
      have hsimplex :=
        finiteSimplex_sampledScheduledHalfTsallisProbabilityAtTime
          arms harms eta t sample
      have hp0 : 0 <= probability sample :=
        hsimplex.1 action (Finset.mem_of_mem_erase haction)
      have hp1 : probability sample <= 1 :=
        finiteSimplex_apply_le_one hsimplex
          (Finset.mem_of_mem_erase haction)
      have habs : referenceDiff sample - actualDiff sample <=
          |actualDiff sample - referenceDiff sample| := by
        rw [abs_sub_comm]
        exact le_abs_self _
      have hweighted :
          (referenceDiff sample - actualDiff sample) * probability sample <=
            deviation t action := by
        calc
          (referenceDiff sample - actualDiff sample) * probability sample <=
              |actualDiff sample - referenceDiff sample| *
                probability sample :=
            mul_le_mul_of_nonneg_right habs hp0
          _ <= |actualDiff sample - referenceDiff sample| := by
            simpa using mul_le_of_le_one_right (abs_nonneg _) hp1
          _ <= deviation t action := by
            simpa only [actualDiff, referenceDiff] using
              hdeviation t ht sample action haction
      linarith
    have hmono := integral_mono_ae
      (hrefIntegrable.sub (integrable_const _))
      hactualIntegrable hpointwise
    change integral mu (fun sample =>
        probability sample * referenceDiff sample - deviation t action) <=
      integral mu (fun sample =>
        probability sample * actualDiff sample) at hmono
    have hsubIntegral :
        integral mu (fun sample =>
            probability sample * referenceDiff sample - deviation t action) =
          integral mu (fun sample =>
            probability sample * referenceDiff sample) -
          integral mu (fun _sample => deviation t action) := by
      simpa only [Pi.sub_apply, Pi.mul_apply] using
        integral_sub hrefIntegrable (integrable_const (μ := mu) _)
    rw [hsubIntegral] at hmono
    have hconst : integral mu (fun _sample => deviation t action) =
        deviation t action := by simp
    rw [hconst] at hmono
    have href : integral mu (fun sample =>
        probability sample * referenceDiff sample) =
        baseGap action * sampledScheduledHalfTsallisExpectedProbabilityAt
          mu arms harms eta t action := by
      simpa only [probability, referenceDiff, Pi.mul_apply] using
        hreferenceGapLaw t ht action haction
    rw [href] at hmono
    simpa only [probability, actualDiff, Pi.mul_apply] using hmono
  calc
    (Finset.range (horizon + 1)).sum (fun t =>
        (arms.erase best).sum (fun action =>
          baseGap action * sampledScheduledHalfTsallisExpectedProbabilityAt
            mu arms harms eta t action)) -
        scheduledTimeVaryingGapDeviationBudget
          arms best horizon deviation =
      (Finset.range (horizon + 1)).sum (fun t =>
        (arms.erase best).sum (fun action =>
          baseGap action * sampledScheduledHalfTsallisExpectedProbabilityAt
              mu arms harms eta t action - deviation t action)) := by
      simp [scheduledTimeVaryingGapDeviationBudget,
        Finset.sum_sub_distrib]
    _ <= (Finset.range (horizon + 1)).sum (fun t =>
        (arms.erase best).sum (fun action =>
          integral mu (fun sample =>
            sampledScheduledHalfTsallisProbabilityAtTime
                arms harms eta t sample action *
              (Exp3.predictableLossAt actualLoss t sample action -
                Exp3.predictableLossAt actualLoss t sample best)))) := by
      apply Finset.sum_le_sum
      intro t ht
      have ht' : t <= horizon :=
        Nat.lt_succ_iff.mp (Finset.mem_range.mp ht)
      apply Finset.sum_le_sum
      intro action haction
      exact hcoordinate t ht' action haction
    _ = integral mu (sampledScheduledHalfTsallisPredictableEnvironmentRegret
        arms harms eta actualLoss (pointMass best) horizon) :=
      hactualIntegral.symm

end Tsallis
end BanditRLProof
