import BanditRLProof.TsallisOracleRestartGeneratedDynamicRegret
import BanditRLProof.TsallisFiniteArmIndependentGlobalMeanSwitchCountDynamicRegret

/-!
# Oracle restart at global population-mean change points

This module builds a deterministic oracle schedule that restarts exactly after
each supplied change point.  It then specializes the change predicate to
population-mean changes of an independent finite-arm reward law.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v

/-- Start of the most recent epoch when a restart occurs after every `change`
boundary.  A true value at `s` starts the new epoch at `s + 1`. -/
def oracleChangePointRestartStart
    (change : Nat -> Prop) [DecidablePred change] : Nat -> Nat
  | 0 => 0
  | n + 1 =>
      if change n then n + 1 else oracleChangePointRestartStart change n

/-- A valid restart schedule generated by an arbitrary decidable boundary
predicate. -/
def oracleChangePointRestartSchedule
    (change : Nat -> Prop) [DecidablePred change] : OracleRestartSchedule where
  start := oracleChangePointRestartStart change
  start_zero := rfl
  start_le := by
    intro t
    induction t with
    | zero => simp [oracleChangePointRestartStart]
    | succ n ih =>
        simp only [oracleChangePointRestartStart]
        split <;> omega
  start_succ := by
    intro n
    by_cases hchange : change n
    · exact Or.inr (by simp [oracleChangePointRestartStart, hchange])
    · exact Or.inl (by simp [oracleChangePointRestartStart, hchange])

@[simp]
theorem oracleChangePointRestartSchedule_start_zero
    (change : Nat -> Prop) [DecidablePred change] :
    (oracleChangePointRestartSchedule change).start 0 = 0 := rfl

@[simp]
theorem oracleChangePointRestartSchedule_start_succ
    (change : Nat -> Prop) [DecidablePred change] (n : Nat) :
    (oracleChangePointRestartSchedule change).start (n + 1) =
      if change n then n + 1
      else (oracleChangePointRestartSchedule change).start n := rfl

/-- The registered epochs are zero together with every successor of a change
point before the inclusive horizon. -/
theorem oracleRestartScheduleEpochs_oracleChangePointRestartSchedule
    (change : Nat -> Prop) [DecidablePred change] (horizon : Nat) :
    oracleRestartScheduleEpochs
        (oracleChangePointRestartSchedule change) horizon =
      insert 0
        (((Finset.range horizon).filter change).image (fun s => s + 1)) := by
  induction horizon with
  | zero =>
      simp [oracleRestartScheduleEpochs,
        oracleChangePointRestartSchedule, oracleChangePointRestartStart]
  | succ horizon ih =>
      rw [oracleRestartScheduleEpochs]
      rw [show horizon + 1 + 1 = (horizon + 1) + 1 by omega]
      rw [Finset.range_add_one, Finset.image_insert]
      change
        insert
            ((oracleChangePointRestartSchedule change).start (horizon + 1))
            (oracleRestartScheduleEpochs
              (oracleChangePointRestartSchedule change) horizon) =
          _
      have hstartMem :
          (oracleChangePointRestartSchedule change).start horizon ∈
            insert 0
              (((Finset.range horizon).filter change).image
                (fun s => s + 1)) := by
        rw [← ih]
        exact oracleRestartSchedule_start_mem_epochs
          (oracleChangePointRestartSchedule change) horizon horizon (by simp)
      rw [ih]
      by_cases hchange : change horizon
      · simp [Finset.range_add_one, Finset.filter_insert,
          Finset.image_insert,
          oracleChangePointRestartSchedule_start_succ, hchange,
          Finset.insert_comm]
      · simp [Finset.range_add_one, Finset.filter_insert,
          oracleChangePointRestartSchedule_start_succ, hchange, hstartMem]

/-- A change-point restart schedule has exactly one more visited epoch than
the number of change boundaries before the inclusive horizon. -/
theorem oracleRestartScheduleEpochs_card_oracleChangePointRestartSchedule
    (change : Nat -> Prop) [DecidablePred change] (horizon : Nat) :
    (oracleRestartScheduleEpochs
        (oracleChangePointRestartSchedule change) horizon).card =
      ((Finset.range horizon).filter change).card + 1 := by
  rw [oracleRestartScheduleEpochs_oracleChangePointRestartSchedule]
  rw [Finset.card_insert_of_notMem]
  · rw [Finset.card_image_of_injective]
    intro s t hst
    exact Nat.add_right_cancel hst
  · simp

/-- A boundary has a global population-mean change when at least one arm
changes mean between its two adjacent reward laws. -/
def finiteArmIndependentGlobalMeanChangeAt {K : Nat}
    (armLaw : Nat -> Fin K -> Measure Rat) (s : Nat) : Prop :=
  ∃ arm : Fin K,
    finiteArmIndependentRewardMean armLaw (s + 1) arm ≠
      finiteArmIndependentRewardMean armLaw s arm

/-- Global population-mean change boundaries strictly before `horizon`. -/
noncomputable def finiteArmIndependentGlobalMeanChangeTimes {K : Nat}
    (armLaw : Nat -> Fin K -> Measure Rat) (horizon : Nat) : Finset Nat := by
  classical
  exact (Finset.range horizon).filter
    (finiteArmIndependentGlobalMeanChangeAt armLaw)

/-- Population-mean oracle schedule: restart immediately after every global
mean-change boundary. -/
noncomputable def finiteArmIndependentGlobalMeanChangeRestartSchedule
    {K : Nat} (armLaw : Nat -> Fin K -> Measure Rat) :
    OracleRestartSchedule := by
  classical
  exact oracleChangePointRestartSchedule
    (finiteArmIndependentGlobalMeanChangeAt armLaw)

/-- The population-mean restart schedule has exactly one initial epoch plus
one epoch for every global mean-change boundary. -/
theorem
    oracleRestartScheduleEpochs_card_finiteArmIndependentGlobalMeanChangeRestartSchedule
    {K : Nat} (armLaw : Nat -> Fin K -> Measure Rat) (horizon : Nat) :
    (oracleRestartScheduleEpochs
        (finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw)
        horizon).card =
      (finiteArmIndependentGlobalMeanChangeTimes armLaw horizon).card + 1 := by
  classical
  simpa [finiteArmIndependentGlobalMeanChangeRestartSchedule,
    finiteArmIndependentGlobalMeanChangeTimes,
    finiteArmIndependentGlobalMeanChangeAt] using
    (oracleRestartScheduleEpochs_card_oracleChangePointRestartSchedule
      (finiteArmIndependentGlobalMeanChangeAt armLaw) horizon)

/-- The existing real-valued global switch count is the coercion of the named
change-time finset cardinality. -/
theorem finiteArmIndependentCumulativeGlobalMeanSwitchCount_eq_changeTimes_card
    {K : Nat} (armLaw : Nat -> Fin K -> Measure Rat) (horizon : Nat) :
    finiteArmIndependentCumulativeGlobalMeanSwitchCount armLaw horizon =
      ((finiteArmIndependentGlobalMeanChangeTimes armLaw horizon).card : Real) := by
  classical
  have htimes :
      finiteArmIndependentGlobalMeanChangeTimes armLaw horizon =
        (Finset.range horizon).filter (fun s =>
          ∃ arm : Fin K,
            finiteArmIndependentRewardMean armLaw (s + 1) arm ≠
              finiteArmIndependentRewardMean armLaw s arm) := by
    ext s
    simp [finiteArmIndependentGlobalMeanChangeTimes,
      finiteArmIndependentGlobalMeanChangeAt]
  rw [finiteArmIndependentCumulativeGlobalMeanSwitchCount_eq_card, htimes]

/-- In real-valued form, the exact epoch count is the existing cumulative
global population-mean switch count plus one. -/
theorem
    oracleRestartScheduleEpochs_card_cast_finiteArmIndependentGlobalMeanChangeRestartSchedule
    {K : Nat} (armLaw : Nat -> Fin K -> Measure Rat) (horizon : Nat) :
    ((oracleRestartScheduleEpochs
        (finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw)
        horizon).card : Real) =
      finiteArmIndependentCumulativeGlobalMeanSwitchCount armLaw horizon + 1 := by
  classical
  rw [
    oracleRestartScheduleEpochs_card_finiteArmIndependentGlobalMeanChangeRestartSchedule,
    Nat.cast_add, Nat.cast_one,
    finiteArmIndependentCumulativeGlobalMeanSwitchCount_eq_changeTimes_card]

/-- Since every global mean change starts a new epoch, each arm's population
mean is constant from the current epoch start through the current round. -/
theorem
    finiteArmIndependentRewardMean_eq_globalMeanChangeRestartStart
    {K : Nat} (armLaw : Nat -> Fin K -> Measure Rat)
    (t : Nat) (arm : Fin K) :
    finiteArmIndependentRewardMean armLaw t arm =
      finiteArmIndependentRewardMean armLaw
        ((finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw).start t)
        arm := by
  classical
  induction t with
  | zero =>
      simp [finiteArmIndependentGlobalMeanChangeRestartSchedule,
        oracleChangePointRestartSchedule, oracleChangePointRestartStart]
  | succ n ih =>
      by_cases hchange :
          finiteArmIndependentGlobalMeanChangeAt armLaw n
      · simp [finiteArmIndependentGlobalMeanChangeRestartSchedule,
          oracleChangePointRestartSchedule, oracleChangePointRestartStart,
          hchange]
      · have hsame :
            finiteArmIndependentRewardMean armLaw (n + 1) arm =
              finiteArmIndependentRewardMean armLaw n arm := by
          apply not_ne_iff.mp
          intro hne
          exact hchange ⟨arm, hne⟩
        rw [hsame, ih]
        simp [finiteArmIndependentGlobalMeanChangeRestartSchedule,
          oracleChangePointRestartSchedule, oracleChangePointRestartStart,
          hchange]

/-- The arm maximizing population mean at the current epoch start remains a
population-mean maximizer at every round in that epoch. -/
theorem
    finiteArmIndependentRewardMean_le_globalMeanChangeRestartBestArm
    {K : Nat} (model : FiniteBanditModel K)
    (armLaw : Nat -> Fin K -> Measure Rat)
    (t : Nat) (arm : Fin K) :
    finiteArmIndependentRewardMean armLaw t arm <=
      finiteArmIndependentRewardMean armLaw t
        (finiteArmIndependentBestArmAt model armLaw
          ((finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw).start
            t)) := by
  rw [
    finiteArmIndependentRewardMean_eq_globalMeanChangeRestartStart
      armLaw t arm,
    finiteArmIndependentRewardMean_eq_globalMeanChangeRestartStart
      armLaw t
        (finiteArmIndependentBestArmAt model armLaw
          ((finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw).start
            t))]
  exact finiteArmIndependentRewardMean_le_bestArmAt
    model armLaw
      ((finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw).start t)
      arm

/-- Under unit support, the raw-population-mean oracle comparator is also
optimal for the clipped loss used by the generated trajectory. -/
theorem
    independentLossStateTimeVaryingMeanGap_globalMeanChangeRestartBestArm_nonneg
    {K : Nat} (model : FiniteBanditModel K)
    (armLaw : Nat -> Fin K -> Measure Rat)
    (hprob : forall t arm, IsProbabilityMeasure (armLaw t arm))
    (hbound : forall t arm, ∀ᵐ reward ∂armLaw t arm,
      ((reward : Rat) : Real) ∈ Set.Icc (0 : Real) 1)
    (t : Nat) (arm : Fin K) :
    0 <=
      independentLossStateTimeVaryingMeanGap
        (finiteArmIndependentRewardVectorLaw armLaw)
        (fun _ => finiteArmIIDRewardVectorLoss)
        t
        (finiteArmIndependentBestArmAt model armLaw
          ((finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw).start
            t))
        arm := by
  rw [
    independentLossStateTimeVaryingMeanGap_finiteArmIndependentRewardVectorLoss_eq_mean_sub
      armLaw hprob hbound]
  exact sub_nonneg.mpr
    (finiteArmIndependentRewardMean_le_globalMeanChangeRestartBestArm
      model armLaw t arm)

/-- The concrete independent reward law, restarted at every global
population-mean change, has generated expected dynamic regret bounded by the
square root of its exact population-mean switch count. The comparator selected
at each epoch start remains optimal for the clipped loss throughout that epoch
under the almost-sure unit-support contract. -/
theorem
    integral_sampledOracleRestartHalfTsallisFiniteArmIndependentGlobalMeanChangeDynamicRegret_le
    {K : Nat} (model : FiniteBanditModel K)
    (armLaw : Nat -> Fin K -> Measure Rat)
    (hprob : ∀ t arm, IsProbabilityMeasure (armLaw t arm))
    (hbound : ∀ t arm, ∀ᵐ reward ∂armLaw t arm,
      ((reward : Rat) : Real) ∈ Set.Icc (0 : Real) 1)
    (horizon : Nat) :
    letI : Nonempty (Fin K) := ⟨model.bestArm⟩
    let law := finiteArmIndependentRewardVectorLaw armLaw
    let value := fun _ : Nat => finiteArmIIDRewardVectorLoss
    let loss := iidTimeVaryingLossStatePredictableLossVector value
      (fun _ => measurable_finiteArmIIDRewardVectorLoss)
      (fun _ => finiteArmIIDRewardVectorLoss_nonneg)
      (fun _ => finiteArmIIDRewardVectorLoss_le_one)
    let schedule :=
      finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw
    let epochComparator :=
      finiteArmIndependentBestArmAt model armLaw
    let prior := Measure.infinitePi law
    let mu := prior ⊗ₘ
      sampledOracleRestartHalfTsallisTrajectoryKernel
        (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
        sampledScheduledHalfTsallisSqrtSchedule schedule loss.environment
    Integrable
        (sampledOracleRestartHalfTsallisPredictableMovingComparatorEnvironmentRegret
          (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
          sampledScheduledHalfTsallisSqrtSchedule schedule loss
          (fun t => epochComparator (schedule.start t)) horizon) mu ∧
      integral mu
          (sampledOracleRestartHalfTsallisPredictableMovingComparatorEnvironmentRegret
            (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
            sampledScheduledHalfTsallisSqrtSchedule schedule loss
            (fun t => epochComparator (schedule.start t)) horizon) <=
        (8 * Real.sqrt (K : Real)) *
            Real.sqrt
              (finiteArmIndependentCumulativeGlobalMeanSwitchCount
                armLaw horizon + 1) *
          Real.sqrt (((horizon + 1 : Nat) : Real)) := by
  letI : Nonempty (Fin K) := ⟨model.bestArm⟩
  letI (t : Nat) (arm : Fin K) :
      IsProbabilityMeasure (armLaw t arm) := hprob t arm
  letI (t : Nat) :
      IsProbabilityMeasure
        (finiteArmIndependentRewardVectorLaw armLaw t) := by
    rw [finiteArmIndependentRewardVectorLaw, finiteArmIIDRewardVectorLaw]
    infer_instance
  dsimp only
  let value : Nat -> (Fin K -> Rat) -> Fin K -> Real :=
    fun _ => finiteArmIIDRewardVectorLoss
  let loss := iidTimeVaryingLossStatePredictableLossVector value
    (fun _ => measurable_finiteArmIIDRewardVectorLoss)
    (fun _ => finiteArmIIDRewardVectorLoss_nonneg)
    (fun _ => finiteArmIIDRewardVectorLoss_le_one)
  let schedule :=
    finiteArmIndependentGlobalMeanChangeRestartSchedule armLaw
  let prior := Measure.infinitePi
    (finiteArmIndependentRewardVectorLaw armLaw)
  haveI : IsProbabilityMeasure prior := inferInstance
  have _hgapNonneg := fun t arm =>
    independentLossStateTimeVaryingMeanGap_globalMeanChangeRestartBestArm_nonneg
      model armLaw hprob hbound t arm
  have h :=
    integral_sampledOracleRestartHalfTsallisPredictableMovingComparatorEnvironmentRegret_sqrtSchedule_le_scheduleSqrt
      prior (Finset.univ : Finset (Fin K)) Finset.univ_nonempty
      schedule loss (finiteArmIndependentBestArmAt model armLaw) horizon
      (by
        intro epoch _hepoch
        exact Finset.mem_univ _)
  dsimp only at h ⊢
  rw [
    oracleRestartScheduleEpochs_card_cast_finiteArmIndependentGlobalMeanChangeRestartSchedule]
    at h
  simpa only [prior, schedule, loss, value, Finset.card_univ,
    Fintype.card_fin] using h

end Tsallis
end BanditRLProof
