import BanditRLProof.TsallisScheduledExpectedGapSelfBounding
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-!
# Conditional-mean producer for scheduled half-Tsallis expected gaps

This module exposes the sampling-before-action sigma-algebra at each scheduled
time.  The scheduled action probability is measurable with respect to that
sigma-algebra, so Mathlib's conditional-expectation pull-out theorem turns a
constant conditional loss-gap law into `HasScheduledExpectedGapLaw`.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v

/-- Information in the generated action/reward trace strictly before the
scheduled action at time `t`.  At time zero there is no trace information; at
time `n + 1` this is the sigma-algebra generated by the prefix through `n`. -/
@[reducible] def sampledScheduledHalfTsallisPastSigma
    {Env : Type u} {Action : Type v} [MeasurableSpace Action] (t : Nat) :
    MeasurableSpace (Env × ((k : Nat) -> Action × Real)) :=
  match t with
  | 0 => ⊥
  | n + 1 =>
      (inferInstance : MeasurableSpace
        (History.FinitePairHistory Action Real n)).comap
          (fun sample => Preorder.frestrictLe n sample.2)

/-- The scheduled past sigma-algebra is a sub-sigma-algebra of the ambient
trajectory sigma-algebra. -/
theorem sampledScheduledHalfTsallisPastSigma_le
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] (t : Nat) :
    sampledScheduledHalfTsallisPastSigma (Env := Env) (Action := Action) t <=
      (inferInstance : MeasurableSpace
        (Env × ((k : Nat) -> Action × Real))) := by
  cases t with
  | zero => exact bot_le
  | succ n =>
      exact ((Preorder.measurable_frestrictLe n).comp measurable_snd).comap_le

/-- Every scheduled action-probability coordinate is measurable using only the
trace prefix available before that action is sampled. -/
theorem measurable_sampledScheduledHalfTsallisProbabilityAtTime_pastSigma
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Nat -> Real)
    (t : Nat) (candidate : Action) (hcandidate : candidate ∈ arms) :
    @Measurable (Env × ((k : Nat) -> Action × Real)) Real
      (sampledScheduledHalfTsallisPastSigma
        (Env := Env) (Action := Action) t) inferInstance
      (fun sample => sampledScheduledHalfTsallisProbabilityAtTime
        arms harms eta t sample candidate) := by
  cases t with
  | zero => exact measurable_const
  | succ n =>
      exact
        (measurable_halfTsallisMinimizer_comp
          arms harms (eta (n + 1))
          (sampledScheduledHalfTsallisHistoryScore arms harms eta n)
          (fun selected hselected =>
            measurable_sampledScheduledHalfTsallisHistoryScore
              arms harms eta
              (canonicalHalfTsallisScheduleFiniteHistorySelectorMeasurability
                arms harms eta) n selected hselected)
          candidate hcandidate).comp
            (comap_measurable
              (fun sample : Env × ((k : Nat) -> Action × Real) =>
                Preorder.frestrictLe n sample.2))

/-- Coordinatewise conditional-mean gap law relative to the information
available before the scheduled action at each time. -/
def HasScheduledConditionalMeanGapLaw
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (mu : Measure (Env × ((k : Nat) -> Action × Real)))
    (arms : Finset Action) (loss : Exp3.PredictableLossVector Env Action)
    (best : Action) (gap : Action -> Real) (horizon : Nat) : Prop :=
  ∀ t, t <= horizon -> ∀ action, action ∈ arms.erase best ->
    condExp
        (sampledScheduledHalfTsallisPastSigma
          (Env := Env) (Action := Action) t)
        mu
        (fun sample =>
          Exp3.predictableLossAt loss t sample action -
            Exp3.predictableLossAt loss t sample best) =ᵐ[mu]
      fun _sample => gap action

/-- A constant conditional loss-gap law implies the expected-gap law consumed
by scheduled stochastic self-bounding.  The proof uses only Mathlib's pull-out
property and preservation of the integral by conditional expectation. -/
theorem hasScheduledExpectedGapLaw_of_conditionalMeanGapLaw
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (mu : Measure (Env × ((k : Nat) -> Action × Real)))
    [IsProbabilityMeasure mu]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Nat -> Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (best : Action) (gap : Action -> Real) (horizon : Nat)
    (hgap : HasScheduledConditionalMeanGapLaw
      mu arms loss best gap horizon) :
    HasScheduledExpectedGapLaw
      mu arms harms eta loss best gap horizon := by
  intro t ht action hactionErase
  have haction : action ∈ arms := Finset.mem_of_mem_erase hactionErase
  let probability := fun sample : Env × ((k : Nat) -> Action × Real) =>
    sampledScheduledHalfTsallisProbabilityAtTime
      arms harms eta t sample action
  let lossDiff := fun sample : Env × ((k : Nat) -> Action × Real) =>
    Exp3.predictableLossAt loss t sample action -
      Exp3.predictableLossAt loss t sample best
  have hm := sampledScheduledHalfTsallisPastSigma_le
    (Env := Env) (Action := Action) t
  have hprobability : StronglyMeasurable[
      sampledScheduledHalfTsallisPastSigma
        (Env := Env) (Action := Action) t] probability := by
    exact
      (measurable_sampledScheduledHalfTsallisProbabilityAtTime_pastSigma
        arms harms eta t action haction).stronglyMeasurable
  have hlossDiff : Integrable lossDiff mu := by
    exact (Exp3.integrable_predictableLossAt mu loss t action).sub
      (Exp3.integrable_predictableLossAt mu loss t best)
  have hproduct : Integrable (probability * lossDiff) mu := by
    simpa only [probability, lossDiff] using
      integrable_sampledScheduledHalfTsallisProbability_mul_predictableLossDiffAt
        mu arms harms eta loss best action haction t
  have hpull :
      condExp
          (sampledScheduledHalfTsallisPastSigma
            (Env := Env) (Action := Action) t)
          mu (probability * lossDiff) =ᵐ[mu]
        probability * condExp
          (sampledScheduledHalfTsallisPastSigma
            (Env := Env) (Action := Action) t)
          mu lossDiff :=
    condExp_mul_of_stronglyMeasurable_left
      hprobability hproduct hlossDiff
  have hconditional :
      condExp
          (sampledScheduledHalfTsallisPastSigma
            (Env := Env) (Action := Action) t)
          mu lossDiff =ᵐ[mu] fun _sample => gap action := by
    simpa only [lossDiff] using hgap t ht action hactionErase
  change integral mu (probability * lossDiff) =
    gap action * sampledScheduledHalfTsallisExpectedProbabilityAt
      mu arms harms eta t action
  calc
    integral mu (probability * lossDiff) =
        integral mu (condExp
          (sampledScheduledHalfTsallisPastSigma
            (Env := Env) (Action := Action) t)
          mu (probability * lossDiff)) := by
          symm
          exact integral_condExp hm
    _ = integral mu (probability * condExp
        (sampledScheduledHalfTsallisPastSigma
          (Env := Env) (Action := Action) t)
        mu lossDiff) :=
      integral_congr_ae hpull
    _ = integral mu (fun sample => probability sample * gap action) :=
      integral_congr_ae ((Filter.EventuallyEq.refl _ probability).mul hconditional)
    _ = gap action * integral mu probability := by
      rw [integral_mul_const]
      exact mul_comm _ _
    _ = gap action * sampledScheduledHalfTsallisExpectedProbabilityAt
        mu arms harms eta t action := by
      rfl

end Tsallis
end BanditRLProof
