import BanditRLProof.TsallisFTRLGeneratedMeasurability

/-!
# Estimated-to-environment regret for generated half-Tsallis FTRL

This module joins the deterministic half-Tsallis FTRL decomposition to the
generated predictable trajectory.  Time zero is kept separate: the recursive
history score at level `n` already contains observations through time `n`, so
the generated successor-stability theorem covers times `1, ..., horizon`.
-/

namespace BanditRLProof
namespace Tsallis

open MeasureTheory ProbabilityTheory

universe u v

/-- The pure half-Tsallis sampling probability at an actual trajectory time. -/
noncomputable def sampledHalfTsallisProbabilityAtTime
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) :
    Nat -> Env × ((k : Nat) -> Action × Real) -> Action -> Real
  | 0, _sample => initialHalfTsallisDistribution arms harms eta
  | n + 1, sample =>
      sampledHalfTsallisHistoryDistribution arms harms eta n
        (Preorder.frestrictLe n sample.2)

/-- The observed-scalar importance-weighted loss vector at an actual time. -/
noncomputable def sampledHalfTsallisObservedEstimatedLossAt
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (t : Nat) (sample : Env × ((k : Nat) -> Action × Real)) :
    Action -> Real :=
  Exp3.importanceWeightedLoss
    (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
    (fun _ => (sample.2 t).2) (sample.2 t).1

/-- The canonical cumulative selector generated by the observed estimator is
the actual pure half-Tsallis probability at the same time. -/
theorem cumulativeLoss_sampledHalfTsallisObservedEstimatedLossAt_succ
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (sample : Env × ((k : Nat) -> Action × Real)) (n : Nat) :
    FTRL.cumulativeLoss
        (fun t => sampledHalfTsallisObservedEstimatedLossAt
          arms harms eta t sample) (n + 1) =
      sampledHalfTsallisHistoryScore arms harms eta n
        (Preorder.frestrictLe n sample.2) := by
  induction n with
  | zero =>
      funext action
      simp [FTRL.cumulativeLoss_succ,
        sampledHalfTsallisObservedEstimatedLossAt,
        sampledHalfTsallisProbabilityAtTime]
  | succ n ih =>
      rw [FTRL.cumulativeLoss_succ]
      funext candidate
      change
        FTRL.cumulativeLoss
              (fun t => sampledHalfTsallisObservedEstimatedLossAt
                arms harms eta t sample) (n + 1) candidate +
            sampledHalfTsallisObservedEstimatedLossAt
              arms harms eta (n + 1) sample candidate = _
      rw [ih, sampledHalfTsallisHistoryScore_succ,
        Exp3.previousPairHistory_frestrictLe]
      rfl

theorem halfTsallisCumulativeMinimizer_observedEstimatedLoss_eq_probabilityAtTime
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (sample : Env × ((k : Nat) -> Action × Real)) (t : Nat) :
    halfTsallisCumulativeMinimizer arms harms eta
        (fun s => sampledHalfTsallisObservedEstimatedLossAt
          arms harms eta s sample) t =
      sampledHalfTsallisProbabilityAtTime arms harms eta t sample := by
  cases t with
  | zero =>
      rfl
  | succ n =>
      unfold halfTsallisCumulativeMinimizer
      rw [cumulativeLoss_sampledHalfTsallisObservedEstimatedLossAt_succ]
      rfl

/-- The time-zero current-minus-updated stability term. -/
noncomputable def sampledHalfTsallisInitialStability
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  let estimatedLoss := sampledHalfTsallisObservedEstimatedLossAt
    arms harms eta 0 sample
  FTRL.linearLoss arms (initialHalfTsallisDistribution arms harms eta)
      estimatedLoss -
    FTRL.linearLoss arms
      (sampledHalfTsallisHistoryDistribution arms harms eta 0
        (Preorder.frestrictLe 0 sample.2)) estimatedLoss

/-- The pathwise successor stability term formed from the scalar reward stored
in the generated trajectory. -/
noncomputable def sampledHalfTsallisObservedSuccessorStabilityAt
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (n : Nat) (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  let estimatedLoss := sampledHalfTsallisObservedEstimatedLossAt
    arms harms eta (n + 1) sample
  FTRL.linearLoss arms
      (sampledHalfTsallisHistoryDistribution arms harms eta n
        (Preorder.frestrictLe n sample.2)) estimatedLoss -
    FTRL.linearLoss arms
      (sampledHalfTsallisHistoryDistribution arms harms eta (n + 1)
        (Preorder.frestrictLe (n + 1) sample.2)) estimatedLoss

/-- Canonical time-zero update after sampling the initial action. -/
noncomputable def sampledHalfTsallisInitialUpdatedAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) :
    Env -> Action -> Action -> Real :=
  halfTsallisHistoryUpdatedMinimizer arms harms eta
    (fun _env _candidate => 0) loss.initial

/-- Canonical predictable stability score for the initial action. -/
noncomputable def sampledHalfTsallisInitialHistoryActionStability
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) : Env × Action -> Real :=
  importanceWeightedStabilityScore arms
    (fun _env => initialHalfTsallisDistribution arms harms eta)
    loss.initial
    (sampledHalfTsallisInitialUpdatedAt arms harms eta loss)

/-- The deterministic FTRL stability sum splits into the initial term and the
generated successor terms. -/
theorem sum_observedEstimated_stability_eq_initial_add_successor
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (sample : Env × ((k : Nat) -> Action × Real)) (horizon : Nat) :
    let estimatedLoss := fun t =>
      sampledHalfTsallisObservedEstimatedLossAt arms harms eta t sample
    let p := halfTsallisCumulativeMinimizer arms harms eta estimatedLoss
    (Finset.range (horizon + 1)).sum (fun t =>
        FTRL.linearLoss arms (p t) (estimatedLoss t) -
          FTRL.linearLoss arms (p (t + 1)) (estimatedLoss t)) =
      sampledHalfTsallisInitialStability arms harms eta sample +
        (Finset.range horizon).sum (fun n =>
          sampledHalfTsallisObservedSuccessorStabilityAt
            arms harms eta n sample) := by
  dsimp only
  rw [Finset.sum_range_succ']
  conv_lhs => rw [add_comm]
  congr 1
  · simp [sampledHalfTsallisInitialStability,
      sampledHalfTsallisProbabilityAtTime,
      halfTsallisCumulativeMinimizer_observedEstimatedLoss_eq_probabilityAtTime]
  · apply Finset.sum_congr rfl
    intro n hn
    rw [halfTsallisCumulativeMinimizer_observedEstimatedLoss_eq_probabilityAtTime,
      halfTsallisCumulativeMinimizer_observedEstimatedLoss_eq_probabilityAtTime]
    simp [sampledHalfTsallisObservedSuccessorStabilityAt,
      sampledHalfTsallisProbabilityAtTime]

/-- Pathwise estimated-loss regret decomposition for time zero followed by
`horizon` generated successor rounds. -/
theorem sampledHalfTsallis_observedEstimatedRegret_le
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (heta : 0 < eta) (q : Action -> Real)
    (hq : FTRL.finiteSimplex arms q)
    (sample : Env × ((k : Nat) -> Action × Real)) (horizon : Nat) :
    (Finset.range (horizon + 1)).sum (fun t =>
        FTRL.linearLoss arms
            (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
            (sampledHalfTsallisObservedEstimatedLossAt
              arms harms eta t sample) -
          FTRL.linearLoss arms q
            (sampledHalfTsallisObservedEstimatedLossAt
              arms harms eta t sample)) <=
      sampledHalfTsallisInitialStability arms harms eta sample +
        (Finset.range horizon).sum (fun n =>
          sampledHalfTsallisObservedSuccessorStabilityAt
            arms harms eta n sample) +
        ((powerSum arms (1 / 2 : Real)
              (initialHalfTsallisDistribution arms harms eta) -
            powerSum arms (1 / 2 : Real) q) /
          (1 - (1 / 2 : Real))) / eta := by
  let estimatedLoss := fun t =>
    sampledHalfTsallisObservedEstimatedLossAt arms harms eta t sample
  have hdecomp :=
    cumulativeLinearLoss_sub_comparator_le_stability_add_powerSumPenalty_half_canonical
      arms harms eta estimatedLoss q (horizon + 1) heta hq
  dsimp [estimatedLoss] at hdecomp
  rw [sum_observedEstimated_stability_eq_initial_add_successor
    arms harms eta sample horizon] at hdecomp
  simpa only
      [halfTsallisCumulativeMinimizer_observedEstimatedLoss_eq_probabilityAtTime]
    using hdecomp

/-- The predictable importance-weighted loss vector at an actual trajectory
time, using the same probability as the observed recursive update. -/
noncomputable def sampledHalfTsallisPredictableEstimatedLossAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (t : Nat) (sample : Env × ((k : Nat) -> Action × Real)) :
    Action -> Real :=
  Exp3.importanceWeightedLoss
    (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
    (Exp3.predictableLossAt loss t sample) (sample.2 t).1

/-- Estimated regret against a fixed comparator distribution, including time
zero and `horizon` successor rounds. -/
noncomputable def sampledHalfTsallisObservedEstimatedRegret
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (q : Action -> Real) (horizon : Nat)
    (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  (Finset.range (horizon + 1)).sum (fun t =>
    FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (sampledHalfTsallisObservedEstimatedLossAt
          arms harms eta t sample) -
      FTRL.linearLoss arms q
        (sampledHalfTsallisObservedEstimatedLossAt
          arms harms eta t sample))

/-- Predictable environment regret for the generated pure half-Tsallis
probabilities against a fixed comparator distribution. -/
noncomputable def sampledHalfTsallisPredictableEnvironmentRegret
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (horizon : Nat)
    (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  (Finset.range (horizon + 1)).sum (fun t =>
    FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (Exp3.predictableLossAt loss t sample) -
      FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample))

/-- The same finite-horizon estimated regret after replacing stored rewards by
their predictable loss-vector coordinates. -/
noncomputable def sampledHalfTsallisPredictableEstimatedRegret
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [MeasurableSpace Action] [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (horizon : Nat)
    (sample : Env × ((k : Nat) -> Action × Real)) : Real :=
  (Finset.range (horizon + 1)).sum (fun t =>
    FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (sampledHalfTsallisPredictableEstimatedLossAt
          arms harms eta loss t sample) -
      FTRL.linearLoss arms q
        (sampledHalfTsallisPredictableEstimatedLossAt
          arms harms eta loss t sample))

theorem measurable_sampledHalfTsallisProbabilityAtTime
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (t : Nat) (candidate : Action) (hcandidate : candidate ∈ arms) :
    Measurable (fun sample : Env × ((k : Nat) -> Action × Real) =>
      sampledHalfTsallisProbabilityAtTime
        arms harms eta t sample candidate) := by
  cases t with
  | zero => exact measurable_const
  | succ n =>
      exact
        (measurable_halfTsallisMinimizer_comp
          arms harms eta
          (sampledHalfTsallisHistoryScore arms harms eta n)
          (fun selected hselected =>
            measurable_sampledHalfTsallisHistoryScore
              arms harms eta
              (canonicalHalfTsallisFiniteHistorySelectorMeasurability
                arms harms eta) n selected hselected)
          candidate hcandidate).comp
            ((Preorder.measurable_frestrictLe n).comp measurable_snd)

theorem measurable_sampledHalfTsallisObservedEstimatedLossAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (t : Nat) (candidate : Action) (hcandidate : candidate ∈ arms) :
    Measurable (fun sample : Env × ((k : Nat) -> Action × Real) =>
      sampledHalfTsallisObservedEstimatedLossAt
        arms harms eta t sample candidate) := by
  unfold sampledHalfTsallisObservedEstimatedLossAt Exp3.importanceWeightedLoss
  refine Measurable.ite ?_
    ((measurable_snd.comp ((measurable_pi_apply t).comp measurable_snd)).div
      (measurable_sampledHalfTsallisProbabilityAtTime
        arms harms eta t candidate hcandidate)) measurable_const
  simpa only [Set.mem_setOf_eq] using
    (measurable_fst.comp ((measurable_pi_apply t).comp measurable_snd))
      (measurableSet_singleton candidate)

theorem measurable_sampledHalfTsallisPredictableEstimatedLossAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (t : Nat) (candidate : Action) (hcandidate : candidate ∈ arms) :
    Measurable (fun sample : Env × ((k : Nat) -> Action × Real) =>
      sampledHalfTsallisPredictableEstimatedLossAt
        arms harms eta loss t sample candidate) := by
  unfold sampledHalfTsallisPredictableEstimatedLossAt
    Exp3.importanceWeightedLoss
  refine Measurable.ite ?_
    ((Exp3.measurable_predictableLossAt loss t candidate).div
      (measurable_sampledHalfTsallisProbabilityAtTime
        arms harms eta t candidate hcandidate)) measurable_const
  simpa only [Set.mem_setOf_eq] using
    (measurable_fst.comp ((measurable_pi_apply t).comp measurable_snd))
      (measurableSet_singleton candidate)

/-- Deterministic predictable feedback identifies the observed estimator with
the corresponding predictable estimator almost surely at every actual time. -/
theorem sampledHalfTsallisObservedEstimatedLossAt_eq_predictable_ae
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (t : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    (fun sample => sampledHalfTsallisObservedEstimatedLossAt
      arms harms eta t sample) =ᵐ[mu]
      (fun sample => sampledHalfTsallisPredictableEstimatedLossAt
        arms harms eta loss t sample) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hreward :
      (fun sample : Env × ((k : Nat) -> Action × Real) =>
        (sample.2 t).2) =ᵐ[mu]
      (fun sample => Exp3.predictableLossAt loss t sample (sample.2 t).1) := by
    cases t with
    | zero =>
        simpa [mu, selector, sampledHalfTsallisTrajectoryKernel,
          Exp3.predictableLossAt] using
          (Exp3.canonicalPredictableTrajectoryMeasure_reward_zero_eq_initialLoss_ae
            prior
              (sampledHalfTsallisHistoryAlgorithm arms harms eta selector)
              loss)
    | succ n =>
        simpa [mu, selector, Exp3.predictableLossAt] using
          (Exp3.canonicalPredictableTrajectoryMeasure_reward_eq_successorLoss_ae
            prior
              (sampledHalfTsallisHistoryAlgorithm arms harms eta selector)
              loss n)
  filter_upwards [hreward] with sample hsample
  funext candidate
  unfold sampledHalfTsallisObservedEstimatedLossAt
    sampledHalfTsallisPredictableEstimatedLossAt
  by_cases hchosen : (sample.2 t).1 = candidate
  · simp [Exp3.importanceWeightedLoss, hchosen, hsample]
  · simp [Exp3.importanceWeightedLoss, hchosen]

theorem measurable_sampledHalfTsallisInitialUpdatedAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (candidate : Action) (hcandidate : candidate ∈ arms) :
    Measurable (fun sample : Env × Action =>
      sampledHalfTsallisInitialUpdatedAt
        arms harms eta loss sample.1 sample.2 candidate) := by
  let updatedScore : (Env × Action) -> Action -> Real :=
    fun sample selected =>
      Exp3.importanceWeightedLoss
        (initialHalfTsallisDistribution arms harms eta)
        (loss.initial sample.1) sample.2 selected
  have hupdatedScore : forall selected, selected ∈ arms ->
      Measurable (fun sample => updatedScore sample selected) := by
    intro selected _hselected
    unfold updatedScore Exp3.importanceWeightedLoss
    refine Measurable.ite ?_
      ((loss.measurable_initial.comp
          (measurable_fst.prodMk measurable_const)).div measurable_const)
      measurable_const
    simpa only [Set.mem_setOf_eq] using
      measurable_snd (measurableSet_singleton selected)
  have hcanonical : Measurable (fun sample =>
      halfTsallisMinimizer arms harms eta
        (updatedScore sample) candidate) :=
    measurable_halfTsallisMinimizer_comp
      arms harms eta updatedScore hupdatedScore candidate hcandidate
  simpa [sampledHalfTsallisInitialUpdatedAt,
    halfTsallisHistoryUpdatedMinimizer, halfTsallisUpdatedMinimizer,
    updatedScore] using hcanonical

theorem measurable_sampledHalfTsallisInitialHistoryActionStability
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) :
    Measurable (sampledHalfTsallisInitialHistoryActionStability
      arms harms eta loss) := by
  unfold sampledHalfTsallisInitialHistoryActionStability
  apply measurable_importanceWeightedStabilityScore
  · intro candidate _hcandidate
    exact measurable_const
  · intro candidate _hcandidate
    exact loss.measurable_initial.comp
      (measurable_id.prodMk measurable_const)
  · intro candidate hcandidate
    exact measurable_sampledHalfTsallisInitialUpdatedAt
      arms harms eta loss candidate hcandidate

/-- The stored-reward initial stability term agrees almost surely with the
canonical predictable updated-minimizer score. -/
theorem sampledHalfTsallisInitialStability_eq_historyAction_ae
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    sampledHalfTsallisInitialStability arms harms eta =ᵐ[mu]
      (fun sample => sampledHalfTsallisInitialHistoryActionStability
        arms harms eta loss (sample.1, (sample.2 0).1)) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hestimated :=
    sampledHalfTsallisObservedEstimatedLossAt_eq_predictable_ae
      prior arms harms eta loss 0
  dsimp only at hestimated
  filter_upwards [hestimated] with sample hestimatedSample
  have hnext :
      sampledHalfTsallisHistoryDistribution arms harms eta 0
          (Preorder.frestrictLe 0 sample.2) =
        sampledHalfTsallisInitialUpdatedAt
          arms harms eta loss sample.1 (sample.2 0).1 := by
    unfold sampledHalfTsallisHistoryDistribution
      sampledHalfTsallisInitialUpdatedAt
      halfTsallisHistoryMinimizer halfTsallisHistoryUpdatedMinimizer
      halfTsallisUpdatedMinimizer
    congr 1
    funext candidate
    rw [sampledHalfTsallisHistoryScore_zero]
    have hcandidate := congrFun hestimatedSample candidate
    simpa [sampledHalfTsallisObservedEstimatedLossAt,
      sampledHalfTsallisPredictableEstimatedLossAt,
      sampledHalfTsallisProbabilityAtTime,
      initialHalfTsallisDistribution, Exp3.predictableLossAt] using hcandidate
  unfold sampledHalfTsallisInitialStability
    sampledHalfTsallisInitialHistoryActionStability
    importanceWeightedStabilityScore
  rw [hestimatedSample, hnext]
  rfl

/-- Observed and predictable successor stability agree almost surely. -/
theorem sampledHalfTsallisObservedSuccessorStabilityAt_eq_predictable_ae
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    sampledHalfTsallisObservedSuccessorStabilityAt
        arms harms eta n =ᵐ[mu]
      sampledHalfTsallisSuccessorStabilityAt
        arms harms eta loss n := by
  dsimp only
  have hestimated :=
    sampledHalfTsallisObservedEstimatedLossAt_eq_predictable_ae
      prior arms harms eta loss (n + 1)
  dsimp only at hestimated
  filter_upwards [hestimated] with sample hestimatedSample
  unfold sampledHalfTsallisObservedSuccessorStabilityAt
    sampledHalfTsallisSuccessorStabilityAt
  rw [hestimatedSample]
  rfl

theorem measurable_mixedImportanceWeightedLoss_of_coordinates
    {History : Type u} {Action : Type v}
    [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (hprob : forall candidate, candidate ∈ arms ->
      Measurable (fun history => prob history candidate))
    (hloss : forall candidate, candidate ∈ arms ->
      Measurable (fun history => loss history candidate)) :
    Measurable (fun sample : History × Action =>
      Exp3.mixedImportanceWeightedLoss arms
        (prob sample.1) (loss sample.1) sample.2) := by
  classical
  unfold Exp3.mixedImportanceWeightedLoss
  refine Finset.measurable_sum arms fun candidate hcandidate => ?_
  have hestimated : Measurable (fun sample : History × Action =>
      Exp3.importanceWeightedLoss
        (prob sample.1) (loss sample.1) sample.2 candidate) := by
    unfold Exp3.importanceWeightedLoss
    refine Measurable.ite ?_
      (((hloss candidate hcandidate).comp measurable_fst).div
        ((hprob candidate hcandidate).comp measurable_fst)) measurable_const
    simpa only [Set.mem_setOf_eq] using
      measurable_snd (measurableSet_singleton candidate)
  exact ((hprob candidate hcandidate).comp measurable_fst).mul hestimated

theorem measurable_weightedImportanceWeightedLoss_of_coordinates
    {History : Type u} {Action : Type v}
    [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (prob weight loss : History -> Action -> Real)
    (hprob : forall candidate, candidate ∈ arms ->
      Measurable (fun history => prob history candidate))
    (hweight : forall candidate, candidate ∈ arms ->
      Measurable (fun history => weight history candidate))
    (hloss : forall candidate, candidate ∈ arms ->
      Measurable (fun history => loss history candidate)) :
    Measurable (fun sample : History × Action =>
      Exp3.weightedImportanceWeightedLoss arms
        (prob sample.1) (weight sample.1) (loss sample.1) sample.2) := by
  classical
  unfold Exp3.weightedImportanceWeightedLoss
  refine Finset.measurable_sum arms fun candidate hcandidate => ?_
  have hestimated : Measurable (fun sample : History × Action =>
      Exp3.importanceWeightedLoss
        (prob sample.1) (loss sample.1) sample.2 candidate) := by
    unfold Exp3.importanceWeightedLoss
    refine Measurable.ite ?_
      (((hloss candidate hcandidate).comp measurable_fst).div
        ((hprob candidate hcandidate).comp measurable_fst)) measurable_const
    simpa only [Set.mem_setOf_eq] using
      measurable_snd (measurableSet_singleton candidate)
  exact ((hweight candidate hcandidate).comp measurable_fst).mul hestimated

/-- Mixed importance-weighted loss is integrable under its finite sampling
kernel without a uniform probability floor. -/
theorem integrable_mixedImportanceWeightedLoss_finiteActionKernel
    {History : Type u} {Action : Type v}
    [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (source : Exp3.MeasurableFiniteActionDistribution arms prob)
    (hprobPos : forall history candidate, candidate ∈ arms ->
      0 < prob history candidate)
    (hloss : forall history candidate, candidate ∈ arms ->
      0 <= loss history candidate ∧ loss history candidate <= 1)
    (hscore : Measurable (fun sample : History × Action =>
      Exp3.mixedImportanceWeightedLoss arms
        (prob sample.1) (loss sample.1) sample.2)) :
    Integrable (fun sample : History × Action =>
      Exp3.mixedImportanceWeightedLoss arms
        (prob sample.1) (loss sample.1) sample.2)
      (historyMu ⊗ₘ Exp3.finiteActionKernel arms prob source) := by
  let score := fun sample : History × Action =>
    Exp3.mixedImportanceWeightedLoss arms
      (prob sample.1) (loss sample.1) sample.2
  have hconditional (history : History) : Integrable
      (fun chosen => score (history, chosen))
      (Exp3.finiteActionKernel arms prob source history) := by
    rw [Exp3.finiteActionKernel_apply]
    exact integrable_finiteActionMeasure arms (prob history)
      (fun chosen => score (history, chosen))
  have hsumMeasurable : Measurable (fun history => arms.sum (fun chosen =>
      prob history chosen * |score (history, chosen)|)) := by
    refine Finset.measurable_sum arms fun chosen hchosen => ?_
    exact (source.measurable_prob chosen hchosen).mul
      ((hscore.comp (measurable_id.prodMk measurable_const)).abs)
  have hsumBound (history : History) :
      arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|) <= 1 := by
    have hscoreNonneg (chosen : Action) (hchosen : chosen ∈ arms) :
        0 <= score (history, chosen) := by
      unfold score Exp3.mixedImportanceWeightedLoss
      exact Finset.sum_nonneg fun candidate hcandidate =>
        mul_nonneg ((source.distribution history).nonneg candidate hcandidate)
          (Exp3.importanceWeightedLoss_nonneg
            ((source.distribution history).nonneg candidate hcandidate)
            (hloss history candidate hcandidate).1)
    calc
      arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|) =
          arms.sum (fun chosen => prob history chosen * score (history, chosen)) := by
            apply Finset.sum_congr rfl
            intro chosen hchosen
            rw [abs_of_nonneg (hscoreNonneg chosen hchosen)]
      _ = arms.sum (fun candidate =>
          prob history candidate * loss history candidate) :=
        Exp3.sum_prob_mul_mixedImportanceWeightedLoss_eq_mixedLoss
          arms (prob history) (loss history)
            (fun candidate hcandidate =>
              ne_of_gt (hprobPos history candidate hcandidate))
      _ <= arms.sum (prob history) := by
        exact Finset.sum_le_sum fun candidate hcandidate =>
          (mul_le_iff_le_one_right
            (hprobPos history candidate hcandidate)).2
              (hloss history candidate hcandidate).2
      _ = 1 := (source.distribution history).sum_eq_one
  have hsumIntegrable : Integrable (fun history => arms.sum (fun chosen =>
      prob history chosen * |score (history, chosen)|)) historyMu := by
    refine Integrable.of_bound hsumMeasurable.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall fun history => by
      rw [Real.norm_eq_abs, abs_of_nonneg]
      · exact hsumBound history
      · exact Finset.sum_nonneg fun chosen hchosen =>
          mul_nonneg ((source.distribution history).nonneg chosen hchosen)
            (abs_nonneg _)
  apply (Measure.integrable_compProd_iff hscore.aestronglyMeasurable).2
  constructor
  · exact Filter.Eventually.of_forall hconditional
  · have hintegralEq :
        (fun history => integral
          (Exp3.finiteActionKernel arms prob source history)
          (fun chosen => ‖score (history, chosen)‖)) =
        (fun history => arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|)) := by
      funext history
      rw [Exp3.finiteActionKernel_apply,
        Exp3.integral_finiteActionMeasure_eq_sum arms (prob history)
          (source.distribution history)]
      simp only [Real.norm_eq_abs]
    rw [hintegralEq]
    exact hsumIntegrable

/-- A fixed simplex comparator weighting of the importance-weighted loss is
integrable under the sampling kernel, again without a uniform floor. -/
theorem integrable_weightedImportanceWeightedLoss_finiteActionKernel
    {History : Type u} {Action : Type v}
    [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (historyMu : Measure History) [IsFiniteMeasure historyMu]
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (source : Exp3.MeasurableFiniteActionDistribution arms prob)
    (hprobPos : forall history candidate, candidate ∈ arms ->
      0 < prob history candidate)
    (hloss : forall history candidate, candidate ∈ arms ->
      0 <= loss history candidate ∧ loss history candidate <= 1)
    (hscore : Measurable (fun sample : History × Action =>
      Exp3.weightedImportanceWeightedLoss arms
        (prob sample.1) q (loss sample.1) sample.2)) :
    Integrable (fun sample : History × Action =>
      Exp3.weightedImportanceWeightedLoss arms
        (prob sample.1) q (loss sample.1) sample.2)
      (historyMu ⊗ₘ Exp3.finiteActionKernel arms prob source) := by
  let weight := fun _history : History => q
  let score := fun sample : History × Action =>
    Exp3.weightedImportanceWeightedLoss arms
      (prob sample.1) q (loss sample.1) sample.2
  have hconditional (history : History) : Integrable
      (fun chosen => score (history, chosen))
      (Exp3.finiteActionKernel arms prob source history) := by
    rw [Exp3.finiteActionKernel_apply]
    exact integrable_finiteActionMeasure arms (prob history)
      (fun chosen => score (history, chosen))
  have hsumMeasurable : Measurable (fun history => arms.sum (fun chosen =>
      prob history chosen * |score (history, chosen)|)) := by
    refine Finset.measurable_sum arms fun chosen hchosen => ?_
    exact (source.measurable_prob chosen hchosen).mul
      ((hscore.comp (measurable_id.prodMk measurable_const)).abs)
  have hsumBound (history : History) :
      arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|) <= 1 := by
    have hscoreNonneg (chosen : Action) (hchosen : chosen ∈ arms) :
        0 <= score (history, chosen) := by
      unfold score Exp3.weightedImportanceWeightedLoss
      exact Finset.sum_nonneg fun candidate hcandidate =>
        mul_nonneg (hq.1 candidate hcandidate)
          (Exp3.importanceWeightedLoss_nonneg
            ((source.distribution history).nonneg candidate hcandidate)
            (hloss history candidate hcandidate).1)
    calc
      arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|) =
          arms.sum (fun chosen => prob history chosen * score (history, chosen)) := by
            apply Finset.sum_congr rfl
            intro chosen hchosen
            rw [abs_of_nonneg (hscoreNonneg chosen hchosen)]
      _ = arms.sum (fun candidate => q candidate * loss history candidate) :=
        Exp3.sum_prob_mul_weightedImportanceWeightedLoss_eq_weightedLoss
          arms (prob history) q (loss history)
            (fun candidate hcandidate =>
              ne_of_gt (hprobPos history candidate hcandidate))
      _ <= arms.sum q := by
        exact Finset.sum_le_sum fun candidate hcandidate =>
          by
            nlinarith [hq.1 candidate hcandidate,
              (hloss history candidate hcandidate).2]
      _ = 1 := hq.2
  have hsumIntegrable : Integrable (fun history => arms.sum (fun chosen =>
      prob history chosen * |score (history, chosen)|)) historyMu := by
    refine Integrable.of_bound hsumMeasurable.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall fun history => by
      rw [Real.norm_eq_abs, abs_of_nonneg]
      · exact hsumBound history
      · exact Finset.sum_nonneg fun chosen hchosen =>
          mul_nonneg ((source.distribution history).nonneg chosen hchosen)
            (abs_nonneg _)
  apply (Measure.integrable_compProd_iff hscore.aestronglyMeasurable).2
  constructor
  · exact Filter.Eventually.of_forall hconditional
  · have hintegralEq :
        (fun history => integral
          (Exp3.finiteActionKernel arms prob source history)
          (fun chosen => ‖score (history, chosen)‖)) =
        (fun history => arms.sum (fun chosen =>
          prob history chosen * |score (history, chosen)|)) := by
      funext history
      rw [Exp3.finiteActionKernel_apply,
        Exp3.integral_finiteActionMeasure_eq_sum arms (prob history)
          (source.distribution history)]
      simp only [Real.norm_eq_abs]
    rw [hintegralEq]
    exact hsumIntegrable

/-- Constant environment-indexed source for the initial half-Tsallis law. -/
noncomputable def initialHalfTsallisEnvironmentDistributionSource
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real) :
    Exp3.MeasurableFiniteActionDistribution arms
      (fun _env : Env => initialHalfTsallisDistribution arms harms eta) where
  distribution _env :=
    finiteActionDistribution_initialHalfTsallisDistribution arms harms eta
  measurable_prob _candidate _hcandidate := measurable_const

/-- Product-law integrability of an arbitrary score transports to the actual
history/action composition under an identified conditional action law. -/
theorem integrable_score_comp_history_action_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type*}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [StandardBorelSpace Action] [Nonempty Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (policy : Kernel History Action) [IsMarkovKernel policy]
    (hcond : condDistrib action history mu =ᵐ[mu.map history] policy)
    (score : History × Action -> Real)
    (hIntegrable : Integrable score (mu.map history ⊗ₘ policy)) :
    Integrable (fun omega => score (history omega, action omega)) mu := by
  have hpair :
      mu.map (fun omega => (history omega, action omega)) =
        mu.map history ⊗ₘ policy :=
    (condDistrib_ae_eq_iff_measure_eq_compProd history
      haction.aemeasurable policy).mp hcond
  have hmap : Integrable score
      (mu.map (fun omega => (history omega, action omega))) := by
    rwa [hpair]
  simpa [Function.comp_def] using
    hmap.comp_measurable (hhistory.prodMk haction)

theorem integrable_mixed_weightedImportanceWeightedLoss_of_condDistrib
    {Omega : Type u} {History : Type v} {Action : Type*}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (source : Exp3.MeasurableFiniteActionDistribution arms prob)
    (hcond : condDistrib action history mu =ᵐ[mu.map history]
      Exp3.finiteActionKernel arms prob source)
    (hprobPos : forall h candidate, candidate ∈ arms ->
      0 < prob h candidate)
    (hlossMeas : forall candidate, candidate ∈ arms ->
      Measurable (fun h => loss h candidate))
    (hloss : forall h candidate, candidate ∈ arms ->
      0 <= loss h candidate ∧ loss h candidate <= 1) :
    Integrable (fun omega =>
        Exp3.mixedImportanceWeightedLoss arms
          (prob (history omega)) (loss (history omega)) (action omega)) mu ∧
      Integrable (fun omega =>
        Exp3.weightedImportanceWeightedLoss arms
          (prob (history omega)) q (loss (history omega)) (action omega)) mu := by
  have hmixedMeas := measurable_mixedImportanceWeightedLoss_of_coordinates
    arms prob loss source.measurable_prob hlossMeas
  have hweightedMeas :=
    measurable_weightedImportanceWeightedLoss_of_coordinates
      arms prob (fun _history => q) loss source.measurable_prob
      (fun _candidate _hcandidate => measurable_const) hlossMeas
  have hmixedProduct :=
    integrable_mixedImportanceWeightedLoss_finiteActionKernel
      (mu.map history) arms prob loss source hprobPos hloss hmixedMeas
  have hweightedProduct :=
    integrable_weightedImportanceWeightedLoss_finiteActionKernel
      (mu.map history) arms prob loss q hq source hprobPos hloss hweightedMeas
  exact ⟨
    integrable_score_comp_history_action_of_condDistrib
      mu history hhistory action haction
      (Exp3.finiteActionKernel arms prob source) hcond _ hmixedProduct,
    integrable_score_comp_history_action_of_condDistrib
      mu history hhistory action haction
      (Exp3.finiteActionKernel arms prob source) hcond _ hweightedProduct⟩

/-- Conditional first moments for a positive finite sampling law, with no
uniform probability floor. -/
theorem integral_mixed_weightedImportanceWeightedLoss_eq_predictable
    {Omega : Type u} {History : Type v} {Action : Type*}
    [MeasurableSpace Omega] [MeasurableSpace History]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    (history : Omega -> History) (hhistory : Measurable history)
    (action : Omega -> Action) (haction : Measurable action)
    (arms : Finset Action) (prob loss : History -> Action -> Real)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (source : Exp3.MeasurableFiniteActionDistribution arms prob)
    (hcond : condDistrib action history mu =ᵐ[mu.map history]
      Exp3.finiteActionKernel arms prob source)
    (hprobPos : forall h candidate, candidate ∈ arms ->
      0 < prob h candidate)
    (hlossMeas : forall candidate, candidate ∈ arms ->
      Measurable (fun h => loss h candidate))
    (hloss : forall h candidate, candidate ∈ arms ->
      0 <= loss h candidate ∧ loss h candidate <= 1) :
    (integral mu (fun omega =>
        Exp3.mixedImportanceWeightedLoss arms
          (prob (history omega)) (loss (history omega)) (action omega)) =
      integral mu (fun omega =>
        FTRL.linearLoss arms (prob (history omega)) (loss (history omega)))) ∧
    (integral mu (fun omega =>
        Exp3.weightedImportanceWeightedLoss arms
          (prob (history omega)) q (loss (history omega)) (action omega)) =
      integral mu (fun omega =>
        FTRL.linearLoss arms q (loss (history omega)))) := by
  let policy := Exp3.finiteActionKernel arms prob source
  have hprobMeas : forall candidate, candidate ∈ arms ->
      Measurable (fun h => prob h candidate) := source.measurable_prob
  have hmixedMeas : Measurable (fun sample : History × Action =>
      Exp3.mixedImportanceWeightedLoss arms
        (prob sample.1) (loss sample.1) sample.2) :=
    measurable_mixedImportanceWeightedLoss_of_coordinates
      arms prob loss hprobMeas hlossMeas
  have hweightedMeas : Measurable (fun sample : History × Action =>
      Exp3.weightedImportanceWeightedLoss arms
        (prob sample.1) q (loss sample.1) sample.2) :=
    measurable_weightedImportanceWeightedLoss_of_coordinates
      arms prob (fun _history => q) loss hprobMeas
      (fun _candidate _hcandidate => measurable_const) hlossMeas
  have hmixedIntegrable :=
    integrable_mixedImportanceWeightedLoss_finiteActionKernel
      (mu.map history) arms prob loss source hprobPos hloss hmixedMeas
  have hweightedIntegrable :=
    integrable_weightedImportanceWeightedLoss_finiteActionKernel
      (mu.map history) arms prob loss q hq source hprobPos hloss hweightedMeas
  have hpolicy : policy =ᵐ[mu.map history]
      fun h => Exp3.finiteActionMeasure arms (prob h) :=
    Exp3.finiteActionKernel_ae_eq_finiteActionMeasure
      (mu.map history) arms prob source
  have hmixed :=
    Exp3.integral_mixedImportanceWeightedLoss_eq_integral_mixedLoss_of_condDistrib
      mu history hhistory action haction arms prob loss source.distribution
      hprobPos policy hpolicy hcond hmixedMeas hmixedIntegrable
  have hweighted :=
    Exp3.integral_weightedImportanceWeightedLoss_eq_integral_weightedLoss_of_condDistrib
      mu history hhistory action haction arms prob (fun _history => q) loss
      source.distribution hprobPos policy hpolicy hcond hweightedMeas
      hweightedIntegrable
  have hmixedTrue : Measurable (fun h =>
      FTRL.linearLoss arms (prob h) (loss h)) := by
    unfold FTRL.linearLoss
    exact Finset.measurable_sum arms fun candidate hcandidate =>
      (hprobMeas candidate hcandidate).mul
        (hlossMeas candidate hcandidate)
  have hweightedTrue : Measurable (fun h =>
      FTRL.linearLoss arms q (loss h)) := by
    unfold FTRL.linearLoss
    exact Finset.measurable_sum arms fun candidate hcandidate =>
      measurable_const.mul (hlossMeas candidate hcandidate)
  constructor
  · calc
      integral mu (fun omega =>
          Exp3.mixedImportanceWeightedLoss arms
            (prob (history omega)) (loss (history omega)) (action omega)) =
          integral (mu.map history) (fun h =>
            arms.sum (fun candidate => prob h candidate * loss h candidate)) :=
        hmixed
      _ = integral (mu.map history) (fun h =>
          FTRL.linearLoss arms (prob h) (loss h)) := by rfl
      _ = integral mu (fun omega =>
          FTRL.linearLoss arms (prob (history omega)) (loss (history omega))) := by
        rw [integral_map hhistory.aemeasurable
          hmixedTrue.aestronglyMeasurable]
  · calc
      integral mu (fun omega =>
          Exp3.weightedImportanceWeightedLoss arms
            (prob (history omega)) q (loss (history omega)) (action omega)) =
          integral (mu.map history) (fun h =>
            arms.sum (fun candidate => q candidate * loss h candidate)) :=
        hweighted
      _ = integral (mu.map history) (fun h =>
          FTRL.linearLoss arms q (loss h)) := by rfl
      _ = integral mu (fun omega =>
          FTRL.linearLoss arms q (loss (history omega))) := by
        rw [integral_map hhistory.aemeasurable
          hweightedTrue.aestronglyMeasurable]

/-- At every actual time, both the sampling-distribution mixed estimator and
the fixed-comparator weighted estimator have the corresponding predictable
first moment under the generated half-Tsallis trajectory. -/
theorem sampledHalfTsallisPredictableEstimatedLossAt_first_moments
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q) (t : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    (Integrable (fun sample =>
        FTRL.linearLoss arms
          (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
          (sampledHalfTsallisPredictableEstimatedLossAt
            arms harms eta loss t sample)) mu ∧
      Integrable (fun sample =>
        FTRL.linearLoss arms q
          (sampledHalfTsallisPredictableEstimatedLossAt
            arms harms eta loss t sample)) mu) ∧
    ((integral mu (fun sample =>
        FTRL.linearLoss arms
          (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
          (sampledHalfTsallisPredictableEstimatedLossAt
            arms harms eta loss t sample)) =
      integral mu (fun sample =>
        FTRL.linearLoss arms
          (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
          (Exp3.predictableLossAt loss t sample))) ∧
    (integral mu (fun sample =>
        FTRL.linearLoss arms q
          (sampledHalfTsallisPredictableEstimatedLossAt
            arms harms eta loss t sample)) =
      integral mu (fun sample =>
        FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample)))) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let algorithm := sampledHalfTsallisHistoryAlgorithm arms harms eta selector
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  cases t with
  | zero =>
      let history := fun sample : Env × ((k : Nat) -> Action × Real) => sample.1
      let action := fun sample : Env × ((k : Nat) -> Action × Real) =>
        (sample.2 0).1
      let prob := fun _env : Env =>
        initialHalfTsallisDistribution arms harms eta
      let roundLoss := loss.initial
      let source := initialHalfTsallisEnvironmentDistributionSource
        (Env := Env) arms harms eta
      have hhistory : Measurable history := measurable_fst
      have haction : Measurable action :=
        measurable_fst.comp ((measurable_pi_apply 0).comp measurable_snd)
      have hkernel : Kernel.const Env algorithm.initialAction =
          Exp3.finiteActionKernel arms prob source := by
        ext env event hevent
        rw [Kernel.const_apply, Exp3.finiteActionKernel_apply]
        rfl
      have hcond : condDistrib action history mu =ᵐ[mu.map history]
          Exp3.finiteActionKernel arms prob source := by
        have hbase :=
          Exp3.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action_zero_given_environment
            prior algorithm loss.environment
        rw [hkernel] at hbase
        simpa [mu, algorithm, history, action,
          sampledHalfTsallisTrajectoryKernel] using hbase
      have hprobPos : forall env candidate, candidate ∈ arms ->
          0 < prob env candidate := by
        intro env candidate hcandidate
        exact isRegularizedMinimizer_pos arms eta (fun _ => 0)
          (initialHalfTsallisDistribution arms harms eta)
          (halfTsallisMinimizer_isRegularizedMinimizer
            arms harms eta (fun _ => 0)) candidate hcandidate
      have hmoment :=
        integral_mixed_weightedImportanceWeightedLoss_eq_predictable
          mu history hhistory action haction arms prob roundLoss q hq source
          hcond hprobPos
          (fun candidate _hcandidate =>
            loss.measurable_initial.comp
              (measurable_id.prodMk measurable_const))
          (fun env candidate _hcandidate =>
            loss.initial_mem_unitInterval env candidate)
      have hintegrable :=
        integrable_mixed_weightedImportanceWeightedLoss_of_condDistrib
          mu history hhistory action haction arms prob roundLoss q hq source
          hcond hprobPos
          (fun candidate _hcandidate =>
            loss.measurable_initial.comp
              (measurable_id.prodMk measurable_const))
          (fun env candidate _hcandidate =>
            loss.initial_mem_unitInterval env candidate)
      constructor
      · simpa [history, action, prob, roundLoss,
          sampledHalfTsallisProbabilityAtTime,
          sampledHalfTsallisPredictableEstimatedLossAt,
          Exp3.mixedImportanceWeightedLoss,
          Exp3.weightedImportanceWeightedLoss, FTRL.linearLoss] using hintegrable
      · simpa [history, action, prob, roundLoss,
          sampledHalfTsallisProbabilityAtTime,
          sampledHalfTsallisPredictableEstimatedLossAt,
          Exp3.predictableLossAt, Exp3.mixedImportanceWeightedLoss,
          Exp3.weightedImportanceWeightedLoss, FTRL.linearLoss] using hmoment
  | succ n =>
      let history := sampledHalfTsallisHistoryAt
        (Env := Env) (Action := Action) n
      let action := sampledHalfTsallisActionAt
        (Env := Env) (Action := Action) n
      let prob := sampledHalfTsallisProbabilityAt
        (Env := Env) arms harms eta n
      let roundLoss := sampledHalfTsallisPredictableLossAt loss n
      let source := sampledHalfTsallisEnvironmentHistoryDistributionSource
        (Env := Env) arms harms eta selector n
      have hhistory : Measurable history :=
        measurable_fst.prodMk
          ((Preorder.measurable_frestrictLe n).comp measurable_snd)
      have haction : Measurable action :=
        measurable_fst.comp ((measurable_pi_apply (n + 1)).comp measurable_snd)
      have hcond : condDistrib action history mu =ᵐ[mu.map history]
          Exp3.finiteActionKernel arms prob source := by
        have hbase :=
          sampledHalfTsallisTrajectoryMeasure_condDistrib_action_given_environment
            prior arms harms eta selector loss.environment n
        change condDistrib action history mu =ᵐ[mu.map history]
          sampledHalfTsallisPolicyAt (Env := Env)
            arms harms eta selector n at hbase
        rw [sampledHalfTsallisPolicyAt_eq_finiteActionKernel
          (Env := Env) arms harms eta selector n] at hbase
        simpa [mu, history, action, prob, source] using hbase
      have hprobPos : forall h candidate, candidate ∈ arms ->
          0 < prob h candidate := by
        intro h candidate hcandidate
        exact isRegularizedMinimizer_pos arms eta
          (sampledHalfTsallisScoreAt arms harms eta n h)
          (prob h)
          (halfTsallisMinimizer_isRegularizedMinimizer
            arms harms eta (sampledHalfTsallisScoreAt arms harms eta n h))
          candidate hcandidate
      have hmoment :=
        integral_mixed_weightedImportanceWeightedLoss_eq_predictable
          mu history hhistory action haction arms prob roundLoss q hq source
          hcond hprobPos
          (fun candidate _hcandidate =>
            measurable_sampledHalfTsallisPredictableLossAt loss n candidate)
          (fun h candidate _hcandidate =>
            loss.successor_mem_unitInterval n h.1 h.2 candidate)
      have hintegrable :=
        integrable_mixed_weightedImportanceWeightedLoss_of_condDistrib
          mu history hhistory action haction arms prob roundLoss q hq source
          hcond hprobPos
          (fun candidate _hcandidate =>
            measurable_sampledHalfTsallisPredictableLossAt loss n candidate)
          (fun h candidate _hcandidate =>
            loss.successor_mem_unitInterval n h.1 h.2 candidate)
      constructor
      · simpa [history, action, prob, roundLoss,
          sampledHalfTsallisProbabilityAtTime,
          sampledHalfTsallisPredictableEstimatedLossAt,
          Exp3.mixedImportanceWeightedLoss,
          Exp3.weightedImportanceWeightedLoss, FTRL.linearLoss] using hintegrable
      · simpa [history, action, prob, roundLoss,
          sampledHalfTsallisProbabilityAtTime,
          sampledHalfTsallisPredictableEstimatedLossAt,
          Exp3.predictableLossAt, Exp3.mixedImportanceWeightedLoss,
          Exp3.weightedImportanceWeightedLoss, FTRL.linearLoss] using hmoment

theorem finiteSimplex_sampledHalfTsallisProbabilityAtTime
    {Env : Type u} {Action : Type v} [DecidableEq Action]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (t : Nat) (sample : Env × ((k : Nat) -> Action × Real)) :
    FTRL.finiteSimplex arms
      (sampledHalfTsallisProbabilityAtTime arms harms eta t sample) := by
  cases t with
  | zero =>
      exact ⟨
        (finiteActionDistribution_initialHalfTsallisDistribution
          arms harms eta).nonneg,
        (finiteActionDistribution_initialHalfTsallisDistribution
          arms harms eta).sum_eq_one⟩
  | succ n =>
      exact (halfTsallisMinimizer_isRegularizedMinimizer arms harms eta
        (sampledHalfTsallisHistoryScore arms harms eta n
          (Preorder.frestrictLe n sample.2))).1

/-- Current mixed predictable loss and fixed-comparator predictable loss are
integrable at every actual time. -/
theorem integrable_sampledHalfTsallisPredictableLinearLossAt
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    (mu : Measure (Env × ((k : Nat) -> Action × Real))) [IsFiniteMeasure mu]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q) (t : Nat) :
    Integrable (fun sample =>
        FTRL.linearLoss arms
          (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
          (Exp3.predictableLossAt loss t sample)) mu ∧
      Integrable (fun sample =>
        FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample)) mu := by
  have hprobMeas (candidate : Action) (hcandidate : candidate ∈ arms) :=
    measurable_sampledHalfTsallisProbabilityAtTime
      (Env := Env) arms harms eta t candidate hcandidate
  have hlossMeas (candidate : Action) :=
    Exp3.measurable_predictableLossAt loss t candidate
  have hcurrentMeas : Measurable (fun sample =>
      FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (Exp3.predictableLossAt loss t sample)) := by
    unfold FTRL.linearLoss
    exact Finset.measurable_sum arms fun candidate hcandidate =>
      (hprobMeas candidate hcandidate).mul (hlossMeas candidate)
  have hcomparatorMeas : Measurable (fun sample =>
      FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample)) := by
    unfold FTRL.linearLoss
    exact Finset.measurable_sum arms fun candidate _hcandidate =>
      measurable_const.mul (hlossMeas candidate)
  have hlossMem (sample : Env × ((k : Nat) -> Action × Real))
      (candidate : Action) :
      Exp3.predictableLossAt loss t sample candidate ∈ Set.Icc (0 : Real) 1 := by
    cases t with
    | zero => exact loss.initial_mem_unitInterval sample.1 candidate
    | succ n =>
        exact loss.successor_mem_unitInterval n sample.1
          (Preorder.frestrictLe n sample.2) candidate
  have hcurrentMem (sample : Env × ((k : Nat) -> Action × Real)) :
      FTRL.linearLoss arms
          (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
          (Exp3.predictableLossAt loss t sample) ∈ Set.Icc (0 : Real) 1 := by
    let p := sampledHalfTsallisProbabilityAtTime arms harms eta t sample
    have hp := finiteSimplex_sampledHalfTsallisProbabilityAtTime
      arms harms eta t sample
    constructor
    · unfold FTRL.linearLoss
      exact Finset.sum_nonneg fun candidate hcandidate =>
        mul_nonneg (hp.1 candidate hcandidate) (hlossMem sample candidate).1
    · calc
        FTRL.linearLoss arms p (Exp3.predictableLossAt loss t sample) <=
            arms.sum p := by
          unfold FTRL.linearLoss
          exact Finset.sum_le_sum fun candidate hcandidate => by
            nlinarith [hp.1 candidate hcandidate,
              (hlossMem sample candidate).2]
        _ = 1 := hp.2
  have hcomparatorMem (sample : Env × ((k : Nat) -> Action × Real)) :
      FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample) ∈
        Set.Icc (0 : Real) 1 := by
    constructor
    · unfold FTRL.linearLoss
      exact Finset.sum_nonneg fun candidate hcandidate =>
        mul_nonneg (hq.1 candidate hcandidate) (hlossMem sample candidate).1
    · calc
        FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample) <=
            arms.sum q := by
          unfold FTRL.linearLoss
          exact Finset.sum_le_sum fun candidate hcandidate => by
            nlinarith [hq.1 candidate hcandidate,
              (hlossMem sample candidate).2]
        _ = 1 := hq.2
  constructor
  · refine Integrable.of_bound hcurrentMeas.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall fun sample => by
      rw [Real.norm_eq_abs, abs_of_nonneg (hcurrentMem sample).1]
      exact (hcurrentMem sample).2
  · refine Integrable.of_bound hcomparatorMeas.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall fun sample => by
      rw [Real.norm_eq_abs, abs_of_nonneg (hcomparatorMem sample).1]
      exact (hcomparatorMem sample).2

/-- Finite-horizon predictable estimated regret is integrable and has exactly
the same integral as predictable environment regret. -/
theorem integral_sampledHalfTsallisPredictableEstimatedRegret_eq_environmentRegret
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (horizon : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    Integrable (sampledHalfTsallisPredictableEstimatedRegret
        arms harms eta loss q horizon) mu ∧
      Integrable (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) mu ∧
      integral mu (sampledHalfTsallisPredictableEstimatedRegret
        arms harms eta loss q horizon) =
        integral mu (sampledHalfTsallisPredictableEnvironmentRegret
          arms harms eta loss q horizon) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  let estimatedTerm := fun t sample =>
    FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (sampledHalfTsallisPredictableEstimatedLossAt
          arms harms eta loss t sample) -
      FTRL.linearLoss arms q
        (sampledHalfTsallisPredictableEstimatedLossAt
          arms harms eta loss t sample)
  let environmentTerm := fun t sample =>
    FTRL.linearLoss arms
        (sampledHalfTsallisProbabilityAtTime arms harms eta t sample)
        (Exp3.predictableLossAt loss t sample) -
      FTRL.linearLoss arms q (Exp3.predictableLossAt loss t sample)
  have hmoment (t : Nat) :=
    sampledHalfTsallisPredictableEstimatedLossAt_first_moments
      prior arms harms eta loss q hq t
  dsimp only at hmoment
  have hestimatedTerm (t : Nat) : Integrable (estimatedTerm t) mu :=
    (hmoment t).1.1.sub (hmoment t).1.2
  have henvironmentParts (t : Nat) :=
    integrable_sampledHalfTsallisPredictableLinearLossAt
      mu arms harms eta loss q hq t
  have henvironmentTerm (t : Nat) : Integrable (environmentTerm t) mu :=
    (henvironmentParts t).1.sub (henvironmentParts t).2
  have hestimatedSum : Integrable
      (sampledHalfTsallisPredictableEstimatedRegret
        arms harms eta loss q horizon) mu := by
    unfold sampledHalfTsallisPredictableEstimatedRegret
    exact IntegrabilitySums.integrable_finset_sum mu
      (Finset.range (horizon + 1)) estimatedTerm
      (fun t _ht => hestimatedTerm t)
  have henvironmentSum : Integrable
      (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) mu := by
    unfold sampledHalfTsallisPredictableEnvironmentRegret
    exact IntegrabilitySums.integrable_finset_sum mu
      (Finset.range (horizon + 1)) environmentTerm
      (fun t _ht => henvironmentTerm t)
  refine ⟨hestimatedSum, henvironmentSum, ?_⟩
  calc
    integral mu (sampledHalfTsallisPredictableEstimatedRegret
        arms harms eta loss q horizon) =
        (Finset.range (horizon + 1)).sum (fun t =>
          integral mu (estimatedTerm t)) := by
      unfold sampledHalfTsallisPredictableEstimatedRegret
      exact ExpectationBochnerSums.integral_finset_sum mu
        (Finset.range (horizon + 1)) estimatedTerm
        (fun t _ht => hestimatedTerm t)
    _ = (Finset.range (horizon + 1)).sum (fun t =>
          integral mu (environmentTerm t)) := by
      apply Finset.sum_congr rfl
      intro t _ht
      rw [integral_sub (hmoment t).1.1 (hmoment t).1.2,
        integral_sub (henvironmentParts t).1 (henvironmentParts t).2,
        (hmoment t).2.1, (hmoment t).2.2]
    _ = integral mu (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) := by
      symm
      unfold sampledHalfTsallisPredictableEnvironmentRegret
      exact ExpectationBochnerSums.integral_finset_sum mu
        (Finset.range (horizon + 1)) environmentTerm
        (fun t _ht => henvironmentTerm t)

/-- The observed estimated-regret functional agrees almost surely with its
predictable-estimator version over every finite horizon. -/
theorem sampledHalfTsallisObservedEstimatedRegret_eq_predictable_ae
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (horizon : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    sampledHalfTsallisObservedEstimatedRegret
        arms harms eta q horizon =ᵐ[mu]
      sampledHalfTsallisPredictableEstimatedRegret
        arms harms eta loss q horizon := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hestimatedAll : ∀ᵐ sample ∂mu, ∀ t,
      sampledHalfTsallisObservedEstimatedLossAt
          arms harms eta t sample =
        sampledHalfTsallisPredictableEstimatedLossAt
          arms harms eta loss t sample := by
    rw [ae_all_iff]
    intro t
    exact sampledHalfTsallisObservedEstimatedLossAt_eq_predictable_ae
      prior arms harms eta loss t
  filter_upwards [hestimatedAll] with sample hsample
  unfold sampledHalfTsallisObservedEstimatedRegret
    sampledHalfTsallisPredictableEstimatedRegret
  apply Finset.sum_congr rfl
  intro t _ht
  rw [hsample t]

/-- Observed importance-weighted regret is integrable and has exactly the
predictable environment-regret integral. -/
theorem integral_sampledHalfTsallisObservedEstimatedRegret_eq_environmentRegret
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (horizon : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    Integrable (sampledHalfTsallisObservedEstimatedRegret
        arms harms eta q horizon) mu ∧
      Integrable (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) mu ∧
      integral mu (sampledHalfTsallisObservedEstimatedRegret
        arms harms eta q horizon) =
        integral mu (sampledHalfTsallisPredictableEnvironmentRegret
          arms harms eta loss q horizon) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  have hpredictable :=
    integral_sampledHalfTsallisPredictableEstimatedRegret_eq_environmentRegret
      prior arms harms eta loss q hq horizon
  dsimp only at hpredictable
  have hae :=
    sampledHalfTsallisObservedEstimatedRegret_eq_predictable_ae
      prior arms harms eta loss q horizon
  dsimp only at hae
  have hobserved : Integrable
      (sampledHalfTsallisObservedEstimatedRegret
        arms harms eta q horizon) mu :=
    hpredictable.1.congr hae.symm
  exact ⟨hobserved, hpredictable.2.1,
    (integral_congr_ae hae).trans hpredictable.2.2⟩

/-- The time-zero observed stability has the same half-power bound as every
successor round.  A probability prior keeps the constant bound unscaled. -/
theorem integral_sampledHalfTsallisInitialStability_le_halfPower
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsProbabilityMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta)
    (loss : Exp3.PredictableLossVector Env Action) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    Integrable (sampledHalfTsallisInitialStability arms harms eta) mu ∧
      integral mu (sampledHalfTsallisInitialStability arms harms eta) <=
        2 * eta * powerSum arms (1 / 2 : Real)
          (initialHalfTsallisDistribution arms harms eta) := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let algorithm := sampledHalfTsallisHistoryAlgorithm arms harms eta selector
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  let history := fun sample : Env × ((k : Nat) -> Action × Real) => sample.1
  let action := fun sample : Env × ((k : Nat) -> Action × Real) =>
    (sample.2 0).1
  let prob := fun _env : Env =>
    initialHalfTsallisDistribution arms harms eta
  let roundLoss := loss.initial
  let next := sampledHalfTsallisInitialUpdatedAt arms harms eta loss
  let source := initialHalfTsallisEnvironmentDistributionSource
    (Env := Env) arms harms eta
  let policy := Exp3.finiteActionKernel arms prob source
  have hhistory : Measurable history := measurable_fst
  have haction : Measurable action :=
    measurable_fst.comp ((measurable_pi_apply 0).comp measurable_snd)
  have hkernel : Kernel.const Env algorithm.initialAction = policy := by
    ext env event hevent
    rw [Kernel.const_apply, Exp3.finiteActionKernel_apply]
    rfl
  have hcond : condDistrib action history mu =ᵐ[mu.map history] policy := by
    have hbase :=
      Exp3.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action_zero_given_environment
        prior algorithm loss.environment
    rw [hkernel] at hbase
    simpa [mu, algorithm, history, action,
      sampledHalfTsallisTrajectoryKernel] using hbase
  have hpolicy : policy =ᵐ[mu.map history]
      fun env => Exp3.finiteActionMeasure arms (prob env) :=
    Exp3.finiteActionKernel_ae_eq_finiteActionMeasure
      (mu.map history) arms prob source
  have hprobMin (env : Env) :
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (fun _candidate => 0) (prob env) :=
    halfTsallisMinimizer_isRegularizedMinimizer
      arms harms eta (fun _candidate => 0)
  have hnextMin (env : Env) (chosen : Action) (_hchosen : chosen ∈ arms) :
      FTRL.IsRegularizedMinimizer (FTRL.finiteSimplex arms)
        arms eta (negEntropyRegularizer arms (1 / 2 : Real))
        (fun candidate => 0 +
          Exp3.importanceWeightedLoss
            (prob env) (roundLoss env) chosen candidate)
        (next env chosen) := by
    simpa [prob, roundLoss, next,
      sampledHalfTsallisInitialUpdatedAt,
      halfTsallisHistoryUpdatedMinimizer] using
      (halfTsallisUpdatedMinimizer_isRegularizedMinimizer
        arms harms eta (fun _candidate => 0) (loss.initial env) chosen)
  have hprobPos (env : Env) (candidate : Action) (hcandidate : candidate ∈ arms) :
      0 < prob env candidate :=
    isRegularizedMinimizer_pos arms eta (fun _candidate => 0)
      (prob env) (hprobMin env) candidate hcandidate
  have hnextSimplex (env : Env) (chosen : Action) (hchosen : chosen ∈ arms) :
      FTRL.finiteSimplex arms (next env chosen) :=
    (hnextMin env chosen hchosen).1
  have hloss (env : Env) (candidate : Action) (_hcandidate : candidate ∈ arms) :
      0 <= roundLoss env candidate ∧ roundLoss env candidate <= 1 :=
    loss.initial_mem_unitInterval env candidate
  have hscore : Measurable
      (importanceWeightedStabilityScore arms prob roundLoss next) := by
    simpa [prob, roundLoss, next,
      sampledHalfTsallisInitialHistoryActionStability] using
      (measurable_sampledHalfTsallisInitialHistoryActionStability
        arms harms eta loss)
  have hscoreIntegrable : Integrable
      (importanceWeightedStabilityScore arms prob roundLoss next)
      (mu.map history ⊗ₘ policy) := by
    exact integrable_importanceWeightedStabilityScore_finiteActionKernel
      (mu.map history) arms prob roundLoss next source hprobPos
      hnextSimplex hloss hscore
  have hboundIntegrable : Integrable
      (halfPowerStabilityBound arms eta prob) (mu.map history) :=
    integrable_halfPowerStabilityBound_of_finiteSimplex
      (mu.map history) arms eta prob source
  have hcanonical :=
    integral_importanceWeightedStabilityScore_le_integral_halfPowerStabilityBound_of_condDistrib_of_minimizers
      mu history hhistory action haction arms eta
      (fun _env _candidate => 0) prob roundLoss next policy hpolicy hcond
      heta hprobMin hnextMin hloss hscore hscoreIntegrable hboundIntegrable
  have hobservedEq :=
    sampledHalfTsallisInitialStability_eq_historyAction_ae
      prior arms harms eta loss
  dsimp only at hobservedEq
  have hcanonicalIntegrable : Integrable (fun sample =>
      importanceWeightedStabilityScore arms prob roundLoss next
        (history sample, action sample)) mu :=
    integrable_score_comp_history_action_of_condDistrib
      mu history hhistory action haction policy hcond _ hscoreIntegrable
  have hobservedEq' :
      sampledHalfTsallisInitialStability arms harms eta =ᵐ[mu]
        (fun sample => importanceWeightedStabilityScore
          arms prob roundLoss next (history sample, action sample)) := by
    simpa [history, action, prob, roundLoss, next,
      sampledHalfTsallisInitialHistoryActionStability] using hobservedEq
  have hobservedIntegrable : Integrable
      (sampledHalfTsallisInitialStability arms harms eta) mu :=
    hcanonicalIntegrable.congr hobservedEq'.symm
  haveI : IsProbabilityMeasure mu := inferInstance
  haveI : IsProbabilityMeasure (mu.map history) :=
    Measure.isProbabilityMeasure_map hhistory.aemeasurable
  refine ⟨hobservedIntegrable, ?_⟩
  calc
    integral mu (sampledHalfTsallisInitialStability arms harms eta) =
        integral mu (fun sample =>
          importanceWeightedStabilityScore arms prob roundLoss next
            (history sample, action sample)) := by
      simpa [history, action, prob, roundLoss, next,
        sampledHalfTsallisInitialHistoryActionStability] using
        integral_congr_ae hobservedEq
    _ <= integral (mu.map history)
        (halfPowerStabilityBound arms eta prob) := hcanonical
    _ = 2 * eta * powerSum arms (1 / 2 : Real)
        (initialHalfTsallisDistribution arms harms eta) := by
      change integral (mu.map history) (fun _env : Env =>
        2 * eta * powerSum arms (1 / 2 : Real)
          (initialHalfTsallisDistribution arms harms eta)) = _
      rw [integral_const]
      simp

/-- Predictable and observed successor stability are both integrable under
the canonical generated half-Tsallis trajectory. -/
theorem integrable_sampledHalfTsallisSuccessorStabilitiesAt_canonical
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty) (eta : Real)
    (loss : Exp3.PredictableLossVector Env Action) (n : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    Integrable (sampledHalfTsallisSuccessorStabilityAt
        arms harms eta loss n) mu ∧
      Integrable (sampledHalfTsallisObservedSuccessorStabilityAt
        arms harms eta n) mu := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let generatedSelector := canonicalHalfTsallisGeneratedSelectorMeasurability
    arms harms eta loss
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  let history := sampledHalfTsallisHistoryAt
    (Env := Env) (Action := Action) n
  let action := sampledHalfTsallisActionAt
    (Env := Env) (Action := Action) n
  let policy := sampledHalfTsallisPolicyAt
    (Env := Env) arms harms eta selector n
  have hhistory : Measurable history :=
    measurable_fst.prodMk
      ((Preorder.measurable_frestrictLe n).comp measurable_snd)
  have haction : Measurable action :=
    measurable_fst.comp ((measurable_pi_apply (n + 1)).comp measurable_snd)
  have hcond : condDistrib action history mu =ᵐ[mu.map history] policy := by
    simpa [mu, history, action, policy, sampledHalfTsallisPolicyAt] using
      (sampledHalfTsallisTrajectoryMeasure_condDistrib_action_given_environment
        prior arms harms eta selector loss.environment n)
  have hscore : Measurable
      (sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n) :=
    measurable_sampledHalfTsallisHistoryActionStabilityAt
      arms harms eta loss generatedSelector n
  have hproduct : Integrable
      (sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n) (mu.map history ⊗ₘ policy) := by
    simpa [mu, history, policy, selector] using
      (integrable_sampledHalfTsallisHistoryActionStabilityAt
        prior arms harms eta selector loss n hscore)
  have hcomposition : Integrable (fun sample =>
      sampledHalfTsallisHistoryActionStabilityAt
        arms harms eta loss n (history sample, action sample)) mu :=
    integrable_importanceWeightedStabilityScore_comp_history_action_of_condDistrib
      mu history hhistory action haction arms
      (sampledHalfTsallisProbabilityAt (Env := Env) arms harms eta n)
      (sampledHalfTsallisPredictableLossAt loss n)
      (sampledHalfTsallisUpdatedAt arms harms eta loss n)
      policy hcond hproduct
  have hscoreSucc := sampledHalfTsallisScoreAt_succ_ae
    prior arms harms eta selector loss n
  dsimp only at hscoreSucc
  have hterm :
      sampledHalfTsallisSuccessorStabilityAt
          arms harms eta loss n =ᵐ[mu]
        (fun sample => sampledHalfTsallisHistoryActionStabilityAt
          arms harms eta loss n (history sample, action sample)) := by
    filter_upwards [hscoreSucc] with sample hscoreSuccSample
    have hnext :
        sampledHalfTsallisHistoryDistribution arms harms eta (n + 1)
            (Preorder.frestrictLe (n + 1) sample.2) =
          sampledHalfTsallisUpdatedAt arms harms eta loss n
            (sampledHalfTsallisHistoryAt n sample)
            (sampledHalfTsallisActionAt n sample) := by
      simp only [sampledHalfTsallisHistoryDistribution,
        sampledHalfTsallisUpdatedAt, halfTsallisHistoryMinimizer,
        halfTsallisHistoryUpdatedMinimizer, halfTsallisUpdatedMinimizer,
        sampledHalfTsallisScoreAt, sampledHalfTsallisPredictableLossAt,
        sampledHalfTsallisHistoryAt, sampledHalfTsallisActionAt]
      rw [hscoreSuccSample]
      rfl
    simp only [sampledHalfTsallisSuccessorStabilityAt,
      sampledHalfTsallisHistoryActionStabilityAt,
      importanceWeightedStabilityScore, history, action]
    rw [hnext]
  have hpredictable : Integrable (sampledHalfTsallisSuccessorStabilityAt
      arms harms eta loss n) mu :=
    hcomposition.congr hterm.symm
  have hobservedEq :=
    sampledHalfTsallisObservedSuccessorStabilityAt_eq_predictable_ae
      prior arms harms eta loss n
  dsimp only at hobservedEq
  exact ⟨hpredictable, hpredictable.congr hobservedEq.symm⟩

/-- Complete estimated-to-environment regret theorem for the generated pure
half-Tsallis policy.  The horizon contains time zero plus `horizon` successor
rounds; self-bounding and learning-rate tuning remain downstream. -/
theorem integral_sampledHalfTsallisPredictableEnvironmentRegret_le
    {Env : Type u} {Action : Type v}
    [MeasurableSpace Env] [StandardBorelSpace Env]
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [StandardBorelSpace Action] [Nonempty Action] [DecidableEq Action]
    (prior : Measure Env) [IsProbabilityMeasure prior]
    (arms : Finset Action) (harms : arms.Nonempty)
    (eta : Real) (heta : 0 < eta)
    (loss : Exp3.PredictableLossVector Env Action)
    (q : Action -> Real) (hq : FTRL.finiteSimplex arms q)
    (horizon : Nat) :
    let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
      arms harms eta
    let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
      arms harms eta selector loss.environment
    integral mu (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) <=
      2 * eta * powerSum arms (1 / 2 : Real)
          (initialHalfTsallisDistribution arms harms eta) +
        integral mu (fun sample => (Finset.range horizon).sum (fun n =>
          sampledHalfTsallisHalfPowerBoundAt (Env := Env)
            arms harms eta n (sampledHalfTsallisHistoryAt n sample))) +
        ((powerSum arms (1 / 2 : Real)
              (initialHalfTsallisDistribution arms harms eta) -
            powerSum arms (1 / 2 : Real) q) /
          (1 - (1 / 2 : Real))) / eta := by
  dsimp only
  let selector := canonicalHalfTsallisFiniteHistorySelectorMeasurability
    arms harms eta
  let mu := prior ⊗ₘ sampledHalfTsallisTrajectoryKernel
    arms harms eta selector loss.environment
  let observedSuccessorSum := fun
      (sample : Env × ((k : Nat) -> Action × Real)) =>
    (Finset.range horizon).sum (fun n =>
      sampledHalfTsallisObservedSuccessorStabilityAt
        arms harms eta n sample)
  let predictableSuccessorSum := fun
      (sample : Env × ((k : Nat) -> Action × Real)) =>
    (Finset.range horizon).sum (fun n =>
      sampledHalfTsallisSuccessorStabilityAt
        arms harms eta loss n sample)
  let halfPowerSum := fun
      (sample : Env × ((k : Nat) -> Action × Real)) =>
    (Finset.range horizon).sum (fun n =>
      sampledHalfTsallisHalfPowerBoundAt (Env := Env)
        arms harms eta n (sampledHalfTsallisHistoryAt n sample))
  let penalty :=
    ((powerSum arms (1 / 2 : Real)
          (initialHalfTsallisDistribution arms harms eta) -
        powerSum arms (1 / 2 : Real) q) /
      (1 - (1 / 2 : Real))) / eta
  let rhs := fun (sample : Env × ((k : Nat) -> Action × Real)) =>
    sampledHalfTsallisInitialStability arms harms eta sample +
      observedSuccessorSum sample + penalty
  haveI : IsProbabilityMeasure mu := inferInstance
  have hmoment :=
    integral_sampledHalfTsallisObservedEstimatedRegret_eq_environmentRegret
      prior arms harms eta loss q hq horizon
  dsimp only at hmoment
  have hinitial := integral_sampledHalfTsallisInitialStability_le_halfPower
    prior arms harms eta heta loss
  dsimp only at hinitial
  have hsuccessorIntegrable (n : Nat) :
      Integrable (sampledHalfTsallisObservedSuccessorStabilityAt
        arms harms eta n) mu :=
    (integrable_sampledHalfTsallisSuccessorStabilitiesAt_canonical
      prior arms harms eta loss n).2
  have hsuccessorSumIntegrable : Integrable observedSuccessorSum mu := by
    unfold observedSuccessorSum
    exact IntegrabilitySums.integrable_finset_sum mu (Finset.range horizon)
      (fun n sample => sampledHalfTsallisObservedSuccessorStabilityAt
        arms harms eta n sample)
      (fun n _hn => hsuccessorIntegrable n)
  have hrhsIntegrable : Integrable rhs mu := by
    unfold rhs
    exact (hinitial.1.add hsuccessorSumIntegrable).add (integrable_const _)
  have hpathwise : ∀ᵐ sample ∂mu,
      sampledHalfTsallisObservedEstimatedRegret
          arms harms eta q horizon sample <= rhs sample := by
    filter_upwards [] with sample
    simpa [sampledHalfTsallisObservedEstimatedRegret, rhs,
      observedSuccessorSum, penalty] using
      (sampledHalfTsallis_observedEstimatedRegret_le
        arms harms eta heta q hq sample horizon)
  have hintegrated := integral_mono_ae hmoment.1 hrhsIntegrable hpathwise
  have hrhsIntegral : integral mu rhs =
      integral mu (sampledHalfTsallisInitialStability arms harms eta) +
        integral mu observedSuccessorSum + penalty := by
    unfold rhs
    have hinner := integral_add hinitial.1 hsuccessorSumIntegrable
    have hpenalty : Integrable
        (fun _sample : Env × ((k : Nat) -> Action × Real) => penalty) mu :=
      integrable_const _
    have houter := integral_add (hinitial.1.add hsuccessorSumIntegrable)
      hpenalty
    calc
      integral mu (fun sample =>
          sampledHalfTsallisInitialStability arms harms eta sample +
            observedSuccessorSum sample + penalty) =
          integral mu (fun sample =>
            sampledHalfTsallisInitialStability arms harms eta sample +
              observedSuccessorSum sample) +
            integral mu (fun _sample : Env × ((k : Nat) -> Action × Real) =>
              penalty) := by
        simpa only [Pi.add_apply] using houter
      _ = (integral mu (sampledHalfTsallisInitialStability arms harms eta) +
            integral mu observedSuccessorSum) + penalty := by
        have hinner' : integral mu (fun sample =>
            sampledHalfTsallisInitialStability arms harms eta sample +
              observedSuccessorSum sample) =
            integral mu (sampledHalfTsallisInitialStability arms harms eta) +
              integral mu observedSuccessorSum := by
          simpa [mu] using hinner
        rw [hinner']
        simp
      _ = _ := by ring
  rw [hrhsIntegral] at hintegrated
  have hsuccessorAll : ∀ᵐ sample ∂mu, ∀ n,
      sampledHalfTsallisObservedSuccessorStabilityAt
          arms harms eta n sample =
        sampledHalfTsallisSuccessorStabilityAt
          arms harms eta loss n sample := by
    rw [ae_all_iff]
    intro n
    exact sampledHalfTsallisObservedSuccessorStabilityAt_eq_predictable_ae
      prior arms harms eta loss n
  have hsuccessorAE : observedSuccessorSum =ᵐ[mu]
      predictableSuccessorSum := by
    filter_upwards [hsuccessorAll] with sample hsample
    unfold observedSuccessorSum predictableSuccessorSum
    exact Finset.sum_congr rfl fun n _hn => hsample n
  have hsuccessorBoundBase :=
    integral_sum_sampledHalfTsallisSuccessorStability_le_integral_sum_halfPowerStabilityBound_canonical
      prior horizon arms harms eta heta loss
  dsimp only at hsuccessorBoundBase
  have hsuccessorBound : integral mu observedSuccessorSum <=
      integral mu halfPowerSum := by
    calc
      integral mu observedSuccessorSum =
          integral mu predictableSuccessorSum := integral_congr_ae hsuccessorAE
      _ <= integral mu halfPowerSum := by
        simpa [mu, selector, predictableSuccessorSum, halfPowerSum] using
          hsuccessorBoundBase
  calc
    integral mu (sampledHalfTsallisPredictableEnvironmentRegret
        arms harms eta loss q horizon) =
        integral mu (sampledHalfTsallisObservedEstimatedRegret
          arms harms eta q horizon) := hmoment.2.2.symm
    _ <= integral mu (sampledHalfTsallisInitialStability arms harms eta) +
        integral mu observedSuccessorSum + penalty := hintegrated
    _ <= 2 * eta * powerSum arms (1 / 2 : Real)
          (initialHalfTsallisDistribution arms harms eta) +
        integral mu halfPowerSum + penalty := by
      linarith [hinitial.2, hsuccessorBound]

end Tsallis
end BanditRLProof
