#!/usr/bin/env python3
"""Verify the anonymous ABRL artifact without trusting its authoring tree."""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "ARTIFACT_MANIFEST.json"

# Identity-specific producer checks deliberately remain outside the anonymous
# archive.  Embedding names, split strings, unsalted digests, or a membership
# oracle here would itself disclose the private blacklist.  This extracted
# verifier checks generic path/email leaks and the producer-generated byte
# manifest; the out-of-archive positive-allowlist builder performs the private
# identity scan before hashing these immutable payload bytes.
WINDOWS_PATH = re.compile(
    br"(?i)(?<![a-z])[a-z]:[\\/](?:users[\\/][^\\/\s]+|home[\\/][^\\/\s]+|wt[\\/]|code[\\/])"
)
HOST_HOME = re.compile(br"(?i)/(?:home|users)/[^/\s]+/")
EMAIL = re.compile(br"(?i)\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b")
DELAYED_IMPLEMENTATION_IDS = (
    "DELAYED-FEEDBACK-SOURCE-ACCOUNTING",
    "DELAYED-FEEDBACK-CAUSAL-PROCESSING",
    "DELAYED-SAPO-ACTIVE-ALLOCATION",
    "DELAYED-SAPO-ELIMINATION-ACTION-LAW",
    "DELAYED-SAPO-GOOD-EVENT-D9-PROJECTION",
    "DELAYED-SAPO-D8-D9-ASSEMBLY",
)
DELAYED_DIAGNOSTIC_ID = "DELAYED-SAPO-D10-D12-GAP-ORDERING-AUDIT"
DELAYED_PROCESSED_PREFIX_ID = "DELAYED-SAPO-D1-ACTIVE-COUNT-WIDTH-PRODUCER"
DELAYED_TRACE_SUMMARY_ID = "DELAYED-SAPO-PROCESSED-TRACE-SUMMARY-ADAPTER"
DELAYED_ORDERED_TRANSITION_ID = "DELAYED-SAPO-ORDERED-NO-SWITCH-PROCESS-ONE"
DELAYED_ORDERED_TRACE_ID = "DELAYED-SAPO-ORDERED-NO-SWITCH-TRACE-ORDERING"
DELAYED_D11_DOMAIN_ID = "DELAYED-SAPO-D11-NONNEGATIVE-GAP-HALF-SET"
DELAYED_LINE10_INITIALIZATION_ID = (
    "DELAYED-SAPO-LINE10-ELIMINATED-ARM-INITIALIZATION"
)
DELAYED_CENTRAL_ENDPOINT_ID = "NEURIPS-2025-DELAYED-BOBW-CENTRAL-ENDPOINTS"


def fail(message):
    raise SystemExit("artifact verification failed: " + message)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_anonymous(path):
    data = path.read_bytes()
    if WINDOWS_PATH.search(data):
        fail("absolute Windows path in {}".format(path.relative_to(ROOT)))
    if HOST_HOME.search(data):
        fail("absolute host home path in {}".format(path.relative_to(ROOT)))
    if EMAIL.search(data):
        fail("email address in {}".format(path.relative_to(ROOT)))


def load_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        fail("cannot parse {}: {}".format(path.relative_to(ROOT), exc))


def verify_manifest():
    manifest = load_json(MANIFEST_PATH)
    require_anonymous(MANIFEST_PATH)
    if manifest.get("schema_version") != 1:
        fail("unsupported manifest schema")
    entries = manifest.get("files")
    if not isinstance(entries, list) or not entries:
        fail("manifest has no payload files")
    if manifest.get("file_count") != len(entries):
        fail("manifest file_count does not match payload inventory")
    seen = set()
    tree_digest = hashlib.sha256()
    for entry in entries:
        rel = entry.get("path")
        if not isinstance(rel, str) or rel.startswith(("/", "\\")) or ".." in Path(rel).parts:
            fail("unsafe manifest path: {!r}".format(rel))
        if rel in seen:
            fail("duplicate manifest path: " + rel)
        seen.add(rel)
        path = ROOT / rel
        if not path.is_file() or path.is_symlink():
            fail("missing or non-regular payload file: " + rel)
        if path.stat().st_size != entry.get("bytes"):
            fail("size mismatch: " + rel)
        if sha256(path) != entry.get("sha256"):
            fail("SHA-256 mismatch: " + rel)
        require_anonymous(path)
        tree_digest.update(rel.encode("utf-8") + b"\0")
        tree_digest.update(entry["sha256"].encode("ascii") + b"\0")
        tree_digest.update(str(entry["bytes"]).encode("ascii") + b"\n")
    if tree_digest.hexdigest() != manifest.get("source_tree_digest"):
        fail("source-tree digest mismatch")
    actual = set()
    for path in ROOT.rglob("*"):
        if path.is_symlink():
            fail("symlink in extracted artifact: " + str(path.relative_to(ROOT)))
        if path.is_file():
            actual.add(path.relative_to(ROOT).as_posix())
    expected = seen | {"ARTIFACT_MANIFEST.json"}
    extras = sorted(actual - expected)
    missing = sorted(expected - actual)
    if extras:
        fail("unmanifested extracted file: " + ", ".join(extras[:8]))
    if missing:
        fail("manifested file is absent: " + ", ".join(missing[:8]))
    return manifest


def verify_proof_graph(manifest):
    binding = manifest.get("proof_graph")
    if not isinstance(binding, dict) or type(binding.get("included")) is not bool:
        fail("manifest proof-graph inclusion flag is missing")
    graph_path = ROOT / "evidence" / "proof-graph" / "current-proof-graph.json"
    report_path = ROOT / "evidence" / "proof-graph" / "current-benchmark-report.json"
    if not binding["included"]:
        if graph_path.exists() or report_path.exists():
            fail("current proof-graph files exist while manifest marks them absent")
        return
    if not graph_path.is_file() or not report_path.is_file():
        fail("manifest marks current proof graph included but files are absent")

    graph = load_json(graph_path)
    report = load_json(report_path)
    sys.path.insert(0, str(ROOT))
    try:
        from tools.proof_graph_lab import validate_export
        validate_export(graph)
    except (ImportError, KeyError, TypeError, ValueError) as exc:
        fail("invalid current proof graph: {}".format(exc))
    finally:
        if sys.path and sys.path[0] == str(ROOT):
            sys.path.pop(0)

    report_graph = report.get("graph")
    if not isinstance(report_graph, dict):
        fail("current proof-graph report has no graph binding")
    if report_graph.get("sha256") != sha256(graph_path):
        fail("current proof-graph report SHA-256 mismatch")
    if report_graph.get("counts") != graph.get("counts"):
        fail("current proof-graph report count mismatch")


def verify_claim_ledger():
    ledger = load_json(ROOT / "evidence" / "claim-ledger.json")
    index = load_json(ROOT / "evidence" / "local_lean_declarations.json")
    declarations = index.get("declarations")
    if not isinstance(declarations, list):
        fail("declaration index has no declarations list")
    names = {row.get("full_name") for row in declarations}
    names.update(ledger["index_counts"].get("generated_declaration_exceptions", []))
    if len(declarations) != ledger["index_counts"]["source_declarations"]:
        fail("declaration-index count drift")

    records = ledger.get("source_records", {})
    impl_ids = ledger["delayed_feedback"]["implementation_facing_ids"]
    diagnostic_id = ledger["delayed_feedback"]["diagnostic_id"]
    delayed = ledger["delayed_feedback"]
    expected_record_bindings = {
        "diagnostic_id": DELAYED_DIAGNOSTIC_ID,
        "processed_prefix_id": DELAYED_PROCESSED_PREFIX_ID,
        "processed_trace_summary_id": DELAYED_TRACE_SUMMARY_ID,
        "ordered_no_switch_transition_id": DELAYED_ORDERED_TRANSITION_ID,
        "ordered_no_switch_trace_id": DELAYED_ORDERED_TRACE_ID,
        "d11_domain_id": DELAYED_D11_DOMAIN_ID,
        "line10_initialization_id": DELAYED_LINE10_INITIALIZATION_ID,
        "central_endpoint_id": DELAYED_CENTRAL_ENDPOINT_ID,
    }
    if tuple(impl_ids) != DELAYED_IMPLEMENTATION_IDS:
        fail("delayed implementation-facing record inventory drift")
    for field, expected_id in expected_record_bindings.items():
        if delayed.get(field) != expected_id:
            fail("delayed record binding drift for " + field)
    for record_id in DELAYED_IMPLEMENTATION_IDS + tuple(expected_record_bindings.values()):
        if records.get(record_id, {}).get("id") != record_id:
            fail("delayed source record self-ID drift for " + record_id)
    if any(records[item]["status"] != "compiled" for item in impl_ids):
        fail("implementation-facing delayed status is not compiled")
    impl_count = sum(len(records[item]["declarations"]) for item in impl_ids)
    if impl_count != 89:
        fail("delayed implementation count is {}, expected 89".format(impl_count))
    diagnostic = records[diagnostic_id]
    if diagnostic["status"] != "partial" or len(diagnostic["declarations"]) != 19:
        fail("D.10--D.12 diagnostic boundary drift")
    if delayed.get("diagnostic_conditional_repair_declaration_count") != 19:
        fail("D.10--D.12 diagnostic/repair count drift")
    processed_prefix_id = delayed.get("processed_prefix_id")
    processed_prefix = records.get(processed_prefix_id, {})
    if processed_prefix.get("status") != "compiled" or len(processed_prefix.get("declarations", [])) != 16:
        fail("D.1 processed-prefix producer boundary drift")
    if delayed.get("processed_prefix_declaration_count") != 16:
        fail("D.1 processed-prefix producer count drift")
    trace_summary_id = delayed.get("processed_trace_summary_id")
    trace_summary = records.get(trace_summary_id, {})
    if trace_summary.get("status") != "compiled" or len(trace_summary.get("declarations", [])) != 9:
        fail("processed-trace-summary adapter boundary drift")
    if delayed.get("processed_trace_summary_declaration_count") != 9:
        fail("processed-trace-summary adapter count drift")
    ordered_transition_id = delayed.get("ordered_no_switch_transition_id")
    ordered_transition = records.get(ordered_transition_id, {})
    if (
        ordered_transition.get("status") != "compiled"
        or len(ordered_transition.get("declarations", [])) != 15
    ):
        fail("ordered no-switch transition boundary drift")
    if delayed.get("ordered_no_switch_transition_declaration_count") != 15:
        fail("ordered no-switch transition count drift")
    ordered_trace_id = delayed.get("ordered_no_switch_trace_id")
    ordered_trace = records.get(ordered_trace_id, {})
    if (
        ordered_trace.get("status") != "compiled"
        or len(ordered_trace.get("declarations", [])) != 12
    ):
        fail("ordered no-switch trace boundary drift")
    if delayed.get("ordered_no_switch_trace_declaration_count") != 12:
        fail("ordered no-switch trace count drift")
    d11_domain_id = delayed.get("d11_domain_id")
    if d11_domain_id != DELAYED_D11_DOMAIN_ID:
        fail("D.11 nonnegative-gap domain record ID drift")
    d11_domain = records.get(d11_domain_id, {})
    if (
        d11_domain.get("status") != "compiled"
        or len(d11_domain.get("declarations", [])) != 6
    ):
        fail("D.11 nonnegative-gap domain boundary drift")
    if delayed.get("d11_domain_declaration_count") != 6:
        fail("D.11 nonnegative-gap domain count drift")
    line10_initialization_id = delayed.get("line10_initialization_id")
    if line10_initialization_id != DELAYED_LINE10_INITIALIZATION_ID:
        fail("Algorithm 5 line-10 initialization record ID drift")
    line10_initialization = records.get(line10_initialization_id, {})
    if (
        line10_initialization.get("status") != "compiled"
        or len(line10_initialization.get("declarations", [])) != 31
    ):
        fail("Algorithm 5 line-10 initialization boundary drift")
    if delayed.get("line10_initialization_declaration_count") != 31:
        fail("Algorithm 5 line-10 initialization count drift")
    central_endpoint = records.get(delayed.get("central_endpoint_id"), {})
    if central_endpoint.get("status") != "partial":
        fail("delayed central endpoint status drift")
    if delayed.get("paper_endpoint_verified") is not False:
        fail("delayed paper endpoint verification flag drift")
    if delayed.get("source_audit_declaration_count") != (
        impl_count
        + len(diagnostic["declarations"])
        + len(processed_prefix["declarations"])
        + len(trace_summary["declarations"])
        + len(ordered_transition["declarations"])
        + len(ordered_trace["declarations"])
        + len(d11_domain["declarations"])
        + len(line10_initialization["declarations"])
    ):
        fail("delayed source-audit total drift")
    delayed_directory_rows = [
        row for row in declarations
        if str(row.get("file", "")).startswith("BanditRLProof/DelayedFeedback/")
    ]
    delayed_generic_rows = [
        row for row in delayed_directory_rows
        if row.get("file") == "BanditRLProof/DelayedFeedback/MultiRegimeContract.lean"
    ]
    if (
        delayed.get("generic_multiregime_contract_declaration_count") != 5
        or len(delayed_generic_rows) != 5
    ):
        fail("DelayedFeedback generic multi-regime count drift")
    if delayed.get("directory_declaration_count") != 202 or len(delayed_directory_rows) != 202:
        fail("DelayedFeedback directory count drift")
    source_audit_ids = impl_ids + [
        diagnostic_id,
        processed_prefix_id,
        trace_summary_id,
        ordered_transition_id,
        ordered_trace_id,
        d11_domain_id,
        line10_initialization_id,
    ]
    source_audit_names = {
        name
        for record_id in source_audit_ids
        for name in records[record_id].get("declarations", [])
    }
    expected_source_audit_names = {
        row.get("full_name")
        for row in delayed_directory_rows
        if row.get("file")
        != "BanditRLProof/DelayedFeedback/MultiRegimeContract.lean"
    }
    if source_audit_names != expected_source_audit_names:
        fail("delayed source-audit declaration set drift")

    missing_names = []
    for record in records.values():
        for name in record.get("declarations", []):
            if name not in names:
                missing_names.append(name)
    if missing_names:
        fail("claim ledger references missing declarations: " + ", ".join(sorted(missing_names)[:8]))

    planned = records[ledger["matched_workflow_study"]["source_record_id"]]
    if planned["status"] != "planned" or planned["declarations"]:
        fail("target-drift study is not a zero-result planned record")
    if ledger["matched_workflow_study"].get("numerical_results_present") is not False:
        fail("target-drift result boundary is not explicit")

    graph = ledger["proof_graph"]
    expected = {
        "standalone_fixed_charge_sum": 1238,
        "union_fixed_charge": 1046,
        "shared_declaration_count": 175,
        "best_zdd_nonterminal_nodes": 1163,
        "cng_root_count": 8,
    }
    for key, value in expected.items():
        if graph.get(key) != value:
            fail("proof-graph evidence drift for {}".format(key))


def verify_theorem_audit_comparison():
    comparison = load_json(ROOT / "evidence" / "theorem-audit-comparison.json")
    ledger = load_json(ROOT / "evidence" / "claim-ledger.json")
    if comparison != ledger.get("theorem_audit_comparison"):
        fail("theorem-audit comparison/claim-ledger mismatch")
    rows = comparison.get("rows")
    expected_ids = [
        "textbook-chapter-15-scoped-positive-control",
        "delayed-bobw-source-frozen-audit",
        "succinct-lower-bound-source-frozen-audit",
        "stochastic-gradient-bandit-source-frozen-audit",
    ]
    if (
        comparison.get("schema_version") != 1
        or not isinstance(rows, list)
        or [row.get("id") for row in rows] != expected_ids
    ):
        fail("theorem-audit comparison row inventory/order drift")
    by_id = {row["id"]: row for row in rows}
    if len(by_id) != len(rows):
        fail("theorem-audit comparison row IDs are not unique")

    records = ledger.get("source_records", {})
    delayed = ledger.get("delayed_feedback", {})
    delayed_ids = delayed.get("implementation_facing_ids", []) + [
        delayed.get("diagnostic_id"),
        delayed.get("processed_prefix_id"),
        delayed.get("processed_trace_summary_id"),
        delayed.get("ordered_no_switch_transition_id"),
        delayed.get("ordered_no_switch_trace_id"),
        delayed.get("d11_domain_id"),
        delayed.get("line10_initialization_id"),
    ]
    specs = {
        expected_ids[0]: {
            "role": "scoped_positive_control",
            "evidence_record_ids": [
                "TEXTBOOK-PART-IV-CH15-GAUSSIAN-MINIMAX-LOWER-BOUND"
            ],
            "central_endpoint_record_id":
                "TEXTBOOK-PART-IV-CH15-GAUSSIAN-MINIMAX-LOWER-BOUND",
            "promotion_status": "compiled",
            "compiled_declaration_count": 12,
            "scoped_endpoint_verified": True,
        },
        expected_ids[1]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-SCHLISSELBERG-LANCEWICKI-AUER-MANSOUR-2025-DELAYED-BOBW",
            "evidence_record_ids": delayed_ids,
            "central_endpoint_record_id": delayed.get("central_endpoint_id"),
            "promotion_status": "partial",
            "compiled_declaration_count": 197,
            "declaration_count_breakdown": {
                "implementation_facing": 89,
                "diagnostic_conditional_repair": 19,
                "processed_prefix": 16,
                "processed_trace_summary_adapter": 9,
                "ordered_no_switch_transition": 15,
                "ordered_no_switch_trace_ordering": 12,
                "nonnegative_gap_d11_domain": 6,
                "line10_eliminated_arm_initialization": 31,
            },
        },
        expected_ids[2]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-ZENG-HONORIO-2025-SUCCINCT-LOWER-BOUNDS",
            "evidence_record_ids": [
                "NEURIPS-2025-SUCCINCT-LOWER-BOUND-GEOMETRY-AUDIT"
            ],
            "central_endpoint_record_id":
                "NEURIPS-2025-SUCCINCT-LOWER-BOUND-GEOMETRY-AUDIT",
            "promotion_status": "partial",
            "compiled_declaration_count": 54,
        },
        expected_ids[3]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-BAUDRY-JOHNSON-VARY-PIKEBURKE-REBESCHINI-2025-SGB",
            "evidence_record_ids": [
                "NEURIPS-2025-STOCHASTIC-GRADIENT-BANDIT-MECHANISM-AUDIT"
            ],
            "central_endpoint_record_id":
                "NEURIPS-2025-STOCHASTIC-GRADIENT-BANDIT-MECHANISM-AUDIT",
            "promotion_status": "partial",
            "compiled_declaration_count": 135,
            "declaration_count_breakdown": {
                "finite_action_algebra": 26,
                "generated_history_and_kernel_bridge": 18,
                "two_arm_zero_sum_and_equation_11": 18,
                "source_c_and_equation_8": 14,
                "generated_equation_8_kernel_bridge": 4,
                "fixed_history_successor_recurrence": 10,
                "two_arm_initial_recurrence": 3,
                "measurable_contract_and_cond_distrib_transport": 25,
                "path_integrability_and_conditional_recurrence": 17,
            },
        },
    }
    freeze = load_json(ROOT / "evidence" / "source-freeze.json")
    freeze_cards = {row.get("card_id") for row in freeze.get("papers", [])}
    index = load_json(ROOT / "evidence" / "local_lean_declarations.json")
    index_names = {
        row.get("full_name") for row in index.get("declarations", [])
    }
    for row_id, spec in specs.items():
        row = by_id[row_id]
        for key, expected in spec.items():
            if row.get(key) != expected:
                fail("theorem-audit comparison {} drift for {}".format(key, row_id))
        if (
            not isinstance(row.get("contract_stress"), list)
            or not row["contract_stress"]
            or not isinstance(row.get("strongest_compiled_bridge"), str)
            or not row["strongest_compiled_bridge"]
            or not isinstance(row.get("scope_boundary"), str)
            or not row["scope_boundary"]
        ):
            fail("theorem-audit comparison has an empty evidence field for " + row_id)
        try:
            evidence_records = [records[item] for item in spec["evidence_record_ids"]]
            central = records[spec["central_endpoint_record_id"]]
        except (KeyError, TypeError):
            fail("theorem-audit comparison references a missing source record")
        if sum(len(record.get("declarations", [])) for record in evidence_records) != spec["compiled_declaration_count"]:
            fail("theorem-audit comparison declaration count drift for " + row_id)
        evidence_names = [
            name
            for record in evidence_records
            for name in record.get("declarations", [])
        ]
        if len(set(evidence_names)) != spec["compiled_declaration_count"]:
            fail("theorem-audit comparison declaration overlap drift for " + row_id)
        if any(name not in index_names for name in evidence_names):
            fail("theorem-audit comparison references an unindexed declaration")
        if spec["role"] == "source_frozen_external_audit":
            if (
                row.get("source_freeze_card_id") not in freeze_cards
                or central.get("status") != "partial"
                or row.get("paper_endpoint_verified") is not False
                or not isinstance(row.get("blocking_obligations"), list)
                or not row["blocking_obligations"]
            ):
                fail("external theorem-audit endpoint boundary drift for " + row_id)
        elif (
            central.get("status") != "compiled"
            or row.get("scoped_endpoint_verified") is not True
            or row.get("blocking_obligations") != []
            or "paper_endpoint_verified" in row
        ):
            fail("Chapter 15 scoped positive-control boundary drift")

    for rel in (
        "evidence/delayed-feedback-proof-obligations.md",
        "evidence/succinct-lower-bound-proof-obligations.md",
        "evidence/stochastic-gradient-bandit-proof-obligations.md",
    ):
        if not (ROOT / rel).is_file():
            fail("missing theorem-audit proof-obligation ledger: " + rel)


def verify_source_freeze():
    freeze = load_json(ROOT / "evidence" / "source-freeze.json")
    papers = freeze.get("papers", [])
    if len(papers) != 3:
        fail("source freeze must contain exactly three papers")
    if freeze.get("selection_status") != (
        "source_locked_with_record_specific_timing"
    ):
        fail("source-lock portfolio timing status drift")
    expected_timing = {
        "PPR-SCHLISSELBERG-LANCEWICKI-AUER-MANSOUR-2025-DELAYED-BOBW":
            "co_published_with_initial_feasibility_slice",
        "PPR-ZENG-HONORIO-2025-SUCCINCT-LOWER-BOUNDS":
            "locked_before_case_specific_lean_slice",
        "PPR-BAUDRY-JOHNSON-VARY-PIKEBURKE-REBESCHINI-2025-SGB":
            "locked_before_case_specific_lean_slice",
    }
    timing = {
        row.get("card_id"): row.get("selection_timing") for row in papers
    }
    if timing != expected_timing:
        fail("source-lock case-specific timing drift")
    if "does not assert that every case was frozen" not in freeze.get(
        "timing_note", ""
    ):
        fail("source-lock timing limitation is missing")
    statuses = {row.get("initial_status") for row in papers}
    if "source_frozen_not_started" not in statuses or "source_frozen_reserve_not_started" not in statuses:
        fail("source-freeze non-completion statuses are missing")
    for paper in papers:
        digest = paper.get("camera_ready_sha256", "")
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            fail("invalid source PDF digest")
        if not paper.get("camera_ready_url", "").startswith("https://"):
            fail("source PDF URL is not HTTPS")


def verify_anonymous_base(manifest):
    base = load_json(ROOT / "evidence" / "anonymous-base-manifest.json")
    if base.get("git_object_database_included") is not False:
        fail("anonymous supplement must not contain a Git object database")
    if base.get("materializable_by_target_drift_runner") is not False:
        fail("target-drift materialization boundary is not explicit")
    digest = hashlib.sha256()
    for row in base.get("files", []):
        path = ROOT / row["path"]
        if not path.is_file() or sha256(path) != row["sha256"]:
            fail("anonymous base file mismatch: " + row["path"])
        digest.update(row["path"].encode("utf-8") + b"\0")
        digest.update(row["sha256"].encode("ascii") + b"\n")
    if digest.hexdigest() != base.get("tree_sha256"):
        fail("anonymous base tree digest mismatch")
    if manifest.get("anonymous_base", {}).get("tree_sha256") != base.get("tree_sha256"):
        fail("manifest/anonymous-base digest mismatch")
    if manifest.get("anonymous_base", {}).get("target_drift_materialization_ready") is not False:
        fail("manifest overstates target-drift materialization readiness")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    manifest = verify_manifest()
    verify_claim_ledger()
    verify_source_freeze()
    verify_theorem_audit_comparison()
    verify_anonymous_base(manifest)
    verify_proof_graph(manifest)
    print(json.dumps({
        "artifact_verified": True,
        "file_count": len(manifest["files"]),
        "source_tree_digest": manifest["source_tree_digest"],
        "proof_graph_included": manifest["proof_graph"]["included"],
        "theorem_audit_comparison_verified": True,
        "target_drift_results_present": False,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
