#!/usr/bin/env python3
"""Verify the anonymous ABRL artifact without trusting its authoring tree."""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


# The verifier imports packaged helper code after checking the manifest.  Keep
# repeated verification side-effect free so a first pass cannot create an
# unmanifested __pycache__ entry that makes a second pass fail.
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "ARTIFACT_MANIFEST.json"

# Identity-specific producer checks deliberately remain outside the anonymous
# archive.  Embedding names, split strings, unsalted digests, or a membership
# oracle here would itself disclose the private blacklist.  This extracted
# verifier checks generic path/email leaks and the producer-generated byte
# manifest; the out-of-archive positive-allowlist builder performs the private
# identity scan before hashing these immutable payload bytes.
WINDOWS_PATH = re.compile(
    br"(?i)(?<![a-z])[a-z]:[\\/](?:users[\\/][^\\/\s]+|home[\\/][^\\/\s]+|wt[\\/]|code[\\/])"
)
HOST_HOME = re.compile(br"(?i)/(?:home|users)/[^/\s]+/")
EMAIL = re.compile(br"(?i)\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b")
DELAYED_IMPLEMENTATION_IDS = (
    "DELAYED-FEEDBACK-SOURCE-ACCOUNTING",
    "DELAYED-FEEDBACK-CAUSAL-PROCESSING",
    "DELAYED-SAPO-ACTIVE-ALLOCATION",
    "DELAYED-SAPO-ELIMINATION-ACTION-LAW",
    "DELAYED-SAPO-GOOD-EVENT-D9-PROJECTION",
    "DELAYED-SAPO-D8-D9-ASSEMBLY",
)
DELAYED_DIAGNOSTIC_ID = "DELAYED-SAPO-D10-D12-GAP-ORDERING-AUDIT"
DELAYED_PROCESSED_PREFIX_ID = "DELAYED-SAPO-D1-ACTIVE-COUNT-WIDTH-PRODUCER"
DELAYED_TRACE_SUMMARY_ID = "DELAYED-SAPO-PROCESSED-TRACE-SUMMARY-ADAPTER"
DELAYED_ORDERED_TRANSITION_ID = "DELAYED-SAPO-ORDERED-NO-SWITCH-PROCESS-ONE"
DELAYED_ORDERED_TRACE_ID = "DELAYED-SAPO-ORDERED-NO-SWITCH-TRACE-ORDERING"
DELAYED_D11_DOMAIN_ID = "DELAYED-SAPO-D11-NONNEGATIVE-GAP-HALF-SET"
DELAYED_LINE10_INITIALIZATION_ID = (
    "DELAYED-SAPO-LINE10-ELIMINATED-ARM-INITIALIZATION"
)
DELAYED_CENTRAL_ENDPOINT_ID = "NEURIPS-2025-DELAYED-BOBW-CENTRAL-ENDPOINTS"
SGB_AUDIT_ID = "NEURIPS-2025-STOCHASTIC-GRADIENT-BANDIT-MECHANISM-AUDIT"
SGB_FOLLOW_ON_ID = "NEURIPS-2025-SGB-PHASE-TRANSITION-FOLLOWON"
SGB_THEOREM_ONE_STACK_DECLARATION_COUNT = 215
SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATION_COUNT = 8
SGB_HISTORICAL_DECLARATION_COUNT = (
    SGB_THEOREM_ONE_STACK_DECLARATION_COUNT
    + SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATION_COUNT
)
SGB_COROLLARY_ONE_DECLARATION_COUNT = 23
SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT = 24
SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT = 26
SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT = 7
SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT = 8
SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT = 13
SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATION_COUNT = 28
SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT = 8
SGB_TOTAL_DECLARATION_COUNT = (
    SGB_HISTORICAL_DECLARATION_COUNT
    + SGB_COROLLARY_ONE_DECLARATION_COUNT
    + SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT
    + SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT
    + SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT
    + SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT
    + SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT
    + SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATION_COUNT
    + SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT
)
SGB_THEOREM_FOUR_CONTRACT_AUDIT_FILE = (
    "BanditRLProof/Algorithms/"
    "StochasticGradientBanditTheoremFourContractAudit.lean"
)
SGB_COROLLARY_ONE_FILE = (
    "BanditRLProof/Algorithms/StochasticGradientBanditCorollaryOne.lean"
)
SGB_THEOREM_TWO_STARVATION_FILE = (
    "BanditRLProof/Algorithms/"
    "StochasticGradientBanditTheoremTwoStarvation.lean"
)
SGB_THEOREM_TWO_NTH_PULL_FILE = (
    "BanditRLProof/Algorithms/"
    "StochasticGradientBanditTheoremTwoNthPull.lean"
)
SGB_THEOREM_TWO_LATENT_REWARD_FILE = (
    "BanditRLProof/Algorithms/"
    "StochasticGradientBanditTheoremTwoLatentReward.lean"
)
SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE = (
    "BanditRLProof/Algorithms/"
    "StochasticGradientBanditTheoremTwoNativeTrajectory.lean"
)
SGB_THEOREM_TWO_BRANCH_LOCALITY_GENERIC_BRIDGE_FILE = (
    "BanditRLProof/KernelIndependentExtension.lean"
)
SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATIONS = frozenset({
    "BanditRLProof.StochasticGradientBandit.theoremFourStepOneMargin",
    "BanditRLProof.StochasticGradientBandit.theoremFourStepFourSurvivalLowerBound",
    "BanditRLProof.StochasticGradientBandit.theoremFourStepOneMargin_pos",
    "BanditRLProof.StochasticGradientBandit.theoremFourStepFourSurvivalLowerBound_pos",
    "BanditRLProof.StochasticGradientBandit.theoremFourStepFour_survivalMass_ge",
    "BanditRLProof.StochasticGradientBandit.theoremFourStepFour_survivalMass_pos",
    "BanditRLProof.StochasticGradientBandit.theoremFourFiniteGeometricPhaseMass_le_inv",
    "BanditRLProof.StochasticGradientBandit.theoremFourFiniteTransientMass_le_inv",
})
SGB_COROLLARY_ONE_REPRESENTATIVE_DECLARATIONS = frozenset({
    "BanditRLProof.StochasticGradientBandit.twoArmSampledPseudoRegret_le_gap_mul_horizon",
    "BanditRLProof.StochasticGradientBandit.sourceTheoremOne_constant_le_inv_eta",
    "BanditRLProof.StochasticGradientBandit.corollaryOne_piecewise_bound",
    "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDDirac_corollaryOne_piecewise",
    "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDDirac_corollaryOne",
})
SGB_THEOREM_TWO_STARVATION_REPRESENTATIVE_DECLARATIONS = frozenset({
    "BanditRLProof.StochasticGradientBandit.twoArmStepOneStarvationEvent",
    "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmStepOneStarvationEvent",
    "BanditRLProof.StochasticGradientBandit.twoArmSampledPseudoRegret_eq_gap_mul_horizon_sub_of_optimalPullCount_eq",
    "BanditRLProof.StochasticGradientBandit.twoArmStepOneStarvationEvent_sampledPseudoRegret_eq",
    "BanditRLProof.StochasticGradientBandit.twoArmStepOneStarvationEvent_charge_mul_probability_le_integral",
    "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDStepOneStarvationEvent_charge_mul_probability_le_integral",
    "BanditRLProof.StochasticGradientBandit.twoArmTerminalOptimalPullCountEvent",
    "BanditRLProof.StochasticGradientBandit.twoArmOptimalPullCountBelowEvent_eq_iUnion_terminalCount",
    "BanditRLProof.StochasticGradientBandit.twoArmTerminalOptimalPullCountEvent_sampledPseudoRegret_eq",
})
SGB_THEOREM_TWO_NTH_PULL_REPRESENTATIVE_DECLARATIONS = frozenset({
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullTime",
    "BanditRLProof.StochasticGradientBandit.isStoppingTime_twoArmNthOptimalPullTime",
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullTime_eq_top_iff",
    "BanditRLProof.StochasticGradientBandit.twoArmOptimalPullCount_lt_succ_of_nthOptimalPullTime_eq_top",
    "BanditRLProof.StochasticGradientBandit.twoArmOptimalPullCount_lt_of_fin_nthOptimalPullTime_eq_top",
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullTime_spec",
    "BanditRLProof.StochasticGradientBandit.measurable_twoArmNthOptimalPullReward",
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullReward_eq_of_time_eq",
    "BanditRLProof.StochasticGradientBandit.measurable_twoArmNthOptimalPullSuccessProbability",
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullSuccessProbability_eq_of_time_eq",
})
SGB_THEOREM_TWO_LATENT_REWARD_DECLARATIONS = frozenset({
    "BanditRLProof.UCB.armStreamMeasure_map_fixedArmFinitePrefix_eq_pi",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryMeasure_map_fixedArmFinitePrefix_eq_pi",
    "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDLatentTrajectoryMeasure",
    "BanditRLProof.StochasticGradientBandit.twoArmTrajectoryMeasure_dirac_eq_map_trajectoryKernel",
    "BanditRLProof.StochasticGradientBandit.stationaryRewardKernelAt_twoArmFixedIIDRewardKernel_eq",
    "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDLatentTrajectoryMeasure_map_optimalPrefix_eq_pi",
    "BanditRLProof.StochasticGradientBandit.twoArmNthOptimalPullReward_eq_latentCoordinate_ae",
})
SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATIONS = frozenset({
    "BanditRLProof.UCB.armStreamMeasure_map_frestrictLe_eq_pi",
    "BanditRLProof.UCB.extendArmStreamFinitePrefix",
    "BanditRLProof.UCB.measurable_extendArmStreamFinitePrefix",
    "BanditRLProof.UCB.extendArmStreamFinitePrefix_apply_of_le",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_frestrictLe_eq_of_streamPrefix_eq",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixKernel",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_frestrictLe_eq_prefixKernel_comap",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryMeasure_map_stream_visiblePrefix_eq",
})
SGB_THEOREM_TWO_ACTION_READOUT_BRANCH_LOCALITY_INTERFACE_AND_COUNT_CAP_SCAFFOLD_DECLARATIONS = frozenset({
    "BanditRLProof.UCB.armStreamMeasure_map_output_coordinate_compProd_comap_without_eq_prod",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction",
    "BanditRLProof.Thompson.measurable_latentArmStreamVisiblePrefixNextAction",
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward",
    "BanditRLProof.Thompson.measurable_latentArmStreamVisibleNextReward",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextActionBranchKernel",
    "BanditRLProof.Thompson.latentArmStreamPrefixCountCap",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamPrefixCountCap",
    "BanditRLProof.Thompson.realHistoryPullCount_extendPairHistorySucc",
    "BanditRLProof.Thompson.LatentArmStreamVisiblePrefixNextActionBranchLocality",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_coordinate_branch_eq_prod_of_locality",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryMeasure_map_visiblePrefix_nextAction_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_eq_selectedCoordinate_ae",
})
SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_prefix_next_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamFeedback_eq_of_withoutCoordinate_eq_of_selectedCoordinate_ne",
    "BanditRLProof.Thompson.historyStepKernel_apply_eq_of_withoutCoordinate_eq_of_target_count_lt",
    "BanditRLProof.Thompson.latentArmStreamNextActionNeSet",
    "BanditRLProof.Thompson.latentArmStreamInitialSafeArmSet",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamNextActionNeSet",
    "BanditRLProof.Thompson.historyStepKernel_apply_restrict_nextActionNe_eq_of_withoutCoordinate_eq",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_frestrictLe_zero",
    "BanditRLProof.Thompson.singletonPairHistory_preimage_latentArmStreamPrefixCountCap_zero",
    "BanditRLProof.Thompson.latentArmStreamPrefixCountCapLocality_zero",
    "BanditRLProof.Thompson.latentArmStreamPrefixCountLt",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamPrefixCountLt",
    "BanditRLProof.Thompson.latentArmStreamPrefixCountEq",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamPrefixCountEq",
    "BanditRLProof.Thompson.mem_latentArmStreamPrefixCountCap_extendPairHistorySucc_iff",
    "BanditRLProof.Thompson.latentArmStreamPrefixCountCap_of_extendPairHistorySucc_mem",
    "BanditRLProof.Thompson.selectedCoordinate_ne_of_extendPairHistorySucc_mem_prefixCountCap",
    "BanditRLProof.Thompson.latentArmStreamSuccessorCountCap_preimage",
    "BanditRLProof.Thompson.latentArmStreamSuccessorCountCapSection",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamSuccessorCountCapSection",
    "BanditRLProof.Thompson.historyStepKernel_apply_restrict_successorCountCap_eq_of_withoutCoordinate_eq",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_frestrictLe_restrict_countCap_succ",
    "BanditRLProof.Thompson.latentArmStreamTrajectoryKernel_map_frestrictLe_restrict_countCap_eq_of_withoutCoordinate_eq",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextActionBranchLocality_of_prefixCountCapLocality",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextActionBranchLocality",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_coordinate_branch_eq_prod",
    "BanditRLProof.Measure.compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq",
    "BanditRLProof.Measure.map_compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq",
})
SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.measurable_latentArmStreamSelectedCoordinate",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_selectedCoordinate_branch_eq_prod",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_selectedCoordinate_mixed_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_selectedCoordinate_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_joint_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_condDistrib_ae_eq_nu",
    "BanditRLProof.Thompson.latentArmStreamVisibleTrajectoryMeasure_nextReward_joint_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleTrajectoryMeasure_nextReward_condDistrib_ae_eq_nu",
})
SGB_THEOREM_TWO_BRANCH_LOCALITY_GENERIC_BRIDGE_DECLARATIONS = frozenset({
    "BanditRLProof.Measure.compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq",
    "BanditRLProof.Measure.map_compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq",
})
SGB_THEOREM_TWO_BRANCH_LOCALITY_NATIVE_DECLARATIONS = (
    SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATIONS
    - SGB_THEOREM_TWO_BRANCH_LOCALITY_GENERIC_BRIDGE_DECLARATIONS
)
SGB_THEOREM_TWO_NATIVE_TRAJECTORY_DECLARATIONS = (
    SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATIONS
    | SGB_THEOREM_TWO_ACTION_READOUT_BRANCH_LOCALITY_INTERFACE_AND_COUNT_CAP_SCAFFOLD_DECLARATIONS
    | SGB_THEOREM_TWO_BRANCH_LOCALITY_NATIVE_DECLARATIONS
    | SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATIONS
)
SGB_THEOREM_TWO_ACTION_FACTORIZATION_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamTrajectoryMeasure_map_visiblePrefix_nextAction_eq_compProd",
})
SGB_THEOREM_TWO_PATHWISE_COORDINATE_SUPPORT_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_eq_selectedCoordinate_ae",
})
SGB_THEOREM_TWO_BRANCH_PRODUCT_CONSUMER_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_coordinate_branch_eq_prod_of_locality",
})
SGB_THEOREM_TWO_UNCONDITIONAL_BRANCH_PRODUCT_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_coordinate_branch_eq_prod",
})
SGB_THEOREM_TWO_FRESHNESS_ENDPOINT_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_joint_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleNextReward_condDistrib_ae_eq_nu",
    "BanditRLProof.Thompson.latentArmStreamVisibleTrajectoryMeasure_nextReward_joint_eq_compProd",
    "BanditRLProof.Thompson.latentArmStreamVisibleTrajectoryMeasure_nextReward_condDistrib_ae_eq_nu",
})
SGB_THEOREM_TWO_BRANCH_LOCALITY_CONTRACT_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.LatentArmStreamVisiblePrefixNextActionBranchLocality",
})
SGB_THEOREM_TWO_BRANCH_LOCALITY_CRITICAL_THEOREM_FILES = {
    "BanditRLProof.Measure.compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq":
        SGB_THEOREM_TWO_BRANCH_LOCALITY_GENERIC_BRIDGE_FILE,
    "BanditRLProof.Measure.map_compProd_restrict_eq_of_base_restrict_eq_of_fiber_restrict_eq":
        SGB_THEOREM_TWO_BRANCH_LOCALITY_GENERIC_BRIDGE_FILE,
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextActionBranchLocality":
        SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE,
    "BanditRLProof.Thompson.latentArmStreamVisiblePrefixNextAction_coordinate_branch_eq_prod":
        SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE,
}
SGB_THEOREM_TWO_FRESHNESS_CRITICAL_THEOREM_FILES = {
    name: SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE
    for name in SGB_THEOREM_TWO_FRESHNESS_ENDPOINT_DECLARATIONS
}
SGB_THEOREM_TWO_COUNT_CAP_SCAFFOLD_DECLARATIONS = frozenset({
    "BanditRLProof.Thompson.latentArmStreamPrefixCountCap",
    "BanditRLProof.Thompson.measurableSet_latentArmStreamPrefixCountCap",
    "BanditRLProof.Thompson.realHistoryPullCount_extendPairHistorySucc",
})
SGB_THEOREM_TWO_TERMINAL_DECLARATION = (
    "BanditRLProof.StochasticGradientBandit."
    "twoArmRademacherDirac_theoremTwo_polynomialRegret"
)


def fail(message):
    raise SystemExit("artifact verification failed: " + message)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_anonymous(path):
    data = path.read_bytes()
    if WINDOWS_PATH.search(data):
        fail("absolute Windows path in {}".format(path.relative_to(ROOT)))
    if HOST_HOME.search(data):
        fail("absolute host home path in {}".format(path.relative_to(ROOT)))
    if EMAIL.search(data):
        fail("email address in {}".format(path.relative_to(ROOT)))


def load_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        fail("cannot parse {}: {}".format(path.relative_to(ROOT), exc))


def verify_manifest():
    manifest = load_json(MANIFEST_PATH)
    require_anonymous(MANIFEST_PATH)
    if manifest.get("schema_version") != 1:
        fail("unsupported manifest schema")
    entries = manifest.get("files")
    if not isinstance(entries, list) or not entries:
        fail("manifest has no payload files")
    if manifest.get("file_count") != len(entries):
        fail("manifest file_count does not match payload inventory")
    seen = set()
    tree_digest = hashlib.sha256()
    for entry in entries:
        rel = entry.get("path")
        if not isinstance(rel, str) or rel.startswith(("/", "\\")) or ".." in Path(rel).parts:
            fail("unsafe manifest path: {!r}".format(rel))
        if rel in seen:
            fail("duplicate manifest path: " + rel)
        seen.add(rel)
        path = ROOT / rel
        if not path.is_file() or path.is_symlink():
            fail("missing or non-regular payload file: " + rel)
        if path.stat().st_size != entry.get("bytes"):
            fail("size mismatch: " + rel)
        if sha256(path) != entry.get("sha256"):
            fail("SHA-256 mismatch: " + rel)
        require_anonymous(path)
        tree_digest.update(rel.encode("utf-8") + b"\0")
        tree_digest.update(entry["sha256"].encode("ascii") + b"\0")
        tree_digest.update(str(entry["bytes"]).encode("ascii") + b"\n")
    if tree_digest.hexdigest() != manifest.get("source_tree_digest"):
        fail("source-tree digest mismatch")
    actual = set()
    for path in ROOT.rglob("*"):
        if path.is_symlink():
            fail("symlink in extracted artifact: " + str(path.relative_to(ROOT)))
        if path.is_file():
            actual.add(path.relative_to(ROOT).as_posix())
    expected = seen | {"ARTIFACT_MANIFEST.json"}
    extras = sorted(actual - expected)
    missing = sorted(expected - actual)
    if extras:
        fail("unmanifested extracted file: " + ", ".join(extras[:8]))
    if missing:
        fail("manifested file is absent: " + ", ".join(missing[:8]))
    return manifest


def verify_proof_graph(manifest):
    binding = manifest.get("proof_graph")
    if not isinstance(binding, dict) or type(binding.get("included")) is not bool:
        fail("manifest proof-graph inclusion flag is missing")
    graph_path = ROOT / "evidence" / "proof-graph" / "current-proof-graph.json"
    report_path = ROOT / "evidence" / "proof-graph" / "current-benchmark-report.json"
    if not binding["included"]:
        if graph_path.exists() or report_path.exists():
            fail("current proof-graph files exist while manifest marks them absent")
        return
    if not graph_path.is_file() or not report_path.is_file():
        fail("manifest marks current proof graph included but files are absent")

    graph = load_json(graph_path)
    report = load_json(report_path)
    sys.path.insert(0, str(ROOT))
    try:
        from tools.proof_graph_lab import validate_export
        validate_export(graph)
    except (ImportError, KeyError, TypeError, ValueError) as exc:
        fail("invalid current proof graph: {}".format(exc))
    finally:
        if sys.path and sys.path[0] == str(ROOT):
            sys.path.pop(0)

    report_graph = report.get("graph")
    if not isinstance(report_graph, dict):
        fail("current proof-graph report has no graph binding")
    if report_graph.get("sha256") != sha256(graph_path):
        fail("current proof-graph report SHA-256 mismatch")
    if report_graph.get("counts") != graph.get("counts"):
        fail("current proof-graph report count mismatch")


def verify_claim_ledger():
    ledger = load_json(ROOT / "evidence" / "claim-ledger.json")
    index = load_json(ROOT / "evidence" / "local_lean_declarations.json")
    declarations = index.get("declarations")
    if not isinstance(declarations, list):
        fail("declaration index has no declarations list")
    names = {row.get("full_name") for row in declarations}
    names.update(ledger["index_counts"].get("generated_declaration_exceptions", []))
    if len(declarations) != ledger["index_counts"]["source_declarations"]:
        fail("declaration-index count drift")

    records = ledger.get("source_records", {})
    impl_ids = ledger["delayed_feedback"]["implementation_facing_ids"]
    diagnostic_id = ledger["delayed_feedback"]["diagnostic_id"]
    delayed = ledger["delayed_feedback"]
    expected_record_bindings = {
        "diagnostic_id": DELAYED_DIAGNOSTIC_ID,
        "processed_prefix_id": DELAYED_PROCESSED_PREFIX_ID,
        "processed_trace_summary_id": DELAYED_TRACE_SUMMARY_ID,
        "ordered_no_switch_transition_id": DELAYED_ORDERED_TRANSITION_ID,
        "ordered_no_switch_trace_id": DELAYED_ORDERED_TRACE_ID,
        "d11_domain_id": DELAYED_D11_DOMAIN_ID,
        "line10_initialization_id": DELAYED_LINE10_INITIALIZATION_ID,
        "central_endpoint_id": DELAYED_CENTRAL_ENDPOINT_ID,
    }
    if tuple(impl_ids) != DELAYED_IMPLEMENTATION_IDS:
        fail("delayed implementation-facing record inventory drift")
    for field, expected_id in expected_record_bindings.items():
        if delayed.get(field) != expected_id:
            fail("delayed record binding drift for " + field)
    for record_id in DELAYED_IMPLEMENTATION_IDS + tuple(expected_record_bindings.values()):
        if records.get(record_id, {}).get("id") != record_id:
            fail("delayed source record self-ID drift for " + record_id)
    if any(records[item]["status"] != "compiled" for item in impl_ids):
        fail("implementation-facing delayed status is not compiled")
    impl_count = sum(len(records[item]["declarations"]) for item in impl_ids)
    if impl_count != 89:
        fail("delayed implementation count is {}, expected 89".format(impl_count))
    diagnostic = records[diagnostic_id]
    if diagnostic["status"] != "partial" or len(diagnostic["declarations"]) != 19:
        fail("D.10--D.12 diagnostic boundary drift")
    if delayed.get("diagnostic_conditional_repair_declaration_count") != 19:
        fail("D.10--D.12 diagnostic/repair count drift")
    processed_prefix_id = delayed.get("processed_prefix_id")
    processed_prefix = records.get(processed_prefix_id, {})
    if processed_prefix.get("status") != "compiled" or len(processed_prefix.get("declarations", [])) != 16:
        fail("D.1 processed-prefix producer boundary drift")
    if delayed.get("processed_prefix_declaration_count") != 16:
        fail("D.1 processed-prefix producer count drift")
    trace_summary_id = delayed.get("processed_trace_summary_id")
    trace_summary = records.get(trace_summary_id, {})
    if trace_summary.get("status") != "compiled" or len(trace_summary.get("declarations", [])) != 9:
        fail("processed-trace-summary adapter boundary drift")
    if delayed.get("processed_trace_summary_declaration_count") != 9:
        fail("processed-trace-summary adapter count drift")
    ordered_transition_id = delayed.get("ordered_no_switch_transition_id")
    ordered_transition = records.get(ordered_transition_id, {})
    if (
        ordered_transition.get("status") != "compiled"
        or len(ordered_transition.get("declarations", [])) != 15
    ):
        fail("ordered no-switch transition boundary drift")
    if delayed.get("ordered_no_switch_transition_declaration_count") != 15:
        fail("ordered no-switch transition count drift")
    ordered_trace_id = delayed.get("ordered_no_switch_trace_id")
    ordered_trace = records.get(ordered_trace_id, {})
    if (
        ordered_trace.get("status") != "compiled"
        or len(ordered_trace.get("declarations", [])) != 12
    ):
        fail("ordered no-switch trace boundary drift")
    if delayed.get("ordered_no_switch_trace_declaration_count") != 12:
        fail("ordered no-switch trace count drift")
    d11_domain_id = delayed.get("d11_domain_id")
    if d11_domain_id != DELAYED_D11_DOMAIN_ID:
        fail("D.11 nonnegative-gap domain record ID drift")
    d11_domain = records.get(d11_domain_id, {})
    if (
        d11_domain.get("status") != "compiled"
        or len(d11_domain.get("declarations", [])) != 6
    ):
        fail("D.11 nonnegative-gap domain boundary drift")
    if delayed.get("d11_domain_declaration_count") != 6:
        fail("D.11 nonnegative-gap domain count drift")
    line10_initialization_id = delayed.get("line10_initialization_id")
    if line10_initialization_id != DELAYED_LINE10_INITIALIZATION_ID:
        fail("Algorithm 5 line-10 initialization record ID drift")
    line10_initialization = records.get(line10_initialization_id, {})
    if (
        line10_initialization.get("status") != "compiled"
        or len(line10_initialization.get("declarations", [])) != 31
    ):
        fail("Algorithm 5 line-10 initialization boundary drift")
    if delayed.get("line10_initialization_declaration_count") != 31:
        fail("Algorithm 5 line-10 initialization count drift")
    central_endpoint = records.get(delayed.get("central_endpoint_id"), {})
    if central_endpoint.get("status") != "partial":
        fail("delayed central endpoint status drift")
    if delayed.get("paper_endpoint_verified") is not False:
        fail("delayed paper endpoint verification flag drift")
    if delayed.get("source_audit_declaration_count") != (
        impl_count
        + len(diagnostic["declarations"])
        + len(processed_prefix["declarations"])
        + len(trace_summary["declarations"])
        + len(ordered_transition["declarations"])
        + len(ordered_trace["declarations"])
        + len(d11_domain["declarations"])
        + len(line10_initialization["declarations"])
    ):
        fail("delayed source-audit total drift")
    delayed_directory_rows = [
        row for row in declarations
        if str(row.get("file", "")).startswith("BanditRLProof/DelayedFeedback/")
    ]
    delayed_generic_rows = [
        row for row in delayed_directory_rows
        if row.get("file") == "BanditRLProof/DelayedFeedback/MultiRegimeContract.lean"
    ]
    if (
        delayed.get("generic_multiregime_contract_declaration_count") != 5
        or len(delayed_generic_rows) != 5
    ):
        fail("DelayedFeedback generic multi-regime count drift")
    if delayed.get("directory_declaration_count") != 202 or len(delayed_directory_rows) != 202:
        fail("DelayedFeedback directory count drift")
    source_audit_ids = impl_ids + [
        diagnostic_id,
        processed_prefix_id,
        trace_summary_id,
        ordered_transition_id,
        ordered_trace_id,
        d11_domain_id,
        line10_initialization_id,
    ]
    source_audit_names = {
        name
        for record_id in source_audit_ids
        for name in records[record_id].get("declarations", [])
    }
    expected_source_audit_names = {
        row.get("full_name")
        for row in delayed_directory_rows
        if row.get("file")
        != "BanditRLProof/DelayedFeedback/MultiRegimeContract.lean"
    }
    if source_audit_names != expected_source_audit_names:
        fail("delayed source-audit declaration set drift")

    sgb = ledger.get("stochastic_gradient_bandit", {})
    if sgb.get("source_record_id") != SGB_AUDIT_ID:
        fail("SGB source record binding drift")
    if sgb.get("follow_on_source_record_id") != SGB_FOLLOW_ON_ID:
        fail("SGB follow-on source record binding drift")
    historical_record = records.get(SGB_AUDIT_ID, {})
    follow_on_record = records.get(SGB_FOLLOW_ON_ID, {})
    if historical_record.get("id") != SGB_AUDIT_ID:
        fail("SGB source record self-ID drift")
    if follow_on_record.get("id") != SGB_FOLLOW_ON_ID:
        fail("SGB follow-on source record self-ID drift")
    if (
        historical_record.get("status") != "partial"
        or follow_on_record.get("status") != "partial"
    ):
        fail("SGB source record status drift")
    historical_declarations = historical_record.get("declarations")
    follow_on_declarations = follow_on_record.get("declarations")
    if (
        not isinstance(historical_declarations, list)
        or not isinstance(follow_on_declarations, list)
    ):
        fail("SGB source records have no declarations list")
    historical_names = set(historical_declarations)
    follow_on_names = set(follow_on_declarations)
    sgb_names = historical_names | follow_on_names
    if (
        len(historical_declarations) != SGB_HISTORICAL_DECLARATION_COUNT
        or len(historical_names) != SGB_HISTORICAL_DECLARATION_COUNT
        or len(follow_on_declarations)
        != SGB_COROLLARY_ONE_DECLARATION_COUNT
            + SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT
            + SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT
            + SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT
            + SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT
            + SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT
            + SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATION_COUNT
            + SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT
        or len(follow_on_names)
        != SGB_COROLLARY_ONE_DECLARATION_COUNT
            + SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT
            + SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT
            + SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT
            + SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT
            + SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT
            + SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATION_COUNT
            + SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT
        or historical_names & follow_on_names
        or len(sgb_names) != SGB_TOTAL_DECLARATION_COUNT
        or sgb.get("declaration_count") != SGB_TOTAL_DECLARATION_COUNT
    ):
        fail(
            "SGB source audit must contain exactly 360 unique declarations "
            "with historical 223 and separate 23+24+26+7+8+13+28+8 follow-on"
        )
    if (
        sgb.get("historical_declaration_count")
        != SGB_HISTORICAL_DECLARATION_COUNT
    ):
        fail("SGB historical declaration count drift")
    if (
        sgb.get("theorem_one_stack_declaration_count")
        != SGB_THEOREM_ONE_STACK_DECLARATION_COUNT
    ):
        fail("SGB Theorem-1 stack declaration count drift")
    if (
        sgb.get("theorem_four_contract_audit_declaration_count")
        != SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATION_COUNT
    ):
        fail("SGB Theorem-4 contract-audit declaration count drift")
    theorem_four_rows = [
        row for row in declarations
        if row.get("file") == SGB_THEOREM_FOUR_CONTRACT_AUDIT_FILE
    ]
    theorem_four_names = {row.get("full_name") for row in theorem_four_rows}
    if (
        not (ROOT / SGB_THEOREM_FOUR_CONTRACT_AUDIT_FILE).is_file()
        or len(theorem_four_rows)
        != SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATION_COUNT
        or theorem_four_names
        != SGB_THEOREM_FOUR_CONTRACT_AUDIT_DECLARATIONS
        or not theorem_four_names.issubset(sgb_names)
    ):
        fail("SGB Theorem-4 contract-audit frozen declaration/file drift")
    if (
        len(historical_names - theorem_four_names)
        != SGB_THEOREM_ONE_STACK_DECLARATION_COUNT
    ):
        fail("SGB Theorem-1 stack derived declaration count drift")
    corollary_one_rows = [
        row for row in declarations
        if row.get("file") == SGB_COROLLARY_ONE_FILE
    ]
    corollary_one_names = {
        row.get("full_name") for row in corollary_one_rows
    }
    theorem_two_starvation_rows = [
        row for row in declarations
        if row.get("file") == SGB_THEOREM_TWO_STARVATION_FILE
    ]
    theorem_two_starvation_names = {
        row.get("full_name") for row in theorem_two_starvation_rows
    }
    theorem_two_nth_pull_rows = [
        row for row in declarations
        if row.get("file") == SGB_THEOREM_TWO_NTH_PULL_FILE
    ]
    theorem_two_nth_pull_names = {
        row.get("full_name") for row in theorem_two_nth_pull_rows
    }
    theorem_two_latent_reward_rows = [
        row for row in declarations
        if row.get("file") == SGB_THEOREM_TWO_LATENT_REWARD_FILE
    ]
    theorem_two_latent_reward_names = {
        row.get("full_name") for row in theorem_two_latent_reward_rows
    }
    theorem_two_native_trajectory_rows = [
        row for row in declarations
        if row.get("file") == SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE
    ]
    theorem_two_native_trajectory_names = {
        row.get("full_name") for row in theorem_two_native_trajectory_rows
    }
    theorem_two_branch_locality_contract_rows = [
        row for row in theorem_two_native_trajectory_rows
        if row.get("full_name") in
        SGB_THEOREM_TWO_BRANCH_LOCALITY_CONTRACT_DECLARATIONS
    ]
    theorem_two_branch_locality_producer_names = {
        row.get("full_name") for row in declarations
        if row.get("full_name") in
        SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATIONS
    }
    theorem_two_branch_locality_critical_rows = {
        row.get("full_name"): row for row in declarations
        if row.get("full_name") in
        SGB_THEOREM_TWO_BRANCH_LOCALITY_CRITICAL_THEOREM_FILES
    }
    theorem_two_branch_locality_critical_metadata_valid = (
        set(theorem_two_branch_locality_critical_rows) ==
        set(SGB_THEOREM_TWO_BRANCH_LOCALITY_CRITICAL_THEOREM_FILES)
        and all(
            row.get("kind") == "theorem"
            and row.get("file") ==
                SGB_THEOREM_TWO_BRANCH_LOCALITY_CRITICAL_THEOREM_FILES[name]
            for name, row in
            theorem_two_branch_locality_critical_rows.items()
        )
    )
    if not theorem_two_branch_locality_critical_metadata_valid:
        fail("SGB Theorem-2 branch-locality theorem metadata drift")
    theorem_two_freshness_names = {
        row.get("full_name") for row in declarations
        if row.get("full_name") in
        SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATIONS
    }
    theorem_two_freshness_critical_rows = {
        row.get("full_name"): row for row in declarations
        if row.get("full_name") in
        SGB_THEOREM_TWO_FRESHNESS_CRITICAL_THEOREM_FILES
    }
    theorem_two_freshness_critical_metadata_valid = (
        set(theorem_two_freshness_critical_rows) ==
        set(SGB_THEOREM_TWO_FRESHNESS_CRITICAL_THEOREM_FILES)
        and all(
            row.get("kind") == "theorem"
            and row.get("file") ==
                SGB_THEOREM_TWO_FRESHNESS_CRITICAL_THEOREM_FILES[name]
            for name, row in theorem_two_freshness_critical_rows.items()
        )
    )
    if not theorem_two_freshness_critical_metadata_valid:
        fail("SGB Theorem-2 selected-reward freshness theorem metadata drift")
    if (
        not (ROOT / SGB_COROLLARY_ONE_FILE).is_file()
        or len(corollary_one_rows) != SGB_COROLLARY_ONE_DECLARATION_COUNT
        or not SGB_COROLLARY_ONE_REPRESENTATIVE_DECLARATIONS.issubset(
            corollary_one_names
        )
        or not (ROOT / SGB_THEOREM_TWO_STARVATION_FILE).is_file()
        or len(theorem_two_starvation_rows)
        != SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT
        or not SGB_THEOREM_TWO_STARVATION_REPRESENTATIVE_DECLARATIONS.issubset(
            theorem_two_starvation_names
        )
        or not (ROOT / SGB_THEOREM_TWO_NTH_PULL_FILE).is_file()
        or len(theorem_two_nth_pull_rows)
        != SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT
        or not SGB_THEOREM_TWO_NTH_PULL_REPRESENTATIVE_DECLARATIONS.issubset(
            theorem_two_nth_pull_names
        )
        or not (ROOT / SGB_THEOREM_TWO_LATENT_REWARD_FILE).is_file()
        or len(theorem_two_latent_reward_rows)
        != SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT
        or theorem_two_latent_reward_names
        != SGB_THEOREM_TWO_LATENT_REWARD_DECLARATIONS
        or not (ROOT / SGB_THEOREM_TWO_PREFIX_FACTORIZATION_FILE).is_file()
        or len(theorem_two_native_trajectory_rows)
        != SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT
            + SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT
            + len(SGB_THEOREM_TWO_BRANCH_LOCALITY_NATIVE_DECLARATIONS)
            + SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT
        or theorem_two_native_trajectory_names
        != SGB_THEOREM_TWO_NATIVE_TRAJECTORY_DECLARATIONS
        or theorem_two_freshness_names
        != SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATIONS
        or theorem_two_branch_locality_producer_names
        != SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATIONS
        or len(theorem_two_branch_locality_contract_rows) != 1
        or theorem_two_branch_locality_contract_rows[0].get("kind") != "def"
        or corollary_one_names | theorem_two_starvation_names |
            theorem_two_nth_pull_names | theorem_two_latent_reward_names |
            theorem_two_native_trajectory_names |
            theorem_two_branch_locality_producer_names
        != follow_on_names
        or SGB_THEOREM_TWO_TERMINAL_DECLARATION in sgb_names
    ):
        fail("SGB Corollary-1/Theorem-2 follow-on declaration or file drift")
    if (
        sgb.get("corollary_one_declaration_count")
        != SGB_COROLLARY_ONE_DECLARATION_COUNT
        or sgb.get(
            "theorem_two_deterministic_starvation_consumer_declaration_count"
        )
        != SGB_THEOREM_TWO_STARVATION_DECLARATION_COUNT
        or sgb.get("theorem_two_nth_pull_bridge_declaration_count")
        != SGB_THEOREM_TWO_NTH_PULL_DECLARATION_COUNT
        or sgb.get(
            "theorem_two_latent_reward_product_readout_declaration_count"
        ) != SGB_THEOREM_TWO_LATENT_REWARD_DECLARATION_COUNT
        or sgb.get("theorem_two_prefix_factorization_declaration_count")
        != SGB_THEOREM_TWO_PREFIX_FACTORIZATION_DECLARATION_COUNT
        or sgb.get(
            "theorem_two_action_readout_branch_locality_interface_and_count_cap_scaffold_declaration_count"
        ) != SGB_THEOREM_TWO_BRANCH_LOCALITY_SCAFFOLD_DECLARATION_COUNT
        or sgb.get("theorem_two_branch_locality_producer_declaration_count")
        != SGB_THEOREM_TWO_BRANCH_LOCALITY_PRODUCER_DECLARATION_COUNT
        or sgb.get(
            "theorem_two_selected_reward_freshness_declaration_count"
        ) != SGB_THEOREM_TWO_SELECTED_REWARD_FRESHNESS_DECLARATION_COUNT
    ):
        fail("SGB Corollary-1/Theorem-2 follow-on count drift")
    if sgb.get("source_theorem_one_compiled") is not True:
        fail("SGB Theorem-1 compiled gate drift")
    if sgb.get("source_theorem_four_contract_audit_compiled") is not True:
        fail("SGB Theorem-4 contract-audit compiled gate drift")
    if sgb.get("paper_endpoint_verified") is not True:
        fail("SGB Theorem-1 paper endpoint verification flag drift")
    if sgb.get("paper_endpoint_verified_scope") != "Theorem 1 only":
        fail("SGB paper endpoint scope drift")
    if (
        sgb.get("source_corollary_one_compiled") is not True
        or sgb.get("source_corollary_one_is_direct_theorem_one_consumer")
        is not True
    ):
        fail("SGB Corollary-1 companion gate drift")
    if (
        sgb.get(
            "source_theorem_two_deterministic_starvation_consumer_compiled"
        )
        is not True
        or sgb.get("source_theorem_two_nth_pull_bridge_compiled") is not True
        or sgb.get("source_theorem_two_latent_product_readout_compiled")
        is not True
        or sgb.get("source_theorem_two_prefix_factorization_compiled")
        is not True
        or sgb.get("source_theorem_two_action_factorization_compiled")
        is not True
        or sgb.get("source_theorem_two_pathwise_coordinate_support_compiled")
        is not True
        or sgb.get("source_theorem_two_branch_product_consumer_compiled")
        is not True
        or sgb.get("source_theorem_two_branch_locality_contract_typed")
        is not True
        or sgb.get("source_theorem_two_count_cap_scaffold_compiled")
        is not True
        or sgb.get("source_theorem_two_branch_locality_producer_compiled")
        is not True
        or sgb.get("source_theorem_two_unconditional_branch_product_compiled")
        is not True
        or sgb.get("source_theorem_two_freshness_compiled") is not True
        or sgb.get(
            "source_theorem_two_visible_marginal_freshness_compiled"
        ) is not True
        or sgb.get(
            "source_theorem_two_native_prefix_identification_compiled"
        ) is not False
        or sgb.get("separate_compiled_native_law_declaration_count") != 10
        or sgb.get("separate_compiled_selected_block_declaration_count") != 8
        or sgb.get("separate_compiled_phase_event_declaration_count") != 14
        or sgb.get("separate_compiled_phase_dichotomy_declaration_count") != 10
        or sgb.get(
            "separate_compiled_missing_pull_terminal_count_declaration_count"
        ) != 1
        or sgb.get(
            "separate_module_theorem_two_native_prefix_identification_compiled"
        ) is not True
        or sgb.get(
            "separate_module_theorem_two_native_trajectory_compiled"
        ) is not True
        or sgb.get(
            "separate_module_theorem_two_selected_block_transport_compiled"
        ) is not True
        or sgb.get(
            "separate_module_theorem_two_phase_event_transport_compiled"
        ) is not True
        or sgb.get(
            "separate_module_theorem_two_phase_dichotomy_compiled"
        ) is not True
        or sgb.get(
            "separate_module_theorem_two_missing_pull_terminal_count_compiled"
        ) is not True
        or sgb.get("source_theorem_two_status") != "blocked"
        or sgb.get("source_theorem_two_endpoint_verified") is not False
    ):
        fail("SGB Theorem-2 blocked-boundary drift")
    sgb_table_rows = [
        row for row in ledger.get("table_rows", [])
        if row.get("artifact") ==
        "Stochastic-gradient-bandit Theorem 1, Corollary 1, and blocked Theorem-2 follow-on"
    ]
    required_scope_boundaries = (
        "deterministic-time one-step selected-reward freshness",
        "separate ten-declaration native-law module",
        "complete visible/native trajectory-law identity",
        "eight declarations transport every finite pull-time/reward block",
        "fourteen declarations transport the exact finite Appendix-C S0/S1 event",
        "ten declarations split the pure latent phase probability",
        "missing-pull-aware masked latent law",
        "stopped or pull-ordered selected IID",
        "one declaration maps the missing-pull branch",
        "terminal-count-below event is not yet connected to a fixed-cutoff starvation trigger",
        "stopped-prefix future-cylinder",
        "conditional no-return probability >= 1/2",
        "Rademacher/binomial ballot probability",
        "asymptotic terminal",
        "do not make totalized or occurrence-conditioned stopped rewards IID",
        "frozen K = 2 Theorem-2 endpoint remain blocked",
    )
    if (
        len(sgb_table_rows) != 1
        or sgb_table_rows[0].get("status") != "partial"
        or any(
            item not in sgb_table_rows[0].get("boundary", "")
            for item in required_scope_boundaries
        )
    ):
        fail("SGB nth-pull/open-Theorem-2 scope boundary drift")
    if sgb.get("theorem_four_endpoint_verified") is not False:
        fail("SGB Theorem-4 endpoint verification flag drift")

    missing_names = []
    for record in records.values():
        for name in record.get("declarations", []):
            if name not in names:
                missing_names.append(name)
    if missing_names:
        fail("claim ledger references missing declarations: " + ", ".join(sorted(missing_names)[:8]))

    planned = records[ledger["matched_workflow_study"]["source_record_id"]]
    if planned["status"] != "planned" or planned["declarations"]:
        fail("target-drift study is not a zero-result planned record")
    if ledger["matched_workflow_study"].get("numerical_results_present") is not False:
        fail("target-drift result boundary is not explicit")

    graph = ledger["proof_graph"]
    expected = {
        "standalone_fixed_charge_sum": 1238,
        "union_fixed_charge": 1046,
        "shared_declaration_count": 175,
        "best_zdd_nonterminal_nodes": 1163,
        "cng_root_count": 8,
    }
    for key, value in expected.items():
        if graph.get(key) != value:
            fail("proof-graph evidence drift for {}".format(key))


def verify_theorem_audit_comparison():
    comparison = load_json(ROOT / "evidence" / "theorem-audit-comparison.json")
    ledger = load_json(ROOT / "evidence" / "claim-ledger.json")
    if comparison != ledger.get("theorem_audit_comparison"):
        fail("theorem-audit comparison/claim-ledger mismatch")
    rows = comparison.get("rows")
    expected_ids = [
        "textbook-chapter-15-scoped-positive-control",
        "delayed-bobw-source-frozen-audit",
        "succinct-lower-bound-source-frozen-audit",
        "stochastic-gradient-bandit-source-frozen-audit",
    ]
    if (
        comparison.get("schema_version") != 1
        or not isinstance(rows, list)
        or [row.get("id") for row in rows] != expected_ids
    ):
        fail("theorem-audit comparison row inventory/order drift")
    by_id = {row["id"]: row for row in rows}
    if len(by_id) != len(rows):
        fail("theorem-audit comparison row IDs are not unique")

    records = ledger.get("source_records", {})
    delayed = ledger.get("delayed_feedback", {})
    delayed_ids = delayed.get("implementation_facing_ids", []) + [
        delayed.get("diagnostic_id"),
        delayed.get("processed_prefix_id"),
        delayed.get("processed_trace_summary_id"),
        delayed.get("ordered_no_switch_transition_id"),
        delayed.get("ordered_no_switch_trace_id"),
        delayed.get("d11_domain_id"),
        delayed.get("line10_initialization_id"),
    ]
    specs = {
        expected_ids[0]: {
            "role": "scoped_positive_control",
            "evidence_record_ids": [
                "TEXTBOOK-PART-IV-CH15-GAUSSIAN-MINIMAX-LOWER-BOUND"
            ],
            "central_endpoint_record_id":
                "TEXTBOOK-PART-IV-CH15-GAUSSIAN-MINIMAX-LOWER-BOUND",
            "promotion_status": "compiled",
            "compiled_declaration_count": 12,
            "scoped_endpoint_verified": True,
        },
        expected_ids[1]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-SCHLISSELBERG-LANCEWICKI-AUER-MANSOUR-2025-DELAYED-BOBW",
            "evidence_record_ids": delayed_ids,
            "central_endpoint_record_id": delayed.get("central_endpoint_id"),
            "promotion_status": "partial",
            "compiled_declaration_count": 197,
            "declaration_count_breakdown": {
                "implementation_facing": 89,
                "diagnostic_conditional_repair": 19,
                "processed_prefix": 16,
                "processed_trace_summary_adapter": 9,
                "ordered_no_switch_transition": 15,
                "ordered_no_switch_trace_ordering": 12,
                "nonnegative_gap_d11_domain": 6,
                "line10_eliminated_arm_initialization": 31,
            },
        },
        expected_ids[2]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-ZENG-HONORIO-2025-SUCCINCT-LOWER-BOUNDS",
            "evidence_record_ids": [
                "NEURIPS-2025-SUCCINCT-LOWER-BOUND-GEOMETRY-AUDIT"
            ],
            "central_endpoint_record_id":
                "NEURIPS-2025-SUCCINCT-LOWER-BOUND-GEOMETRY-AUDIT",
            "promotion_status": "partial",
            "compiled_declaration_count": 54,
        },
        expected_ids[3]: {
            "role": "source_frozen_external_audit",
            "source_freeze_card_id":
                "PPR-BAUDRY-JOHNSON-VARY-PIKEBURKE-REBESCHINI-2025-SGB",
            "evidence_record_ids": [
                "NEURIPS-2025-STOCHASTIC-GRADIENT-BANDIT-MECHANISM-AUDIT",
                "NEURIPS-2025-SGB-PHASE-TRANSITION-FOLLOWON",
            ],
            "central_endpoint_record_id":
                "NEURIPS-2025-STOCHASTIC-GRADIENT-BANDIT-MECHANISM-AUDIT",
            "promotion_status": "partial",
            "compiled_declaration_count": 360,
            "theorem_one_endpoint_verified": True,
            "corollary_one_endpoint_verified": True,
            "theorem_two_endpoint_verified": False,
            "theorem_four_endpoint_verified": False,
            "theorem_two_nth_pull_bridge_compiled": True,
            "theorem_two_latent_product_readout_compiled": True,
            "theorem_two_prefix_factorization_compiled": True,
            "theorem_two_action_factorization_compiled": True,
            "theorem_two_pathwise_coordinate_support_compiled": True,
            "theorem_two_branch_product_consumer_compiled": True,
            "theorem_two_branch_locality_contract_typed": True,
            "theorem_two_count_cap_scaffold_compiled": True,
            "theorem_two_branch_locality_producer_compiled": True,
            "theorem_two_unconditional_branch_product_compiled": True,
            "theorem_two_freshness_compiled": True,
            "theorem_two_visible_marginal_freshness_compiled": True,
            "separate_compiled_native_law_declaration_count": 10,
            "separate_compiled_selected_block_declaration_count": 8,
            "separate_compiled_phase_event_declaration_count": 14,
            "separate_compiled_phase_dichotomy_declaration_count": 10,
            "separate_compiled_missing_pull_terminal_count_declaration_count": 1,
            "separate_module_theorem_two_native_prefix_identification_compiled":
                True,
            "separate_module_theorem_two_native_trajectory_compiled": True,
            "separate_module_theorem_two_selected_block_transport_compiled":
                True,
            "separate_module_theorem_two_phase_event_transport_compiled": True,
            "separate_module_theorem_two_phase_dichotomy_compiled": True,
            "separate_module_theorem_two_missing_pull_terminal_count_compiled":
                True,
            "theorem_two_native_prefix_identification_compiled": False,
            "declaration_count_breakdown": {
                "finite_action_algebra": 26,
                "generated_history_and_kernel_bridge": 18,
                "two_arm_zero_sum_and_equation_11": 18,
                "source_c_and_equation_8": 14,
                "generated_equation_8_kernel_bridge": 4,
                "fixed_history_successor_recurrence": 10,
                "two_arm_initial_recurrence": 3,
                "measurable_contract_and_cond_distrib_transport": 25,
                "path_integrability_and_conditional_recurrence": 19,
                "fixed_iid_source_contract_bridge": 9,
                "unconditional_recurrence_and_failure_mass": 37,
                "source_theorem_one_terminal": 32,
                "source_theorem_four_contract_audit": 8,
                "source_corollary_one_companion": 23,
                "source_theorem_two_deterministic_starvation_consumer": 24,
                "source_theorem_two_nth_pull_bridge": 26,
                "source_theorem_two_latent_reward_product_readout": 7,
                "source_theorem_two_deferred_decisions_prefix_factorization": 8,
                "source_theorem_two_action_readout_branch_locality_interface_and_count_cap_scaffold": 13,
                "source_theorem_two_branch_locality_producer": 28,
                "source_theorem_two_selected_reward_freshness_aggregation": 8,
            },
        },
    }
    freeze = load_json(ROOT / "evidence" / "source-freeze.json")
    freeze_cards = {row.get("card_id") for row in freeze.get("papers", [])}
    index = load_json(ROOT / "evidence" / "local_lean_declarations.json")
    index_names = {
        row.get("full_name") for row in index.get("declarations", [])
    }
    for row_id, spec in specs.items():
        row = by_id[row_id]
        for key, expected in spec.items():
            if row.get(key) != expected:
                fail("theorem-audit comparison {} drift for {}".format(key, row_id))
        if (
            not isinstance(row.get("contract_stress"), list)
            or not row["contract_stress"]
            or not isinstance(row.get("strongest_compiled_bridge"), str)
            or not row["strongest_compiled_bridge"]
            or not isinstance(row.get("scope_boundary"), str)
            or not row["scope_boundary"]
        ):
            fail("theorem-audit comparison has an empty evidence field for " + row_id)
        try:
            evidence_records = [records[item] for item in spec["evidence_record_ids"]]
            central = records[spec["central_endpoint_record_id"]]
        except (KeyError, TypeError):
            fail("theorem-audit comparison references a missing source record")
        if sum(len(record.get("declarations", [])) for record in evidence_records) != spec["compiled_declaration_count"]:
            fail("theorem-audit comparison declaration count drift for " + row_id)
        evidence_names = [
            name
            for record in evidence_records
            for name in record.get("declarations", [])
        ]
        if len(set(evidence_names)) != spec["compiled_declaration_count"]:
            fail("theorem-audit comparison declaration overlap drift for " + row_id)
        if any(name not in index_names for name in evidence_names):
            fail("theorem-audit comparison references an unindexed declaration")
        if row_id == "stochastic-gradient-bandit-source-frozen-audit":
            selected_block_file = (
                "BanditRLProof/Algorithms/"
                "StochasticGradientBanditTheoremTwoSelectedIID.lean"
            )
            selected_block_names = {
                item.get("full_name")
                for item in index.get("declarations", [])
                if item.get("file") == selected_block_file
            }
            expected_selected_block_names = {
                "BanditRLProof.StochasticGradientBandit.twoArmOptimalPullTimeRewardBlock",
                "BanditRLProof.StochasticGradientBandit.measurable_twoArmOptimalPullTimeRewardBlock",
                "BanditRLProof.StochasticGradientBandit.twoArmLatentMaskedOptimalPullBlock",
                "BanditRLProof.StochasticGradientBandit.measurable_twoArmLatentMaskedOptimalPullBlock",
                "BanditRLProof.StochasticGradientBandit.twoArmOptimalPullTimeRewardBlock_eq_latentMasked_ae",
                "BanditRLProof.StochasticGradientBandit.twoArmNativeOptimalPullTimeRewardBlock_map_eq_latentMasked",
                "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDTrajectoryMeasure_map_snd_eq_nativeStationary",
                "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDTrajectoryMeasure_map_optimalPullTimeRewardBlock_eq_latentMasked",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCPhaseOnePrefixSum",
                "BanditRLProof.StochasticGradientBandit.measurable_twoArmAppendixCPhaseOnePrefixSum",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCRewardPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCRewardPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCAllPullsPresent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCAllPullsPresent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCObservedPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCObservedPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCLatentPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCLatentPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmLatentMaskedOptimalPullBlock_preimage_appendixCObservedPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCGeneratedPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCGeneratedPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDTrajectoryMeasure_appendixCGeneratedPhaseEvent_eq_latent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCPureLatentRewardEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCPureLatentRewardEvent",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCMissingPullLatentPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.measurableSet_twoArmAppendixCMissingPullLatentPhaseEvent",
                "BanditRLProof.StochasticGradientBandit.mem_twoArmAppendixCMissingPullLatentPhaseEvent_iff",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCPureLatentRewardEvent_eq_union_phase_missing",
                "BanditRLProof.StochasticGradientBandit.disjoint_twoArmAppendixCLatentPhaseEvent_missing",
                "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDLatentTrajectoryMeasure_purePhaseEvent_eq_pi",
                "BanditRLProof.StochasticGradientBandit.twoArmFixedIIDLatentTrajectoryMeasure_purePhaseEvent_eq_phase_add_missing",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCRewardPhaseProbability_eq_generated_add_missing",
                "BanditRLProof.StochasticGradientBandit.twoArmAppendixCMissingPullLatentPhaseEvent_subset_terminalCountBelow",
            }
            if selected_block_names != expected_selected_block_names:
                fail("separate SGB selected-block declaration inventory drift")
        if spec["role"] == "source_frozen_external_audit":
            expected_endpoint_verified = (
                row_id == "stochastic-gradient-bandit-source-frozen-audit"
            )
            if (
                row.get("source_freeze_card_id") not in freeze_cards
                or central.get("status") != "partial"
                or row.get("paper_endpoint_verified") is not
                    expected_endpoint_verified
                or not isinstance(row.get("blocking_obligations"), list)
                or not row["blocking_obligations"]
            ):
                fail("external theorem-audit endpoint boundary drift for " + row_id)
            if row_id == "stochastic-gradient-bandit-source-frozen-audit" and (
                "paper_endpoint_verified refers only to Theorem 1"
                not in row.get("scope_boundary", "")
                or "conditional no-return probability >= 1/2"
                not in row.get("scope_boundary", "")
                or "a finite stream-box/visible-prefix mixture"
                not in row.get("scope_boundary", "")
                or "deterministic-time one-step freshness"
                not in row.get("scope_boundary", "")
                or "A separate ten-declaration module proves every native-prefix identity"
                not in row.get("scope_boundary", "")
                or "equality of the complete visible/native trajectory measures by projective-limit uniqueness"
                not in row.get("scope_boundary", "")
                or "eight declarations transport the exact finite observable pull-time/reward block to a masked latent law"
                not in row.get("scope_boundary", "")
                or "fourteen more declarations define the exact finite Appendix-C S0/S1 event"
                not in row.get("scope_boundary", "")
                or "ten more declarations split its pure latent probability"
                not in row.get("scope_boundary", "")
                or "one declaration proves that the missing-pull branch lies inside"
                not in row.get("scope_boundary", "")
                or "neither supply a product law nor make totalized or occurrence-conditioned rewards IID"
                not in row.get("scope_boundary", "")
                or "terminal-count-below event is not yet connected to a fixed-cutoff starvation trigger"
                not in row.get("scope_boundary", "")
                or "ballot probability"
                not in row.get("scope_boundary", "")
                or "asymptotic terminal remain blocked"
                not in row.get("scope_boundary", "")
                or not any(
                    "compiled exact missing-pull/all-present probability split" in item
                    and "stopped-prefix future-cylinder" in item
                    and "ballot probability" in item
                    and "asymptotic assembly" in item
                    for item in row.get("blocking_obligations", [])
                )
            ):
                fail("SGB theorem-audit endpoint scope drift")
        elif (
            central.get("status") != "compiled"
            or row.get("scoped_endpoint_verified") is not True
            or row.get("blocking_obligations") != []
            or "paper_endpoint_verified" in row
        ):
            fail("Chapter 15 scoped positive-control boundary drift")

    for rel in (
        "evidence/delayed-feedback-proof-obligations.md",
        "evidence/succinct-lower-bound-proof-obligations.md",
        "evidence/stochastic-gradient-bandit-proof-obligations.md",
        "evidence/stochastic-gradient-bandit-follow-on-proof-obligations.md",
    ):
        if not (ROOT / rel).is_file():
            fail("missing theorem-audit proof-obligation ledger: " + rel)


def verify_source_freeze():
    freeze = load_json(ROOT / "evidence" / "source-freeze.json")
    papers = freeze.get("papers", [])
    if len(papers) != 3:
        fail("source freeze must contain exactly three papers")
    if freeze.get("selection_status") != (
        "source_locked_with_record_specific_timing"
    ):
        fail("source-lock portfolio timing status drift")
    expected_timing = {
        "PPR-SCHLISSELBERG-LANCEWICKI-AUER-MANSOUR-2025-DELAYED-BOBW":
            "co_published_with_initial_feasibility_slice",
        "PPR-ZENG-HONORIO-2025-SUCCINCT-LOWER-BOUNDS":
            "locked_before_case_specific_lean_slice",
        "PPR-BAUDRY-JOHNSON-VARY-PIKEBURKE-REBESCHINI-2025-SGB":
            "locked_before_case_specific_lean_slice",
    }
    timing = {
        row.get("card_id"): row.get("selection_timing") for row in papers
    }
    if timing != expected_timing:
        fail("source-lock case-specific timing drift")
    if "does not assert that every case was frozen" not in freeze.get(
        "timing_note", ""
    ):
        fail("source-lock timing limitation is missing")
    statuses = {row.get("initial_status") for row in papers}
    if "source_frozen_not_started" not in statuses or "source_frozen_reserve_not_started" not in statuses:
        fail("source-freeze non-completion statuses are missing")
    for paper in papers:
        digest = paper.get("camera_ready_sha256", "")
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            fail("invalid source PDF digest")
        if not paper.get("camera_ready_url", "").startswith("https://"):
            fail("source PDF URL is not HTTPS")


def verify_anonymous_base(manifest):
    base = load_json(ROOT / "evidence" / "anonymous-base-manifest.json")
    if base.get("git_object_database_included") is not False:
        fail("anonymous supplement must not contain a Git object database")
    if base.get("materializable_by_target_drift_runner") is not False:
        fail("target-drift materialization boundary is not explicit")
    digest = hashlib.sha256()
    for row in base.get("files", []):
        path = ROOT / row["path"]
        if not path.is_file() or sha256(path) != row["sha256"]:
            fail("anonymous base file mismatch: " + row["path"])
        digest.update(row["path"].encode("utf-8") + b"\0")
        digest.update(row["sha256"].encode("ascii") + b"\n")
    if digest.hexdigest() != base.get("tree_sha256"):
        fail("anonymous base tree digest mismatch")
    if manifest.get("anonymous_base", {}).get("tree_sha256") != base.get("tree_sha256"):
        fail("manifest/anonymous-base digest mismatch")
    if manifest.get("anonymous_base", {}).get("target_drift_materialization_ready") is not False:
        fail("manifest overstates target-drift materialization readiness")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    manifest = verify_manifest()
    verify_claim_ledger()
    verify_source_freeze()
    verify_theorem_audit_comparison()
    verify_anonymous_base(manifest)
    verify_proof_graph(manifest)
    print(json.dumps({
        "artifact_verified": True,
        "file_count": len(manifest["files"]),
        "source_tree_digest": manifest["source_tree_digest"],
        "proof_graph_included": manifest["proof_graph"]["included"],
        "theorem_audit_comparison_verified": True,
        "target_drift_results_present": False,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
