import BanditRLProof.Algorithms.ETCCenteredDiffRewardSubGaussian
import BanditRLProof.Algorithms.ETCPairwiseCenteredSubGaussianTail
import BanditRLProof.ConcentrationSubGaussian
import BanditRLProof.HistoryFiltration
import Mathlib.Probability.ConditionalExpectation

/-!
# ETC conditional sub-Gaussian witness surface

This module packages the conditional reward-law witnesses needed to use the
compiled Mathlib conditional sub-Gaussian concentration wrapper on ETC centered
reward differences.  It does not prove those witnesses from a concrete reward
kernel or conditional expectation identity.
-/

namespace BanditRLProof
namespace ETC

/--
Centered pairwise reward differences are measurable at time `t` with respect to
the shifted generated history filtration.

The shifted filtration contains action/reward observations with index `< t+1`,
so the reward coordinate at time `t` is available.  This proves only the
adaptedness/measurability part of the conditional route; it does not prove any
conditional MGF or conditional expectation identity.
-/
theorem measurable_centeredPairwiseRewardDiff_historyFiltrationSucc
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (a : Fin K) (t : Nat) :
    @Measurable Omega Real
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      inferInstance
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega) := by
  have hreward_t :
      @Measurable Omega Rat
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward t)
        inferInstance
        (fun omega => reward omega t) := by
    exact
      History.measurable_reward_mem_historyFiltration_of_lt
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward
        (Nat.lt_succ_self t)
  let transform : Rat -> Real := fun r =>
    (((if ETC.actionWithCommit spec commitArm t = a then
        r - model.mean a else 0) +
      (if ETC.actionWithCommit spec commitArm t = model.bestArm then
        model.mean model.bestArm - r else 0) : Rat) : Real)
  have htransform : Measurable transform := by
    exact measurable_of_countable transform
  simpa [ETC.centeredPairwiseRewardDiff, transform] using
    htransform.comp hreward_t

/--
The fixed-commit ETC centered reward-difference process is strongly adapted to
the shifted generated history filtration.

This discharges the `StronglyAdapted` witness field for the conditional
centered-diff package under the local discrete history model.  Conditional MGF
witnesses remain separate assumptions.
-/
theorem stronglyAdapted_centeredPairwiseRewardDiff_historyFiltrationSucc
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (a : Fin K) :
    MeasureTheory.StronglyAdapted
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward)
      (fun t omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega) := by
  intro t
  exact
    (ETC.measurable_centeredPairwiseRewardDiff_historyFiltrationSucc
      spec model commitArm reward hreward a t).stronglyMeasurable

/--
Independence-based conditional mean-zero source for one centered reward
coordinate.

If the sigma-algebra generated by the centered reward coordinate is independent
of the conditioning sigma-algebra, and the centered reward has global integral
zero, then its conditional expectation against that sigma-algebra is zero.  This
is a thin ETC-shaped wrapper around Mathlib's `condExp_indep_eq`; it does not
derive the required independence or integral identity from a reward kernel.
-/
theorem centeredReward_condExp_eq_zero_of_indep
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (mcond : MeasurableSpace Omega) (hm : mcond <= mOmega)
    (model : FiniteBanditModel K)
    (reward : Omega -> RewardTrace Rat)
    (b : Fin K) (t : Nat)
    (hmeas : @Measurable Omega Real mOmega inferInstance
      (fun omega : Omega =>
        (((reward omega t - model.mean b : Rat) : Real))))
    (h_indep :
      ProbabilityTheory.Indep
        (MeasurableSpace.comap
          (fun omega : Omega =>
            (((reward omega t - model.mean b : Rat) : Real)))
          inferInstance)
        mcond mu)
    (h_integral :
      MeasureTheory.integral mu
        (fun omega : Omega =>
          (((reward omega t - model.mean b : Rat) : Real))) = 0) :
    Filter.EventuallyEq (MeasureTheory.ae mu)
      (MeasureTheory.condExp mcond mu
        (fun omega : Omega =>
          (((reward omega t - model.mean b : Rat) : Real))))
      (fun _omega : Omega => (0 : Real)) := by
  let X : Omega -> Real := fun omega =>
    (((reward omega t - model.mean b : Rat) : Real))
  let mX : MeasurableSpace Omega := MeasurableSpace.comap X inferInstance
  have hmeasX : @Measurable Omega Real mOmega inferInstance X := by
    simpa [X] using hmeas
  have hleX : mX <= mOmega := Measurable.comap_le hmeasX
  have hsmX : @MeasureTheory.StronglyMeasurable Omega Real _ mX X :=
    (comap_measurable X).stronglyMeasurable
  have hindepX : ProbabilityTheory.Indep mX mcond mu := by
    simpa [mX, X] using h_indep
  have h_intX : MeasureTheory.integral mu X = 0 := by
    simpa [X] using h_integral
  have h :=
    @MeasureTheory.condExp_indep_eq Omega Real _ _ _
      mX mcond mOmega mu X hleX hm inferInstance hsmX hindepX
  change Filter.EventuallyEq (MeasureTheory.ae mu)
    (MeasureTheory.condExp mcond mu X)
    (fun _omega : Omega => (0 : Real))
  exact h.mono (fun _omega homega => by
    rw [homega, h_intX])

/--
Shifted-history specialization of `centeredReward_condExp_eq_zero_of_indep`.

This is the first compiled conditional mean-zero source for the fixed-commit
ETC history filtration.  It still assumes the centered reward coordinate is
independent of the shifted generated history sigma-algebra and has integral
zero; later product-law work should discharge those two assumptions.
-/
theorem centeredReward_condExp_historyFiltrationSucc_eq_zero_of_indep
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (b : Fin K) (t : Nat)
    (h_indep :
      ProbabilityTheory.Indep
        (MeasurableSpace.comap
          (fun omega : Omega =>
            (((reward omega t - model.mean b : Rat) : Real)))
          inferInstance)
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward t)
        mu)
    (h_integral :
      MeasureTheory.integral mu
        (fun omega : Omega =>
          (((reward omega t - model.mean b : Rat) : Real))) = 0) :
    Filter.EventuallyEq (MeasureTheory.ae mu)
      (MeasureTheory.condExp
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward t)
        mu
        (fun omega : Omega =>
          (((reward omega t - model.mean b : Rat) : Real))))
      (fun _omega : Omega => (0 : Real)) := by
  have hmeas : @Measurable Omega Real mOmega inferInstance
      (fun omega : Omega =>
        (((reward omega t - model.mean b : Rat) : Real))) := by
    exact
      (measurable_of_countable
        (fun r : Rat => (((r - model.mean b : Rat) : Real)))).comp
        (hreward t)
  exact
    ETC.centeredReward_condExp_eq_zero_of_indep
      mu
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      model reward b t hmeas h_indep h_integral

/--
Future centered reward coordinates are independent of the reward-only past
sigma-algebra generated by earlier coordinates, provided the reward trace
coordinates are mutually independent.

This is a product-law/history-independence bridge for the conditional
mean-zero route.  It deliberately targets only the reward-coordinate past
`iSup`; adding the deterministic action generators from the local history
filtration is a separate wrapper.
-/
theorem indep_centeredReward_succ_pastReward_iSup_of_iIndepFun_reward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    (model : FiniteBanditModel K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (h_reward_indep :
      ProbabilityTheory.iIndepFun
        (fun t omega => reward omega t) mu)
    (b : Fin K) (i : Nat) :
    ProbabilityTheory.Indep
      (MeasurableSpace.comap
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real)))
        inferInstance)
      (iSup fun j : Nat =>
        iSup fun _h : j <= i =>
          MeasurableSpace.comap
            (fun omega : Omega => reward omega j) inferInstance)
      mu := by
  let mReward : Nat -> MeasurableSpace Omega := fun j =>
    MeasurableSpace.comap (fun omega : Omega => reward omega j) inferInstance
  have h_le : forall j : Nat, mReward j <= mOmega := by
    intro j
    exact Measurable.comap_le (hreward j)
  have h_indep_m :
      ProbabilityTheory.iIndep mReward mu := by
    exact h_reward_indep.iIndep
  have hST : Disjoint ({i + 1} : Set Nat) {j : Nat | j <= i} := by
    rw [Set.disjoint_left]
    intro j hjS hjT
    have hj : j = i + 1 := by
      simpa using hjS
    subst hj
    exact Nat.not_succ_le_self i hjT
  have h_indep_iSup :
      ProbabilityTheory.Indep
        (iSup fun j : Nat =>
          iSup fun _h : j ∈ ({i + 1} : Set Nat) => mReward j)
        (iSup fun j : Nat =>
          iSup fun _h : j ∈ {j : Nat | j <= i} => mReward j)
        mu := by
    exact
      ProbabilityTheory.indep_iSup_of_disjoint
        (m := mReward) h_le h_indep_m hST
  have h_center_meas_reward :
      @Measurable Omega Real
        (mReward (i + 1)) inferInstance
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real))) := by
    exact
      (measurable_of_countable
        (fun r : Rat => (((r - model.mean b : Rat) : Real)))).comp
        (comap_measurable (fun omega : Omega => reward omega (i + 1)))
  have h_center_le_reward :
      MeasurableSpace.comap
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real)))
        inferInstance <= mReward (i + 1) := by
    exact Measurable.comap_le h_center_meas_reward
  have h_reward_le_iSup :
      mReward (i + 1) <=
        (iSup fun j : Nat =>
          iSup fun _h : j ∈ ({i + 1} : Set Nat) => mReward j) := by
    exact
      le_iSup_of_le (i + 1)
        (le_iSup_of_le (by simp) le_rfl)
  exact
    ProbabilityTheory.indep_of_indep_of_le_left
      h_indep_iSup
      (le_trans h_center_le_reward h_reward_le_iSup)

/--
For a fixed-commit ETC action trace, the shifted generated history filtration
is contained in the reward-only past sigma-algebra.

The action generators are deterministic singleton preimages, hence either
`univ` or `empty`; the reward generators at filtration level `i` are exactly
coordinates `j <= i`.  This is the missing deterministic-action bridge from the
reward-only past independence leaf to the local `History.historyFiltrationSucc`.
-/
theorem historyFiltrationSucc_actionWithCommit_le_pastReward_iSup
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (spec : ETC.Spec K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (i : Nat) :
    (History.historyFiltrationSucc
      (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
      reward
      (fun _t : Nat => measurable_const)
      hreward i : MeasurableSpace Omega) <=
    (iSup fun j : Nat =>
      iSup fun _h : j <= i =>
        MeasurableSpace.comap
          (fun omega : Omega => reward omega j) inferInstance) := by
  rw [History.historyFiltrationSucc_apply, History.historyFiltration_apply]
  refine MeasurableSpace.generateFrom_le ?_
  intro s hs
  rcases hs with hs | hs
  · rcases hs with ⟨j, _hjlt, a, hs_eq⟩
    rw [hs_eq]
    by_cases hconst : ETC.actionWithCommit spec commitArm j = a
    · have hpre :
          Set.preimage
            (fun _omega : Omega => ETC.actionWithCommit spec commitArm j)
            (Set.singleton a) = Set.univ := by
        ext omega
        simp only [Set.mem_preimage, Set.mem_univ]
        change ETC.actionWithCommit spec commitArm j = a <-> True
        constructor
        · intro _h
          trivial
        · intro _h
          exact hconst
      rw [hpre]
      exact
        (show @MeasurableSet Omega
          (iSup fun k : Nat =>
            iSup fun _h : k <= i =>
              MeasurableSpace.comap
                (fun omega : Omega => reward omega k) inferInstance)
          (Set.univ : Set Omega) from
          (@MeasurableSet.univ Omega
            (iSup fun k : Nat =>
              iSup fun _h : k <= i =>
                MeasurableSpace.comap
                  (fun omega : Omega => reward omega k) inferInstance)))
    · have hpre :
          Set.preimage
            (fun _omega : Omega => ETC.actionWithCommit spec commitArm j)
            (Set.singleton a) = (∅ : Set Omega) := by
        ext omega
        simp only [Set.mem_preimage, Set.mem_empty_iff_false]
        change ETC.actionWithCommit spec commitArm j = a <-> False
        constructor
        · intro h
          exact hconst h
        · intro h
          exact False.elim h
      rw [hpre]
      exact
        (show @MeasurableSet Omega
          (iSup fun k : Nat =>
            iSup fun _h : k <= i =>
              MeasurableSpace.comap
                (fun omega : Omega => reward omega k) inferInstance)
          (∅ : Set Omega) from
          (@MeasurableSet.empty Omega
            (iSup fun k : Nat =>
              iSup fun _h : k <= i =>
                MeasurableSpace.comap
                  (fun omega : Omega => reward omega k) inferInstance)))
  · rcases hs with ⟨j, hjlt, r, hs_eq⟩
    rw [hs_eq]
    have hjle : j <= i := Nat.le_of_lt_succ hjlt
    have hle :
        MeasurableSpace.comap
          (fun omega : Omega => reward omega j) inferInstance <=
        (iSup fun k : Nat =>
          iSup fun _h : k <= i =>
            MeasurableSpace.comap
              (fun omega : Omega => reward omega k) inferInstance) := by
      exact le_iSup_of_le j (le_iSup_of_le hjle le_rfl)
    have hmeas_comap :
        @MeasurableSet Omega
          (MeasurableSpace.comap
            (fun omega : Omega => reward omega j) inferInstance)
          (Set.preimage
            (fun omega : Omega => reward omega j) (Set.singleton r)) := by
      exact
        (comap_measurable (fun omega : Omega => reward omega j))
          (MeasurableSet.singleton r)
    exact hle _ hmeas_comap

/--
Future centered reward coordinates are independent of the full fixed-commit
shifted history filtration when reward coordinates are mutually independent.

This extends `indep_centeredReward_succ_pastReward_iSup_of_iIndepFun_reward`
from the reward-only past to `History.historyFiltrationSucc` by the deterministic
action-generator inclusion above.
-/
theorem indep_centeredReward_succ_historyFiltrationSucc_of_iIndepFun_reward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (h_reward_indep :
      ProbabilityTheory.iIndepFun
        (fun t omega => reward omega t) mu)
    (b : Fin K) (i : Nat) :
    ProbabilityTheory.Indep
      (MeasurableSpace.comap
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real)))
        inferInstance)
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward i)
      mu := by
  exact
    ProbabilityTheory.indep_of_indep_of_le_right
      (ETC.indep_centeredReward_succ_pastReward_iSup_of_iIndepFun_reward
        (mOmega := mOmega)
        mu model reward hreward h_reward_indep b i)
      (ETC.historyFiltrationSucc_actionWithCommit_le_pastReward_iSup
        (mOmega := mOmega)
        spec commitArm reward hreward i)

/--
One-step conditional mean-zero wrapper for Mathlib's conditional tail API.

Mathlib asks for the summand at `i + 1` to be conditionally controlled against
filtration level `i`.  This theorem specializes the generic independence-based
conditional expectation wrapper to that index shape.
-/
theorem centeredReward_succ_condExp_historyFiltrationSucc_eq_zero_of_indep
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (b : Fin K) (i : Nat)
    (h_indep :
      ProbabilityTheory.Indep
        (MeasurableSpace.comap
          (fun omega : Omega =>
            (((reward omega (i + 1) - model.mean b : Rat) : Real)))
          inferInstance)
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward i)
        mu)
    (h_integral :
      MeasureTheory.integral mu
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real))) = 0) :
    Filter.EventuallyEq (MeasureTheory.ae mu)
      (MeasureTheory.condExp
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward i)
        mu
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real))))
      (fun _omega : Omega => (0 : Real)) := by
  have hmeas : @Measurable Omega Real mOmega inferInstance
      (fun omega : Omega =>
        (((reward omega (i + 1) - model.mean b : Rat) : Real))) := by
    exact
      (measurable_of_countable
        (fun r : Rat => (((r - model.mean b : Rat) : Real)))).comp
        (hreward (i + 1))
  exact
    ETC.centeredReward_condExp_eq_zero_of_indep
      mu
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward i)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le i)
      model reward b (i + 1) hmeas h_indep h_integral

/--
One-step conditional mean-zero source from reward-coordinate independence.

This combines the full fixed-commit history independence theorem with the
existing `condExp_indep_eq` wrapper.  It still leaves the zero-integral identity
as an explicit side condition, supplied separately by exact-mean or bounded
source leaves.
-/
theorem centeredReward_succ_condExp_historyFiltrationSucc_eq_zero_of_iIndepFun_reward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (h_reward_indep :
      ProbabilityTheory.iIndepFun
        (fun t omega => reward omega t) mu)
    (b : Fin K) (i : Nat)
    (h_integral :
      MeasureTheory.integral mu
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real))) = 0) :
    Filter.EventuallyEq (MeasureTheory.ae mu)
      (MeasureTheory.condExp
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward i)
        mu
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real))))
      (fun _omega : Omega => (0 : Real)) := by
  exact
    ETC.centeredReward_succ_condExp_historyFiltrationSucc_eq_zero_of_indep
      (mOmega := mOmega)
      mu spec model commitArm reward hreward b i
      (ETC.indep_centeredReward_succ_historyFiltrationSucc_of_iIndepFun_reward
        (mOmega := mOmega)
        mu spec model commitArm reward hreward h_reward_indep b i)
      h_integral

/--
Unconditional sub-Gaussianity plus independence from the conditioning
sigma-algebra gives conditional sub-Gaussianity.

This is a Mathlib-shaped source for later sampled reward-law witnesses.  It
uses `Kernel.HasSubgaussianMGF.of_rat`: for each rational exponent the
conditional MGF is the unconditional MGF by `condExp_indep_eq`, and Mathlib
extends the bound to all real exponents by continuity/density.
-/
theorem hasCondSubgaussianMGF_of_indep_comap
    {Omega : Type u}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (mcond : MeasurableSpace Omega) (hm : mcond <= mOmega)
    (X : Omega -> Real) (c : NNReal)
    (hmeasX : @Measurable Omega Real mOmega inferInstance X)
    (h_subG : ProbabilityTheory.HasSubgaussianMGF X c mu)
    (h_indep :
      ProbabilityTheory.Indep
        (MeasurableSpace.comap X inferInstance) mcond mu) :
    ProbabilityTheory.HasCondSubgaussianMGF mcond hm X c mu := by
  have hleX :
      MeasurableSpace.comap X inferInstance <= mOmega := by
    exact Measurable.comap_le hmeasX
  let k : @ProbabilityTheory.Kernel Omega Omega mcond mOmega :=
    @ProbabilityTheory.condExpKernel Omega mOmega _ mu _ mcond
  have hcomp : (mu.trim hm).bind k = mu := by
    exact @ProbabilityTheory.condExpKernel_comp_trim Omega mcond mOmega _ mu _ hm
  have h_subG_comp_direct :
      @ProbabilityTheory.HasSubgaussianMGF Omega mOmega X c
        ((mu.trim hm).bind
          (@ProbabilityTheory.condExpKernel Omega mOmega _ mu _ mcond)) := by
    rw [@ProbabilityTheory.condExpKernel_comp_trim Omega mcond mOmega _ mu _ hm]
    exact h_subG
  have h_subG_comp :
      @ProbabilityTheory.HasSubgaussianMGF Omega mOmega X c ((mu.trim hm).bind k) := by
    simpa [k] using h_subG_comp_direct
  change
    @ProbabilityTheory.Kernel.HasSubgaussianMGF
      Omega Omega mOmega mcond
      X c k (mu.trim hm)
  refine
    @ProbabilityTheory.Kernel.HasSubgaussianMGF.of_rat
      Omega Omega mOmega mcond (mu.trim hm)
      k X c ?_ ?_
  · intro t
    exact h_subG_comp.integrable_exp_mul t
  · intro q
    let f : Omega -> Real := fun omega => Real.exp (((q : Real) * X omega))
    let Filt : Filter Omega := MeasureTheory.ae (mu.trim hm)
    show
      Filter.Eventually
        (fun omega : Omega =>
          @ProbabilityTheory.mgf Omega mOmega X (k omega) (q : Real)
            <= Real.exp (((c : NNReal) : Real) * (q : Real) ^ 2 / 2))
        Filt
    have h_int_f : @MeasureTheory.Integrable Real _ _ Omega mOmega f mu := by
      simpa [f] using h_subG.integrable_exp_mul (q : Real)
    let intKernel : Omega -> Real :=
      fun omega : Omega => @MeasureTheory.integral Omega Real _ _ mOmega (k omega) f
    let intMu : Real :=
      @MeasureTheory.integral Omega Real _ _ mOmega mu f
    let ce : Omega -> Real :=
      @MeasureTheory.condExp Omega Real mcond mOmega _ _ _ mu f
    have hmeasX_mX :
        @Measurable Omega Real
          (MeasurableSpace.comap X inferInstance) inferInstance X := by
      exact comap_measurable X
    have hmeas_f_mX :
        @Measurable Omega Real
          (MeasurableSpace.comap X inferInstance) inferInstance f := by
      dsimp [f]
      exact (Real.measurable_exp.comp (measurable_const.mul hmeasX_mX))
    have hsm_f_mX :
        @MeasureTheory.StronglyMeasurable Omega Real _
          (MeasurableSpace.comap X inferInstance) f :=
      hmeas_f_mX.stronglyMeasurable
    have h_indep_mX :
        ProbabilityTheory.Indep
          (MeasurableSpace.comap X inferInstance) mcond mu := by
      exact h_indep
    have hcond_mu :
        Filter.EventuallyEq (MeasureTheory.ae mu)
          ce
          (fun _omega : Omega => intMu) := by
      simpa [ce, intMu] using
        (@MeasureTheory.condExp_indep_eq Omega Real _ _ _
          (MeasurableSpace.comap X inferInstance) mcond mOmega mu f
          hleX hm inferInstance
          hsm_f_mX h_indep_mX)
    have hcond_trim :
        Filter.EventuallyEq Filt
          ce
          (fun _omega : Omega => intMu) := by
      simpa [Filt, ce, intMu] using
        MeasureTheory.StronglyMeasurable.ae_eq_trim_of_stronglyMeasurable
          hm
          (@MeasureTheory.stronglyMeasurable_condExp
            Omega Real mcond mOmega mu f _ _ _)
          MeasureTheory.stronglyMeasurable_const
          hcond_mu
    have hkernel :
        Filter.EventuallyEq Filt
          ce
          intKernel := by
      simpa [Filt, ce, intKernel, k] using
        (@ProbabilityTheory.condExp_ae_eq_trim_integral_condExpKernel
          Omega Real mcond mOmega _ mu _ _ f _ _ hm h_int_f)
    have hkernel_to_mu :
        Filter.EventuallyEq Filt
          (fun omega : Omega =>
            @MeasureTheory.integral Omega Real _ _ mOmega (k omega) f)
          (fun _omega : Omega => intMu) := by
      simpa [intKernel] using
        (@Filter.EventuallyEq.trans Omega Real Filt intKernel ce
          (fun _omega : Omega => intMu) hkernel.symm hcond_trim)
    refine hkernel_to_mu.mono ?_
    intro omega hcond
    calc
      @ProbabilityTheory.mgf Omega mOmega X
          (k omega) (q : Real)
          =
        @MeasureTheory.integral Omega Real _ _ mOmega
          (k omega) f := by
            simp [ProbabilityTheory.mgf, f]
      _ = intMu := hcond
      _ = @ProbabilityTheory.mgf Omega mOmega X mu (q : Real) := by
            simp [ProbabilityTheory.mgf, f, intMu]
      _ <= Real.exp (((c : NNReal) : Real) * (q : Real) ^ 2 / 2) :=
            h_subG.mgf_le (q : Real)

/--
One-step conditional sub-Gaussian source from reward-coordinate independence.

This is the sampled centered-reward MGF analogue of
`centeredReward_succ_condExp_historyFiltrationSucc_eq_zero_of_iIndepFun_reward`:
unconditional sub-Gaussianity of the future centered reward, together with
`iIndepFun` reward coordinates, gives the conditional MGF witness against the
fixed-commit shifted history filtration.
-/
theorem centeredReward_succ_hasCondSubgaussianMGF_historyFiltrationSucc_of_iIndepFun_reward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega) [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      @Measurable Omega Rat mOmega inferInstance
        (fun omega : Omega => reward omega t))
    (h_reward_indep :
      ProbabilityTheory.iIndepFun
        (fun t omega => reward omega t) mu)
    (b : Fin K) (i : Nat) (c : NNReal)
    (h_subG :
      ProbabilityTheory.HasSubgaussianMGF
        (fun omega : Omega =>
          (((reward omega (i + 1) - model.mean b : Rat) : Real)))
        c mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward i)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le i)
      (fun omega : Omega =>
        (((reward omega (i + 1) - model.mean b : Rat) : Real)))
      c mu := by
  let hist : MeasureTheory.Filtration Nat mOmega :=
    History.historyFiltrationSucc
      (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
      reward
      (fun _t : Nat => measurable_const)
      hreward
  let X : Omega -> Real := fun omega =>
    (((reward omega (i + 1) - model.mean b : Rat) : Real))
  have hmeasX : @Measurable Omega Real mOmega inferInstance X := by
    exact
      (measurable_of_countable
        (fun r : Rat => (((r - model.mean b : Rat) : Real)))).comp
        (hreward (i + 1))
  have h_subG_X : ProbabilityTheory.HasSubgaussianMGF X c mu := by
    simpa [X] using h_subG
  have h_indep_X :
      ProbabilityTheory.Indep
        (MeasurableSpace.comap X inferInstance) (hist i) mu := by
    simpa [hist, X] using
      (ETC.indep_centeredReward_succ_historyFiltrationSucc_of_iIndepFun_reward
        (mOmega := mOmega)
        mu spec model commitArm reward hreward h_reward_indep b i)
  change ProbabilityTheory.HasCondSubgaussianMGF (hist i) (hist.le i) X c mu
  exact
    ETC.hasCondSubgaussianMGF_of_indep_comap
      (mOmega := mOmega)
      mu (hist i) (hist.le i) X c hmeasX h_subG_X h_indep_X

/--
If the fixed ETC trace at time `t` pulls neither arm `a` nor the selected best
arm, the centered pairwise reward-difference summand is identically zero and
therefore has a zero-variance sub-Gaussian MGF.

This is a small reward-law source for the independent/zeroth MGF side only; it
does not cover the sampled-arm times where the reward coordinate appears.
-/
theorem centeredPairwiseRewardDiff_hasSubgaussianMGF_of_action_miss
    {Omega : Type u} {K : Nat}
    [MeasurableSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsZeroOrProbabilityMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (a : Fin K) (t : Nat)
    (h_ne_a : ETC.actionWithCommit spec commitArm t ≠ a)
    (h_ne_best :
      ETC.actionWithCommit spec commitArm t ≠ model.bestArm) :
    ProbabilityTheory.HasSubgaussianMGF
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      0 mu := by
  simp [ETC.centeredPairwiseRewardDiff, h_ne_a, h_ne_best]

/--
If the fixed ETC trace at time `t` pulls neither arm `a` nor the selected best
arm, the centered pairwise reward-difference summand is conditionally
sub-Gaussian with zero variance proxy with respect to any sub-sigma-algebra.

This discharges only the zero summand cases of the conditional MGF field.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_miss
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (m : MeasurableSpace Omega) (hm : m ≤ mOmega)
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (a : Fin K) (t : Nat)
    (h_ne_a : ETC.actionWithCommit spec commitArm t ≠ a)
    (h_ne_best :
      ETC.actionWithCommit spec commitArm t ≠ model.bestArm) :
    ProbabilityTheory.HasCondSubgaussianMGF
      m hm
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      0 mu := by
  simp [ETC.centeredPairwiseRewardDiff, h_ne_a, h_ne_best]

/--
History-filtration specialization of the zero-summand conditional MGF source.

For conditional concentration over the shifted generated history filtration,
the summand at process time `t` is conditionally sub-Gaussian with zero variance
whenever `actionWithCommit t` is neither the comparison arm nor the best arm.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_historyFiltrationSucc_of_action_miss
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (a : Fin K) (t : Nat)
    (h_ne_a : ETC.actionWithCommit spec commitArm t ≠ a)
    (h_ne_best :
      ETC.actionWithCommit spec commitArm t ≠ model.bestArm) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      0 mu := by
  exact
    ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_miss
      mu
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      spec model commitArm reward a t h_ne_a h_ne_best

/--
Sampled comparison-arm conditional MGF transfer.

When the fixed ETC trace pulls the comparison arm `a` at time `t`, the centered
pairwise reward-difference summand is exactly the centered reward
`reward t - mean a`, so any conditional MGF witness for that centered reward
transfers to the pairwise summand.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_arm
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (m : MeasurableSpace Omega) (hm : m ≤ mOmega)
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (a : Fin K) (t : Nat) (c : NNReal)
    (hne : a = model.bestArm -> False)
    (h_action : ETC.actionWithCommit spec commitArm t = a)
    (h_subG :
      ProbabilityTheory.HasCondSubgaussianMGF
        m hm
        (fun omega : Omega =>
          (((reward omega t - model.mean a : Rat) : Real)))
        c mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      m hm
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      c mu := by
  have hane : a ≠ model.bestArm := hne
  have hnot_best :
      ETC.actionWithCommit spec commitArm t ≠ model.bestArm := by
    intro hbest
    exact hne (h_action.symm.trans hbest)
  simpa [ETC.centeredPairwiseRewardDiff, h_action, hnot_best, hane] using
    h_subG

/--
Sampled best-arm conditional MGF transfer.

When the fixed ETC trace pulls `model.bestArm` at time `t`, the centered
pairwise reward-difference summand is the negative centered best-arm reward
`mean bestArm - reward t`.  This theorem consumes that negative-direction
conditional MGF witness explicitly.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_bestArm
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (m : MeasurableSpace Omega) (hm : m ≤ mOmega)
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (a : Fin K) (t : Nat) (c : NNReal)
    (hne : a = model.bestArm -> False)
    (h_action :
      ETC.actionWithCommit spec commitArm t = model.bestArm)
    (h_subG :
      ProbabilityTheory.HasCondSubgaussianMGF
        m hm
        (fun omega : Omega =>
          (((model.mean model.bestArm - reward omega t : Rat) : Real)))
        c mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      m hm
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      c mu := by
  have hnot_a :
      ETC.actionWithCommit spec commitArm t ≠ a := by
    intro ha
    exact hne (ha.symm.trans h_action)
  have hbest_ne_a : model.bestArm ≠ a := by
    intro h
    exact hne h.symm
  simpa [ETC.centeredPairwiseRewardDiff, hnot_a, h_action, hbest_ne_a] using
    h_subG

/--
Shifted-history specialization of the sampled comparison-arm conditional MGF
transfer.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_historyFiltrationSucc_of_action_eq_arm
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (a : Fin K) (t : Nat) (c : NNReal)
    (hne : a = model.bestArm -> False)
    (h_action : ETC.actionWithCommit spec commitArm t = a)
    (h_subG :
      ProbabilityTheory.HasCondSubgaussianMGF
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward t)
        ((History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward).le t)
        (fun omega : Omega =>
          (((reward omega t - model.mean a : Rat) : Real)))
        c mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      c mu := by
  exact
    ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_arm
      (mOmega := mOmega) (mu := mu)
      (m := History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      (hm := (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      spec model commitArm reward a t c hne h_action h_subG

/--
Shifted-history specialization of the sampled best-arm conditional MGF
transfer.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_historyFiltrationSucc_of_action_eq_bestArm
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (a : Fin K) (t : Nat) (c : NNReal)
    (hne : a = model.bestArm -> False)
    (h_action :
      ETC.actionWithCommit spec commitArm t = model.bestArm)
    (h_subG :
      ProbabilityTheory.HasCondSubgaussianMGF
        (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward t)
        ((History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          hreward).le t)
        (fun omega : Omega =>
          (((model.mean model.bestArm - reward omega t : Rat) : Real)))
        c mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      c mu := by
  exact
    ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_bestArm
      (mOmega := mOmega) (mu := mu)
      (m := History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      (hm := (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      spec model commitArm reward a t c hne h_action h_subG

/--
Action-case assembly for sampled centered-reward conditional MGF witnesses.

This is the conditional analogue of
`ETC.centeredPairwiseRewardDiff_hasSubgaussianMGF_of_centeredReward`: if the
reward coordinate pulled by the fixed ETC trace has the appropriate centered
conditional MGF witness, then the concrete centered pairwise reward-difference
summand has the corresponding action-selected variance proxy.  The miss case is
closed by the zero-summand theorem, and the best-arm case uses the sign-flipped
conditional MGF witness.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_centeredReward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (m : MeasurableSpace Omega) (hm : m ≤ mOmega)
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (cReward : Fin K -> Nat -> NNReal)
    (a : Fin K) (t : Nat)
    (hne : a = model.bestArm -> False)
    (h_subG :
      forall b : Fin K, ETC.actionWithCommit spec commitArm t = b ->
        ProbabilityTheory.HasCondSubgaussianMGF
          m hm
          (fun omega : Omega =>
            (((reward omega t - model.mean b : Rat) : Real)))
          (cReward b t) mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      m hm
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      (ETC.centeredPairwiseRewardDiffVarianceProxy
        spec model commitArm cReward a t)
      mu := by
  classical
  by_cases ha : ETC.actionWithCommit spec commitArm t = a
  · have hnot_best :
        ETC.actionWithCommit spec commitArm t ≠ model.bestArm := by
      intro hbest
      exact hne (ha.symm.trans hbest)
    have h :=
      ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_arm
        (mOmega := mOmega) (mu := mu) (m := m) (hm := hm)
        spec model commitArm reward a t (cReward a t) hne ha
        (h_subG a ha)
    simpa [ETC.centeredPairwiseRewardDiffVarianceProxy, ha, hnot_best] using h
  · by_cases hbest : ETC.actionWithCommit spec commitArm t = model.bestArm
    · have hneg :
          ProbabilityTheory.HasCondSubgaussianMGF
            m hm
            (fun omega : Omega =>
              -(((reward omega t -
                model.mean model.bestArm : Rat) : Real)))
            (cReward model.bestArm t) mu := by
        exact ProbabilityTheory.Kernel.HasSubgaussianMGF.neg
          (h_subG model.bestArm hbest)
      have hbest_subG :
          ProbabilityTheory.HasCondSubgaussianMGF
            m hm
            (fun omega : Omega =>
              (((model.mean model.bestArm - reward omega t : Rat) : Real)))
            (cReward model.bestArm t) mu := by
        simpa [Rat.cast_sub, sub_eq_add_neg, add_comm, add_left_comm, add_assoc]
          using hneg
      have h :=
        ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_eq_bestArm
          (mOmega := mOmega) (mu := mu) (m := m) (hm := hm)
          spec model commitArm reward a t (cReward model.bestArm t)
          hne hbest hbest_subG
      have hbest_ne_a : model.bestArm ≠ a := by
        intro hba
        exact hne hba.symm
      simpa [ETC.centeredPairwiseRewardDiffVarianceProxy, ha, hbest, hbest_ne_a] using h
    · have h :=
        ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_action_miss
          (mOmega := mOmega) (mu := mu) (m := m) (hm := hm)
          spec model commitArm reward a t ha hbest
      simpa [ETC.centeredPairwiseRewardDiffVarianceProxy, ha, hbest] using h

/--
Shifted-history specialization of the action-case conditional MGF assembly from
sampled centered-reward witnesses.
-/
theorem centeredPairwiseRewardDiff_hasCondSubgaussianMGF_historyFiltrationSucc_of_centeredReward
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (hreward : forall t : Nat,
      Measurable (fun omega : Omega => reward omega t))
    (cReward : Fin K -> Nat -> NNReal)
    (a : Fin K) (t : Nat)
    (hne : a = model.bestArm -> False)
    (h_subG :
      forall b : Fin K, ETC.actionWithCommit spec commitArm t = b ->
        ProbabilityTheory.HasCondSubgaussianMGF
          (History.historyFiltrationSucc
            (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
            reward
            (fun _t : Nat => measurable_const)
            hreward t)
          ((History.historyFiltrationSucc
            (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
            reward
            (fun _t : Nat => measurable_const)
            hreward).le t)
          (fun omega : Omega =>
            (((reward omega t - model.mean b : Rat) : Real)))
          (cReward b t) mu) :
    ProbabilityTheory.HasCondSubgaussianMGF
      (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      ((History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      (fun omega =>
        ETC.centeredPairwiseRewardDiff
          spec model commitArm reward a t omega)
      (ETC.centeredPairwiseRewardDiffVarianceProxy
        spec model commitArm cReward a t)
      mu := by
  exact
    ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_centeredReward
      (mOmega := mOmega) (mu := mu)
      (m := History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward t)
      (hm := (History.historyFiltrationSucc
        (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
        reward
        (fun _t : Nat => measurable_const)
        hreward).le t)
      spec model commitArm reward cReward a t hne h_subG

/--
Reward-level conditional sub-Gaussian source contract for the fixed-commit ETC
centered-diff route.

This contract is one layer closer to a concrete reward law than
`CenteredDiffCondSubGaussianWitnesses`: it asks for conditional MGF witnesses for
the sampled reward coordinate centered at the arm actually pulled by
`actionWithCommit`, plus the zeroth unconditional witness and the final tail
budget.  The constructor below turns it into the centered-diff witness package.
-/
structure CenteredRewardCondSubGaussianWitnesses
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    [MeasureTheory.IsZeroOrProbabilityMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (tail : Fin K -> ENNReal) where
  cReward : Fin K -> Nat -> NNReal
  hreward : forall t : Nat,
    Measurable (fun omega : Omega => reward omega t)
  subG0 :
    forall b : Fin K, ETC.actionWithCommit spec commitArm 0 = b ->
      ProbabilityTheory.HasSubgaussianMGF
        (fun omega : Omega =>
          (((reward omega 0 - model.mean b : Rat) : Real)))
        (cReward b 0) mu
  condSubG :
    forall i, i < spec.explorationPulls * K - 1 ->
      forall b : Fin K,
        ETC.actionWithCommit spec commitArm (i + 1) = b ->
          ProbabilityTheory.HasCondSubgaussianMGF
            (History.historyFiltrationSucc
              (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
              reward
              (fun _t : Nat => measurable_const)
              hreward i)
            ((History.historyFiltrationSucc
              (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
              reward
              (fun _t : Nat => measurable_const)
              hreward).le i)
            (fun omega : Omega =>
              (((reward omega (i + 1) - model.mean b : Rat) : Real)))
            (cReward b (i + 1)) mu
  tail_bound :
    forall a : Fin K, (a = model.bestArm -> False) ->
      ENNReal.ofReal
        (Real.exp
          (-(ETC.centeredPairwiseGapThreshold spec model a) ^ 2 /
            (2 *
              (((Finset.range (spec.explorationPulls * K)).sum
                (fun t =>
                  ETC.centeredPairwiseRewardDiffVarianceProxy
                    spec model commitArm cReward a t) : NNReal) : Real)))) <=
        tail a

/--
Witness package for the concrete centered reward-difference conditional
sub-Gaussian ETC tail route.

This is a project-local conditional reward-law surface: it records the
filtration, strong adaptedness, zeroth unconditional MGF witness, later
conditional MGF witnesses, and tail domination needed to produce the fixed
ETC pairwise empirical-mean tail contract.
-/
structure CenteredDiffCondSubGaussianWitnesses
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    [MeasureTheory.IsZeroOrProbabilityMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (tail : Fin K -> ENNReal) where
  c : Fin K -> Nat -> NNReal
  filtration : Fin K -> MeasureTheory.Filtration Nat mOmega
  stronglyAdapted :
    forall a : Fin K, (a = model.bestArm -> False) ->
      MeasureTheory.StronglyAdapted
        (filtration a)
        (fun t omega =>
          ETC.centeredPairwiseRewardDiff
            spec model commitArm reward a t omega)
  subG0 :
    forall a : Fin K, (a = model.bestArm -> False) ->
      ProbabilityTheory.HasSubgaussianMGF
        (fun omega =>
          ETC.centeredPairwiseRewardDiff
            spec model commitArm reward a 0 omega)
        (c a 0) mu
  condSubG :
    forall a : Fin K, (a = model.bestArm -> False) ->
      forall i, i < spec.explorationPulls * K - 1 ->
        ProbabilityTheory.HasCondSubgaussianMGF
          ((filtration a) i) ((filtration a).le i)
          (fun omega =>
            ETC.centeredPairwiseRewardDiff
              spec model commitArm reward a (i + 1) omega)
          (c a (i + 1)) mu
  tail_bound :
    forall a : Fin K, (a = model.bestArm -> False) ->
      ENNReal.ofReal
        (Real.exp
          (-(ETC.centeredPairwiseGapThreshold spec model a) ^ 2 /
            (2 *
              (((Finset.range (spec.explorationPulls * K)).sum
                (fun t => c a t) : NNReal) : Real)))) <= tail a

/--
Build the centered-diff conditional witness package from reward-level sampled
conditional MGF witnesses.

This bridges the remaining action-case gap between raw reward-law conditional
MGF facts and the already compiled centered-diff conditional tail consumer.
-/
noncomputable def centeredDiffCondSubGaussianWitnesses_of_centeredRewardCondSubGaussianWitnesses
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    [MeasureTheory.IsZeroOrProbabilityMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (tail : Fin K -> ENNReal)
    (w :
      ETC.CenteredRewardCondSubGaussianWitnesses
        mu spec model commitArm reward tail) :
    ETC.CenteredDiffCondSubGaussianWitnesses
      mu spec model commitArm reward tail where
  c := ETC.centeredPairwiseRewardDiffVarianceProxy
    spec model commitArm w.cReward
  filtration := fun _a =>
    History.historyFiltrationSucc
      (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
      reward
      (fun _t : Nat => measurable_const)
      w.hreward
  stronglyAdapted := by
    intro a _hne
    exact
      ETC.stronglyAdapted_centeredPairwiseRewardDiff_historyFiltrationSucc
        spec model commitArm reward w.hreward a
  subG0 := by
    intro a hne
    exact
      ETC.centeredPairwiseRewardDiff_hasSubgaussianMGF_of_centeredReward
        mu spec model commitArm reward w.cReward a 0 hne
        (fun b hb => w.subG0 b hb)
  condSubG := by
    intro a hne i hi
    exact
      ETC.centeredPairwiseRewardDiff_hasCondSubgaussianMGF_of_centeredReward
        (mOmega := mOmega) (mu := mu)
        (m := History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          w.hreward i)
        (hm := (History.historyFiltrationSucc
          (fun _omega : Omega => ETC.actionWithCommit spec commitArm)
          reward
          (fun _t : Nat => measurable_const)
          w.hreward).le i)
        spec model commitArm reward w.cReward a (i + 1) hne
        (fun b hb => w.condSubG i hi b hb)
  tail_bound := by
    intro a hne
    exact w.tail_bound a hne

/--
Consume a centered reward-difference conditional witness package to build the
fixed-commit ETC pairwise empirical-mean tail contract.

This is the first compiled conditional reward-law bridge for the ETC route. It
uses the generated centered-diff event inclusion plus the Mathlib-backed
conditional sub-Gaussian finite-prefix wrapper, while keeping the actual
conditional MGF and adaptedness facts explicit in the witness package.
-/
theorem pairwiseEmpMeanTailContract_of_centeredDiffCondSubGaussianWitnesses
    {Omega : Type u} {K : Nat}
    [mOmega : MeasurableSpace Omega] [StandardBorelSpace Omega]
    (mu : MeasureTheory.Measure Omega)
    [MeasureTheory.IsFiniteMeasure mu]
    [MeasureTheory.IsZeroOrProbabilityMeasure mu]
    (spec : ETC.Spec K)
    (model : FiniteBanditModel K)
    (commitArm : Fin K)
    (reward : Omega -> RewardTrace Rat)
    (tail : Fin K -> ENNReal)
    (hexplorationPulls_pos : 0 < spec.explorationPulls)
    (w :
      ETC.CenteredDiffCondSubGaussianWitnesses
        mu spec model commitArm reward tail) :
    ETC.PairwiseEmpMeanTailContract
      mu spec model commitArm reward tail := by
  refine ⟨?_⟩
  intro a hne
  have heps :
      0 <= ETC.centeredPairwiseGapThreshold spec model a := by
    unfold ETC.centeredPairwiseGapThreshold
    exact
      (Rat.cast_nonneg (K := Real)).2
        (mul_nonneg
          (Nat.cast_nonneg spec.explorationPulls)
          (sub_nonneg.mpr
            (FiniteBanditModel.mean_le_bestArm_mean model a)))
  have hsubset :
      Set.Subset
        {omega : Omega |
          ETC.empMeanAtExploration spec commitArm (reward omega) a >=
            ETC.empMeanAtExploration spec commitArm
              (reward omega) model.bestArm}
        {omega : Omega |
          ETC.centeredPairwiseGapThreshold spec model a <=
            (Finset.range (spec.explorationPulls * K)).sum (fun t : Nat =>
              ETC.centeredPairwiseRewardDiff
                spec model commitArm reward a t omega)} :=
    ETC.empMeanAtExploration_ge_best_event_subset_centered_pairwise_sum_event
      spec model commitArm reward a hexplorationPulls_pos
  have htail_sum :
      mu {omega : Omega |
          ETC.centeredPairwiseGapThreshold spec model a <=
            (Finset.range (spec.explorationPulls * K)).sum (fun t : Nat =>
              ETC.centeredPairwiseRewardDiff
                spec model commitArm reward a t omega)} <=
        ENNReal.ofReal
          (Real.exp
            (-(ETC.centeredPairwiseGapThreshold spec model a) ^ 2 /
              (2 *
                (((Finset.range (spec.explorationPulls * K)).sum
                  (fun t => w.c a t) : NNReal) : Real)))) := by
    exact
      Concentration.condSubGaussian_sum_tail_ennreal_of_stronglyAdapted
        (mu := mu)
        (Y := fun t omega =>
          ETC.centeredPairwiseRewardDiff
            spec model commitArm reward a t omega)
        (cY := w.c a)
        (F := w.filtration a)
        (w.stronglyAdapted a hne)
        (w.subG0 a hne)
        (spec.explorationPulls * K)
        (w.condSubG a hne)
        heps
  exact (MeasureTheory.measure_mono hsubset).trans
    (htail_sum.trans (w.tail_bound a hne))

end ETC
end BanditRLProof
