import BanditRLProof.Algorithms.ETCInfinitePiExpectedRegretAssembly
import BanditRLProof.Algorithms.ETCMeasurability
import BanditRLProof.ConditionalRewardLawSource

/-!
# Generated finite-history ETC policy

This module constructs the canonical ETC action trace as a policy generated
from finite reward histories. It closes the deterministic action-alignment
layer needed before an adaptive reward law can be transported through the
existing generated-action conditional-expectation surfaces.

It does not prove a reward law, conditional mean-zero, concentration bound, or
the final LML ETC regret theorem.
-/

namespace BanditRLProof
namespace ETC

/--
The state reconstructed from a finite reward history for the ETC commit rule.

The prefix through `t` is retained exactly and the unobserved suffix is zero.
The defaulted suffix is only an implementation device: score reconstruction
requires the exploration horizon to be contained in the retained prefix.
-/
def explorationArgmaxHistoryState
    (t : Nat) (history : History.FiniteRewardHistory Rat t) :
    RewardTrace Rat :=
  History.completeRewardTrace t history (0 : Rat)

/-- The finite-history ETC state reconstruction is measurable as a trace. -/
theorem measurable_explorationArgmaxHistoryState (t : Nat) :
    Measurable (explorationArgmaxHistoryState t) := by
  refine measurable_pi_lambda _ ?_
  intro s
  by_cases hs : s <= t
  · let i : Finset.Iic t := ⟨s, Finset.mem_Iic.mpr hs⟩
    have h_eval : Measurable
        (fun history : History.FiniteRewardHistory Rat t => history i) :=
      measurable_pi_apply i
    simpa [explorationArgmaxHistoryState, History.completeRewardTrace, hs, i]
      using h_eval
  · simp [explorationArgmaxHistoryState, History.completeRewardTrace, hs]

/--
At policy time `t`, explore at action time `t + 1` while that action lies in
the exploration prefix; otherwise choose the empirical-mean argmax computed
from the completed finite-history state.
-/
noncomputable def explorationArgmaxHistoryPolicy
    {K : Nat} (spec : ETC.Spec K) (model : FiniteBanditModel K)
    (t : Nat) : Policy.MeasurablePolicy (RewardTrace Rat) (Fin K) where
  action := fun completedReward =>
    if t + 1 < spec.explorationPulls * K then
      ETC.exploreArm spec (t + 1)
    else
      (ETC.argmaxCommitOracle model.hK).choose
        (fun a : Fin K =>
          ETC.empMeanAtExploration spec model.bestArm completedReward a)
  measurable_action := by
    by_cases hphase : t + 1 < spec.explorationPulls * K
    · simp [hphase]
    · simpa [hphase] using
        (ETC.measurable_commitOracle_choose_of_forall_measurable_empMean
          (oracle := ETC.argmaxCommitOracle model.hK)
          (empMean := fun omega : RewardTrace Rat => fun a : Fin K =>
            ETC.empMeanAtExploration spec model.bestArm omega a)
          (ETC.measurable_empMeanAtExploration_coordinates
            spec model.bestArm (fun omega : RewardTrace Rat => omega)
            (fun i => measurable_pi_apply i)))

/--
The canonical ETC action generator obtained by running the finite-history
policy against the identity reward trace.
-/
noncomputable def explorationArgmaxGeneratedAction
    {K : Nat} (spec : ETC.Spec K) (model : FiniteBanditModel K) :
    RewardTrace Rat -> ActionTrace (Fin K) :=
  ConditionalExpectationReward.generatedActionFromRewardHistory
    (fun t => ETC.explorationArgmaxHistoryPolicy spec model t)
    (fun t history => ETC.explorationArgmaxHistoryState t history)
    (ETC.exploreArm spec 0)
    (fun reward : RewardTrace Rat => reward)

/--
The canonical empirical-mean ETC trace is generated by the measurable policy
over finite reward histories.

Positive exploration pulls are essential at time zero: the shifted generated
trace starts with `ETC.exploreArm spec 0`, which matches the ETC trace only
when time zero belongs to the exploration prefix. At later commit times, the
finite-history score reconstruction theorem supplies the argmax equality.
-/
theorem explorationArgmaxGeneratedAction_eq_explorationArgmaxAction
    {K : Nat} (spec : ETC.Spec K) (model : FiniteBanditModel K)
    (hexplorationPulls_pos : 0 < spec.explorationPulls) :
    ETC.explorationArgmaxGeneratedAction spec model =
      ETC.explorationArgmaxAction spec model := by
  funext reward time
  cases time with
  | zero =>
      have hzero : 0 < spec.explorationPulls * K :=
        Nat.mul_pos hexplorationPulls_pos spec.hK
      simp [ETC.explorationArgmaxGeneratedAction,
        ConditionalExpectationReward.generatedActionFromRewardHistory,
        Policy.generatedActionTraceSucc, ETC.explorationArgmaxAction,
        ETC.fixedProductArgmaxAction, ETC.actionWithCommit, hzero]
  | succ t =>
      by_cases hphase : t + 1 < spec.explorationPulls * K
      · simp [ETC.explorationArgmaxGeneratedAction,
          ConditionalExpectationReward.generatedActionFromRewardHistory,
          Policy.generatedActionTraceSucc, ETC.explorationArgmaxHistoryPolicy,
          ETC.explorationArgmaxAction, ETC.fixedProductArgmaxAction,
          ETC.actionWithCommit, hphase]
      · have hhorizon : spec.explorationPulls * K <= t + 1 :=
          Nat.le_of_not_gt hphase
        have hscores :
            (fun a : Fin K =>
              ETC.empMeanAtExploration spec model.bestArm
                (ETC.explorationArgmaxHistoryState t
                  (History.finiteRewardHistoryOfTrace reward t)) a) =
              (fun a : Fin K =>
                ETC.empMeanAtExploration spec model.bestArm reward a) := by
          funext a
          exact
            ETC.empMeanAtExploration_completeRewardTrace_eq_of_explorationHorizon_le
              spec model.bestArm reward t hhorizon a
        simp only [ETC.explorationArgmaxGeneratedAction,
          ConditionalExpectationReward.generatedActionFromRewardHistory,
          Policy.generatedActionTraceSucc, ETC.explorationArgmaxHistoryPolicy,
          ETC.explorationArgmaxAction,
          ETC.fixedProductArgmaxAction, ETC.fixedProductArgmaxCommit,
          ETC.actionWithCommit, hphase, hscores]

/--
During the exploration prefix, the generated finite-history ETC policy agrees
with every fixed-commit ETC trace because both choose the same round-robin arm.

The post-exploration commit arm is deliberately arbitrary in this statement;
only the strict exploration-horizon hypothesis is used.
-/
theorem explorationArgmaxGeneratedAction_eq_actionWithCommit_of_lt
    {K : Nat} (spec : ETC.Spec K) (model : FiniteBanditModel K)
    (commitArm : Fin K) (reward : RewardTrace Rat) {t : Nat}
    (hexplorationPulls_pos : 0 < spec.explorationPulls)
    (ht : t < spec.explorationPulls * K) :
    ETC.explorationArgmaxGeneratedAction spec model reward t =
      ETC.actionWithCommit spec commitArm t := by
  have hgenerated := congrFun
    (congrFun
      (ETC.explorationArgmaxGeneratedAction_eq_explorationArgmaxAction
        spec model hexplorationPulls_pos)
      reward)
    t
  calc
    ETC.explorationArgmaxGeneratedAction spec model reward t =
        ETC.explorationArgmaxAction spec model reward t := hgenerated
    _ = ETC.exploreArm spec t := by
      simp [ETC.explorationArgmaxAction, ETC.fixedProductArgmaxAction,
        ETC.actionWithCommit, ht]
    _ = ETC.actionWithCommit spec commitArm t :=
      (ETC.actionWithCommit_eq_exploreArm_of_lt spec commitArm ht).symm

/--
Canonical kernel-trajectory law source for the finite-history ETC policy.

The reward process is the identity coordinate process under the
`RewardKernel.historyStepKernelFamily` trajectory measure. The existing
canonical `trajMeasure` construction proves the full finite-pair
`partialTraj` law for the generated policy action without assuming an ambient
selected-reward law. Combined with
`explorationArgmaxGeneratedAction_eq_explorationArgmaxAction`, this law is the
action-dependent probability foundation for the canonical ETC action trace.

It remains a kernel-generated trajectory law. Transport to an arbitrary
adaptive environment and identification with the fixed product-coordinate
source remain separate obligations.
-/
noncomputable def explorationArgmaxGeneratedActionPartialTrajectoryPairLawSource_trajMeasure
    {K : Nat} {Context : Type}
    [MeasurableSpace Context]
    (spec : ETC.Spec K) (model : FiniteBanditModel K)
    (mu0 : MeasureTheory.Measure Rat)
    [MeasureTheory.IsProbabilityMeasure mu0]
    (rewardKernel : RewardKernel.MarkovRewardKernel (Prod Context (Fin K)) Rat)
    (context : (n : Nat) -> ((j : Finset.Iic n) -> Rat) -> Context)
    (hcontext : forall n : Nat, Measurable (context n)) :
    ConditionalExpectationReward.GeneratedActionPartialTrajectoryPairLawSource
      (ProbabilityTheory.Kernel.trajMeasure
        (X := fun _ : Nat => Rat) mu0
        (RewardKernel.historyStepKernelFamily rewardKernel
          (fun t => ETC.explorationArgmaxHistoryPolicy spec model t)
          context
          (fun t history => ETC.explorationArgmaxHistoryState t history)
          hcontext
          (fun t => ETC.measurable_explorationArgmaxHistoryState t)))
      rewardKernel
      (fun t => ETC.explorationArgmaxHistoryPolicy spec model t)
      context
      (fun t history => ETC.explorationArgmaxHistoryState t history)
      (ETC.exploreArm spec 0)
      (fun trajectory : RewardTrace Rat => trajectory)
      (fun t => measurable_pi_apply t) := by
  exact
    ConditionalExpectationReward.historyStepKernelFamily_generatedActionPartialTrajectoryPairLawSource_trajMeasure
      mu0 rewardKernel
      (fun t => ETC.explorationArgmaxHistoryPolicy spec model t)
      context
      (fun t history => ETC.explorationArgmaxHistoryState t history)
      hcontext
      (fun t => ETC.measurable_explorationArgmaxHistoryState t)
      (ETC.exploreArm spec 0)

/--
Canonical trajectory conditional sub-Gaussian MGF for the successor reward
centered at the finite-bandit model mean selected by the ETC policy.

The mean surface is context-independent, `fun _ action => model.mean action`.
The kernel centered-reward law supplies conditional mean-zero and the
one-step MGF; the remaining regularity contract is the selected finite-history
variance ceiling at the requested successor time. This theorem is therefore a
concentration foundation for the canonical kernel trajectory, not a transport
to the fixed product-coordinate reward source or an arbitrary adaptive bandit
environment.
-/
theorem explorationArgmaxHistory_centeredReward_succ_hasCondSubgaussianMGF_trajMeasure
    {K : Nat} {Context : Type}
    [MeasurableSpace Context]
    (spec : ETC.Spec K) (model : FiniteBanditModel K)
    (mu0 : MeasureTheory.Measure Rat)
    [MeasureTheory.IsProbabilityMeasure mu0]
    (rewardKernel : RewardKernel.MarkovRewardKernel (Prod Context (Fin K)) Rat)
    (context : (n : Nat) -> ((j : Finset.Iic n) -> Rat) -> Context)
    (hcontext : forall n : Nat, Measurable (context n))
    (varianceProxy : Context -> Fin K -> NNReal)
    (law :
      RewardKernel.CenteredRewardKernelLaw rewardKernel
        (fun _ action => model.mean action) varianceProxy)
    (i : Nat) (c : NNReal)
    (hvariance :
      forall history : ((j : Finset.Iic i) -> Rat),
        varianceProxy (context i history)
          ((ETC.explorationArgmaxHistoryPolicy spec model i).action
            (ETC.explorationArgmaxHistoryState i history)) <= c) :
    let policy := fun t => ETC.explorationArgmaxHistoryPolicy spec model t
    let state := fun t history => ETC.explorationArgmaxHistoryState t history
    let stepKernel :=
      RewardKernel.historyStepKernelFamily rewardKernel policy context state
        hcontext (fun t => ETC.measurable_explorationArgmaxHistoryState t)
    let trajMeasure :=
      ProbabilityTheory.Kernel.trajMeasure
        (X := fun _ : Nat => Rat) mu0 stepKernel
    let reward : RewardTrace Rat -> RewardTrace Rat := fun trajectory => trajectory
    let hreward : forall t : Nat,
        Measurable (fun trajectory : RewardTrace Rat => reward trajectory t) :=
      fun t => measurable_pi_apply t
    ProbabilityTheory.HasCondSubgaussianMGF
      ((History.historyFiltrationSucc
        (ConditionalExpectationReward.generatedActionFromRewardHistory
          policy state (ETC.exploreArm spec 0) reward)
        reward
        (ConditionalExpectationReward.generatedActionFromRewardHistory_measurable
          (policy := policy) (state := state)
          (defaultAction := ETC.exploreArm spec 0) (reward := reward)
          hreward (fun t => ETC.measurable_explorationArgmaxHistoryState t))
        hreward) i)
      ((History.historyFiltrationSucc
        (ConditionalExpectationReward.generatedActionFromRewardHistory
          policy state (ETC.exploreArm spec 0) reward)
        reward
        (ConditionalExpectationReward.generatedActionFromRewardHistory_measurable
          (policy := policy) (state := state)
          (defaultAction := ETC.exploreArm spec 0) (reward := reward)
          hreward (fun t => ETC.measurable_explorationArgmaxHistoryState t))
        hreward).le i)
      (fun trajectory : RewardTrace Rat =>
        (((reward trajectory (i + 1) -
          model.mean
            ((policy i).action
              (state i
                (History.finiteRewardHistoryOfTrace (reward trajectory) i))) :
          Rat) : Real)))
      c trajMeasure := by
  have hmean : Measurable
      (fun pair : Prod Context (Fin K) => model.mean pair.2) := by
    exact (measurable_of_countable model.mean).comp measurable_snd
  simpa only using
    (ConditionalExpectationReward.historyStepKernelFamily_centeredReward_succ_hasCondSubgaussianMGF_trajMeasure
      mu0 rewardKernel
      (fun t => ETC.explorationArgmaxHistoryPolicy spec model t)
      context
      (fun t history => ETC.explorationArgmaxHistoryState t history)
      hcontext
      (fun t => ETC.measurable_explorationArgmaxHistoryState t)
      (fun _ action => model.mean action)
      varianceProxy law hmean (ETC.exploreArm spec 0) i c hvariance)

end ETC
end BanditRLProof
