import BanditRLProof.Algorithms.StochasticGradientBanditExponentialAudit
import BanditRLProof.Algorithms.StochasticGradientBanditTrajectoryAudit

/-!
# Generated stochastic-gradient-bandit conditional Equation (8)

This module composes the source-exact bounded-reward Equation (8) with the
actual action/reward kernel generated by the SGB history policy.  Its main
contract permits an action-dependent exponent `q`; this is the form needed by
the two-arm Theorem-1 proof, where the selected-arm branches use different
coefficients.

Proof route and API ledger:

* `integral_exp_mul_le_sourceEqEight_of_ae_abs_le_one` supplies Equation (8)
  on each conditional reward fiber;
* `Thompson.measurableEnvironmentInitialPairKernel` and
  `Thompson.historyStepKernel` expose the initial and successor
  policy/reward `compProd` laws;
* bounded reward support and measurability of the real reward coordinate
  produce the fiber and joint exponential integrability required by
  `Measure.integral_compProd`;
* `historyAlgorithm_policy` and
  `Exp3.integral_finiteActionMeasure_eq_sum` turn the outer integral into the
  explicit softmax mixture, while `softmaxProbability_sum` supplies its
  constant term.

There is no independence premise: each reward law is conditioned on the
actual finite action/reward history and selected action.  The source support
contract remains exactly `[-1, 1]`.  The result is a one-step conditional
moment bound, not either Theorem-1 recurrence or a regret endpoint.
-/

namespace BanditRLProof
namespace StochasticGradientBandit

open MeasureTheory ProbabilityTheory
open scoped BigOperators ProbabilityTheory

noncomputable section

universe u v

variable {Action : Type u}
  [MeasurableSpace Action] [MeasurableSingletonClass Action]
  [Fintype Action] [DecidableEq Action] [Nonempty Action]

/--
Action-dependent Equation (8) for the generated initial action/reward pair.

Source-time fence: this kernel samples source round `t = 1` from the untouched
parameter `initialTheta`; consuming pair zero then constructs source
`theta_2`.  In the source Theorem 1, `initialTheta` is the zero vector.  This
base bridge is therefore separate from the successor bridge below.
-/
theorem integral_measurableEnvironmentInitialPairKernel_exp_actionReward_le_sourceEqEight_of_mean
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (env : Env) (q mean : Action -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.initialFeedback (env, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.initialFeedback (env, selected)) id =
        mean selected) :
    integral
        (Thompson.measurableEnvironmentInitialPairKernel
          (historyAlgorithm initialTheta eta) environment env)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) <=
      1 + ∑ selected,
        softmaxProbability initialTheta selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
  have hrewardAt (selected : Action) :
      ∀ᵐ reward ∂(environment.at env).initialFeedback selected,
        |reward| <= 1 := by
    simpa [Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hreward selected
  have hmeanAt (selected : Action) :
      integral ((environment.at env).initialFeedback selected) id =
        mean selected := by
    simpa [Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hmean selected
  have hq : Measurable q := measurable_of_finite q
  have hfullMeas : Measurable
      (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) :=
    Real.measurable_exp.comp
      ((hq.comp measurable_fst).mul measurable_snd)
  have hfiberIntegrable (selected : Action) : Integrable
      (fun reward : Real => Real.exp (q selected * reward))
      ((environment.at env).initialFeedback selected) := by
    have hexpMeasurable : AEStronglyMeasurable
        (fun reward : Real => Real.exp (q selected * reward))
        ((environment.at env).initialFeedback selected) :=
      (Real.measurable_exp.comp
        (measurable_const.mul measurable_id)).aestronglyMeasurable
    have hexpBound : ∀ᵐ reward
        ∂(environment.at env).initialFeedback selected,
        ‖Real.exp (q selected * reward)‖ <= Real.exp |q selected| :=
      (hrewardAt selected).mono fun reward hrewardSelected => by
        rw [Real.norm_eq_abs, abs_of_pos (Real.exp_pos _), Real.exp_le_exp]
        calc
          q selected * reward <= |q selected * reward| := le_abs_self _
          _ = |q selected| * |reward| := abs_mul _ _
          _ <= |q selected| :=
            mul_le_of_le_one_right (abs_nonneg _) hrewardSelected
    exact Integrable.of_bound hexpMeasurable (Real.exp |q selected|)
      hexpBound
  have hcompProdIntegrable : Integrable
      (fun pair : Action × Real => Real.exp (q pair.1 * pair.2))
      ((historyAlgorithm initialTheta eta).initialAction ⊗ₘ
        (environment.at env).initialFeedback) := by
    apply (Measure.integrable_compProd_iff
      hfullMeas.aestronglyMeasurable).2
    constructor
    · exact Filter.Eventually.of_forall hfiberIntegrable
    · change Integrable _
        (Exp3.finiteActionMeasure (Finset.univ : Finset Action)
          (softmaxProbability initialTheta))
      rw [Exp3.finiteActionMeasure]
      refine integrable_finset_sum_measure.2 fun selected hselected => ?_
      exact (integrable_dirac (by simp)).smul_measure ENNReal.ofReal_ne_top
  have hfiberBound (selected : Action) :
      integral ((environment.at env).initialFeedback selected)
          (fun reward : Real => Real.exp (q selected * reward)) <=
        1 + q selected * mean selected +
          q selected ^ 2 / 2 * sourceC (|q selected| / 2) := by
    have hEqEight :=
      integral_exp_mul_le_sourceEqEight_of_ae_abs_le_one
        ((environment.at env).initialFeedback selected) (q selected) id
        measurable_id.aestronglyMeasurable (hrewardAt selected)
    have hmeanId :
        (∫ reward : Real, reward
          ∂(environment.at env).initialFeedback selected) = mean selected := by
      simpa only [id_eq] using hmeanAt selected
    simp only [id_eq] at hEqEight
    rw [hmeanId] at hEqEight
    exact hEqEight
  rw [Thompson.measurableEnvironmentInitialPairKernel_apply]
  calc
    integral
        ((historyAlgorithm initialTheta eta).initialAction ⊗ₘ
          (environment.at env).initialFeedback)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) =
      integral (historyAlgorithm initialTheta eta).initialAction
        (fun selected =>
          integral ((environment.at env).initialFeedback selected)
            (fun reward : Real => Real.exp (q selected * reward))) :=
        Measure.integral_compProd hcompProdIntegrable
    _ = ∑ selected, softmaxProbability initialTheta selected *
          integral ((environment.at env).initialFeedback selected)
            (fun reward : Real => Real.exp (q selected * reward)) := by
        change integral
          (Exp3.finiteActionMeasure (Finset.univ : Finset Action)
            (softmaxProbability initialTheta)) _ = _
        rw [Exp3.integral_finiteActionMeasure_eq_sum
          (Finset.univ : Finset Action) (softmaxProbability initialTheta)
          (softmaxFiniteActionDistribution initialTheta)]
    _ <= ∑ selected, softmaxProbability initialTheta selected *
          (1 + q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        exact Finset.sum_le_sum fun selected _ =>
          mul_le_mul_of_nonneg_left (hfiberBound selected)
            (softmaxProbability_nonneg initialTheta selected)
    _ = (∑ selected, softmaxProbability initialTheta selected) +
        ∑ selected, softmaxProbability initialTheta selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        rw [← Finset.sum_add_distrib]
        apply Finset.sum_congr rfl
        intro selected _
        ring
    _ = 1 + ∑ selected, softmaxProbability initialTheta selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        rw [softmaxProbability_sum initialTheta]

/--
Action-dependent Equation (8) under the actual generated SGB history-step
kernel.  The real reward coordinate is measurable by construction, so the
only reward-law premise needed beyond the Markov-kernel contract is its
almost-sure source support in `[-1, 1]`.

Source-time fence: `historyParameter initialTheta eta n history` has already
consumed trace pairs `0, ..., n`, so it is source `theta_{n+2}`.  This
successor kernel samples source round `n+2`; consuming its new pair produces
`theta_{n+3}`.  Consequently it does not replace the initial-pair bridge above
when assembling a recurrence that begins at source `t = 1`.

For the later `Fin 2` consumer with best-arm probability `p`, the positive
recurrence instantiates this generic coefficient by
`q 0 = 2 * eta * (1 - p)` and `q 1 = -2 * eta * p`; the inverse-odds
recurrence uses the pointwise negation.  Those recurrence simplifications are
deliberately left to the next layer.
-/
theorem integral_historyStepKernel_exp_actionReward_le_sourceEqEight
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.HistoryEnvironment Action Real)
    (n : Nat) (history : History.FinitePairHistory Action Real n)
    (q : Action -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1) :
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) <=
      1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
  let theta := historyParameter initialTheta eta n history
  let prob := softmaxProbability theta
  have hq : Measurable q := measurable_of_finite q
  have hfullMeas : Measurable
      (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) :=
    Real.measurable_exp.comp
      ((hq.comp measurable_fst).mul measurable_snd)
  have hfiberIntegrable (selected : Action) : Integrable
      (fun reward : Real => Real.exp (q selected * reward))
      (environment.feedback n (history, selected)) := by
    have hexpMeasurable : AEStronglyMeasurable
        (fun reward : Real => Real.exp (q selected * reward))
        (environment.feedback n (history, selected)) :=
      (Real.measurable_exp.comp
        (measurable_const.mul measurable_id)).aestronglyMeasurable
    have hexpBound : ∀ᵐ reward
        ∂environment.feedback n (history, selected),
        ‖Real.exp (q selected * reward)‖ <= Real.exp |q selected| :=
      (hreward selected).mono fun reward hrewardSelected => by
        rw [Real.norm_eq_abs, abs_of_pos (Real.exp_pos _), Real.exp_le_exp]
        calc
          q selected * reward <= |q selected * reward| := le_abs_self _
          _ = |q selected| * |reward| := abs_mul _ _
          _ <= |q selected| :=
            mul_le_of_le_one_right (abs_nonneg _) hrewardSelected
    exact Integrable.of_bound hexpMeasurable (Real.exp |q selected|)
      hexpBound
  have hcompProdIntegrable : Integrable
      (fun pair : Action × Real => Real.exp (q pair.1 * pair.2))
      (((historyAlgorithm initialTheta eta).policy n history) ⊗ₘ
        (environment.feedback n).sectR history) := by
    apply (Measure.integrable_compProd_iff
      hfullMeas.aestronglyMeasurable).2
    constructor
    · exact Filter.Eventually.of_forall fun selected => by
        simpa using hfiberIntegrable selected
    · rw [historyAlgorithm_policy, Exp3.finiteActionKernel_apply]
      rw [Exp3.finiteActionMeasure]
      refine integrable_finset_sum_measure.2 fun selected hselected => ?_
      exact (integrable_dirac (by simp)).smul_measure ENNReal.ofReal_ne_top
  have hfiberBound (selected : Action) :
      integral (environment.feedback n (history, selected))
          (fun reward : Real => Real.exp (q selected * reward)) <=
        1 + q selected *
            integral (environment.feedback n (history, selected)) id +
          q selected ^ 2 / 2 * sourceC (|q selected| / 2) := by
    exact integral_exp_mul_le_sourceEqEight_of_ae_abs_le_one
      (environment.feedback n (history, selected)) (q selected) id
      measurable_id.aestronglyMeasurable (hreward selected)
  calc
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) =
      integral ((historyAlgorithm initialTheta eta).policy n history)
        (fun selected =>
          integral (environment.feedback n (history, selected))
            (fun reward : Real => Real.exp (q selected * reward))) := by
        rw [Thompson.historyStepKernel,
          ProbabilityTheory.Kernel.compProd_apply_eq_compProd_sectR]
        exact Measure.integral_compProd hcompProdIntegrable
    _ = ∑ selected, prob selected *
          integral (environment.feedback n (history, selected))
            (fun reward : Real => Real.exp (q selected * reward)) := by
        rw [historyAlgorithm_policy, Exp3.finiteActionKernel_apply,
          Exp3.integral_finiteActionMeasure_eq_sum
            (Finset.univ : Finset Action) prob
            (softmaxFiniteActionDistribution theta)]
    _ <= ∑ selected, prob selected *
          (1 + q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        exact Finset.sum_le_sum fun selected _ =>
          mul_le_mul_of_nonneg_left (hfiberBound selected)
            (softmaxProbability_nonneg theta selected)
    _ = (∑ selected, prob selected) + ∑ selected, prob selected *
          (q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        rw [← Finset.sum_add_distrib]
        apply Finset.sum_congr rfl
        intro selected _
        ring
    _ = 1 + ∑ selected, prob selected *
          (q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        rw [show (∑ selected, prob selected) = 1 by
          exact softmaxProbability_sum theta]
    _ = 1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        rfl

/-- Mean-surface form of the generated action-dependent Equation-(8) bound. -/
theorem integral_historyStepKernel_exp_actionReward_le_sourceEqEight_of_mean
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.HistoryEnvironment Action Real)
    (n : Nat) (history : History.FinitePairHistory Action Real n)
    (q mean : Action -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected) :
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) <=
      1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
  have hbound :=
    integral_historyStepKernel_exp_actionReward_le_sourceEqEight
      initialTheta eta environment n history q hreward
  calc
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) <=
      1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected *
              integral (environment.feedback n (history, selected)) id +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := hbound
    _ = 1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
        apply congrArg (fun value : Real => 1 + value)
        apply Finset.sum_congr rfl
        intro selected _
        rw [hmean selected]

/--
Environment-indexed wrapper over the jointly measurable feedback kernel used
by the canonical generated trajectory.
-/
theorem integral_measurableEnvironmentHistoryStepKernel_exp_actionReward_le_sourceEqEight_of_mean
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) (env : Env)
    (history : History.FinitePairHistory Action Real n)
    (q mean : Action -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (env, (history, selected)),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (env, (history, selected))) id =
        mean selected) :
    integral
        (Thompson.measurableEnvironmentHistoryStepKernel
          (historyAlgorithm initialTheta eta) environment n (env, history))
        (fun pair : Action × Real => Real.exp (q pair.1 * pair.2)) <=
      1 + ∑ selected,
        softmaxProbability (historyParameter initialTheta eta n history)
            selected *
          (q selected * mean selected +
            q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
  rw [Thompson.measurableEnvironmentHistoryStepKernel_apply]
  apply integral_historyStepKernel_exp_actionReward_le_sourceEqEight_of_mean
    initialTheta eta (environment.at env) n history q mean
  · intro selected
    simpa [Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hreward selected
  · intro selected
    simpa [Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hmean selected

end

end StochasticGradientBandit
end BanditRLProof
