import BanditRLProof.Algorithms.StochasticGradientBanditConditionalExponentialAudit

/-!
# Two-arm stochastic-gradient-bandit one-step recurrences

This module instantiates the generated conditional Equation (8) at the two
action-dependent coefficients used in the proof of Theorem 1 of
Baudry--Johnson--Vary--Pike-Burke--Rebeschini (NeurIPS 2025).  It proves both
one-step exponential recurrences over the actual generated history-step
kernel, under the source initialization `theta = 0`.

Time fence: a value
`historyParameter (fun _ : Fin 2 => 0) eta n history` is the source parameter
`theta_{.,n+2}` after the inclusive history through Lean time `n`.  The
successor expressions below add the update generated by the next pair, and
therefore represent `theta_{.,n+3}`.  They do not consume that pair twice.

Probability / Equation-(8) ledger:

* the one-step random object is the `(selected action, reward)` pair drawn
  from `Thompson.historyStepKernel` at the fixed generated history;
* no independence premise is used: the reward law is already conditioned on
  both the history and selected action;
* `hmean` fixes the two conditional reward means, and `hgap` identifies their
  difference with `Delta`;
* `hreward` gives the exact source support contract `|reward| <= 1` almost
  everywhere on each action fiber;
* measurability and integrability of the exponential are discharged inside
  `integral_historyStepKernel_exp_actionReward_le_sourceEqEight_of_mean`;
* `sourceC_mono` replaces the branch constants
  `sourceC (eta * p)` and `sourceC (eta * (1-p))` by the common `sourceC eta`.

The final declarations are conditional one-step recurrences.  They do not
yet provide the initial/base expectation, tower-property iteration, failure
mass summation, or the finite-horizon regret theorem.
-/

namespace BanditRLProof
namespace StochasticGradientBandit

open MeasureTheory ProbabilityTheory
open scoped BigOperators ProbabilityTheory

noncomputable section

/-- The action-dependent coefficient in the forward exponential potential.
For source arm `1` (Lean arm `0`) it is `2 eta (1-p)`; for source arm `2`
(Lean arm `1`) it is `-2 eta p`. -/
def twoArmForwardQ (eta : Real) (prob : Fin 2 -> Real)
    (selected : Fin 2) : Real :=
  if selected = 0 then 2 * eta * (1 - prob 0) else -(2 * eta * prob 0)

/-- The coefficient for the inverse-odds exponential potential. -/
def twoArmInverseQ (eta : Real) (prob : Fin 2 -> Real)
    (selected : Fin 2) : Real :=
  -twoArmForwardQ eta prob selected

/-- `q_+ reward` is exactly twice the learning-rate-scaled best-coordinate
source update. -/
theorem twoArmForwardQ_mul_reward_eq_sourceIncrement
    (eta reward : Real) (prob : Fin 2 -> Real) (selected : Fin 2) :
    twoArmForwardQ eta prob selected * reward =
      2 * eta * sourceIncrement prob reward selected 0 := by
  fin_cases selected <;> simp [twoArmForwardQ, sourceIncrement] <;> ring

/-- `q_- reward` is the negative of twice the learning-rate-scaled
best-coordinate source update. -/
theorem twoArmInverseQ_mul_reward_eq_sourceIncrement
    (eta reward : Real) (prob : Fin 2 -> Real) (selected : Fin 2) :
    twoArmInverseQ eta prob selected * reward =
      -2 * eta * sourceIncrement prob reward selected 0 := by
  rw [twoArmInverseQ, neg_mul,
    twoArmForwardQ_mul_reward_eq_sourceIncrement]
  ring

/-- The two-branch Equation-(8) remainder for the forward potential, after
replacing both branch constants by the common source constant `C_eta`. -/
theorem twoArmForwardEqEightRemainder_le
    (eta p meanZero meanOne Delta : Real)
    (heta : 0 <= eta) (hp_nonneg : 0 <= p) (hp_le_one : p <= 1)
    (hgap : meanZero - meanOne = Delta) :
    p *
          ((2 * eta * (1 - p)) * meanZero +
            (2 * eta * (1 - p)) ^ 2 / 2 *
              sourceC (|2 * eta * (1 - p)| / 2)) +
        (1 - p) *
          ((-(2 * eta * p)) * meanOne +
            (-(2 * eta * p)) ^ 2 / 2 *
              sourceC (|-(2 * eta * p)| / 2)) <=
      2 * p * (1 - p) * (eta * Delta + eta ^ 2 * sourceC eta) := by
  have hfail_nonneg : 0 <= 1 - p := sub_nonneg.mpr hp_le_one
  have hfail_le_one : 1 - p <= 1 := by linarith
  have hqZero_nonneg : 0 <= 2 * eta * (1 - p) := by positivity
  have hqOneAbs_nonneg : 0 <= 2 * eta * p := by positivity
  have habsZero : |2 * eta * (1 - p)| / 2 = eta * (1 - p) := by
    rw [abs_of_nonneg hqZero_nonneg]
    ring
  have habsOne : |-(2 * eta * p)| / 2 = eta * p := by
    rw [abs_neg, abs_of_nonneg hqOneAbs_nonneg]
    ring
  have hCZero : sourceC (eta * (1 - p)) <= sourceC eta :=
    sourceC_mono (mul_nonneg heta hfail_nonneg)
      (mul_le_of_le_one_right heta hfail_le_one)
  have hCOne : sourceC (eta * p) <= sourceC eta :=
    sourceC_mono (mul_nonneg heta hp_nonneg)
      (mul_le_of_le_one_right heta hp_le_one)
  have htailZero :
      (2 * eta * (1 - p)) ^ 2 / 2 *
          sourceC (|2 * eta * (1 - p)| / 2) <=
        (2 * eta * (1 - p)) ^ 2 / 2 * sourceC eta := by
    rw [habsZero]
    exact mul_le_mul_of_nonneg_left hCZero (by positivity)
  have htailOne :
      (-(2 * eta * p)) ^ 2 / 2 *
          sourceC (|-(2 * eta * p)| / 2) <=
        (-(2 * eta * p)) ^ 2 / 2 * sourceC eta := by
    rw [habsOne]
    exact mul_le_mul_of_nonneg_left hCOne (by positivity)
  have hbranchZero :
      p *
          ((2 * eta * (1 - p)) * meanZero +
            (2 * eta * (1 - p)) ^ 2 / 2 *
              sourceC (|2 * eta * (1 - p)| / 2)) <=
        p *
          ((2 * eta * (1 - p)) * meanZero +
            (2 * eta * (1 - p)) ^ 2 / 2 * sourceC eta) :=
    mul_le_mul_of_nonneg_left
      (add_le_add_right htailZero _) hp_nonneg
  have hbranchOne :
      (1 - p) *
          ((-(2 * eta * p)) * meanOne +
            (-(2 * eta * p)) ^ 2 / 2 *
              sourceC (|-(2 * eta * p)| / 2)) <=
        (1 - p) *
          ((-(2 * eta * p)) * meanOne +
            (-(2 * eta * p)) ^ 2 / 2 * sourceC eta) :=
    mul_le_mul_of_nonneg_left
      (add_le_add_right htailOne _) hfail_nonneg
  calc
    p *
          ((2 * eta * (1 - p)) * meanZero +
            (2 * eta * (1 - p)) ^ 2 / 2 *
              sourceC (|2 * eta * (1 - p)| / 2)) +
        (1 - p) *
          ((-(2 * eta * p)) * meanOne +
            (-(2 * eta * p)) ^ 2 / 2 *
              sourceC (|-(2 * eta * p)| / 2)) <=
      p *
          ((2 * eta * (1 - p)) * meanZero +
            (2 * eta * (1 - p)) ^ 2 / 2 * sourceC eta) +
        (1 - p) *
          ((-(2 * eta * p)) * meanOne +
            (-(2 * eta * p)) ^ 2 / 2 * sourceC eta) :=
      add_le_add hbranchZero hbranchOne
    _ = 2 * p * (1 - p) *
        (eta * Delta + eta ^ 2 * sourceC eta) := by
      have hmeanZero : meanZero = Delta + meanOne := by linarith
      rw [hmeanZero]
      ring

/-- The analogous Equation-(8) remainder for the inverse potential. -/
theorem twoArmInverseEqEightRemainder_le
    (eta p meanZero meanOne Delta : Real)
    (heta : 0 <= eta) (hp_nonneg : 0 <= p) (hp_le_one : p <= 1)
    (hgap : meanZero - meanOne = Delta) :
    p *
          ((-(2 * eta * (1 - p))) * meanZero +
            (-(2 * eta * (1 - p))) ^ 2 / 2 *
              sourceC (|-(2 * eta * (1 - p))| / 2)) +
        (1 - p) *
          ((2 * eta * p) * meanOne +
            (2 * eta * p) ^ 2 / 2 *
              sourceC (|2 * eta * p| / 2)) <=
      -2 * eta * p * (1 - p) * (Delta - eta * sourceC eta) := by
  have hfail_nonneg : 0 <= 1 - p := sub_nonneg.mpr hp_le_one
  have hfail_le_one : 1 - p <= 1 := by linarith
  have hqZeroAbs_nonneg : 0 <= 2 * eta * (1 - p) := by positivity
  have hqOne_nonneg : 0 <= 2 * eta * p := by positivity
  have habsZero : |-(2 * eta * (1 - p))| / 2 = eta * (1 - p) := by
    rw [abs_neg, abs_of_nonneg hqZeroAbs_nonneg]
    ring
  have habsOne : |2 * eta * p| / 2 = eta * p := by
    rw [abs_of_nonneg hqOne_nonneg]
    ring
  have hCZero : sourceC (eta * (1 - p)) <= sourceC eta :=
    sourceC_mono (mul_nonneg heta hfail_nonneg)
      (mul_le_of_le_one_right heta hfail_le_one)
  have hCOne : sourceC (eta * p) <= sourceC eta :=
    sourceC_mono (mul_nonneg heta hp_nonneg)
      (mul_le_of_le_one_right heta hp_le_one)
  have htailZero :
      (-(2 * eta * (1 - p))) ^ 2 / 2 *
          sourceC (|-(2 * eta * (1 - p))| / 2) <=
        (-(2 * eta * (1 - p))) ^ 2 / 2 * sourceC eta := by
    rw [habsZero]
    exact mul_le_mul_of_nonneg_left hCZero (by positivity)
  have htailOne :
      (2 * eta * p) ^ 2 / 2 * sourceC (|2 * eta * p| / 2) <=
        (2 * eta * p) ^ 2 / 2 * sourceC eta := by
    rw [habsOne]
    exact mul_le_mul_of_nonneg_left hCOne (by positivity)
  have hbranchZero :
      p *
          ((-(2 * eta * (1 - p))) * meanZero +
            (-(2 * eta * (1 - p))) ^ 2 / 2 *
              sourceC (|-(2 * eta * (1 - p))| / 2)) <=
        p *
          ((-(2 * eta * (1 - p))) * meanZero +
            (-(2 * eta * (1 - p))) ^ 2 / 2 * sourceC eta) :=
    mul_le_mul_of_nonneg_left
      (add_le_add_right htailZero _) hp_nonneg
  have hbranchOne :
      (1 - p) *
          ((2 * eta * p) * meanOne +
            (2 * eta * p) ^ 2 / 2 * sourceC (|2 * eta * p| / 2)) <=
        (1 - p) *
          ((2 * eta * p) * meanOne +
            (2 * eta * p) ^ 2 / 2 * sourceC eta) :=
    mul_le_mul_of_nonneg_left
      (add_le_add_right htailOne _) hfail_nonneg
  calc
    p *
          ((-(2 * eta * (1 - p))) * meanZero +
            (-(2 * eta * (1 - p))) ^ 2 / 2 *
              sourceC (|-(2 * eta * (1 - p))| / 2)) +
        (1 - p) *
          ((2 * eta * p) * meanOne +
            (2 * eta * p) ^ 2 / 2 * sourceC (|2 * eta * p| / 2)) <=
      p *
          ((-(2 * eta * (1 - p))) * meanZero +
            (-(2 * eta * (1 - p))) ^ 2 / 2 * sourceC eta) +
        (1 - p) *
          ((2 * eta * p) * meanOne +
            (2 * eta * p) ^ 2 / 2 * sourceC eta) :=
      add_le_add hbranchZero hbranchOne
    _ = -2 * eta * p * (1 - p) *
        (Delta - eta * sourceC eta) := by
      have hmeanZero : meanZero = Delta + meanOne := by linarith
      rw [hmeanZero]
      ring

/-- Multiplicative forward one-step recurrence at a fixed generated history.
The current parameter is source `theta_{.,n+2}` and the integrand is the
source successor `theta_{1,n+3}`. -/
theorem integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le
    (eta Delta : Real) (heta : 0 <= eta)
    (environment : Thompson.HistoryEnvironment (Fin 2) Real)
    (n : Nat) (history : History.FinitePairHistory (Fin 2) Real n)
    (mean : Fin 2 -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected)
    (hgap : mean 0 - mean 1 = Delta) :
    integral
        (Thompson.historyStepKernel
          (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
        (fun pair : Fin 2 × Real =>
          Real.exp
            (2 *
              (historyParameter (fun _ : Fin 2 => 0) eta n history 0 +
                eta * sourceIncrement
                  (softmaxProbability
                    (historyParameter (fun _ : Fin 2 => 0) eta n history))
                  pair.2 pair.1 0))) <=
      Real.exp
          (2 * historyParameter (fun _ : Fin 2 => 0) eta n history 0) *
        (1 + 2 *
          softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0 *
          (1 - softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0) *
          (eta * Delta + eta ^ 2 * sourceC eta)) := by
  let theta := historyParameter (fun _ : Fin 2 => 0) eta n history
  let prob := softmaxProbability theta
  let q := twoArmForwardQ eta prob
  have hp_nonneg : 0 <= prob 0 := softmaxProbability_nonneg theta 0
  have hp_le_one : prob 0 <= 1 := softmaxProbability_le_one theta 0
  have hEqEight :=
    integral_historyStepKernel_exp_actionReward_le_sourceEqEight_of_mean
      (fun _ : Fin 2 => 0) eta environment n history q mean hreward hmean
  have hrem :
      (∑ selected, prob selected *
        (q selected * mean selected +
          q selected ^ 2 / 2 * sourceC (|q selected| / 2))) <=
        2 * prob 0 * (1 - prob 0) *
          (eta * Delta + eta ^ 2 * sourceC eta) := by
    have hprobOne : prob 1 = 1 - prob 0 := by
      simpa [prob] using softmaxProbability_one_eq_one_sub_zero theta
    simp only [Fin.sum_univ_two]
    rw [hprobOne]
    simpa [q, twoArmForwardQ] using
      twoArmForwardEqEightRemainder_le eta (prob 0)
        (mean 0) (mean 1) Delta heta hp_nonneg hp_le_one hgap
  have hbase :
      integral
          (Thompson.historyStepKernel
            (historyAlgorithm (fun _ : Fin 2 => 0) eta)
              environment n history)
          (fun pair : Fin 2 × Real => Real.exp (q pair.1 * pair.2)) <=
        1 + 2 * prob 0 * (1 - prob 0) *
          (eta * Delta + eta ^ 2 * sourceC eta) := by
    have hEqEight' :
        integral
            (Thompson.historyStepKernel
              (historyAlgorithm (fun _ : Fin 2 => 0) eta)
                environment n history)
            (fun pair : Fin 2 × Real => Real.exp (q pair.1 * pair.2)) <=
          1 + ∑ selected, prob selected *
            (q selected * mean selected +
              q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
      simpa [theta, prob] using hEqEight
    exact hEqEight'.trans (add_le_add_right hrem 1)
  have hexp :
      (fun pair : Fin 2 × Real =>
          Real.exp
            (2 *
              (theta 0 + eta * sourceIncrement prob pair.2 pair.1 0))) =
        (fun pair : Fin 2 × Real =>
          Real.exp (2 * theta 0) * Real.exp (q pair.1 * pair.2)) := by
    funext pair
    rw [← Real.exp_add]
    apply congrArg Real.exp
    rw [twoArmForwardQ_mul_reward_eq_sourceIncrement]
    ring
  change integral
      (Thompson.historyStepKernel
        (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
      (fun pair : Fin 2 × Real =>
        Real.exp
          (2 * (theta 0 + eta * sourceIncrement prob pair.2 pair.1 0))) <= _
  rw [hexp, integral_const_mul]
  exact mul_le_mul_of_nonneg_left hbase (Real.exp_nonneg _)

/-- Forward recurrence in the additive source form
`E_t exp(2 theta_{1,t+1}) <= exp(2 theta_{1,t})
  + 2 p_t^2 (eta Delta + eta^2 C_eta)`. -/
theorem integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le_add_success_sq
    (eta Delta : Real) (heta : 0 <= eta)
    (environment : Thompson.HistoryEnvironment (Fin 2) Real)
    (n : Nat) (history : History.FinitePairHistory (Fin 2) Real n)
    (mean : Fin 2 -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected)
    (hgap : mean 0 - mean 1 = Delta) :
    integral
        (Thompson.historyStepKernel
          (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
        (fun pair : Fin 2 × Real =>
          Real.exp
            (2 *
              (historyParameter (fun _ : Fin 2 => 0) eta n history 0 +
                eta * sourceIncrement
                  (softmaxProbability
                    (historyParameter (fun _ : Fin 2 => 0) eta n history))
                  pair.2 pair.1 0))) <=
      Real.exp
          (2 * historyParameter (fun _ : Fin 2 => 0) eta n history 0) +
        2 *
          softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0 ^ 2 *
          (eta * Delta + eta ^ 2 * sourceC eta) := by
  let theta := historyParameter (fun _ : Fin 2 => 0) eta n history
  let p := softmaxProbability theta 0
  have hmul :=
    integral_twoArmHistoryStepKernel_exp_forwardSuccessor_le
      eta Delta heta environment n history mean hreward hmean hgap
  have hodds : Real.exp (2 * theta 0) * (1 - p) = p := by
    simpa [theta, p] using historyParameter_exp_two_mul_zero_eq_odds
      eta n history
  change _ <= Real.exp (2 * theta 0) +
    2 * p ^ 2 * (eta * Delta + eta ^ 2 * sourceC eta)
  calc
    _ <= Real.exp (2 * theta 0) *
        (1 + 2 * p * (1 - p) *
          (eta * Delta + eta ^ 2 * sourceC eta)) := by
      simpa [theta, p] using hmul
    _ = Real.exp (2 * theta 0) +
        2 * p * (Real.exp (2 * theta 0) * (1 - p)) *
          (eta * Delta + eta ^ 2 * sourceC eta) := by ring
    _ = Real.exp (2 * theta 0) +
        2 * p ^ 2 * (eta * Delta + eta ^ 2 * sourceC eta) := by
      rw [hodds]
      ring

/-- Multiplicative inverse-potential one-step recurrence at the same time
fence. -/
theorem integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le
    (eta Delta : Real) (heta : 0 <= eta)
    (environment : Thompson.HistoryEnvironment (Fin 2) Real)
    (n : Nat) (history : History.FinitePairHistory (Fin 2) Real n)
    (mean : Fin 2 -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected)
    (hgap : mean 0 - mean 1 = Delta) :
    integral
        (Thompson.historyStepKernel
          (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
        (fun pair : Fin 2 × Real =>
          Real.exp
            (-2 *
              (historyParameter (fun _ : Fin 2 => 0) eta n history 0 +
                eta * sourceIncrement
                  (softmaxProbability
                    (historyParameter (fun _ : Fin 2 => 0) eta n history))
                  pair.2 pair.1 0))) <=
      Real.exp
          (-2 * historyParameter (fun _ : Fin 2 => 0) eta n history 0) *
        (1 - 2 * eta *
          softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0 *
          (1 - softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0) *
          (Delta - eta * sourceC eta)) := by
  let theta := historyParameter (fun _ : Fin 2 => 0) eta n history
  let prob := softmaxProbability theta
  let q := twoArmInverseQ eta prob
  have hp_nonneg : 0 <= prob 0 := softmaxProbability_nonneg theta 0
  have hp_le_one : prob 0 <= 1 := softmaxProbability_le_one theta 0
  have hEqEight :=
    integral_historyStepKernel_exp_actionReward_le_sourceEqEight_of_mean
      (fun _ : Fin 2 => 0) eta environment n history q mean hreward hmean
  have hrem :
      (∑ selected, prob selected *
        (q selected * mean selected +
          q selected ^ 2 / 2 * sourceC (|q selected| / 2))) <=
        -2 * eta * prob 0 * (1 - prob 0) *
          (Delta - eta * sourceC eta) := by
    have hprobOne : prob 1 = 1 - prob 0 := by
      simpa [prob] using softmaxProbability_one_eq_one_sub_zero theta
    simp only [Fin.sum_univ_two]
    rw [hprobOne]
    simpa [q, twoArmInverseQ, twoArmForwardQ] using
      twoArmInverseEqEightRemainder_le eta (prob 0)
        (mean 0) (mean 1) Delta heta hp_nonneg hp_le_one hgap
  have hbase :
      integral
          (Thompson.historyStepKernel
            (historyAlgorithm (fun _ : Fin 2 => 0) eta)
              environment n history)
          (fun pair : Fin 2 × Real => Real.exp (q pair.1 * pair.2)) <=
        1 - 2 * eta * prob 0 * (1 - prob 0) *
          (Delta - eta * sourceC eta) := by
    have hEqEight' :
        integral
            (Thompson.historyStepKernel
              (historyAlgorithm (fun _ : Fin 2 => 0) eta)
                environment n history)
            (fun pair : Fin 2 × Real => Real.exp (q pair.1 * pair.2)) <=
          1 + ∑ selected, prob selected *
            (q selected * mean selected +
              q selected ^ 2 / 2 * sourceC (|q selected| / 2)) := by
      simpa [theta, prob] using hEqEight
    have := hEqEight'.trans (add_le_add_right hrem 1)
    calc
      _ <= 1 + -2 * eta * prob 0 * (1 - prob 0) *
          (Delta - eta * sourceC eta) := this
      _ = 1 - 2 * eta * prob 0 * (1 - prob 0) *
          (Delta - eta * sourceC eta) := by ring
  have hexp :
      (fun pair : Fin 2 × Real =>
          Real.exp
            (-2 *
              (theta 0 + eta * sourceIncrement prob pair.2 pair.1 0))) =
        (fun pair : Fin 2 × Real =>
          Real.exp (-2 * theta 0) * Real.exp (q pair.1 * pair.2)) := by
    funext pair
    rw [← Real.exp_add]
    apply congrArg Real.exp
    rw [twoArmInverseQ_mul_reward_eq_sourceIncrement]
    ring
  change integral
      (Thompson.historyStepKernel
        (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
      (fun pair : Fin 2 × Real =>
        Real.exp
          (-2 * (theta 0 + eta * sourceIncrement prob pair.2 pair.1 0))) <= _
  rw [hexp, integral_const_mul]
  exact mul_le_mul_of_nonneg_left hbase (Real.exp_nonneg _)

/-- Inverse recurrence in the source telescoping form
`E_t exp(-2 theta_{1,t+1}) <= exp(-2 theta_{1,t})
  - 2 eta (1-p_t)^2 (Delta-eta C_eta)`. -/
theorem integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le_sub_failure_sq
    (eta Delta : Real) (heta : 0 <= eta)
    (environment : Thompson.HistoryEnvironment (Fin 2) Real)
    (n : Nat) (history : History.FinitePairHistory (Fin 2) Real n)
    (mean : Fin 2 -> Real)
    (hreward : forall selected,
      ∀ᵐ reward ∂environment.feedback n (history, selected),
        |reward| <= 1)
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected)
    (hgap : mean 0 - mean 1 = Delta) :
    integral
        (Thompson.historyStepKernel
          (historyAlgorithm (fun _ : Fin 2 => 0) eta) environment n history)
        (fun pair : Fin 2 × Real =>
          Real.exp
            (-2 *
              (historyParameter (fun _ : Fin 2 => 0) eta n history 0 +
                eta * sourceIncrement
                  (softmaxProbability
                    (historyParameter (fun _ : Fin 2 => 0) eta n history))
                  pair.2 pair.1 0))) <=
      Real.exp
          (-2 * historyParameter (fun _ : Fin 2 => 0) eta n history 0) -
        2 * eta *
          (1 - softmaxProbability
              (historyParameter (fun _ : Fin 2 => 0) eta n history) 0) ^ 2 *
          (Delta - eta * sourceC eta) := by
  let theta := historyParameter (fun _ : Fin 2 => 0) eta n history
  let p := softmaxProbability theta 0
  have hmul :=
    integral_twoArmHistoryStepKernel_exp_inverseSuccessor_le
      eta Delta heta environment n history mean hreward hmean hgap
  have hinverseOdds : Real.exp (-2 * theta 0) * p = 1 - p := by
    exact exp_neg_two_mul_zero_mul_softmaxProbability_zero theta
      (historyParameter_zeroInitialization_sum eta n history)
  change _ <= Real.exp (-2 * theta 0) -
    2 * eta * (1 - p) ^ 2 * (Delta - eta * sourceC eta)
  calc
    _ <= Real.exp (-2 * theta 0) *
        (1 - 2 * eta * p * (1 - p) *
          (Delta - eta * sourceC eta)) := by
      simpa [theta, p] using hmul
    _ = Real.exp (-2 * theta 0) -
        2 * eta * (Real.exp (-2 * theta 0) * p) * (1 - p) *
          (Delta - eta * sourceC eta) := by ring
    _ = Real.exp (-2 * theta 0) -
        2 * eta * (1 - p) ^ 2 * (Delta - eta * sourceC eta) := by
      rw [hinverseOdds]
      ring

end

end StochasticGradientBandit
end BanditRLProof
