import BanditRLProof.Algorithms.StochasticGradientBanditAudit
import BanditRLProof.Exp3PredictableMoments

/-!
# Generated stochastic-gradient-bandit trajectory audit

This module lifts the finite Algorithm-1 / Equation-(5) algebra in
`StochasticGradientBanditAudit` to the repository's canonical measurable
action/reward trajectory.  It constructs the recursive parameter vector,
packages its softmax law as a history algorithm, and identifies the generated
successor action and pair conditional laws.

The learning-rate thresholds, failure events, and regret-rate conclusions of
the source paper remain outside this process-level audit.
-/

namespace BanditRLProof
namespace StochasticGradientBandit

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal ProbabilityTheory

noncomputable section

universe u v

variable {Action : Type u}

/-- Coordinate measurability of the source softmax transform. -/
theorem measurable_softmaxProbability
    [Fintype Action]
    {History : Type*} [MeasurableSpace History]
    (theta : History -> Action -> Real)
    (htheta : forall action, Measurable (fun history => theta history action))
    (action : Action) :
    Measurable (fun history => softmaxProbability (theta history) action) := by
  unfold softmaxProbability softmaxDenominator
  exact (Real.measurable_exp.comp (htheta action)).div
    (Finset.measurable_sum Finset.univ fun candidate _ =>
      Real.measurable_exp.comp (htheta candidate))

/-- Measurability of one Algorithm-1 coordinate update. -/
theorem measurable_sourceIncrement
    [MeasurableSpace Action] [MeasurableSingletonClass Action]
    [DecidableEq Action]
    {History : Type*} [MeasurableSpace History]
    (prob : History -> Action -> Real)
    (reward : History -> Real) (selected : History -> Action)
    (coordinate : Action)
    (hprob : Measurable (fun history => prob history coordinate))
    (hreward : Measurable reward) (hselected : Measurable selected) :
    Measurable (fun history =>
      sourceIncrement (prob history) (reward history)
        (selected history) coordinate) := by
  unfold sourceIncrement
  refine Measurable.ite ?_ ((measurable_const.sub hprob).mul hreward)
    ((hprob.mul hreward).neg)
  simpa only [Set.mem_setOf_eq] using
    hselected (measurableSet_singleton coordinate)

/--
The Algorithm-1 parameter vector after an inclusive finite action/reward
history.  At round zero the first observed pair updates `initialTheta`; every
successor uses the softmax vector generated by the preceding inclusive prefix.
-/
noncomputable def historyParameter
    [Fintype Action] [DecidableEq Action]
    (initialTheta : Action -> Real) (eta : Real) :
    (n : Nat) -> History.FinitePairHistory Action Real n -> Action -> Real
  | 0, history, coordinate =>
      initialTheta coordinate + eta *
        sourceIncrement (softmaxProbability initialTheta)
          (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).2
          (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).1 coordinate
  | n + 1, history, coordinate =>
      let previous := Exp3.previousPairHistory history
      historyParameter initialTheta eta n previous coordinate + eta *
        sourceIncrement
          (softmaxProbability (historyParameter initialTheta eta n previous))
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).2
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).1 coordinate

@[simp]
theorem historyParameter_zero
    [Fintype Action] [DecidableEq Action]
    (initialTheta : Action -> Real) (eta : Real)
    (history : History.FinitePairHistory Action Real 0)
    (coordinate : Action) :
    historyParameter initialTheta eta 0 history coordinate =
      initialTheta coordinate + eta *
        sourceIncrement (softmaxProbability initialTheta)
          (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).2
          (history ⟨0, Finset.mem_Iic.mpr le_rfl⟩).1 coordinate :=
  rfl

@[simp]
theorem historyParameter_succ
    [Fintype Action] [DecidableEq Action]
    (initialTheta : Action -> Real) (eta : Real) (n : Nat)
    (history : History.FinitePairHistory Action Real (n + 1))
    (coordinate : Action) :
    historyParameter initialTheta eta (n + 1) history coordinate =
      historyParameter initialTheta eta n
          (Exp3.previousPairHistory history) coordinate + eta *
        sourceIncrement
          (softmaxProbability
            (historyParameter initialTheta eta n
              (Exp3.previousPairHistory history)))
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).2
          (history ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩).1 coordinate :=
  rfl

variable [MeasurableSpace Action] [MeasurableSingletonClass Action]
  [Fintype Action] [DecidableEq Action]

/-- Every recursive parameter coordinate is measurable in the finite history. -/
theorem measurable_historyParameter
    (initialTheta : Action -> Real) (eta : Real) :
    forall n coordinate,
      Measurable (fun history : History.FinitePairHistory Action Real n =>
        historyParameter initialTheta eta n history coordinate) := by
  intro n
  induction n with
  | zero =>
      intro coordinate
      let zeroIndex : Finset.Iic 0 :=
        ⟨0, Finset.mem_Iic.mpr le_rfl⟩
      have hselected : Measurable
          (fun history : History.FinitePairHistory Action Real 0 =>
            (history zeroIndex).1) :=
        measurable_fst.comp (measurable_pi_apply zeroIndex)
      have hreward : Measurable
          (fun history : History.FinitePairHistory Action Real 0 =>
            (history zeroIndex).2) :=
        measurable_snd.comp (measurable_pi_apply zeroIndex)
      exact measurable_const.add (measurable_const.mul
        (measurable_sourceIncrement
          (fun _history : History.FinitePairHistory Action Real 0 =>
            softmaxProbability initialTheta)
          (fun history => (history zeroIndex).2)
          (fun history => (history zeroIndex).1)
          coordinate measurable_const hreward hselected))
  | succ n ih =>
      intro coordinate
      let lastIndex : Finset.Iic (n + 1) :=
        ⟨n + 1, Finset.mem_Iic.mpr le_rfl⟩
      have hprevious : Measurable
          (Exp3.previousPairHistory (Action := Action) (n := n)) :=
        Exp3.measurable_previousPairHistory
      have hstate : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            historyParameter initialTheta eta n
              (Exp3.previousPairHistory history) coordinate) :=
        (ih coordinate).comp hprevious
      have hprob : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            softmaxProbability
              (historyParameter initialTheta eta n
                (Exp3.previousPairHistory history)) coordinate) :=
        (measurable_softmaxProbability
          (fun previous : History.FinitePairHistory Action Real n =>
            historyParameter initialTheta eta n previous)
          ih coordinate).comp hprevious
      have hselected : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            (history lastIndex).1) :=
        measurable_fst.comp (measurable_pi_apply lastIndex)
      have hreward : Measurable
          (fun history : History.FinitePairHistory Action Real (n + 1) =>
            (history lastIndex).2) :=
        measurable_snd.comp (measurable_pi_apply lastIndex)
      exact hstate.add (measurable_const.mul
        (measurable_sourceIncrement
          (fun history => softmaxProbability
            (historyParameter initialTheta eta n
              (Exp3.previousPairHistory history)))
          (fun history => (history lastIndex).2)
          (fun history => (history lastIndex).1)
          coordinate hprob hreward hselected))

variable [Nonempty Action]

/-- The source softmax vector as a finite probability distribution on all actions. -/
def softmaxFiniteActionDistribution (theta : Action -> Real) :
    Exp3.FiniteActionDistribution (Finset.univ : Finset Action)
      (softmaxProbability theta) where
  nonneg action _ := softmaxProbability_nonneg theta action
  sum_eq_one := softmaxProbability_sum theta

/-- Measurable softmax policy generated from the recursive SGB state. -/
def historySoftmaxDistributionSource
    (initialTheta : Action -> Real) (eta : Real) (n : Nat) :
    Exp3.MeasurableFiniteActionDistribution (Finset.univ : Finset Action)
      (fun history : History.FinitePairHistory Action Real n =>
        softmaxProbability (historyParameter initialTheta eta n history)) where
  distribution history :=
    softmaxFiniteActionDistribution
      (historyParameter initialTheta eta n history)
  measurable_prob action _ :=
    measurable_softmaxProbability
      (fun history : History.FinitePairHistory Action Real n =>
        historyParameter initialTheta eta n history)
      (measurable_historyParameter initialTheta eta n) action

/-- The recursive stochastic-gradient-bandit history policy. -/
noncomputable def historyAlgorithm
    (initialTheta : Action -> Real) (eta : Real) :
    Thompson.HistoryAlgorithm Action Real where
  policy n := Exp3.finiteActionKernel (Finset.univ : Finset Action)
    (fun history =>
      softmaxProbability (historyParameter initialTheta eta n history))
    (historySoftmaxDistributionSource initialTheta eta n)
  policy_isMarkov n := Exp3.instFiniteActionKernelIsMarkovKernel
    (Finset.univ : Finset Action)
    (fun history =>
      softmaxProbability (historyParameter initialTheta eta n history))
    (historySoftmaxDistributionSource initialTheta eta n)
  initialAction := Exp3.finiteActionMeasure (Finset.univ : Finset Action)
    (softmaxProbability initialTheta)
  initialAction_isProbability :=
    Exp3.finiteActionMeasure_isProbabilityMeasure
      (Finset.univ : Finset Action) (softmaxProbability initialTheta)
      (softmaxFiniteActionDistribution initialTheta)

@[simp]
theorem historyAlgorithm_policy
    (initialTheta : Action -> Real) (eta : Real) (n : Nat) :
    (historyAlgorithm initialTheta eta).policy n =
      Exp3.finiteActionKernel (Finset.univ : Finset Action)
        (fun history : History.FinitePairHistory Action Real n =>
          softmaxProbability (historyParameter initialTheta eta n history))
        (historySoftmaxDistributionSource initialTheta eta n) :=
  rfl

/-- Equation (5) for the generated initial action/reward pair law. -/
theorem integral_measurableEnvironmentInitialPairKernel_sourceIncrement_eq_expectedSourceIncrement
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (env : Env) (mean : Action -> Real) (coordinate : Action)
    (hIntegrable : Integrable
      (fun pair : Action × Real =>
        sourceIncrement (softmaxProbability initialTheta)
          pair.2 pair.1 coordinate)
      (Thompson.measurableEnvironmentInitialPairKernel
        (historyAlgorithm initialTheta eta) environment env))
    (hmean : forall selected,
      integral (environment.initialFeedback (env, selected)) id =
        mean selected) :
    integral
        (Thompson.measurableEnvironmentInitialPairKernel
          (historyAlgorithm initialTheta eta) environment env)
        (fun pair : Action × Real =>
          sourceIncrement (softmaxProbability initialTheta)
            pair.2 pair.1 coordinate) =
      expectedSourceIncrement (softmaxProbability initialTheta)
        mean coordinate := by
  rw [Thompson.measurableEnvironmentInitialPairKernel_apply] at hIntegrable ⊢
  let prob := softmaxProbability initialTheta
  have hmeanAt (selected : Action) :
      (∫ reward : Real, reward
        ∂(environment.at env).initialFeedback selected) = mean selected := by
    simpa only [id_eq, Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hmean selected
  have hinner : forall selected,
      integral ((environment.at env).initialFeedback selected)
          (fun reward => sourceIncrement prob reward selected coordinate) =
        sourceIncrement prob (mean selected) selected coordinate := by
    intro selected
    by_cases hselected : selected = coordinate
    · subst selected
      simp only [sourceIncrement, ite_true]
      rw [integral_const_mul, hmeanAt]
    · simp only [sourceIncrement, if_neg hselected]
      rw [integral_neg, integral_const_mul, hmeanAt]
  calc
    integral
        ((historyAlgorithm initialTheta eta).initialAction ⊗ₘ
          (environment.at env).initialFeedback)
        (fun pair : Action × Real =>
          sourceIncrement prob pair.2 pair.1 coordinate) =
        integral (historyAlgorithm initialTheta eta).initialAction
          (fun selected =>
            integral ((environment.at env).initialFeedback selected)
              (fun reward =>
                sourceIncrement prob reward selected coordinate)) :=
      Measure.integral_compProd hIntegrable
    _ = integral (historyAlgorithm initialTheta eta).initialAction
          (fun selected =>
            sourceIncrement prob (mean selected) selected coordinate) := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall hinner
    _ = ∑ selected,
          prob selected *
            sourceIncrement prob (mean selected) selected coordinate := by
      change integral
          (Exp3.finiteActionMeasure (Finset.univ : Finset Action) prob)
          (fun selected =>
            sourceIncrement prob (mean selected) selected coordinate) = _
      rw [Exp3.integral_finiteActionMeasure_eq_sum
        (Finset.univ : Finset Action) prob
        (softmaxFiniteActionDistribution initialTheta)]
    _ = expectedSourceIncrement prob mean coordinate := by
      rfl

/--
The exact Equation-(5) conditional-kernel calculation at a fixed generated
history.  The reward-law hypotheses expose precisely the two facts used here:
integrability of the source increment and the selected arm's reward mean.
-/
theorem integral_historyStepKernel_sourceIncrement_eq_expectedSourceIncrement
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.HistoryEnvironment Action Real)
    (n : Nat) (history : History.FinitePairHistory Action Real n)
    (mean : Action -> Real) (coordinate : Action)
    (hIntegrable : Integrable
      (fun pair : Action × Real =>
        sourceIncrement
          (softmaxProbability (historyParameter initialTheta eta n history))
          pair.2 pair.1 coordinate)
      (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
        environment n history))
    (hmean : forall selected,
      integral (environment.feedback n (history, selected)) id =
        mean selected) :
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real =>
          sourceIncrement
            (softmaxProbability (historyParameter initialTheta eta n history))
            pair.2 pair.1 coordinate) =
      expectedSourceIncrement
        (softmaxProbability (historyParameter initialTheta eta n history))
        mean coordinate := by
  let prob :=
    softmaxProbability (historyParameter initialTheta eta n history)
  have hmeanId (selected : Action) :
      (∫ reward : Real, reward
        ∂environment.feedback n (history, selected)) = mean selected := by
    simpa only [id_eq] using hmean selected
  have hinner : forall selected,
      integral (environment.feedback n (history, selected))
          (fun reward => sourceIncrement prob reward selected coordinate) =
        sourceIncrement prob (mean selected) selected coordinate := by
    intro selected
    by_cases hselected : selected = coordinate
    · subst selected
      simp only [sourceIncrement, ite_true]
      rw [integral_const_mul, hmeanId]
    · simp only [sourceIncrement, if_neg hselected]
      rw [integral_neg, integral_const_mul, hmeanId]
  have hIntegrable' : Integrable
      (fun pair : Action × Real =>
        sourceIncrement prob pair.2 pair.1 coordinate)
      (((historyAlgorithm initialTheta eta).policy n history) ⊗ₘ
        (environment.feedback n).sectR history) := by
    simpa [prob, Thompson.historyStepKernel,
      ProbabilityTheory.Kernel.compProd_apply_eq_compProd_sectR] using
      hIntegrable
  calc
    integral
        (Thompson.historyStepKernel (historyAlgorithm initialTheta eta)
          environment n history)
        (fun pair : Action × Real =>
          sourceIncrement prob pair.2 pair.1 coordinate) =
        integral ((historyAlgorithm initialTheta eta).policy n history)
          (fun selected =>
            integral (environment.feedback n (history, selected))
              (fun reward =>
                sourceIncrement prob reward selected coordinate)) := by
      rw [Thompson.historyStepKernel,
        ProbabilityTheory.Kernel.compProd_apply_eq_compProd_sectR]
      exact Measure.integral_compProd hIntegrable'
    _ = integral ((historyAlgorithm initialTheta eta).policy n history)
          (fun selected =>
            sourceIncrement prob (mean selected) selected coordinate) := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall hinner
    _ = ∑ selected,
          prob selected *
            sourceIncrement prob (mean selected) selected coordinate := by
      rw [historyAlgorithm_policy, Exp3.finiteActionKernel_apply,
        Exp3.integral_finiteActionMeasure_eq_sum
          (Finset.univ : Finset Action) prob
          (softmaxFiniteActionDistribution
            (historyParameter initialTheta eta n history))]
    _ = expectedSourceIncrement prob mean coordinate := by
      rfl

/--
Environment-indexed form of the same conditional-kernel calculation.  This is
the exact kernel that appears on the right-hand side of the generated
trajectory's successor-pair `condDistrib` theorem below.
-/
theorem integral_measurableEnvironmentHistoryStepKernel_sourceIncrement_eq_expectedSourceIncrement
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) (env : Env)
    (history : History.FinitePairHistory Action Real n)
    (mean : Action -> Real) (coordinate : Action)
    (hIntegrable : Integrable
      (fun pair : Action × Real =>
        sourceIncrement
          (softmaxProbability (historyParameter initialTheta eta n history))
          pair.2 pair.1 coordinate)
      (Thompson.measurableEnvironmentHistoryStepKernel
        (historyAlgorithm initialTheta eta) environment n (env, history)))
    (hmean : forall selected,
      integral (environment.feedback n (env, (history, selected))) id =
        mean selected) :
    integral
        (Thompson.measurableEnvironmentHistoryStepKernel
          (historyAlgorithm initialTheta eta) environment n (env, history))
        (fun pair : Action × Real =>
          sourceIncrement
            (softmaxProbability (historyParameter initialTheta eta n history))
            pair.2 pair.1 coordinate) =
      expectedSourceIncrement
        (softmaxProbability (historyParameter initialTheta eta n history))
        mean coordinate := by
  rw [Thompson.measurableEnvironmentHistoryStepKernel_apply]
  apply integral_historyStepKernel_sourceIncrement_eq_expectedSourceIncrement
    initialTheta eta (environment.at env) n history mean coordinate
  · simpa [Thompson.measurableEnvironmentHistoryStepKernel_apply] using
      hIntegrable
  · intro selected
    simpa [Thompson.MeasurableHistoryEnvironment.at,
      ProbabilityTheory.Kernel.comap_apply] using hmean selected

/-- Generated Equation (5), in the source instantaneous-gap coordinates. -/
theorem integral_measurableEnvironmentHistoryStepKernel_sourceIncrement_eq_gapCoordinate
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) (env : Env)
    (history : History.FinitePairHistory Action Real n)
    (mean gap : Action -> Real) (bestMean : Real) (coordinate : Action)
    (hIntegrable : Integrable
      (fun pair : Action × Real =>
        sourceIncrement
          (softmaxProbability (historyParameter initialTheta eta n history))
          pair.2 pair.1 coordinate)
      (Thompson.measurableEnvironmentHistoryStepKernel
        (historyAlgorithm initialTheta eta) environment n (env, history)))
    (hmean : forall selected,
      integral (environment.feedback n (env, (history, selected))) id =
        mean selected)
    (hgap : forall action, gap action = bestMean - mean action) :
    integral
        (Thompson.measurableEnvironmentHistoryStepKernel
          (historyAlgorithm initialTheta eta) environment n (env, history))
        (fun pair : Action × Real =>
          sourceIncrement
            (softmaxProbability (historyParameter initialTheta eta n history))
            pair.2 pair.1 coordinate) =
      softmaxProbability (historyParameter initialTheta eta n history)
          coordinate *
        (instantaneousGap
          (softmaxProbability (historyParameter initialTheta eta n history))
          gap - gap coordinate) := by
  rw [integral_measurableEnvironmentHistoryStepKernel_sourceIncrement_eq_expectedSourceIncrement
    initialTheta eta environment n env history mean coordinate hIntegrable hmean]
  exact expectedSourceIncrement_eq_gapCoordinate
    (softmaxProbability (historyParameter initialTheta eta n history))
    mean gap bestMean coordinate
    (softmaxProbability_sum (historyParameter initialTheta eta n history)) hgap

/-- Canonical generated action/reward trajectory for the recursive SGB policy. -/
noncomputable def trajectoryKernel
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real) :
    Kernel Env ((n : Nat) -> Action × Real) :=
  Thompson.canonicalMeasurableEnvironmentTrajectoryKernel
    (historyAlgorithm initialTheta eta) environment

instance instTrajectoryKernelIsMarkov
    {Env : Type v} [MeasurableSpace Env]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real) :
    IsMarkovKernel (trajectoryKernel initialTheta eta environment) := by
  unfold trajectoryKernel
  infer_instance

/-- The generated initial action follows the initial softmax law given the environment. -/
theorem trajectoryMeasure_condDistrib_action_zero_given_environment
    {Env : Type v} [MeasurableSpace Env]
    [StandardBorelSpace Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.2 0).1)
        (fun sample : Env × ((k : Nat) -> Action × Real) => sample.1)
        (prior ⊗ₘ trajectoryKernel initialTheta eta environment) =ᵐ[
      (prior ⊗ₘ trajectoryKernel initialTheta eta environment).map
        (fun sample : Env × ((k : Nat) -> Action × Real) => sample.1)]
      Kernel.const Env
        (Exp3.finiteActionMeasure (Finset.univ : Finset Action)
          (softmaxProbability initialTheta)) := by
  simpa [trajectoryKernel] using
    (Exp3.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action_zero_given_environment
      prior (historyAlgorithm initialTheta eta) environment)

/-- Every generated successor action has the recursive softmax conditional law. -/
theorem trajectoryMeasure_condDistrib_action
    {Env : Type v} [MeasurableSpace Env] [StandardBorelSpace Env]
    [StandardBorelSpace Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.2 (n + 1)).1)
        (fun sample => Preorder.frestrictLe n sample.2)
        (prior ⊗ₘ trajectoryKernel initialTheta eta environment) =ᵐ[
      (prior ⊗ₘ trajectoryKernel initialTheta eta environment).map
        (fun sample => Preorder.frestrictLe n sample.2)]
      Exp3.finiteActionKernel (Finset.univ : Finset Action)
        (fun history : History.FinitePairHistory Action Real n =>
          softmaxProbability (historyParameter initialTheta eta n history))
        (historySoftmaxDistributionSource initialTheta eta n) := by
  simpa [trajectoryKernel, historyAlgorithm_policy] using
    (Thompson.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_action
      prior (historyAlgorithm initialTheta eta) environment n)

/--
Conditional on the retained environment and visible prefix, the next generated
action/reward pair follows the canonical SGB history-step kernel.
-/
theorem trajectoryMeasure_condDistrib_nextPair_given_environment_prefix
    {Env : Type v} [MeasurableSpace Env] [StandardBorelSpace Env]
    [StandardBorelSpace Action]
    (prior : Measure Env) [IsFiniteMeasure prior]
    (initialTheta : Action -> Real) (eta : Real)
    (environment : Thompson.MeasurableHistoryEnvironment Env Action Real)
    (n : Nat) :
    condDistrib
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          sample.2 (n + 1))
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.1, Preorder.frestrictLe n sample.2))
        (prior ⊗ₘ trajectoryKernel initialTheta eta environment) =ᵐ[
      (prior ⊗ₘ trajectoryKernel initialTheta eta environment).map
        (fun sample : Env × ((k : Nat) -> Action × Real) =>
          (sample.1, Preorder.frestrictLe n sample.2))]
      Thompson.measurableEnvironmentHistoryStepKernel
        (historyAlgorithm initialTheta eta) environment n := by
  simpa [trajectoryKernel] using
    (Exp3.canonicalMeasurableEnvironmentTrajectoryMeasure_condDistrib_nextPair_given_environment_prefix
      prior (historyAlgorithm initialTheta eta) environment n)

end

end StochasticGradientBandit
end BanditRLProof
